### ISSUE TITLE
Second login window popup after acquiring id token

### ISSUE THREAD

**Issue by oh-fv** [AzureAD/microsoft-authentication-library-for-js#484] opened 2018-11-14 15:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 70
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

</code></pre>

## Current behavior
After clicking Sign In in the "MSAL JS quickstart sample", a popup for logging into my Microsoft account appears. After logging in, an id_token is acquired. The sample then proceeds to query the Graph API by calling acquireTokenSilent to acquire an access token. This causes a second login popup to appear, and only after logging in a second time the user data is retrieved from the Graph API.

In Firefox and Edge, a second popup window does not appear.

## Expected behavior

No second popup window for logging in.

## Minimal reproduction of the problem with instructions

Set up the "MSAL JS quickstart sample" by replacing clientID with an app ID and inserting an authority valid for the tenant in the Msal.UserAgentApplication call.

**Comment by nehaagrawal** [comment] 2018-11-16 18:46
@oh-fv You are seeing a second login popup because acquireTokenSilent failed. Did you check why it failed? If AcquireTokenSilent fails, we call acquireTokenRedirect/popup. This is expected behavior. I am closing this issue.

**Closed by nehaagrawal** 2018-11-16 18:46 UTC

**Comment by jeverduzco** [comment] 2019-03-19 23:13
The same happens to me, fails and launches a second popup window but only in chrome 70 or higher
