### ISSUE TITLE
post_request_failed error is thrown when network connection is disabled with MSAL2.17

### ISSUE THREAD

**Issue by rahul-microsoft** [AzureAD/microsoft-authentication-library-for-js#4114] opened 2021-09-30 13:44 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Description

post_request_failed error is thrown when network connection is disabled with MSAL2.17

### Error Message

code: "**post_request_failed**",
desc: "Network request failed: If the browser threw a CORS error, check that the redirectUri is registered in the Azure App Portal as type 'SPA'"

### Msal Logs

NA

### MSAL Configuration

```javascript
{
auth: {
 clientId: "5e3ce6c0-2b1f-4285-8d4b-75ee78787346"
}
}
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

 1. ensure there is no network
 2. call acquireTokenSilent using MSAL2 - this.userAgentApplication.acquireTokenSilent(request)

### Expected Behavior

Error code should be no_network_connectivity 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment] 2021-10-04 18:53
Thanks, we've heard of this happening. We currently check for `window.navigator.onLine` to determine if the user has a network connection and [throw the appropriate error](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0a4e110c6d0a56da38d91ce0b5dea89e3708983b/lib/msal-browser/src/network/FetchClient.ts#L29). I suspect this isn't reporting correctly when you receive the wrong error. We'll see if we can reproduce and potentially improve the network connectivity check

**Comment by tnorling** [comment] 2021-11-23 23:49
Closing as this is due to a [known limitation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) of the browser API that reports network status and there's currently nothing that can be done by MSAL.js to improve the accuracy of network detection.

**Closed by tnorling** 2021-11-23 23:49 UTC
Labels: question, msal-angular, msal-browser, investigate, bug-unconfirmed, answered
