### ISSUE TITLE
Refresh token in chrome extension background

### ISSUE THREAD

**Issue by nichovski** [AzureAD/microsoft-authentication-library-for-js#4682] opened 2022-04-05 17:29 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm working on a chrome extension and using the MSAL library to log in via chrome popup. Everything works great when the library is called from the popup. I have an issue when I'm trying to "acquireTokenSilent" from the background script, the MSAL is throwing: 
Uncaught (in promise) BrowserAuthError: non_browser_environment: Login and token requests are not supported in non-browser environments.

Is there a way how I can get tokens from the background script without opening the popup?

Thanks

### Relevant Code Snippets

```javascript
export async function acquireToken(request) {
    return msalInstance.acquireTokenSilent(request)
        .catch(async (error) => {
            console.error(error);
            const acquireTokenUrl = await getAcquireTokenUrl(request);

            return launchWebAuthFlow(acquireTokenUrl);
        })
}
```

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2022-04-05 17:44
@nichovski This looks like a duplicate of #3923. Are you using the v3 manifest?

**Comment by nichovski** [comment] 2022-04-05 17:48
@jasonnutter Yes, I'm using manifest v3. It looks like the same issue :( I hope it will be solved sooner.

**Comment by jasonnutter** [comment] 2022-04-05 17:51
@nichovski Thanks for confirming. Unfortunately, we haven't been able to prioritize compatibility for manifest v3 in service workers, given the current dependency on the window object. Apologies for the inconvenience there. I'll close this issue as a duplicate, please follow the linked issue for updates.

**Closed as completed by jasonnutter** 2022-04-05 17:51 UTC
Labels: question, msal-browser
