### ISSUE TITLE
Logging in with a live account fails when requesting consent with invalid_request: The provided request must include a 'client_id' input parameter.

### ISSUE THREAD

**Issue by brugh** [AzureAD/microsoft-authentication-library-for-js#3179] opened 2021-03-10 11:20 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.12.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.0.0-beta.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [X] Angular@11.2.4
- [ ] React
- [ ] Other

## Description
Trying to log in to an application fails when trying to ask for consent. Using more than the default scope profile or open_id produces an error as described below. 
Scopes on the application are Files.ReadWrite.All Sites.Read.All offline_access OpenId Profile User.Read and when I go to the URL
```
https://login.live.com/oauth20_authorize.srf?client_id={my client ID}&scope=Files.ReadWrite.All%20Sites.Read.All%20offline_access%20OpenId%20Profile%20User.Read&response_type=code&redirect_uri={my redirect URL}
```
as described at 
```
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online
``` 
I get a proper consent prompt but with msal-angular I get an error message: 

## Error Message

After login with a hotmail.com account, I get stranded on: 
```
https://login.live.com/oauth20_authorize.srf?res=error&ec=&uaid={ some ID }
```
with a message: 
```
invalid_request: The provided request must include a 'client_id' input parameter.
```

## MSAL Configuration

```js
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.msal.clientId,
      authority: environment.msal.authority, // = https://login.microsoftonline.com/common/
      redirectUri: environment.msal.redirectUri,
      navigateToLoginRequestUrl: true,
      knownAuthorities: [],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Error,
        piiLoggingEnabled: false
      },
      tokenRenewalOffsetSeconds: 300,
      navigateFrameWait: 1000,
      windowHashTimeout: 60000,
      iframeHashTimeout: 6000,
      loadFrameTimeout: 0
    },
  });
}
```

## Reproduction steps

I used the basic code from the sample at 
```js
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-sample-app
```
I changed the Client_ID to my own registered application which has two specific configuration changes. 
I removed the WEB as platform and added the Single-page Application reply url instead. I also changed the audience to:
```
"signInAudience": "AzureADandPersonalMicrosoftAccount",
```

## Expected behavior
Able to sign in with both my AzureAD account as my Live.com account. 

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [X] Other: Microsoft Edge Legacy (sideloading the page as an add-in through a manifest.xml in Office)

## Regression
This failed in previous versions too but since this is a beta and still exists I'm trying to report the bug

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment] 2021-03-10 17:25
@brugh Can you send us a network trace with this behavior? Email is on my profile, thanks!

**Comment by brugh** [comment] 2021-03-12 13:05
@tnorling I sent you a mail with a network trace. The URLs in there are showing a client_id in the queryparams so something's wrong when the consent question should popup because the error says the client_id is missing. hope you can make sense of it

**Comment by tnorling** [comment] 2021-03-22 23:24
@brugh Is this still an issue? The network traces provided were incomplete, if you still need assistance please refer to my email, otherwise let us know if this can be closed? Thanks!

**Comment by brugh** [comment] 2021-03-23 12:00
sorry, had another project that needed attention. 
the issue is still very much a problem. I will try to capture a complete trace this or next week.

**Comment by will-bartlett** [comment] 2021-04-09 18:09
@brugh chiming in from the server side here, @tnorling shared your trace with me. The short answer is that your trace shows non-web-browser behavior. In particular, your trace shows two different user agents:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19042
and
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68
These are pre-Chromium Edge v18 and post-Chromium Edge v89.

The point of transition from v18 to v89 is a request to https://account.live.com/Consent/Update (frame 34 in the trace). This request should be an auto-navigated POST with data but instead is a user-navigated (Sec-Fetch-User: ?1) GET without data. Because the data is dropped, the context is lost, and you see the error described.

Given that you say the page is side-loaded in Office via a manifest.xml, I suspect this "not-a-web-browser" behavior is coming from Office. (If you hadn't said this, I might have suggested e.g. browser plugins, enterprise policies, etc.). Then, I think Office is the right team to continue investigating this issue.

**Comment by tnorling** [comment] 2021-04-09 18:57
@brugh I missed the part where you mentioned you're trying to build an office add-in. Can you confirm? If so, we have a sample that demonstrates integrating msal.js with office [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3179) as there are some extra considerations. Can you check that out and let me know if that aligns with how you're trying to build your add-in?

**Comment by brugh** [comment] 2021-04-12 08:04
@tnorling yes, I'm trying to build an office add-in with msal2. Can you check the link you mentioned? it points to this issue, not a sample app :) Really curious what considerations that may be. I thought I worked around quite a few already 😛 

@will-bartlett Seems indeed that the office add-in runs in v18 for some reason, but I have no control over that. Why would an auto-navigated Post from msal result in a Get in a new context/session? I'm assuming that v18 would be just as able to handle that Post and keep it in its own context? Isn't that something that msal induces maybe?
I really hope I dont have to ask the Office team to fix this. They seem to have quite a different focus on issues that you guys have!

**Comment by tnorling** [comment] 2021-04-12 16:18
@brugh Sorry about that! Try [this one](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth/Office-Add-in-Microsoft-Graph-React). You may also find [these docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz) about authenticating with office add-ins helpful. The main thing to be aware of is that you should be using the dialog API instead of sideloading the Edge browser.

**Comment by brugh** [comment] 2021-04-14 07:42
Thanks! that sample helps a lot although the integration with msal looks very limited. Capturing the token and adding it to graph calls yourself seems like a job for MSAL, not something you'd have to do yourself. But if I can somehow hook into MsalGuard to open a Dialog when the guard cancels navigation, I think i'll be golden. I think I'll go try my own guard and see what happens. 

@will-bartlett Can you confirm that the auto navigated Post you mentioned is the point where msal makes the sideloaded Edge bug out and start an external instance with loss of context? Feels like something msal does makes this happen and could maybe be detected and fixed?

**Comment by tnorling** [comment] 2021-04-14 16:07
> Capturing the token and adding it to graph calls yourself seems like a job for MSAL, not something you'd have to do yourself. 

This sample just uses `msal-browser` by itself, which does not have an interceptor like `msal-angular`. In your case you should be able to use the `msal-angular` interceptor to do this.

> Can you confirm that the auto navigated Post you mentioned is the point where msal makes the sideloaded Edge bug out and start an external instance with loss of context? Feels like something msal does makes this happen and could maybe be detected and fixed?

Our understanding when talking to the folks in office is that this was caused by a domain allow list in your manifest. One of the domains that was being navigated to was not explicitly allowed and the Office was redirecting the request to another API that can handle it. In this case, it's ultimately not that important as sideloading Edge is not the correct way to handle auth in an office add-in.

**Comment by brugh** [comment] 2021-04-26 09:33
Just to send some feedback; I completely reworked the login procedure based on this ticket. Problem I'm having is that Office.js REQUIRES a /#/ router while Azure AD entirely prohibits the use of fragments in the redirectUri. To work around that in Angular is difficult because the initial router picks up everything so having a login component that goes without a # and an application that uses hash seems impossible. 
So, I built 2 separate applications, one that handles the login without a useHash-router to accommodate Azure that opens in a dialogbox from the Office add-in, and another one that captures the token (as in the example you sent) and has no msal at all. Downside I see is that when the token expires, the user gets a new dialogbox to login while when the main app would use msal, it could try to SSO-login. This also poses a problem where running it locally for dev purposes, runs 2 separate apps on 2 separate ports. But publishing it (building it to https://<site> and https://<site>/login) works ok. I could probably catch the localstorage in the main app as the domain is the same and msal could pickup the login settings. Maybe in the next release ;) 

Anyway, I still think that the point @will-bartlett identified where somehow the POST gets (wrongly) transformed into a GET is weird and could be a bug in MSAL, But this workaround is good enough for now and this ticket can be closed.

**Comment by tnorling** [comment] 2021-04-26 16:58
@brugh 
> Problem I'm having is that Office.js REQUIRES a /#/ router while Azure AD entirely prohibits the use of fragments in the redirectUri.

This problem can be solved by setting your `redirectUri` to your homepage (which does not require a hash). If you initiate login from a different page, let's say `/#/profile`, MSAL will handle getting you back to that page after the redirect to `/`. Our [angular 11 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-sample-app) demonstrates using MSAL with hash routing. Would this solve the problem you're having?

> somehow the POST gets (wrongly) transformed into a GET is weird and could be a bug in MSAL.

As stated above, this was caused by the Office API, completely outside the context of MSAL, and was due to using the Office API incorrectly. We do not believe this is a bug.

**Comment by brugh** [comment] 2021-05-04 10:05
@tnorling I should test that some more. I took the example  you mentioned and built the office addin around it but still ran into trouble when the app.component and app.router started. somewhere when idtokens and code's were returned the routing still went wrong (coming back to #code breaks routing and whatnot). not sure if there's something I missed but in all tests I still haven't found a way to combine the two (msal and office.js). 

anyway, I think that's not an issue for this ticket anymore :) thanks for the help!
(and maybe if somebody can ask for an example from the office.js team using msal, that would be very helpful :)).

**Comment by tnorling** [comment] 2021-05-04 16:02
@brugh Yeah you'll need to add a #code route to your routing module like demonstrated in the [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app-routing.module.ts#L32).

Closing but please feel free to open a new issue if you continue to have issues getting this set up. Thanks!

**Closed by tnorling** 2021-05-04 16:02 UTC
Labels: answered, msal-browser, office-addin, question
