### ISSUE TITLE
Angular example for new tabs, logging out and expected behavior

### ISSUE THREAD

**Issue by claprincedesigns** [AzureAD/microsoft-authentication-library-for-js#1029] opened 2019-10-03 20:58 UTC
Hello, I have a project that I'm working on and we have a question regarding the cacheLocation? What I'm trying to accomplish is opening a new tab and using the same session which was accomplished using the cacheLocation and setting that to localStorage. 

However, the problem comes when you log out of one tab the other tab becomes unresponsive. What I'm trying to understand is if there is a way to have both tabs logout vs just the one tab? Or if you can tell me why it seems to refuse to display the sign-in screen. Here is the error that I get:

`Refused to display 'https://capstonelogisticspartners.b2clogin.com/capstonelogisticspartners.onmicrosoft.com/b2c_1_signupsignin2/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=1b09176d-6046-45cf-a177-4455e9eb9141&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=8cd5429b-cb0d-430e-a340-eacc86512a22&nonce=ee5a2b90-50b2-4049-a3ef-d7b86f74773b&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.1&client-request-id=11c32ba3-4898-4c52-8f62-f1ee6fc30ee2&prompt=select_account&response_mode=fragment' in a frame because it set 'X-Frame-Options' to 'deny'.`

Any thoughts would be most appreciated.

**Comment by sameerag** [comment] 2019-10-04 16:26
@claprincedesigns

- For `sign-up` policy where you need interaction, `acquireTokenSilent()` is not supported. We expect the user to call an interactive API, `loginPopup()`/`acquireTokenPopup()` wherever credential entry is required.
- It is a little unclear for me that you are seeing the error only after `logout`, is it possible that you are calling `acquireTokenSilent()` after logging out?
- Can you please provide us the steps to reproduce this issue and the `msal js` version in use?

**Note**: B2C service team is collaborating with us on documentation for patterns to be used with multiple policies.

**Comment by claprincedesigns** [comment] 2019-10-04 17:17
I'm using `import { BroadcastService, MSAL_CONFIG,  MsalConfig, MsalGuard, MsalInterceptor,
  MsalService, } from "@azure/msal-angular";` 

- When I have signed in, I can see the dashboard.
- Right-click on one of the links to 'Open in a new tab'
- The new tab open with the same session storage thanks to cacheLocation: localStorage
- I begin to click around both tabs to make sure that everything is working as expected
- Next step is the click the logout button on the second tab
- Return to the original tab and click around only to notice that the page is unresponsive because 
   the session has now ended (which is what I expect), however, it's not displaying the sign-in 
   screen like the other tab is doing. 

Instead, I get a couple of errors:
1. Letting me know the session has ended which is again what I expect
2. Refused to display ..... in a frame because it set 'X-Frame-Options' to 'deny'

I haven't been able to find where it could be set to anything and I was wondering if this is something that's related to MSAL-Angular or if this is something that I should look into outside of MSAL or if there is something in MSAL that I can use to get the expected results of both tabs logging out when the session has ended.

**Comment by negoe** [comment] 2019-10-04 20:39
@sameerag Reviewing.

**Comment by sameerag** [comment] 2020-01-10 00:26
@sameerag to reproduce this and help with a pattern for users to prevent this usage

**Comment by pkanher617** [comment] 2020-05-13 22:41
@derisen Could you make sure the scenarios outlined here are represented in the [Angular B2C samples](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa)?

**Comment by derisen** [comment] 2020-05-13 23:35
@pkanher617 sounds good, I'll check.

**Comment by derisen** [comment] 2020-05-15 16:42
I was not able to reproduce this with our Angular B2C sample on Chrome and Edge; login/logout works as expected in both tabs.

**Comment by pkanher617** [comment] 2020-06-03 20:10
Closing for now, please let us know if you are still having this issue.

**Closed by pkanher617** 2020-06-03 20:10 UTC
Labels: Issue Triage, b2c, b2c-service, external, no-issue-activity, samples
