### ISSUE TITLE
Login redirect interaction not cleared when clicking browser back 

### ISSUE THREAD

**Issue by timotuunanen** [AzureAD/microsoft-authentication-library-for-js#4171] opened 2021-10-19 06:56 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I have created a minimal React application using these instructions: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react I am using Azure B2C tenant and loginRedirect() to log in. Previous interaction is not cleared if user presses browser back -button in the login page. Calling handleRedirectPromise() does not help.

### MSAL Configuration

```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
  auth: {
    clientId: "xxx",
    authority:
      "https://xxx/B2C_1_SignupSignin_v1",
    knownAuthorities: [
      "https://xxx/B2C_1_SignupSignin_v1",
    ],
    redirectUri: "/",
    postLogoutRedirectUri: "/",
  },
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest = {
  scopes: ["openid", "email", "profile"],
};
```

### Relevant Code Snippets

```javascript
import logo from "./logo.svg";
import "./App.css";

import { useIsAuthenticated, useMsal } from "@azure/msal-react";
import { InteractionStatus } from "@azure/msal-browser";

function App() {
  const isAuthenticated = useIsAuthenticated();
  const { instance, inProgress } = useMsal();

  const logInClicked = async () => {
    console.log("logInClicked");

    if (!isAuthenticated && inProgress === InteractionStatus.None) {
      instance.loginRedirect().then((res) => {
        instance.handleRedirectPromise().catch((error) => {
          console.log(error);
        });
      });
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <button onClick={logInClicked}>Login</button>
      </header>
    </div>
  );
}

export default App;
```

### Reproduction Steps

1. Press login button.
2. When you are redirected to the login page, press browser back -button to return to your application. 
3. Press the login -button again and you will not be redirected to the login -page, since previous interaction is ongoing. 

### Expected Behavior

Ongoing session should be cleared and login page should be displayed.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by timotuunanen** [comment] 2021-10-19 07:04
Note that this behaviour only occurs in the production build. So, running `yarn start` will NOT reproduce the bug.

**Comment by jasonnutter** [comment] 2021-10-19 22:16
@timotuunanen Can you please provide verbose logs from MSAL?

When using MSAL React, you should use the MsalProvider component, which will automatically invoke `handleRedirectPromise` for you, which is what handles clearing the temporary cache (which keeps track of interaction in progress). Details here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#initialization

**Comment by jasonnutter** [comment] 2021-10-19 23:22
If you are using `MsalProvider`, please debug it's invocation of `handleRedirectPromise` (which should be invoked when the component is first rendered), as it should be clearing any temporary cache values for interaction in progress.

**Comment by timotuunanen** [comment] 2021-10-20 05:52
Yes. I am using `MsalProvider` From my index.js:

```
import App from "./App";

import { PublicClientApplication } from "@azure/msal-browser";
import { MsalProvider } from "@azure/msal-react";
import { msalConfig } from "./authConfig";

const msalInstance = new PublicClientApplication(msalConfig);

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={msalInstance}>
      <App />
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById("root")
);
```
I will try to get some verbose logs.

**Comment by timotuunanen** [comment] 2021-10-20 06:25
Here are the logs from the simple: login -> browser back -> login

```
logInClicked App.js:11:12
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - loginRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - preflightBrowserEnvironmentCheck started authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - loginRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - preflightBrowserEnvironmentCheck started authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback b0f7db71-7a11-42b6-97bd-fd71bdbce035: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback c77fa3b2-7583-4505-929d-1c513750ddd7: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-react@1.1.0 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback b0f7db71-7a11-42b6-97bd-fd71bdbce035: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback c77fa3b2-7583-4505-929d-1c513750ddd7: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-react@1.1.0 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - preflightInteractiveRequest called, validating app environment authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeAuthorizationRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - preflightInteractiveRequest called, validating app environment authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeAuthorizationRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getRedirectUri called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getRedirectUri called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Initializing BaseAuthRequest authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Initializing BaseAuthRequest authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeServerTelemetryManager called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeAuthorizationRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeServerTelemetryManager called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - initializeAuthorizationRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called 3 authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getClientConfiguration called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getClientConfiguration called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getDiscoveredAuthority called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Creating discovered authority with request authority authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - getDiscoveredAuthority called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:10 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Creating discovered authority with request authority authConfig.ts:4:10
Navigated to https://xxxxxxx/b2c_1_signupsignin_v1/oauth2/v2.0/authorize?client_id=xxxxxxx&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2F&client-request-id=12039e55-9b4e-4172-a2ac-da853f19b530&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.18.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=1pvqztASVQi-iQIfnoK3aAKU-s9H9JAGXTtiWVuQiJQ&code_challenge_method=S256&nonce=3001e6fc-71e8-4770-9416-4692130ad2ca&state=eyJpZCI6IjA3MmUwOWNiLTc5Y2MtNGQxZi04YTdkLThmMjQzOTkxMjMzOCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Auth code client created authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - Auth code client created authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:11 GMT] : [12039e55-9b4e-4172-a2ac-da853f19b530] : msal.js.browser@2.18.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url authConfig.ts:4:10
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. authorize:17:55403
Some cookies are misusing the recommended “SameSite“ attribute 2
Navigated to http://localhost:8000/
logInClicked App.js:11:12
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - loginRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - preflightBrowserEnvironmentCheck started authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenRedirect called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback b0f7db71-7a11-42b6-97bd-fd71bdbce035: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback c77fa3b2-7583-4505-929d-1c513750ddd7: msal:loginStart authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-react@1.1.0 : Info - MsalProvider - msal:loginStart results in setting inProgress from login to login authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [05983a87-9e91-432a-89d8-751c21b47310] : msal.js.browser@2.18.0 : Verbose - preflightInteractiveRequest called, validating app environment authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:loginFailure authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback b0f7db71-7a11-42b6-97bd-fd71bdbce035: msal:loginFailure authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-react@1.1.0 : Info - MsalProvider - no account changes authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - Emitting event to callback c77fa3b2-7583-4505-929d-1c513750ddd7: msal:loginFailure authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-react@1.1.0 : Info - MsalProvider - msal:loginFailure results in setting inProgress from login to none authConfig.ts:4:10
[Wed, 20 Oct 2021 06:20:16 GMT] : [1234] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called 3 authConfig.ts:4:10
Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    t 2.8594a624.chunk.js:2
    t 2.8594a624.chunk.js:2
    createInteractionInProgressError 2.8594a624.chunk.js:2
    preflightInteractiveRequest 2.8594a624.chunk.js:2
    acquireToken 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    acquireToken 2.8594a624.chunk.js:2
    acquireTokenRedirect 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    acquireTokenRedirect 2.8594a624.chunk.js:2
    loginRedirect 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    a 2.8594a624.chunk.js:2
    loginRedirect 2.8594a624.chunk.js:2
    n App.js:14
    l 2.8594a624.chunk.js:2
    _invoke 2.8594a624.chunk.js:2
    S 2.8594a624.chunk.js:2
    r 2.8594a624.chunk.js:2
    c 2.8594a624.chunk.js:2
    o 2.8594a624.chunk.js:2
    o 2.8594a624.chunk.js:2
    c App.js:10
    ze 2.8594a624.chunk.js:2
    Ye 2.8594a624.chunk.js:2
    Or 2.8594a624.chunk.js:2
    Or 2.8594a624.chunk.js:2
    kr 2.8594a624.chunk.js:2
    Mr 2.8594a624.chunk.js:2
    xe 2.8594a624.chunk.js:2
    Mr 2.8594a624.chunk.js:2
    Mr 2.8594a624.chunk.js:2
    Zt 2.8594a624.chunk.js:2
    $t 2.8594a624.chunk.js:2
    unstable_runWithPriority 2.8594a624.chunk.js:2
    Wo 2.8594a624.chunk.js:2
    Ue 2.8594a624.chunk.js:2
    Jt 2.8594a624.chunk.js:2
    Ur 2.8594a624.chunk.js:2
    Lr 2.8594a624.chunk.js:2
    Nr 2.8594a624.chunk.js:2
    Nr 2.8594a624.chunk.js:2
    ou 2.8594a624.chunk.js:2
    _reactRootContainer 2.8594a624.chunk.js:2
    au 2.8594a624.chunk.js:2
    render 2.8594a624.chunk.js:2
    30 index.js:13
    a (index):1
    r (index):1
    t (index):1
    <anonymous> main.2917fa32.chunk.js:1
2.8594a624.chunk.js:2:28344


```

**Comment by cristian-calugar** [comment] 2021-10-21 08:19
I have the same issue. But only on Safari (both on Mac and iPhone).

It seems that Safari does not trigger a page refresh when returning from log in page to our app. This causes the inProgress flag to still have the value 'login'.

If the user tries to login again, we call loginRedirect(), but nothing is happening.

Is there a way we can clear the inProgress state programatically?

Thanks!

**Comment by jo-arroyo** [comment] 2021-10-27 21:00
@timotuunanen We have been unable to reproduce this behavior. Are you able to reproduce this in one of our samples? That would help with debugging. 

@cristian-calugar The `inProgress` state is not designed to be cleared programmatically. If you wish to reproduce your issue in one of our samples, we would be happy to look at it too.

**Comment by timotuunanen** [comment] 2021-10-28 06:42
@jo-arroyo I was able to reproduce the problem using b2c-sample and Firefox (93.0 (64-bit)). Using Chrome the sample worked fine. Note that I am running a production build. Development build does not have the same problem.

All the following commands are run in the /microsoft-authentication-library-for-js/samples/msal-react-samples/b2c-sample -directory:

```
npm run install:published
npm install
npm run build
npm install -g serve
serve -s build/

```

Then:

1. Click login -> Sign in using Redirect
2. Hit the browser back button on the login page
3. Repeat step 1
4. No login page is displayed.

**Comment by jo-arroyo** [comment] 2021-10-29 22:48
@timotuunanen Thanks for the steps, we were able to reproduce this and will be investigating the cause.

**Comment by jasonnutter** [comment] 2021-11-03 16:45
@hectormmg @jo-arroyo Can you please work together on solving this issue? Thanks!

**Comment by lohse614** [comment] 2021-11-30 12:42
Hi, 

I am facing the same problem with a plain javascript application.

1. opening the app on the welcome page with a sign-in button
2. click on sign-in button triggers a custom policy with a step for the identity provider selection
3. when clicking the browser's back button, the app navigates back to the welcome page with the sign-in button
4. sign-in again appears to not do anything, in the console there is the following error
` Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.`

On page load the following code is executed:
`myMSALObj
        .handleRedirectPromise()
        .then(response => handleResponse(response))
        .catch(error => console.log(error));`

The issue appears in Firefox 94.0 (64-bit), chrome (Version 96.0.4664.45 (Official Build) (64-bit)) is working with the back button as expected.
It appears that firefox is not executing the javascript code containing the `handleRedirectPromise` when using the browser's back button.

It turns out that I can manually remove the `msal.interaction.status` from session- / localStorage to make it work again.

Is there a way to make firefox work with the browsers back button? Or 
is there a standard way to reset the interaction status without fiddling manually in the storage used by the msal-library?

Any help is appreciated.

Thanks and regards,
Henrik

**Comment by rebendajirijr** [comment] 2022-02-09 12:14
We'are also facing the same issue in our project. Is there any known workaround? It works when the application is served in development mode, but when serving the production-like build, it doesn't.

**msal:loginStart** event is fired, but no other events then, so this results in having inconsistent state.

**Comment by tnorling** [comment] 2022-02-10 01:15
It seems like this behavior is due to a feature in some browsers: [Back/Forward Cache](https://web.dev/bfcache/) which is preventing `handleRedirectPromise` from being run again when the page is loaded as a result of going back. What happens if you include an event listener that calls `handleRedirectPromise` when loading the page from cache?

```javascript
window.addEventListener('pageshow', (event) => {
        if (event.persisted) {
            // Page loaded from cache
            pca.handleRedirectPromise();
        }
    })
```

**Comment by rebendajirijr** [comment] 2022-02-10 06:32
> It seems like this behavior is due to a feature in some browsers: [Back/Forward Cache](https://web.dev/bfcache/) which is preventing `handleRedirectPromise` from being run again when the page is loaded as a result of going back. What happens if you include an event listener that calls `handleRedirectPromise` when loading the page from cache?
> 
> ```js
> window.addEventListener('pageshow', (event) => {
>         if (event.persisted) {
>             // Page loaded from cache
>             pca.handleRedirectPromise();
>         }
>     })
> ```
You are probably right. I checked that when serving the application in development mode, the pageshow event isn't fired at all. But when using production-like build it is. So I've tried your approach, but it doesn't work.
![image](https://user-images.githubusercontent.com/3431185/153349580-5426f212-964a-4e05-821a-5c3682d0a7b7.png)
It says it returns the result from the previous call which is useless because the previous kinda doesn't complete.
![image](https://user-images.githubusercontent.com/3431185/153349508-e2fd22cd-8509-4b7f-ab11-4436ca092182.png)

I ended up with a very hacky workaround. When the MSAL broadcast service emits anything else than `InteractionStatus.None`, then I wait few seconds if the action completes with `InteractionStatus.None`. After this timeout I simply reload the whole page. This is the only way how I was able to mitigate the issue and prevent the user from being stucked with loading having an incorrect auth state :(

Maybe it would be even better to combine it with your approach - to detect the `event.persisted` case and reload the page only then. That could make it work better.

**Comment by tnorling** [comment] 2022-02-10 17:10
I see, it's preserving everything as if you never left the page, including the in-memory storage objects we use to memoize `handleRedirectPromise`. This is something we'll likely have to address in the library but until we get a chance to work on this would it work to just do a hard reload when the above window event is fired? Another option as a workaround, though admittedly hacky, would be to make your app ineligible for the back/forward caching, there were a couple suggestions in the article linked.

**Closed as completed** 2022-03-07 21:34 UTC
Labels: bug, msal-browser, msal-react

**Comment by IvanTrajkovic1** [comment] 2024-12-03 23:21
Try clear session storage before redirect to login page. For me that works :)
