### ISSUE TITLE
broadcast event loginsuccess sends inconsistent results (msal-angular)

### ISSUE THREAD

**Issue by abulsujon** [AzureAD/microsoft-authentication-library-for-js#445] opened 2018-09-23 19:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version-0.2.3

<pre><code>
Library version: X.Y.Z

## Current behavior

Broadcast event "loginSuccess" sends different data values  depending on whether we call loginpopup or loginredirect. We have added code to call loginpopup/loginredirect depending on if pop up blocked by browser but we get different result from the events.

## Minimal reproduction of the problem with instructions

call loginpopup and loginredirect from a sample and compare each property name.

</code></pre>

**Comment by nehaagrawal** [comment] 2018-09-26 00:11
Welcome to Github :-).  Please don't open issues without mentioning exact library versions. This helps us to support you better. I am unable to reproduce this issue. It's possible that you are using an old version.

**Comment by navyasric** [comment] 2019-02-09 01:31
Closing this issue due to lack of further info from original poster.

**Closed by navyasric** 2019-02-09 01:31 UTC
Labels: needs info
