### ISSUE TITLE
Node: AccountUserInfo.idTokenClaims is undefined when deserializing from cache

### ISSUE THREAD

**Issue by ccosmincc** [AzureAD/microsoft-authentication-library-for-js#3208] opened 2021-03-13 11:04 UTC
## Library
- [x] `@azure/msal-node@1.0.1`

## Framework
- [X] Electron

## Description
I'm following the Msal Electron Node sample ([link](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/67ab72d3b76f1e2c98bc2b1a36c73934c74b0a38/samples/msal-node-samples/standalone-samples/ElectronTestApp))  and I would like to read the user roles (`authProvider.currentAccount.idTokenClaims.roles`) but `idTokenClaims` is always undefined, even if I do have the object properly populated with the roles array after doing the login and before serializing it and saving it into the cache file. It seems like the Serializer ([link](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/cache/serializer/Serializer.ts#L52)) does not include information about `idTokenClaims.roles`, or I might be missing something regarding how (if possible) to get this information based on what is serialized inside the `IdToken` object.

## Error Message
-

## MSAL Configuration
-

## Reproduction steps

Try to obtain information about the user roles `authProvider.currentAccount.idTokenClaims.roles`.

## Expected behavior

User roles information should be exposed via `idTokenClaims.roles`

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [x] Other (Electron)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [x] Customer request

**Comment by sameerag** [comment] 2021-03-17 19:10
@ccosmincc Serializer is used only for persisting the cache in a pre-agreed format to the disk. The user interface for account info is [Account](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_common.html#accountinfo) object returned in the [AuthenticationResult](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_common.html#authenticationresult) contains the `IdTokenClaims` which should have `roles` in it.

This is the response we send when you make a token request, for both interactive or silent calls. Please let me know if you need more info on the usage.

**Comment by ccosmincc** [comment] 2021-03-20 13:28
@sameerag: I have the following use case: after the user does the login, I want to display/hide certain parts based on what he has defined in `roles`. Given your input that I can only get this information from a token request, does that mean I need to manually trigger a `getToken` operation as part of the login process only to get the roles that I can then add to the current account (something like `account.idTokenClaims = authResponse.idTokenClaims` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/67ab72d3b76f1e2c98bc2b1a36c73934c74b0a38/samples/msal-node-samples/standalone-samples/ElectronTestApp/src/AuthProvider.ts#L110))? Or is there another way I can get this information right after login, but before any other requests that require a token are being made?

**Comment by ccosmincc** [comment] 2021-04-06 13:55
any updates?

**Comment by sameerag** [comment] 2021-04-09 19:06
@ccosmincc A little confused here. 

* When you initially login, you do get back an [AuthenticationResult](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_common.html#authenticationresult)  that has the [AccountInfo](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_common.html#accountinfo) object. `AccountInfo` consists of `idTokenClaims` and you can persist them on your end. 
* If you are asking about the `TokenCache` we persist, no, it does not contain idToken claims specifically. 

So in your case, when the user logs in, the response you receive (since login requires token fetching and returns `id_token` and `access_token` along with the `AccountInfo`), you should have this information already. 

What am I missing here?

**Comment by ccosmincc** [comment] 2021-04-11 06:12
@sameerag this is how my login looks like:
`async login() {
    const account = await authProvider.loginSilent();
    if (!account) await authProvider.login(mainWindow);
}`
where `authProvider.loginSilent()` is [this ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/67ab72d3b76f1e2c98bc2b1a36c73934c74b0a38/samples/msal-node-samples/standalone-samples/ElectronTestApp/src/Main.ts#L65) method and `authProvider.login(mainWindow);` is [this ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/67ab72d3b76f1e2c98bc2b1a36c73934c74b0a38/samples/msal-node-samples/standalone-samples/ElectronTestApp/src/Main.ts#L75) one. To me this translates into: get account from cache, if any, otherwise trigger the login flow (with redirect). So, because `loginSilent()` will find the account information in my cache, it will just return it (with `idTokenClaims: undefined`).

**Comment by sameerag** [comment] 2021-04-28 07:56
@ccosmincc Is this a browser use case? I thought this was marked as an `msal-node` issue, but looks like you are using `msal-browser`. To access an Account, can you try `getAccount()` which ideally always has `idTokenClaims` populated in case you have previously logged in. In your case when you successfully make a `loginSilent` call, it means that the account can be fetched from the cache and we populate `idTokenClaims` with it.

**Comment by ccosmincc** [comment] 2021-04-28 10:21
@sameerag no, it's not a browser use case. I'm using `msal-node` in Electron following [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/67ab72d3b76f1e2c98bc2b1a36c73934c74b0a38/samples/msal-node-samples/standalone-samples/ElectronTestApp) sample. All of my previous comments are using links from this Electron sample.
I want to achieve the following:
1. user opens the Electron app for the first time (cache file does not exist)
2. app redirects to Azure login screen
3. user logs in with username and password (at this point I get `idTokenClaims`, but it's not stored in the cache file)
4. user closes app
5. user opens app again (cache file exists)
6. user is no longer be redirected to login screen, but automatically logged in based on cache information
7. I want to access `idTokenClaims` (but it's not available since it was not saved in the cache file at step 3, and that cache file is used to get the account info at step 6)

"In your case when you successfully make a loginSilent call, it means that the account can be fetched from the cache and we populate idTokenClaims with it." - this is exactly my problem, that when loginSilent fetches the account from the cache, `idTokenClaims` is undefined, even if I had it populated when the account data was put into cache.

**Comment by sameerag** [comment] 2021-06-01 23:26
@ccosmincc Apologies for the delayed response. We are able to reproduce this issue and it is a bug on our end. Working on a fix and will update soon after a PR is available here.

**Comment by jasonnutter** [comment] 2021-10-18 20:28
@sameerag Is this still an issue?

**Comment by sameerag** [comment] 2021-10-19 09:28
Should be resolved with #4081

**Comment by Philluxx** [comment] 2021-11-03 15:11
Is it foreseeable when this bug will be fixed? Currently the ID token claims are completely empty when deserializing from the cache. This requires a messy workaround and you have to persist the claims yourself elsewhere.

Thank you so much!

**Comment by sameerag** [comment] 2022-04-02 04:45
#4081 is merged now. Closing this issue. Please test and raise another issue if you are still seeing this problem.

**Closed by sameerag** 2022-04-02 04:45 UTC
Labels: bug, p2, msal-node

**Comment by nicotroia** [comment] 2023-04-12 05:18
The `idTokenClaims` is actually empty upon `getTokenCache().serialize()`, so I guess this can be solved by caching `JSON.stringify(client.getTokenCache())` instead of `client.getTokenCache().serialize()`
