### ISSUE TITLE
@azure/msal-node-extensions doesn't have pre-compiled binaries

### ISSUE THREAD

**Issue by dzearing** [AzureAD/microsoft-authentication-library-for-js#6716] opened 2023-11-23 00:06 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Public or Confidential Client?

Public

### Description

I am reopening a bug to track the fact that depending on this library causes all down streams who directly or indirectly depend on @azure/msal-node-extensions (in our case we were using @azure/identity) to require Visual Studio to be installed just to use this. This includes Loop, Teams, and other primary Office apps.

It looks like the original complaint was here: #3332

It seems like @tnorling had made some changes in #6084 but we are still seeing developers failing to install dependencies when they do not have visual studio. This was introduced by upgrading a separate, completely unrelated tool which has a dependency on  `@azure/identity-cache-persistence@1.0.0` , adding new requirements to repos that use the tool.

Can we fix this asap and actually distribute optional pre-built binaries? This is what we do in other packages, such as github.com/microsoft/ori or github.com/kenotron/glob-hasher.

### Source

Internal (Microsoft)

**Comment by JasonGore** [comment] 2023-11-27 17:48
If the issue is with alpha versions of `@azure/msal-node-extensions`, I wonder if the issue here is actually `@azure/identity-cache-persistence` `v1.0.0` (and `v1.0.1`), which seems to [be pinning to `@azure/msal-node-extensions` `1.0.0-alpha.25`](https://github.com/Azure/azure-sdk-for-js/blob/36b3a9eb4fc5a6d4650ad5eac6fb417be3b8ac73/sdk/identity/identity-cache-persistence/package.json#L65). At least in our repo, that's how the alpha version was being included.

**Comment by tnorling** [comment] 2023-11-28 17:31
Closing - precompiled binaries started being included in the beta releases. msal-node-extensions has since GA'd so I recommend updating to the latest non-alpha/beta version.

**Closed as completed by tnorling** 2023-11-28 17:31 UTC
Labels: question, msal-node, msal-node-extensions, feature-unconfirmed, public-client

**Comment by JasonGore** [comment] 2023-11-28 17:44
@tnorling Per my comment, the version specification isn't under our control. It's pinned by `@azure/identity-cache-persistence` via the link I provided.

**Comment by tnorling** [comment] 2023-11-28 21:49
Understood, please open an issue on the affected package's repo. There's no work needed by the MSAL.js team at this time.
