### ISSUE TITLE
Front channel logout not working in Firefox default settings

### ISSUE THREAD

**Issue by mamoorkhan** [AzureAD/microsoft-authentication-library-for-js#6511] opened 2023-09-25 20:35 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Public

### Description
We have an angular app where the front channel logout is working fine on edge and chrome. But it is not working out of the box in Firefox.

We updated the the libraries to the latest to see if that would help, but the behavior is still the same.

```json
    "@azure/msal-angular": "^3.0.4",
    "@azure/msal-browser": "^3.1.0",
```

Firefox version
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/136f9ba8-6c1b-482d-a642-0bb2169cfbc8)

Firefox with its default settings/behavior does not allow the session to be destroyed in our MSAL.js based angular application. On the other hand, we have an MVC application which stores its session in the cookies, gets its session cleared when its logout endpoint is called, but the localStorage items we are setting for updating the app UI aren't getting set as well.

Upon further testing to verify that its nothing to do with Firefox allowing/disallowing copies of sites loaded in iframes manipulating localstorage, I loaded my SPA in an iframe in the MVC web app and was successfully able to read/write the localstorage for the SPA, also tested the other way around as well.

Following are default settings 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/4db57038-de0a-4f80-9b94-e8d69994bfa4)
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/7bf8d048-7c13-4a08-bb8f-0813bc577a9a)

But if we change it as follows, it starts working as it is in edge and chrome.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/b21eaa25-8f27-4060-b186-b6460c00e2a5)
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/d90a144e-b23d-4236-a47d-f26593431e48)

I have attached the logout request being made to the MSAL app as HAR file.

[angular-app-logout.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/12719106/angular-app-logout.zip)

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: clientId, // This is the ONLY mandatory field that you need to supply.
    authority: b2cPolicies.authorities.signUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
    knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
    redirectUri: environment.loginRedirectUri, // Points to window.location.origin by default. You must register this URI on Azure portal/App Registration.
    postLogoutRedirectUri: environment.logoutRedirectUri, // Points to window.location.origin by default.
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
    storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge. Remove this line to use Angular Universal
  },
  system: {
    allowRedirectInIframe: true,
    loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: environment.logLevel,
      piiLoggingEnabled: false
    },
    tokenRenewalOffsetSeconds: 300, // Sets the window of offset needed to renew the token before expiry. E.g., if acquireTokenSilent() is called within 300 seconds of tokens expiring, the call will attempt to refresh the tokens
  }
}
```

### Relevant Code Snippets

```javascript
remoteLogout() {
    const logoutRequest: EndSessionRequest = {
      authority: 'https://login.microsoftonline.com/common',
      onRedirectNavigate: () => false
    };
    this.authService.logoutRedirect(logoutRequest);
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment] 2023-10-02 23:26
If 3P cookies are disabled, front channel logout would not work. Unfortunately, we cannot fix this behavior as the browser clears the cookies and the service has no context to enable front channel logout.

**Comment by mamoorkhan** [comment] 2023-10-10 14:30
@sameerag thank you for your response, however by default Firefox claims that they do not block 3p cookies for first five websites. We are not using our cookies in more than 1 website. 

https://support.mozilla.org/en-US/kb/third-party-trackers

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/6604239/47127649-47e9-47bb-83a0-8d8da10f2e26)

**Comment by tnorling** [comment] 2023-10-13 22:50
It's not your website's cookies that are getting blocked, the cookies belong to the login.microsoftonline.com domain

**Comment by mamoorkhan** [comment] 2023-10-16 09:03
@tnorling thank you for the explanation and I am sorry for the confusion I created when I said more than 1 for single logout. In our scenario, the user is only logging into 2 websites. One is angular SPA and the other dotnet MVC with razer views. 

I am still of the opinion that the logout call should clear the cookies as we have yet to cross the 5 websites limit.

**Comment by tnorling** [comment] 2023-10-16 17:05
Undersood, thanks for clarifying! It sounds pretty clear from your description above that 3P cookie settings are the cause here. Unfortunately, I don't have a good answer for you here. Since there's no programmatic way for an application to determine whether 3P cookies are blocked by the browser the service will always attempt to read/set the cookies on login and read/remove the cookies on logout (assuming the other conditions for logout are also met). If that's not happening only when the browser blocks 3P cookies it's reasonable to assume that's what's happening here. 

With that in mind I would suggest you reach out to Firefox to understand why 3P cookies are being blocked despite not reaching the 5 site limit they documented. Closing as I don't believe there's anything that can be done from the MSAL.js/AAD side.

**Closed as completed by tnorling** 2023-10-16 17:05 UTC
Labels: question, b2c, msal-angular, msal-browser, no-issue-activity, public-client

**Comment by mamoorkhan** [comment] 2023-10-19 10:26
@tnorling thank you for the reply, there's a little experiment I did. I am not sure if it will help understanding the issue further or not. I loaded my MVC app in an iframe in my angular SPA and was able manipulate the cookies from that iframe. I also loaded the SPA in an iframe within my MVC app and was able to manipulate localstroage from that iframe.
