### ISSUE TITLE
acquireTokenSilent fetching expiredToken

### ISSUE THREAD

**Issue by sonam-serchan** [AzureAD/microsoft-authentication-library-for-js#6130] opened 2023-06-15 06:58 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.8

### Public or Confidential Client?

Public

### Description

I have an app rendered inside microsoft teams.

The expiry time for tokens is one hour.

What we have noticed is if we stay idle in the app i.e. leave it open and browse other tabs, then come back to the app around the time the token is expired (within half an hour approximately), the `acquireTokenSilent` seems to fetch the previously used and expired token. 

I have verified this by checking the token in jwt.ms and then checking the value in `exp` payload using unixtimestamp converter. And it keeps on getting the same old token for almost next 10-20 mins in average. 

Then, after a while only it hits `https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token` to fetch new fresh tokens.

### MSAL Configuration

```javascript
{
        auth: {
            clientId,
            authority: `https://login.microsoftonline.com/${tenantId}`,
            redirectUri: window.location.origin + '/login/end'
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: isIE || isEdge || isFirefox
        },
        system: {
            loggerOptions: {
                logLevel: LogLevel.Trace,
                piiLoggingEnabled: true
            }
        }
}
```

### Relevant Code Snippets

```javascript
let account: AccountInfo;
            account = this.authContext.getActiveAccount();

            if (!account || account?.localAccountId !== userObjectId) {
                const { account: accountInfo } = await this.authContext.ssoSilent({
                    ...msalRequest,
                    loginHint
                });
                this.authContext.setActiveAccount(accountInfo);
                account = accountInfo;
            }

            const { idToken } = await this.authContext.acquireTokenSilent({
                ...msalRequest,
                account
            });
            console.log(idToken);
```

### Reproduction Steps

Login in the app
acquireTokenSilent gets a token
Stay idle for an hour
acquireTokenSilent fetches the same token even though it's expired

### Expected Behavior

If the token is expired, it should get new token not return expired token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by konstantin-msft** [comment] 2023-06-15 21:38
Hi @sonam-serchan. Thanks for reporting this. That's an interesting issue.
Do you have `Memory Saver` enabled in the browser settings (chrome://settings/performance)? Did the application tab got deactivated while you were browsing other tabs?

**Comment by sonam-serchan** [comment] 2023-06-16 07:15
Hi @konstantin-msft, thanks for the reply.
Yes, it looks like I have `Memory Saver` enabled in the browser settings. Does this affect how `acquireTokenSilent` works?

**Comment by konstantin-msft** [comment] 2023-06-16 12:55
@sonam-serchan I have double checked that memory saver does not affect `acquireTokenSilent` API behavior.
This issue is a duplicate of [#4206](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206). We have it tracked internally, but there is currently no easy way to fix that. Our recommendation is to use access tokens instead of id tokens whenever possible.

**Comment by konstantin-msft** [comment] 2023-06-16 17:30
Closing this issue as a duplicate. Workarounds or fixes will be tracked and updated in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206. Thanks.

**Closed as completed by konstantin-msft** 2023-06-16 17:30 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client
