### ISSUE TITLE
angular MsalGuard wrongly checking for 'code='  in URL 

### ISSUE THREAD

**Issue by lf-novelt** [AzureAD/microsoft-authentication-library-for-js#4084] opened 2021-09-22 08:05 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

When the app url contains a query parameter named like "table_code=XXx", it creates a redirect loop due to MsalGuard.

It's probably because of the way checking for the string `code=` in the current path, the check should be stricter (like expecting the / or # or ? character before)

![image](https://user-images.githubusercontent.com/46479127/134305123-9786075e-8d23-43cd-8583-809e1c442c84.png)

### Msal Logs

[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
[Wed, 22 Sep 2021 07:37:59 GMT] : @azure/msal-angular@2.0.2 : Info - Guard - Hash contains known code response, stopping navigation.

### MSAL Configuration

```javascript
new PublicClientApplication({
    auth: {
      clientId: xClientId,
      authority: 'https://login.microsoftonline.com/' + xTenandId,
      redirectUri: URL_BASE + '/login-redirect',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  })
```

### Relevant Code Snippets

```javascript
export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [`api://${xClientId}/.default`]
    },
    loginFailedRoute: '/#login-failed'
  };
}

...
providers: [
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
```
```


### Reproduction Steps

1. Have a secured route query param named `table_code`
2. Navigate to route /secured-route?table_code=123
3. Browser page freezes due to redirect loop

### Expected Behavior

It should not enter a redirect loop when a query parameter name ends by `code`

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge, Other

### Regression

_No response_

### Source

External (Customer)

**Comment by lf-novelt** [comment] 2021-09-22 08:32
Bug also present in latest msal-angular 2.0.3
![image](https://user-images.githubusercontent.com/46479127/134310048-7140dc4d-c034-4fdc-9fc7-3995a631e7dc.png)

**Comment by lf-novelt** [comment] 2021-09-22 08:37
Proposed fix:
```js
// Prevent navigating the app to /#code= or /code=
 if (state && (state.url.indexOf("/#code=") > -1 || state.url.indexOf("/code=") > -1)) {
```

**Comment by jo-arroyo** [comment] 2021-09-22 16:42
@lf-novelt Thanks for pointing this out. We will investigate a fix for this bug and let you know when it is released.

**Comment by cmplank** [comment] 2021-09-23 15:30
Wow. I just came here to report the same bug. Here are some further clarifications not in the original bug report.

1. In version 2.0.3 the problem is partially mitigated. Prior to 2.0.3, you would run into a loop which leaves the page unable to render. In 2.0.3, it doesn't loop, but it does stop navigation and removes all query params from the url. Depending on what those query params are, it can have a deleterious effect on your app. In my case they are marketing campaign info so we're losing analytics with the 2.0.3 version which is bad, but still better than marketing links crashing the page as in 2.0.0-2.0.2.

2. It's worth noting that it's not just the query param "code" that is affected, but any query param ending in "code". In my case, "acode" is a param that is on many links into my app. So this issue may impact a lot of users.

**Comment by Keyzmo** [comment] 2021-10-18 00:23
This is a serious issue. Essentially any query params ending with "code" are now prohibited. For us it broke (after updating from from MSAL-angular v1.x) OAuth auth code flow authorization with a 3d party app where mutual users give our app access to their data in the 3rd party app. Now when they are redirected back to us from 3rd party app after authorizing access (with "code" query param in the URL), they are thrown to MSAL's redirectUri even if there's a valid MSAL token in the local storage.

**Comment by jasonnutter** [comment] 2021-10-25 21:21
@lf-novelt @cmplank @AccessViolator Please see the linked PR for proposed fix, feedback appreciated, thanks!

**Closed** 2021-11-01 20:52 UTC
Labels: bug, msal-angular, msal-browser
