### ISSUE TITLE
Login redirect stuck with hashtag state in Firefox and Safari

### ISSUE THREAD

**Issue by deepti1805** [AzureAD/microsoft-authentication-library-for-js#5144] opened 2022-08-29 14:58 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.6.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

When I tried to set password for a user then it went through all the pages but got stuck in the redirecturi with #state=dnjsjsks only in Firefox and Safari. It is working fine in chrome,edge,IE.

### MSAL Configuration

```javascript
const msalConfigForgotPassword = {
        auth: {
            clientId: clientId,
            authority: forgotPasswordPolicyUrl,
            validateAuthority: false,
            knownAuthorities: [b2cPolicies.authorityDomain],
            redirectUri: msForgotPwdRedirectValue
        },
        cache: {
            cacheLocation: "sessionStorage",
            storeAuthStateInCookie: false
        }
    };
```

### Source

External (Customer)

**Comment by tnorling** [comment] 2022-08-29 16:52
@deepti1805 Please upgrade to the latest version (currently 2.28.1) and let us know if this is still an issue. Thanks!

**Comment by deepti1805** [comment] 2022-09-01 07:59
@tnorling - I am still not able to resolve this issue. Could you please suggest something?

**Comment by tnorling** [comment] 2022-09-01 16:38
@deepti1805 Please provide verbose level logs from MSAL and code snippets showing how you are trying to use the library.

**Comment by deepti1805** [comment] 2022-09-01 17:02
@tnorling I have included below script in page.html and it used all over the website. I am not getting any msal logs in console it just got stuck with #state
<script type="text/javascript" src="[https://alcdn.msauth.net/browser/2.6.1/js/msal-browser.js"](https://alcdn.msauth.net/browser/2.6.1/js/msal-browser.js%22) integrity="sha384-kHVR+hnKKUXpL5UEI3dgmdIKZgopBagC1RdQytFqglEGROvOSAGJRkaFWfu8VsSx" crossorigin="anonymous"></script>

Below is the code that I am using

    const msalConfigForgotPassword = {
        auth: {
            clientId: clientId,
            authority: forgotPasswordPolicyUrl,
            validateAuthority: false,
            knownAuthorities: [b2cPolicies.authorityDomain],
            redirectUri: msForgotPwdRedirectValue
        },
        cache: {
            cacheLocation: "sessionStorage",
            storeAuthStateInCookie: false
        }
    };

    var forgotPasswordRequest = {
        scopes: [...apiConfig.b2cScopes],
    };

    initMsalConfig(msalConfigForgotPassword);
    
function initMsalConfig(configuration) {
        msalInstance = new msal.PublicClientApplication(configuration);
        if (msalInstance != null) {
            msalInstance.handleRedirectPromise()
                .then(handleResponse)
                .catch(error => {
                    console.error(error);
                    console.log(error.errorMessage);
                    if (error && error.errorMessage && error.errorMessage.indexOf("AADB2C90118") > -1) {
                        console.log("forgot password");
                        try {
                            // msalInstance.loginRedirect(b2cPolicies.authorities.forgotPassword);
                        } catch (err) {
                            console.log(err);
                        }
                    }
                    if (error && error.errorMessage && error.errorMessage.indexOf("State mismatch") > -1) {
                        console.log("state mismatch");
                        try {
                            emailActivationRedirect();
                        } catch (err) {
                            console.log(err);
                        }
                    }
                });
        }
    }

**Comment by tnorling** [comment] 2022-09-01 17:18
@deepti1805 Please configure the logger as shown in [this sample configuration](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/07540895a6a2e96009fcc9bcf85af10c632826e7/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/authConfig.js#L11)

**Comment by tnorling** [comment] 2022-09-01 17:19
Please also update to 2.28.1. The version you are using is almost 2 years old.

**Comment by deepti1805** [comment] 2022-09-02 12:42
@tnorling - actually our website in production environments since 2 year back that’s why we are using this oldest version. I will let team know about updation of version but for now we need to resolve this issue.If we have any workaround please do let me know.

please find the logs that you needed 

[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - Emitting event: msal:handleRedirectStart [b2c__libs.js:54:221208]
[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. [b2c__libs.js:54:221208]
[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - Emitting event: msal:handleRedirectStart [b2c__libs.js:54:221208]
[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. [b2c__libs.js:54:221208]
[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - Emitting event: msal:handleRedirectEnd [b2c__libs.js:54:221208]
[Fri, 02 Sep 2022 12:33:23 GMT] :  : 1.7.1 : Info - Emitting event: msal:handleRedirectEnd [b2c__libs.js:54:221208]


WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [XgFpJQk:1:48660]

**Comment by tnorling** [comment] 2022-09-02 16:34
@deepti1805 So many changes have been made in the last 2 years that it's very likely this has been resolved in a newer version. Please update and then come back to us if it's still an issue in the latest version.

**Comment by deepti1805** [comment] 2022-09-05 11:01
@tnorling - updated to latest version but still got stuck with #state. Please check the logs.

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - handleRedirectPromise called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - getAllAccounts called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Info - Emitting event: msal:handleRedirectStart b2c__libs.js:54:221208

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getCachedNativeRequest called b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getCachedNativeRequest: No cached native request found b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - handleRedirectPromise - acquiring token from web flow b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : [2a5c494a-9e13-4970-8cea-8ae9b5faea9c] : msal.js.browser@2.28.1 : Verbose - initializeServerTelemetryManager called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : [2a5c494a-9e13-4970-8cea-8ae9b5faea9c] : msal.js.browser@2.28.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. b2c__libs.js:54:221208

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - handleRedirectPromise called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - getAllAccounts called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Info - Emitting event: msal:handleRedirectStart b2c__libs.js:54:221208

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getCachedNativeRequest called b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getCachedNativeRequest: No cached native request found b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - handleRedirectPromise - acquiring token from web flow b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : [cfe8dce6-723c-46b7-bb1a-49e604e93bd2] : msal.js.browser@2.28.1 : Verbose - initializeServerTelemetryManager called b2c__libs.js:54:221263

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage b2c__libs.js:54:221355

[Mon, 05 Sep 2022 10:54:39 GMT] : [cfe8dce6-723c-46b7-bb1a-49e604e93bd2] : msal.js.browser@2.28.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. b2c__libs.js:54:221208

[Mon, 05 Sep 2022 10:54:39 GMT] : @azure/msal-browser@2.28.1 : Info - Emitting event: msal:handleRedirectEnd

**Comment by tnorling** [comment] 2022-09-06 16:58
@deepti1805 

>  [Mon, 05 Sep 2022 10:54:39 GMT] : [cfe8dce6-723c-46b7-bb1a-49e604e93bd2] : msal.js.browser@2.28.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. b2c__libs.js:54:221208

This line indicates what the problem is. MSAL doesn't think there is any interaction currently in progress, which means that temporary cache items in `sessionStorage` are not present. Please debug and confirm that your application is not clearing `sessionStorage`

**Closed as completed** 2022-09-19 01:01 UTC
Labels: question, msal-browser, no-issue-activity, Needs: Author Feedback, public-client
