### ISSUE TITLE
x-frame-deny  with Angular PWA on iOS after disabling ITP

### ISSUE THREAD

**Issue by dcokely7** [AzureAD/microsoft-authentication-library-for-js#1353] opened 2020-03-05 23:53 UTC
## Library
- [x ] `msal@1.2.1`

## Framework
Angular 8
angular/pwa": "^0.802.0"

## Description
Using B2C login with an AAD tenant as the identity provider, the newer b2clogin.com based url (instead of *onmicrosoft.com) for the auth response in the iframe results in the x-frame-options deny when acquiring a token (slient) in a PWA on iOS only.  Using Safari directly (not bookmarking) on iOS works fine after turning off ITP, and without making any changes other than bookmarking the PWA, it starts having the x-frame-options deny.  The PWA also works without issue on iOS if the authresp is the *microsoftonline.com based url, its only the bc2login.com based url that causes this issue.

## Security
no

## Regression
It worked in the soon to be deprecated *onmicrosoft.com based auth response.

## Configuration
 this.userAgent = new Msal.UserAgentApplication(
            {
                auth: {
                    clientId: authKeys.audience,
                    authority: authKeys.authority,
                    validateAuthority: false, 
                    redirectUri: location.origin, // root app url
                    postLogoutRedirectUri: location.origin, /// root app url
                },
                cache: {
                    cacheLocation: 'sessionStorage'
                },
                system: {
                    // This is the number of milliseconds of inactivity in the Iframe before a token renewal
                    // response from Azure AD is considered timed out. The default value is 6 seconds
                    loadFrameTimeout: 30000,
                    logger: new Msal.Logger((level, message) => {
                        switch (level) {
                            case Msal.LogLevel.Error:
                                console.error(message);
                                break;
                            case Msal.LogLevel.Warning:
                                console.warn(message);
                                break;
                            case Msal.LogLevel.Info:
                            case Msal.LogLevel.Verbose:
                            default:
                                console.log(message);
                                break;
                        }
                    }, { level: Msal.LogLevel.Verbose })
                },
            }
        );
![Screen Shot 2020-03-05 at 5 25 03 PM](https://user-images.githubusercontent.com/17841245/76036158-5bf3ab80-5f11-11ea-91c3-d7cda274d64d.png)

## Expected behavior
response is not blocked

## Browsers
PWA on iOS

**Comment by jennyf19** [comment] 2020-03-06 17:45
@jasonnutter @sameerag @DarylThayil

**Comment by DarylThayil** [comment] 2020-03-10 00:48
Can you confirm one thing? If you call Acquire Token Silent and get a catch from Xframes Deny, can you try acquire Token Popup and see if this works and if it does, is it because interaction was required?

**Comment by jasonnutter** [comment] 2020-03-10 01:01
@dcokely7 To confirm, you receive the `X-FRAME-DENY` header when using b2clogin.com and your site is used as a PWA? And if you either use the site in normal Mobile Safari with ITP enabled, or use `onmicrosoft.com`, it works as expected?

If so, I am guessing that when you install and use a site as a PWA on iOS, ITP is turned on (I will find out to confirm). If so, unfortunately, I don't think there is anything we can do in the current version of MSAL, as our library relies on third-party cookies, and ITP disables third-party cookies for domains it thinks are trackers (and I betting that Safari thinks `b2clogin.com` is a tracker, but `*.onmicrosoft.com` isn't).

The [next version of MSAL](https://www.npmjs.com/package/@azure/msal-browser) (currently in development) will not rely on third-party cookies, which will allow it to be used when ITP is enabled.

**Comment by dcokely7** [comment] 2020-03-10 19:55
@jasonnutter to your first point, Safari on mobile still requires ITP disabled (for both onmicrosoft.com and b2clogin), but everything works fine once thats turned off. PWA works with onmicrosoft.com but not b2clogin. 

I agree its almost like the in-app browser (or whatever the PWA is rendered in, since its not a full safari) always has ITP enabled, regardless of what the user selects. At least on full Safari you can turn off ITP and the flow works fine. 

Is there any way to enable the onmicrosoft.com url for new b2c tenants, given the deprecated url works in all scenarios?

**Comment by jasonnutter** [comment] 2020-03-10 20:11
@dcokely7 
>Is there any way to enable the onmicrosoft.com url for new b2c tenants, given the deprecated url works in all scenarios? 

Doesn't look like it, unfortunately: https://azure.microsoft.com/en-us/updates/b2c-deprecate-msol/

**Comment by jasonnutter** [comment] 2020-03-26 22:33
> I agree its almost like the in-app browser (or whatever the PWA is rendered in, since its not a full safari) always has ITP enabled, regardless of what the user selects. 

I confirmed with a Webkit engineer that this is the case. See this blog for more details:
https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

**Comment by jasonnutter** [comment] 2020-03-26 22:45
Closing, as no further action at this time.

**Closed by jasonnutter** 2020-03-26 22:45 UTC
Labels: b2c, bug
