### ISSUE TITLE
MSAL library accessTokenSilent returns ClientAuthError in Firefox

### ISSUE THREAD

**Issue by malvica** [AzureAD/microsoft-authentication-library-for-js#1724] opened 2020-05-28 21:06 UTC
Hello,
My team has developed an office add-in for Outlook online and are using **MSAL** library **acquireTokenSilent** to get the token.
Using outlook online in **Firefox browser,** creating a new message in Pop-out window, user clicks on our add-in we make a call to acquireTokenSilent which returns **ClientAuthError: User Login is required.**
The same works when a new message is opened in in-line mode inside Outlook online in Firefox.
All other browsers work fine as well, the issue is only seen in Firefox.

Thanks

**Comment by jasonnutter** [comment] 2020-06-02 18:30
@malvica This error is thrown when the user is not logged in (i.e. the UserAgentApplication has no context of the user's session). This can be resolved by calling `loginPopup` or `loginRedirect`. Have you tried that?

**Comment by malvica** [comment] 2020-06-09 16:35
Hello @jasonnutter ,
sorry for the late reply. I am indeed logged in to my Outlook Online account. I create a new email open it in a new pop-out window and try to load my add-in where I always get this error and yes we are indeed using acquireMsTokenPopup() where we get a quick popup that disappears immediately itself and gets the token.
Doing the same in a non-pop out window works fine. Our concern is why acquireMSTokenSilent doesn;t work in Firefox when a new message is opened in a separate window whereas works fine when a new message is opened inline.

**Comment by jasonnutter** [comment] 2020-06-09 16:43
> Our concern is why acquireMSTokenSilent doesn;t work in Firefox when a new message is opened in a separate window whereas works fine when a new message is opened inline.

Does this happen in normal windows or in private windows? Or both?

**Comment by malvica** [comment] 2020-06-09 16:52
I have tried this is in private window only haven't tried it in a normal one yet, will give it a quick try.

**Comment by malvica** [comment] 2020-06-09 17:13
Hi, 
so, in firefox it's happening for both InPrivate and normal window. 
In chrome no errors and popups for both Incognito and normal window

**Comment by malvica** [comment] 2020-06-11 10:32
Hello @jasonnutter, that didn't help either. I even tried enabling all cookies still it fails for acquireMSTokenPopup

**Comment by jasonnutter** [comment] 2020-06-17 01:06
@malvica Can you please share a screenshot of your Firefox settings for cookies? Thanks!

**Comment by malvica** [comment] 2020-06-17 15:47
Hello @jasonnutter , here is the screenshot:
![image](https://user-images.githubusercontent.com/50148375/84919550-10b07380-b090-11ea-9a32-130c
d78944e6.png)

I tested with all of them disabled.

**Comment by malvica** [comment] 2020-06-17 15:49
Hello @jasonnutter here is the screenshot:

![Annotation 2020-06-17 114838](https://user-images.githubusercontent.com/50148375/84919946-8e747f00-b090-11ea-89b0-09d5c4ad5cb3.png)

**Comment by jasonnutter** [comment] 2020-06-18 17:40
@malvica I am unable to reproduce that error with those settings. Do you have any extensions that may be blocking cookies?

**Comment by malvica** [comment] 2020-06-19 14:06
Hi @jasonnutter , I don't have any extensions loaded in firefox browser. Multiple people are able to reproduce this on their machines including our customers.
Did you try loading the new message in a Pop-out window?

**Comment by jasonnutter** [comment] 2020-06-20 00:30
@malvica I did not try that. It is possible this is a result of new privacy settings in Firefox: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop

Given this is browser specific and may be related to privacy settings in the browser, I don't think there's much we can do in MSAL.js v1, as the server requires those cookies and MSAL.js itself cannot set them. Keep in mind, your application should contain fallback logic to handle these errors regardless, as acquireTokenSilent can fail for many reasons outside the control of the library.

In MSAL.js v2 (@azure/msal-browser), we are switching to the Auth Code Flow, which does not need third-party cookies. See #1000 for more info.

**Comment by tnorling** [comment] 2020-07-21 01:06
Closing due to inactivity and no further action needed from the MSAL team

**Closed by tnorling** 2020-07-21 01:06 UTC
Labels: bug, no-issue-activity
