### ISSUE TITLE
Azure B2C - MSAL.js Session Behavior with Multiple Tabs

### ISSUE THREAD

**Issue by nilact** [AzureAD/microsoft-authentication-library-for-js#4369] opened 2022-01-06 10:05 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

We're using MSAL.js V2 to authenticate with Azure B2C AD and are able to retrieve the token, renew it, and log out the user of the system. At present, we're using sessionStorage as recommended [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-is-the-difference-between-sessionstorage-and-localstorage) and as explained [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-browser-tabs) to prevent sharing a session across multiple tabs.

However, we're facing the issue mentioned [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2025). I would like to know exactly what has been fixed as per the last comment of jo-arroyo in the thread. If it has not been fixed, when can we expect the fix? Is there any workaround to make it work with sessionStorage?

Also, I couldn't find anything with respect to login_hint for the B2C scenarios. Is this [document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent) applicable to B2C? If yes, what are the possible values for the same?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment] 2022-01-10 18:11
@nilact This behavior is caused by either:

1. Your application is not providing a `loginHint`
2. B2C is not forwarding the `loginHint` to your federated IDP

Point 2 was previously not implemented on the B2C server side. This is now configurable in custom policies and has been implemented for _some_ IDPs in basic policies. This was the "fix" referenced in the issue you linked. If you need help configuring your custom policy to forward the `login_hint` to your federated IDP please reach out to [B2C Support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options).

> Also, I couldn't find anything with respect to login_hint for the B2C scenarios. Is this document applicable to B2C? If yes, what are the possible values for the same?

Yes this document is applicable to B2C. The `login_hint` is typically the user's email address which you can retrieve from the `username` field on the `AccountInfo` object returned by all the `acquireTokenXXX` and `loginXXX` APIs. If this field is not populated you will need to [configure your B2C policy to return the emails claim](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-getaccountbyusername-returning-null-even-though-im-signed-in)

**Comment by nilact** [comment] 2022-01-11 12:42
@tnorling 

I checked that login_hint works with the email address by hardcoding it. However, could you please provide an example of using it with MSAL.js considering the below code snippet: 

```
var loginRequest = {
    scopes: ["user.read", "mail.send"], // optional Array<string>
    login_hint: myemail@address.com //how to set this value even before log-in?
};

try {
    msalInstance.loginRedirect(loginRequest);
} catch (err) {
    // handle error
}
```
What are the possible values for login_hint apart from email address? We only want at this stage to prompt the user to login into a new tab while using the sessionStorage. We don't want to pre-populate the username field at this stage. 




I think that this fact needs to be mentioned in the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-browser-tabs) as MSAL.js doesn't ask the user to log in while using sessionStorage unless we use login_hint.

**Comment by tnorling** [comment] 2022-01-11 17:58
@nilact 

> What are the possible values for login_hint apart from email address? We only want at this stage to prompt the user to login into a new tab while using the sessionStorage. We don't want to pre-populate the username field at this stage.

`login_hint` is only email address for B2C scenarios. If all you want to do is force a sign-in prompt and skip SSO you can provide `prompt: "login"` but that is different from the issue described in the issue you linked. I'm a bit confused, it's not entirely clear to me the behavior you are experiencing vs. what you expect to experience. Could you please describe specifically the issue you're facing?

> I think that this fact needs to be mentioned in the documentation here as MSAL.js doesn't ask the user to log in while using sessionStorage unless we use login_hint.

Are you saying without providing `login_hint` you are getting SSO but with `login_hint` you are being asked to sign-in? That's not what I would expect. `login_hint`, when provided should give you SSO into an existing session for that username, if possible. If no session exists for that username the email field will be pre-populated with the user's email. If you are experiencing behavior that is different you should speak with B2C support as this is the part they control.

If the goal is to sign the same user into both tabs the easiest solution is just to use localStorage. If the goal is to sign **different** users into each tab you should use the `prompt` parameter to force the sign-in page and provide either `loginHint` or the account object on each acquireToken API call thereafter to ensure you get tokens for the correct user.

**Comment by nilact** [comment] 2022-01-12 10:22
> that is different from the issue described in the issue you linked. 

I thought that the Azure B2C team had not resolved the issue yet, and that is why sessionStorage is not working the way it is mentioned in the documentation. But as you confirmed, the Azure B2C team fixed the issue, and it prompts the user to log in while using sessionStorage along with login_hint or prompt.

>Are you saying without providing login_hint, you are getting SSO, but with login_hint, you are being asked to sign in?

Yes and Yes.

>If all you want to do is force a sign-in prompt and skip SSO you can provide prompt: "login" but that is different from the issue described in the issue you linked. 

Thanks, this works. I wanted to use sessionStorage, and it should behave the way it is described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-browser-tabs). One cannot have the behavior described in the documentation unless he uses login_hint/prompt parameter as you explained. And I believe it might create confusion as to why sessionStorage is not working.

**Comment by tnorling** [comment] 2022-01-12 18:28
@nilact Ah I see the confusion. There are 2 places a user's authentication context is held: 
1. In your application (e.g. browser storage) 
2. On the authentication server (e.g. cookies)

`localStorage` and `sesisonStorage` only control the boundary for your application's context and does not affect the server context.

In the doc, this line: 

> By default, MSAL.js uses sessionStorage, which doesn't allow the session to be shared between tabs. To get SSO between tabs, make sure to set the cacheLocation in MSAL.js to localStorage as shown below.

should instead read: 

> By default, MSAL.js uses sessionStorage, which doesn't allow storage to be shared between tabs. To share authentication state between tabs, make sure to set the cacheLocation in MSAL.js to localStorage as shown below.

I'll see if we can get this doc updated to make this more clear. Did I answer all your questions? Has your issue been resolved?

**Comment by nilact** [comment] 2022-01-13 07:43
@tnorling 

Thanks for clearing the air.

Yes, my issue is resolved now after using the prompt parameter as you mentioned.

Regarding documentation, it seems that the Azure B2C session cookie is having precedence on sessionStorage if you don't use prompt/login_hint. The authentication would be shared across tabs even if you use sessionStorage. This is what I experienced and it should be mentioned either in the documentation or in the FAQ to avoid any confusion in the future.

**Comment by tnorling** [comment] 2022-01-13 21:51
@nilact It's not really a question of "precedence". These are 2 completely different things that control different behaviors. Taking another look at the doc you mentioned, it does explain both of these (application storage vs. server session cookie) albeit without the `prompt` control bit. I agree the wording here could be improved to make the difference more clear but the doc is also pretty out of date (still references MSAL.js v1) and should get an overhaul anyway. 

@mmacy How can we help get [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso) updated with MSAL.js v2 code snippets and improved language?

**Comment by mmacy** [comment] 2022-01-14 19:40
@tnorling Two options:

1. Submit a PR to make the update - [**CLICK ME** to overhaul MSAL.js SSO doc](https://github.com/MicrosoftDocs/azure-docs-pr/edit/master/articles/active-directory/develop/msal-js-sso.md?description=Overhauling%20with%20MSAL.js%20v2%20information) ⬅️ **Recommended**!
    I'll help PR review, edit, and usher the PR through. This is the recommended option.
2. Open an issue on the doc, provide as much of the information (content and/or links) that should go into the update, and I'll close the docs issue and add it to the ADO backlog.
    ![image](https://user-images.githubusercontent.com/13394541/149574943-e1a7b486-ecaa-49b2-8f98-ee557166e82f.png)

I recommend Option 1 because the docs backlog is lllooonnnggg.

**Comment by nilact** [comment] 2022-01-18 04:31
@tnorling 

Thanks for responding and clearing up things. Much appreciate all your help. :)

It would be great if the documentation could be updated with MSAL.js v2 code snippets and differences.

**Comment by derisen** [comment] 2022-10-17 18:39
Documentation has ben updated to clarify this. Closing as completed.

**Closed as completed by derisen** 2022-10-17 18:39 UTC
Labels: b2c, documentation, msal-browser, msal-react
