### ISSUE TITLE
state_mismatch error when multiple acquireTokenSilent are fired "simultaneously"

### ISSUE THREAD

**Issue by sidecus** [AzureAD/microsoft-authentication-library-for-js#2246] opened 2020-09-09 04:44 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
I am currently using @azure/msal-browser@2.1.0 PKCE flow (redirect) in my React app. From time to time I am getting the state_mismatch error, see below (please ignore the call stack):

![image](https://user-images.githubusercontent.com/4399408/92554877-3a0a1700-f21b-11ea-83c4-3b429d79ad43.png)

I tried to debug a bit and believe that it can happen when multiple acquireTokenSilent calls are fired "simultaneously".

To be more specific, I have two different components monitoring "signedin" flag in redux store and when it's true they both have useEffect calls to try to get an access token (with the same scope) and then call my backend. I tried to comment one of them out and things started working.

Furthermore, once access token is cached, things also work well even though I added the 2nd call back - this is understandable since there is no real "async" operations here.

I am not familiar with MSAL.js code, but if we are putting something into local storage for acquireTokenSilent (like nonce) using the same cache key for different calls, it seems a bug to me for my scenario.
IMHO there should be some "synchronization" on this kind of operations within msal. Or, just use different cache keys.

## Error Message
msalauthentication.ts:95 state_mismatch: State mismatch error. Please check your network. Continued requests may cause cache overflow.

## Security
- [ ] Is this issue security related?
NO

## Regression
- [ ] Did this behavior work before? 
N/A

## MSAL Configuration
not really related

## Reproduction steps
Fire two acquireTokenSilent calls "simultaneously" upon log in success.

## Expected behavior
All acquireTokenSilent calls should not interfere with each other - we are not talking about acquireTokenRedirect here.

## Browsers/Environment
doesn't really matter, but I am using new Edge.

**Comment by sidecus** [comment] 2020-09-09 05:31
BTW, I just added a poor man's sync lock on top of msal to guard acquireTokenSilent, and this issue is resolved.

**Comment by jmckennon** [comment] 2020-09-09 16:16
Closing this as a duplicate of #2175. As you mentioned, mitigation for now is to make the request in serial.

**Closed by jmckennon** 2020-09-09 16:16 UTC
Labels: bug

**Comment by AndreiZe** [comment] 2020-09-09 19:33
@jasonnutter , @jmckennon , do you have a timeline on 2.1.1 release? We had to roll back to using 1.x in our app due to this issue: proposed workaround (make token fetches serial) causes perf regression.
