### ISSUE TITLE
Unexpected TypeError from SilentFlowClient.ts

### ISSUE THREAD

**Issue by rstutton** [AzureAD/microsoft-authentication-library-for-js#2119] opened 2020-08-08 04:48 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
msal2.0.1

## Framework
no framework. Custom spa in Typescript using jquery, bootstrap

## Description
Called acquireTokenSilent(). It threw a TypeError "Cannot read property 'homeAccountId' of null at SilentFlowClient..." which was unexpected. The error was logged but the token acquistion failed.
I had devtools open so could see the line, which is this one "const homeAccountId = cachedAccount.homeAccountId;" at line 54 of https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c9603bdcda2b1958d128f5fe7073447ac49cfc81/lib/msal-common/src/client/SilentFlowClient.ts

## Error Message
Cannot read property 'homeAccountId' of null at SilentFlowClient...

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Once I got passed the issue (see below) it hasn't reoccurred.
```js
export async function getTokenPopup( request: SilentRequest): Promise<boolean>
{
  request.account = loggedinAccount;

  try
  {
    // silently acquire the access token
    let tokenResponse = await msalInstance.acquireTokenSilent(request);
    onLogin(tokenResponse);
    return true;
  }
  catch(error)
  {
    console.log("silent token acquisition fails.");

    // we are being asked to acquire token interactively
    if (error instanceof msal.InteractionRequiredAuthError ||
      // Cannot read property 'homeAccountId' of null at SilentFlowClient
      // *** added this to get passed the issue ***
        error instanceof TypeError)
    {
      console.log("acquiring token using popup");

      try
      {
        let tokenResponse = await msalInstance.acquireTokenPopup(request);
        onLogin(tokenResponse);
        return true;
      }
      catch(error)
      {
        console.error(error);
        return false;
      }
    }
    console.error(error);
    return false;
  }
}```

## Expected behavior
Previously the call either succeeded or, as anticipated it could have thrown a InteractionRequiredAuthError.
I updated my code to catch the typeerror, and then called (as for the InteractionRequiredAuthError)  acquireTokenPopup and the code succeeded.

## Browsers/Environment
- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment] 2020-08-11 00:04
Hi @rstutton ! The issue you are seeing seems related to #2099, which we are looking into. We'll follow up when we have an update or if we need more information. Thanks for raising the issue.

**Comment by technical-boy** [comment] 2020-08-11 16:44
Closing this since it's a duplicate of #2099.

**Closed by technical-boy** 2020-08-11 16:44 UTC
Labels: bug, known-issue, msal-browser
