### ISSUE TITLE
React with MSAL for Azure AD auth. MFA Redirects and acquireTokenSilent  overwrite scopes

### ISSUE THREAD

**Issue by Tzvetelin88** [AzureAD/microsoft-authentication-library-for-js#2258] opened 2020-09-10 08:38 UTC
Hello I have some questions regarding MFA and Redirecting and acquireTokenSilent where scopes are overwrite when using: 
 GRAPH_SCOPES.APP and GRAPH_SCOPES.USER_READ together.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`  - exact version is "msal": "^1.3.0"

## Description
We are using "react": "16.12.0" with MSAL library for Azure AD authentication.

First question is regarding acquireTokenRedirect and MFA. When user clicks Login on the application he is redirected to Microsoft Page for User and Pass authentication and then redirected back to App page, but when user is outside company network he needs to use MFA as second step of authentication. 
The problem here is MFA is not happening on Microsoft page, but it happens on Application Page and MFA appears in Popup.
How can I make MFA to happen on Microsoft page and after that to be redirected to Application side?
P.S. here we get sometime next error:
> Loading frame has timed out after: 6 seconds
> Non-interactive error: token_renewal_error

Second question is regarding acquireTokenSilent. As we need to get some user data from the Azure AD as User Name, User Email, we also need to get user Image. When using acquireTokenSilent with:
GRAPH_SCOPES.APP,
GRAPH_SCOPES.USER_READ, - generates accessToken with access to fetchMsGraphPhoto.
is seems that in the tokenResponse object, value of "scopes" is overwrite if we using APP and USER_READ together. ([Screenshot](https://drive.google.com/file/d/10Uy9BlJIjkVWP5hFVeLvyixfuKU8Lpj9/view?usp=sharing)). 
We have fixed this issue with two different calls to acquireToken with two different GRAPH_REQUESTS parameters:
const tokenResponse = yield acquireToken(GRAPH_REQUESTS.LOGIN);
const tokenResponse1 = yield acquireToken(GRAPH_REQUESTS.GROUP);

To have more visibility I will upload some code here.
msalConfiguration:

```
import { UserAgentApplication } from "msal";

export const requiresInteraction = errorMessage => {
    if (!errorMessage || !errorMessage.length) {
        return false;
    }

    return (
        errorMessage.indexOf("consent_required") > -1 ||
        errorMessage.indexOf("interaction_required") > -1 ||
        errorMessage.indexOf("login_required") > -1
    );
};

export const fetchMsGraph = async (url, method, accessToken, body = null) => {
    let response;
    if (body) {
        response = await fetch(url, {
            method: method,
            body:JSON.stringify(body),
            headers: {
                Authorization: `Bearer ${accessToken}`,
                'Content-Type': "application/json"
            }
        });
    } else {
        response = await fetch(url, {
            method: method,
            headers: {
                Authorization: `Bearer ${accessToken}`,
                'Content-Type': "application/json"
            }
        });
    }
    

    return response.json();
};


export const fetchMsGraphPhoto = async (url, accessToken) => {
    let response;
 
    response = await fetch(url, {
        headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': "image/jpg"
        }
    });
    

    return response;
};

export const isIE = () => {
    const ua = window.navigator.userAgent;
    const msie = ua.indexOf("MSIE ") > -1;
    const msie11 = ua.indexOf("Trident/") > -1;

    // If you as a developer are testing using Edge InPrivate mode, please add "isEdge" to the if check
    // const isEdge = ua.indexOf("Edge/") > -1;

    return msie || msie11;
};

export const GRAPH_SCOPES = {
    OPENID: "openid",
    PROFILE: "profile",
    USER_READ: "User.Read",
    APP: "api://<id>/<endpoint>.all.all",
    MAIL_READ: "Mail.Read"
};

export const GRAPH_ENDPOINTS = {
    MEGROUPS: "https://graph.microsoft.com/v1.0/me/checkMemberObjects",
    MAIL: "https://graph.microsoft.com/v1.0/me/messages",
    PHOTO: "https://graph.microsoft.com/v1.0/me/photo/$value"
};

export const GRAPH_REQUESTS = {
    LOGIN: {
        scopes: [
            GRAPH_SCOPES.APP,
            GRAPH_SCOPES.USER_READ,
            GRAPH_SCOPES.OPENID,
            GRAPH_SCOPES.PROFILE,
        ]
    },
    GROUP: {
        scopes: [GRAPH_SCOPES.USER_READ]
    }
};

export const msalApp = new UserAgentApplication({
    auth: {
        clientId: "<client_id>",
        authority: "https://login.microsoftonline.com/<id>",
        validateAuthority: true,
        // postLogoutRedirectUri: "http://localhost:3000/",
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE()
    },
    system: {
        navigateFrameWait: 0,
        logger: {
            error: console.error,
            errorPii: console.error,
            info: console.log,
            infoPii: console.log,
            verbose: console.log,
            verbosePii: console.log,
            warning: console.warn,
            warningPii: console.warn
        }
    }
});
```

newAuthRedux file : 
```
if(!msalApp.getAccount()) {
    yield msalApp.loginRedirect(GRAPH_REQUESTS.LOGIN);
} else {
    const tokenResponse = yield acquireToken(GRAPH_REQUESTS.LOGIN);
    const tokenResponse1 = yield acquireToken(GRAPH_REQUESTS.GROUP);
    let reader;
    if (tokenResponse1) {
        const graphProfile = yield fetchMsGraph(
            GRAPH_ENDPOINTS.MEGROUPS,
            "post",
            tokenResponse1.accessToken,
            {
                "ids": ["<id1>,<id2>"]
            }
        )
        if (graphProfile) {
            isAdmin = graphProfile.value.includes("<id_admin>");
        }
        const graphProfile2 = yield fetchMsGraphPhoto(
            GRAPH_ENDPOINTS.PHOTO,
            tokenResponse1.accessToken
        )
        reader = yield graphProfile2.body.getReader();
        let stream = yield new ReadableStream({
            start(controller) {
                return pump();
                function pump() {
                    return reader.read().then(({ done, value }) => {
                        // When no more data needs to be consumed, close the stream
                        if (done) {
                            controller.close();
                            return;
                        }
                        // Enqueue the next data chunk into our target stream
                        controller.enqueue(value);
                        return pump();
                    });
                }
            }
        });
        //get and transform image to Base64 and save it to the redux, so we do not lose it on page refresh! 
        let response = yield new Response(stream);
        let blob = yield response.blob();

        const blobToBase64 = blob => {
            const reader = new FileReader();
            reader.readAsDataURL(blob);
            return new Promise(resolve => {
                reader.onloadend = () => {
                    resolve(reader.result);
                };
            });
        };

        yield blobToBase64(blob).then(res => {
            photoURL = res;
        });
       //get and transform image to Base64 ENDs  
    }
    yield put(authSuccess(
        tokenResponse.idToken.rawIdToken,
        tokenResponse.account.userName,
        tokenResponse.accessToken,
        tokenResponse.account.name,
        tokenResponse.idTokenClaims.email,
        tokenResponse.idTokenClaims.oid,
        tokenResponse.expiresOn.toISOString(),
        isAdmin,
        photoURL)
    );  
}
```

**Comment by jmckennon** [comment] 2020-09-11 16:36
> The problem here is MFA is not happening on Microsoft page, but it happens on Application Page and MFA appears in Popup.
How can I make MFA to happen on Microsoft page and after that to be redirected to Application side?

If you call `acquireTokenRedirect` and MFA is required, MFA will be performed on the Microsoft page and not in a popup. Can you clarify what you're seeing, potentially with screenshots? Additionally, make sure that `acquireTokenPopup` isn't accidentally being called somewhere.

>Second question is regarding acquireTokenSilent. As we need to get some user data from the Azure AD as User Name, User Email, we also need to get user Image. When using acquireTokenSilent with:
GRAPH_SCOPES.APP,
GRAPH_SCOPES.USER_READ, - generates accessToken with access to fetchMsGraphPhoto.
is seems that in the tokenResponse object, value of "scopes" is overwrite if we using APP and USER_READ together.

This behavior is by design. If you need access tokens for two different resources (e.g., Microsoft Graph and your backend API) you need two separate `acquireToken` calls as access tokens are scoped to a specific resource and you cannot get a single access token that can be used for multiple resources.

**Comment by Tzvetelin88** [comment] 2020-09-16 08:34
Hello and sorry for the late response. Regarding "acquireTokenPopup". I do not have anywhere "acquireTokenPopup". I have uploaded all my code above. 

Here are the steps and issue with popup:

**1. Step one on application side click Login:**
![image](https://user-images.githubusercontent.com/9692941/93312608-1729c500-f810-11ea-85e2-72cbab43263f.png)

**2. Step two redirecting to MS page:**
![image](https://user-images.githubusercontent.com/9692941/93312640-214bc380-f810-11ea-8bd9-40f516f786f1.png)

**3. Step three go back to Application Side:**
![image](https://user-images.githubusercontent.com/9692941/93312716-36285700-f810-11ea-8fe3-af73e184f869.png)



And the popup appears here and not on MS side. 

Here is my function of "acquireToken":

```
async function acquireToken(request, redirect) {
    return msalApp.acquireTokenSilent(request)
}
```

**Comment by Tzvetelin88** [comment] 2020-09-18 07:26
Reading more it seems "acquireTokenSilent" do not support MFA? So only way is to use MFA on Application Side in POPUP?

**Comment by jmckennon** [comment] 2020-09-21 18:01
> Reading more it seems "acquireTokenSilent" do not support MFA? So only way is to use MFA on Application Side in POPUP?

Yes, this is correct. If MFA is required, you must invoke one of the interactive methods to resolve.

**Comment by Tzvetelin88** [comment] 2020-09-23 07:21
Yep.... 
I found out that there is MSAL.js 2.x apps: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications  and now testing  "msal-browser-react". 
It seems it's supporting MFA on MS page and working much better with React and one page applications. Also it's supporting handleRedirectPromise.

Not sure what is the core difference between "msal-browser-react" and "msal-common" ?

I found this example: https://www.linkedin.com/pulse/using-authorization-code-flow-pkce-azure-ad-from-react-pablo-cibraro/?articleId=6674740637935448064 and Git: https://github.com/pcibraro/msal-browser-react. First tests showing that this is working with redirection and MFA on MS page.

Also very good documentation regarding classes: https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/classes/_src_app_publicclientapplication_.publicclientapplication.html#logout

**Comment by jmckennon** [comment] 2020-09-24 21:28
> I found out that there is MSAL.js 2.x apps:

Yes, there is a version 2 of our library named `msal-browser`. We recommend most users to upgrade to get more advanced support and features. We have a [migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#migrating-from-previous-msal-versions) for users looking to upgrade.

> and now testing "msal-browser-react".

`msal-browser-react` is not a library/app that we own, that was written by another user as a wrapper for our `msal-browser` library. Creating our own version of a react library like `msal-react` is on our radar, but we don't have a release date for something like this yet.

> Not sure what is the core difference between "msal-browser-react" and "msal-common" ?

To be clear: `msal-common` is our own common library. Both `msal-browser` and `msal-node` consume `msal-common`, as will future libraries that we create.

**Comment by Tzvetelin88** [comment] 2020-09-25 08:31
Thanks so much. I have switched to MSAL 2.x and now everything works fine. You can close this ticket.

**Comment by jmckennon** [comment] 2020-09-28 19:54
Awesome, happy to help. Closing now as the problem has been solved.

**Closed by jmckennon** 2020-09-28 19:54 UTC
Labels: question
