### ISSUE TITLE
Getting startPerformanceMeasuremeant is not a function error  

### ISSUE THREAD

**Issue by tickoosunny** [AzureAD/microsoft-authentication-library-for-js#5579] opened 2023-01-17 09:53 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.51

### Public or Confidential Client?

Public

### Description

I am getting Error when I try to call method `instance.loginRedirect(authRequest)` in react , where 

```
const authRequest = {
    scopes: ["User.Read"],
  };
```
the error is "typeError: this.startPerformanceMeasuremeant is not a function"

### Error Message

![image](https://user-images.githubusercontent.com/20644008/212864602-06d856b7-4e16-465a-b3ee-d4f44b65fa06.png)

### Msal Logs

Uncaught (in promise) TypeError: this.startPerformanceMeasuremeant is not a function
    at PerformanceClient.startMeasurement (PerformanceClient.js?20e5:50:1)
    at BrowserPerformanceClient.startMeasurement (BrowserPerformanceClient.js?7cdd:43:1)
    at RedirectClient.eval (StandardInteractionClient.js?4d15:223:1)
    at step (_tslib.js?89f4:87:1)
    at Object.eval [as next] (_tslib.js?89f4:68:46)
    at eval (_tslib.js?89f4:61:1)
    at new Promise (<anonymous>)
    at __awaiter (_tslib.js?89f4:57:1)
    at StandardInteractionClient.getDiscoveredAuthority (StandardInteractionClient.js?4d15:217:25)
    at RedirectClient.eval (StandardInteractionClient.js?4d15:155:1)

### MSAL Configuration

```javascript
const config = {
    auth: {
      authority: initialState.appConfig.AUTHORITY,
      clientId: initialState.appConfig.CLIENT_ID,
      redirectUri: initialState.appConfig.REDIRECT_URI,
      postLogoutRedirectUri: initialState.appConfig.REDIRECT_URI,
    },
  };
```

### Relevant Code Snippets

```javascript
function AuthBarrier(props) {
  const { strings } = useContext(LangContext);
  const appInsights = useAppInsightsContext();
  const { instance, accounts, inProgress } = useMsal();
  const isAuthenticated = useIsAuthenticated();

  useEffect(() => {
    if (isAuthenticated && accounts && accounts.length > 0) {
      const account = accounts[0];
      instance.setActiveAccount(account);

      const { localAccountId } = account || {};
      appInsights.setAuthenticatedUserContext(localAccountId);
      // walkme required user id to use further details
      sessionStorage.setItem("msal_uid", localAccountId);
    }
  }, [isAuthenticated]);

  const authRequest = {
    scopes: ["User.Read"],
  };

  const loadingView = () => {
    return (
      <LoginPage>
        <Spinner />
      </LoginPage>
    );
  };

  const login = () => {
    if (!isAuthenticated) {      
      instance.loginRedirect(authRequest);
    }
  };

  if (inProgress !== InteractionStatus.None) {
    return loadingView();
  }

  if (!isAuthenticated) {
    return (
      <LoginPage>
        <Button
          data-testid="login-button"
          className="fs-login-button"
          onClick={login}
        >
          {strings.login.button}
        </Button>
      </LoginPage>
    );
  }

  return (
    <MsalAuthenticationTemplate
      interactionType={InteractionType.Popup}
      authenticationRequest={authRequest}
      loadingComponent={loadingView}
      errorComponent={
        <LoginPage>
          <LoginError message={strings.login.error} retry={login} />
        </LoginPage>
      }
    >
      {props.children}
    </MsalAuthenticationTemplate>
  );
}

AuthBarrier.propTypes = {
  children: PropTypes.node.isRequired,
};

export default AuthBarrier;
```

### Reproduction Steps

1) load the application from localhost
2) click on login button

### Expected Behavior

The call to loginRedirect should not throw this error and if it it does then this error should be communicated back to app gracefully.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

@azure/msal-browser": "^2.25.0, "@azure/msal-react": "^1.5.0"

### Source

External (Customer)

**Comment by hectormmg** [comment] 2023-01-17 20:08
Closing as duplicate of #5569

**Closed as completed by hectormmg** 2023-01-17 20:08 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client
