### ISSUE TITLE
acquireTokenSilent() even when called twice in a row, does two calls to authorize endpoint

### ISSUE THREAD

**Issue by jdudleyie** [AzureAD/microsoft-authentication-library-for-js#1586] opened 2020-05-02 21:52 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.3.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

React - CRA - "react-scripts": "3.4.1"
"react": "16.13.1",
"react-aad-msal": "2.3.5"

## Description

When either calling react-aad-msal's `getAccessToken()` or msal's `acquireTokenSilent()` twice in a row, each call results in a call to authorize endpoint, so it appears that the token is not being stored in the cache. I see there was a recent fix in this area, so not sure if it's related? https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1516

I noticed that when moving to, away and back to a route in my React App, it was making the call each time. Then I tried adding the same line twice in a row and it also resulted in two calls e.g.:

    let token = await AuthProvider.acquireTokenSilent({
          scopes: [
            'openid',
            'profile',
            'https://....onmicrosoft.com/f2d1e134-c045-4715-bef7-...../Users.Read',
          ],
        });
        token = await AuthProvider.acquireTokenSilent({
          scopes: [
            'openid',
            'profile',
            'https://....onmicrosoft.com/f2d1e134-c045-4715-bef7-...../Users.Read',
          ],
        });

Everything is working, a valid JWT is acquired and I can call my API, the only issue is that it calls this endpoint to get a new token every time I try to acquire a token for an API call.

## Security
Is this issue security related?

No.

## Regression
Did this behavior work before?

This is the first time I've tried it.

## Configuration
Please provide your MSAL configuration options.

This is the standard react-aad-msal config - I don't think it's an issue in that library as the same thing happens when calling acquireTokenSilent which they expose.

```js
import { LoginType, MsalAuthProvider } from 'react-aad-msal';

const currentHost =
  window.location.protocol +
  '//' +
  window.location.hostname +
  (window.location.port ? ':' + window.location.port : '');

// Msal Configurations
const config = {
  auth: {
    clientId: 'f2d1e134-c045-4715-bef7-d2c65a6ff364',
    authority:
      'https://rtsmarttagscom.b2clogin.com/rtsmarttagscom.onmicrosoft.com/b2c_1_signupsignin1',
    validateAuthority: false,
    redirectUri: currentHost,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
};

// Authentication Parameters
const authenticationParameters = {
  scopes: [
    'openid',
    'profile',
    'https://rtsmarttagscom.onmicrosoft.com/f2d1e134-c045-4715-bef7-d2c65a6ff364/Users.Read',
  ],
};

// Options
const options = {
  loginType: LoginType.Redirect,
};

export const AuthProvider = new MsalAuthProvider(
  config,
  authenticationParameters,
  options
);

```

## Reproduction steps

Hopefully it's easy to reproduce - I have not done anything special I think but if I can provide more information please let me know.

## Expected behavior

I expect the cached token to be used until it expired at least, to avoid unnecessary latency before every API call.

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

This is in Chrome, so not sure if browser specific.

**Comment by flieks** [comment] 2020-05-03 20:14
I think i am also having this but only when deployed to azure app service. Was working find on 1.2.2.

![image](https://user-images.githubusercontent.com/5032389/80923927-b3ce5780-8d86-11ea-809a-1d2038e697a0.png)

**Comment by jasonnutter** [comment] 2020-05-04 16:50
@jdudleyie Can you try making the call to `acquireTokenSilent` without including `openid` and `profile`?

**Comment by jdudleyie** [comment] 2020-05-04 19:40
Hi @jasonnutter - this works! Thanks 😃

**Comment by jasonnutter** [comment] 2020-05-04 20:37
@flieks The cancelled requests were likely done inside the hidden iframe when requesting the token, and were cancelled when the iframe was removed when the response was parsed. Is your app working otherwise?

**Comment by jasonnutter** [comment] 2020-05-04 20:38
@jdudleyie Great! Since your b2c scope is a custom scope, requests to get an access token for it should not include other scopes such as `openid profile` or MS graph scopes.

Closing, as original question was addressed.

**Closed by jasonnutter** 2020-05-04 20:38 UTC
Labels: bug

**Comment by flieks** [comment] 2020-05-06 13:20
@jasonnutter thanks alot. My app works locally but not in production. Worked with 1.2.2 in prod.
It is also opening popup to authenticate (but i never called acquireTokenPopup i think). 
And it seems the problem is the token is never in cache with each api call i do i get the token from acquireTokenSilent which should have it in cache right ?
![image](https://user-images.githubusercontent.com/5032389/81181604-fcfff080-8fac-11ea-8fa5-1669be57a980.png)

**Comment by jasonnutter** [comment] 2020-05-06 17:20
@flieks Can you try 1.3.0? Should have some fixes for cache bugs.

**Comment by flieks** [comment] 2020-05-07 09:50
@jasonnutter I am using 1.3.0. I did not have the issues with 1.2.2

**Comment by jasonnutter** [comment] 2020-05-07 16:52
@flieks Can you please open a new issue, thanks!
