### ISSUE TITLE
msal react typescript jest tests are failing

### ISSUE THREAD

**Issue by ranshine** [AzureAD/microsoft-authentication-library-for-js#6788] opened 2023-12-26 14:06 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.8

### Public or Confidential Client?

Public

### Description

```
   /Users/node_modules/.pnpm/@azure+msal-react@2.0.8_@azure+msal-browser@3.6.0_react@18.2.0/node_modules/@azure/msal-react/dist/index.js:3
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       7 |   RedirectRequest,
       8 | } from '@azure/msal-browser'
    >  9 | import {MsalProvider} from '@azure/msal-react'
         | ^
      10 |
      11 | // Config object to be passed to Msal on creation
      12 | export const msalConfig: Configuration = {

      at Runtime.createScriptFromCode (../../node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (../../packages/api/config/authConfig.ts:9:1)
      at Object.<anonymous> (../../packages/api/CustomApiClient.ts:3:1)
      at Object.<anonymous> (../../packages/api/index.ts:1:1)
      at Object.<anonymous> (src/hooks/useDashboard.ts:2:1)
      at Object.<anonymous> (src/hooks/index.ts:1:1)
      at Object.<anonymous> (src/screens/Home.tsx:2:1)
      at Object.<anonymous> (src/screens/index.ts:1:1)
      at Object.<anonymous> (src/__test__/Home.test.tsx:4:1)
```

### Error Message

```
   /Users/sgorle/PNPM_DRIFT_REPO/node_modules/.pnpm/@azure+msal-react@2.0.8_@azure+msal-browser@3.6.0_react@18.2.0/node_modules/@azure/msal-react/dist/index.js:3
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       7 |   RedirectRequest,
       8 | } from '@azure/msal-browser'
    >  9 | import {MsalProvider} from '@azure/msal-react'
         | ^
      10 |
      11 | // Config object to be passed to Msal on creation
      12 | export const msalConfig: Configuration = {

      at Runtime.createScriptFromCode (../../node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (../../packages/api/config/authConfig.ts:9:1)
      at Object.<anonymous> (../../packages/api/CustomApiClient.ts:3:1)
      at Object.<anonymous> (../../packages/api/index.ts:1:1)
      at Object.<anonymous> (src/hooks/useDashboard.ts:2:1)
      at Object.<anonymous> (src/hooks/index.ts:1:1)
      at Object.<anonymous> (src/screens/Home.tsx:2:1)
      at Object.<anonymous> (src/screens/index.ts:1:1)
      at Object.<anonymous> (src/__test__/Home.test.tsx:4:1)
```

### MSAL Configuration

```javascript
import { Configuration, PopupRequest } from "@azure/msal-browser";

// Config object to be passed to Msal on creation
export const msalConfig: Configuration = {
    auth: {
        clientId: "b5c2e510-4a17-4feb-b219-e55aa5b74144",
        authority: "https://login.microsoftonline.com/common",
        redirectUri: "/",
        postLogoutRedirectUri: "/"
    },
    system: {
        allowNativeBroker: false // Disables WAM Broker
    }
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest: PopupRequest = {
    scopes: ["User.Read"]
};

// Add here the endpoints for MS Graph API services you would like to use.
export const graphConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};
```

### Relevant Code Snippets

```javascript
const esModules = ['@azure/msal-react', '@azure/msal-browser'].join('|');

export default {
	preset: 'ts-jest',
	transform: { '^.+\\.ts?$': 'ts-jest' },
	collectCoverage: true,
	testEnvironment: "jsdom",
	coverageDirectory: "<rootDir>/coverage",
	transformIgnorePatterns: [
		`<rootDir>/node_modules/(?!${esModules})`,
	],

	testPathIgnorePatterns: [`<rootDir>/node_modules/(?!${esModules}`],
	coverageReporters: ["json", "lcov", "html"],

}
```

### Reproduction Steps

```
import React from "react";
import '@testing-library/jest-dom'
import { render, screen } from "@testing-library/react";
import { Home } from "../screens";


test("render home screen", () => {
	render(<Home />);
	const text = screen.getByText("My React and TypeScript App");
	expect(text).toBeInTheDocument();
});
```
const esModules = ['@azure/msal-react', '@azure/msal-browser'].join('|');

jest.config.ts
```
export default {
	preset: 'ts-jest',
	transform: { '^.+\\.ts?$': 'ts-jest' },
	collectCoverage: true,
	testEnvironment: "jsdom",
	coverageDirectory: "<rootDir>/coverage",
	transformIgnorePatterns: [
		`<rootDir>/node_modules/(?!${esModules})`,
	],

	testPathIgnorePatterns: [`<rootDir>/node_modules/(?!${esModules}`],
	coverageReporters: ["json", "lcov", "html"],

}
```

### Expected Behavior

test cases should run for typescript react msal project

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by ranshine** [comment] 2024-01-02 10:39
if i use @azure/msal-react 1.5.0 then i am not getting any issue, will it be resolved in latest versions ?

**Comment by marc-niclas** [comment] 2024-01-14 14:55
Can confirm I'm getting the same after upgrade to `2.0.9` and `msal-browser 3.7.0`

**Comment by ranshine** [comment] 2024-01-18 13:51
@marc-at-brightnight is this issue resolved in latest version ?

**Comment by marc-niclas** [comment] 2024-01-18 21:47
> @marc-at-brightnight is this issue resolved in latest version ?

No, as I noted above, I'm getting the same issue in the latest versions

**Comment by pondchamp** [comment] 2024-01-22 00:37
+1, tests are failing after upgrading to `2.x` (tried all minor versions), I had to downgrade back to `1.5.12` for my Jest tests to work again

**Comment by tnorling** [comment] 2024-02-05 18:41
Closing as duplicate of #6487. We're aware of this but haven't been able to prioritize a fix, PRs are welcome if this is a blocker.

**Closed as completed by tnorling** 2024-02-05 18:41 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client
