### ISSUE TITLE
Protectet API would not be authorized if angular routs are part of the API URL

### ISSUE THREAD

**Issue by hoharald** [AzureAD/microsoft-authentication-library-for-js#2038] opened 2020-07-28 11:48 UTC
## Library
- [x] `@azure/msal-angular@1.3.3`

## Description
In my case the angular frontend endpoints match API request URLs in some wording. So the API calls would fallback to unprotected and won't get an authorization header (token) as expected cause of this methode in msal.service.ts.

```js
private isUnprotectedResource(url: string): boolean {
        const frameworkUnprotectedResources = this.msalConfig.framework && this.msalConfig.framework.unprotectedResources;
        const configUnprotectedResources = this.msalAngularConfig.unprotectedResources || [];

        const unprotectedResources = frameworkUnprotectedResources && frameworkUnprotectedResources.length ? frameworkUnprotectedResources : configUnprotectedResources;

        return unprotectedResources.some(resource => url.indexOf(resource) > -1);
    }
```

unprotectedResources contains a list of all my angular router endpoints:

- costs
- collect
- scheduler

So if the api contains some of the above wordings it would return true and become an unprotected resource. Like it is the case for...

- .../api/azureusage/gettotal**costs**
- .../api/azureusage/get**costs**permonth
- .../api/**collect**or/**collect**offer
- .../api/**collect**or/**collect**usage
- .../api/**collect**or/getbusystate

#### The app configuration file...
```js
{
    "auth": {
        "clientId": "<secret>",
        "authority": "https://login.microsoftonline.com/<another-secret>",
        "validateAuthority": true,
        "redirectUri": "http://localhost:4200",
        "postLogoutRedirectUri": "http://localhost:4200",
        "navigateToLoginRequestUrl": true
    },
    "cache": {
        "cacheLocation": "localStorage"
    },
    "scopes": {
        "loginRequest": [
            "openid",
            "profile"
        ]
    },
    "resources": {
        "azureUsageApi": {
            "resourceUri": "http://localhost:5000/api/azureusage",
            "resourceScope": "api://<and-another-secret>/access_as_user"
        }
    }
}
```
#### Here the configuration for msal in app.module.ts 
```js
export const protectedResourceMap: [string, string[]][] = [    
    ['http://localhost:5000/api/azureusage/gettotalcosts', [config.resources.azureUsageApi.resourceScope]],
    ['http://localhost:5000/api/azureusage/test', [config.resources.azureUsageApi.resourceScope]],
    ['http://localhost:5000/api/azureusage/getcostspermonth', [config.resources.azureUsageApi.resourceScope]],
    ['http://localhost:5000/api/collector/collectoffer', [config.resources.azureUsageApi.resourceScope]],
    ['http://localhost:5000/api/collector/collectusage', [config.resources.azureUsageApi.resourceScope]],
    ['http://localhost:5000/api/collector/getbusystate', [config.resources.azureUsageApi.resourceScope]]
];

function MSALAngularConfigFactory(): MsalAngularConfiguration {
    return {
        popUp: !isIE,
        consentScopes: [
            config.resources.azureUsageApi.resourceScope,
            ...config.scopes.loginRequest
        ],
        unprotectedResources: [],
        protectedResourceMap,
        extraQueryParameters: {}
    };
}
....
providers: [
        MatDatepickerModule,
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        },
        {
            provide: MSAL_CONFIG,
            useFactory: MSALConfigFactory
        },
        {
            provide: MSAL_CONFIG_ANGULAR,
            useFactory: MSALAngularConfigFactory
        },
        MsalService
    ],
```

### Router config in app-routing.module.ts (as you can see 'costs' and 'collect' are angular router endpoints)
```js
const routes: Routes = [
  { path: '', redirectTo: '/costs', pathMatch: 'full' },
  { path: 'costs', component: CostsComponent },
  { path: 'scheduler', component: SchedulerComponent },
  { path: 'collect', component: CollectComponent }
];
```

## Expected behavior
I would expect that the API call gets an authorization header with the bearer token. Or are there any suggestions to solve this issue. Maybe it depends on some other configurations i'm not knowing so far.

## Browsers/Environment
- [x] Edge (Version 84.0.522.44 (Official Build) (64-Bit) => Chromium Engine)

## Links
Might be a duplicate to #1712 and maybe also to #1438 in some case. But this would take more time for investigation.

**Comment by jo-arroyo** [comment] 2020-07-28 16:36
@hoharald This is a known issue that we are addressing soon. Closing as this is a duplicate of #1695 and progress is being tracked there.

**Closed by jo-arroyo** 2020-07-28 16:36 UTC
Labels: angular, bug, known-issue
