### ISSUE TITLE
refreshTokenExpirationOffsetSeconds gives no effect on extExpiresOn

### ISSUE THREAD

**Issue by AndrewElans** [AzureAD/microsoft-authentication-library-for-js#6766] opened 2023-12-13 00:14 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Ref. to this article on [Token Lifetimes, Expiration, and Renewal](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#avoiding-interactive-interruptions-in-the-middle-of-a-users-session)

refreshTokenExpirationOffsetSeconds has no effect and returns default "extExpiresOn" as follows:

"expiresOn": "2023-12-13T00:28:43.000Z",
"extExpiresOn": "2023-12-13T01:32:58.000Z",

### MSAL Configuration

```javascript
var request = {
    account: myMSALObj.getActiveAccount(),
    forceRefresh: true,
    refreshTokenExpirationOffsetSeconds: 20000
};

myMSALObj.acquireTokenSilent(request)... as per your examples
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment] 2023-12-13 01:01
A couple things to note here:

1. This is a new config value which has not been released yet, it will be released in version 3.7.0
2. This config value is not expected to affect `extExpiresOn`, or any other return value. Instead it affects how the library interprets the refresh token's expiration value and controls when refresh token redemption should be skipped.

**Comment by AndrewElans** [comment] 2023-12-13 23:33
When is 3.7.0 available?

**Comment by tnorling** [comment] 2023-12-14 17:15
Currently scheduled for early January

**Closed as completed** 2023-12-14 17:15 UTC
Labels: question, msal-browser, public-client

**Comment by AndrewElans** [comment] 2023-12-15 00:00
Hei, how to check expiration value of the refresh token? And what is the meaning of extExpiresOn?

**Comment by AndrewElans** [comment] 2023-12-15 16:20
Hi @tnorling, including your name in case you haven't seen my previous question. Could be so kind to clarify?

**Comment by tnorling** [comment] 2023-12-15 20:17
You can't check the expiration value of the refresh token. You should not take any direct dependency on the refresh token.

extExpiresOn refers to the access token and may be used in offline or outage scenarios to temporarily extend the lifetime of the access token

**Comment by pr3d1ction** [comment] 2023-12-18 09:29
@tnorling : Is there any way for PWAs to control the refresh token expiration. We have special scenarios where the internet connectivity is really bad (A redirect or popup re-login) can block the whole application for more than 5 minutes. 

Is there no way to skip this 24 hrs refresh token impediment?
Or at least give control about when a new refresh token (that is valid then for 24 hours) should be created?

Thanks!

**Comment by AndrewElans** [comment] 2023-12-18 09:55
Just another question in this regard. 

My user needs to fill out a supplier form (quite big) and submit it. In some cases, the user would leave the form open and continue sometime later when the token/refresh token has already expired. There were cases when user pop-ups were blocked and redirect started, losing the form data.

I got it set up so: 

1. Check if account is present with **getAccount** with loginHint and start **acquireTokenSilent** with this account
2. If account is not present, or Step 1 fails, start **ssoSilent** with loginHint
3. If Step 2 fails, start **acquireTokenPopup**
4. **acquireTokenRedirect** as a last resort

I save the form in the local storage but when it comes to the refreshing token, how to ensure a seamless form-filling from a user perspective that he will not be put off by redirects in the middle of the form submission?

p.s. once this error came in forcing redirect https://login.microsoftonline.com/error?code=700084

**Comment by pr3d1ction** [comment] 2023-12-21 13:15
> I got it set up so:
> 
> 1. Check if account is present with **getAccount** with loginHint and start **acquireTokenSilent** with this account
> 2. If account is not present, or Step 1 fails, start **ssoSilent** with loginHint
> 3. If Step 2 fails, start **acquireTokenPopup**
> 4. **acquireTokenRedirect** as a last resort

Is this what you are using?
https://learn.microsoft.com/en-us/entra/identity-platform/msal-js-sso

Does this even work when the refresh token is expired? Is there any pattern when ssoSilent works or not?

**Comment by AndrewElans** [comment] 2023-12-21 13:41
I guess I have to explain a bit.

I have a corporate Power Pages portal with Dataverse, set up with Azure Active Directory (single tenant) as an Identity provider. By default, you don't need MSAL at all as the portal gets own token from the identity provider which also allows to query dataverse with [pages web api](https://learn.microsoft.com/en-us/power-pages/configure/web-api-overview). 

I ditched the "low-code" functionality provided by Power Pages as this is slow and cumbersome, and built custom business logic to render page elements and query data (I have some corporate limitations to build a proper SPA from scratch).

The main challenge with the pages web api is that it's limited in functionality, compared to the [dataverse web api](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/overview). But to use the dataverse web api you need a separate token, and that's where MSAL comes in.

So a user first authenticates automatically to power pages with own process (redirect) and the page is rendered. This process is independent of MSAL. Once it's done, I know who the user is.

I use email as a **loginHint** for MSAL to **getAccount** and start **acquireTokenSilent** with own scope for dataverse "<dataverse url>/user_impersonation". Therefore, I don't have any redirects or pop-us the second time in 90% of the cases. Sometimes, however, a refresh or new token process fires redirect as I explained above.

**Comment by AndrewElans** [comment] 2023-12-21 13:48
SSO silent also fails sometimes, here is a log from a user: 

<<<<< MSAL => acquireTokenSilent with existing account failed: InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. 
<<<<< MSAL => ssoSilent failed: InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. 
<<<<< MSAL => acquireTokenPopup failed: BrowserAuthError: popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser
And then redirect started...

I assume in this case, the session of the power pages user has also expired and therefore none of the silent methods worked with MSAL.

**Comment by Emprint** [comment] 2024-01-24 13:32
I can confirm we have the issue that @AndrewElans is mentionning just above.

We have an Angular PWA on Angular 16 and this error is raised everytime for iOS users (tested on iOS 17.2/17.3 with Safari or installed application) when we try to refresh the token even if their session is active:
- `getActiveAccount()` is called a few seconds before and returns an account as expected
- other requests requiring authentication are working as expected so I don't believe there is an issue with cookies as the error is suggesting

This is causing unexpected reloads of the application. For now we had to disable `forceRefresh`/`refreshTokenExpirationOffsetSeconds` and will need to investigate more to understand if it's due to our implementation or if it's a bug in MSAL but I just wanted to react here before our tests are done to say that you are not alone.
```
 {
  "errorCode":"login_required",
  "errorMessage":"AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: 812f2bfb-5f66-4cbf-ac8a-30087a1d6600 Correlation ID: daf0e4ac-1a35-47e8-a58b-d932339b25fd Timestamp: 2024-01-23 10:22:43Z",
  "subError":"",
  "name":"InteractionRequiredAuthError",
  "timestamp":"",
  "traceId":"",
  "correlationId":"daf0e4ac-1a35-47e8-a58b-d932339b25fd",
  "claims":""
}
```

**Comment by Emprint** [comment] 2024-01-29 18:42
As this issue is closed, I have created a new bug for the issue with iOS: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6858
