### ISSUE TITLE
[Msal for Angular] Angular with MSAL Tenant causes app reload in Iframe.

### ISSUE THREAD

**Issue by xxis** [AzureAD/microsoft-authentication-library-for-js#479] opened 2018-11-12 06:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 70
- [x] Firefox version 62 and 63
- [x] IE version 11
- [X] Edge version 42
- [?] Safari version XX

## Library version

Library version: Msal-Angular 0.1.2
Angular 7.1.0

```typescript
 MsalConfig: <MsalConfig>{
    clientID: 'xxxxx-9491-42a7-a605-xxxxx',
    authority: 'https://login.microsoftonline.com/xxxx-432f-bc98-xxxxx/',
    redirectUri: 'http://localhost:4200/signin-microsoft',
    consentScopes: ['user.read'],
    isAngular: true,
    tokenReceivedCallback: false, //tried both
    logger: logger,
    popUp: true,
    postLogoutRedirectUri: 'http://localhost:4200/home',
    cacheLocation: 'localStorage',
    protectedResourceMap: [['http://localhost:50133/api', ['api://xxx-xxx/access_as_user']],
                             ['https://login.microsoftonline.com/xxxx-fca9-432f-bc98-xxx', ['user.read']],
                             ['https://graph.microsoft.com/v1.0/me', ['user.read']]],
  },
```

## Current behavior

#Edge
redirect happens within the popup - config not passed back to original session.

#IE
could not get it to load due to 'class' issue.
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/414

#Firefox:
error in processHash(event), where event is not defined. (code below). however the token is parsed and the application does not duel-load.
```javascript
if (window.parent !== window) {
                    //in iframe
                    if (event && event.preventDefault) {
                        event.preventDefault();
                    }
```
![image](https://user-images.githubusercontent.com/6135868/48328976-8f645400-e696-11e8-91ae-1e5315a233e7.png)

#Chrome
The Application does a full reload inside the iframe.
this is NOT the desired outcome, being an angular applicaiton this means that the full stack of services bootstrap again.
there is many attempts to capture the page reload and stop it, but there is one missed somewhere.
related issues:
https://blog.kloud.com.au/2018/05/26/preventing-double-app-loading-behaviour-with-adal-js/
https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4

there are workarounds there for adal, however i couldn't seem to apply these to the msal-angular service.

## Expected behavior

An angular application should be prevented from bootstrapping inside an Iframe.
either the package needs to handle this, or better documentation needs to be added to stop this. 
the other sorts of events block the redirect.
this might be the 'design' of a 302 http code, however this should not be the design of an anuglar app.

## Minimal reproduction of the problem with instructions

create anuglar application.
install msal-angular.
connect to AAD.
watch as application bootstraps inside iframe on RENEW_TOKEN.

**Comment by michaellichtner** [comment] 2018-12-11 14:59
Any other work arounds?

**Comment by david-lpg** [comment] 2018-12-20 09:40
I can confirm the bug with Edge (version 42.17134.1.0 with msal-angular 0.1.2): using loginPopup function redirects in the popup window after login in...
Combine with issue #414 this library is not usable with both Microsoft browsers. Funny for a Microsoft library...
I hope these two issues will be resolved soon as we can't release our app without the support of Edge and IE.

**Comment by Dedme** [comment] 2019-01-15 05:02
Just wantted to add that as soon as you turn on AOT my solution fails. :(

**Comment by Ralms** [comment] 2019-01-23 00:34
The solution from @Dedme worked great. 
Not pretty but solves the issue for now. 
Thanks.

**Comment by navyasric** [comment] 2019-01-31 23:48
Closing this as duplicate. Please track #526.

**Closed by navyasric** 2019-01-31 23:48 UTC
Labels: angular

**Comment by Marco-Mauri** [comment] 2019-02-01 08:46
IMO this is not a duplicate of #526.

The problem reported in this bug causes an entire copy of the Angular application to be loaded in an hidden iframe, the main app work correctly.

This **"only"** causes extreme memory consumption and sluggines when refreshing the tokens.

**Comment by Ralms** [comment] 2019-02-01 13:12
> IMO this is not a duplicate of #526.
> 
> The problem reported in this bug causes an entire copy of the Angular application to be loaded in an hidden iframe, the main app work correctly.
> 
> This **"only"** causes extreme memory consumption and sluggines when refreshing the tokens.

Hi @Marco-Mauri , I believe we are all talking about the same thing here, however focusing on different scenarios. 

In issue #526, @vramasam and @Dedme work around is to bootstrap Angular to load only a basic empty component instead of the main app component, which on my case for example is good enough since it won't create new instances of singleton services and other components. 

Although what I don't agree is the label of "Documentation issue" as it's not only a documentation issue in my eyes.
