### ISSUE TITLE
performanceMeasurement.startMeasurement is not a function Error in Type script sample

### ISSUE THREAD

**Issue by rnphani** [AzureAD/microsoft-authentication-library-for-js#5587] opened 2023-01-18 12:47 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.9

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.9

### Public or Confidential Client?

Public

### Description

Getting issue with type script sample  path for sample download  :microsoft-authentication-library-for-js-dev\samples\msal-react-samples\typescript-sample, cloud not able to proceed further with type script sample , dont know how to fix this error 

### Error Message

error details Uncaught TypeError: performanceMeasurement.startMeasurement is not a function
at PerformanceClient.startMeasurement (PerformanceClient.ts:123:1)
at BrowserPerformanceClient.startMeasurement (BrowserPerformanceClient.ts:46:1)
at ClientApplication.acquireTokenPopup (ClientApplication.ts:328:1)
at PublicClientApplication.loginPopup (PublicClientApplication.ts:84:1)
at handleLogin (SignInButton.tsx:18:1)
at onClick (SignInButton.tsx:47:1)
at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
at invokeGuardedCallback (react-dom.development.js:4277:1)
at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
Please let me know how to fix this issue as soon as possible

### Msal Logs

n/a

### MSAL Configuration

```javascript
auth: {
        clientId: "clientId",
        authority: "https://login.windows-ppe.net/common",
        redirectUri: "",
        postLogoutRedirectUri: "/"
    }
```

### Relevant Code Snippets

```javascript
n/a
```

### Reproduction Steps

n/a

### Expected Behavior

n/a

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser": "^2.30.0"

### Source

Internal (Microsoft)

**Comment by ysagar-drreddys** [comment] 2023-01-18 12:51
Facing the same issue. Kindly let us know when can this be fixed or any other workarounds.

**Comment by NickAusloos** [comment] 2023-01-18 13:01
Having the same issue with my Angular app (@azure/msal-browser": "^2.28.0)

```
TypeError: c.startMeasurement is not a function
    at n.startMeasurement (main.170c67012d4545f5.js:1:1231498)
    at t.startMeasurement (main.170c67012d4545f5.js:1:1436828)
    at t.<anonymous> (main.170c67012d4545f5.js:1:1369813)
    at f (main.170c67012d4545f5.js:1:379297)
    at Object.next (main.170c67012d4545f5.js:1:379402)
    at main.170c67012d4545f5.js:1:378337
    at new E (polyfills.17058541d81afe21.js:1:18860)
    at _n (main.170c67012d4545f5.js:1:378072)
    at t.getDiscoveredAuthority (main.170c67012d4545f5.js:1:1369584)
    at t.<anonymous> (main.170c67012d4545f5.js:1:1368368)
```

**Comment by pascalgross** [comment] 2023-01-18 13:38
Just updated my angular app and got the same problem.
File header of PerformanceClient.js says: /*! @azure/msal-common v9.1.0 2023-01-18 */

**Comment by ISvirko** [comment] 2023-01-18 13:52
is there going to be any fix for this? or a workaround?

**Comment by Nic-Nitro5** [comment] 2023-01-18 14:22
Should we roll back a version here? We have: a.startMeasurement is not a function

**Comment by NKFahrni** [comment] 2023-01-18 14:38
![image](https://user-images.githubusercontent.com/58515781/213199607-bc064b8a-3789-4446-8ec6-53112587831f.png)
Found this here: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5582

**Comment by georgiosApo** [comment] 2023-01-18 15:10
Can confirm that this is happening to our latest deploys as well. We're using:

```
"@azure/msal-browser": "^2.32.2",
"@azure/msal-react": "^1.5.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

And getting the following issue:
```
TypeError: performanceMeasurement.startMeasurement is not a function
    at PerformanceClient2.startMeasurement (PerformanceClient.ts:123:32)
    at BrowserPerformanceClient2.startMeasurement (BrowserPerformanceClient.ts:46:55)
    at RedirectClient2.<anonymous> (StandardInteractionClient.ts:205:65)
    at step (_tslib.js:87:23)
    at Object.next (_tslib.js:68:53)
    at _tslib.js:61:71
    at new Promise (<anonymous>)
    at __awaiter (_tslib.js:57:12)
    at StandardInteractionClient2.getDiscoveredAuthority (StandardInteractionClient.ts:203:115)
    at RedirectClient2.<anonymous> (StandardInteractionClient.ts:142:48)
```

Thing to note is the number 2 added to the names of PerformanceClient2, BrowserPerformanceClient2 etc.
Any idea what can be causing that or is it intended?

Any pointers or workarounds would be much appreciated!

Thanks a lot in advance!

// G

**Comment by Nic-Nitro5** [comment] 2023-01-18 15:23
`"@azure/msal-browser": "2.30.0",
"@azure/msal-react": "^1.5.2"`

We did a rollback and app is running fine.

**Comment by Cowraider** [comment] 2023-01-18 15:30
For Angular I used those two versions to make it work again: 
`"@azure/msal-angular": "^2.5.2"` and `"@azure/msal-browser": "^2.32.1"`
The bug seems to be in msal-browser version 2.32.2 if I am not mistaken

**Comment by ivaanortega** [comment] 2023-01-18 17:24
In React we did a rollback in `"@azure/msal-common": "9.1.0"` to `"@azure/msal-common": "9.0.2"` and it works like a charm.
The msal-browser we use : `"@azure/msal-browser": "2.32.2"`

**Comment by kotacode** [comment] 2023-01-18 18:57
> In React we did a rollback in `"@azure/msal-common": "9.1.0"` to `"@azure/msal-common": "9.0.2"` and it works like a charm. The msal-browser we use : `"@azure/msal-browser": "2.32.2"`

Thank you! Been banging my head against the wall 😅

**Comment by georgiosApo** [comment] 2023-01-18 19:39
The issue was really caused by us using the non explicit versioning for msal-browser. `2.32.2` seems to be the culprit so using 2.32.1 with `"@azure/msal-react": "^1.5.2"`.

Just remember to use explicit versioning and target version `"@azure/msal-browser": "2.32.1"` WITHOUT the "^" symbol in conjunction with the version number.

Most likely the cause that is making this issue emerge.
The faulty MSAL version gets released, pipeline runs, faulty version gets deployed and the issue occurs.

Thanks for all the help in this thread!

**Comment by mohd7469** [comment] 2023-01-19 04:27
@jo-arroyo it seems you updated PerformanceClient but it didn't fixed yet please confirm

**Comment by pascalgross** [comment] 2023-01-19 13:56
@jo-arroyo whats the status on this issue?
Obviously broken and still unconfirmed?

**Comment by kotacode** [comment] 2023-01-19 14:39
> @jo-arroyo it seems you updated PerformanceClient but it didn't fixed yet please confirm

> @jo-arroyo whats the status on this issue? Obviously broken and still unconfirmed?

Doesn't look like the PR has been merged yet if you look at [#5589](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5589). Looks like code reviews are still being performed.

**Comment by mohd7469** [comment] 2023-01-19 15:30
For now this is the temporary solution until they proper fix. Just use it without `^` carret.

`"@azure/msal-angular": "2.5.2",`
`"@azure/msal-browser": "2.32.1"`

**Comment by rafi007akhtar** [comment] 2023-01-19 16:08
For me, the following versions worked in Angular.
```json
"@azure/msal-angular": "2.5.1",
"@azure/msal-browser": "2.32.1",
```

**Comment by jo-arroyo** [comment] 2023-01-19 17:12
Hi all, yes this is a confirmed bug that we are working on fixing. Please downgrade until the next release is available.

@pascalgross @mohd7469 @kotacode

**Comment by timtucker-dte** [comment] 2023-01-19 18:04
First a breaking defect in the App Insights SDK and then this...

Were all the Azure JS testers part of the layoffs this week?

**Comment by jo-arroyo** [comment] 2023-01-20 01:30
Thank you all for your patience. Msal-common v 9.1.1 has been released. Please upgrade and let us know if you continue to see issues.

**Comment by jo-arroyo** [comment] 2023-01-23 21:11
Closing as msal-common v9.1.1 release addresses these issues. Please open a new issue if you continue to see errors.

**Closed as completed by jo-arroyo** 2023-01-23 21:11 UTC
Labels: bug, msal-browser, msal-common, public-client
