### ISSUE TITLE
B2C Microsoft identity provider with msal-browser 2.x login error: "Proof Key for Code Exchange is required..."

### ISSUE THREAD

**Issue by zzzachzzz** [AzureAD/microsoft-authentication-library-for-js#2801] opened 2020-12-21 19:12 UTC
## Library
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] React

## Description
I'm trying to use Azure AD B2C with msal-browser 2.x in a SPA using the recommended PKCE auth flow. I'm using the preset 'Sign up and sign in' recommended B2C User Flow. I have B2C configured with 3 identity providers: Google, Microsoft, and Local account (Email). The only provider of the 3 which is not working and yielding this error is the Microsoft identity provider.

## Error Message

> ServerError: server_error: AADB2C90273: An invalid response was received : 'Error: invalid_request,Error Description: Proof Key for Code Exchange is required for cross-origin authorization code redemption.'

## MSAL Configuration
```js
const redirectUri = 'http://localhost:3000/login';
const authority = 'https://<TENANT>.b2clogin.com/tfp/<TENANT>.onmicrosoft.com/b2c_1_signin_signup';
const msalConfig = {
  auth: {
    clientId: '<CLIENT_ID>',
    authority,
    knownAuthorities: ['<TENANT>.b2clogin.com'],
    redirectUri,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
};
const msal = new MSAL.PublicClientApplication(msalConfig);
```

## Reproduction steps
```js
// With the above config, trigger a login popup
msal.acquireTokenPopup({ scopes: [] });
// Login popup appears, I click to sign in with a Microsoft social account
// Error message is seen in browser console
```

## Expected behavior
The Microsoft login should appear, and the MSAL library should handle PKCE.

## Identity Provider
- [x] Azure B2C Basic Policy

## Browsers/Environment
- [x] Chrome

## Source
- [x] Customer request

**Comment by tnorling** [comment] 2020-12-21 19:38
@zzzachzzz The fact that it works for 2/3 IDPs suggests to me that B2C is not forwarding the PKCE params, at least to, AAD. Can you verify that your redirectUris are configured in the portal as type "SPA" and not type "Web". If so, can you email me (email on my profile) a network trace showing both the flow that works as well as the one that doesn't? I'll follow up with the service to see what's going on here. 

cc. @nickgmicrosoft

**Comment by codymullins** [comment] 2020-12-26 18:50
I don't have a ton of information to add here, but just wanted to mention I'm seeing the same error for Microsoft IDP. Google works OK - before I tried a custom User Flow, logging it through the normal `login.live` default worked fine.

**Comment by tnorling** [comment] 2021-01-07 16:25
@codymullins Could you email me a network trace? I was not able to reproduce this on my end so I would be curious to see what's going on here.

**Comment by zzzachzzz** [comment] 2021-01-18 18:23
As a workaround, I was able to get the Microsoft IDP working by registering a Web Redirect URI rather than a SPA Redirect URI for `https://<TENANT>.b2clogin.com/<TENANT>.onmicrosoft.com/oauth2/authresp`. However I noticed that AAD logins could not be used with the B2C Microsoft IDP. Is this a known limitation of B2C? I was able to use an AAD login with non-B2C MSAL.

**Comment by tnorling** [comment] 2021-01-19 17:48
@zzzachzzz

> As a workaround, I was able to get the Microsoft IDP working by registering a Web Redirect URI rather than a SPA Redirect URI for https://<TENANT>.b2clogin.com/<TENANT>.onmicrosoft.com/oauth2/authresp

I'm not sure the SPA redirect type is intended for use between B2C and AAD so Web here I think is correct. The SPA redirect type should be used to register your application's redirect uris. @nickgmicrosoft Can you confirm?

> However I noticed that AAD logins could not be used with the B2C Microsoft IDP. Is this a known limitation of B2C? 

By "B2C Microsoft IDP" do you mean AAD or "Microsoft Account"? An AAD login will not work with the MSA IDP and vice versa. There is no known limitation I am aware of that would prevent you from being able to login to any of the external IDPs as B2C essentially just forwards the request for them to handle. There's likely something misconfigured.

>I was able to use an AAD login with non-B2C MSAL.

Can you clarify what you mean here? There is no "B2C MSAL" and "non-B2C MSAL" there's just MSAL.

**Comment by zzzachzzz** [comment] 2021-01-19 18:10
@tnorling What I mean by "non-B2C MSAL" is configuring MSAL with the standard authority of `https://login.microsoftonline.com/common`. Using MSAL with B2C the authority is configured with, for example: `https://<TENANT>.b2clogin.com/tfp/<TENANT>.onmicrosoft.com/b2c_1_signin_signup`.

Regarding the AAD logins, sorry if I have some terminology mixed up. What I've observed is that when MSAL is configured to use a B2C authority, I can login with a personal MS account, but I cannot login with my work account, which to my understanding is an Azure Active Directory account.

**Comment by tnorling** [comment] 2021-01-19 18:31
@zzzachzzz

>What I've observed is that when MSAL is configured to use a B2C authority, I can login with a personal MS account, but I cannot login with my work account, which to my understanding is an Azure Active Directory account.

That's right. So you'll need to make sure you log into the personal MS account using the Microsoft IDP and the work account with the AAD IDP. When you use the "https://login.microsoftonline.com/common" authority that endpoint will automatically route you to the correct authority (your AAD tenant in the case of work account, or live.com in the case of personal account) depending on which user you are trying to log in with.

You may be able to use the /common endpoint with B2C if you use the AAD IDP and configure your AAD app registration as multitenant + personal accounts. But unfortunately I am not the expert in B2C configuration so I would encourage you to open a ticket with [B2C Support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) if you need help getting this set up properly.

**Comment by hectormmg** [comment] 2021-02-05 22:13
@zzzachzzz are there any updates on whether your issue has been solved so we can close this thread?

**Comment by zzzachzzz** [comment] 2021-02-05 22:59
@hectormmg I have my workaround but it doesn't seem the root problem was resolved / discovered. If @tnorling speculation is accurate:
>I'm not sure the SPA redirect type is intended for use between B2C and AAD so Web here I think is correct

...then that should probably be documented. My intuition was to register the redirect URIs as SPA, since my app is a SPA. You can close it if you want.

**Comment by tnorling** [comment] 2021-02-05 23:20
@zzzachzzz Please see this [doc](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-single-tenant?pivots=b2c-user-flow). The distinction here is that this redirect URI is not a redirect URI for your SPA. It's an internal redirect URI between the AAD service and B2C service.

From the linked doc:
> For the Redirect URI, accept the value of Web, and enter the following URL in all lowercase letters, where your-B2C-tenant-name is replaced with the name of your Azure AD B2C tenant.

**Closed by tnorling** 2021-02-05 23:20 UTC
Labels: b2c, b2c-service, bug-unconfirmed, msal-browser, no-issue-activity, question
