### ISSUE TITLE
Access token not writing out to client

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#159] opened 2017-10-24 15:16 UTC
Hello-

Is there something preventing the access token from being returned in localhost development?

I am successfully getting an id_token back.  However,   none of my other console.log are showing anything at all.  I can see the user is signed in successfully.    However, my goal is to get the access token for use in REST calls.  

Any idea?

I have used npm to install MSAL.  I am including a reference to the the types:
/// <reference path="../../../node_modules/msal/out/msal.d.ts" />

My code:
```
  tenantConfig = {
    clientID: "my client id",
    scopes: ["user.read", "mail.send"]
  };

if (token) {
      this.clientApplication.acquireTokenSilent(this.tenantConfig.scopes).then(
        function(accessToken): any {
          // Change button to Sign Out
          // updateUI();
          console.log("here 1");
          console.log(accessToken);
        },
        function(error: any) {
          console.log(error);
          this.clientApplication
            .acquireTokenPopup(this.tenantConfig.scopes)
            .then(
              function(accessToken: any) {
                // updateUI();
                console.log("here 2");
                console.log(accessToken);
              },
              function(error: any) {
                console.log(error);
              }
            );
        }
      );
    } else if (errorDesc || error) {
      console.log(error + ":" + errorDesc);
    }
  }
```

**Comment by jrmcdona** [comment] 2017-10-24 15:30
I have also tried using the clientId for the scope as seen here:
https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2/blob/master/TodoSPA/App/Scripts/Ctrls/todoListCtrl.js

Same issue however,  no access token seems to be coming back but nothing failing either.

**Comment by tomidix** [comment] 2017-11-29 09:33
@rohitnarula7176 
It is an "issue" with the acquireTokenRedirect function.
Please make a fix that it returns the accessToken just like the acquireTokenPopup popup does.

The problem is that the acquireTokenRedirect returns void so naturally we can't get the token out of it, it just writes the token to the cacheStorage. We have to read the token from the session/local storage at the moment directly and it's not the best solution.

This has to be fixed asap.

**Comment by jmprieur** [comment] 2017-11-29 09:45
@tomidix 
acquireTokenRedirect redirects the browser to Azure AD for the authentication, and then Azure AD calls 
back you application (if the reply URL is among the "Reply URLs" registered into the AzureAD application). 
Therefore the page is no longer in the browser when acquireTokenRedirect complets, and this method cannot return any value.
The way to get the token back is to let MSAL do it: the auth callback passed in the constructor of the MSAL.UserAgentApplication will be called by MSAL with the access token

Please have a look at this sample application. This is the way to use acquireTokenRedirect.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html#L47

**Comment by tomidix** [comment] 2017-11-29 11:58
@jmprieur Thanks for answer. Ok for return, you're right.
I have a problem with authCallback function in angular4.
There is an additional action in your example `                userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
`
Problem is in Angular because I use authentication service and my authCallback funcion has to save token and has to call that method like this: `this.clientApplication.acquireTokenRedirect(environment.b2cScopes);` - notice **this**
clientApplication is the instance of Msal.UserAgentApplication, the same is with acquireTokenSilent or acquireTokenPopup

When my authCallback is triggered it's this points to Msal.UserAgentApplication instance instead of my authenticationService class.

Example I'm referring to is here: https://github.com/Gimly/NetCoreAngularAzureB2CMsal/blob/master/ClientApp/app/services/authentication.service.ts

**Comment by jmprieur** [comment] 2017-11-29 12:13
Great @tomidix  if you found the answer. can we close the issue?

**Comment by chigivigi** [comment] 2017-12-01 15:45
in the example here: https://github.com/Gimly/NetCoreAngularAzureB2CMsal/blob/master/ClientApp/app/services/authentication.service.ts
I am having a similiar problem where userAgentApplication.acquireTokenSilent does not return a token and i can't use the userAgentApplication.acquireTokenPopup so I am forced to use userAgentApplication.acquireTokenRedirect and getting the token from my session storage.

is there a way to get the token with userAgentApplication.acquireTokenSilent ?

**Comment by hkusulja** [comment] 2018-01-15 18:41
Any update on this, without popup, @jmprieur and @tomidix ? tx

**Closed** 2018-03-19 18:02 UTC
