### ISSUE TITLE
ES6 export option for package @azure/msal-common

### ISSUE THREAD

**Issue by stefaniehansen** [AzureAD/microsoft-authentication-library-for-js#5443] opened 2022-12-02 00:21 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Related to #5274 https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5274

Currently, @azure/msal-common does not ship an ESM build of the library. That means that tree-shaking is not possible for consumers of @azure/msal-common. With tree-shaking, we could significantly reduce the bundle size of consumer projects, including the OneNote Meeting Notes application. msal-common is currently one of the largest contributors to our bundle at around 121 KB parsed. 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/31112980/205186341-e1466464-7fea-46d1-bcdd-843751392704.png">

Given that the current recommendation for the size of an entry point bundle is 244KB according to webpack, this represents half of size of a typical app entry point. With both msal-browser and msal-common together, we've already taken up 249KB, more than the recommended entry point bundle size, even without **any app code whatsoever**.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/31112980/205186478-23d1fb0d-bca5-4c24-85ca-e1e8a855f53e.png">

This is a bulky library and adding ES6 exports make a very big difference to many apps that use it.

### Source

Internal (Microsoft)

**Comment by bmahall** [comment] 2022-12-05 18:02
Closing as duplicate of [#5724](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5274)

**Comment by stefaniehansen** [comment] 2022-12-08 06:09
@bmahall  This isn't a dupe because this is concerning a different package (msal-common vs msal-browser).

**Comment by michaeloliverx** [comment] 2023-02-10 09:34
Is this planned for the react bindings? Currently trying to reduce our bundle size and MSAL accounts for 60% of the entire bundle.
![image](https://user-images.githubusercontent.com/55017335/218056311-7d221f74-3328-44c1-968b-3150ba7e780b.png)

**Comment by sameerag** [comment] 2023-02-10 21:19
Yes, we have plans to, no decided deadline yet though. Will reopen this to track. cc @EmLauber

**Comment by tnorling** [comment] 2023-07-06 20:31
A beta of the v3 version of msal-browser and beta of msal-react v2 are released which should be exporting ES2020 modules. Can you try that out and let us know if that resolves this issue? Thanks!

**Comment by tnorling** [comment] 2023-08-14 18:29
Closing as msal-browser 3.0.0 and msal-common 14.0.0 are now released and include these changes.

**Closed as completed by tnorling** 2023-08-14 18:29 UTC
Labels: enhancement, msal-browser, public-client
