### ISSUE TITLE
How to Check if user is Logged in

### ISSUE THREAD

**Issue by BarishSarac** [AzureAD/microsoft-authentication-library-for-js#4040] opened 2021-09-08 16:17 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

Hello,

How can I tell if user that is trying to load the app is logged in or not? Currently, I have this:

But with this snippet, app loads the page I see text and images then it redirects to login. 

### Relevant Code Snippets

```javascript
export default function Main() {
  const msalInstance = new PublicClientApplication(msalConfig);
  useEffect(() => {
    msalInstance
      .handleRedirectPromise()
      .then((s) => {
        if (s === null) msalInstance.loginRedirect(loginRequest); // not logged in
        else console.log(s); // logged in
      })
      .catch((a: any) => {
        console.log("err");
        console.log(a);
      });
  }, []);
  return <App instance={msalInstance} />;
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by BarishSarac** [comment] 2021-09-08 16:18
I need to redirect user to login screen right away if user is not logged in. User shouldn't see the app at all.

**Comment by hectormmg** [comment] 2021-09-08 16:37
Hi @BarishSarac , in order to achieve that specific behavior, there are two options:

1. Delay rendering your app until the user is confirmed to be logged in (they will be redirected to authenticate before you render your app).
2. Handle this on the server side by redirecting to the login interaction before the app is rendered (which would involve a solution other than `msal-react`).

Here is some documentation on the [MSAL AuthenticationTemplate](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#determining-whether-a-user-is-authenticated), which may be of some help in determining what the right way to use our library would be in this case.

As a final note, we don't recommend you initialize the `PublicClientApplication` inside a React component. Please review our [Getting Started](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md) documentation and our [react-router-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) for more guidance on how to initialize MSAL in your application.

**Comment by BarishSarac** [comment] 2021-09-13 22:13
Hello @hectormmg
I have the below setup. I need to have my own AuthWrapper so I created a HOC and wrapped my whole app with it. Whenever I use `instance.loginRedirect(loginRequest)` inside the appwrapper's app.js my app gets into forever refreshing cycle.

All I am trying to achieve is have AuthWrapper HOC, configure my MSAL and redirect users if they're not logged in to the login page...


index.js
```
const msalInstance = new PublicClientApplication(msalConfig);

ReactDOM.render(
  <React.StrictMode>
    <Main instance={msalInstance} />
  </React.StrictMode>,
  document.getElementById("root")
);
```
main.js
```
import React from "react";
import AuthWrapper from "./components/auth-wrapper";
function Main() {
  return <div>Main</div>;
}
export default AuthWrapper(Main);
```
authwrapper/index.js
```
import React from "react";
import AuthWrapper from "./components/auth-wrapper";
function Main() {
  return <div>Main</div>;
}
export default AuthWrapper(Main);
```
authwrapper/app.js
```
import React from "react";
import { useIsAuthenticated, useMsal } from "@azure/msal-react";
import { loginRequest } from "./../auth-config";
export default function App({ children }) {
  const isAuthenticated = useIsAuthenticated();
  const { instance } = useMsal();
  if (!isAuthenticated) {
    instance.loginRedirect(loginRequest);
    return "";
  } else
    return (
      <>
        <p>Anyone can see this paragraph.</p>
        {isAuthenticated && <p>At least one account is signed in!</p>}
        {children}
      </>
    );
}
```

**Comment by BarishSarac** [comment] 2021-09-13 23:34
After much research, this is the code that works

Anyone that needs to require users to sign in to view the applicaton can use this. I can't believe everywhere about msal examples include only click to sign in. No single best practice to signinredirect already implemented

i```
mport React from "react";
import { useIsAuthenticated, useMsal } from "@azure/msal-react";
import { InteractionStatus } from "@azure/msal-browser";
import { loginRequest } from "./../auth-config";

export default function App({ children }) {
  const isAuthenticated = useIsAuthenticated();
  const { instance, inProgress } = useMsal();
  if (inProgress === InteractionStatus.None && !isAuthenticated) {
    instance.loginRedirect(loginRequest);
  } else
    return (
      <>
        <p>Anyone can see this paragraph.</p>
        {isAuthenticated && <p>At least one account is signed in!</p>}
        <button
          onClick={() =>
            instance.logoutRedirect({ postLogoutRedirectUri: "/" })
          }
        >
          Logout
        </button>
        {children}
      </>
    );
}

```

**Comment by hectormmg** [comment] 2021-09-13 23:46
Thanks for the feedback @BarishSarac! Closing the issue since you've found a solution that works for you.

**Closed by hectormmg** 2021-09-13 23:46 UTC
Labels: question, b2c, msal-browser, msal-react, answered, Needs: Attention :wave:
