### ISSUE TITLE
Error during sign out - AADSTS90023

### ISSUE THREAD

**Issue by aelij** [AzureAD/microsoft-authentication-library-for-js#1642] opened 2020-05-12 17:24 UTC
## Library
- [x] `@azure/msal-browser@2.0.0-beta2`

## Framework
React 7.106.0

## Description
After calling `PublicClientApplication.signOut()` the browser redirects to an AAD page with the following error:

> AADSTS90023: Invalid request. The request specified session id but did not specify issuer

## Security
Is this issue security related? No

## Regression
Did this behavior work before? No

## Configuration
Please provide your MSAL configuration options.

```ts
export const msalConfig: Configuration = {
    auth: {
        clientId: viewContext.aadClientId,
        authority: 'https://login.microsoftonline.com/common/',
        redirectUri: 'http://localhost:4100',
        postLogoutRedirectUri: 'http://localhost:4100',
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
    }
};
export const loginRequest: TokenRenewParameters | AuthenticationParameters = {
    scopes: [viewContext.aadResource],
};
```

Code: [msal.ts.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/4617459/msal.ts.txt)

## Reproduction steps
1. Sign in
2. Sign out

## Expected behavior
Redirect to sign out URL.

## Browsers
Tried New Edge and Firefox (latest).

**Comment by pkanher617** [comment] 2020-05-12 19:54
This was caused by an issue in the app registration, fixed by clearing the Logout URL in the Authentication blade.

**Closed by pkanher617** 2020-05-12 19:54 UTC
Labels: bug
