### ISSUE TITLE
MSALInterceptor Not Validate Audiance

### ISSUE THREAD

**Issue by McInnesIan** [AzureAD/microsoft-authentication-library-for-js#3046] opened 2021-02-19 13:46 UTC
We have a couple of websites running on same domain using MSAL Angular MSALGuard we have found that if we login using SSO and switch between apps the token is not refreshed for the website we switch to and continues trying to use the token from the switched from website. To fix this we have had to write a new interceptor which checks that the token aud is the same as the Azure client id of the website and if not calls login to fetch the appropriate token. Surely MSAGuard should be validating the aud and follow this behavior rather than allowing the application to continue using a token intended for another website.

**Comment by pkanher617** [comment] 2021-02-22 17:16
@McInnesIan Could you please fill out the [issue template](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/.github/ISSUE_TEMPLATE)? Are these sites using different client ids?

**Comment by McInnesIan** [comment] 2021-02-22 17:47
Yes they are using different clientids, my fix for this involves creating a new guard which accesses the token and compares the tokens aud claim against the clientid of the application, if they are different, I force a silent login, since its SSO the user is already logged-in but it updates the token. Note the domains for both applications are the same.
________________________________

**Comment by McInnesIan** [comment] 2021-03-09 16:11
Still open because it has not been fixed, in MSALInterceptor compare the clientid with the tokens aud

**Comment by tnorling** [comment] 2021-03-18 00:19
Closing as duplicate of #3172 which was resolved by recent patch

**Closed by tnorling** 2021-03-18 00:19 UTC
