### ISSUE TITLE
MSAL does not return the new token after an acquireSilent()

### ISSUE THREAD

**Issue by scambier** [AzureAD/microsoft-authentication-library-for-js#759] opened 2019-06-13 09:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chromium version 74 (with Brave)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 1.0.1

## Current behavior

- I'm using MSAL with VueJS
- I use the localStorage (and not the sessionStorage)
- I use axios to intercept outgoing requests to my API, and inject the `accessToken` from `acquireTokenSilent()` as a bearer token

When the token expires, MSAL fetches a new one (using `acquireTokenSilent()`), updates the localStorage accordingly, but still returns the old one. As a result, when I call my API, I have 401 errors.

- When I refresh the page, `acquireTokenSilent()` returns the new token.
- When I open a new tab from the same app, the new tab `acquireTokenSilent()` returns the new token. However, the old tab still uses the old token

The localStorage just after a login:
![image](https://user-images.githubusercontent.com/3216752/59423387-58902100-8dd2-11e9-8000-24c3cce532a7.png)

After a token refresh:
![image](https://user-images.githubusercontent.com/3216752/59423658-db18e080-8dd2-11e9-8e2d-94faeaef4d89.png)

The new token is present (in green), while the old one is still there in red. MSAL still returns the old one when calling `acquireTokenSilent()`

## Expected behavior

MSAL should use the new token

## Minimal reproduction of the problem with instructions

The ajax interceptor:

```ts
    axios.interceptors.request.use(
      async request => {
        await setToken(request)
        return request
      },
      error => {
        return Promise.reject(error)
      }
    )

    const setToken = async (request: any) => {
      const res = await authService.getAuthResponse() as Msal.AuthResponse
      request.headers.common['Authorization'] = `Bearer ${res.accessToken}` // This fails if MSAL requested a new token
    }
```

The authService:
```ts
  public async getAuthResponse(): Promise<null | Msal.AuthResponse> {
    const tokenRequest = {
      scopes: this.graphScopes
    }

    try {
      return await this.userAgentApp.acquireTokenSilent(tokenRequest)
    }
    catch (e) {
      this.userAgentApp.acquireTokenRedirect(tokenRequest)
      return null
    }
  }
```

UPDATED WORKAROUND: 

To manually retrieve the correct token:

```ts
function extractMSALToken() {
  const timestamp = Math.floor((new Date()).getTime() / 1000)
  let token = null

  for (const key of Object.keys(localStorage)) {
    if (key.includes('"authority":')) {
      const val: any = JSON.parse(localStorage.getItem(key)!)

      if (val.expiresIn) {
        // We have a (possibly expired) token

        if (val.expiresIn > timestamp && val.idToken === val.accessToken) {
          console.log(key)
          // Found the correct token
          token = val.idToken
        }
        else {
          console.log('will remove ' + key)
          // Clear old data
          localStorage.removeItem(key)
        }
      }
    }
  }
  if (token) return token
  throw new Error('No valid token found')
}
```

Old workaround (invalid):

```
    const setToken = async (request: any) => {
      // Make sure that MSAL token is up-to-date
      const res = await authService.getAuthResponse() as Msal.AuthResponse
      // DIRTY FIX : directly fetch the token from the localStorage
      request.headers.common['Authorization'] = `Bearer ${localStorage.getItem('msal.idtoken')}`
      // request.headers.common['Authorization'] = `Bearer ${res.accessToken}` // This doesn't work
    }
```

**Comment by DarylThayil** [comment] 2019-06-13 18:13
This is really interesting, thanks for sharing! 
@pkanher617  can you take a look at this? 
Looks like we may be fumbling something in the cache of refreshed tokens

**Comment by tylerjwatson** [comment] 2019-06-17 00:26
+1.  I get this as well.

Question for @scambier if I may:  In your 'workaround', I noticed this line: 
```
request.headers.common['Authorization'] = `Bearer ${localStorage.getItem('msal.idtoken')}`
```
Is there any specific reason why the id token is getting injected into your Authorization header and not the access token?  The workaround seems succinct, apart from this one line.

Cheers! 👍

**Comment by tylerjwatson** [comment] 2019-06-17 00:38
Team, I also noticed something of particular interest:

In the localStorage container, tokens acquired on initial boot have the `expiredIn` property set to a number:
![image](https://user-images.githubusercontent.com/5001408/59571793-a9ae5680-90eb-11e9-8400-d6766241bde4.png)

whereas subsequents (or tokens requested by `acquireTokenSilent`) are strings:

![image](https://user-images.githubusercontent.com/5001408/59571812-dd897c00-90eb-11e9-9737-02d44a3b4c71.png)

This may be breaking some of your comparison logic for clearing expired stuff and may be part of the reason why erroneous tokens are being returned from these calls.

Cheers

**Comment by scambier** [comment] 2019-06-17 06:22
> Is there any specific reason why the id token is getting injected into your Authorization header and not the access token? The workaround seems succinct, apart from this one line.
> 
> Cheers!

@tylerjwatson I have two objects containing an `access_token` in the localStorage (cf. my second screenshot), and their keys (that are also objects) don't make them easy to retrieve and compare, so I'm just picking the `msal.idtoken` value. Since it's a workaround, I didn't give it much thought and went with the first "it seems to work" solution

**Comment by scambier** [comment] 2019-07-03 07:06
Updated workaround: getting `msal.idtoken` from the localStorage does not work reliably, as the value is sometimes (often) not correctly updated by msal.

This function seems to get the correct, up-to-date token more reliably:

```ts
function extractMSALToken() {
  const timestamp = Math.floor((new Date()).getTime() / 1000)
  let token = null

  for (const key of Object.keys(localStorage)) {
    if (key.includes('"authority":')) {
      const val: any = JSON.parse(localStorage.getItem(key)!)

      if (val.expiresIn) {
        // We have a (possibly expired) token

        if (val.expiresIn > timestamp && val.idToken === val.accessToken) {
          // Found the correct token
          token = val.idToken
        }
        else {
          // Clear old data
          localStorage.removeItem(key)
        }
      }
    }
  }
  if (token) return token
  throw new Error('No valid token found')
}
```

**Comment by tylerjwatson** [comment] 2019-07-07 23:37
Guys,

This is a severe issue with a Microsoft product.  Can we please get an update and an ETA to fix?

Cheers

**Comment by sameerag** [comment] 2019-07-10 03:05
@pkanher617  Will your PR #799 solve some of the issues above?

**Comment by dluc** [comment] 2019-07-10 22:53
I'm experiencing the same issue, which is causing my app to stop working every 24 hours (when token expires). 

As a workaround I have to manage token expiration and clearing localstorage with dedicated code, which is far from ideal (and duplicates what MSAL should be doing) - the workaround could stop working anytime MSAL decides to use different storage keys.

**Comment by DarylThayil** [comment] 2019-09-09 18:24
Adding this bug to our October  2019 miletsone

**Comment by keystroke** [comment] 2019-09-14 02:59
I'm also running into this issue. MSAL is giving me an expired access token because one is in the cache. /Sigh. A fix won't be ready until after October milestone, released perhaps in November, and finally available at the CDN link maybe in time for Christmas? Am I to understand that I should be writing code directly in my application to muck around directly in the MSAL cache to try and remove the expired token?

**Comment by jasonnutter** [comment] 2019-09-25 21:50
@scambier Is this still an issue with the latest version (1.1.3)?

**Comment by bjornicus** [comment] 2019-09-27 20:43
@jasonnutter yes this is still a problem with 1.1.3

**Comment by sameerag** [comment] 2019-10-23 22:25
@scambier We pushed up some cache fixes(nonce clearance) in the recent `msal` beta releases. Can you please try `msal 1.2.0-beta.2` and report to us if the issue is still seen? The package is available in npm for download.

**Comment by scambier** [comment] 2019-10-24 11:35
@sameerag I've updated a few hours ago, and so far the token seems to refresh itself correctly, thanks.

**Comment by sameerag** [comment] 2019-10-29 00:33
Thanks @scambier. Closing this issue.

**Comment by scambier** [comment] 2019-10-31 08:18
@sameerag actually, it seems to still not working as expected, but maybe I'm misunderstanding. My setup is still the one described in the first post, but MSAL still often fails to refresh the token by itself.

Basicall, each ajax request I do is preceded by a call to this function:
```ts
  public async getAuthResponse(): Promise<Msal.AuthResponse> {
    try {
      return await this.userAgentApp.acquireTokenSilent(this.tokenRequest)
    }
    catch (e) {
      try {
        return await this.userAgentApp.acquireTokenPopup(this.tokenRequest)
      }
      catch (e) {
        console.error('Cannot retrieve token')
        throw e
      }
    }
  }
```

So, 401 responses shouldn't happen, right? Because they still happen (less often than when I created this issue, but still). Then I need to intercept those 401 responses, force an `acquireTokenPopup()`, and finally replay the request.

In the end the token is correctly refreshed, but some ajax calls are still missed.

Is there something I'm missing?

**Comment by mbondoso** [comment] 2019-11-25 11:20
I tested it on beta 1.2.0-4 but still not working.

**Comment by sameerag** [comment] 2019-11-25 23:10
How frequent is this @scambier the 401 errors? Ideally a token is valid for an hour and `acquireTokenSilent` if called within an hour will be able to refresh the token silently before the token expires as long as the session is valid. If the AAD session is invalid, that is when the user is prompted for interaction and may need to call `acquireTokenPopup`.

Can you paste the response you are seeing in the catch when `acquireTokenSilent` fails? What is the error thrown?

**Comment by scambier** [comment] 2019-11-26 11:50
> How frequent are the 401 errors?

They're infrequent, but they happen. I had 1 in 5 hours this morning, for example. That's why I thought the issue was fixed in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/759#issuecomment-545877042

> if called within an hour will be able to refresh the token silently before the token expires as long as the session is valid.

Yes, and that works most of the time. Just once in a while, it doesn't.

> Can you paste the response you are seeing in the catch when acquireTokenSilent fails? What is the error thrown?

It does not fail per se. Like I said in my previous post https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/759#issuecomment-548260376, it's almost like the acquireTokenSilent() is sending a false positive "your token is still fresh", when it should have been renewed. So when I call my API, it responds with a 401.

To circumvent this, I had to write an interceptor to catch the 401 responses. All it does is call acquireTokenSilent _again_, then retry my API call.

**Comment by jasonnutter** [comment] 2019-11-26 23:46
@scambier I wonder if you are encountering some sort of edge case, where MSAL thinks the token is still valid, but the API does not. Would you be able to share the access token (privately) with us next time this happens (along with the exact timestamp of the request)? Email is on my profile. Thanks!

**Comment by scambier** [comment] 2019-11-29 10:12
@jasonnutter I was wrong on my assumptions: the accessToken is not invalid, it's null. So yeah, it's normal to have a 401 response, since I'm sending "Bearer null" as my Authorization. But I guess it's not normal to have a null `accessToken`

However, everything else in the `acquireToken()` response is valid, even the `idToken.rawIdToken`. So when I re-query `acquireToken()`, the `accessToken` is correctly filled, and is identical to the previous `idToken.rawIdToken`.

This was the response I got today at 09:48 GMT. The expiration value is good (valid until 10:41 GMT)
![image](https://user-images.githubusercontent.com/3216752/69861243-4b8bbf00-1298-11ea-828c-695dc1bdde50.png)

**Comment by jasonnutter** [comment] 2019-12-02 16:55
@scambier Ah, I see. Note, that `acquireTokenSilent` can be used to retrieve access tokens and ID tokens, and it looks like the first time you call `acquireTokenSilent` in this scenario, you are returned an ID token, not an access token. I assume you are using the same `scopes` for both requests? Might be a bug if you are getting back an ID token the first time you make the call for a set of scopes and then an access token token the second time (with the same set of scopes). cc: @sameerag

**Comment by scambier** [comment] 2019-12-03 12:23
@jasonnutter 
>Note, that acquireTokenSilent can be used to retrieve access tokens and ID tokens, and it looks like the first time you call acquireTokenSilent in this scenario, you are returned an ID token, not an access token

It looks like it. There are some differences in the "Id Token" :
- `uniqueId` is filled (empty string in the Access Token)
- `tenantId` is filled (empty string in the Access Token)
- `accessToken` is null (filled in the Access Token)
- `scopes` are empty (filled in the Access token)
- `accountState` is different

If you still need them, I can send you both responses (id token and access token) privately by e-mail.

>  I assume you are using the same scopes for both requests?

Indeed.

**Comment by jasonnutter** [comment] 2019-12-04 23:44
@scambier Which scopes are you passing to `acquireTokenSilent`?

**Comment by scambier** [comment] 2019-12-05 07:40
@jasonnutter only our ClientId (application Id), in the form of `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Comment by jasonnutter** [comment] 2019-12-05 19:10
@scambier Ah, that would explain why you are getting back an ID token. To properly protect a custom web API using AAD access tokens, you need to register a custom scope in the Azure Portal, and then pass that custom scope to your login call as well as `acquireTokenSilent`. Your web API will need to use one of our middlewares to verify the access token.

See this comment for more info: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1040#issuecomment-540810355

**Comment by jasonnutter** [comment] 2020-01-09 18:08
Closing, as no further action at this time.

**Closed by jasonnutter** 2020-01-09 18:08 UTC
Labels: Issue Triage, bug, investigating

**Comment by arunprasathv** [comment] 2020-03-26 15:25
@jasonnutter @sameerag Is the issue fixed for Angular Wrapper Library as well ?

**Comment by jasonnutter** [comment] 2020-03-26 20:38
@arunprasathv This issue ended up being a usage problem. Any bugs that are fixed in the latest version of `msal` are fixed for MSAL Angular if you use the latest version of both `msal` and `@azure/msal-angular`. 

If you are encountering behavior you believe is a bug, please open a new issue, thanks!

**Comment by arunprasathv** [comment] 2020-03-26 21:36
@jasonnutter I see auth pop showing once the token expires when the user is in middle of something it pops up for auth which bad user experience.  Any examples would be great.

**Comment by jasonnutter** [comment] 2020-03-27 17:55
@arunprasathv Please open a new issue, thanks!

**Comment by mxswat** [comment] 2020-04-25 19:44
@jasonnutter I need to create a custom scope also if I'm using Azure Function Apps?

**Comment by jasonnutter** [comment] 2020-04-27 16:30
@mxswat Yes, if you are using access tokens for a custom API (e.g. an Azure Function), you should create a custom scope.

**Comment by rosiejaneenomar** [comment] 2020-07-04 07:05
Hi, I'm having this problem using azure-msal in angular

"msal": "^1.3.2",
"@azure/msal-angular": "^1.0.0",

 I have this custom checker if **msal.idtoken** is expired then i called this function to get new **idtoken**

![image](https://user-images.githubusercontent.com/7923836/86506959-d6243600-be06-11ea-9b14-959b68b6033f.png)

1. when it is success the existing **msal.idtoken** coming from your first login doesn't refresh. **(not that i was not using the msalInterceptor because i made a custom httpinceptor)**
2. it also added a new key the one that is highlighted in yellow.

![image](https://user-images.githubusercontent.com/7923836/86507046-91e56580-be07-11ea-80a3-17cf4fa0c846.png)

may i know someone who encountered this and found workaround? or any suggestions?
