### ISSUE TITLE
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. (Happened when start login with loginredirect and then user click browser goback button. And then click login button again)

### ISSUE THREAD

**Issue by oldorange** [AzureAD/microsoft-authentication-library-for-js#4167] opened 2021-10-18 20:21 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.12.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.01

### Description

Start login by click login button, call this function: 
export async function signIn(myMSALObj) {
    return myMSALObj.loginRedirect(loginRequest);
}

in the b2c login user journey, if user click browser's "goback button", and then click "login button" again,
the following error thrown:
index.es.js:524 Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at t [as constructor] (index.es.js:524)
    at new t (index.es.js:7129)
    at Function.t.createInteractionInProgressError (index.es.js:7190)
    at t.e.preflightInteractiveRequest (index.es.js:10817)
    at t.<anonymous> (index.es.js:10178)
    at index.es.js:75
    at Object.next (index.es.js:56)
    at index.es.js:49
    at new Promise (<anonymous>)
    at a (index.es.js:45)

since the go back button in browser use the cache. the following key value in sessionStorage will remain "interaction_in_progress" and cause the error.

![Screenshot 2021-10-18 161735](https://user-images.githubusercontent.com/25421843/137800791-8230d2f0-cbca-4f62-bb5e-983e7cce3bb3.png)

How to avoid this?

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "clientId",
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain], 
    redirectUri: "http://localhost:3000"
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true
  },
};
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2021-10-18 20:40
@oldorange Can you please update to the latest versions of MSAL Browser (2.18.0) and MSAL React (1.1.0), and then see if this is still an issue?

Also, are you able to reproduce this with our MSAL React B2C sample? https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample

**Comment by oldorange** [comment] 2021-10-19 17:32
Oh yes! The issue gone after I upgraded both lib to latest version.

**Comment by oldorange** [comment] 2021-10-19 20:08
oh no! after I upgrade both the packages, it works fine in dev mode: npm start. But it still has the same error in prod :(

**Comment by oldorange** [comment] 2021-10-19 20:08
Same issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4171#issuecomment-946423700

**Comment by oldorange** [comment] 2021-10-19 20:14
This time the sessionStorage is different 

(before I upgraded the packages): 
![Screenshot 2021-10-18 161735](https://user-images.githubusercontent.com/25421843/137983665-18c1cf71-30fd-4789-a5b7-64a66ae1c865.png)

after upgraded:

![Screenshot 2021-10-19 161124](https://user-images.githubusercontent.com/25421843/137983370-584d7a29-848c-4b9b-af82-66f70b2024c3.png)

**Comment by jasonnutter** [comment] 2021-10-19 22:18
Closing as duplicate of #4171. Please feel free to comment there.

**Closed as completed by jasonnutter** 2021-10-19 22:18 UTC
Labels: question, b2c, msal-browser, msal-react
