### ISSUE TITLE
Access SharePoint Online "_api/web/..." api using the MSAL library

### ISSUE THREAD

**Issue by dsm0880** [AzureAD/microsoft-authentication-library-for-js#400] opened 2018-08-17 20:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version
Library version: 0.2.1

## Current behavior
I cannot access any resource in the _api/web/lists/... api. SharePoint is a bit odd having multiple APIs to get data (Graph endpoint and _api endpoint), but before I dive into an MSAL conversion I wanted to know whether it actually supports access tokens to this SharePoint _api. I have tried without success. I cannot find anything in the Microsoft documentation about the supported APIs so I was hoping for some guidance. Note our application is currently working with ADAL. Thanks!

## Expected behavior
Able to access SharePoint _api/web/lists using the MSAL library.

**Comment by navyasric** [comment] 2018-08-28 23:12
@dsm0880 Can you provide some more details about which Sharepoint API you are trying to call?
What is the exact error message you got? MSAL should be able to get tokens for any of the Microsoft APIs.

**Comment by dsm0880** [comment] 2018-08-29 01:03
Well it's more of the setup that I ran into a dead end. According to the documentation you must register your app with the new registration portal to use V2.0 endpoint. When you go through that portal setup you can only add Microsoft Graph permissions. Granted you can access a ton of resources with this api you cannot do everything, especially in SharePoint. When calling SharePoint APIs outside of the Microsoft Graph you call <sitecollectionurl>/_api/web/lists for example will retrieve all the lists. If an app needs to perform this action using the Microsoft Graph permissions then I get an access denied error message. This makes sense to me as the scopes are different for the two APIs. In Microsoft Graph you as for Sites.Read where is the /_api endpoint you need AllSites.Read. My guess is the SharePoint /_api cannot be used with MSAL since it is for the V2.0 endpoint which only works with graph. I hope I'm wrong but that is what I concluded.

**Comment by andystroz** [comment] 2018-09-06 16:04
I am also interested in accessing the SharePoint API's using MSAL.js. Is there an example of showing how you can use a JWT bearer token obtained from the V2 endpoint to access the Sharepoint Online REST API. Currently I am struggling with what permissions to add to the Microsoft APP registration portal.

**Comment by viksakshum** [comment] 2018-10-30 01:35
i need it as well

**Comment by KishanRathod** [comment] 2019-02-01 22:33
I am having similar issues.
I tried to use graph api to access SharePoint Online in my Xamarin app then I found out that you cannot use Azure AD guest accounts ([Only Work and School accounts](https://docs.microsoft.com/en-us/graph/permissions-reference)). I decided to switch to SharePoint Api but I cannot get the correct scopes for SharePoint permissions. I tried **AllSites.Write** and https://`<domain>`.sharepoint.com/AllSites.Write with no success. I get scope parameter not valid error everytime (AADSTS28000).

**Comment by jampy** [comment] 2019-03-27 21:16
someone got this working?

**Comment by KishanRathod** [comment] 2019-03-27 21:19
> someone got this working?

I got around this issue by switching all my calls from Graph to SharePoint Rest Api.

**Comment by sushrutparanjape** [comment] 2019-04-04 07:36
Try the scope as : https://<domain>.sharepoint.com/Sites.ReadWrite.All

**Comment by zinonz** [comment] 2019-04-17 09:44
My azure tenant gives the sharepoint search scope as [https://microsoft.sharepoint-df.com/Sites.Search.All](url)

**Comment by Mentate** [comment] 2019-05-09 19:07
I have done some research on this. Based on [this](https://blog.mastykarz.nl/azure-ad-app-only-access-token-using-certificate-dotnet-core/) article you can use the AAD auth to access the SharePoint Rest API, but you must use a *certificate* rather than a secret. According to Microsoft's documentation  [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials) you can use MSAL for certificate based authentication, though I haven't quite figured it out yet.

**Comment by Mentate** [comment] 2019-05-09 21:21
I had to dig through the MSAL source but I got it to work! Below is the code I used (Python)

`cert = {"private_key": "key.pem contents", "thumbprint": "cert thumbpring"}# the thumbprint can be found on the app registration where you uploaded the cert
        app = msal.ConfidentialClientApplication(client_id = client_ID, client_credential = cert, authority = ("https://login.microsoftonline.com/" + tenant_id))        
        scope = ["https://yourSite.sharepoint.com/.default"]
        auth_token = app.acquire_token_for_client(scopes=scope) 
        session = requests.Session()
        session.headers.update({'Authorization': f'Bearer {auth_token["access_token"]}'})#adding headers using token
        session.headers.update({'Content-type': 'application/json'})
        session.headers.update({'Accept': 'aplication/json'})
        self.session = session
        self.digest = GetDigest(session, host, context)        
        self.host = host
        self.context = context`

**Comment by dsm0880** [comment] 2019-05-09 21:28
@Mentate Awesome, hopefully someone from Microsoft can shed some light as I would think digging through the source code shouldn't be needed, but I'll try something similar on our app and report back.

**Comment by mcqueene** [comment] 2019-05-24 01:26
> I had to dig through the MSAL source but I got it to work! Below is the code I used (it's Python but should be pretty much the same for js)
> 
@Mentate 
I might try to get this working in JS but I have yet to work with certs in AAD so I am not sure I can get a sample going.

**Comment by sameerag** [comment] 2019-06-24 20:53
@negoe Can you please help pointing (or creating if need be) a document that helps people understand how to access SharePoint resources using MSAL JS?

**Comment by Aculeo** [comment] 2019-06-25 13:26
@zedthehead I was confused by the same, but that is probably why it is a permission that requires admin consent.

The consent shows as `https://microsoft.sharepoint-df.com/Sites.Search.All`, but in the actual app you should request your token with the scope `https://yourtenant.sharepoint.com/Sites.Search.All`.  If you don't SharePoint Online will reject the token because of invalid audience (meaning the token wasn't issued for the correct tenant).

It's weird, and I wish the documentation mentioned this, because it cost me a lot of time to figure this out. I never thought it's possible to request a token with a different scope than defined in the app registration.

**Comment by sergey-tihon** [comment] 2019-06-28 04:57
There is an easier way, if you need one access token with all permissions configured in your AAD application, you can request them using one scope `https://yourtenant.sharepoint.com/.default`

**Comment by ZaMaZaN4iK** [comment] 2019-10-02 10:41
@sergey-tihon Sorry for the necroposting but can I with an access token for `https://yourtenant.sharepoint.com/.default` make requests to `https://yourtenant.sharepoint.com/subsite1/subsite2/subsite3`?

**Comment by sergey-tihon** [comment] 2019-10-02 10:43
@ZaMaZaN4iK yes, I believe so

**Comment by ashutoshbajpai007** [comment] 2019-11-05 11:15
i am trying to access the https://mytenant.sharepoint.com/sites/test/_api/web/lists API with help of  MSAL library .  I am getting unauthorized access error. 
I tried to use the  https://mytenant.sharepoint.com/.default as well but still there is same error.Can anyone please help me.Thanks

**Comment by sameerag** [comment] 2019-11-08 04:32
Apologies for the delay in the response. I reached out to the SPO team to clarify app permissions to access SPO resources as we know that they do use adal js for their SPA validation. Will update once I hear back from them.

**Comment by lahuey** [comment] 2019-11-11 18:10
@ashutoshbajpai007 could you please provide a SPRequestGuid (should be a header on the response from SharePoint) and tenant name? You can email it to me at lahuey@microsoft.com

**Comment by sameerag** [comment] 2019-11-15 23:44
**Info from SharePoint team on documentation:**

_Permission names for SharePoint sites and OneDrive files through Microsoft Graph are documented here:_
- _https://docs.microsoft.com/en-us/graph/permissions-reference#files-permissions_  
- _https://docs.microsoft.com/en-us/graph/permissions-reference#sites-permissions_

_The names of API permissions for the SharePoint resource application (including accessing SharePoint legacy REST API’s) are generally the same as they are in Graph, with similar restrictions._

**Comment by DuncanFisher** [comment] 2019-11-18 22:18
Also hitting this problem.
I need to use ClientId/Secret authentication and consume a list (get schema/fields and insert records).
I can't get the scopes to work. Even configuring SharePoint scopes I can't seem to make them work.

**Comment by jmckennon** [comment] 2019-12-04 23:10
@aiwangmicrosoft Can you please start working on this documentation and work with @negoe to close this documentation issue?

**Comment by osysltd** [comment] 2019-12-12 14:28
Indeed, I have granted permissions for the appV1 

![image](https://user-images.githubusercontent.com/1292744/70720329-e9997380-1cf3-11ea-8bbe-06d0c20fef42.png)

How should I use them properly? To be honest I've got lost between different APIs approaches and articles on the MSFT sites.

**Comment by sameerag** [comment] 2019-12-14 00:31
Can you please expand on the usage @osysltd? 

- How are you sending the scopes (request type and sample code?) and what is the response? 
- Which version of `msal js`?

**Comment by osysltd** [comment] 2019-12-16 13:17
@sameerag Thanks for picking up. I tried to obtain different endpoint tokens, was trying to use different APIs, different implementations of MSFT authentication and haven't even found a valuable MSFT article with the description on how to leverage the SharePoint App Registration permission. Sorry for possible offtopic but how should leverage the mentioned permissions?

**Comment by sameerag** [comment] 2019-12-19 00:31
@lahuey Can anyone from your team help here? Please tag the PM that can follow up and we can display a link in our documentation for SPO users.

**Comment by michaelmaillot** [comment] 2020-02-05 17:24
Hi,

As I was facing the same problems, I'll post here how I managed to connect to SharePoint API through AAD Application with MSAL (OAuth v2 and AAD v2 endpoint).

First, I only succeeded with a certificate (the client / secret method doesn't work as far as I know).

# Create certificate
For testing purposes, I've created a self-signed certificate with the "[New-PnPAzureCertificate](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/new-pnpazurecertificate?view=sharepoint-ps)" like this :

```powershell
$secPassword = ConvertTo-SecureString -String "MyPassword" -AsPlainText -Force
$cert = New-PnPAzureCertificate -OutCert "CertSPUser.cer" -OutPfx "CertSPUser.pfx" -ValidYears 10  -CertificatePassword $secPassword -CommonName "CertSPUser" -Country "FR" -State "France"
```
(The ```-Country``` and the ```-State``` parameters doesn't matter for the test)
(It also works with the [New-SelfSignedCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps) command)

# Register certificate
Then, you have to upload the certificate in your AAD Application (the ".cer" file):

![image](https://user-images.githubusercontent.com/44271458/73860438-d4e0e400-483b-11ea-8dbd-85705b69d78f.png)

# Set Up Application API Permissions
After that, you have to authorize the SharePoint APIs:

![image](https://user-images.githubusercontent.com/44271458/73862239-96005d80-483e-11ea-97d2-2aeac9b0e8a6.png)

# Try the access through Daemon App (C#)

## NuGet Packages (hope I forgot nothing)
- Microsoft.SharePointOnline.CSOM
- Microsoft.Identity.Client

To make things work, you have to it in 3 steps (I've simplified it, but you better separate the actions into methods with some try/catch)

## Get Pfx Certificate
For this step, I highly recommand to use a KeyVault (see links on the bottom of the post)
```csharp
string certPath = System.IO.Path.GetFullPath(@"C:\PathTo\CertSPUser.pfx");
X509Certificate2 certificate = new X509Certificate2(certPath, "MyPassword", X509KeyStorageFlags.MachineKeySet);
```

## Get Token
```csharp
string tenantId = "yourTenant.onmicrosoft.com" // Or "TenantId"
string applicationId = "IdOfYourAADApp"
IConfidentialClientApplication confApp = ConfidentialClientApplicationBuilder.Create(applicationId)
.WithAuthority($"https://login.microsoftonline.com/{tenantId}")
.WithCertificate(certificate)
.Build();

string sharePointUrl = "https://yourSharePoint.sharepoint.com" // Or "https://yourSharePoint-admin.sharepoint.com" if you want to access the User Profile REST API
var scopes = new[] { $"{sharePointUrll}/.default" };
var authenticationResult = await confApp.AcquireTokenForClient(scopes).ExecuteAsync();
string token = authenticationResult.AccessToken;
```

## Test your connection
```csharp
ClientContext ctx = new ClientContext(sharePointUrl);
ctx.ExecutingWebRequest += (s, e) =>
{
      e.WebRequestExecutor.RequestHeaders["Authorization"] = "Bearer " + token;
};

Web web = ctx.Web;
ctx.Load(web);
ctx.Load(web);
ctx.ExecuteQuery();

// OR if you connect to User Profile ("sharepointsite-admin.sharepoint.com")
/* 
PeopleManager peopleManager = new PeopleManager(ctx);
var personProperties = peopleManager.GetUserProfileProperties("i:0#.f|membership|employee.mail@tenant.onmicrosoft.com");
ctx.ExecuteQuery();
*/
```

And if I didn't miss anything, you should get some Web Info ! 😉

Hope that it helps.

Thanks to @laurakokkarinen and @mmsharepoint for their articles that really helped me ([here](https://laurakokkarinen.com/authenticating-to-office-365-apis-with-a-certificate-step-by-step/) and [here](https://mmsharepoint.wordpress.com/2019/01/11/secure-azure-functions-part-2-handle-certificates-with-azure-keyvault-when-accessing-sharepoint-online/))

**Comment by michaelmaillot** [comment] 2020-02-07 16:13
> @sameerag Thanks for picking up. I tried to obtain different endpoint tokens, was trying to use different APIs, different implementations of MSFT authentication and haven't even found a valuable MSFT article with the description on how to leverage the SharePoint App Registration permission. Sorry for possible offtopic but how should leverage the mentioned permissions?

Hi @osysltd !

The AAD Permissions you want to set up depends on your context (maybe you already have the answer though):
- If you want to interact with SharePoint throught a (C#) console application (daemon app), you will set up **Application Permissions** ([Client Credential Flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials))
- If you want to interact with SharePoint in user context (client side), you will set up **Delegated Permissions** ([Implicit Flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#implicit-grant), [Interactive](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#interactive) or [Authorization Code](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#authorization-code))

I have tested both contexts and its working 🙂 

If you want the process for Daemon App using the Client Credential Flow (although it's off topic), I proposed a solution [here](https://stackoverflow.com/questions/54771270/msal-ad-token-not-valid-with-sharepoint-online-csom/60090373#60090373)

If you want the process for SPA using the Implicit Flow, you can try to reproduce steps below (assuming that you already have registered your AAD Application).

# Set up AAD Application
## Authentication
You must configure your Application to set redirect URL and manage tokens (for the Implicit Flow), by adding a "Web" Platform:
![image](https://user-images.githubusercontent.com/44271458/74035277-4646a100-49ba-11ea-9606-687bf067ebac.png)

You also must set your Application to support multi-tenant accounts:
![image](https://user-images.githubusercontent.com/44271458/74035574-ca008d80-49ba-11ea-8fc2-3019bf411734.png)

## Set up Delegated API Permissions
You have to authorize the SharePoint APIs:

![image](https://user-images.githubusercontent.com/44271458/74034481-a6d4de80-49b8-11ea-8be4-ac77d185cfc2.png)

# Try the access through SPA (MSAL.js)

You can reuse [this sample](https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2) explained [here](https://docs.microsoft.com/fr-fr/azure/active-directory/develop/tutorial-v2-javascript-spa) with the following modifications:

## Update (or not) MSAL.js version
Update line 6 to replace this:
```html
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.js"></script>
```
By this:
```html
<script src="https://alcdn.msauth.net/lib/1.2.0/js/msal.min.js"></script>
```

## Set up configuration
Update from line 21 to 26:
```javascript
const msalConfig = {
    auth: {
      clientId: 'Enter_the_Application_Id_here', //This is your client ID
      authority: "https://login.microsoftonline.com/Enter_the_Tenant_Info_Here", //This is your tenant info
      redirectUri: "Enter_the_Redirect_Uri_Here" //This is your redirect URI
}
```

## Set up endpoint
You can replace the following declaration line 33 (or keep the Graph call and add other endpoints) by this:

```javascript
const account = "loginAccountToGetInfo"
const domain= "yourtenant.onmicrosoft.com"
const spUrl = "https://onepointdev365.sharepoint.com"
const appConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
    spListsEndpoint: spUrl + "/_api/lists",
    spUsersEndpoint: spUrl + `/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)?@v='i%3A0%23.f%7Cmembership%7C${account}%40${domain}'`
};
```
(make sure to replace ```graphConfig``` with ```appConfig``` everywhere you call it in the code)
In this example, I've set up two endpoints:
- one for reaching a Site's Lists (requires "AllSites.Read" AAD delegated permission)
- one for reaching User Profile Properties (requires "User.Read.All" AAD delegated permission)

## Set up the scope
Next, go to line 33 (or 43 after code update) and set the desired scope:
```javascript
const requestObj = {
    scopes: [spUrl + "/.default"]
};
```
(As the SharePoint REST API is a v1 endpoint, you don't specify the scope but the "default" resource, instead of Graph API)

## Call the right endpoint
Then, you can refer to those SP endpoints in your ```callMSGraph``` method like this (lines 85 and 113 for example or lines 79 and 105 before code update):
```javascript
callMSGraph(
     appConfig.spUsersEndpoint,
     tokenResponse.accessToken,
     graphAPICallback
);
// OR
callMSGraph(
     appConfig.spListsEndpoint,
     tokenResponse.accessToken,
     graphAPICallback
);
```

## Update API Call Headers
Finally, update the ```callMSGraph``` method to add JSON header as the returned format (below line 181 or 186):
```javascript
xmlHttp.open("GET", theUrl, true); // true for asynchronous
xmlHttp.setRequestHeader("Authorization", `Bearer ${accessToken}`);
xmlHttp.setRequestHeader("Accept", "application/json; odata=verbose");
xmlHttp.send();
```

Then you can try ! 🙂 

Please let me know if it's working or not, or I missed something.

Hope that it helps.

**Comment by osysltd** [comment] 2020-02-27 11:08
Hi @michaelmaillot! 
Thanks a lot for explicit clarification, but as I can see you leverage Graph API permissions set in the app registration and not SharePoint

```
const account = "loginAccountToGetInfo"
const domain= "yourtenant.onmicrosoft.com"
const spUrl = "https://onepointdev365.sharepoint.com"
const appConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
    spListsEndpoint: spUrl + "/_api/lists",
    spUsersEndpoint: spUrl + `/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)?@v='i%3A0%23.f%7Cmembership%7C${account}%40${domain}'`
};
```

![image](https://user-images.githubusercontent.com/1292744/75439143-954c7a00-5959-11ea-891e-ca46246f9355.png)


Could you please give a hint (or any reference to MSFT article) on how to reuse SharePoint permissions set and not Graph API

![image](https://user-images.githubusercontent.com/1292744/75439244-be6d0a80-5959-11ea-950a-3481b8b4cd1b.png)

**Comment by sameerag** [comment] 2020-03-06 19:36
We have all the instructions from multiple people on this thread. Closing this now and if there are new questions, please raise a new PR.

**Closed by sameerag** 2020-03-06 19:36 UTC
Labels: Issue Triage, documentation, question
