### ISSUE TITLE
Msal Browser not working with Azure Ad B2C

### ISSUE THREAD

**Issue by dersia** [AzureAD/microsoft-authentication-library-for-js#6360] opened 2023-08-17 20:15 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

Azure Ad B2c does not support the scope profile. and when used with B2c with msal loginRedirect or loginPopup the scope is added automatically (I think since this PR #2267).

as you can see here in the official docs it only supports the scopes openid and offline_access https://learn.microsoft.com/en-us/azure/active-directory-b2c/openid-connect

I think it makes sense to make the default scopes either overrideable or provide a way to disable them.

Although I do understand why this is done, I think automatically adding anything to the request is not a good practice and needed setup like scopes should be in documentation. anyhow now that it is there and it would probably be a breaking change to remove them silently I would prefer a way to opt out of it. this would also allow me to force our devs to add the scopes manually so they understand what is happening.

### MSAL Configuration

```javascript
auth: {
    clientId: "<my-clientID>",
    authority: "https://<my-tenant>.b2clogin.com/<my-tenant>.onmicrosoft.com/<my-policyID>",
    knownAuthorities: ["<my-tenant>.b2clogin.com"]
  }
```

### Relevant Code Snippets

```javascript
new PublicClientApplication(config).instance().loginRedirect({ scopes: ['openid offline_access']});
```

### Reproduction Steps

1. Create a B2c tenant
2. add a user singing flow
3. add an application
4. add a user
5. try using msal

### Expected Behavior

redirected to b2c login page so I can login

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment] 2023-08-17 20:34
@dersia thanks for raising the issue. While the B2C service doesn't support profile, it doesn't fail a request that includes it. This is a duplicate of #6340, which has been solved in #6342, which will ship in the next release. Please look at #6340 for the explanation and a workaround in the meantime.

**Closed as completed by hectormmg** 2023-08-17 20:34 UTC
Labels: question, b2c, msal-browser, bug-unconfirmed, public-client
