### ISSUE TITLE
Can't Login to B2C tenant with msal-browser 2.x.x (empty_input_scopes_error)

### ISSUE THREAD

**Issue by Georgeoak** [AzureAD/microsoft-authentication-library-for-js#1943] opened 2020-07-13 21:24 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.0.0-beta.3`
- [ ] `@azure/msal-browser@2.0.0-beta.4`

## Framework
VanillaJSTestApp2.0 default example.

## Description
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default
I'm using this default example with B2C tenant, it can redirect to B2C login page, after input user name and password,
click login, it shows below error in the console.
 (BTW, I already disabled web-security for Chrome to bypass CORS issue with B2C.)

## Error Message
```
auth.js:20 ClientConfigurationError: empty_input_scopes_error: Scopes cannot be passed as null, undefined or empty array because they are required to obtain an access token. Given Scopes: 
    at ClientConfigurationError.AuthError [as constructor] (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:201:28)
    at ClientConfigurationError.ClientAuthError [as constructor] (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:481:32)
    at new ClientConfigurationError (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:1362:32)
    at Function.ClientConfigurationError.createEmptyScopesArrayError (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:1418:20)
    at ScopeSet.validateInputScopes (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:1517:48)
    at new ScopeSet (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:1494:18)
    at Function.ScopeSet.fromString (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:1507:20)
    at ResponseHandler.generateCacheRecord (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:3155:43)
    at ResponseHandler.handleServerTokenResponse (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:3134:36)
    at AuthorizationCodeClient.<anonymous> (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:3420:61)
    at step (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:166:27)
    at Object.next (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:147:57)
    at fulfilled (https://alcdn.msauth.net/browser/2.0.0-beta.4/js/msal-browser.js:137:62)
    at r (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:31:10952)
    at i._settlePromiseFromHandler (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:30:15746)
    at i._settlePromise (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:30:16549)
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? No
Version:

## MSAL Configuration

authConfig.js
```
// Config object to be passed to Msal on creation
const msalConfig = {
    auth: {
        clientId: "xxx",
        authority: "https://xxx.b2clogin.com/xxx.onmicrosoft.com/B2C_1A_SignUpOrSignIn",        
        knownAuthorities: ["xxx.b2clogin.com"],
        redirectUri: "http://localhost:30662/",
        navigateToLoginRequestUrl: true,
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {	
                    return;	
                }	
                switch (level) {	
                    case msal.LogLevel.Error:	
                        console.error(message);	
                        return;	
                    case msal.LogLevel.Info:	
                        console.info(message);	
                        return;	
                    case msal.LogLevel.Verbose:	
                        console.debug(message);	
                        return;	
                    case msal.LogLevel.Warning:	
                        console.warn(message);	
                        return;	
                }
            }
        }
    }
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
const loginRequest = {
    scopes: ["openid", "profile", 'offline_access'],
    redirectUri: "http://localhost:30662/"
};

// Add here the endpoints for MS Graph API services you would like to use.
const graphConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
    graphMailEndpoint: "https://graph.microsoft.com/v1.0/me/messages"
};

// Add here scopes for access token to be used at MS Graph API endpoints.
const tokenRequest = {
    scopes: ["openid", "profile", 'offline_access', 'User.Read'],
    redirectUri: "http://localhost:30662/",
    forceRefresh: false // Set this to "true" to skip a cached token and go to the server to get a new token
};

const silentRequest = {
    scopes: ["openid", "profile", "https://graph.microsoft.com/User.Read"],
    redirectUri: "http://localhost:30662/"
};
```

## Reproduction steps
1. Startup default example
2. Open "http://localhost:30662"
3. Click 'Sign in use Redirect'
4. Input user name and password then click login.

## Expected behavior
Login to B2C and display Home page.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment] 2020-07-13 23:11
@Georgeoak Thanks for reporting this. I was able to reproduce this and have a fix up in PR #1946. For now, until that is merged, you can pass a valid resource scope to your login request. Note that MS Graph is not supported in B2C scenarios so the examples you have shown are not expected to work without some additional setup.

**Comment by Georgeoak** [comment] 2020-07-14 12:57
@tnorling Thanks for your quick response.
Could you please give me more detailed info about valid resource scope to login request?
like below?
scopes: ["https://xxx.onmicrosoft.com/tenantId/openid", 
    "https://xxx.onmicrosoft.com/tenantId/profile",
    "https://xxx.onmicrosoft.com/tenantId/user_impersonation",
    "https://xxx.onmicrosoft.com/tenantId/User.Read"],

You mentioned MS Graph API is not supported in B2C, what kind of additional setup do I need to do?

Thank you very much.

**Comment by tnorling** [comment] 2020-07-14 16:20
In order to use MS Graph you would need to create an extra App registration on an AAD tenant and have that app registration do all your MS Graph calls. B2C cannot get tokens for MS Graph directly. 

As for the scopes, `user_impersonation` might work you can give it a shot, but I would suggest creating a custom dummy scope on your app registration. `User.Read` won't work as it's a Graph scope, and `openid` and `profile` won't get you an access token back, which is the root cause of the bug you found.

**Comment by Georgeoak** [comment] 2020-07-14 17:36
@tnorling Thank you so much for the detailed explanation.

**Closed** 2020-07-15 17:52 UTC
Labels: b2c, bug
