### ISSUE TITLE
conditional access policies validation

### ISSUE THREAD

**Issue by ryandegruyter** [AzureAD/microsoft-authentication-library-for-js#713] opened 2019-05-15 05:40 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

## Current behavior
Users can not authenticate with Azure because they cannot provide the required information to validate conditional access policies.

## Expected behavior
Users can authenticate by providing device information and meeting the requirements set by conditional access.

**Comment by sameerag** [comment] 2019-05-15 05:42
@ryandegruyter Can you please send us the steps to Repro? We have some 'claims' behavior already supported and the 'Conditional Access' feature in progress. Understanding where your use case falls through will help us track this with the CA feature.

**Comment by ryandegruyter** [comment] 2019-05-15 06:52
@sameerag our specific use case is a Cordova based app being deployed as a native app for Android and iOS.

These devices need to comply with the "Require compliant device" conditional access policy.
The compliancy rules are set by our MDM solution Microsoft Intune.

Do you think it is possible for this library to provide the required device information?

**Comment by sameerag** [comment] 2019-05-15 17:11
@pkanher617 can you please check if this scenario is supported/will be supported in our upcoming CA feature?

**Comment by pkanher617** [comment] 2019-05-15 23:45
Hi @ryandegruyter, can you please explain how you are using msal.js to perform the request? We support the scenario [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/conditional-access-dev-guide#complying-with-a-conditional-access-policy) where the app attempts to access a service with a conditional access policy and is given a claims challenge to pass to the subsequent request. Your scenario may be a little different, and it may be something we support, but I would need to understand more about how the communication works.

**Comment by ryandegruyter** [comment] 2019-05-16 11:56
Hi @pkanher617 , we're currently using the ADAL Cordova plugin (https://github.com/AzureAD/azure-activedirectory-library-for-cordova/tree/archive#broker-support) which works for our scenario.

But since it has been deprecated, I'm currently investigating alternative solutions.
I haven't made any specific implementation yet with MSAL since I'm only reading and searching through various documentation and investigating possibilities.

I just have my doubts this can work without communicating with native API's. For example, how can the MSAL library find out if the user has a rooted device or not? 

Before I dive in, I just want to make sure it's possible, and if not, get an idea if it will be supported in the near future?

**Comment by DarylThayil** [comment] 2019-05-20 22:23
@ryandegruyter  Confirming you want to use msal js with Cordova correct? 
We have not tested with cordova in msal js.   As it currently stands msal js is aimed toward single page web apps. 
My suggestion would be to try out the library in your app and see what is missing for you.  If they are easy features, we can try and work them into our roadmap.  If they require a new msal-cordova lib, that is good feedback as well.

**Comment by DarylThayil** [comment] 2019-05-20 22:27
@ryandegruyter  elaborating on "does it fit your use case", might mean that you look at what cordova exposes api wise, and find in our code where that could be used and open another issue / pr ( this will help us understand how it can fit into our roadmap) 
Sorry I don't have a better answer. 
Closing this for now, since this is not a bug.

**Closed by DarylThayil** 2019-05-20 22:27 UTC
