### ISSUE TITLE
 Token renewal operation failed due to timeout(React).

### ISSUE THREAD

**Issue by suresh777** [AzureAD/microsoft-authentication-library-for-js#1290] opened 2020-02-19 10:15 UTC
Hi, i am using this library(msal@1.2.1) in my react project for authentication. I am trying loginRedirect, after that i am trying silent token.
I am facing this issue

 ```
Token renewal operation failed due to timeout.
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/static/js/0.chunk.js:65073:24)
    at new ClientAuthError (http://localhost:3000/static/js/0.chunk.js:65218:24)
    at Function.ClientAuthError.createTokenRenewalTimeoutError (http://localhost:3000/static/js/0.chunk.js:65255:12)
    at http://localhost:3000/static/js/0.chunk.js:67409:89
```
But if i use msal@1.1.3 it is working

**Comment by jasonnutter** [comment] 2020-02-26 23:59
@suresh777 Apologies for the delay. Are you getting a response in `handleRedirectCallback`? Also, it would be helpful if you could debug MSAL to determine what is happening when you call `acquireTokenSilent`, as timeouts could happen for a number of reasons.

Any other information you can provide (such as Fiddler traces, correlation IDs) would be helpful, thanks!

**Comment by suresh777** [comment] 2020-02-28 10:05
I am not getting any response in handleRedirectCallback and  in fiddler traces also nothing i found

**Comment by jasonnutter** [comment] 2020-03-02 20:51
@suresh777 Can you share the Fiddler trace with me? Email is in my profile, thanks!

**Comment by suresh777** [comment] 2020-03-03 11:21
I didn't get any traces in console and so many users already raised this issue, It is not working in latest version

**Comment by jasonnutter** [comment] 2020-03-11 23:57
@suresh777 A Fiddler trace will help us in debugging your issue. There are many things that can cause a timeout, so your situation may be different from others.

**Comment by suresh777** [comment] 2020-04-09 09:57
Token renewal working in msal@1.1.3 version. Why it is not working with latest msal@1.2.2 version

**Comment by jurisjansons** [comment] 2020-04-16 13:19
@jasonnutter Hello, I'm facing simmilar issue when trying to renew token. I'm currently using msal@1.3.0-beta.1. Authorization works fine, but when I need to renew token I get timeout error. 

Here are some logs from msal:
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Verbose Token is not in cache for scope:66a74d60-dc9b-4289-8525-afa544135f73`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Verbose renewing idToken`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Info renewidToken is called`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Info Add msal frame to document:msalIdTokenFrame`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Verbose Renew Idtoken Expected state: eyJpZCI6IjAxN2ZhMjIwLWM4YTgtNGViOC04NjY3LTQwOGFiZDc0Njk4MiIsInRzIjoxNTg3MDQxNjc2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Verbose Set loading state to pending for: 66a74d60-dc9b-4289-8525-afa544135f73:eyJpZCI6IjAxN2ZhMjIwLWM4YTgtNGViOC04NjY3LTQwOGFiZDc0Njk4MiIsInRzIjoxNTg3MDQxNjc2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9`
`[MSAL] Thu, 16 Apr 2020 12:54:35 GMT:1.3.0-Info LoadFrame: msalIdTokenFrame`
`[MSAL] Thu, 16 Apr 2020 12:54:36 GMT:1.3.0-Info Add msal frame to document:msalIdTokenFrame`
`InvalidAccessError: A parameter or an operation is not supported by the underlying object authorize:82`
`[MSAL] Thu, 16 Apr 2020 12:54:42 GMT:1.3.0-Verbose Loading frame has timed out after: 6 seconds for scope 66a74d60-dc9b-4289-8525-afa544135f73:eyJpZCI6IjAxN2ZhMjIwLWM4YTgtNGViOC04NjY3LTQwOGFiZDc0Njk4MiIsInRzIjoxNTg3MDQxNjc2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9`
`[ERROR] ClientAuthError: URL navigated to is https://login.microsoftonline.com/2d657834-57ae-4bce-91ec-a4395f9c062f/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=66a74d60-dc9b-4289-8525-afa544135f73&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth.html&state=eyJpZCI6IjAxN2ZhMjIwLWM4YTgtNGViOC04NjY3LTQwOGFiZDc0Njk4MiIsInRzIjoxNTg3MDQxNjc2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=5058cfb0-bb96-4de7-bf5b-8766c8cffe64&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Juris.Jansons%40wearedots.com&client-request-id=193fc654-eefa-4b71-8dbf-a4b807be4886&prompt=none&response_mode=fragment, Token renewal operation failed due to timeout.`

If you need more info let me know.

**Comment by jasonnutter** [comment] 2020-04-18 00:39
@jurisjansons It looks like the redirectUri you used for that request is invalid, in that it is not registered in the Azure Portal for that application. Add `http://localhost:3000/auth.html` to the list of redirect URIs in the Azure Portal and try again.

**Comment by jurisjansons** [comment] 2020-04-20 07:08
@jasonnutter thank you, that resolved my timeout issue, had it added with `https` not `http`

**Comment by suresh777** [comment] 2020-04-20 07:15
@jasonnutter right now my project redirect uri http://localhost:3000/, you are saying that change to http://localhost:3000/auth.html. Any difference between these two redirect uri.

**Comment by jurisjansons** [comment] 2020-04-20 07:30
@suresh777  AFAIK `auth.html` is used to open webpage on your domain withour loading in any scripts to store a new cookie, if you use plain `http://localhost:3000/` then, I think you need to handle that it doesn't call another authorization cycle witch can result in loop, I think. I'm using `react-aad-msal` to handle that for me and it was written in theirs documentation

**Comment by suresh777** [comment] 2020-04-20 07:38
Thanks, in auth.html what code should i write. Do you have any auth.html sample

**Comment by jurisjansons** [comment] 2020-04-20 07:45
@suresh777 it's empty `.html` file, empty file with `.html` as extenstion, didn't even add any html code in it. I have placed it in public folder (next to index.html) so I can call it without rendering react. [Here](https://github.com/syncweek-react-aad/react-aad/tree/master/samples/react-javascript) is sample from `react-aad-msal`

**Comment by suresh777** [comment] 2020-04-20 09:35
Thanks @jurisjansons , I will try

**Comment by jasonnutter** [comment] 2020-04-20 16:52
Quick note, we found a regression that will be fixed in `1.3.0` by #1516, which might be the root cause of this issue.

**Comment by suresh777** [comment] 2020-04-24 06:17
I guess you are using react-aad-msal but i am using msal js library. Here where should i give token refresh uri
export const msalApp = new UserAgentApplication({
  auth: {
    clientId: “XXXXXXXXXXXXXXXXXXXXX”,
    authority:
      "https://login.microsoftonline.com/XXXXXXXXXXXXXXXX/“,
    validateAuthority: true,
    postLogoutRedirectUri:
      "https://login.microsoftonline.com/XXXXXXXXXXXXXXXX/oauth2/logout",
    redirectUri: redirectUri,
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: isIE(),
  }

});

**Comment by tnorling** [comment] 2020-04-24 20:14
@suresh777 Pass it into the request object you send to ```acquireTokenSilent```, not to your msal config. You will need to also make sure that it is registered in the app portal as a valid redirect uri

**Comment by suresh777** [comment] 2020-04-27 08:05
@tnorling i am passing like below still it is not working, i am getting token renewal client error

export const LOGIN_REQUEST = {
  scopes: ["xxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  redirectUri:"http://localhost:3000/auth.html"
};

 msalApp
      .acquireTokenSilent(LOGIN_REQUEST).then((response) => {
})

**Comment by tnorling** [comment] 2020-04-27 17:37
@suresh777 Can you try opening the link provided in the error in a new tab or window? This might help you narrow down what is happening.

**Comment by suresh777** [comment] 2020-04-28 07:25
I clicked that link it opens in new tab 
http://localhost:3000/auth.html#id_token=xxxxxxxxxxxxxxxxxxxxxxxx
the site cannot be reached localhost refused to connect message showing on browser

**Comment by tnorling** [comment] 2020-04-28 15:38
@suresh777 Sounds like that's your issue. Does `auth.html` exist on your webserver? You can see the token is being returned in the url, figure out why your webserver isn't serving up `auth.html` and your timeout issue should resolve itself.

**Comment by suresh777** [comment] 2020-04-28 15:49
You are saying that in azure http://localhost:auth.html is not registered right. I kept auth.html in react public folder

**Comment by tnorling** [comment] 2020-04-28 16:58
@suresh777 From what you shared it sounds like your server is refusing to serve auth.html. This is something you need to troubleshoot yourself, I cannot help you with this. You can verify this by navigating directly to the page without using msal.

**Comment by suresh777** [comment] 2020-04-29 09:45
I checked everything it is serving properly but it is not returning to my app if i change to localhost:3000 it is returning to my app otherwise it struck there
<img width="1440" alt="Screenshot 2020-04-29 at 3 10 49 PM" src="https://user-images.githubusercontent.com/10288824/80582224-f06b1d80-8a2b-11ea-828e-c2ff3a598e12.png">

**Comment by tnorling** [comment] 2020-04-29 14:30
@suresh777 The blank html page should only be used for silent or popup flows. When using redirect flows you will need to set your redirect uri to a page that loads msal.

**Comment by tnorling** [comment] 2020-05-06 19:45
Closing as I don't believe this is an issue with msal. Let us know if you are still unable to get this working.

**Closed by tnorling** 2020-05-06 19:45 UTC
Labels: bug

**Comment by suresh777** [comment] 2020-05-07 05:38
I checked with msal@1.2.2 , refresh token is working properly with auth.html
