### ISSUE TITLE
Angular 9 application error after redirect from successful Azure B2C login

### ISSUE THREAD

**Issue by mg-arrow** [AzureAD/microsoft-authentication-library-for-js#2835] opened 2021-01-06 19:35 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.8.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.0.0-alpha.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [X] Angular
- [ ] React
- [ ] Other

## Description

We are trying to integrate the existing Angular 9 application with existing custom policy in B2C tenant. We are using the sample code from the B2C integration sample and getting redirected to Azure and were able to login. The application fails after the redirect with the message listed below.

## Error Message

EXCEPTION: Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at BrowserAuthError.AuthError [as constructor] (index.es.js:503)
    at new BrowserAuthError (index.es.js:6627)
    at Function.push../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createInteractionInProgressError (index.es.js:6670)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.preflightInteractiveRequest (index.es.js:9843)
    at PublicClientApplication.<anonymous> (index.es.js:9286)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:44)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:705
    at step (index.es.js:47)
    at index.es.js:48
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.PublicClientApplication.loginRedirect (index.es.js:10051)
    at MsalService.loginRedirect (azure-msal-angular.js:48)
    at AppComponent.login (app.component.ts:147)

## MSAL Configuration

The policy name - B2C_1A_ARW_ECSDEV_SIGN_UP_SIGNIN_V1
application client_id - 8d19f993-c776-4209-a9c3-913fcbc048a2

## Reproduction steps

Application files will be provided via secure files transfer.

## Expected behavior

Application is using the token provided from Azure B2C.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [X] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by mg-arrow** [comment] 2021-01-07 00:45
I enabled logging as suggested and only got 1 additional line added the output

[Thu, 07 Jan 2021 00:43:10 GMT] :  : @azure/msal-browser@2.8.0 : Info - Emitting event: msal:loginStart

core.js:40846 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
exception-handler.service.ts:10 EXCEPTION: Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at BrowserAuthError.AuthError [as constructor] (index.es.js:503)
    at new BrowserAuthError (index.es.js:6627)
    at Function.push../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createInteractionInProgressError (index.es.js:6670)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.preflightInteractiveRequest (index.es.js:9843)
    at PublicClientApplication.<anonymous> (index.es.js:9286)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:44)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:705
    at step (index.es.js:47)
    at index.es.js:48
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.PublicClientApplication.loginRedirect (index.es.js:10051)
    at MsalService.loginRedirect (azure-msal-angular.js:48)
    at AppComponent.login (app.component.ts:148)
client:52 [WDS] Live Reloading enabled.

**Comment by jo-arroyo** [comment] 2021-01-07 19:41
@mg-arrow Can you email me the application files along with steps to reproduce the error?

**Comment by mg-arrow** [comment] 2021-01-07 20:00
Jo,

I've attached the important files using the secure transfer link provided by Ray.

The application is very large and some parts of the application contain sensitive information, which I would not be able to share. Plus you would not be able to run it because application is using our on prem APIs.

Is it possible to have follow up call later today using Teams and I will show you the whole flow.

Thanks a lot for your help

Regards

Mikhail


Mikhail Goncharov
Enterprise Architect
T: +1 303-566-5057|M: +1 720-838-8258
E: mgoncharov@arrow.com
Arrow Electronics | arrow.com

**Comment by jo-arroyo** [comment] 2021-01-08 00:09
@mg-arrow Thanks for the files. It looks like the check on lines 129-130 of `app.component.ts` may be causing the interaction in progress error. Can you try removing it and seeing if you still have errors?

**Comment by mg-arrow** [comment] 2021-01-08 21:02
I used the original code without the lines 129-130 in the app.component.ts file but this way application did not redirect to the B2C login screen and nothing was happening.

I've added lines 

if (!this.loggedIn)
      this.login();

to force login in case user is not logged in yet.

**Comment by jasonnutter** [comment] 2021-01-08 21:15
@mg-arrow Have you tried using the `MsalGuard` (which will handle checking if the user is logged in and redirect them to login if not)?

**Comment by mg-arrow** [comment] 2021-01-08 21:23
Yes, MsalGuard is setup on the routing to protect main route of of the application.

I think I sent you all the routing details.

Let me know if you need additional info.

**Comment by jasonnutter** [comment] 2021-01-08 22:29
@mg-arrow If your app is using the MSAL Guard for the main route, why do you have the logic to manually invoke `loginRedirect` on page load (as the MSAL Guard should do this for you)?

**Comment by mg-arrow** [comment] 2021-01-09 07:02
This is the reason we added the code on app.component.ts to force the redirect (see above)

Do you recommend to place it in the different place ?

**Comment by jo-arroyo** [comment] 2021-02-05 22:08
Closing as this issue as a fix for redirects has been released, and continuing communication is being handled with the customer offline. Future questions regarding redirects should open a new issue.

**Closed by jo-arroyo** 2021-02-05 22:08 UTC
Labels: bug-unconfirmed, question
