### ISSUE TITLE
Using msal-angular with Angular9 and IE11 causes build error.

### ISSUE THREAD

**Issue by corporate-warrior** [AzureAD/microsoft-authentication-library-for-js#3765] opened 2021-06-17 09:43 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

We're using IE11 with Angular9 in our project, but having some trouble while introducing msal-angular into it.
When we install msal-angular and build the project, we get the following error.

_ERROR in getInternalNameOfClass() called on a non-ES5 class: expected MsalService to have an inner class declaration_

It's clear that it is just a compilation issue of msal-angular which is built with ES2015 has not downgraded properly by Angular9 IVY compiler,
We've already got around this problem by using locally built msal-angular package targetting at es5, and put it directly into the resource, but I wonder if there's any better workaround.

### Relevant Code Snippets

```javascript
It's fairly easy to reproduce using an official sample.

1. download Angular9 sample
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular9-v2-sample-app

2. change build target to ES5
[tsconfig.json]
"target": "es5",

3. add some pollyfills
npm -i core-js@latest
[pollyfill.ts]
import 'core-js';

4 npm run build
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2021-06-17 23:27
I can reproduce this, and will close as a duplicate of #3277. It seems Angular 9 does not perform the needed transpiling by default, while Angular 11 does, so I'll see if I can figure out what can be done about that.

**Closed by jasonnutter** 2021-06-17 23:27 UTC
Labels: b2c, msal-angular, msal-browser, question
