### ISSUE TITLE
How to protect all routes - Node Back End

### ISSUE THREAD

**Issue by nubianMONK** [AzureAD/microsoft-authentication-library-for-js#4174] opened 2021-10-20 05:57 UTC
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.1

### Description

Stack:
Front End - Angular 12
  |-- Leveraging Angular/MSAL to integrate with Azure AD for authentication

Back End
  |-- Node JS  V14.17.6
  |-- Express 4.17.1
  |-- Passport-Azure-AD V4.3.0 (passport-azure-ad is a collection of Passport Strategies to help you integrate with Azure Active
  |-- Authentication Strategy - BearerStrategy (Protects APIs and Resources)
 Directory)
       |-- Passport V0.3.2 (Passport version leveraged by Passport-Azure-AD)

Back End Project Structure (Excerpt shown for brevity)
  Root Directory
   |-- src 
     |-- routers(Sub directory that holds all modularized routes per entity in individual .js files e.g. users.js, actions.js)
     |--index.js(Application entry point)

I'm looking for a way to protect all my routes/api endpoints, rather than having to apply the passport.authenticate to each route handler within each of the route endpoints which could be "N" number of routes per modularized route .js files as expressed above. I have tried the following below to no avail.

1. Within the index.js file, i.e. the applications entry point, in which I use e.g. const users = require('./routers/users') and app.use('/api/v1/users', users) to mount my route handlers, I introduced the following app.use(passport.authenticate('oauth-bearer', { session: false })) since passport is a middleware but no joy

2. Within the modularized route handling files, I tried the following as well: router.all('*',passport.authenticate('oauth-bearer', { session: false })) based on the express documentation, router.all should apply a middleware or provided function/handler at a path for all request methods and in this case the '*' should match all paths, but still this only worked for the base path '/' and not others in the file e.g. '/relationships' 

If anyone can prescribe a way to protect all routes, it will be greatly appreciated.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2021-10-21 17:25
This is outside the scope of passport-azure-ad, and it looks like you have received an answer at https://github.com/expressjs/express/issues/4734 . Closing.

**Closed as completed by jasonnutter** 2021-10-21 17:25 UTC
Labels: question, msal-angular

**Comment by nubianMONK** [comment] 2021-10-22 02:20
@jasonnutter The issue was not resolved at express Jason, the chap did not have a solution for me.

**Comment by jasonnutter** [comment] 2021-10-22 02:36
Verify you register the Auth middleware early in the middleware chain, otherwise it may not get invoked.

**Comment by nubianMONK** [comment] 2021-10-26 17:19
@jasonnutter Yes I can verify the Auth middleware early in the middleware chain, that's not the issue, but I eventually was able to find the root cause which has to the do with the MSAL/Angular ProtectedResoureMAP feature, details below, kindly look into this:

So after many a days, seeking a solution, I finally found the culprit as to why my implementation as stated above did not work. It boil's down to the recent introduction of the wildcard '*' feature as it applies to MSAL/Angular's protectedResourceMap. Leveraging the example above, the way this is implemented from the client(Angular V12) is by setting the aforementioned protected resource map to: 'http://localhost:3001/api/v1/*' and this one will logically think well in turn protect endpoints such as

'http://localhost:3001/api/v1/users'
'http://localhost:3001/api/v1/users/relationshp'
but what I uncovered is that the Wildcard doesn't quite work as one will think, it pretty much will just match the first url above tagged (1.) as this is handled within the "users.js" router file by the router handler, base endpoint router.get('/', (req, res, next) => {...do something }); and will totally jettison the following router handler(Should match Second url above tagged (2.)), endpoint router.get('/relationships', (req, res, next) => {...do something }); which by the way is equally implemented within the "users.js" router file.

Solution that saved the day client fix(Angular V12) was to first to remove the Wildcard asterix '*' as part of the Protected Resource Map configuration and just kept it as such : 'http://localhost:3001/api/v1/' and on the server side(NodeJs) per my requirements i.e. protect all routes was to apply the following solution to the entry point of the server solution "index.js" leveraging passport as a middleware applied to the application across the board: app.use(passport.authenticate('oauth-bearer', { session: false })); this way not needing to implement same within each router handler file. Hope this helps folks out there facing similar issues.

**Comment by jasonnutter** [comment] 2021-10-27 21:32
@nubianMONK Thanks for the update. And yes, [by design](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md#protected-resource-map) if the interceptor finds multiple entries in the `protectedResourceMap` that work for a given request, it will use the first of those entries. Given that, we recommend that your entries in the `protectedResourcemap` are ordered from most specific to least specific.
