### ISSUE TITLE
Dist of msal.js & msal.min.js

### ISSUE THREAD

**Issue by Pheil** [AzureAD/microsoft-authentication-library-for-js#967] opened 2019-09-03 15:51 UTC
I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 1.01 -> 1.1.3
</code></pre>

Why does it take so long after a version release for these links to work?  As of this submission it's been 20 days and still they don't work.  This wasn't an issue before when these were included in msal-core\dist\, but that dir was deleted after 1.0.1. 

https://secure.aadcdn.microsoftonline-p.com/lib/1.1.3/js/msal.js
https://secure.aadcdn.microsoftonline-p.com/lib/1.1.3/js/msal.min.js

Is there something I'm missing how to get these files?

**Comment by DarylThayil** [comment] 2019-09-03 17:33
@pkanher617  can you update status here

**Comment by pkanher617** [comment] 2019-09-05 19:00
@Pheil There is an issue with our CDN upload process that we are trying to fix. We hope to have this version up by the end of the week. We don't anticipate any delays after this week. Thanks for your patience.

**Comment by andrewconnell** [comment] 2019-09-23 18:39
Any updates @pkanher617 ?

**Comment by jasonnutter** [comment] 2019-09-23 18:47
@andrewconnell You can find the updated urls here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/957#issuecomment-532923268

We're working on updating the README and wider messaging (e.g. blog post). Sorry about the delay!

**Comment by andrewconnell** [comment] 2019-09-23 18:51
Multiple issues in the repo mention this... quick stop-gap would be to reference #957 and close these dupes

**Comment by jasonnutter** [comment] 2019-09-23 21:26
Indeed, I'll close this. Apologies again for the delay.

**Closed by jasonnutter** 2019-09-23 21:26 UTC
Labels: question

**Comment by vzhikness** [comment] 2019-11-12 09:25
Hi! Looks like the issue is still here.

https://secure.aadcdn.microsoftonline-p.com/lib/1.1.3/js/msal.js says:

```
The specified blob does not exist.
RequestId:1f76faad-901e-00d9-643a-99e856000000
Time:2019-11-12T09:23:42.4884816Z
```

Same for https://secure.aadcdn.microsoftonline-p.com/lib/1.1.3/js/msal.min.js.

**Comment by DarylThayil** [comment] 2019-11-12 18:53
@pkanher617  @jasonnutter was this still a problem?

**Comment by jasonnutter** [comment] 2019-11-12 18:56
@vzhikness There are new URLs for our CDN builds. https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#via-latest-microsoft-cdn-version
