### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by virgo-no-shaka** [AzureAD/microsoft-authentication-library-for-js#125] opened 2017-09-10 13:02 UTC
Dear contributors,

I spent a couple of days trying to make it work but found a fundamental issue that will prevent any attempt to get it run correctly.

In fact, the way the popup login process is handled can't but lead to a dead end. First, a timer has been set to monitor the current popup url/hash which is far from reliable. Second, browsers prevent any attempt to access location properties of other window than the inner one. **MSAL can't work.**

I propose another implementation based on how Facebook manage popup login.

Here's a simple *working* library :
```
/*-- Let's call this library mslv-js-sdk-web.js --*/
var MS = (function () 
{
	var self = { };

	var popupWidth = 483;
	var popupHeight = 600;

	var genNonce = function ()
	{
		const result = [];

		const charset = '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._~';

		window.crypto.getRandomValues(new Uint8Array(32)).forEach(c => result.push(charset[c % charset.length]));

		return result.join('');
	};

	var deserialize = function (query) 
	{
		var match;

		var pl = /\+/g;

		var search = /([^&=]+)=([^&]*)/g;

		var decode = function (s) 
		{ 
			return decodeURIComponent(s.replace(pl, " "));
		};

		var obj = { };

		match = search.exec(query);

		while (match) 
		{
			obj[decode(match[1])] = decode(match[2]);

			match = search.exec(query);
		}

		return obj;
	};

	var parseHash = function (hash)
	{
		var h = hash;

		if (h.indexOf("#/") > -1) 
		{
			h = h.substring(h.indexOf("#/") + 2);
		}
		else if (h.indexOf("#") > -1) 
		{
			h = h.substring(1);
		}

		return deserialize(h);
	};

	var openPopup = function (urlNavigate, title, width, height)
	{
		try 
		{
			var top = window.screenTop ? window.screenTop : window.screenY;
			var left = window.screenLeft ? window.screenLeft : window.screenX;

			var w = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
			var h = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;

			var t = ((h / 2) - (height / 2)) + top;
			var l = ((w / 2) - (width / 2)) + left;

			var popupWindow = window.open(urlNavigate, title, 'width=' + width + ', height=' + height + ', top=' + t + ', left=' + l);

			if (popupWindow.focus) 
			{
				popupWindow.focus();
			}

			return popupWindow;
        }
        catch (e) 
		{
            return null;
        }
	};

	self.init = function (params)
	{
		if (params && params['clientId'])
		{
			self.clientId = params['clientId'];
		}

		if (window.opener != null)
		{
			opener.location.hash = window.location.hash;

			opener.msAsyncInit();

			window.close();
		}

		if (window.location.hash)
		{
			var h = parseHash(window.location.hash);

			if (window.localStorage.getItem('ms_auth') && h['id_token'])
			{
				window.localStorage.setItem('ms_token', h['id_token']);

				window.localStorage.removeItem('ms_auth');
			}

			window.location.href = window.location.pathname;
		}
	};

	self.loginPopup = function () 
	{
		window.localStorage.setItem('ms_auth', 'true');

		var url = 'https://login.microsoft.com/common/oauth2/v2.0/authorize';

		url += '?' + 'client_id=' + self.clientId;

		url += '&' + 'scope=' + 'openid+profile';

		url += '&' + 'response_type=' + 'id_token';
		url += '&' + 'response_mode=' + 'fragment';

		url += '&' + 'nonce=' + genNonce();

		openPopup(url, 'Log-in with your Microsoft account', popupWidth, popupHeight);
	};

	return self;
}());

window.msAsyncInit();
/*-- End of mslv-js-sdk-web.js --*/
```
In body section of your web page (html or aspx) :
```
	<script>
	//<![CDATA[
		window.msAsyncInit = function ()
		{
			MS.init
			({
				clientId: '(your client id)'
			});
		};

		(function (d, s, id)
		{
			var js, mjs = d.getElementsByTagName(s)[0];

			if (d.getElementById(id)) return;

			js = d.createElement(s); js.id = id;

			js.src = "/path-to/mslv-js-sdk-web.js";

			mjs.parentNode.insertBefore(js, mjs);
		}
		(document, 'script', 'microsoft-jssdk'));
	//]]>
	</script>
```
Finally, you can put any button, div, img that calls this function to open the login popup :
```
function onClickLoginPopup()
{
	MS.loginPopup();
}
```
Hope this helps

**Comment by rohitnarula7176** [comment] 2017-09-10 20:13
@virgo-no-shaka The code you see in the library is by design. When you click login, it opens a popUp window and sets it URL to login.microsoftonline.com which lies in a different domain than your app. We then use the polling mechanism to monitor its URL in a try catch to avoid cross domain URL check error. After you enter your credentials, AAD redirects the popUp URL back to your redirectURI which lies in the same domain with the token served in the URL fragment. At that time we are able to grab the token from the URL without a cross domain URL error and process the token. This is the only way to enable login using a popUp window and the library works using this approach without any issues. Please refer to the samples in the repo under The dev apps folder to see it in action.

**Comment by navyasric** [comment] 2017-09-11 20:19
@virgo-no-shaka Thank you for your feedback. Is the issue resolved for you? If not, can you elaborate on your scenario? Can you provide the code snippet of how you tried to use the MSAL library and what your experience was to make you feel that MSAL can't work for your case?

**Comment by rohitnarula7176** [comment] 2017-09-11 22:42
@virgo-no-shaka Closing this issue. Please refer to the samples for directions on how to use the popup based login.

**Closed by rohitnarula7176** 2017-09-11 22:42 UTC
