### ISSUE TITLE
Can't get acquireTokenSilent to work

### ISSUE THREAD

**Issue by Ideline** [AzureAD/microsoft-authentication-library-for-js#339] opened 2018-07-04 08:22 UTC
I'm having problems to get acquireTokenSilent to work. The following code with acquireTokenPopup works fine but I would like to be able to fetch a token without the user having to manually approve every time.

    state.userAgentApplication = new Msal.UserAgentApplication(state.applicationConfig.clientID, null,{cacheLocation: 'localStorage'});
    state.userAgentApplication.acquireTokenPopup(state.applicationConfig.graphScopes).then(function (token) {

        commit("setGraphToken", token);

      }, function (error) {
            console.log(error);
      });

I have tried the sample code you provide but with no luck. I can get the loginPopup to work but then it runs acquireTokenSilent with no errors and no success.

I also have a second issue with the working code. Like I said it works fine but only for my add-in when I'm using the web-version of Outlook. When I run the desktop application there is no popUp dialog at all. What am I missing here?

**Comment by nehaagrawal** [comment] 2018-07-05 18:10
@Ideline For the first issue, are you calling the acquireTokenSilent()  after loginPopup() like this ?

userAgentApplication.loginPopup(applicationConfig.graphScopes).then(function (idToken) {
                //Login Success
                userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
                    //AcquireToken Success
                    updateUI();
                }, function (error) {
                    //AcquireToken Failure, send an interactive request.
                    userAgentApplication.acquireTokenPopup(applicationConfig.graphScopes).then(function (accessToken) {
                        updateUI();
                    }, function (error) {
                        console.log(error);
                    });
                })
            }, function (error) {
                console.log(error);
            });

 The samples that we have on github, works fine. Are you running the same sample and it doesn't work? Can you share your code?

**Comment by Ideline** [comment] 2018-07-09 07:14
Hi.

I have tried this exact code with no success:

getAccessToken({ state, commit, dispatch }) {

      state.userAgentApplication = new Msal.UserAgentApplication(state.applicationConfig.clientID, null, { cacheLocation: 'localStorage' });

      state.userAgentApplication.loginPopup(state.applicationConfig.graphScopes).then(function (idToken) {

        state.userAgentApplication.acquireTokenSilent(state.applicationConfig.graphScopes).then(function (accessToken) {
          updateUI();
          commit("setGraphToken", accessToken);
        }, function (error) {

          state.userAgentApplication.acquireTokenPopup(state.applicationConfig.graphScopes).then(function (accessToken) {
            updateUI();
            commit("setGraphToken", accessToken);
          }, function (error) {
            console.log(error);
          });
        })
      }, function (error) {
        console.log(error);
      });
    },

I get the login popup and then it does the aquireTokenSilent but it doesn't get to

commit("setGraphToken", accessToken); 

and it doesn't try to aquireTokenPopup. I'm not getting any errors either.

My add-in is for Outlook and so when the user starts it, they have already logged in to their Outlook account. That's why I would like to avoid loginPopup aswell.

I also had trouble getting the aquireTokenPopup to work at first. Once I have done a window.Office.initialize the aquireTokenPopup doesn't work. So currently I'm acquiring the token before the Office initialization.

**Comment by jkga** [comment] 2018-07-09 08:30
Try using `this` for inner scope  https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/278

```javascript
state.userAgentApplication.loginPopup(state.applicationConfig.graphScopes).then(function (idToken) {
   // not state.userAgentApplication
   this.acquireTokenSilent(state.applicationConfig.graphScopes).then(...)
   this.acquireTokenPopup(state.applicationConfig.graphScopes).then(...)
})

**Comment by Ideline** [comment] 2018-07-09 12:02
I have tried this now but "this" is undefined while state.userAgentApplication is not undefined. 
To clarify ... if I don't use acquireTokenSilent but instead only use acquireTokenPopup the authentication works and I will receive the graphToken when using the web Outlook. My problem is that it doesn't work for the desktop Outlook and acquireTokenSilent doesn't work at all.

It seems as the promise returned by acquireTokenSilent never resolves or rejects?

**Comment by Tekki** [comment] 2018-07-09 15:17
Take a look at #341 
But I think this is a problem with the sample application and not with the library itself. I use it in a Vue.js app and userAgentApplication.acquireTokenSilent always resolves.

**Comment by Ideline** [comment] 2018-07-12 11:41
I still haven't found a solution to my problem. My add-in is for Outlook and at the moment I can not get a graph token while using the desktop client since neither the silent or popup function works, and I can only get one while using the popup in the web client. If anyone has another suggestion for what I can look into I would really appreciate it.

**Comment by nehaagrawal** [comment] 2018-07-13 18:22
@Ideline Can you please share your repo or sampel code where we can reproduce this issue? Noone has ever reported this issue and we confirmed that sample works fine. There is something else in your code that is causing this issue.

**Comment by vladkosarev** [comment] 2018-07-20 15:15
I actually have exact same issue. That call just never comes back with either success or error. If I'm already logged in and refresh the page then it works, if I just logged in and get redirected back and try to get the token it doesn't do anything. It's really odd. 

Since this is in Vue I'm wondering if Vue is doing something that makes acquireTokenSilent never come back.

**Comment by vladkosarev** [comment] 2018-07-20 15:23
Here's what I'm thinking -
new Msal.UserAgentApplication has some async bits that might not be done by the time acquireTokenSilent is called or something along those lines. That's why in some situations the object exists but doesn't work properly.

**Comment by Tekki** [comment] 2018-07-22 15:00
@vladkosarev I've just published my project at https://github.com/Tekki/ivoc4, take a look at it. Maybe the difference is that I don't get the token immediately, but first I log in, then load a new component and from here call acquireTokenSilent.

**Comment by Ideline** [comment] 2018-07-24 07:06
Thank you for chairing. 
Looking at your code I think it's kind of what I do. I will keep trying. 

Yesterday I tested the code that I have which is working in Chrome and Firefox. The one without the acquireTokenSilent and just the acquireTokenPopup. It's not working in Edge or Explorer. 

In Explorer I get the log in popup but it doesn't close after signing in and it never resolves or rejects. 

And in Edge the popup is just an empty window. I get the error message "Permission denied".

**Comment by nehaagrawal** [comment] 2018-08-02 23:11
@Ideline  IE/Edge support is an open issue curently. Glad to know that it worked on chrome and firefox. We already have an issue for IE/Edge for tracking purpose. I am closing this issue for now.

**Closed by nehaagrawal** 2018-08-02 23:11 UTC
Labels: needs info
