### ISSUE TITLE
msal acquireTokenSilent produces Cookie length should be less than or equal to 4096 characters

### ISSUE THREAD

**Issue by ritmos** [AzureAD/microsoft-authentication-library-for-js#534] opened 2019-01-14 17:17 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
<pre><code>
Library version: 0.2.4

## Current behavior
After login with loginRedirect
const msal = UserAgentApplication(...)
msal.loginRedirect(scopes, extraParameters);
// <page redirects back here>

I try to obtain a token with

const msal = UserAgentApplication(...)
msal.acquireTokenSilent(scopes).then(
token => console.log(token),
error => console.error(error)
);

And I get a warning in console saying:
Set-Cookie header is ignored in response from url: https://log.... Cookie length should be less than or equal to 4096 characters.

And then, after 6 seconds (default timeout set), the error printed by acquireTokenSilent promise handler: 
Token renewal operation failed due to timeout|Token Renewal Failed

## Expected behavior
The token requested should be returned

## Minimal reproduction of the problem with instructions
- Instantiate UserAgentApplication
- Log in with login instance.loginRedirect
- After good login and redirection, instantiate again UserAgentApplication
- use instance.acquireTokenSilent to get a token

I will try to build a usecase repo for that.

Already tried cleaning all cookies, using private browser mode.
With Safari, the error is almost the same with the exception that the cookie warning is not notified (only the timeout)

</code></pre>

**Comment by navyasric** [comment] 2019-01-15 00:20
@ritmos What is the reason for instantiating the UserAgentApplication twice? In MSAL.js the UserAgentApplication object represents a single authentication context and should be instantiated once.

**Comment by jkga** [comment] 2019-01-15 00:33
@navyasric I also encountered this error. The reason why he needs to initialize it twice is because the popup doesn't close automatically after authentication. Setting a longer timeout also doesn't help.

see #174

**Comment by russellr86** [comment] 2019-02-07 04:21
@navyasric, I have this error as well.  In my case it is being instantiated twice seemingly by the order of operations resulting from `acquireTokenSilent`

The order in my network tab in chrome debugger goes something like this:

1. GET localhost - 200
2. GET localhost resources (js, css) - 200
3. Javascript is executed, singleton of MSAL is instantiated.
4. `acquireTokenSilent` called
5. GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=token&scope=offline_access%20https%3A%2F%2Fgraph.microsoft.com%2FUser.ReadBasic.All%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read%20https%3A%2F%2Fgraph.microsoft.com%2FCalendars.Read%20https%3A%2F%2Fgraph.microsoft.com%2FCalendars.ReadWrite%20https%3A%2F%2Fgraph.microsoft.com%2FCalendars.ReadWrite.Shared%20https%3A%2F%2Fgraph.microsoft.com%2FCalendars.Read.Shared%20openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F - **302**
6. GET localhost - 200
7. GET localhost resources (js, css) - 200
8. Javascript is executed, singleton of MSAL is instantiated in new context.

console reads: `Set-Cookie header is ignored in response from url: [common url]. Cookie length should be less than or equal to 4096 characters.`

Chrome: 71.0.3578.98
msal: 0.2.4

**Comment by SamNutkins** [comment] 2019-04-10 22:12
I'm having the same issue, although it seems to happen when calling `loginRedirect`.  The flow works fine on Firefox, but fails on Chrome with the same 'Set-Cookie' warning being logged.

Does anyone know a work-around? Is there a plan for this to be fixed?

**Comment by DarylThayil** [comment] 2019-04-11 18:09
@SamNutkins  can you repro this consistently?
If so can you capture through Fiddler logs for us?

**Comment by SamNutkins** [comment] 2019-04-12 16:06
@DarylThayil 

I've actually been able to work around the issue for now.  

I was seeing redirect loop the behavior described in #498.  As several people suggested there, setting the `navigateToLoginRequestUrl` config property to `false` solved my problem and the redirect flow is working.

It's worth noting that even after that change, I still see the 'Set-Cookie' warning in the logs.  I'm not sure if that is related or having any adverse affects at all.

**Comment by sameerag** [comment] 2019-04-30 23:49
@sameerag We are following up with the service team regarding the cookie length, Will update once we have a traction on this.

**Comment by aashiman** [comment] 2019-05-03 21:50
@SamNutkins  does the warning in the logs impact end user sign-in? It might be a false positive from chrome dev tools, likely complaining about total cookie size, for which Chrome doesn’t actually have a limit: http://browsercookielimits.squawky.net/

**Comment by derekparsons718** [comment] 2019-06-13 00:31
Any news on this? I'm having the same issue intermittently.

**Comment by joshfriend** [comment] 2019-06-24 17:13
related: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/864

**Comment by DarylThayil** [comment] 2019-06-24 18:08
Quick question, is this showing up as a warning only or are you blocked from getting tokens?

**Comment by derekparsons718** [comment] 2019-06-24 18:59
@DarylThayil Just as ritmos explains, the cookie warning appears first and then a few seconds later this error is thrown: "Token renewal operation failed due to timeout|Token Renewal Failed". No token is returned.

**Comment by geitir** [comment] 2019-06-28 17:38
I am also getting this warning in Chrome. However I do not seem to have any adverse effects from it at this time

**Comment by sameerag** [comment] 2019-06-29 06:30
@geitir @SamNutkins Yes, we are hearing that it is a false positive from chrome from some quarters. Nevertheless it helps to have all the network and msal logs in this context to understand the exact error.

@ritmos @derekparsons718 Can you guys upgrade to msal 1.0.x and let us know if the timeout is still seen? Also as @DarylThayil already asked above, it helps if a fiddler log is shared

**Comment by derekparsons718** [comment] 2019-07-03 23:05
@sameerag I was having the problem in the angularjs msal library. I switched to using the normal js msal v1.0.2 and I am no longer having the problem. (I do still see the cookie warning though.) I guess the bug is specific to the angularjs library.

**Comment by CodeEpiphany** [comment] 2019-07-11 21:01
Experiencing this bug as of today in an Angular project. Kills authentication. Did not have it a few days ago.

**Comment by ritmos** [comment] 2019-08-21 19:32
I'm using 1.1.3 and I'm not experiencing this bug anymore

**Comment by DarylThayil** [comment] 2019-08-22 19:49
@ritmos  thanks for the update! 
Can anyone else confirm if this is fixed in 1.1.3 for them?

**Comment by favetelinguis** [comment] 2019-09-04 12:02
Im using [react-aad](https://github.com/syncweek-react-aad/react-aad/blob/master/package.json) but they depend on 1.1.3 and im getting this exact problem.

**Comment by sameerag** [comment] 2019-10-02 22:22
@favetelinguis Can you specify if you are seeing any other error that is blocking the authentication? The `cookie length` issue is almost always a false positive from chrome dev tools in most cases reported to us and we suspect something else is going on.

Server team also confirmed that they have chunking logic that limits their cookies from ever exceeding this limit.

**Closed by sameerag** 2019-10-02 22:22 UTC
Labels: bug, core, protocol
