### ISSUE TITLE
Token renewal operation failed due to timeout: null

### ISSUE THREAD

**Issue by hkamel** [AzureAD/microsoft-authentication-library-for-js#59] opened 2017-05-21 16:34 UTC
Hello team,

I'm getting the above error whenever I try to use acquireTokenSilent().

any guidance?

**Comment by jmprieur** [comment] 2017-05-29 12:57
Hi @hkamel, were you able to check if this was due to network latencies as discussed? Closing this for now. Feel free to re-open.

**Closed by jmprieur** 2017-05-29 12:57 UTC

**Comment by bampakoa** [comment] 2017-06-01 10:12
@jmprieur I get the same error with the sample provided [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/devApps/VanillaJSTestApp-b2c). Below are my steps to reproduce:

1. Click the login button
2. The popup shows up and I sign in with my credentials
3. The popup closes and I notice a delay
4. The popup shows again and I sign again also.
5. I get the following error:
![image](https://cloud.githubusercontent.com/assets/7170892/26675187/a0a6a7a2-46cb-11e7-8b8b-a755d38c3364.png)

This is the error that I get after the 1st login attempt:
![image](https://cloud.githubusercontent.com/assets/7170892/26675251/e3cfee8a-46cb-11e7-991e-f7cac8a07db2.png)

**Comment by bampakoa** [comment] 2017-06-02 10:30
Just to let you know, after some digging, we found out that it was a scope problem. `b2cScopes` was not set correctly in `applicationConfig`. Specifically, we set it to the `clientID` value and it worked.

**Comment by tmarkovski** [comment] 2019-01-19 14:38
> Just to let you know, after some digging, we found out that it was a scope problem. `b2cScopes` was not set correctly in `applicationConfig`. Specifically, we set it to the `clientID` value and it worked.

But "b2cScopes" shouldn't be set to clientID. Nowhere in the documentation is this pointed. I ran into the same issue and oddly it worked when I set the b2cScopes to clientId.
The problem only happened when I used Facebook authentication and not username/password.
