### ISSUE TITLE
Sign In occurs in Pop-up Dialogue

### ISSUE THREAD

**Issue by markholst** [AzureAD/microsoft-authentication-library-for-js#3126] opened 2021-03-03 05:08 UTC
## Library
@azure/msal-browser@2.11.2

## Framework
React 16

## Description
It has been observed that a situation can be created where a User's Sign In session opens in the Sign In pop-up dialogue rather than redirected back to main window in a desktop web browser, when that desktop web browser is not in the immediate background of the dialogue.

## Error Message
No error message.

## MSAL Configuration
        const configuration: Msal.Configuration = {
            auth: {
                clientId: clientId,
                authority: "https://login.microsoftonline.com/" + tenantId,
                redirectUri: redirectUri,
                postLogoutRedirectUri: postLogoutRedirectUri,
                navigateToLoginRequestUrl: true,
            },
            cache: {
                cacheLocation: "localStorage",
                storeAuthStateInCookie: false,
            },
        };

Using the standard Azure B2C Sign-In flow.

## Reproduction steps
1. Navigate to the application landing page in a desktop web browser (use full screen window size).
2. Click the Sign In option.
3. Confirm a Sign In dialogue appears in the foreground.
4. Click any desktop app to put that in the foreground (i.e. launch and view Windows Paint).
5. Use the Windows Task Bar to find the Sign In dialogue window and select that to appear in the foreground.
6. Confirm that the desktop app (i.e. Windows Paint) is in the immediate background behind the Sign In dialogue, and that the application landing page in the main window of the desktop web browser is not visibile.
7. Sign In to the using a valid User Account (this can be for a first OR non-first login attempt).
8. When the Sign In process is successful, confirm that the User Sign In session appears to open in the Sign In dialogue rather than redirected back to main window in desktop web browser (it should be note the initially the application landing page is visible, but if the user clicks the Sign In option, then the Sign In session opens in the dialogue) (it should be noted that the Sign In dialogue window can be maximised and the user's login session appears as expected).

We're using the standard Azure B2C Sign-In flow.

## Expected behavior
The pop-up should close, and the sign-in 

## Identity Provider
Azure B2C Basic Policy

## Browsers/Environment
Chrome 88

## Regression
This is a new implementation.

## Security
No

## Source
Customer request

**Comment by pkanher617** [comment] 2021-03-03 16:46
@markholst I couldn't reproduce this behavior in our samples. I'm not sure I fully understand the issue here. Do you have a video that you can provide showing the errant behavior? As well as some logs from the browser?

**Comment by markholst** [comment] 2021-03-04 07:51
Thanks @pkanher617 for checking in quickly on this

I provided the instructions from our tester, however I have managed to reproduce this one quite easily.  I think the key is to minimise the browser window and continue working in the popup dialog.

This shows the initial page of the application, signed-out.
![image](https://user-images.githubusercontent.com/56993727/109927842-c0ea0900-7cff-11eb-9659-4d54872fc5f2.png)

I have now clicked sign-in to show the sign-in window.
![image](https://user-images.githubusercontent.com/56993727/109928013-f262d480-7cff-11eb-8757-f1adb93e2535.png)

I have now minimised the main browser window, but left the pop-up visible.
![image](https://user-images.githubusercontent.com/56993727/109928177-263dfa00-7d00-11eb-913d-2f269e43033b.png)

I then let things sit for about 30 seconds...

I have now completed sign-in and I have seen that the sign-in occurs within the pop-up.  Normally it would close the pop-up and I would see this content back in the main application window.
![image](https://user-images.githubusercontent.com/56993727/109928343-51284e00-7d00-11eb-873c-b18fa9ca3022.png)

Looking at F12 on the popup, it's only logging as if it's a new instance of the application... it has clearly done a redirect in the pop-up.
![image](https://user-images.githubusercontent.com/56993727/109928960-f8a58080-7d00-11eb-9794-c9adf2d95bfb.png)

Bringing the main application window forward, I can see that it has failed to log any new messages to the console.
![image](https://user-images.githubusercontent.com/56993727/109928501-7ae17500-7d00-11eb-99aa-3f557d12379b.png)

This is everything sitting together at the end of the process.
![image](https://user-images.githubusercontent.com/56993727/109929256-399d9500-7d01-11eb-84c0-604e045e96e5.png)

**Comment by markholst** [comment] 2021-03-12 02:16
Hi Thomas,

The issue occurs consistently in Edge, Firefox, Opera and Chrome.

Chrome 89
Edge 89
Opera 74
Firefox 84

Confirmed using @azure/msal-browser 2.12.0

It's almost like the browsers 'go to sleep' when minimised.

I can certainly have a try a confirming through a sample, it might take a few days to find the time.  I'll let you know as soon as I can.

Cheers,
Mark

**Comment by markholst** [comment] 2021-03-22 09:25
This one is interesting.

I've taken this sample - https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0 and I definitely cannot reproduce the problem.

This was tested using both the sample B2C configuration and my B2C configuration.

Watching it perform the login, it looks the like sequence of events is:
1. The pop-up is shown,
2. I sign in,
3. The content in the popup is redirected _and I can briefly see the sample app load in here_,
4. The pop-up closes.

Given I have a fairly chunky app, which makes service calls immediately on loading, is it possible for me to detect that the app is loading within the context of the pop-up?  I can ensure nothing is rendered or run.

**Comment by markholst** [comment] 2021-03-22 11:11
Yes, I believe my hunch is correct.

I have just modified my App.tsx and put in a statement:
`if (window.innerWidth === 483) return <></>;`

With this in place, I can no longer reproduce the issue.

Of course, looking for a better solution here.  Is there anything that I can reliably use to determine if the app is initialising in the pop-up?

**Comment by tnorling** [comment] 2021-03-22 17:34
@markholst What we typically recommend is that you set your `redirectUri` to a blank page when using the popup or silent flows. Can you try that?

**Comment by markholst** [comment] 2021-03-23 00:24
Thankyou Thomas, I can confirm that using an alternative redirectUri does the trick.

In my App.tsx I can simply assert on the route early and not render any components.  It's a little indirect, but effective.  I am no longer able to reproduce the issue described in this ticket.  You are free to close this ticket.

```
const isLoginRedirect = window.location.pathname === "/auth-redirect";
if (isLoginRedirect) return <></>;
```

I am also finding silent sign-on is much quicker and more reliable, looking at the logs I believe it was getting into an auth loop.

Can you please confirm where the use of a blank page is documented?  I have been over the documentation at various points, it is clear I have missed this.  I would like to check if there's any other tips I might have missed in this content.

**Comment by tnorling** [comment] 2021-03-23 16:59
@markholst To be quite honest, I'm not sure it is explicitly documented anywhere for msal-browser. This is something we should add, I'll make a note to add this soon. Generally our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md) is a good place to find tips as well as our [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser/docs)

Closing as the original issue was solved but please feel free to open a new issue if you have additional questions. Thanks!

**Closed by tnorling** 2021-03-23 16:59 UTC
Labels: bug-unconfirmed, msal-browser, question
