### ISSUE TITLE
Daylight savings system clock adjustment on client machine causes MSAL.js to return cached expired token instead of acquiring refreshed token

### ISSUE THREAD

**Issue by morr0350** [AzureAD/microsoft-authentication-library-for-js#2608] opened 2020-11-17 15:01 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.4.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 9 / Electron 

## Description
Daylight Savings Time system clock adjustment on client machine caused acquireTokenSilent to believe the browser's cached token was valid, when in fact, it had expired

## Error Message
No error message

## Security
- [X] Is this issue security related? No, the token does eventually get validated against the correctly adjusted time when it hits the API

## Regression
- [X] Did this behavior work before?  Not believed to have worked before
Version:

## MSAL Configuration
cache: {
                cacheLocation: 'sessionStorage'
}

## Reproduction steps
Scenario 1:
1) Acquire and cache first-time token from API
2) Leave session idle for duration of time exceeding the expiration limit of token and including a fall-back daylight savings period system time adjustment
3) Reenter browser session and attempt to call actions that make authenticated requests to the API
4) Browser is unaware token has expired and does not know to acquire a new one, all API requests fail

Scenario 2:
1) Acquire and cache first-time token from API
2) Leave session idle for duration of time exceeding the expiration limit of token and manually adjust system clock to a time earlier than the current time
3) Reenter browser session and attempt to call actions that make authenticated requests to the API
4) Browser is unaware token has expired and does not know to acquire a new one, all API requests fail

## Expected behavior
acquireTokenSilent should be aware of changes to the client machine system clock so that tokens are expired after the correct duration of time

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment] 2020-11-24 22:57
@morr0350 For scenario 1, I'll see if I can reproduce, although I find it surprising given we do token expiration calculation with unix timestamps.

For scenario 2, I'm not sure there's anything we can do in the library if the machine has a manually adjusted clock.

Generally speaking, you can force MSAL to skip the cache by setting `forceRefresh` to `true` when calling `acquireTokenSilent`. This would allow your app to reinvoke `acquireTokenSilent` and skip the cache if the retrieved token has already expired.

**Comment by jasonnutter** [comment] 2020-12-11 18:20
Closing, as I've been unable to reproduce this issue. Our timing logic uses [getTime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime), so it doesn't make sense as that is DST agnostic.

**Closed by jasonnutter** 2020-12-11 18:20 UTC
Labels: bug-unconfirmed, msal-browser, msal-common, question
