### ISSUE TITLE
useIsAuthenticated is always initially false

### ISSUE THREAD

**Issue by jamesots** [AzureAD/microsoft-authentication-library-for-js#2846] opened 2021-01-08 18:16 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React 16.14
- [ ] Other

## Description

When I use the `useIsAuthenticated` hook, on the first call the result is always false, even if I am actually logged in. This is because the `useEffect` call inside `useIsAuthenticated` isn't called until after the initial state has been returned. The initial state should probably be set to `isAuthenticated(allAccounts, account, matchAccount)` instead of `false`.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment] 2021-01-08 18:21
@jamesots This was done to addressed issues in server environments, see #2646. @tnorling for more context.

**Comment by tnorling** [comment] 2021-01-08 19:43
Yeah that's right. @jamesots Is this breaking anything for you? If so, I would suggest not having your initial render be dependent on msal. Alternatively, you could write your own hook with the changes you need instead of using the built in one.

**Comment by jamesots** [comment] 2021-01-08 19:53
I'm having problems with my SPA redirecting me to the ms login server when I enter an authenticated route, even if I'm already logged in. There may be another way of structuring my site to stop this happening. I'll put a simple example together next week. At the moment I have written my own hook to make this work, but it seems a bit of a shame to be switching to use msal-react and then to discover I need to rewrite parts of it :) (Incidentally, is there a more up-to-date roadmap available for this library? The current roadmap still expects a private preview in November 2020.)

**Comment by tnorling** [comment] 2021-01-08 20:03
@jamesots I would suggest using the `MsalAuthentication` component or `useMsalAuthentication` hook to protect routes. These will automatically invoke login if a user is unauthenticated and should not be adversely affected by `useIsAuthenticated` defaulting to false. Can you give that a shot and see if that resolves your use case?

We are expecting to go to Public Preview / beta sometime this month. There's a few administrative items that need to be completed to get there but from a code perspective there will not be any major changes. We'll make sure to update the roadmap, thanks for the callout.

**Comment by jamesots** [comment] 2021-01-08 21:21
I created an app with create-react-app, added @azure/msal-browser, @azure/msal-react and @reach/router, and updated App.js as below. I set up the CLIENT_ID, SIGN_IN_POLICY and AUTHORITY values in index.js. When I click on 'Go to secure page', it goes to the secure page, then back to the public page, then back to the secure page.

```jsx
import React from 'react';
import * as msal from '@azure/msal-browser';
import { MsalAuthenticationTemplate, MsalProvider } from '@azure/msal-react';
import { Link, Router } from '@reach/router';

const Public = () => (
  <div>
    <h1>Public page</h1>
    <Link to="/secure">Go to secure page</Link>
  </div>
)

const Secure = () => (
  <MsalAuthenticationTemplate interactionType={msal.InteractionType.Redirect}>
    <h1>Secure page</h1>
    <Link to="/">Go to public page</Link>
  </MsalAuthenticationTemplate>
)


export const App = () => {
  const msalInstance = new msal.PublicClientApplication({
    auth: {
      clientId: window.CLIENT_ID,
      authority: window.AUTHORITY + '/' + window.SIGN_IN_POLICY,
      knownAuthorities: [window.AUTHORITY],
      navigateToLoginRequestUrl: true,
      redirectUri: 'http://localhost:8000/',
      validateAuthority: false,
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false,
    },
    system: {},
  });

  return (
    <MsalProvider instance={msalInstance}>
      <Router>
        <Public path="/"/>
        <Secure path="/secure"/>
      </Router>
    </MsalProvider>
  );
}
```

**Comment by tnorling** [comment] 2021-01-08 21:47
@jamesots 

> When I click on 'Go to secure page', it goes to the secure page, then back to the public page, then back to the secure page.

Does it loop or does it stay on the secure page after this? If it's the latter, does it do this everytime you go to /secure or only the first time? Intended design is: when you go to the secure page, if you are not yet authenticated it will call login redirect which will send you back to the public page (what you've set as your redirectUri) and then back to the secure page (because that's where the login call originated).

I'll try to reproduce this on Monday but in the meantime you can check out the [sample using react-router](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2813) currently in PR which is very similar to the example you shared.

**Comment by jamesots** [comment] 2021-01-11 08:35
It doesn't loop. It does do the little redirect dance every time you try to go to /secure, however.

**Comment by tnorling** [comment] 2021-01-11 19:42
@jamesots I just spun up an example using the same versions of `msal-browser`, `msal-react`, `react`, and `@reach/router` with the same configuration options and setup you shared above and could not reproduce this behavior. Could you put together a minimal sample or edit [this one](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) to reproduce this so that I can take a look to see what's going on here? 

Alternatively if you could debug on your end and determine why `MsalAuthenticationTemplate` seems to be invoking `loginRedirect` on each page load. Is local storage being cleared somehow in between? This would not be related to the default value of `useIsAuthenticated` since that value should be overwritten with the actual state before login is called.

**Comment by jamesots** [comment] 2021-01-12 09:15
I created a minimal test app: https://github.com/jamesots/test-msal-react

I've tried it on my Windows and Linux computers, in Chrome and new Edge, and it behaves the same in all situations — with the extra redirect every time to go to the secure page.

I also edited the sample you linked to, and made the changes below. The sample was reloading the entire page every time you navigate, so I've changed it so that the material-ui Link and Button components are using the react-router's Link, so that it navigates by re-rendering instead of reloading, and it now shows the same issue. It seems to be able to detect that it's logged in when the page loads from scratch, but not when you use react-router to load it.

```patch
diff --git a/src/pages/Home.jsx b/src/pages/Home.jsx
index 612200a..3b2f692 100644
--- a/src/pages/Home.jsx
+++ b/src/pages/Home.jsx
@@ -1,12 +1,13 @@
 import { AuthenticatedTemplate, UnauthenticatedTemplate } from "@azure/msal-react";
 import Button from "@material-ui/core/Button";
 import Typography from "@material-ui/core/Typography";
+import { Link as RouterLink } from "react-router-dom";
 
 export function Home() {
   return (
       <>
           <AuthenticatedTemplate>
-              <Button variant="contained" color="primary" href="/profile">Request Profile Information</Button>
+              <Button component={RouterLink} variant="contained" color="primary" to="/profile">Request Profile Information</Button>
           </AuthenticatedTemplate>
 
           <UnauthenticatedTemplate>
diff --git a/src/pages/Profile.jsx b/src/pages/Profile.jsx
index 395d155..35a8d0a 100644
--- a/src/pages/Profile.jsx
+++ b/src/pages/Profile.jsx
@@ -44,7 +44,7 @@ export function Profile() {
 
     return (
         <MsalAuthenticationTemplate 
-            interactionType={InteractionType.Popup} 
+            interactionType={InteractionType.Redirect}
             authenticationRequest={authRequest} 
             errorComponent={ErrorComponent} 
             loadingComponent={Loading}
diff --git a/src/ui-components/NavBar.jsx b/src/ui-components/NavBar.jsx
index 7ff87a3..a22c645 100644
--- a/src/ui-components/NavBar.jsx
+++ b/src/ui-components/NavBar.jsx
@@ -5,6 +5,7 @@ import Typography from "@material-ui/core/Typography";
 import WelcomeName from "./WelcomeName";
 import SignInSignOutButton from "./SignInSignOutButton";
 import useStyles from "../styles/useStyles";
+import { Link as RouterLink } from "react-router-dom";
 
 const NavBar = () => {
     const classes = useStyles();
@@ -14,7 +15,7 @@ const NavBar = () => {
             <AppBar position="static">
             <Toolbar>
                 <Typography className={classes.title}>
-                    <Link href="/" color="inherit" variant="h6">MS Identity Platform</Link>
+                    <Link component={RouterLink} to="/" color="inherit" variant="h6">MS Identity Platform</Link>
                 </Typography>
                 <WelcomeName />
                 <SignInSignOutButton />

```

**Comment by tnorling** [comment] 2021-01-12 20:01
@jamesots Thanks for this. With your sample I was able to reproduce this and I now understand what's happening here. We do want this library to work out of the box with routers, so I'm marking this as a bug and will link a PR when I have one ready. Thanks for bringing this to our attention and for taking the time to provide a reproduction. Much appreciated!

**Closed** 2021-01-15 21:35 UTC
Labels: bug, msal-react
