### ISSUE TITLE
Infinite reload loop when refresh token expires

### ISSUE THREAD

**Issue by jakobgn** [AzureAD/microsoft-authentication-library-for-js#3771] opened 2021-06-18 13:07 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

2

### Description

When our users access our page and there is an expired refresh token in the cache,  _acquireTokenSilent_ fails with the following error object:
{
    "errorCode": "monitor_window_timeout",
    "errorMessage": "Token acquisition in iframe failed due to timeout.",
    "subError": "",
    "name": "BrowserAuthError"
}
By following examples we do a acquireTokenRedirect with the required API scopes as input. 
This redirects to B2C, which by using a cookie redirects back and the token endpoints return 400, going back to the original error in an infinite loop. 
Clearing the browser cache (localstorage) fixes the issue. So I am looking for the right approach to solve this, i.e. by clearing the cache before doing the acquireTokenRedirect  call.  

 

### Error Message

400 Bad request

Token acquisition in iframe failed due to timeout.

### MSAL Configuration

```javascript
const authority = `https://${b2cSettings.tenant}.b2clogin.com/${b2cSettings.domain}/${b2cSettings.signInPolicy}`;
  return new PublicClientApplication({
    auth: {
      clientId: b2cSettings.clientId,
      redirectUri: `${window.location.origin}`,
      authority,
      knownAuthorities: [`${b2cSettings.tenant}.b2clogin.com`]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    }
  });
```

### Relevant Code Snippets

```javascript
return this.authService.acquireTokenSilent({ scopes, account }).pipe(
      catchError(err => {
        this.authService.acquireTokenRedirect({
          ...this.msalInterceptorConfig.authRequest,
          scopes,
          redirectStartPage
        });
        return EMPTY;
      }),
```

### Reproduction Steps

Wait for refresh token to expire without logging in (24h) or inject expired tokens into local storage then reload app

### Expected Behavior

Not going into infinite loops

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment] 2021-06-18 15:11
@jakobgn This error is thrown by `acquireTokenSilent`, not `acquireTokenRedirect`, and is expected when 3rd party cookies are blocked. Can you try to determine why this error is not being caught by your code?

**Comment by jakobgn** [comment] 2021-06-21 07:11
@tnorling Sorry the description was not correct, it is indeed acquireTokenSilent that fails

**Comment by jakobgn** [comment] 2021-06-21 07:15
And as I understand, the library should still work with 3rd party cookies blocked as it is 2.x with auth code and PKCE? 

We also do catch the error, it is just not handled well by default (going in infinite reload loop). Maybe it is MSAL, probably B2C, but who knows really.

**Comment by tnorling** [comment] 2021-06-21 17:09
> And as I understand, the library should still work with 3rd party cookies blocked as it is 2.x with auth code and PKCE?

Yes, the library will work in **most** scenarios where 3rd party cookies are blocked. The one thing that will not work with 3rd party cookies blocked is silent token renewal when the refresh token has expired (every 24 hours).

In this scenario you'll receive a `monitor_window_timeout` error such as the one you're getting. And you'll need to catch this and call `acquireTokenRedirect` as you're doing.

So it seems the error you're getting is probably expected and we just need to determine why you're getting stuck in a loop afterwards. Are you calling `handleRedirectPromise` anywhere to handle returning from the redirect? Are you waiting for that to complete before calling `acquireTokenSilent`?

Also you indicated that you're not using a wrapper library but the code snippet you shared looks like Angular. Can you please confirm whether you are using `msal-browser` on it's own or are you also using `msal-angular`?

**Comment by jakobgn** [comment] 2021-06-22 13:43
Good points, thank you for your insight!

We are indeed using `msal-browser `in Angular without the Angular wrapper. We wanted to move to MSAL 2.0 before the wrapper was ready.
We are indeed calling `handleRedirectPromise ` in the `authGuard `which should be called on all authenticated page loads. I can look into if it gets called and completed before `acquireTokenSilent `
And we are sometimes manipulating the hash - will look into if that is also the case here, thanks

**Comment by jakobgn** [comment] 2021-06-25 11:39
@tnorling 
I have investigated a bit further based on your feedback. Our solution is more or less the same as https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample

- The interceptor acquireTokenRedirect returns to our baseUrl with only #state in the url. It does not remember the furl href i.e. /user/settings. 
```
this.authService.acquireTokenRedirect({
          ...this.msalInterceptorConfig.authRequest,
          scopes,
          redirectStartPage
        });
```

- In our app component onInit we have some custom logic that routes the user to their start page based on token permissions. I.e. /dashboard for some users and admin/dashboard for others. This rerouting loses the url #state causing the infinite reload loop. 
-  If I remove the rerouting, the looping stops but there is still a single awkward redirect happening after the timeout 5ish seconds after the app loads.
-  A possible fix is to append the #state when we do the rerouting. Perhaps we can live with a single awkward redirect.


On another note - there is some concern in our org about storing tokens in the browser storage. Do you plan to support storing tokens in memory (I think this is what Auth0 does)?

**Comment by jakobgn** [comment] 2021-06-25 12:02
Sadly adding state to the route fragment like so `/admin/dashboard#state=eyJpZCI6ImRlZjkw...` does not fix the infinite reload 😢

**Comment by jakobgn** [comment] 2021-06-25 12:22
Would it be a solution to just clear the cache for msal tokens before doing the acquireTokenRedirect? We don't mind that the user will need to do an interactive login after 24 hours - I think it would actually be preferable to limit access via stored refresh tokens as much as possible for security purposes

**Comment by tnorling** [comment] 2021-06-28 17:45
@jakobgn 

I'm not sure I understand your scenario both the expected behavior as well as the current behavior. Can you please walk me through step by step how you want this to work and how it is working right now? For instance, you say only #state is in the url. Are you saying that AAD is redirecting back to your redirectUri with only #state and no tokens? Or is your app providing a custom state that you are using to handle the redirects between pages and appending this manually on redirects?

> On another note - there is some concern in our org about storing tokens in the browser storage. Do you plan to support storing tokens in memory (I think this is what Auth0 does)?

This is supported by setting `cacheLocation: "memoryStorage"` in your MSAL config. [API docs](https://azuread.github.io/microsoft-authentication-library-for-js/ref/enums/_azure_msal_browser.browsercachelocation.html) for reference. Be warned, however, that this can lead to a degraded user experience when using redirects as tokens will be lost on each page load.

> Would it be a solution to just clear the cache for msal tokens before doing the acquireTokenRedirect? We don't mind that the user will need to do an interactive login after 24 hours - I think it would actually be preferable to limit access via stored refresh tokens as much as possible for security purposes

I'm not sure what you mean here or why this would help. Can you please clarify? Are you saying you wish to not hold access tokens in the cache and only use the refresh token to acquire new tokens? We don't provide a way to pick and choose like this.

**Comment by jakobgn** [comment] 2021-07-01 08:25
@tnorling 

> I'm not sure I understand your scenario both the expected behavior as well as the current behavior. Can you please walk me through step by step how you want this to work and how it is working right now? For instance, you say only #state is in the url. Are you saying that AAD is redirecting back to your redirectUri with only #state and no tokens? Or is your app providing a custom state that you are using to handle the redirects between pages and appending this manually on redirects?

Sorry for the confusion. We are being redirected back from B2C with tokens and everything as expected. The issue is that we are navigating our users to a default page using the angular router when the page is done loading and the ACQUIRE_TOKEN_SUCCESS event is emitted from MSAL. This happens before MSAL is done timing out, which seem to cause the loop. Appending the #state to the new route did not help. 
> 
> > On another note - there is some concern in our org about storing tokens in the browser storage. Do you plan to support storing tokens in memory (I think this is what Auth0 does)?
> 
> This is supported by setting `cacheLocation: "memoryStorage"` in your MSAL config. [API docs](https://azuread.github.io/microsoft-authentication-library-for-js/ref/enums/_azure_msal_browser.browsercachelocation.html) for reference. Be warned, however, that this can lead to a degraded user experience when using redirects as tokens will be lost on each page load.
> 

We tried changing to memoryStorage as that would fix this issue but it seems like the tokens are not being cached properly. On every API call we make, MSAL fetches new tokens instead of retrieving them from the memory cache, but maybe I misunderstood the intent of memoryStorage. The documentation of this feature is very limited. 

> > Would it be a solution to just clear the cache for msal tokens before doing the acquireTokenRedirect? We don't mind that the user will need to do an interactive login after 24 hours - I think it would actually be preferable to limit access via stored refresh tokens as much as possible for security purposes
> 
> I'm not sure what you mean here or why this would help. Can you please clarify? Are you saying you wish to not hold access tokens in the cache and only use the refresh token to acquire new tokens? We don't provide a way to pick and choose like this.

The issue is caused due to expired tokens being cached in the browserStorage. I am asking if clearing the browserStorage when we catch the timeout error would be a decent fix in this case.

**Comment by tnorling** [comment] 2021-07-01 17:47
@jakobgn 

> The issue is that we are navigating our users to a default page using the angular router when the page is done loading and the ACQUIRE_TOKEN_SUCCESS event is emitted from MSAL.

Got it. Can you please put a check in your code to detect when it's being run in an iframe? When your app is loaded in an iframe it should not do **any** navigation or manipulate the hash as it can cause race conditions like this. I suspect this navigation is causing the top frame's acquireTokenSilent call to timeout which means it's falling back to `acquireTokenRedirect` and causing your loop.

> Appending the #state to the new route did not help.

I'm still not really sure I understand how `state` is playing into this. Can you please explain why this is important?

> We tried changing to memoryStorage as that would fix this issue but it seems like the tokens are not being cached properly. On every API call we make, MSAL fetches new tokens instead of retrieving them from the memory cache, but maybe I misunderstood the intent of memoryStorage.

In-memory storage means the tokens will be cached in a variable on the `PublicClientApplication` instance. If the page is reloaded or `PublicClientApplication` is being re-instantiated all cache entries will be lost. Because you're using redirects to handle interactive auth I would expect this to happen at least every time you need to invoke interaction. If you're not changing routes or reloading the page and are still seeing cache misses then I would suggest debugging to see if `PublicClientApplication` is being re-instantiated somewhere.

> The issue is caused due to expired tokens being cached in the browserStorage. I am asking if clearing the browserStorage when we catch the timeout error would be a decent fix in this case.

Generally we advise against manually clearing cache. The library should handle cleanup on it's own and the fact that you're getting a timeout error means that something is misconfigured, your best bet to is to solve the underlying problem.

**Comment by jakobgn** [comment] 2021-07-05 12:58
> @jakobgn
> 
> > The issue is that we are navigating our users to a default page using the angular router when the page is done loading and the ACQUIRE_TOKEN_SUCCESS event is emitted from MSAL.
> 
> Got it. Can you please put a check in your code to detect when it's being run in an iframe? When your app is loaded in an iframe it should not do **any** navigation or manipulate the hash as it can cause race conditions like this. I suspect this navigation is causing the top frame's acquireTokenSilent call to timeout which means it's falling back to `acquireTokenRedirect` and causing your loop.
> 
Sure - but my understanding was that the running in iframe is an implementation detail of MSAL so how do I know when it is running in an iframe? Which MSAL file can give me this information?

> > Appending the #state to the new route did not help.
> 
> I'm still not really sure I understand how `state` is playing into this. Can you please explain why this is important?
> 
Fair - It is probably not important. 
> > We tried changing to memoryStorage as that would fix this issue but it seems like the tokens are not being cached properly. On every API call we make, MSAL fetches new tokens instead of retrieving them from the memory cache, but maybe I misunderstood the intent of memoryStorage.
> 
> In-memory storage means the tokens will be cached in a variable on the `PublicClientApplication` instance. If the page is reloaded or `PublicClientApplication` is being re-instantiated all cache entries will be lost. Because you're using redirects to handle interactive auth I would expect this to happen at least every time you need to invoke interaction. If you're not changing routes or reloading the page and are still seeing cache misses then I would suggest debugging to see if `PublicClientApplication` is being re-instantiated somewhere.
> 
Yea unfortunately it is fetching tokens on the same page several times without redirects. The only change being the configuration of  memoryStorage over localStorage and storeAuthStateInCookie:true. 

> > The issue is caused due to expired tokens being cached in the browserStorage. I am asking if clearing the browserStorage when we catch the timeout error would be a decent fix in this case.
> 
> Generally we advise against manually clearing cache. The library should handle cleanup on it's own and the fact that you're getting a timeout error means that something is misconfigured, your best bet to is to solve the underlying problem.
Agree, it would be nice to solve the root cause. I feel MSAL should be able to handle expiring tokens more gracefully than a timeout after a failed call to the /token endpoint. It should be possible to check the expire time on the token before calling the /token endpoint to avoid the failed request?

**Comment by tnorling** [comment] 2021-07-06 17:19
@jakobgn 

> Sure - but my understanding was that the running in iframe is an implementation detail of MSAL so how do I know when it is running in an iframe? Which MSAL file can give me this information?

Use this: `const isInIframe = window !== window.parent;`

> Agree, it would be nice to solve the root cause. I feel MSAL should be able to handle expiring tokens more gracefully than a timeout after a failed call to the /token endpoint. 

To be very clear, the timeout is **not** caused by an expired token or a failed call to the /token endpoint. The timeout is caused by a race condition between your app's route changes and MSAL receiving the response from the server. There's unfortunately nothing we can do on our side to fix that or make it handle that scenario more gracefully. It's an unexpected error and usually should be an indication to you that something is wrong with your implementation.

> It should be possible to check the expire time on the token before calling the /token endpoint to avoid the failed request? 

This is how MSAL works. It first looks in the cache for a token and checks if it is expired. If the token does not exist or is expired it will attempt to renew using the refresh token and a POST request to the /token endpoint. If that fails due to an expired refresh token or other, MSAL will then open a hidden iframe to the /authorize endpoint and use the server's session cookie to sign you back in. The last step is what's failing.

**Comment by jakobgn** [comment] 2021-07-08 12:32
@tnorling 
isInIframe is always false, is that a bad sign?

I discovered that we initiate angular routing already as soon as we have an account object available starting the race condition in the case that the token is invalid. If I delay the routing until `msal:acquireTokenSuccess` has been emitted the loop is avoided but the app doesn't reroute at all in the case that there is a valid token in the cache so also a no-go unfortunately. Clearing the browser cache is still the only working solution so far.
It would be nice if MSAL could always emit an event when it is "done" so we can do our rerouting after that.

For any of the tried solutions the app hangs for 6 seconds after the failed /token call. Is that expected?

**Comment by tnorling** [comment] 2021-07-08 16:08
> `isInIframe` is always false, is that a bad sign?

This should return false anytime this code is run in the top frame of the window. It should return true if it is run inside of an iframe. Unless your app is intentionally being embedded inside an iframe the only time this should return true is inside the hidden iframe that is used when the refresh token is expired.

> It would be nice if MSAL could always emit an event when it is "done" so we can do our rerouting after that. Right now we cannot really trust the presence of tokens(as the refresh token might be expired) nor the `msal:acquireTokenSuccess` as it is not fired when the token comes from cache.

What you're looking for here is `msal:HandleRedirectEnd` which will be emitted after `handleRedirectPromise` has finished processing the hash. Additionally `msal:acquireTokenSuccess` does get emitted after a token is retrieved from the cache as seen [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/be9a1f45b6b52fce073ffdb2e36b89a93121170e/lib/msal-browser/src/app/PublicClientApplication.ts#L102). It may be worth double checking that it's not getting fired in your case and spending some time debugging if that is indeed the case...

I would also highly recommend moving over to the `msal-angular` v2 library as that is now GA and may solve some of these issues you are having out of the box.

> For any of the tried solutions the app hangs for 6 seconds after the failed `/token` call. Is that expected and can it be improved?

No this is unexpected. Is it succeeding after the 6 seconds or is it timing out still?

**Comment by jakobgn** [comment] 2021-07-12 14:13
@tnorling 
I updated our app to use the latest angular wrapper and it seemed to have fixed the issues mentioned here (hurray!). Thanks for the help. 

The MSAL interceptor does multiple requests to the token endpoint instead of waiting for the first request to finish

![image](https://user-images.githubusercontent.com/29198565/125301061-e67cc400-e32a-11eb-8e52-e83430d0ddab.png)
We had a fix to this in our own version of the interceptor but it would be nice to have this as part of the framework. It is mentioned in a different issue though.

**Comment by tnorling** [comment] 2021-07-12 16:08
@jakobgn Great to hear, thanks for the update! The parallel requests issue will be resolved in the next release of msal-browser via #3837

As this issue has been resolved, I'll go ahead and close this but feel free to open a new issue if you run into anything else.

**Closed by tnorling** 2021-07-12 16:08 UTC
Labels: Needs: Attention :wave:, answered, b2c, bug-unconfirmed, msal-browser, question
