### ISSUE TITLE
Logout Redirection issue

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#3590] opened 2021-05-06 08:46 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.5

### Description

There is a mismatch about what the documentation says about the post logout redirection and what actually happens. I will try to elaborate. The documentation can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logoutpopup). 

> postLogoutRedirectUri is **required** in order for MSAL to be able to close the popup when signout is complete

If I don't set the postLogoutRedirectUri, the popup still closes.

> postLogoutRedirectUri will be opened in the popup window, not the main frame. If you need your top level app to be redirected after logout you can use the mainWindowRedirectUri parameter on the logout request.

If I set the `postLogoutRedirectUri`, I am not sure if the URI is opened in the popup window, but what I am experiencing is that it is opening in the main frame for sure. I can not find a difference between the `postLogoutRedirectUri` and the `mainWindowRedirectUri` inside of the logout request.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: environment.AzureClientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    redirectUri: environment.FrontendBaseUrl,
    postLogoutRedirectUri: environment.FrontendBaseUrl,
    knownAuthorities: [environment.AzureB2CKnownAuthority],
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE, // set to true for IE 11
  },
}
```

### Relevant Code Snippets

```ts
if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
  return this.msal.logoutPopup({
    mainWindowRedirectUri: "/logout"
  });
} else {
  return this.msal.logoutRedirect();
}
```

```ts
if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
  return this.msal.logoutPopup({
    postLogoutRedirectUri: "/logout"
  });
} else {
  return this.msal.logoutRedirect();
}
```

Both main frmes land in the `/logout` page.

### Reproduction Steps

1. Logout

### Expected Behavior

I am not sure what the correct behavior should be, but either the docs or the behavior should be updated to match each other.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by hectormmg** [comment] 2021-05-06 22:39
Hi @eluchsinger 

1. The reason the popup is closing even if you don't set the `postLogoutRedirectUri` in the token request configuration may be that you have it configured in the MSAL Client configuration (so MSAL is still adding it to the request). What the doc means is that the server requires a `postLogoutReidrectUri` because otherwise it won't know where to redirect the browser to. For that reason, if you don't specify a `postLogoutRedirectUri` in either the request or the top-level configuraiton, MSAL sets it to the current page by default.

We'll try to reproduce your issue ourselves to see if there's something else going one since the main window shouldn't be doing the redirect if `mainWindowRedirectUri` isn't set.

While we do that, could you please provide verbose MSAL logs so we can better diagnose the issue? Thanks!

**Comment by eluchsinger** [comment] 2021-05-07 07:55
Hi @hectormmg 
I guess you mean the `environment.FrontendBaseUrl` variable in the MSAL Configuration. The value there is `https://localhost:3000`.   That should not be causing the the `/logout`  redirection.

**Comment by tnorling** [comment] 2021-05-10 17:57
@eluchsinger This was in reference to your first question about why the popup still closes despite not including `postLogoutRedirectUri` on the request object.

`postLogoutRedirectUri` -> navigated to in the popup window
`mainWindowRedirectUri` -> navigated to in the main window

Can you please provide logs and/or a link to a minimal reproduction? The main window should not be redirecting at all if `mainWindowRedirectUri` is not set on the request.

**Comment by eluchsinger** [comment] 2021-05-22 16:18
Keep open

**Comment by eluchsinger** [comment] 2021-05-31 07:00
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0NjQzMDY1NA==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0NjQzMDY1NA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0NjQzMDY1NA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-846430654" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="333f4727347bb91cb8f57b9fb206c412e4ad74a74bc88fbc53ac320bb9ddb132" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Keep open</task-lists></div><form class="js-comment-update" id="issuecomment-846430654-edit-form" action="https://github.com/AzureAD/microsoft-authentication-library-for-js/issue_comments/846430654" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOkxhYmVsZWRFdmVudDQ3ODI0OTU4NjA=" style="box-sizing: border-box;"><div class="TimelineItem js-targetable-element" data-team-hovercards-enabled="" id="event-4782495860" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class="TimelineItem-badge " style="box-sizing: border-box; position: relative; z-index: 1; display: flex; width: 32px; height: 32px; margin-right: 8px; margin-left: -15px; color: var(--color-icon-secondary); align-items: center; background-color: var(--color-timeline-badge-bg); border: 2px solid var(--color-bg-canvas); border-radius: 50%; justify-content: center; flex-shrink: 0; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><svg class="octicon octicon-tag" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M2.5 7.775V2.75a.25.25 0 01.25-.25h5.025a.25.25 0 01.177.073l6.25 6.25a.25.25 0 010 .354l-5.025 5.025a.25.25 0 01-.354 0l-6.25-6.25a.25.25 0 01-.073-.177zm-1.5 0V2.75C1 1.784 1.784 1 2.75 1h5.025c.464 0 .91.184 1.238.513l6.25 6.25a1.75 1.75 0 010 2.474l-5.026 5.026a1.75 1.75 0 01-2.474 0l-6.25-6.25A1.75 1.75 0 011 7.775zM6 5a1 1 0 100 2 1 1 0 000-2z"></path></svg></div><br class="Apple-interchange-newline">

</div></div>

**Comment by tnorling** [comment] 2021-06-01 16:00
@eluchsinger We're still waiting for more information we requested from you. Please provide logs and/or a minimal reproduction so that we can assist you in debugging this. Thanks!

**Closed** 2021-06-14 13:00 UTC
Labels: Needs: Author Feedback, answered, b2c, bug-unconfirmed, msal-angular, msal-browser, no-issue-activity, question
