### ISSUE TITLE
openWindow resolve is never called

### ISSUE THREAD

**Issue by vipero07** [AzureAD/microsoft-authentication-library-for-js#341] opened 2018-07-05 13:57 UTC
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d29fa63e737d5f811d2a8af1f3a03448d07e5fe3/src/UserAgentApplication.ts#L482

As it stands if you use .loginPopup and expect the resolve to be called, the promise is never called. If you look at the code for the method linked above you will see resolve is never used, and tslint (if set up) actually says "'resolve' is declared but its value is never read."

To reproduce follow the example from the docs.
```
<script>
    userAgentApplication.loginPopup(applicationConfig.graphScopes).then(function (idToken) {
                //Login Success
                userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
                    //AcquireToken Success
                }, function (error) {
                    //AcquireToken Failure, send an interactive request.
                    userAgentApplication.acquireTokenPopup(applicationConfig.graphScopes).then(function (accessToken) {
                        updateUI();
                    }, function (error) {
                        console.log(error);
                    });
                })
            }, function (error) {
                console.log(error);
            });
    </script>
```
acquireTokenSilent will never be called.

**Comment by nehaagrawal** [comment] 2018-07-12 00:29
@vipero07 our samples work fine and acquireTokenSilent does get called.  OpenWindow() doesn't  resolve promise but it's resolved later in the code during the call to  `this.registerCallback(authenticationRequest.state, scope, resolve, reject);`

OpenWindow() doesn't return promise and it's a sync call. It calls reject only for error scenarios.
Can you please share what version of the library you are using and also if possible your repo where we can reproduce this issue?

**Comment by nehaagrawal** [comment] 2018-07-13 18:19
This issue is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/339. Please track it there. Closing this.

**Closed by nehaagrawal** 2018-07-13 18:19 UTC
Labels: duplicate

**Comment by vipero07** [comment] 2018-07-13 18:35
I don't have a copy of the exact code as I never checked it in (since it didn't work) but it was word for word the same as the code pasted above (different scopes and clientId of course). I already replaced it all with the adal-angular library which seems to work just fine (though I'm sure it has things included I don't need, and isn't typescript friendly). It is possible that the problem was aquireSilentToken didn't work, but I put a debugger inside the then function (right around the //Login Success comment) and it was never hit. Which lead me down the path of openWindow never calling resolve. If it is supposed to resolve elsewhere, it was never happening, and the issue could stem from there.
