### ISSUE TITLE
MSAL Angular Wrapper is not passing protectedResourceMap when building --prod

### ISSUE THREAD

**Issue by ik1728** [AzureAD/microsoft-authentication-library-for-js#438] opened 2018-09-18 11:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
ALL Browser

## Library version
0.1.2

<pre><code>
Library version: 0.1.2
Angular Version : 6.1.6

## Current behavior
In Angular Production Build not able to get Access Token respective to protected resource map.
In DEV its working fine.

## Expected behavior
It should do  acquireTokenSilent in prod also like in DEV

## Minimal reproduction of the problem with instructions

Test in Angular Prod

</code></pre>

**Comment by nehaagrawal** [comment] 2018-09-19 00:11
This was fixed in 0.1.2. If you try our sample [here]( https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/samples) and run it with ng serve --prod --aot, it works fine,

**Comment by nehaagrawal** [comment] 2018-09-19 21:59
@ik1728  Can you please try our sample and let me know if it works?

**Comment by ik1728** [comment] 2018-09-20 00:28
Hi,

I have tried to download and run demo app but .
But in ng serve it gives me error msal not found in ../../msal.config.d

Can you please help me in this
So that I can try it.

Thanks
Imran

**Comment by nehaagrawal** [comment] 2018-09-20 18:09
@ik1728  These are our dev samples so currently you need to clone our branch and build the project and then run the sample. We are working on providing samples where you don't need to build the project. Can you please try building the branch first?

**Comment by nehaagrawal** [comment] 2018-09-26 00:09
@ik1728 This works fine. Do you work for Microsoft? I can help you there.

**Comment by nehaagrawal** [comment] 2018-10-22 23:56
Closing this issue since it's not reproducible.

**Closed by nehaagrawal** 2018-10-22 23:56 UTC
Labels: invalid, needs info
