### ISSUE TITLE
Error on login redirect

### ISSUE THREAD

**Issue by akhileshea** [AzureAD/microsoft-authentication-library-for-js#2686] opened 2020-12-03 11:36 UTC
I get the below error when I try to use login redirect and handleRedirectPromise is never called. 
Uncaught (in promise) TypeError: hashString.indexOf is not a function
    at Function.UrlString.parseHash (index.es.js:1907)
    at Function.UrlString.getDeserializedHash (index.es.js:1929)
    at Function.UrlString.hashContainsKnownProperties (index.es.js:1945)
    at PublicClientApplication.ClientApplication.getRedirectResponseHash (index.es.js:9048)
    at PublicClientApplication.<anonymous> (index.es.js:8993)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new Promise (<anonymous>)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.ClientApplication.handleRedirectResponse (index.es.js:8984)
    at PublicClientApplication.<anonymous> (index.es.js:8947)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at index.es.js:48
    at new Promise (<anonymous>)
    at __awaiter (index.es.js:44)
    at PublicClientApplication.ClientApplication.handleRedirectPromise (index.es.js:8940)
    at Main.login (MainComponent.js:87)
    at Main.componentDidMount (MainComponent.js:66)
    at commitLifeCycles (react-dom.development.js:19814)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at commitRoot (react-dom.development.js:22381)
    at finishSyncRender (react-dom.development.js:21807)
    at performSyncWorkOnRoot (react-dom.development.js:21793)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at flushSync (react-dom.development.js:21932)
    at Object.scheduleRefresh (react-dom.development.js:11626)
    at react-refresh-runtime.development.js:304
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js:293)
    at RefreshUtils.js:62

**Comment by tnorling** [comment] 2020-12-03 17:52
@akhileshea Can you please use one of the provided [issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose). Thanks!

**Comment by tnorling** [comment] 2020-12-07 18:09
Closing as duplicate of #2704

**Closed by tnorling** 2020-12-07 18:09 UTC
Labels: more-information-needed
