### ISSUE TITLE
Cannot find module '@azure/msal-angular'

### ISSUE THREAD

**Issue by AmielFabreguettes** [AzureAD/microsoft-authentication-library-for-js#6324] opened 2023-08-10 15:59 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0

### Public or Confidential Client?

Public

### Description

Hello ! 
I downloaded msal-angular and it appears in node_modules/@azure. But when i try to import it in app.module.ts it says: 
"Cannot find module '@azure/msal-angular' or its corresponding type declarations".
I already tried to reinstall it to clear the cache but it doesn't work.

### Relevant Code Snippets

```javascript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { IPublicClientApplication } from '@azure/msal-browser';
import { MsalModule } from '@azure/msal-angular';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    MsalModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by AmielFabreguettes** [comment] 2023-08-10 16:01
I would add that it's probably not a path issue, as msal-browser imports successfully.

**Comment by jo-arroyo** [comment] 2023-08-10 16:13
@AmielFabreguettes There was an error with our msal-angular release process, and we are currently working on a fix. Please see #6310, where the issue was first raised, and where updates will be posted.

Closing as duplicate of #6310.

**Closed as completed by jo-arroyo** 2023-08-10 16:13 UTC
Labels: question, msal-angular, msal-browser, public-client
