### ISSUE TITLE
I cannot refresh my expired token immediately

### ISSUE THREAD

**Issue by webivan1** [AzureAD/microsoft-authentication-library-for-js#4530] opened 2022-02-16 20:22 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.2.4

### Description

Hi 
When i try to refresh an expired token the Azure send me back the same expired token
I use the library @azure/msal-browser with Vue2 and axios
I have tried to refresh my access token through acquireTokenSilent
I check my current token is it expired or not yet 
```javascript
isExpired(): boolean {
    const { exp } = this.VueJwtDecode.decode(this.token)
    return exp <= new Date().getTime() / 1000
  }
```
```javascript
import { PublicClientApplication } from '@azure/msal-browser'
import { AccountInfo, AuthenticationResult } from '@azure/msal-common'

   init(): PublicClientApplication {
      return new PublicClientApplication({
        auth: {
          clientId: this.apiKey.clientId,
          authority: `${this.url}/${this.apiKey.tenantId}`,
          redirectUri: this.uri,
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: true,
        },
      })
    },

    getAccount(): AccountInfo | undefined {
      const accounts = this.init().getAllAccounts()

      if (!accounts) {
        return undefined
      }

      return accounts.shift()
    },

    async refreshToken(): Promise<AuthenticationResult> {
      const account = this.getAccount()

      if (!account) {
        throw new Error('You should be logged in')
      }

      return await this.init().acquireTokenSilent({
        scopes: ['openid', 'profile'],
        account,
      })
    },
```
The Azure send me back the same token in during 5 - 10 minutes and after a new token

### MSAL Configuration

```javascript
auth: {
          clientId: this.apiKey.clientId,
          authority: `${this.url}/${this.apiKey.tenantId}`,
          redirectUri: this.uri,
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: true,
        },
```

### Relevant Code Snippets

```javascript
import { PublicClientApplication } from '@azure/msal-browser'
import { AccountInfo, AuthenticationResult } from '@azure/msal-common'

   init(): PublicClientApplication {
      return new PublicClientApplication({
        auth: {
          clientId: this.apiKey.clientId,
          authority: `${this.url}/${this.apiKey.tenantId}`,
          redirectUri: this.uri,
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: true,
        },
      })
    },

    getAccount(): AccountInfo | undefined {
      const accounts = this.init().getAllAccounts()

      if (!accounts) {
        return undefined
      }

      return accounts.shift()
    },

    async refreshToken(): Promise<AuthenticationResult> {
      const account = this.getAccount()

      if (!account) {
        throw new Error('You should be logged in')
      }

      return await this.init().acquireTokenSilent({
        scopes: ['openid', 'profile'],
        account,
      })
    },
```

### Reproduction Steps

1. Expired token
2. Try to refresh token immediately

### Expected Behavior

If my access token is expired I want to get a new token immediately 

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by webivan1** [comment] 2022-02-16 23:19
I have received the same token and time wasn't correct https://i.imgur.com/npg4Tc9.png
Actually "ext" of payload object in a "new JWT token" have already expired https://i.imgur.com/dT5WUNo.png
My current time is 23:00) 
Finally my token was expired at 22:55 but the same token is still alive in Azure until 23:17

**Comment by webivan1** [comment] 2022-02-17 14:09
If someone has the same issue please try the code:
```javascript
    async refreshToken(oldToken?: string): Promise<AuthenticationResult> {
        const account = this.getAccount()

        const accessTokenRequest = {
          scopes: ['openid', 'profile'],
          account,
        }

        try {
          const response = await this.init().acquireTokenSilent(accessTokenRequest)

          if (oldToken && response.idToken === oldToken) {
            throw new Error('Invalid token')
          }

          return response
        } catch (error) {
          return await this.init().acquireTokenPopup(accessTokenRequest)
        }
      },
```
It works for me, but I hope the logic of acquireTokenSilent will be resolved

**Comment by hectormmg** [comment] 2022-02-17 18:04
@webivan1 it seems this issue is a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206. At the moment MSAL doesn't look at the ID Token's expiration for renewal logic, please look at that issue for details. Closing as duplicate.

**Closed as completed by hectormmg** 2022-02-17 18:04 UTC
Labels: question, msal-browser, bug-unconfirmed
