### ISSUE TITLE
Please just add the refreshToken to the `acquireTokenByCode` api

### ISSUE THREAD

**Issue by justinmchase** [AzureAD/microsoft-authentication-library-for-js#6079] opened 2023-05-31 22:05 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

I have code such as this:
```ts
const { idToken, idTokenClaims, accessToken, expiresOn } = await app.acquireTokenByCode({
  code,
  scopes: DEFAULT_SCOPE,
  redirectUri,
})
```

But I need it to return the `refreshToken` as well. I know you're getting it and intentionally omitting it but its really frustrating and I just need to get the refresh token.

I've looked at a lot of your samples for the caching and I have to say after reviewing it and using this library for multiple years now I just don't think it makes any sense at all the way you're doing it. All of your examples and even your wrapper library `@azure/msal-node-extensions` are attempting to do caching of the refresh tokens to disk and even if I were to build my own cache plugin its expecting me to be caching all of these refresh tokens in a database and I have to say it just _doesn't make any sense to me_. 

For one thing, caching anything to a servers disk is a huge error. Nothing should be caching into a servers disk, my servers don't even have writiable disks at all so none of that makes any sense. Also I have more than one server, what good is caching to disk going to do? So why you all even have these disk cache examples is beyond me.

Secondly, caching to a database similarly makes no sense to me. I'll have to give the user an id of the cached entry no? I don't think its safe to use anything off of an expired token so that means they'll need a secret... and at that point I'm wondering why I didn't just give them a dang refreshToken, now they need a token to get the refresh token.

You know whats easy? Just giving the user the refresh token and having them cache it however they want. Super easy. No database calls, no complexity, no caching. 

I'm looking [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/refresh-token#msal-node-standalone-sample-refresh-token-grant) and it says:

> Note that MSAL does not expose refresh tokens by default and developers are not expected to build logic around them, as MSAL handles the token refreshing process itself.

I think its fine if you want to support that but its really frustrating that not only do you not expose it by default but you're omitting it entirely and not exposing it at all. I've been struggling with this for a while and I can't tell you how much better it would be if you would _please_ just return the refreshToken along with all the other tokens in this function.

I really can't stress enough how much better this library would be if it would alter this opinion and stop doing all the caching at this layer. I really think if you want to have some fancy no-refresh caching system then make a new library which focuses on that but please just don't consume and hide the refresh token.

Maybe I'm just missing some massive piece of the vision here? I'm open to having it explained to me like a 5 year old but the above is just not cutting it for me. You say what you're doing but not why and I'm really skeptical that you're correct.

These examples by the way do not instill a lot of confidence, the code looks like it was written by an intern with no prior knowledge of javascript or nodejs. A couple of critiques:

1.  You're using `req.session` in this example. Try to write an example which doesn't not utilize the session at all, make it completely stateless.
2. Assume you will have two (or more) servers. Do not utilize the memory or disk for caching.
3. Use typescript. 
4. In the msalCachePlugin.js file, use the `export` and `class` keywords. Use async file system apis.
5. Your cache plugin api seems to serialize the _entire_ cache to the same file every time. What if you have multiple users? What if you have millions of users? Do I have a different app and different cache for every single user? This example does not show how during the cache persistence step it should be able to tell which user its being serialized for?
6. What if multiple requests for the same user are happening in parallel on different machines? If the whole cache is just being serialized and persisted on each request then how is that race condition being resolved?

### Source

External (Customer)

**Comment by jo-arroyo** [comment] 2023-05-31 23:28
Adding @bgavrilMS @sameerag @EmLauber for feedback on `acquireTokenbyCode` and refresh tokens.

**Comment by bgavrilMS** [comment] 2023-06-01 12:53
Hi @justinmchase - thanks for the feedback!

First of all, please note that AAD is fully standards compliant with OAuth2 / OpenID Connect and you can use any SDK that  implements the protocol if you want to have full control. MSAL is a slightly higher level API which aims to raise the abstraction level from the protocols and to focus on scenarios - desktop apps, SPA, web site, web api. You are not locked in to use MSAL for auth with AAD, particularly if your application targets a single AAD tenant.

`AcqurireTokenByAuthCode` is specific to the web site scenario. Are you trying to integrate MSAL with Express?

MSAL offers token cache extensibility. It does NOT persist the token cache anywhere by default, definitely not on disk. It'll keep tokens in its memory, so if you use a singleton `ConfidentialClientApplication` object then all the tokens will be in memory. This is not great, as the tokens for 1 user are about 8 KB in size, so you can see how this doesn't scale. 

As such, we recommend using the token cache extensibility mechanism. The Express sample shows you how to use [Redis to persist tokens](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ExpressTestApp/README.md#token-caching). This serializes the cache of a **single user**. The cache key is essentially the user id. 

You can also use the session to persist tokens as you suggest. Simplest is to create a new ConfidentialClientApplication and point it to the cache location each time. @derisen - do we have a sample for using session? Are there disadvantages for using session?


Aside. Some of the complexity in handling refresh token yourself: 

1. you have to handle access token expiration and it's not trivial. You have to handle durations etc. and come up with a clock skew as well.
2. the refresh_token flow can end up in a an error. This could be something like "MFA is required" or "bad credential". MSAL will disambiguate these errors to guide you to the correct way of handling them - e.g. if "MFA is required" you'll get an "UiRequiredException" and you have to redirect the user to re-login. 
3. A user can be a guest in other tenants. The refresh token in the same across all tenants so you don't need to re-auth the same user in every other tenant.

**Comment by bgavrilMS** [comment] 2023-06-01 13:03
CC @jmprieur and @localden

**Comment by derisen** [comment] 2023-06-01 18:25
@justinmchase thanks you very much for the detailed feedback. I think we have caused a misunderstanding with our use of the word "disk" -this was meant to be "non-in-memory" cache, any medium to save the cache other than the memory, e.g. a database or a redis cache. We certainly did not mean the actual disk for the server side apps. Apologies for the confusion, I'll look into revising wording in cache docs. 

On a more general note, samples under this repo are primarily meant to showcase msal APIs in action for automated and manual testing, and none of them deals with server side issues like scaling unless explicitly mentioned (neither they showcase the larger IAM best practices, but that's another matter). To help with the scaling issues, we've put forward a few distributed caching samples recently. I'm curious about your take on them:

- [client-credentials-distributed-cache](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/client-credentials-distributed-cache)
- [on-behalf-of-distributed-cache](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/on-behalf-of-distributed-cache)
- [auth-code-distributed-cache](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5772) (this one is in PR -would appreciate any reviews)

We have also updated the docs on caching recently (not sure if you came across them):

- [Caching](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md)
- [Performance](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/performance.md)

Regarding session usage. The session middleware used in the samples is storing the user session server-side, which you can opt-in to use together with a distributed session store. Could you help me understand why would that be an issue for scaling, and what a stateless approach would look like instead?

**Comment by justinmchase** [comment] 2023-06-01 23:28
The other source of confusion is the use of the session and session id for persistence. I don't have a session at all and am intentionally not using the session. So I've tried to implement a MongoCachePlugin but there is no "id" available to use to save the state to. The id of the user is the logical id to use but the plugin doesn't give me the account information clearly in the cache plugin.

And again, I can't really state this emphatically enough, even with caching of the tokens enabled I still need the refresh token. I _really_ wish you guys would please just start returning the refresh token along with the other tokens it would make my life so much simpler its not even funny. By all means people can also use the caching and ignore the refresh token if they want but if you do want it and can't get it... its brutal.

Also, sorry to be so rude in the original issue, I was getting frustrated. But I will say that a lot of these  samples would be greatly improved with TypeScript and some other code quality pass overs. I see some functions for example returning promises and using .then().catch() instead of using async/await and functions in places where classes should be used... It would help quite a bit to put in some effort to modernize some of the javascript in here.

**Comment by justinmchase** [comment] 2023-06-01 23:34
> Are you trying to integrate MSAL with Express?

Yes, exactly.

Based on some of this feedback I am altering my app to create a `new ConfidentialClientApplication()` on every request for now... though I really don't think this should be necessary it seems like it should be easily possible to use a single instance, I would definitely prefer to not construct throw away objects on every request if it can be avoided.

> The cache key is essentially the user id.

But in that example it seems to be getting the userid from the session. I would be really interested in seeing a non-session based solution, I can't seem to figure it out.

**Comment by derisen** [comment] 2023-06-02 21:11
@justinmchase sorry for the late response. the reason we are making use of sessions in the web app samples is twofold:

1) Before the token request takes place, you don't have any artifacts (e.g. ID token) to identify the user, so you don't have a way to do a cache lookup. So using a persistent server side session helps to identify the user to do a cache lookup before making the token request.
2) Token acquisition with msal-node is a 2 legged process, where you first make a request to the authorization endpoint, and then obtain the authorization code from its response to make a request to the token endpoint (after which AAD responds with tokens). Since the execution context is lost when a redirect happens, sessions are utilized to keep some state about the user (for instance, which page to redirect the user after auth takes place). 

With respect to (1), I think it should be possible to do [hybrid flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow) to receive an ID token directly from the authorize endpoint, which would give you the user id to do the cache lookup before the access token request. For (2), I don't have a workaround on top of my mind -open to suggestions : )

Let me try to put together a working example and share it here.

**Comment by derisen** [comment] 2023-06-05 17:45
@justinmchase @bgavrilMS hybrid flow doesn't seem to be supported with msal-node at the moment. In that case, an alternative that might give you more flexibility is to serialize/deserialize the cache blob directly with tokenCache APIs. For instance:

```ts
    import { ConfidentialClientApplication  } from "@azure/msal-node";

    getMsalInstance(): ConfidentialClientApplication {
         return new ConfidentialClientApplication(msalConfig);
    }

    async getToken(tokenRequest): Promise<AuthenticationResult | null> {
          const msalInstance = getMsalInstance(); // get a fresh CCA instance
          
          msalInstance.getTokenCache().deserialize(await MyCacheStore.read(userId)); // read the cache blob for this user from your cache store into msal, if any
          
          const tokenResponse = await msalInstance.acquireTokenByCode(tokenRequest); // or acquireTokenSilent if you have account
          
          await MyCacheStore.write(userId, msalInstance.getTokenCache().serialize()); // write the cache blob for this user back to your cache store
          
          return tokenResponse;
    }
```

**Comment by justinmchase** [comment] 2023-06-06 00:56
Ok I see, I'll probably try that.

**Comment by ghost** [comment] 2023-06-12 13:00
@justinmchase This issue has been automatically marked as stale because it is marked as requiring author feedback but has not had any activity for **5 days**. If your issue has been resolved please let us know by closing the issue. If your issue has **not** been resolved please leave a comment to keep this open. It will be closed automatically in **7 days** if it remains stale.

**Closed as completed** 2023-06-12 19:32 UTC
Labels: question, msal-node, no-issue-activity, feature-unconfirmed, confidential-client

**Comment by derisen** [comment] 2023-06-12 20:24
Hi @justinmchase, just curious about how did it go -were you able to use serialize/deserialize directly?

**Comment by oshihirii** [comment] 2024-07-27 10:22
Can anyone please tell me how to get a refresh token?  

I instantiate MSAL instance with:

```
new msal.ConfidentialClientApplication(msal_config);
```

I log the response returned from:

```
const response = await confidential_client_application.acquireTokenByCode(
      token_request
    );
```

It returns an object that does not contain a `refreshToken` property.  

I have read that this is 'by design' but there must be a solution.  

There are so many posts on this topic throughout the internet, but I haven't found a solution.  

**Edit:**

Posts like this are giving me some hope, but they just seem like too much work to just get a refresh token, so I don't know if they are recommended approaches or not:

https://melmanm.github.io/misc/2023/01/29/article2-oauth-refresh-tokens-with-azure-b2c.html

**Comment by bgavrilMS** [comment] 2024-07-27 12:29
Hi @oshihirii - MSAL manages the refresh token internally. Just call AcquireTokenSilent and MSAL will: 

- return any cached access token
- if the cached access token exists but it is expired, it will use a cached refresh token to get a new access token and give it to you
- if none exists, an UiRequiredError will be thrown

Ultimately, you don't have to agree with out SDK choice to hide refresh tokens from app developers. Entra ID is fully OIDC compliant and you can use any OIDC library to fetch tokens.

**Comment by oshihirii** [comment] 2024-07-27 13:01
@bgavrilMS thank you very much for your reply.

My Node/Express app allows login via Azure AD B2C from two user types:

 - `INTERNAL` users who are within an Azure AD tenant that is specified as an Identity Provider (IDP) in Azure AD B2C, therefore Single Sign On (SSO) 
 - `EXTERNAL` users who are created directly in Azure AD B2C

In order to support login from internal and external users, and provide them both with varying levels of Graph API access to the internal users tenant, my app uses three different MSAL Node methods to return tokens, depending on the user type. 

It then saves the tokens to the user’s `req.session` object:    

**01)  acquireTokenByCode()**   

Session Property Name:  
`int_idp_access_token_app_reg_B2C_SignIn`     
Usage:
For `INTERNAL` users, returned after signing in to B2C.    
   
Session Property Name:
`int_access_token_ad_signin_Internal_User` 
Usage:
For `INTERNAL` users, returned after automatically signing them in to their own tenant, used for an OBO token request.  

**02)  acquireTokenOnBehalfOf()**  

Session Property Name:
`int_access_token_app_reg_InternalUser_M365_Access`
Usage:
For `INTERNAL` users, from an Azure App Registration that specifies permissions in their own tenant.   

**03)  acquireTokenByClientCredential()** 

Session Property Name:
`int_access_token_app_reg_Admin_M365_Access`  
Usage:
For `INTERNAL` users, from an Azure App Registration that specifies elevated permissions in their own tenant.  

Session Property Name:
`ext_access_token_app_reg_ExternalUser_M365_Access` 
Usage:
For `EXTERNAL` users, from an Azure App Registration that specifies limited permissions in the `INTERNAL` tenant.  

I am rying to implement a middleware function that checks if a token is about to expire.  

If it is about to expire, I want to refresh all the user's tokens.  

So I am hoping that `acquireTokenSilent` which is documented here: 

https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.ClientApplication.html#acquireTokenSilent

01.  Will be able to extend the expiry of access tokens that were originally created with those 3 methods, ie:

 - `acquireTokenByCode()`  
 - `acquireTokenOnBehalfOf()`
 - `acquireTokenByClientCredential()`

02.  Works with Confidential Client Applications 

03.  Can handle the `idp_access_token` that is associated with the initial Azure AD B2C signin.  

So I will try that now, fingers crossed.  

Thanks again.  

**Update:**

I called `acquireTokenSilent()` to refresh the `idp_access_token` returned for an `INTERNAL` user after B2C signin:

```
InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.
    at createInteractionRequiredAuthError (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-common/dist/error/InteractionRequiredAuthError.mjs:83:12)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-common/dist/client/RefreshTokenClient.mjs:97:19)
    at file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-common/dist/utils/FunctionWrappers.mjs:64:16    
    at RefreshTokenClient.acquireTokenByRefreshToken (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-common/dist/client/RefreshTokenClient.mjs:86:211)
    at SilentFlowClient.acquireToken (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-common/dist/client/SilentFlowClient.mjs:50:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConfidentialClientApplication.acquireTokenSilent (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/node_modules/@azure/msal-node/dist/client/ClientApplication.mjs:138:20)
    at async refresh_access_tokens_if_required (file:///C:/Users/<user-name>/Documents/REPOS/<repo-name>/config/msal_functionality.js:483:8) {
  errorCode: 'no_tokens_found',
  errorMessage: 'No refresh token found in the cache. Please sign-in.',
  subError: '',
  timestamp: '',
  traceId: '',
  correlationId: '******',
  claims: ''
}
```

So I get the same error when calling `acquireTokenSilent()` for these three tokens:

Original tokens from acquireTokenByCode():
 - `int_idp_access_token_app_reg_B2C_SignIn` 
 - `int_access_token_ad_signin_Internal_User`
 
Original tokens from acquireTokenOnBehalfOf():  
 - `int_access_token_app_reg_EVA_InternalUser_M365_Access`  

These tokens relate to the `INTERNAL` users signing in.    

When I call `acquireTokenByClientCredential` on the tokens below, however, it seems to work.

The returned access token has an expiry 1hr from the time it was refreshed:

Original tokens from acquireTokenByClientCredential(): 
 - `int_access_token_app_reg_Admin_M365_Access`
 - `ext_access_token_app_reg_ExternalUser_M365_Access`

I am trying to figure out what the pattern is for the failures and successes, and how to resolve the failures.  

The only thing I can think of is:

 - The two successes are related to purely 'app registration' permissions, as opposed to an individual user's permissions.  
 - I don't know if the fact that the internal users are signing in via Azure AD B2C and are in a Azure AD tenant that has been specified as an IDP is a problem 

I'm looking at the docs and dozens of websites posts and articles, but I can't find a solution:

https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_node.html

My `package.json` file was at `"@azure/msal-node": "^2.6.0"`, I updated to `2.12.0` and still get same behaviour.
