### ISSUE TITLE
Access token didn't get refreshed after switching to another tenant in MSAL2.0

### ISSUE THREAD

**Issue by Miwa199739** [AzureAD/microsoft-authentication-library-for-js#3687] opened 2021-05-27 04:34 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

We're implementing this customer requirement:
1. user login with the home tenant, and get an access token to management.azure.com/.default scope, acquireTokenSilently
2. we list all tenants that the current user belongs to (including home and tenant they're invited into)
3. user switch to one of non-home tenants
4. we get another token to management.azure.com/.default scope with updated authority with newly selected tenant ID, 
**5. we still get the legacy access token.**

**Notice we don't want to set forceRefresh as true as it compromises performance.**
And we didn't notice the same experience in MSAL 1.0, the access token gets refreshed once tenant ID changed.

Request correlationID: da2c1130-85e6-4e63-8edc-93c2df0492e2

Please see the following screenshots for more details:

Current cache state:
![image](https://user-images.githubusercontent.com/14820833/119765288-974b1300-bee5-11eb-87fd-875022029182.png)

Invoke a new request with updated authority:
![image](https://user-images.githubusercontent.com/14820833/119765420-d5483700-bee5-11eb-99e2-a4df67854f59.png)

Still get the legacy access token:
![image](https://user-images.githubusercontent.com/14820833/119765611-2fe19300-bee6-11eb-8990-dc141be7028a.png)

### Msal Logs

Request correlationID: da2c1130-85e6-4e63-8edc-93c2df0492e2

### MSAL Configuration

```javascript
{
            auth: {
                clientId: 'xxxxxx',
                authority: 'https://login.microsoftonline.com/organizations',
                redirectUri: window.location.origin,
                postLogoutRedirectUri: window.location.origin + baseHref,
                navigateToLoginRequestUrl: true
            },
            cache: {
                storeAuthStateInCookie: false,
                cacheLocation: 'sessionStorage'
            },
            system: {
                loggerOptions: {
                    loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
                        if (containsPii) {
                            return;
                        }
                        switch (level) {
                            case LogLevel.Error:
                                console.error(message);
                                return;
                            case LogLevel.Info:
                                console.info(message);
                                return;
                            case LogLevel.Verbose:
                                console.debug(message);
                                return;
                            case LogLevel.Warning:
                                console.warn(message);
                                return;
                        }
                    },
                    piiLoggingEnabled: false
                }
            }
        };
```

### Relevant Code Snippets

```javascript
public getToken(authArea: string | string[], designatedTenantId : string) {
const tenantId = designatedTenantId || this._tenantId || this._urlInfo.tenantId || await this.fetchTenantAsync;
        const request: SilentRequest = await this._generateAuthParams(authArea, tenantId, forceRefresh);
        
        const authResult = await this._msalInstance.acquireTokenSilent(request);   
}

 private async _generateAuthParams(authArea: string | string[], tenantId?: string, forceRefresh?: boolean): Promise<SilentRequest> {
        let scopes: string[] = [];
        if (typeof authArea === 'string') {
            authArea = authArea + '/.default';
            scopes = [authArea];
        } else {
            scopes = authArea;
        }
        const curAccount = await this.getAccount();
        return {
            scopes,
            authority: tenantId != null ? AuthConstants.AAD_ENDPOINT + tenantId : undefined,
            // forceRefresh: tenantId != null,
            account: curAccount,
            correlationId: generateUUID()
        };
    }
```

### Reproduction Steps

1. user login with the home tenant, and get an access token to management.azure.com/.default scope, acquireTokenSilently
2. we list all tenants that the current user belongs to (including home and tenant they're invited into)
3. user switch to one of non-home tenants
4. we get another token to management.azure.com/.default scope with updated authority with newly selected tenant ID, 
**5. we still get the legacy access token.**

### Expected Behavior

A new access token should be fetched if the authority changed.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

Internal (Microsoft)

**Comment by pkanher617** [comment] 2021-06-01 23:48
The user will need to sign into the non-home tenant, which will populate the cache with the account from that tenant. You can then use the account from that tenant to obtain tokens from that tenant for that user.

**Comment by Miwa199739** [comment] 2021-06-02 09:04
Thanks for the response but still got a few questions.

Are you referring to that in MSAL 2.0, we can only fetch access tokens to a specific tenant that the user is logged into? say if we want a home tenant access token, then log in user to the home tenant, and whenever cross-tenant acquireToken is invoked, the user should be forced to log in to that tenant? 
This sounds unexpected since if I pass **forceRefresh** as true when acquiring a token to access the resource in another tenant, I can still get the desirable token.

Also, this's not the case in MSAL1.0, in which we're using the same approach to get a cross-tenant access token, w/o having to explictly log in user in a different tenant. Each time the tenant is switched, we can acquire a new token silently to that specific tenant.

**Comment by pkanher617** [comment] 2021-06-05 00:08
Discussed offline, seems like this will need some improvements in the library for multi-tenant scenarios (i.e. tenant profiles, multi-tenant accounts). We will track this here and add a PR when we have some bandwidth for this feature.

**Comment by Miwa199739** [comment] 2021-06-10 07:20
This issue hasn't been resolved, and @pkanher617 is working on the fix, thanks!

**Comment by fhljys** [comment] 2021-07-05 02:53
@pkanher617 Any update on this issue?

**Comment by fhljys** [comment] 2021-08-30 10:52
Any update?

**Comment by sameerag** [comment] 2021-08-30 13:56
This is being tracked as a new feature but we currently do not have an ETA. We will reach out once we have this feature slated for release. @pkanher617 lets track this internally and figure out the details.

**Comment by izikl** [comment] 2021-09-23 13:03
@sameerag this issue is blocking our team from moving to MsalV2. You wrote 24 days ago that there in no ETA, is this still the case?

**Comment by fhljys** [comment] 2021-09-23 15:03
Same situation here. We got everything done and waiting for this fix. Could we take priority on this bug?

**Comment by jasonnutter** [comment] 2021-09-23 15:06
Does setting `forceRefresh` to `true` when invoking `acquireTokenSilent` work as a workaround? Obviously you shouldn't set it everytime, but setting it to true when you know the user has switched tenants should fix it, correct?

**Comment by izikl** [comment] 2021-09-23 15:10
We tried that. It works when forceRefresh is true but consecutive calls with forceRefresh = false are returning the old access token.

**Comment by jasonnutter** [comment] 2021-09-23 15:17
> We tried that. It works when forceRefresh is true but consecutive calls with forceRefresh = false are returning the old access token.

To clarify, are you saying that `acquireTokenSilent` with forceRefresh set to true returns the correct token, but when it is set to false (even after making a call where it was set to true) returns the old token?

**Comment by izikl** [comment] 2021-09-23 15:19
Yes.

**Comment by jasonnutter** [comment] 2021-09-23 15:23
> Yes.

Thanks. And did you try the workaround described above (when they switch tenants, send them through the login flow): https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3687#issuecomment-852566421

**Comment by izikl** [comment] 2021-09-23 15:45
> Thanks. And did you try the workaround described above (when they switch tenants, send them through the login flow)

We tried calling `acquireTokenRedirect` as well.

**Comment by izikl** [comment] 2021-09-23 16:00
Actually, with `acquireTokenRedirect` we saw an infinite redirect loop, that might have been caused by a bug on our side. I will go over it today and update this thread.

**Comment by Miwa199739** [comment] 2021-09-24 02:04
@jasonnutter, this workaround https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3687#issuecomment-925903055 doesn't seem appropriate for our case, where the main use scenario consists of 
1. user login to home tenant, 
2. select a data factory (an Azure resource) _in another tenant_, 
3. access the selected data factory and other Azure resources (azure storage, azure table and etc.)

In step 1, we **do not want** to re-login user to data factory tenant since it's a behavior change, then in step 3, whenever the acquireTokenSilent() is called, we gotta check if **curAccount.idTokenClaims.tid equals to the specified tenantId** (default is the data factory tenant), and set forceRefresh value accordingly. If the user's home tenant is not the data factory tenant, forceRefresh is always true thus invalidating token cache.

This seems a critical bug in MSAL 2.0, everything (token refreshing) worked perfect in 1.0. Could you please take this with priority?

**Comment by izikl** [comment] 2021-09-24 05:23
The workaround works. Thanks @jasonnutter.
I will keep an eye on this thread for the `acquireTokenSilent` fix.

**Comment by jasonnutter** [comment] 2021-09-24 14:13
> In step 1, we do not want to re-login user to data factory tenant since it's a behavior change,

@Miwa199739 Can you please clarify this point? And does doing this fix this issue for you?

**Comment by Miwa199739** [comment] 2021-09-25 05:43
@jasonnutter, yes, forceRefresh works in terms of funcitonality, but the experience is unwanted cause we don't expect token API call to be invoked too frequently.

Regarding 'In step 1, we do not want to re-login user to data factory tenant since it's a behavior change,', we actually mean if we want to reduce forceRefresh call due to mis-match tenant in step3 as much as possible, we gotta re-login user to the selected azure data factory's tenant. But this re-login deoptimizes the user experience, thus making it inappropriate for us.

Will wait for your fix for acquireTokenSilent, thanks!

**Comment by Miwa199739** [comment] 2021-11-15 09:37
@jasonnutter, any update?

**Comment by fhljys** [comment] 2021-11-15 09:37
@jasonnutter, any plan to fix this?

**Comment by sameerag** [comment] 2022-04-02 05:19
@EmLauber Lets track this internally for multi-tenant support in MSAL JS.

**Comment by MaslinuPoimal** [comment] 2023-01-27 17:50
@sameerag @jasonnutter Has there been any process on this? Forcing the user to re-login into the other tenant is far from ideal experience-wise. Any suggested ways to silently acquire the new tenant token?

**Comment by tnorling** [comment] 2024-02-02 18:02
Multi-tenant support shipped in MSAL.js v3.6.0 - More information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/multi-tenant-accounts.md), if you have questions or issues with this feature please open a new issue

**Closed by tnorling** 2024-02-02 18:02 UTC
Labels: enhancement, feature, msal-browser, tracked-internally
