### ISSUE TITLE
Is UserAgentApplication.acquireTokenPopup intended to gracefully handle concurrency?

### ISSUE THREAD

**Issue by chenxinyanc** [AzureAD/microsoft-authentication-library-for-js#2662] opened 2020-11-26 14:12 UTC
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I've been observing `AcquireToken_In_Progress` errors when trying to do some refactor to the existing authentication code. I was trying the code E2E under the scenario where `UserAgentApplication.acquireTokenSilent` fails with `AADSTS50076`, where user needs to sign in with popup dialog (we are using `UserAgentApplication.acquireTokenPopup`).

My question is, can I safely start another call to `UserAgentApplication.acquireTokenPopup` when there is already an outstanding `acquireTokenPopup` call whose returned `Promise<AuthResponse>` is yet to be resolved (i.e. user has not completed the login flow yet)?

My expectation is that any subsequent `acquireTokenPopup` calls should be delayed until the previous call has finished (like in #2116). But from my current observation, I'll receive following error if `acquireTokenPopup` gets called before user completes the login flow in the pop-up window.
```
ERROR Error: Uncaught (in promise): ClientAuthError: AcquireToken_In_Progress: Error during login call - login is already in progress.
ClientAuthError: AcquireToken_In_Progress: Error during login call - login is already in progress.
```

**Comment by jasonnutter** [comment] 2020-11-30 18:59
@chenxinyanc This is by design, as we don't allow multiple concurrent interactive requests. Your app will need to wait until the first popup request has completed before making another one.

**Comment by chenxinyanc** [comment] 2020-12-01 01:34
Okay. Then I'll need to do something like preserving the current `acquireTokenPopup` promise and waiting for it to settle before initiating another `acquireTokenPopup` (or even `acquireTokenSilent`) call.

**Comment by jasonnutter** [comment] 2020-12-11 18:03
Closing, as no further action in the library.

**Closed by jasonnutter** 2020-12-11 18:03 UTC
Labels: msal@1.x, question
