### ISSUE TITLE
Auth code grant stuck on authorization code

### ISSUE THREAD

**Issue by its-miller-time** [AzureAD/microsoft-authentication-library-for-js#4736] opened 2022-04-25 02:57 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Description

We have been using this same Aure app registration, redirect, etc for over 2 years without any issues but  over the past few days, our auth flow has been failing. To eliminate application errors I followed the code demo in the documentation and got the same issue described below:

- The user is prompted to enter their email in popup
- User is redirected to the login page in popup 
- The auth code is seen coming back in the URL

Auth flow simply stalls here. No errors, no prompts, no pending requests. Code is taken directly from the tutorial here: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react

### Msal Logs

`SAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:48 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:48 GMT] : [06f236fd-cf44-475d-b2c1-46e095a4b4f5] : msal.js.browser@2.23.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
2authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:48 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:48 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectEnd
2authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:48 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:56 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:loginStart
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:56 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:56 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
authConfig.js:17 [MSAL AUTH LOGGING] [Mon, 25 Apr 2022 03:03:56 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:popupOpened`

### MSAL Configuration

```javascript
{
    auth: {
      clientId: "<clientId>",
      authority: "https://login.microsoftonline.com/<tenentId>", // This is a URL (e.g. https://login.microsoftonline.com/{your tenant ID})
      redirectUri: "<redirectUrl>/redirect.html",
    },
    cache: {
      cacheLocation: "sessionStorage", // This configures where your cache will be stored
      storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    }
  }
```

### Relevant Code Snippets

```javascript
import { useMsal } from "@azure/msal-react";

function handleLogin(instance) {
    instance.loginPopup(loginRequest).catch(e => {
        console.error(e);
    });
}
```

### Reproduction Steps

1. build out sample app from tutorial
2. plug in relevant msal config info
3. click login button 
4. observe auth flow stall  in popup on code return 

### Expected Behavior

Auth flow completes, tokens are retrieved and set in sessionStorage

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment] 2022-04-25 19:32
@its-miller-time thanks for raising this issue. I've followed your repro steps and haven't been able to reproduce the stalling behavior. Are you able to share a network trace using a tool like Fiddler? You can send it to the email listed in my profile to avoid sharing sensitive information over GitHub.

There is also the possibility that the auth code is being cleared from the URL before MSAL can process it, are you getting any errors about an empty URL hash?

**Comment by bartlomiejborzucki** [comment] 2022-05-02 10:05
I have the same problem. 
Maybe this is the reason: 
`"There is also the possibility that the auth code is being cleared from the URL before MSAL can process it, are you getting any errors about an empty URL hash?" `
but I changed nothing in my code (like @its-miller-time)

**Comment by its-miller-time** [comment] 2022-05-02 12:36
Apologies for the delayed follow up. Dug into this an found it was a conflict in a minor version of react-router. Not sure which one, needed to get a fix out so I pinned it to the lowest minor version. Try taking the caret out of your dependencies list for react-router-dom and related dependancies.

**Comment by hectormmg** [comment] 2022-05-02 19:52
Thanks, closing the issue.

**Closed as completed by hectormmg** 2022-05-02 19:52 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed
