### ISSUE TITLE
acquireTokenSilent error not InteractionRequiredAuthError as documented

### ISSUE THREAD

**Issue by TiagoBrenck** [AzureAD/microsoft-authentication-library-for-js#733] opened 2019-05-28 20:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 74
- [x ] Firefox version 67

## Library version

Library version: 1.0.0

## Current behavior

According to the documentation, the error handling when acquiring a token could be done like this:

(code from: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release#signing-in-and-getting-tokens-with-msaljs)

```javascript
msalInstance.acquireTokenSilent(tokenRequest)
            .then(response => {
                // get access token from response
                // response.accessToken
            })
            .catch(err => {
                // could also check if err instance of InteractionRequiredAuthError if you can import the class.
                if (err.name === "InteractionRequiredAuthError") {
                    return msalnstance.acquireTokenPopup(tokenRequest)
                        .then(response => {
                            // get access token from response
                            // response.accessToken
                        })
                        .catch(err => {
                            // handle error
                        });
                }
            });
```

However, if errorCode == "login_required" or "consent_required", the error.name is actually "ServerError" not "InteractionRequiredAuthError"

## Expected behavior
I would expect the error.name to be "InteractionRequiredAuthError" or, update the documentation and remove the misleading example.

## Minimal reproduction of the problem with instructions
Execute the following code, in a scenario where an exception will the thrown for "login_required" or "consent_required" and observes the value on err.name:

```javascript
msalInstance.acquireTokenSilent(tokenRequest)
            .then(response => {
                // get access token from response
                // response.accessToken
            })
            .catch(err => {
                // could also check if err instance of InteractionRequiredAuthError if you can import the class.
                if (err.name === "InteractionRequiredAuthError") {
                    return msalnstance.acquireTokenPopup(tokenRequest)
                        .then(response => {
                            // get access token from response
                            // response.accessToken
                        })
                        .catch(err => {
                            // handle error
                        });
                }
            });
```

**Comment by pkanher617** [comment] 2019-05-29 21:30
@TiagoBrenck Thank you for bringing this to our attention. I believe this is because some errors contain the code in the description vs the error-code field. I can fix this in a PR. Do you have a console log of the full error object that causes this bug? Just to see what the field values are for code, description and name.

**Comment by TiagoBrenck** [comment] 2019-05-29 21:58
Here is the error object for a `login_required` exception:

```
{"errorCode":"login_required","errorMessage":"AADSTS50058: A silent sign-in request was sent but no user is signed in.\r\nTrace ID: 97c8ec8b-22f8-41cc-ae5d-28c792c13100\r\nCorrelation ID: 61920bed-96fe-4e4d-8b24-c648aa08f407\r\nTimestamp: 2019-05-29 21:55:49Z","name":"ServerError"}
```

**Comment by Ivan-L** [comment] 2019-06-10 10:07
Hi @pkanher617 I believe we are also affected by this issue.

```
ERROR AADSTS50058: A silent sign-in request was sent but no user is signed in.
Trace ID: 86311c91-d8a3-432a-9286-82325a743100
Correlation ID: 2fc73c0c-a46e-4078-a174-b21965ff2ffb
Timestamp: 2019-05-28 06:00:16Z|login_required
```

Is there any additional information that I can provide to help expedite this bug fix? We are currently using msal-angular preview.

**Comment by pkanher617** [comment] 2019-06-10 20:57
@TiagoBrenck @Ivan-L I believe I have found the cause for this issue. Our logic for checking the error was leaving out some error cases. I have implemented a fix for it in a PR #753. Please pull and run the branch to see if this fixes your issue.

**Comment by Ivan-L** [comment] 2019-06-12 19:18
Hi @pkanher617 I see the fix was in msal-core.

We are using msal-angular preview and it is stuck on an old version of msal-core. Referencing a newer version of msal-core causes msal-angular to not compile last time I checked, so it is difficult for me to verify.

I might move over to [angular-msal](https://www.npmjs.com/package/angular-msal) which is a fork of msal-angular but references a newer msal-core and is Angular 6+ compatible. That would enable me to test the fix you did.

Not directly related to this issue, but it is a pity that msal-angular preview is quite behind and will only be worked on between July and September according to the roadmap, forcing me to seek workarounds like this.

**Comment by pkanher617** [comment] 2019-06-21 19:49
@Ivan-L I understand your frustration. I will leave this issue open and update once we have an angular solution available.

**Comment by sameerag** [comment] 2019-06-26 05:07
Linking this to #786. We are tagging all angular requests that can be resolved with a basic angular wrapper support to msal 1.0.x with the above PR.

**Closed by sameerag** 2019-06-26 05:07 UTC
Labels: angular, bug, core
