### ISSUE TITLE
interaction_in_progress errror after returning from logoutRedirect

### ISSUE THREAD

**Issue by TylerBurnett** [AzureAD/microsoft-authentication-library-for-js#5807] opened 2023-03-22 02:09 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

As the title suggests, when using the MSAL browser in a react SPA, I get an `interaction_in_progress` error from the console. I understand the normal circumstances under which this can occur with a sign-in redirect, which I have been careful to ensure is not the case here. It is specifically when I log out that the issue occurs.

From looking through the code used to trigger the log-out request it stands out to me that in fact the call to set the interaction as is in progress doesn't have a counterpart for after the logout redirection from what I've observed. The docs don't seem to indicate some missing logout request receiver either.

Interaction in progress is set here for logout:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c72bd52d91e01ad36ce4d0e89a25530ccc9ab996/lib/msal-browser/src/interaction_client/RedirectClient.ts#L288-L307

I haven't run a debugger all the way through but it looks like my case is being caught on the 2nd else.

The current docs on logout behaviour:
https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2#sign-out-with-a-redirect

A workaround for this as of right now would be to just delete it from session storage which I will do whilst this is still an issue.

### Error Message

Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new BrowserAuthError (BrowserAuthError.ts:199:1)
    at BrowserAuthError.createInteractionInProgressError (BrowserAuthError.ts:280:1)
    at BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.ts:1000:1)
    at ClientApplication.preflightInteractiveRequest (ClientApplication.ts:887:1)
    at ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.ts:870:1)
    at PublicClientApplication.<anonymous> (ClientApplication.ts:282:1)
    at step (theme.ts:95:1)
    at Object.next (theme.ts:95:1)
    at theme.ts:95:1

### Msal Logs

[Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - logoutRedirect called
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - initializeLogoutRequest called
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - The ID Token Claims tied to the provided account do not contain a login_hint claim, logoutHint will not be added to logout request
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Setting postLogoutRedirectUri to configured uri
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - initializeServerTelemetryManager called
msal.ts:51 [Wed, 22 Mar 2023 01:55:56 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:logoutStart
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Setting active account to null
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : @azure/msal-browser@2.34.0 : Verbose - setActiveAccount: No account passed, active account not set
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Cleared cache items belonging to the account provided in the logout request.
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - getClientConfiguration called
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - getDiscoveredAuthority called
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Creating discovered authority with configured authority
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Attempting to get cloud discovery metadata in the config
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Known Authorities: redacted.b2clogin.com
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Authority Metadata: N/A
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Canonical Authority: https://redacted.b2clogin.com/redacted.onmicrosoft.com/b2c_1a_userinfo_signup_signin/
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Found cloud discovery metadata in the config.
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : @azure/msal-browser@2.34.0 : Verbose - PerformanceClient: Emitting performance events
msal.ts:54 [Wed, 22 Mar 2023 01:55:56 GMT] : [199f7e60-a323-4ab8-b337-25faf9d99d3a] : msal.js.browser@2.34.0 : Verbose - Auth code client created
msal.ts:51 [Wed, 22 Mar 2023 01:55:56 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:logoutSuccess

### MSAL Configuration

```javascript
export const MSAL_CONFIG: Configuration = {
  auth: {
    clientId: process.env.REACT_APP_AD_B2C_CLIENTID ?? "",
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: `${window.location.origin}/token`,
    postLogoutRedirectUri: window.location.origin,
  },
  cache: {
    cacheLocation: "localStorage", // We use localStorage since this persists between sessions. (We dont want users to constantly re-login)
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: true,
      loggerCallback: (level, message, containsPii) => {
        /*
        if (containsPii) {
          return;
        }
        */
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
export function initiateLogoutRequest(): Promise<void> {
  const request: EndSessionRequest = {
    account: msal.getActiveAccount(),
  };

  return msal.logoutRedirect(request);
}
```

### Reproduction Steps

1. Log in via redirect
2. handle redirect via the correct API `handleRedirectPromise`
3. Log out via logoutRedirect as above.

### Expected Behavior

It should remove the msal.interaction.status from session storage.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

N/A

### Source

External (Customer)

**Comment by TylerBurnett** [comment] 2023-03-22 02:54
For react compadre's chuck this on the page that you land on after redirection.
```
  // Workaround for MSAL issue, see below.
  // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5807
  useEffect(() => {
    const itemKey = "msal.interaction.status";
    if (sessionStorage.getItem(itemKey)) {
      sessionStorage.removeItem(itemKey);
    }
  }, []);
  ```

**Comment by konstantin-msft** [comment] 2023-03-22 15:34
Hi @TylerBurnett.
Can you please share verbose MSAL logs for the login redirect flow as well? This should help me to figure out why `msal.interaction.status` was not cleared after login.

**Comment by TylerBurnett** [comment] 2023-03-22 23:02
Hell, @konstantin-msft, thanks for looking into this, I appreciate it, as I mentioned above, I've been careful to ensure that the login redirect flow is not the cause of this issue. When I log in via the react app. There is no trace of the `msal.interaction.status` in session storage after the redirect handler has done its job. It only appears residually after logging out via redirect, I have verified this personally via watching session storage via dev tools. 


Regardless, I will honour your request, here are the logs from login-redirect.
```
[Wed, 22 Mar 2023 22:53:59 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:loginStart
Navigated to REDACTED
Navigated to http://localhost:3000/token
msal.ts:48 [Wed, 22 Mar 2023 22:54:03 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectStart
msal.ts:48 [Wed, 22 Mar 2023 22:54:03 GMT] : [2ad0613c-36c2-4820-81e4-2393ca45cce4] : @azure/msal-common@11.0.0 : Info - in acquireToken call in auth-code client
msal.ts:48 [Wed, 22 Mar 2023 22:54:03 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:loginSuccess
[Wed, 22 Mar 2023 22:54:03 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectEnd
```

I understand I may be barking up the wrong tree here, but the code in the library clearly sets interaction status to true, with no intention of removing it after the logout redirection has occurred as you can see in the above code.

**Comment by TylerBurnett** [comment] 2023-03-22 23:47
Had a bit more of a check to verify if I had missed something. I'm starting to become certain that the code is incorrect. If you have a look at the gif below, as I suspected the code is purposefully checking the interaction status is set to `true` before it navigates off of the page. I had a dig further into the `await this.navigationClient.navigateExternal(logoutUri, navigationOptions);` and it has no responsibility to reset the interaction status. Seeing as after line 306 you are sent off the page, the return never occurs which is of course another issue in the code.

![InterractioInProgress](https://user-images.githubusercontent.com/11090043/227062722-c5f05940-ff7a-4b4b-b108-db85ece973b2.gif)


I may get to wear a dunce hat for missing the point here. But I am feeling quite confident the code should be:
```
// https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c72bd52d91e01ad36ce4d0e89a25530ccc9ab996/lib/msal-browser/src/interaction_client/RedirectClient.ts#L301-L308
 else {
                // Ensure interaction is not in progress
                if (this.browserStorage.getInteractionInProgress()) {
                    this.browserStorage.setInteractionInProgress(false);
                }
                await this.navigationClient.navigateExternal(logoutUri, navigationOptions); <-- this will never return due to navigation.
            }
```

instead of:

```
// https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c72bd52d91e01ad36ce4d0e89a25530ccc9ab996/lib/msal-browser/src/interaction_client/RedirectClient.ts#L301-L308
 else {
                // Ensure interaction is in progress
                if (!this.browserStorage.getInteractionInProgress()) {
                    this.browserStorage.setInteractionInProgress(true);
                }
                await this.navigationClient.navigateExternal(logoutUri, navigationOptions);
                return;
            }
```

**Comment by TylerBurnett** [comment] 2023-03-23 00:01
Your tests also expect that `getInteractionInProgress()` is true after navigation. And then subsequently resets it inside of the test case?

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c4432b9cc711cc037261c815410433346836c95d/lib/msal-browser/test/interaction_client/RedirectClient.spec.ts#L2104-L2117

Is this a bug or are the docs missing something I need to do after the logout redirect has occurred?

**Comment by konstantin-msft** [comment] 2023-03-23 18:17
@TylerBurnett Thanks for providing the additional details!
Unfortunately, I wasn't able to reproduce the error. It looks like you are using `msal-browser` instead of `msal-react` to run react SPA. We recommend the latter as it helps you to handle the response of a redirect under the hood. It does clean all temporary cache items for the interaction type, including `msal.interaction.status` key. Please see https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#how-do-i-handle-the-redirect-flow-in-a-react-app for details. If you would really like to keep using `msal-browser` to run react SPA you should consider mimicking the following code https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/src/MsalProvider.tsx#L132.
FYI: we don't recommend direct msal cache manipulations to avoid any unexpected errors.

Please let me know if that helps. Should you have any questions please reach out.

**Comment by TylerBurnett** [comment] 2023-03-23 23:57
Hello, while I appreciate you providing some information on a workaround (which I had already created). This is not about just fixing my issue, this is a bug in your code! I am not using the react skew of your library since it relies on react context, I do not use context I use redux. I wanted to keep authentication data in the state which is why I decided upon the browser skew. 

regarding not being able to replicate the issue, yes. it could appear that way for two factors. 
1. the samples for the browser lib have not been kept in line with their respective versions. See https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TestingSample/app/index.html#L8
2. the application is one page only and always calls `handleRedirectRequest` on page load. 

After mitigating the first issue, the logs clearly show `handleRedirectRequest` as mentioned in issue 2 catching on the bug where it would expect an actual redirect from a log-in to occur.
```
authConfig.js:26 [Thu, 23 Mar 2023 23:49:56 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:26 [Thu, 23 Mar 2023 23:49:56 GMT] : [f6c9a2a7-55d5-4942-b2a8-18b4226a1765] : msal.js.browser@2.34.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
authConfig.js:26 [Thu, 23 Mar 2023 23:49:56 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectEnd
```

Breaking down these logs respective to the function call, it is clear that a session from MSAL exists in this case due to the fact you need to go through here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/55d5d6fa47dc60a15db7e76c8fa9bf6245238428/lib/msal-browser/src/interaction_client/RedirectClient.ts#L101-L104

To get here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/55d5d6fa47dc60a15db7e76c8fa9bf6245238428/lib/msal-browser/src/interaction_client/RedirectClient.ts#L109

To make my point even clearer. Your test cases actually used to be correct. Please refer to this git commit:
https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/191577ecc2320cf3c212a40ac1ce28513131384e

As you can see, the test case used to verify that the interaction in progress was in fact false. It no longer does this which is incorrect. Coming back to your point about modifying the MSAL cache directly, of course, you wouldn't suggest it as good practice because it shouldn't be my responsibility to reset it. It is a bug in the library! 

Can this please be triaged for the issue it is and move on, I would be inclined to even create a PR for it if you could just verify that this is unintended functionality. I apologise for being blunt, but I am starting to get impatient with the fact I have provided you with overwhelming evidence that this needs to be fixed.

**Comment by hectormmg** [comment] 2023-03-27 16:07
Hi, @TylerBurnett. When you say:
> After mitigating the first issue, the logs clearly show handleRedirectRequest as mentioned in issue 2 catching on the bug where it would expect an actual redirect from a log-in to occur.

What exactly do you mean? The logs show the message " handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache." Is that what you mean by "catching on the bug"? If so, this log message is actually evidence that the logout flow works as expected, given that "did not detect a response hash" means it's not a login call, but a logout call, hence MSAL doesn't have to do much other than clearing the temporary cache (including the interaction in progress flag).

`handleRedirectPromise` is called at the top of the page in our samples because once MSAL navigates away from the page (whether for login or logout), execution ends and in-memory context is lost. MSAL leverages the temporary cache and the URL hash when coming back from a redirect to rebuild said context. This is why the logout method MUST turn the interaction in progress ON before finishing its execution and has an empty return. It is `handleRedirectPromise`'s responsibility to clear the cache, not `logoutRedirect`'s.

**Comment by TylerBurnett** [comment] 2023-04-10 23:23
Hello @hectormmg,

Responding to:
> What exactly do you mean? The logs show the message " handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache." Is that what you mean by "catching on the bug"? If so, this log message is actually evidence that the logout flow works as expected, given that "did not detect a response hash" means it's not a login call, but a logout call, hence MSAL doesn't have to do much other than clearing the temporary cache (including the interaction in progress flag).

 Yes. I'd agree with this if your examples listed here actually mentioned this. But they do not.
https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2#sign-out-with-a-redirect

Responding to your point on:
> MSAL leverages the temporary cache and the URL hash when coming back from a redirect to rebuild said context. This is why the logout method MUST turn the interaction in progress ON before finishing its execution and has an empty return. It is handleRedirectPromise's responsibility to clear the cache, not logoutRedirect's.

For other flows, I would assume yes, for logout redirect, No. The user's cache is entirely wiped before they leave the page in the log-out redirect flow. All the handle re-direct response does in this context is remove the final piece which is the ever-so-frustrating interaction in the progress piece. See below for code context in the lib:

This is where the user's information is entirely wiped in the logout flow, well before any redirect or other logic:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/629883fbfe597b56260483e4567bacd9ae9ba81d/lib/msal-browser/src/interaction_client/RedirectClient.ts#L270

This is the base interaction client where the previous call actually points to:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/629883fbfe597b56260483e4567bacd9ae9ba81d/lib/msal-browser/src/interaction_client/BaseInteractionClient.ts#L50-L74

As I've mentioned before. The job is already entirely done. The use of interaction in progress in this context is essentially useless. If you look at this commit which I've mentioned before https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/191577ecc2320cf3c212a40ac1ce28513131384e.  Prior to this commit all of this code used to work fine without `interractionInProgress` existing in the flow.

The change has created inflexibility in the library that honestly is relatively unnecessary. I'm not saying you should roll back every piece of `interactionInProgress` functionality. But I think we can assert quite safely that someone is being logged out after you forcibly send them off the page back to the tenant, like the code used to assume.

The way that I ran into this issue is because the page that manages redirection for my site is in fact a completely separate page. such as: `https://app.test/redirect` alongside the docs indicating that this shouldn't be an issue, it's also quite unfair to expect that `handleRedirect` is called every time a page loads on any part of the site whatsoever.

**Comment by tnorling** [comment] 2023-04-11 16:59
> Yes. I'd agree with this if your examples listed here actually mentioned this. But they do not.
https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2#sign-out-with-a-redirect

Thanks for bringing that to our attention, we'll make sure these docs get updated. @derisen is this something you can help with?

> As I've mentioned before. The job is already entirely done. The use of interaction in progress in this context is essentially useless. If you look at this commit which I've mentioned before https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/191577ecc2320cf3c212a40ac1ce28513131384e. Prior to this commit all of this code used to work fine without interractionInProgress existing in the flow.

The behavior is intentional and the change you referenced was done for a very important reason. Many apps will invoke login when no user is signed in, so previously when logout was invoked the cache would be cleared and the app would immediately invoke login which would result in a race between the loginRedirect and the redirect to the logout page. To prevent this, we made the change to set the interaction_in_progress flag on logout which would block other interactive APIs from being invoked until the logout was complete (including redirection to the logout page and back).

> The way that I ran into this issue is because the page that manages redirection for my site is in fact a completely separate page. such as: https://app.test/redirect alongside the docs indicating that this shouldn't be an issue, it's also quite unfair to expect that handleRedirect is called every time a page loads on any part of the site whatsoever.

`handleRedirectPromise` should be invoked on every page that may invoke an interactive API, this has always been the recommended practice but I do apologize that this was not made more clear in the docs you referenced, like I mentioned above we will take this feedback and see what we can do to improve the docs around this.

**Comment by derisen** [comment] 2023-04-12 00:47
> > Yes. I'd agree with this if your examples listed here actually mentioned this. But they do not.
> > https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2#sign-out-with-a-redirect
> 
> Thanks for bringing that to our attention, we'll make sure these docs get updated. @derisen is this something you can help with?

@TylerBurnett apologies for the confusion, will make sure to link to redirect API guideliness in these docs cc @tnorling

**Comment by TylerBurnett** [comment] 2023-04-12 03:12
Thanks,
Referencing my comments and the logs in my original issue. There's nothing in the logs that actually indicate that something has been missed. The logs in fact mention that the logout was a complete success. 

Maybe some adjustment to these logs so they closely match that of the Log-in redirect would help make this more indicative?

**Comment by tnorling** [comment] 2023-04-12 18:49
Noted. I appreciate the feedback, we'll see what we can do. Closing for now but please let us know if you have further questions. Thanks!

**Closed as completed by tnorling** 2023-04-12 18:49 UTC
Labels: question, b2c, msal-browser, bug-unconfirmed, public-client

**Comment by NikxDa** [comment] 2023-08-04 14:44
@tnorling @TylerBurnett Thought I'd tag you since you were the primary people looking at the problem as far as I can see.

I'm facing a very similar problem; I am calling `logoutRedirect`, but after having successfully logged out, I still have a value with key `msal.interaction.status` in my session storage.

I am returning to a different page upon logout, but both the page starting the logout process as well as the page being redirected to call `handleRedirectPromise`.

I can of course manually remove the session storage entry, but that feels rather hacky. Any suggestions here? I read the above conversation, but I can't really make out whether the behavior I am seeing is intended or not after all. Currently, after having logged out, I cannot log back in, because login complains there's an interaction in progress...

**Comment by kevinBonkewitzz** [comment] 2023-09-08 21:52
> For react compadre's chuck this on the page that you land on after redirection.
> 
> ```
>   // Workaround for MSAL issue, see below.
>   // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5807
>   useEffect(() => {
>     const itemKey = "msal.interaction.status";
>     if (sessionStorage.getItem(itemKey)) {
>       sessionStorage.removeItem(itemKey);
>     }
>   }, []);
> ```

For anyone having this issue with SvelteKit-  upgraded 'msal-browser' from v2.30.0 to v3.0.2 and had the 'Interaction_in_progress' error appear when attempting to sign-out. Waiting for 'handleRedirectPromise' kept resolving as null and thus -again- returning the same error.

Implementing Tyler's code in an event and on a component that is available post-redirection (like the global layout.svelte component) seems to fix the issue.
```
	const itemKey = 'msal.interaction.status';
	if (sessionStorage.getItem(itemKey)) {
		sessionStorage.removeItem(itemKey);
	}
```

**Comment by PhoneixS** [comment] 2024-09-02 12:32
For others who found this issue with modern standalone components, you could add `handleRedirectObservable()` to the app.component.ts as suggested in [Redirects with standalone components](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md#redirects-with-standalone-components).
