### ISSUE TITLE
How to debug AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request errors?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2694] opened 2020-12-03 23:55 UTC
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.6.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We see quite a few logs showing this error
AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request

an example one with correlation id and trace id 
501481 - [2020-12-03 19:34:01Z]: AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request. Trace ID: 4dca72dd-f02e-4615-b1c9-e226952f2200 Correlation ID: 0a49cdbc-2e94-4089-bc6f-1162b123592c Timestamp: 2020-12-03 19:34:01Z - Correlation ID: 0a49cdbc-2e94-4089-bc6f-1162b123592c - Trace ID: 4dca72dd-f02e-4615-b1c9-e226952f2200

I understand the error is coming from the service, what can I do to debug this error and figure out why it is happening?

Thank you!

**Comment by tnorling** [comment] 2020-12-04 00:32
Closing as duplicate of #2691, also may be related to #2690

**Closed by tnorling** 2020-12-04 00:32 UTC
Labels: question
