### ISSUE TITLE
ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint when doing a nested http request

### ISSUE THREAD

**Issue by bladmorenoacn** [AzureAD/microsoft-authentication-library-for-js#3321] opened 2021-03-27 02:44 UTC
## Library

- [X] `msal@1.4.4`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.1.2`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [X] Angular
- [ ] React
- [ ] Other

## Description
Aftert to get and configure the MSAL from the base configuration file, I made to a protected API where the Configuration Values for the application are present, I am not able to do the  request due to the following error, although the MSAL has all the configurations and values necesary for the request.

## Error Message
```
core.js:5980 ERROR Error: Uncaught (in promise): ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint
ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint
    at ClientAuthError.AuthError [as constructor] (AuthError.js:22)
    at new ClientAuthError (ClientAuthError.js:100)
    at Function.push.7ZR7.ClientAuthError.createUserLoginRequiredError (ClientAuthError.js:149)
    at MsalService.<anonymous> (UserAgentApplication.js:566)
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at Module.__awaiter (tslib.es6.js:70)
    at UserAgentApplication.js:544
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28282)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)
```

## MSAL Configuration

```js
"msal": {
        "auth": {
            "authority": "https://login.microsoftonline.com/XXXXXX-XXXX-XXXX-86db-322b19a65a22",
            "clientId": "XXXXXXX-XXXX-XXXXX-b357-8e4cf97e4cc2",
            "redirectUri": "https:/XXXXXXX.accenture.com"
        },
        "system": {
            "loadFrameTimeout": 200000
        },
        "consentScopes": [
            "user.read",
            "openid",
            "profile"
          ],
        "protectedResourceMap": [
                "https://XXXXXXX.accenture.com/api/v1",
                [
                    "user.read",
                    "openid",
                    "profile"
                ],"https://graph.microsoft.com/beta/",
                [ "user.read",
                    "openid",
                    "profile"
                ]
            ]
    },
```

## Reproduction steps
It happens when I do a nested request through httpClient in the App Initializer method
**angular.module.ts**
```js
provide: APP_INITIALIZER,
      useFactory: (config: AppConfigService) => () => config.load(),
      deps: [AppConfigService], multi: true
```

**AppConfigService.ts**

```js

 constructor(private readonly httpHandler: HttpBackend, private httpClient: HttpClient) {
    this.httpClientBack = new HttpClient(httpHandler);
  }

  public load(): Promise<boolean> {
    return new Promise<boolean>((resolve, reject) =>{
      this.httpClientBack.get(AppConfigService.configPath).toPromise().then(initConf =>{
         this.config =  initConf;
         this.httpClient.get(this.config.CIOuhConfigurationVariablesAPIAdminUI).toPromise().then(confData => {
            let confDataObj = <any>confData;
            let configItem = confDataObj.ConfigItems.Configurations.ConfigItemValue;
            let configItemObj = JSON.parse(configItem);
            let configUI = Object.assign({},this.config, configItemObj);
            this.config = configUI;
            sessionStorage[AppConfigService.configPath] = JSON.stringify(configItemObj);
            resolve(true);
          }
        );
      });
    });
}
```
**auth.module.ts**
```js
import { NgModule, ModuleWithProviders, InjectionToken } from '@angular/core';

import {
  MsalModule,
  MsalInterceptor,
  MsalGuard,
  MSAL_CONFIG,
  MsalService,
  MSAL_CONFIG_ANGULAR,
  MsalAngularConfiguration,
} from '@azure/msal-angular';
import { AppConfigService } from '../services/app-config.service';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { environment } from '../../../environments/environment';
import { LoggingService } from '../services/logging.service';
import { Configuration } from 'msal';

export const AUTH_GUARD = new InjectionToken<string>('AUTH_GUARD');


/*
  When running locally `npm run start:local` or `npm run test` or `npm run e2e`
  use mock values, to turn off security.  This is set at build time.
*/

export const PROVIDERS = {
  mock: [
    {
      provide: MSAL_CONFIG,
      useValue: { client: 'mock', authority: 'mock' }

    },
    {
      provide: AUTH_GUARD,
      useValue: emptyGuard
    },
    {
      provide: MsalService,
      useFactory: () => { }
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useValue: {},
    },
  ],
  app: [
    {
      provide: MSAL_CONFIG,
      useFactory: AuthConfigFactory,
      deps: [AppConfigService]
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: MSALAngularConfigFactory,
      deps: [AppConfigService],
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    { provide: AUTH_GUARD, useClass: MsalGuard },
    MsalService

  ]
};

@NgModule({
  imports: [MsalModule]
})

export class AuthModule {
  static forRoot(): ModuleWithProviders<AuthModule> {
    return {
      ngModule: AuthModule,
      providers: PROVIDERS[environment.providers]
    };
  }
}


export function AuthConfigFactory(config: AppConfigService): Configuration {
  const isIE = config.isIE();
  const cfg = Object.assign({}, config.config.msal, {
    cache: {
      cacheLocation:isIE?'localStorage':'sessionStorage',
     // storeAuthStateInCookie: isIE
    }
  });

  return cfg;
}

export function MSALAngularConfigFactory(
  config: AppConfigService
): MsalAngularConfiguration {

  const cfg = Object.assign({
    protectedResourceMap:  new Map(Object.entries(config.getConfig().msal.protectedResourceMap)) }
    //popUp: !isIE
    );
  return cfg || {};
}




export function emptyGuard(
  route: ActivatedRouteSnapshot,
  state: RouterStateSnapshot
) {
  return true;
}
```
## Expected behavior

After to load the MSAL configurations from config.json, being able to request to the API included in the protectedResourceMap, the access_token is needed in order to access the ConfigurationAPI, to retrieve the configurations of the rest of the application.

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by jasonnutter** [comment] 2021-03-29 16:53
Closing as duplicate of #3317, will address issue there.

**Closed by jasonnutter** 2021-03-29 16:53 UTC
Labels: bug-unconfirmed, msal-angular, msal@1.x, question
