### ISSUE TITLE
Cannot find module '@azure/msal-common' and  '@azure/msal-angular' or its corresponding type declarations.

### ISSUE THREAD

**Issue by hansakaRightS** [AzureAD/microsoft-authentication-library-for-js#6310] opened 2023-08-09 07:41 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

```
import { MsalService } from '@azure/msal-angular';
                            ^^^^^^^^^^^^^^^^^^
import { AuthenticationResult, InteractionRequiredAuthError } from '@azure/msal-common';
                                                                   ^^^^^^^^^^^^^^^^^^^^
                                                                                                           
```

we can not import the `MsalService` from `@azure/msal-angular`.
we noticed this error few hours ago. we are using angular 16.

we also tried following versions. and its same for all those versions.
```
    "@azure/msal-angular": "^3.0.0",
    "@azure/msal-browser": "^3.0.0",
   ```
   ```
    "@azure/msal-angular": "^3.0.0-alpha.2",
    "@azure/msal-browser": "^3.0.0-alpha.2"
```
   ```
    "@azure/msal-angular": "^3.0.0-beta.1",
    "@azure/msal-browser": "^3.0.0-beta.1"
```

### Error Message

Cannot find module '@azure/msal-angular' or its corresponding type declarations.

### Msal Logs

-

### MSAL Configuration

```javascript
{
auth: {
        clientId: clientId,
        authority: "B2C_1A_SIGNUP_SIGNIN",
        redirectUri: '/',
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "LocalStoarage",
        storeAuthStateInCookie: false
    }
}
```

### Relevant Code Snippets

```javascript
import { MsalService } from '@azure/msal-angular';
import { AuthenticationResult, InteractionRequiredAuthError } from '@azure/msal-common';
```

### Reproduction Steps

1. npm i @azure/msal-browser
2. npm i @azure/msal-angular
3. import { MsalService } from '@azure/msal-angular'; to the service.
4. import { AuthenticationResult, InteractionRequiredAuthError } from '@azure/msal-common';

### Expected Behavior

Should be able to use `MsalService` from `'@azure/msal-angular'`

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by khamui** [comment] 2023-08-09 08:35
same here! is there already a workaround?

**Comment by michaelmairegger** [comment] 2023-08-09 08:36
The release version has this issue too, not only 3.0.0-alpha.0 as the issue owner stated

**Comment by hansakaRightS** [comment] 2023-08-09 08:39
```
    "@azure/msal-angular": "3.0.0-alpha.0",
    "@azure/msal-browser": "3.0.0-alpha.0",
    ```
    we updated the packages like this and installed the `npm i @azure/msal-common` seems to get rid of the error.

**Comment by khamui** [comment] 2023-08-09 08:49
thanks! downgrading to `3.0.0-alpha.0` worked for me. Even without installing `@azure/msal-common`.

**Comment by greut** [comment] 2023-08-09 10:10
the content of the package seems borked, https://app.renovatebot.com/package-diff?name=@azure%2fmsal-angular&from=3.0.0-beta.1&to=3.0.0

**Comment by hansakaRightS** [comment] 2023-08-09 11:06
any permanent solution for this?

this is how its looks like in the node modules. with the version `3.0.0`
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/121548903/2095f3e0-1636-45ea-8e55-e9881b536231)

**Comment by ghost** [comment] 2023-08-09 11:06
It's broken, do not use version ^3.0.0 right now, this fix the issue for now:
    "@azure/msal-angular": "3.0.0-beta.1",
    "@azure/msal-browser": "3.0.0-beta.1",

**Comment by sandrooco** [comment] 2023-08-09 13:17
Wow, they really shit the bed.. see also https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5410

**Comment by Core121** [comment] 2023-08-09 14:42
Getting the same error on 3.0.0, beta version works fine. Looks like they published incorrectly

**Comment by jo-arroyo** [comment] 2023-08-09 18:57
@HansakaSS Thanks for raising this issue. There has been an error in our release process and we are currently working on a fix. Thank you all for your patience.

**Comment by mcavazotti** [comment] 2023-08-09 20:36
Getting same error, but only for msal-angular 3.0.0

**Comment by hansakaRightS** [comment] 2023-08-10 10:49
also mentioned here #6323

**Comment by achrysanthakopoulou** [comment] 2023-08-10 10:57
> It's broken, do not use version ^3.0.0 right now, this fix the issue for now: "@azure/msal-angular": "3.0.0-beta.1", "@azure/msal-browser": "3.0.0-beta.1",

Yes, beta.1 seems to be working fine BUT when build runs on azure pipelines or docker (node:18.13-alpine, nginx:1.20.0-alpine), it still throws the same error!
I also reproduced it at angular16-sample-app.

**Comment by achrysanthakopoulou** [comment] 2023-08-10 13:46
Oh my. The answer was in front of my eyes!
It was working fine locally due to installing the exact version with npm install.
However, package.json indicated the package as "^3.0.0-beta.1" and not "3.0.0-beta.1" ... I removed the ^ and it worked!

**Comment by julianf-dev** [comment] 2023-08-10 22:24
I have tthe same problem, i tried to come backo to "  "@azure/msal-angular": "3.0.0-alpha.0",
    "@azure/msal-browser": "3.0.0-alpha.0", but didn't work.
Another problem is that when I upload to production the MSAL package does not download.

**Comment by tnorling** [comment] 2023-08-14 18:19
A fix for this was released last week in versions 3.0.1 of msal-browser and 2.0.1 of msal-angular. Let us know if this is still an issue, thanks!

**Comment by bookmountain** [comment] 2023-08-17 08:02
Can confirm that the bug in react version is still there
```
"@azure/msal-browser": "3.0.1",
"@azure/msal-react": "2.0.1",
```
another issue is that `source-map-loader` shows the warning message, we need to ignore the warning message by the following workaround. 
[fix: ignore webpack warnings by source-map-loader #11752](https://github.com/facebook/create-react-app/pull/11752)

**Comment by achrysanthakopoulou** [comment] 2023-08-17 14:20
Not sure if we have to add those:
"@azure/msal-browser": "3.0.1",
"@azure/msal-angular": "2.0.1",

or those:
"@azure/msal-browser": "3.0.1",
"@azure/msal-angular": "3.0.1",

in our package.json .

Anyway, none of those works:
With 3.0.1 with 2.0.1 versions I get a peer dependency error (I guess the versions should match anyways).
With 3.0.1 versions I get a runtime error that was not there before:
""AADB2C90012: The scope '[a-custom-b2c-scope-here] openid profile offline_access' provided in request is not supported.
Correlation ID: f33ed4a2-4db0-43fa-a734-f7f27586b632
Timestamp: 2023-08-17 14:16:42Z"

**Comment by michaelmairegger** [comment] 2023-08-17 15:35
I have the same error with _AADB2C90012_, but ony when authenticating against **Azure B2C**, not when autenticating against **Azure AD**

**Comment by achrysanthakopoulou** [comment] 2023-09-04 09:33
Any update on the error I have described? Indeed, this is happening on azure b2c.

> Not sure if we have to add those: "@azure/msal-browser": "3.0.1", "@azure/msal-angular": "2.0.1",
> 
> or those: "@azure/msal-browser": "3.0.1", "@azure/msal-angular": "3.0.1",
> 
> in our package.json .
> 
> Anyway, none of those works: With 3.0.1 with 2.0.1 versions I get a peer dependency error (I guess the versions should match anyways). With 3.0.1 versions I get a runtime error that was not there before: ""AADB2C90012: The scope '[a-custom-b2c-scope-here] openid profile offline_access' provided in request is not supported. Correlation ID: f33ed4a2-4db0-43fa-a734-f7f27586b632 Timestamp: 2023-08-17 14:16:42Z"

**Comment by michaelmairegger** [comment] 2023-09-04 11:30
Using 3.0.2 and Azure B2C works on my projects

**Comment by sandrooco** [comment] 2023-09-06 13:24
@tnorling Yes it is indeed still a problem.
The contents of `node_modules@azure/msal-angular` only consist of LICENSE, readme.md and package.json.

**Comment by Cotspheer** [comment] 2023-10-02 09:52
Same here, any updates? Using the angular-standalone-sample and Node 18.8.0.

``` json
{
  "name": "angular-standalone-sample",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "jest"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.1.5",
    "@angular/common": "^16.1.5",
    "@angular/compiler": "^16.1.5",
    "@angular/core": "^16.1.5",
    "@angular/forms": "^16.1.5",
    "@angular/material": "^16.1.5",
    "@angular/platform-browser": "^16.1.5",
    "@angular/platform-browser-dynamic": "^16.1.5",
    "@angular/router": "^16.1.5",
    "@azure/msal-angular": "^3.0.4",
    "@azure/msal-browser": "^3.1.0",
    "@azure/msal-node": "^2.1.0",
    "rxjs": "~7.8.0",
    "ts-node": "^10.9.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.4",
    "@angular/cli": "~16.1.4",
    "@angular/compiler-cli": "^16.1.5",
    "@types/jasmine": "~4.3.0",
    "@types/jest": "^29.5.0",
    "e2e-test-utils": "^0.0.1",
    "jasmine-core": "~4.5.0",
    "jest": "^29.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ts-jest": "^29.1.0",
    "typescript": "~4.9.4"
  }
}
```
@azure/msal-angular nor @azure/msal-browser are within node_modules.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/4779528/05d240f3-b4b6-4c4b-aa7d-785c8fd86d6f)

**Comment by hansakaRightS** [comment] 2023-10-02 11:57
```
    "@azure/msal-angular": "3.0.4",
    "@azure/msal-browser": "3.1.0",

we are using this version with node `v18.17.1`. i can confirm this is working fine.

**Comment by HansakaSS** [comment] 2023-10-02 11:59
s

**Closed as completed** 2023-10-02 16:31 UTC
Labels: question, b2c, msal-angular, msal-browser, bug-unconfirmed, public-client

**Comment by ghost** [comment] 2023-12-20 12:37
> Can confirm that the bug in react version is still there
> 
> ```
> "@azure/msal-browser": "3.0.1",
> "@azure/msal-react": "2.0.1",
> ```
> 
> another issue is that `source-map-loader` shows the warning message, we need to ignore the warning message by the following workaround. [fix: ignore webpack warnings by source-map-loader #11752](https://github.com/facebook/create-react-app/pull/11752)

I can confirm that I am still finding this issue in react

**Comment by sirajalam049** [comment] 2024-02-20 09:58
This is really pathetic. It's feb 2024, and the error is still there.

    "@azure/msal-browser": "^3.10.0",
    "@azure/msal-react": "^2.0.12",

<img width="1157" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/22110988/d6e1c076-7c04-4afc-8df7-f0501f040bdd">

**Comment by ghost** [comment] 2024-02-20 10:08
> This is really pathetic. It's feb 2024, and the error is still there.
> 
> ```
> "@azure/msal-browser": "^3.10.0",
> "@azure/msal-react": "^2.0.12",
> ```
> 
> <img alt="image" width="1157" src="https://private-user-images.githubusercontent.com/22110988/306217057-d6e1c076-7c04-4afc-8df7-f0501f040bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjM5NDIsIm5iZiI6MTcwODQyMzY0MiwicGF0aCI6Ii8yMjExMDk4OC8zMDYyMTcwNTctZDZlMWMwNzYtN2MwNC00YWZjLThkZjctZjA1MDFmMDQwYmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEwMDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZjFkYmEyODQwNjNiMmQyMDg3YjllZmUyYzI1MjQzZDU0NTk5NWU0NjI3MTgzZGE1M2MwMDBjNjYxODY2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnrwOXU_6LuPUYW2N7XQb6fVqxBLB8tXHkEgTvmsP_g">

The current workaround for this issue is using the beta version for msal browser: 
"@azure/msal-browser": "3.0.0-beta.1",
"@azure/msal-common": "^14.5.0",
"@azure/msal-react": "2.0.8",

**Comment by BartusZak** [comment] 2024-05-13 13:29
Samples provided in source code does now work.
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples

2 kind of exceptions exists:

1. Conflicting peer dependencies when trying to use most bumped answer versions https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6310#issuecomment-1953876010
2. Can't resolve `@azure/msal-browser` / `@azure/msal-react` when using source code examples

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/16143176/7a95d137-5b63-49f4-92f7-c581389eac92)
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/16143176/8682619c-a776-4d58-b86f-0adccd8aafe7)

Tested with 
Node: v18.19.1
npm: 10.2.4

Any hints how to make it work?

**Comment by BartusZak** [comment] 2024-05-13 14:28
Its funny but I cloned whole repo once again and moved `react-router-sample` example to separate directory on my desktop and triggered `npm i` and its working 😠 

 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/16143176/0a0fc7a6-67af-4918-b332-6a463f2cb1c0)

**Comment by danstraughn** [comment] 2024-08-22 14:15
> ```
>     "@azure/msal-angular": "3.0.4",
>     "@azure/msal-browser": "3.1.0",
> 
> we are using this version with node `v18.17.1`. i can confirm this is working fine.
> ```

Can confirm changing the versions to above works, finally:

Change: package.json ->
"@azure/msal-angular": "3.0.4",
"@azure/msal-browser": "3.1.0",

npm install
npm run build
npm run start

Angular 18 stand alone site is up and functioning.
