### ISSUE TITLE
AcquireTokenSilent Behavior with Apollo Client setContext

### ISSUE THREAD

**Issue by othpwn** [AzureAD/microsoft-authentication-library-for-js#4696] opened 2022-04-08 14:36 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Description

Hello,

I am using Apollo Client to manage the state of my react app.
However, when I want to acquire a token to authenticate my requests, it results in infinite loop of requests from Apollo Client.
I tried to debug the code, and it appears that this happen when I call **instance.acquireTokenSilent**.
But all those requests are authenticated. I just don't know why there are infinite requests, knowing that without the acquireTokenSilent call, and if I put the token directly into the authorization header, everything works fine.

### MSAL Configuration

```javascript
auth: {
    clientId: "clientId",
    authority:
      "https://login.microsoftonline.com/tenantId",
    // redirectUri: "http://localhost:3000/",
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
```

### Relevant Code Snippets

```javascript
const AsyncTokenLookup = async () => {
      const accounts = await instance.getAllAccounts();

      const account = get(accounts, "[0]");
      if (account && inProgress === "none") {
        try {
          const result = await instance.acquireTokenSilent({
            ...loginSilentRequest,
            account,
          });
          return result.accessToken;
        } catch (err) {
          if (err instanceof InteractionRequiredAuthError) {
            // fallback to interaction when silent call fails
            return instance.acquireTokenRedirect(loginRequest);
          }
        }
      }
      return;
    };
    const withToken = setContext(async (_, { headers }) => {
      const my_token = await AsyncTokenLookup();
      return {
        headers: {
          ...headers,
          Authorization: my_token ? `Bearer ${my_token}` : null,
        },
      };
    });
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by othpwn** [comment] 2022-04-08 14:47
I went back to "@azure/msal-browser": "2.14.2" and "@azure/msal-react": "1.0.0" and the issue is gone. I think the behavior of acquireTokenSilent was changed and didn't work well with Apollo

**Comment by ellymakuba** [comment] 2022-04-08 15:46
@othpwn please provide verbose MSAL logs when it loops and when also when it doesn't

**Comment by othpwn** [comment] 2022-04-12 17:35
Here is the log I got, it keep looping between msal:acquireTokenStart msal:acquireTokenSuccess:

[Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : [fbea0831-737d-42db-8b24-b9ce26905408] : msal.js.browser@2.23.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectEnd
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-react@1.3.2 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
auth-config.js:26 [Tue, 12 Apr 2022 17:34:05 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart

**Comment by jasonnutter** [comment] 2022-04-12 22:55
@othpwn Does the behavior you observe match what is described here (i.e. does it work with 1.3.0 but not the latest)? https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4701#issuecomment-1095531435

**Comment by othpwn** [comment] 2022-04-12 23:00
Indeed, it works with 1.3.0 but not the latest.

**Comment by jasonnutter** [comment] 2022-04-12 23:01
Thanks for confirming, will close as a duplicate of #4701.

**Closed as completed by jasonnutter** 2022-04-12 23:01 UTC
Labels: question, msal-browser, msal-react
