### ISSUE TITLE
Intermittent: After trying to log in, login pop-up not closing and inside that pop-up window application is rendering

### ISSUE THREAD

**Issue by bokipantic** [AzureAD/microsoft-authentication-library-for-js#5351] opened 2022-11-01 16:46 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

The issue is intermittent.
In login pop-up window the user typed valid credentials to log in his Microsoft account.
In most cases the user will successfully be logged in and pop-up will close.

However, sometimes login pop-up doesn't close and inside that pop-up window the user can use the same application.
I noticed that app is also running in the parent app window but user is not logged in.

Please could you help me to avoid this unexpected behavior?

### Error Message

No error message is displayed.

### MSAL Configuration

```javascript
const configuration = {
  auth: {
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: `${window.location.origin}/services/ApplicationCenter/blank.html`,
    clientId: process.env.REACT_APP_CLIENT_ID,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
  clientId: process.env.REACT_APP_CLIENT_ID,
};
```

### Relevant Code Snippets

```javascript
const configuration = {
  auth: {
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: `${window.location.origin}/services/ApplicationCenter/blank.html`,
    clientId: process.env.REACT_APP_CLIENT_ID,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
  clientId: process.env.REACT_APP_CLIENT_ID,
};
const requestScope = {
  scopes: ['openid',
    'profile',
    'offline_access',
    'User.Read.All',
    'Contacts.ReadWrite',
    'Presence.Read.All',
    'Team.ReadBasic.All',
    'GroupMember.Read.All',
  ],
};
const clientApp = new PublicClientApplication(configuration);
async function signIn() {
  const res = await clientApp.loginPopup(requestScope);
  // business logic
}
```

### Reproduction Steps

1. User clicks to log into application with his Microsoft account.
2. Pop-up window shows up and user enters valid credentials.
3. The pop-up does not close and inside that pop-up window application is rendering.

### Expected Behavior

After giving valid credentials the login pop-up window is always closing and user is logged into application.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment] 2022-11-01 19:19
@bokipantic this issue was fixed in MSAL Browser v 2.30.0, please upgrade to the newest version and let us know if your problem persists.

**Comment by bokipantic** [comment] 2022-11-02 18:25
@hectormmg I did as you suggested, but the issue still persists.
Any other bugfix please?

**Comment by bokipantic** [comment] 2022-11-07 11:09
Hi @hectormmg 
Please could you provide me with another fix for my bug?
Please respond, thanks in advance

**Comment by hectormmg** [comment] 2022-11-07 18:54
You can try increasing the frequency with which MSAL checks the hash by reducing the `pollIntervalMilliseconds` [system configuration option](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#system-config-options)

It is 30ms by default, you can try dropping it to 20 or 15ms and see if that works.

**Comment by bokipantic** [comment] 2022-11-13 18:38
The issue is still reproducible, but less often. I am waiting for additional QA team feedback.

**Comment by tnorling** [comment] 2022-11-14 23:27
@bokipantic When this happens does the URL of the popup window contain a hash? Also it appears you've set your redirectUri to blank.html (which is recommended) but you've also stated that your application is rendering in the popup, I'm a bit confused by that as these are mutually exclusive, can you clarify which it is?

**Comment by johnwhitehead91** [comment] 2022-11-21 09:41
We are also experiencing this issue.

**Comment by diamant-isufi-sveasolar** [comment] 2022-12-09 18:05
This issue happens here too, any solution @bokipantic @johnwhitehead91?

**Comment by diamant-isufi-sveasolar** [comment] 2022-12-12 03:38
> @bokipantic this issue was fixed in MSAL Browser v 2.30.0, please upgrade to the newest version and let us know if your problem persists.

hi @bokipantic I am still facing this issue

**Comment by diamant-isufi-sveasolar** [comment] 2022-12-12 03:40
@tnorling My issue contains a hash, could you provide some help?

**Comment by tnorling** [comment] 2022-12-12 17:04
@diamant-isufi-sveasolar Please open a new issue and we'd be happy to help you out

**Comment by bokipantic** [comment] 2023-01-04 13:48
> @bokipantic When this happens does the URL of the popup window contain a hash? Also it appears you've set your redirectUri to blank.html (which is recommended) but you've also stated that your application is rendering in the popup, I'm a bit confused by that as these are mutually exclusive, can you clarify which it is?

@tnorling The URL of the popup window does not contain a hash.
That is still happening for very first login ( very low reproducibility rate ).
Previously I did upgrade MSAL Browser to version 2.30.0 and reduced the pollIntervalMilliseconds to 15ms.
What do you have to suggest next please?

**Comment by bokipantic** [comment] 2023-01-04 15:47
@tnorling  I managed to reproduce the issue with the hash in the popup URL with the quickly caught print screen. It just appeared for a moment (less than 300ms) and then switched to the parent URL ( . . / ).
Now when we know it contains hash sign, could you please help me to resolve this bug?
Thanks

**Comment by tnorling** [comment] 2023-01-04 17:17
@bokipantic This means something is removing the hash or auto-redirecting the page to another route. You need to find that something and stop it from doing so. Most commonly it is caused by a router and you should ensure that your router is not acting upon your redirect page.

**Comment by bokipantic** [comment] 2023-01-06 15:32
@tnorling I am working on a widget which is integrated in other application. We are not controlling routing, we have no router config in our React code. We just do redirect URL to blank.html.
Please share if you have any idea how to resolve this.
Thank you very much

**Comment by tnorling** [comment] 2023-01-06 17:13
So the application you are embedded in controls the routing? You'll need to work with whoever controls your routing to get a static route set up. The blank page is great but if its still subject to the router it won't solve the problem.

**Comment by diamant-isufi-sveasolar** [comment] 2023-01-23 20:14
@bokipantic Hi, I am facing the same issue, were you able to solve it?

**Comment by bokipantic** [comment] 2023-01-24 10:31
@diamant-isufi-sveasolar Hi.. As for now I think I have resolved the issue, but waiting for app release including freshest changes to be able to test. Try to add blank.html file in app folder and connect ms teams redirect uri with absolute path of that file.

**Closed as completed** 2023-02-12 13:00 UTC
Labels: question, msal-browser, no-issue-activity, bug-unconfirmed, Needs: Author Feedback, public-client

**Comment by henrymcl** [comment] 2024-04-30 10:05
The issue's still here with
```json
{
  "@azure/msal-browser": "^3.13.0",
  "@azure/msal-react": "^2.0.15",
}
```

My vite setup:

```ts
server: {
headers: {
	'Access-Control-Allow-Origin': '*',
	'Cross-Origin-Opener-Policy': 'same-origin-allow-popups',
	'Content-Security-Policy': `
		script-src 'self' 'sha256-8ZgGo/nOlaDknQkDUYiedLuFRSGJwIz6LAzsOrNxhmU=' https://accounts.google.com https://www.google.com/recaptcha/api.js https://www.gstatic.com https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js;
		frame-src 'self' www.youtube.com www.google.com;
		frame-ancestors 'self';
		sandbox allow-scripts allow-same-origin allow-presentation allow-forms allow-popups allow-popups-to-escape-sandbox allow-modals
	` // "sandbox allow-scripts allow-same-origin" should only be used in development
		.replace(/(?:^\s+|\s+$)/gm, '')
		.split(/;?\r?\n/g)
		.join('; '),
},
}
```

**Comment by marcoshenke** [comment] 2025-03-12 15:06
I was facing the same problem.

The strangest thing was that with localhost the popup worked fine and the login was done correctly., but with my app in production the problem started to occurr.

The only way I found was to change the loginPopup to loginRedirect.

the versions I'm using:
"@azure/msal-browser": "^2.0.0",
"@azure/msal-react": "^1.0.0",
