### ISSUE TITLE
iframe for token refresh is NOT hidden and distracts the user

### ISSUE THREAD

**Issue by muratygt** [AzureAD/microsoft-authentication-library-for-js#3998] opened 2021-08-23 21:42 UTC
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.11

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

As the documentation indicates, MSAL implicit flow does not refresh token (v1) automatically so we need to call acquireSilenToken() periodically to refresh token. We implemented this approach in our web app (React) as seen the attached code snippet. Documentation tells that it will send a request in the hidden iframe to renew a token. 

However, in our app the iframe is **NOT** hidden. It is visible to the user and user has to manually click to the mini iframe window to close it. It is really a major distraction to the user since it takes all of the attention even though you are on a different browser window. The URL in the mini iframe window looks like `ourappurl.com/#accessToken=theaccesstoken....`

Based on the some issue research, MSAL team is suggesting `redirectUri` should be an empty page so page does not try to render the whole application. Also MSAL team suggests to not to call `acquireToken` function on the initial page load to avoid these types of problem. 

We need clear steps to fix this problem based on the attached code snippets for our app. 

`Expected Behavior:`

- We just want to refresh the token via hidden iframe
- If the mini iframe window has to be visible, at the very least window should close itself. 
- User should not get distracted at all.

### MSAL Configuration

```javascript
auth: {
            instance: 'https://login.microsoftonline.com/',
            tenant: myTenant,
            clientId: myclientID,
            authority: myauthority,
            validateAuthority: true,
            extraQueryParameters: { domain_hint: myDomainHit },
            redirectUri: 'http://localhost:3000',
            navigateToLoginRequestUrl: true,
            expireOffsetSeconds: 300
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false
        },
```

### Relevant Code Snippets

```javascript
Attaching both of the code snippets auth.js and main.js (at the bottom) that handle user authentication.

#########
auth.js
########

import * as Msal from 'msal';
import { axiosInstance as axios } from '../helpers/axiosInstance';

const msalInstance = new Msal.UserAgentApplication(MSAL_CONFIG);
export const loginRequest = {
    scopes: ['openid', 'profile', 'User.Read.All']
};

export const extractMSALToken = async () => {

    // ### Removes all of the existing expired token data from the local storage

    for (const key of Object.keys(localStorage)) {
        if (key.includes('authority') || key.includes('msal')) {
            localStorage.removeItem(key);
        }
    }
    // ### calls the function to acquire a new token
    return acquireToken(loginRequest).catch((error) => {});
};

const requiresInteraction = (errorMessage) => {
    if (!errorMessage || !errorMessage.length) {
        return false;
    }
    return (
        errorMessage.indexOf('consent_required') > -1 ||
        errorMessage.indexOf('interaction_required') > -1 ||
        errorMessage.indexOf('login_required') > -1 ||
        errorMessage.indexOf('token_renewal_error') > -1
    );
};

export const acquireToken = async (request) => {
    try {
        await msalInstance.acquireTokenSilent(request).then((response) => {
            const idToken = response.idToken.rawIdToken;
            axios.defaults.headers.common.Authorization = `Bearer ${idToken}`;
            return accessToken;
        });
    } catch (error) {
        if (requiresInteraction(error.errorCode)) {
            return msalInstance
                .acquireTokenPopup(request)
                .then((response) => {
                    const idToken = response.idToken.rawIdToken;
                    axios.defaults.headers.common.Authorization = `Bearer ${idToken}`;
                })
                .catch((err) => {
                    console.log(err);
                });
        }
    }
};

const signIn = async () => {
    const loginResponse = await msalInstance.loginRedirect(loginRequest).catch((error) => {});

    if (loginResponse) {
        return acquireToken(loginRequest).catch((error) => {
            console.log(error);
        });
    }
};

const autoMsalSignIn = async () => {
    msalInstance.handleRedirectCallback((error, response) => {});

    // ### TOKEN REFRESH ### - Refreshes the token every 55 minutes
    setInterval(() => {
        extractMSALToken();
    }, 3300000);

    if (window === window.parent && window === window.top) {
        let account = msalInstance.getAccount();

        if (account) {
            return acquireToken(loginRequest).catch((error) => {});
        } else if (!msalInstance.isCallback(window.location.hash)) {
            signIn();
        }
    }
};


export { autoMsalSignIn };


#######
main.js
#######
const initPromise = DISABLE_SSO ? Promise.resolve() : autoMsalSignIn();

initPromise.then(() => {
    ReactDOM.render(
            <Provider store={store}>
                <BrowserRouter basename={BASE_URL}>
                    <Routes />
                </BrowserRouter>
            </Provider>,
        document.getElementById('app')
    );
});
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment] 2021-08-23 21:44
> However, in our app the iframe is NOT hidden. It is visible to the user and user has to manually click to the mini iframe window to close it. 

Can you please provide a screenshot of this behavior? The iframe created by MSAL should be hidden and not require any user interaction to close.

**Comment by muratygt** [comment] 2021-08-31 03:31
@jasonnutter . I fixed all of the redirect uris to match the correct app url. So if I am on `https://dev.mayappname.hub.aws.com`, I am sure that `redirectUri=https://dev.mayappname.hub.aws.com` so they all match the home link of each environment. 

However problem still happens. Popup window appears when the `Uncaught (in promise) ClientAuthError: Token calls are blocked in hidden iframes` error occurs and takes all the attention. Then it is self closing in a minute or two. 

As I read more of the issue threads similar to my problem, I see your [response on this thread](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1156#issuecomment-569768269) stating that `We generally don't recommend calling acquireTokenSilent on page load, ...`, I am assuming that might be what is happening in my app since we do this 
```
#######
main.js
autoMsalSignIn() function is where all the auth logic happens (see above)

Here we authenticate the user first and then render the entire application. 
I am assuming this fits your response in the above statement where we call acquireTokenSilent on page load. 
#######


const initPromise = DISABLE_SSO ? Promise.resolve() : autoMsalSignIn();

initPromise.then(() => {
    ReactDOM.render(
            <Provider store={store}>
                <BrowserRouter basename={BASE_URL}>
                    <Routes />
                </BrowserRouter>
            </Provider>,
        document.getElementById('app')
    );
});
```

I also have following values in under the system configs. Does `loadFrameTimeout` or `tokenRenewalOffsetSeconds` have any negative effect to my issue?

```
system: {
            loggerOptions: {
                loggerCallback: (level, message, containsPii) => {
                    if (containsPii) {
                        return;
                    }
                    switch (level) {
                        case level.Error:
                            console.error('Error Logs', message);
                            return;
                        case level.Info:
                            console.info('Info Logs', message);
                            return;
                        case level.Verbose:
                            console.debug('Verbose Logs', message);
                            return;
                        case level.Warning:
                            console.warn('Warning Logs', message);
                    }
                },
                piiLoggingEnabled: false
            },
            loadFrameTimeout: 9000,
            tokenRenewalOffsetSeconds: 300
        }
```

**Comment by muratygt** [comment] 2021-08-31 15:59
Here is the more with the error messaging. 
`ClientAuthError: Token renewal operation failed due to timeout.`

**Comment by muratygt** [comment] 2021-08-31 19:46
I was able to grab the request endpoint with its query params. I can assure that redirectUri is correct. Some posts were talking about requesting `openid profile and User.Read.All` at the same time throws error. 

- Is that really the case?
- Do you see anything in this request which is not ideal?

```
https://login.microsoftonline.com/my-tenant-id-value/oauth2/v2.0/authorize
?response_type=id_token%20token
&scope=openid%20profile%20User.Read.All
&client_id=my-client-id-value
&redirect_uri=https%3A%2F%2Fqa.myappname.hub.aws.com
&state=somesortofHashedMsalStatevalue%3D
&nonce=some-value-4817-999d
&client_info=1
&x-client-SKU=MSAL.JS
&x-client-Ver=1.4.11
&login_hint=myemail@microsot.something.com
&client-request-id=some-type-of-request-id-c60ee9dcab96
&response_mode=fragment
```

**Comment by muratygt** [comment] 2021-08-31 20:29
@jasonnutter It looks like there are some answers [on this page](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#refused-to-display--in-a-frame-because-it-set-x-frame-options-to-deny). 

```
Solutions

- If using a browser with third party cookies disabled you must call an interactive method such as acquireTokenRedirect or acquireTokenPopup
- Solve the accompanying error
- Set the redirectUri for the acquireTokenSilent call to a blank page

```

Looks like ideal solution to this problem redirectUri should be a blank page. I am using React Router for the navigation. So if I create a new route to an empty page, do you think it will work?

**Comment by jasonnutter** [comment] 2021-08-31 23:30
@muratygt Sorry for the delayed response. 

> Looks like ideal solution to this problem redirectUri should be a blank page. I am using React Router for the navigation. So if I create a new route to an empty page, do you think it will work?

Yes, I would recommend setting a blank page as the redirect URI for your calls to `acquireTokenSilent` and `acquireTokenPopup/loginPopup` (you cannot use a blank page for the redirect uri for `loginRedirect`, please continue to use your home page for the redirect URI for that). You can do this by setting the `redirectUri` explicitly on each `acquireTokenSilent/acquireTokenPopup/loginPopup` call.

And yes, the "ClientAuthError: Token calls are blocked in hidden iframes" error was due to the page used for teh redirect URI for acquireTokenSilent automatically invoking acquireTokenSilent on page load (when inside the hidden iframe created by MSAL). This error is thrown to prevent endlessly nested iframes.

**Comment by muratygt** [comment] 2021-09-01 15:42
Thanks @jasonnutter for your response. This gives me more confidence on what to do to solve the problem. 

Here is what I came up. Just wanted to confirm with you. 

1. I created a Route (not protected) to the empty page called `/auth`  and created an empty page called `AuthRedirect` shown below. I will make sure I add `myapplink.com/auth` urls for each environment to the `Azure Registration`

<img width="659" alt="Screen Shot 2021-09-01 at 10 08 16 AM" src="https://user-images.githubusercontent.com/51856156/131687036-b38a5a58-e61f-4bf5-bccb-1f460575953a.png">
<img width="1021" alt="Screen Shot 2021-09-01 at 10 08 34 AM" src="https://user-images.githubusercontent.com/51856156/131687085-805b329c-58f4-400e-b642-ad756af77aad.png">


2. As you suggest, I explicitly added redirectUri only to the `acquireTokenSilent and acquireTokenPopup` functions as below. 

Is this the correct implementation of explicitly adding the redirect uri?

```
export const loginRequest = {
    scopes: ['openid', 'profile', 'User.Read.All']
};
```

```
export const acquireToken = async (loginRequest) => {
    try {
        await msalInstance
            .acquireTokenSilent({ ...loginRequest, redirectUri: `${window.location.origin}/auth` })
            .then((response) => {
                const idToken = response.idToken.rawIdToken;
                axios.defaults.headers.common.Authorization = `Bearer ${idToken}`;
                return accessToken;
            });
    } catch (error) {
        if (requiresInteraction(error.errorCode)) {
            return msalInstance
                .acquireTokenPopup({ ...loginRequest, redirectUri: `${window.location.origin}/auth` })
                .then((response) => {
                    const idToken = response.idToken.rawIdToken;
                    axios.defaults.headers.common.Authorization = `Bearer ${idToken}`;
                })
                .catch((err) => {
                });
        }
    }
};
```

Question: 
I remember from the issue reading, msal engineers are suggesting redirect uri to be an empty page which `does not require authentication`. I just want to make sure my solution fits into that category.  

Basically, I created a new route under all routes which is an empty page. I just want to make sure that page fits into `does not require authentication` suggestion mentioned in the issues. 

Here is the directory to the empty page

```
#######
main.js
autoMsalSignIn() function is where all the auth logic happens (see above)

Here we authenticate the user first and then render the entire application. 
#######


const initPromise = DISABLE_SSO ? Promise.resolve() : autoMsalSignIn();

initPromise.then(() => {
    ReactDOM.render(
            <Provider store={store}>
                <BrowserRouter basename={BASE_URL}>
                    <Routes />        // ==> That empty page is under Routes
                </BrowserRouter>
            </Provider>,
        document.getElementById('app')
    );
});
```

**Comment by jasonnutter** [comment] 2021-09-01 18:28
> QUESTION 1: 
> Is this the correct implementation of explicitly adding the redirect uri?

Yes, that looks correct.

> QUESTION 2:
> Can empty page be under Routes component shown below?
> OR should it be somewhere outside of the entire app render?

It doesn't have to be outside of our React application (e.g. as a blank html page in your assets folder), but sometimes that can simpler in the interest of the page not itself requiring auth.

> QUESTION 3:
> Does !window.location.href.includes('#access_token') logic prevent anything?
> Someone recommending not to call acquireSilentToken in that mini window so I come up with adding this logic.

Just checking for "#access_token" isn't comprehensive. If you know the only time your application will be rendered in an frame with a hash, then you can simplified that check to check that `window.location.hash` is not a blank string.

**Comment by muratygt** [comment] 2021-09-01 18:36
Testing changes locally

This empty page now opens up the pop up window again and takes all the attention with empty content

<img width="1792" alt="Screen Shot 2021-09-01 at 1 49 42 PM" src="https://user-images.githubusercontent.com/51856156/131724185-4c0a9225-3dfd-4761-8fff-72aeab087ba0.png">

And here is the console logs and the error messaging

<img width="1073" alt="Screen Shot 2021-09-01 at 2 31 09 PM" src="https://user-images.githubusercontent.com/51856156/131725353-6db87b94-9233-43d9-bfc7-d066d2cb14f5.png">

**Comment by muratygt** [comment] 2021-09-01 19:10
In the Routes component, we have a function (useEffect hook) that calls `acquireToken` when there is `401 Error`. 

Do you think this is triggering some sort of infinite loop and then iframe is getting blocked/timeout which makes it `popup window` visible?

<img width="853" alt="Screen Shot 2021-09-01 at 3 07 21 PM" src="https://user-images.githubusercontent.com/51856156/131729559-b5115c6f-de6e-4098-a9f6-02174d481c3c.png">

**Comment by muratygt** [comment] 2021-09-01 22:40
Is `acquireTokenPopup` call the only way to refresh token when there is an error on `acquireTokenSilent` call? 

It looks like it is how that popup window is getting opened with `/#access_token...` stuff in the url. 

How can we eliminate error happening on the `acquireTokenSilent` call  so it does not call `acquireTokenPopup` because it is pretty frequent on our case?

![Screen Shot 2021-09-01 at 6 37 21 PM](https://user-images.githubusercontent.com/51856156/131754592-536860e0-1f87-41d4-9ae2-c58dfffecfa6.png)

**Comment by jasonnutter** [comment] 2021-09-01 23:43
> Is there anyway we can refresh the token without any extra popup window via MSAL Implicit Flow?
> I know token refresh can fail for many reasons but the popup window (which has /#access_token...) makes the auth process really distractive.
> Think about it. You are using an application and once in a while you see some weird popup window appears/disappears and takes all of your attention.
> I totally understand token refresh might have some errors but I am just trying to understand what MSAL does not like that we do in our app so it keeps popping up a window with that hash value occasionally.

If silent authentication fails, you must usually perform an interactive flow to complete auth. You can either do a full page redirect or popup.

Popups should not show up often, and should close themselves automatically, and I'm not understand why your don't do that. Can you try using a blank html page (that is not part of your app)?

And have you inspected the error returned from acquireTokenSilent?

**Comment by muratygt** [comment] 2021-09-02 13:56
@jasonnutter 

> Popups should not show up often, and should close themselves automatically, and I'm not understand why your don't do that.

About this, the popup we have is closing itself in a minute or two. But popup window is appearing pretty often which creates a major distraction to the user. 

> And have you inspected the error returned from acquireTokenSilent?

I inspected the error returned from the `acquireTokenSilent`. It throws `Token renewal operation failed due to the timeout.`

Here is how it looks

<img width="995" alt="Screen Shot 2021-09-02 at 9 38 41 AM" src="https://user-images.githubusercontent.com/51856156/131853818-c5ea48ee-cb71-4d82-a0e2-4d5d3bf700cf.png">

<img width="745" alt="Screen Shot 2021-09-02 at 9 32 18 AM" src="https://user-images.githubusercontent.com/51856156/131853855-aabadb68-210b-46c4-99b7-d30d31cc18df.png">

**Comment by muratygt** [comment] 2021-09-02 20:26
I also grabbed the response from `acquireTokenSilent` call to see if that means anything for you in regards to our app's misconfiguration. 

<img width="451" alt="Screen Shot 2021-09-02 at 4 21 07 PM" src="https://user-images.githubusercontent.com/51856156/131911346-a661eb9d-fcb2-4784-a6a0-a5e975a41cd4.png">

**Comment by muratygt** [comment] 2021-09-03 16:12
This is how I explicitly refresh token. I created a `setInterval` which calls `extractMSALToken` function on every 55 min. 

`extractMSALToken` function removes all of the msal values from the local storage and make a new call to the `acquireToken` function which calls `acquireTokenSilent` (if fails `acquireTokenPopup`)

**Question:** 
Do you think this flow might be the cause of the issue since we are removing all of the msal values and recalling `acquireToken` explicitly on every 55 min (3,300,000 ms)?

<img width="719" alt="Screen Shot 2021-09-03 at 12 07 17 PM" src="https://user-images.githubusercontent.com/51856156/132035811-3fbf1d16-0fa3-4e4c-b57a-b639b38084a5.png">

<img width="1066" alt="Screen Shot 2021-09-03 at 12 06 34 PM" src="https://user-images.githubusercontent.com/51856156/132035808-a35be809-2701-46c4-b711-30acb29d50fe.png">

**Comment by jasonnutter** [comment] 2021-09-08 16:06
@muratygt Generally speaking, we do not recommend proactively renewing tokens, such as with the code you shared. Our general best practice is to invoke `acquireTokenSilent` when you need a token, let MSAL figure out if the token has expired (and get you a new one if so), and then handle any errors MSAL returns if it is unable to do so. Furthermore, you do not need to manage the cache, as MSAL handles that for you.

Attempting to acquire tokens on an interval can cause strange UX, especially if prompts are shown when the user is not expecting it.

**Comment by muratygt** [comment] 2021-09-08 19:33
Thanks @jasonnutter 

I created that `setInterval` logic because of [this statement](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#refreshing-tokens) in the MSAL Implicit Flow documentation. 

Based on my understanding on this statement 
```
Both id_tokens and access_tokens will expire after a short period of time, 
so your app must be prepared to refresh these tokens periodically
```

To refresh the token `periodically`, I created a function to clear cache (just to be sure) and call `acquireTokenSilent` on every 55 min. (periodically). 

I also track `401 Errors` on my app. When it occurs, I do another call to that function where it clears the cache and calls `acquireTokenSilent` so that it refreshes the token and saves it to the local storage. 


**Question 1:** 
What is the best way to `refresh the token periodically` from your point of view?

**Question 2:** 
Do you think calling `acquireTokenSilent` call when 401 errors occur is a bad practice?

**Question 3:**
When is the optimal (periodic/`as needed`) time from your view to refresh token?

**Comment by jasonnutter** [comment] 2021-09-10 00:37
> What is the best way to refresh the token periodically from your point of view?

Call `acquireTokenSilent` when you need an access token, and let MSAL handle figuring out if the token is still valid, and if its not, it will attempt to renew it. If runs into a problem doing that, it will throw an error, which your application should catch and handle (usually by invoking an interactive method).

You also do not need to manage the msal cache (e.g. removing old tokens), as msal will handle that for you.

> Do you think calling acquireTokenSilent call when 401 errors occur is a bad practice?

I assume you are referring to getting a 401 back from the API resource when you attempt to acquire data using the token. If so, it is fine to call `acquireTokenSilent` to get a new token (in this specific scenario, you may want to also set `forceRefresh` to `true`, to force MSAL to get a new token, as we've had problems before of MSAL returning an already expired token).

> When is the optimal (periodic/as needed) time from your view to refresh token?

As mentioned, you shouldn't worry about that. Call `acquireTokenSilent` when your needs to do something that requires a token, and catch and handle any errors that are thrown.

**Comment by pashvin** [comment] 2021-09-21 21:53
Hi, I have similar issue (unexpected login popup) but may be diff root cause. I see in your post you mentioned about timeout. I had that issue long time ago and I fixed by providing following iframeHashTimeout in MSAL init code. Give a try if that works.

auth : {...}
cache : {...}
system: {
        iframeHashTimeout: 10000
}

**Closed** 2021-09-29 01:00 UTC
Labels: question, msal@1.x, no-issue-activity, answered, Needs: Author Feedback
