### ISSUE TITLE
Redirect the user to the page he is trying to access by having it in the browser memory

### ISSUE THREAD

**Issue by sneha-boopal** [AzureAD/microsoft-authentication-library-for-js#2849] opened 2021-01-11 05:46 UTC
## Library

- ["1.1.3" ] `msal@1.x.x` 
-  ["2.1.1"] : "react-aad-msal",
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

**unable to Redirect the user to the page he is trying to access on login by having it in the browser memory.**

How can this be accomplished if we are using "react-aad-msal"? Could you share if there are any examples?

I tried by setting the reply url in azue as http://localhost:3000/ad-callbackurl'(so for any request url the token will be sent to this url which is registered in azure) and in client application i'm storing the request url in session storage and on successful login i need to get redirected to the request url which is stored in session storage. But with the below code on successful login it is getting redirected to https://localhost:3000/ad-callbackurl?#state=<token> and then automatically getting redirected to base url which is http://localhost:3000

import { MsalAuthProvider, LoginType } from 'react-aad-msal';
import {authority, clientId, defaultScope,} from './utilities';

function AuthProvider() {
sessionStorage.setItem('local-url', window.location.href);
return new MsalAuthProvider(
{
auth: {
authority: authority ,
clientId: clientId ,
postLogoutRedirectUri: window.location.origin,
redirectUri: window.location.origin + '/ad-callbackurl ',
validateAuthority: false,
navigateToLoginRequestUrl: true,
},
cache: {
cacheLocation: "localStorage",
storeAuthStateInCookie: true,
},
},
{
scopes: [ defaultScope ],
},
LoginType.Redirect,
);
}

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment] 2021-01-11 18:55
Closing as duplicate of #2843.

**Closed by jo-arroyo** 2021-01-11 18:55 UTC
Labels: question
