### ISSUE TITLE
@azure/msal-angular - Do not force '/auth' route when the whole application must be protected

### ISSUE THREAD

**Issue by mdarefull** [AzureAD/microsoft-authentication-library-for-js#3306] opened 2021-03-25 17:09 UTC
## Library

- @azure/msal-browser": "^2.13.0"
- @azure/msal-angular": "^2.0.0-beta.2",

## Framework

- [ X] Angular
- [ ] React
- [ ] Other

## Description
In the documentation for [log users in when they hit the application](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#how-do-i-log-users-in-when-they-hit-the-application) for the `PathLocationStrategy` it is mentioned that we should set `redirectUri `to `/auth` and make `MsalRedirectComponent` as the target component.

I don't think that is a good experience:

1. That creates a valid `/auth` path in our application that when targetted directly doesn't display any component.
1. If I add MSAL to all my pages (but `/auth`) and I'm already logged in, browsing to a protected page `inProgress$` emits `handleRedirects` but never emits `None` after that.
1. If I add MSAL to all my pages (but `/auth`) and I'm already logged in, browsing to `/auth`, `inProgress$` behaves as expected, but nothing displays since `MsalRedirectComponent` is blank.
1. I would think that forcing the usage of a Component is too restrictive and might not be possible for every single type of application.
1. I would like to keep MSAL logic as encapsulated as possible. It is not a good idea to be forcing the app to create and maintain an additional route or any MSAL specific requirements to be filtered to other modules/components.

Note: I was able to implement this behavior using `handleRedirect `directly entirely in-code. I'm willing to provide any insights or support... I don't think imposing the usage of a redirect component is a good idea. 

Could it be possible to create a service that would centralize all this logic? If the service is added as a provider as soon as it is instantiated it could subscribe to the handleRedirect and centralize the responsibilities that would previously be handled by MsalRedirectComponent and MsalGuard.
Services are singleton so this would really simplify the current setup and reduces the chance for race conditions.

`PathLocationStrategy` is the default strategy for angular projects and several sites are members only.

## Error Message
X

## MSAL Configuration
X

## Reproduction steps
X

## Expected behavior
X

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x ] Customer request

**Comment by jasonnutter** [comment] 2021-04-07 18:40
@mdarefull Apologies for the delay in responding.

First, using a separate `/auth` route is not a requirement. Per the documentation you linked to:

> For those using the PathLocationStrategy, we _**recommend**_:

(emphasis mine)

This is a recommendation, but not a hard requirement. You are free to use any page (e.g. your home page) as the redirect, and we want to support both scenarios in MSAL Angular.

> 1. That creates a valid /auth path in our application that when targetted directly doesn't display any component.
> 3. If I add MSAL to all my pages (but /auth) and I'm already logged in, browsing to /auth, inProgress$ behaves as expected, but nothing displays since MsalRedirectComponent is blank.

This is intended. We would not expect a user to manually browser to the `/auth` route. If this is a concern, you can add logic that checks whether the url includes a hash (which would indicate if the route is being loaded manually), and handle that situation accordingly (e.g. display a message, redirect the user).

> 2. If I add MSAL to all my pages (but /auth) and I'm already logged in, browsing to a protected page inProgress$ emits handleRedirects but never emits None after that.

I believe this should be addressed by using the [custom navigation client](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md).

> 4. I would think that forcing the usage of a Component is too restrictive and might not be possible for every single type of application.

As noted above, using the `/auth` route and/or the `MsalRedirectComponent` is optional. What is required, however, is that when performing redirect-based interactions, that your application invoke `handleRedirectObservable` in order to process the request. The redirect component does this for you, and the dedicated route helps mitigates common problems with redirects.

> 5. I would like to keep MSAL logic as encapsulated as possible. It is not a good idea to be forcing the app to create and maintain an additional route or any MSAL specific requirements to be filtered to other modules/components.

Using a dedicated redirect URI is a common pattern for auth libraries, and can help with performance, mitigate race conditions, etc. But again, it is optional.

> Could it be possible to create a service that would centralize all this logic? If the service is added as a provider as soon as it is instantiated it could subscribe to the handleRedirect and centralize the responsibilities that would previously be handled by MsalRedirectComponent and MsalGuard.
> Services are singleton so this would really simplify the current setup and reduces the chance for race conditions.

This is what the `MsalService` is meant to be. Generally speaking, we believe in composition over configuration (to more easily support a wide range of app scenarios), which means it is the responsibility of the application to compose the APIs we provide to accomplished the desired experience. It is important for us to provide reasonable defaults, while not being too opinionated for any particular architecture or set of considerations.

> PathLocationStrategy is the default strategy for angular projects and several sites are members only.

I think it worth pointing out that the `MsalGuard` is a provided a **user-experience** feature, not a security feature, i.e. it prompts the user to login if they are not already, but is not intended to completely secure a route, given it performs client-side validation. Applications should not solely rely on the guard for security, and should ensure that any data that needs to be secured is done so by requiring access tokens and validating those access tokens in the resource (e.g. MSFT graph, any custom web api).

**Comment by mdarefull** [comment] 2021-04-08 12:22
@jasonnutter There's nothing to apologize for! 

Let's clean the discussion a little bit... there are a lot of mixed topics...

First, I think my project is not a particular one. Its only characteristics are that it uses Path routing (the default) and it requires authenticated user access. There are many members-only sites that should have these requirements. So, I would say that we could start by having a simple example (like the ones you already have), leveraging MSAL-angular to protect all the routes...

As for the issues, I started testing this version since its alpha 3 version and I've found several sorts of issues trying to solve that scenario:
* Alpha 3 was the most stable. I had to manage the handle redirect on my own and the only issue I was having when using MSAL to protect the whole app is that the State hash would remain visible in the URL after a successful login. (Reproducible using your b2c sample)
* The betas collectively brought the Redirect Component and the InProgress... In trying to leverage all those components to achieve my goal:
   * The same #state= issue at login persists.
   * InProgress was emitting redirect => none => redirect => none at least twice. (this probably got fixed in the last version)
   * If I don't add an unprotected auth/ with the redirect component there... login was never being triggered.
   * If I add an unprotected auth/ with the redirect component there:
      * If, as an unauthenticated user, I access to a protected route, login works as expected (except for the #state issue)
      * If, as an unauthenticated user, I access to /auth... login requests never occur... the site is blank
      * If, as an authenticated user, I access to /auth... the site displays blank.

**Comment by mdarefull** [comment] 2021-04-08 12:33
As for the routes and component discussion... my point is that I don't think providing a component is a good design.

Components are meant for presentational logic. Handling the redirect observable (the core part of the MSAL usage) should be responsibility of a service and has no presentational responsibilities.

In Angular, application initialization and component renderization are separate stages. I could leverage APP_Initializer to delay rendering components in order to perform some initialization logic, one of which could be to validate the user is authenticated. But the recommended RedirectComponent would never be used...

As you stated, MSAL Service is meant to centralize all this logic, shouldn't then MSAL upon instantiation, handle the redirect observable itself? Why not, instead of creating a RedirectComponent that should be rendered next to the app-root and also inside the auth/ route, don't we extend the MSALService to provide angular-specific defaults?

> Generally speaking, we believe in composition over configuration

And I totally agree with you! Now, if we have to manage the handle redirects ourselves, and implement our own auth guards with our own checks, and triggering login manually for projects as simple as mine... what's the value that msal-angular provides? the HTTP interceptor?

**Comment by mdarefull** [comment] 2021-04-08 12:53
And as my last, but not least, important comment let's consider ease of use. I work for a consultancy company and we have many projects, we mainly focus on Azure technologies. Many of my coworkers have tried to use MSAL, followed the official documentation and then they stumble with all these details. They are no AD/MSAL expert, to most of them all these moving parts are very complex. It feels frustrating when you go by the official sample and it doesn't cover your scenario, then you need to start digging... I feel that hurts really bad the adoption of this amazing library.

**Comment by jasonnutter** [comment] 2021-05-03 23:28
> So, I would say that we should start by having a simple sample (like the ones you already have) to cover this scenario. That would allow us to spot all these issues.

We have several samples that cover many of the basic scenarios (hash routing, path routing, etc), however, please note we cannot have samples for all scenarios (even all "basic" scenarios). We are working on providing documentation for scenarios that are not covered in samples.

> The same #state= issue at login persists.

This should be addressed in the last version.

> InProgress was emitting redirect => none => redirect => none at least twice. (this probably got fixed in the last version)

I have not heard about this. Please file a separate issue with details if you can reproduce this in the last version. cc @jo-arroyo 

> If I don't add an unprotected auth/ with the redirect component there... login was not working.

The latest version should better handle setting the guard on the redirect uri.

> As you stated, MSAL Service is meant to centralize all this logic, shouldn't then MSAL upon instantiation, handle the redirect observable itself? Why not, instead of creating a RedirectComponent that should be rendered next to the app-root and also inside the auth/ route, don't we extend the MSALService to provide angular-specific defaults?

We do not automatically invoke `handleRedirectObservable` intentionally because we have found that is too opinionated to do so (i.e. not all apps use redirects, some need to control over processing, etc.). We provide the `MsalRedirectComponent` and raw API so that apps can pick which approach works for them. We also do as much as we can do abstract away boilerplate and complexity, which is why we created the `MsalRedirectComponent` (i.e. just make sure it gets rendered on the page and redirects will be processed).

> And I totally agree with you! Now, if we have to manage the handle redirects ourselves, and implement our own auth guards with our own checks, and triggering login manually for projects as simple as mine... what's the value that msal-angular provides? the HTTP interceptor?

Generally speaking, the wrapper libraries fit idiomatic MSAL concepts (e.g. managing a `PublicClientApplication` instance, logging in, acquiring tokens) into idiomatic framework concepts (e.g. services, components, guard, interceptors). We expect most applications to find value in managing a `PublicClientApplication` instance, for example, but not all applications will find the guards or interceptors will fit their use case. We strive to make these features extensible and configurable to support as many use cases as we can, and are always open to feedback for how we can make our wrapper libraries support more use cases (without being overly opinionated to a specific use case(s)).

> And as my last, but not least important, comment let's consider ease of use.
I work for a consultancy company and we have many projects, we mainly focus on Azure technologies. Many of my coworkers have tried to use MSAL, followed the official documentation, and then stumbled with all these details. They are no AD/MSAL experts, to most of them all these moving parts look intimidating. They have been frustrated after going by the docs and sample and realizing these issues and start digging and researching on a "custom" solution... I feel that hurts really bad the adoption of this amazing library.

I understand your frustration, and we are continually working to make our libraries easier to use and understand. Please feel free to share further feedback on areas of our libraries that are not easy to understand or use.

**Comment by mdarefull** [comment] 2021-05-13 16:42
@jasonnutter: I'm all for collaborating to improve this great library. I'm currently very short on time but I have scheduled to check the newest modifications to the library and update our projects, just wait for couple days and I would provide one (or many) simple projects highlighting each issue I encounter.

Personally, I think the more projects adhere to the recommended configurations the best.

**Comment by jasonnutter** [comment] 2021-05-19 17:03
@mdarefull Sounds good!

Closing, as no further action at this time.

**Closed by jasonnutter** 2021-05-19 17:03 UTC
Labels: Needs: Attention :wave:, answered, b2c, msal-angular, question
