### ISSUE TITLE
acquireTokenSilent does not make B2C request when user is not logged in.

### ISSUE THREAD

**Issue by nbangera** [AzureAD/microsoft-authentication-library-for-js#563] opened 2019-02-14 16:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version 71.0.3578.98

## Library version

<pre><code>
Library version: 0.2.4

## Current behavior

If user is not logged in and doesn't have a session.
calling acquireTokenSilent does not make a server B2C request. it only checks the browser session.
but if user is logged in and has a B2C session. acquireTokenSilent makes a server request and network call can be traced.

## Expected behavior
acquireTokenSilent should check with B2C server to get actual user session. Or there should be provision to force server check. 
Since user might have logged out from B2C using another application but since local session is still active, acquireTokenSilent returns incorrect user  status.

## Minimal reproduction of the problem with instructions

    function testSilentB2cCall() {
            clientApplication.acquireTokenSilent(applicationConfig.b2cScopes).then(function (accessToken) {
                alert("MSAL- user session exist");
                console.log(accessToken);
            }, function (error) {

                alert("MSAL - user session does not exist");
                //console.log(accessToken);
             
            })
        }

**Comment by zamzowd** [comment] 2019-02-19 21:54
I believe this is a duplicate of #275 

I created a pull request #541 to add a way to ignore the "User login is required" condition.

**Closed** 2019-09-19 20:39 UTC
Labels: B2C, enhancement

**Comment by zamzowd** [comment] 2019-09-19 21:19
Why was this closed?

**Comment by sameerag** [comment] 2019-09-19 21:52
This will be tracked with #900.
