### ISSUE TITLE
acquireTokenSilent cause page refresh

### ISSUE THREAD

**Issue by Gtyrande** [AzureAD/microsoft-authentication-library-for-js#526] opened 2019-01-06 09:03 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Center Browser version 3.7.2.33 (Chromium 70.0.3538.110)
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior
My vue page refreshed after every time acquireTokenSilent has been called, it causes my created() method in App.vue to be called multiple times.

## Expected behavior
My page will not refresh after acquireTokenSilent.

## Minimal reproduction of the problem with instructions
// store.js
state.msalService.getApiToken().then(token => {}
// msal.service.js
getApiToken() {
    return this.app.acquireTokenSilent(this.applicationConfig.apiScopes).then(
      accessToken => {
        return accessToken;
      },
      error => {
        console.log(error);
        return this.app
          .acquireTokenPopup(this.applicationConfig.apiScopes)
          .then(
            accessToken => {
              return accessToken;
            },
            err => {
              console.error(err);
            }
          );
      }
    );
  };

</code></pre>

**Comment by Ralms** [comment] 2019-01-14 02:03
I'm having the same issue. 
Using Angular, I've noticed that all classes gets re-instantiated when I request a token silently.

Is this reload really required?

**Comment by vramasam** [comment] 2019-01-16 05:18
We are calling acquireTokenSilently to get the access Token (To extend the token). 

But it causes all classes in the angular gets initiated. Because of that it loses the immemory contents and the UI contents.

Our requirement , we are adding all the REST API request in queue. When we get unauthorised we have to get the token silently and make the pending queue api success. 

But because of entire Angular APP gets reinitiated when we call acquireTokenSilently. All the information(Queue) gets lost.

**Comment by sameerag** [comment] 2019-01-16 07:30
@vramasam we started investigating this issue. Will update as soon as we find the rootcause for the above behavior stated.

**Comment by sameerag** [comment] 2019-01-18 01:37
So here is how MSAL JS is designed:
All our responses are HTTP 302 - both silent and interactive, which implies there is a reload. But we do all the heavy lifting in a separate window to process the response and leave the original window as is. For a popup this is handled in a popup window, for silent we handle it in an iFrame. 

To avoid a reload for the main window, please follow the instructions @ https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs. Specifically please ensure that redirect_uri is set to a page which can be discarded once you have a token.

Please let us know if this resolves the issue.

**Comment by sameerag** [comment] 2019-01-18 01:39
@Gtyrande we do not have a wrapper for Vue and since Vue works differently, can you please share MSAL logs and the Auth Code snippets, particularly the initialization of UserAgentApplication instance. Also please check the above comment if it helps your case.

**Comment by Ralms** [comment] 2019-01-18 01:51
Hi @sameerag,

Doing acquireTokenPopup doesn't cause a reload, only the acquireTokenSilent is. 
I'm having a hard time understanding why you can't block the HTTP 302 while doing it silently.

**Comment by sameerag** [comment] 2019-01-18 19:20
@Ralms acquireTokenSilent() should not cause page reload as we handle it in a hidden iFrame. Can you please share your code snippet that is relevant to reproduce this issue? Detailed steps for reproduction and any stack trace you may have had will be helpful.

We are interested in the code sample that initializes UserAgentApplication() and the acquireTokenSilent() call and the point of refresh in your code.

**Comment by sameerag** [comment] 2019-01-18 20:01
@Ralms In our Angular sample, we have code that helps avoid the refresh when acquireTokenSilent() is called.

//  This is to avoid reload during acquireTokenSilent() because of hidden iframe
this.isIframe = window !== window.parent && !window.opener;

Please check the below files for a general idea on how to avoid reloads in Angular: 
1) https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/1a7b3c5fdb67d160a216eabe09c4c004e3310649/lib/msal-angular/samples/MSALAngularDemoApp/src/app/app.component.html 

2) https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9fa581aa01e5314dc765ea33161b431b6f3e6c04/lib/msal-angular/samples/MSALAngularDemoApp/src/app/app.component.ts

Let me know if this helps.
I will follow up to document this in our wiki soon in case if it isn't.

**Comment by Ralms** [comment] 2019-01-18 21:40
@sameerag I feel so dumb right now lol

I started with the sample like 1 month ago, than move a lot of the authentication and token related stuff to a service file, with the variable isIframe that I didn't spend the time understanding what was for.

I've added this back to the router outlet and the check in the app.component.ts constructor and seems to stop the reloading to components pushed by the router.
Although Menus that are outside the router are still getting reloaded but I think I can work around that.

I'm checking now if it's only the menu components that are reloading which in turn are causing some services to reload.

**Comment by Ralms** [comment] 2019-01-18 22:22
@sameerag Ok, I ran some tests and although the router content wont reload, the rest of the files are still reloading, this includes the app.module.ts causing services to get instantiated again. 

The log in the console when I call for the token silently is the following: 
( I've removed the ClientID and some info end the end of the Navigate Url log)
`
app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:57 GMT:0.2.1-Info Add msal frame to document:msalRenewFrameuser.read

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:57 GMT:0.2.1-Info Navigate to:https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=token&scope=user.read%20openid%20profile&client_id={...}&redirect_uri=http%3A%2F%2Flocalhost%3A4200&state=701cf0d1-b2c3-48d3-89a3-2b2be55d2120&nonce=d6713b95-2a3c-4e6e-93e4-f02c1682961a&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.1&client-request-id=befbc73a-c74f-4bce-ba48-b1b0ae9658c6&prompt=none&login_hint=...

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:57 GMT:0.2.1-Info LoadFrame: msalRenewFrameuser.read

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:58 GMT:0.2.1-Info Add msal frame to document:msalRenewFrameuser.read

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:58 GMT:0.2.1-Info Frame Name : msalRenewFrameuser.read Navigated to: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=token&scope=user.read%20openid%20profile&client_id={...}&redirect_uri=http%3A%2F%2Flocalhost%3A4200&state=701cf0d1-b2c3-48d3-89a3-2b2be55d2120&nonce=d6713b95-2a3c-4e6e-93e4-f02c1682961a&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.1&client-request-id=befbc73a-c74f-4bce-ba48-b1b0ae9658c6&prompt=none&login_hint=...

app.module.ts:62 APP Module Constructor!

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:59 GMT:0.2.1-Info State status:true; Request type:RENEW_TOKEN

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:59 GMT:0.2.1-Info State is right

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:59 GMT:0.2.1-Info Fragment has access token

app.module.ts:27 [MSAL] Fri, 18 Jan 2019 22:13:59 GMT:0.2.1-Info The user object received in the response is the same as the one passed in the acquireToken request

auth.service.ts:30 AuthService Constructor.
`

Is there a way to go around this? 
I will try to get a repro available.

**Comment by Gtyrande** [comment] 2019-01-20 03:11
@sameerag Hi, I'm sorry for reply to you so late. 
Our auth code is following: 

```
import * as Msal from 'msal';

export default class AuthService {
  constructor() {
    let PROD_REDIRECT_URI = 'https://*.chinacloudsites.cn';
    let redirectUri = 'http://localhost:8080/';
    if (window.location.hostname !== '127.0.0.1' && window.location.hostname !== 'localhost') {
      redirectUri = PROD_REDIRECT_URI;
    }
    this.applicationConfig = {
      clientID: '***',
      Scopes: ['profile', 'offline_access', 'api://***/access_as_user', 'https://***/***/user_impersonation'],
      itApiScope: ['api://***/access_as_user'],
      authApiScope: ['https://***/***/user_impersonation'],
      authority: 'https://login.microsoftonline.com/***/'
    };
    this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
      () => {
        // callback for login redirect
      },
      {
        redirectUri
      }
    );
  }

  login() {
    return this.app.loginPopup(this.applicationConfig.Scopes, "&prompt=login").then(
      idToken => {
        const user = this.app.getUser();
        if (user) {
          return user;
        } else {
          return null;
        }
      },
      error => {
        console.log(error);
      },
      () => {
        return null;
      }
    );
  }

  getUser() {
    const user = this.app.getUser();
    if (user) {
      return user;
    } else {
      return null;
    }
  }

  logout() {
    this.app.logout();
  }

  getItApiToken() {
    return this.app.acquireTokenSilent(this.applicationConfig.itApiScope).then(
      accessToken => {
        return accessToken;
      },
      error => {
        console.log(error);
        return this.app
          .acquireTokenPopup(this.applicationConfig.itApiScope)
          .then(
            accessToken => {
              return accessToken;
            },
            err => {
              console.error(err);
            }
          );
      }
    );
  }

  getAuthApiToken() {
    return this.app.acquireTokenSilent(this.applicationConfig.authApiScope).then(
      accessToken => {
        return accessToken;
      },
      error => {
        console.log(error);
        return this.app
          .acquireTokenPopup(this.applicationConfig.authApiScope)
          .then(
            accessToken => {
              return accessToken;
            },
            err => {
              console.error(err);
            }
          );
      }
    );
  }
```
I'm going to do some test with your comment, will feedback as soon as i get some new result.

**Comment by vramasam** [comment] 2019-01-21 11:39
@sameerag 

We have already added the iframe reload part in the code.

But the problem was not reloading of UI elements. But it's recreating Angular services(singleton classes). So it looses all the data hold by angular services(singleton classes).

**Comment by Ralms** [comment] 2019-01-23 00:36
@sameerag Same here, workaround from @Dedme at "[#479 (comment)](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/479#issuecomment-438110088)" worked for me also.
Not pretty but solves the issue for now.

**Comment by Dedme** [comment] 2019-01-23 00:46
Hello, Just wanted to note, that i had to unwind my use of the above fix as the AOT compiler does not like it.
the Angular AOT compiler does not handle multiple entry root modules, and as such will not compile the MSAL Module.

i really think the library needs to come with a standalone html+js page which handles that silent iframe.
this page either needs to be added outside the IIS settings as to avoid angular altogether, as all the variables are known, it just has to interact with window.parent and bootstrap itself appropriately.
at least this is my thought process.

**Comment by Ralms** [comment] 2019-01-23 01:05
@Dedme are you getting a warning during compilation like this?
`WARNING in Lazy routes discovery is not enabled. Because there is neither an entryModule nor a statically analyzable bootstrap code in the main file.`

Doing "Ng Serve" was working, then I tried to deploy it to my static website host and gives the error on the browser console: 
`Uncaught Error: No NgModule metadata found for 'function(){}'`
complaining about the main App Module.

**Comment by Dedme** [comment] 2019-01-23 01:18
@Ralms yes i was, this is directly the outcome of my most recent comments issue.

its going to come down to a choice, if you disable AOT in your build config it will continue to work.
but is not running AOT going to impact your performance too much? if not just disable it in the angular.json under the build step.

``` json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "PROJECTNAME": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          ...
          "configurations": {
            "production": {
              ...
              "aot": false, <-CHANGE HERE
              ...
            },
            ...
          }
        },
        ...
      }
    },
    ...
  },
  ..
}
```
if your did an "ng s --aot" (running serve with AOT turned on, it will fail also.

if this is blocking, running my code with the AOT off will get you out of trouble, but its not a good longterm solution.

**Comment by vramasam** [comment] 2019-01-23 04:49
This work around avoids the lazy loading problem.
Instead of using the code in main.ts.

Try using it in AppModule.ts, Load only MsalComponent. It work for us.
export class AppModule {
  constructor(private router: Router) {
  }
  ngDoBootstrap(ref: ApplicationRef) {
    if(window !== window.parent && !window.opener) {
        ref.bootstrap(MsalComponent);
     } else {
     //this.router.resetConfig(RouterModule);
      ref.bootstrap(AppComponent);
    }

}

**Comment by Dedme** [comment] 2019-01-23 05:52
@vramasam  does this stop all the services loading from 'root'? or does all the services/providers still load within the iframe?

**Comment by Ralms** [comment] 2019-01-23 20:16
Hi all, 
Just replaced @Dedme with the proposed solution by @vramasam which worked in my project after some tweaks.

In my app.module.ts I had to replace the property of NgModule
`bootstrap: [AppComponent]`
to
`entryComponents: [ AppComponent, MsalComponent ]`

App module gets initialized twice, but everything else isn't.

This is my app.module.ts
```
// Imports...
@NgModule({
  declarations: [
    AppComponent,
    MsalComponent,
    MainMenuComponent,
    AccountMenuComponent,
    OsNavComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production }),
    MsalModule.forRoot(environment.MsalConfig),
    SuiModule,
    PagesModule
  ],
  providers: [
    HttpServiceHelper,
    {provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true},
    AuthService
  ],
  entryComponents: [
    AppComponent,
    MsalComponent
  ]
})
export class AppModule {
  constructor() {
    console.log('APP Module Constructor!');
  }

  ngDoBootstrap(ref: ApplicationRef) {
    if (window !== window.parent && !window.opener)
    {
      console.log("Bootstrap: MSAL");
      ref.bootstrap(MsalComponent);
    }
    else
    {
    //this.router.resetConfig(RouterModule);
      console.log("Bootstrap: App");
      ref.bootstrap(AppComponent);
    }
  }
}
```
And MsalComponent is a dummy one as @Dedme did on his workaround
```
import { Component} from '@angular/core';
import { MsalService } from '@azure/msal-angular';

// This component is used only to avoid Angular reload
// when doing acquireTokenSilent()

@Component({
  selector: 'app-root',
  template: '',
})
export class MsalComponent {
  constructor(private Msal: MsalService) {
  }
}
```


I have console.log() is most of my constructors currently to test.

With this, the order of events in my app is currently the following: 
 1- APP Module Constructor
 2- Bootstrap: App (Comment I placed in bootstrap selector)
 3- AuthService Constructor (Singleton service)
 4- MENU INIT (component)
 5- OS-NAV Init  (component)
 6- Home INIT  (component)
 7- [Auth.login()] Login sucessfully.
 Call acquireTokenSilent()
 8- APP Module Constructor
 9- Bootstrap: MSAL
 Token retrieved

This works for me. Thank you guys @Dedme and @vramasam

**Comment by Dedme** [comment] 2019-01-23 23:06
Together, with our powers combined....

great work, i have also adopted the new method.

after some testing i will updated my original issue too

**Comment by vramasam** [comment] 2019-01-24 03:52
Hi @Dedme & @Ralms  I think some how we found the workaround for this issue.

It will be great helpful if any working production workaround for this issue also : https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/414. Please let me know how its handled in your projects

**Comment by sameerag** [comment] 2019-01-24 22:48
@Ralms @Dedme Would one of you be interested to provide a PR for the final solution that seems to work. If this PR mitigates the refresh issues for the community we are open to take it in our dev branch.

**Comment by Ralms** [comment] 2019-01-24 23:53
> Hi @Dedme & @Ralms I think some how we found the workaround for this issue.
> 
> It will be great helpful if any working production workaround for this issue also : #414. Please let me know how its handled in your projects

I'm simply not supporting any version of Internet Explorer, version 11 is 5 years old already.

**Comment by Dedme** [comment] 2019-01-25 00:19
@sameerag, i dont know how much of this can be PR'ed?
it might be more of a documentation, or part of a seed/sample application, but this doesn't change the package, just how its implemented... at least for this moment.
its as simple as - create dummy component, update appModule Bootstrap process.

I still don't think this is a 100% fix as it does bootstrap all of angular still

**Comment by sameerag** [comment] 2019-01-25 00:40
Sure @Dedme.  Thanks for the detail.
 @navyasric can we please follow up on documenting this to unblock folks using Angular for now?

**Comment by Dedme** [comment] 2019-02-04 01:19
@navyasric i think the ultimate solution, if you are looking into a revamp of the angular component is to not use the angular app as the reroute address. i think a small html/js file which does what the service does now for checking the iframe, and passing back to the parent would solve a lot of the bloating/double loading.

i dont currently know how you might get a page from the MSAL package into the root routing outside of angular. but i think the solution involves a url path which is outside of angular. it could be part of a angular scaffold which places a small html/js file in the assets folder, which should be set up for exclusion from the web server. 'msal_auth' or something, which is then used as the return path when in the iframe.

i do believe the current solution above is a workaround to the greater problem. 1 to use this library now we are having to change the appmodule bootstrap process, this could either break things and if nothing else ads a layer of complexity not needed by other packages. and 2 that the angular base modules are still bootstrapped. 3. there is more manual application changes than with other packages, it should be a import and configure, not involving creating our own dummy component (likely could be exported from the MSAL module), and change the entry/bootstrap process.

at least this is my 2 cents on the matter. it does currently work, but i think for ease of use and maintainability, there is something more that should be done.

**Comment by brianorwhatever** [comment] 2019-02-20 18:34
+1 to everything @Dedme said. The common pattern I've seen for silent refreshes has been an html page outside of the app. Before trying this library I was using this https://github.com/manfredsteyer/angular-oauth2-oidc one and it has a silent-refresh.html page that does this. I will probably be switching back to this library now while this has such an ugly workaround.

**Comment by DeanB2015** [comment] 2019-04-01 14:34
@brianorwhatever  Did you switch back to https://github.com/manfredsteyer/angular-oauth2-oidc ?  I'm debating if I should make the switch or make a fix.  What's your recommendation?

**Comment by brianorwhatever** [comment] 2019-04-01 18:24
@DeanB2015 yeah I did unfortunately

**Comment by sameerag** [comment] 2019-06-24 23:53
Linking with #786 but leaving this open as this is a popular requirement for Angular Wrapper design. The gist is to offload the redirect to a separate HTML: A HTML/JS file to check the iFrame and passing the control back to parent - saving the app from reloading every time a silent token call is made in the background.

**Comment by DarylThayil** [comment] 2019-07-25 22:41
closing because it is tracked in #786

**Comment by aszalacinski** [comment] 2019-07-30 14:27
@DarylThayil Why is this being closed? The OP was having an issue with a VUE.JS app. It appears the discussion morphed from the VUEJS issue to updating the angular library. Is there a recommended solution/pattern to handle the redirect that's not related to Angular?

**Comment by DarylThayil** [comment] 2019-08-01 16:58
Apologies, I think I misunderstood this issue. Reopening

**Comment by aszalacinski** [comment] 2019-08-01 22:22
@DarylThayil thank you! Is there anything in regards to a recommended pattern the msal could publish that would allow this issue to be closed up? Something for we engineers who have the luxury of getting to work with languages that do not have the benefit of the MS Mothership templates? :) I think there is enough interested talent on this forum to craft a community solution with the MSAL team guidance.

**Comment by DarylThayil** [comment] 2019-08-02 19:26
@sameerag  I think this is not necessarily an angular issue but might be related to sandboxing the iframes!

**Comment by DarylThayil** [comment] 2019-08-02 19:26
@step-lee  is this what your pr was fixing

**Comment by sameerag** [comment] 2019-08-02 21:23
@DarylThayil Yes, I am aware that this is not necessarily angular issue. This issue exists in MSAL core JS. The reason for tagging this in angular space is to pursue the feasibility of a path in Angular framework to mitigate the redirect reload issue before we fix MSAL JS.

I think part of @step-lee 's fix may help here.

**Comment by AndrewCraswell** [comment] 2019-08-13 19:47
I think @step-lee's PR is no longer being pursued... is there a chance this will be picked up in the near future? I've just encountered this in my app that about to go to production soon... this is a big performance issue for us.

**Comment by jasonnutter** [comment] 2019-08-13 19:50
@AndrewCraswell I am working now to re-implement #622. Don't have an exact ETA at the moment, but know that it is high priority for us and we are planning to include it in an upcoming release.

**Comment by sameerag** [comment] 2019-10-02 21:13
#939 Addresses this issue. 

For all folks following this thread for an angular solution, the Angular wrapper upcoming this quarter(tracked with #786) will have #939 when released. Closing this issue.

**Closed by sameerag** 2019-10-02 21:13 UTC
Labels: Feature Request, angular, performance
