### ISSUE TITLE
 [Angular 4 app] - IE 11 intermittently returning NULL in the redirectURL

### ISSUE THREAD

**Issue by smehra711** [AzureAD/microsoft-authentication-library-for-js#330] opened 2018-06-19 15:07 UTC
We have developed a Single page application in Angular 4. Our first screen is Login Screen where we are using MSAL.js library to authenticate username/password. We are facing two intermittent issues in IE 11 browser only while authenticating username/password using Microsoft Authentication Library(MSAL.js) and due to which we see blank screen sometimes. [Note: In other browsers like chrome and safari, the functionality works as expected.]

Issue 1: IE 11 intermittently returning NULL in the redirect URL For ex: https://domain-name/null  

Steps to reproduce the issue: 

1.	In my App, when clicking on login button from home page, it calls msal.js login function which redirects to this link https://login.microsoftonline.com/....... 
2.	Microsoft library (msal.js) after authenticating username and password information,  should come back to the login screen from where it started but it is going to  https://domain-name/null 
3.	Null stays there for a second and then it stop showing at the end of the URL, and the browser screen is blank. Now if I refresh the browser, it opens https://domain-name/home/login 

Issue 2:  In IE 11, sometimes after authenticating username and password, redirect URL is incorrect:

for example this is the login URL:: https://domain-name/home/login
But after authentication it redirects to: https://domain-name/home

**Comment by smehra711** [comment] 2018-06-28 18:21
any update?

**Comment by nehaagrawal** [comment] 2018-07-03 21:54
@smehra711 Ths is an existing issue with the Edge and IE browsers. We have documented this in our ADAL library but this applies here as well. Currently, we only have the work around listed here: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge#issues

To give you some context since the session/local storage is cleared during the redirect in IE/Edge and the MSAL stores the url of the page where user started in browser cache. Now since the cache is cleared, MSAL is unable to recreate the url where user started after the login is done and is appending null.

One workaround is to set NavigateToLoginRequestUrl flag to false in MSAL config. By default this flag is true. If you do this then user wouldn't be redirected to the page where he/she started but in the callback, you can reset the browser location to your desired url using window.location.href.

Please let me know if you are still facing issues.

**Comment by jkga** [comment] 2018-07-04 01:40
@smehra711 
> [Note: In other browsers like chrome and safari, the functionality works as expected.]

based on my own experience, intermittently returning `NULL` is also happening even in chrome browser not just IE. If you get redirected to `MS login page` and waited for a minute, you will notice that after successfully logging in you will be redirected to `https://your-domain/null`

**Comment by smehra711** [comment] 2018-07-10 16:44
After adding redirectURi and setting NavigateToLoginRequestUrl flag to false in MSAL config, it fixed the IE 11 null issue. Thank you so much for your help on this But I am having another issue now on Window 7 with IE 11.0.9600 version.

{
            redirectUri: this.redirectUri,
            navigateToLoginRequestUrl: false

        }

	The issue is from login screen when I call msal login function, it redirects back to the url with # sign. This is happening only on Window 7 with IE 11.0.9600 version

https://domain-name/home/login#

Can you please help us solving this issue, we have a big team using Window 7 with IE 11.0.9600 version.

**Comment by smehra711** [comment] 2018-07-10 16:55
Hi Wen,

After adding the redirectURi and setting NavigateToLoginRequestUrl flag to false in MSAL config, it fixed the IE 11 null issue. Thank you so much for your help on this But I am having another issue now on Window 7 with IE 11.0.9600 version.

{
            redirectUri: this.redirectUri,
            navigateToLoginRequestUrl: false

        }


  *   The issue is from login screen when I call msal login function, it redirects back to the url with # sign. This is happening only on Window 7 with IE 11.0.9600 version

https://domain-name/home/login#

Can you please help us solving this issue, we have a big team using Window 7 with IE 11.0.9600 version.

Thanks,
Saloni

**Comment by nehaagrawal** [comment] 2018-07-18 20:18
duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/347. Please track this issue there.

**Closed by nehaagrawal** 2018-07-18 20:18 UTC

**Comment by nehaagrawal** [comment] 2018-08-18 00:58
@smehra711 @jkga  This is fixed and released in MSAL 0.2.2. Please check release notes for more details.
