### ISSUE TITLE
Access Panel Applications links break login

### ISSUE THREAD

**Issue by hkhamm** [AzureAD/microsoft-authentication-library-for-js#1326] opened 2020-02-28 23:57 UTC
## Library
msal@1.2.1

## Framework
react@16.13.0

## Description
When opening our app from a link on our tenant's Access Panel Applications page (https://account.activedirectory.windowsazure.com/r#/applications), then calling `UserAgentApplication.loginRedirect({ scopes: [<clientId>] })` results in a redirect where we enter our MS credentials, and then we are redirected back to the app. The authentication process then stops with the id_token as a field in the url's hash. Looking in session storage `msal.interaction_status` is `inProgress`. Calls to `UserAgentApplication.getAccount()` return `null`.

When going directly to the page in a new tab, or access the page any other way, the authentication succeeds and calls to `getAccount()` properly return the filled `Account` object.

## Security
no

## Regression
Not sure, just found out about the Access Panel Applications page from a client.

## Configuration
Please provide your MSAL configuration options.

```js
{
    auth: {
        clientId: <client id>,
        authority: "https://login.microsoftonline.com/common",
        validateAuthority: true,
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE()
    }
}
```

## Reproduction steps
1. Create an application in the Azure Portal
2. Setup a React app that uses the MSAL library to request tokens using the redirect flow with the config above.
3. Deploy the app to Azure and then register the app in your tenant.
4. Go to your tenant's Access Panel Applications page and use the link to open your app.
5. When attempting to call `loginRedirect({ scopes: [<clientId>] })` from an instance of `UserAgentApplication` the `msal.interaction_status` in session storage will be `inProgress` and calls to `getAccount()` will return null.

## Expected behavior
The library should not stop with `msal.interaction_status` is `inProgress`. It should instead complete the login and subsequent calls to `getAccount()` should return the `Account` object.

## Browsers
Happens in all browsers tested.

**Comment by hkhamm** [comment] 2020-02-29 02:17
Found the issue in `UserAgentApplication.ts`. After the redirect, in the constructor checks 
`if (urlContainsHash && !WindowUtils.isInIframe() && !WindowUtils.isInPopup())` before calling `handleAuthenticationResponse`.  The first two were true, but `!WindowUtils.isInPopup()` is false. That method (in `WindowUtils.ts`) is doing this:

```
static isInPopup(): boolean {
    return !!(window.opener && window.opener !== window)
}
```

My hacky fix was to manually set `window.opener = null` on my login page. This caused `!WindowUtils.isInPopup()` to return true and allowed me to successfully complete the login.

My guess is the Access Panel is making `window.opener` something other than `null`, even though I'm not in a popup.

**Comment by jasonnutter** [comment] 2020-03-02 16:37
@hkhamm Yes, this is the recommended workaround for now. We're aware of this issue, and plan to have a fix soon. Thanks!

**Comment by hkhamm** [comment] 2020-03-02 17:29
Sadly, the `window.opener = null` fix does not work in original Edge. We ended up forking so we could remove the `!WindowUtils.isInPopup()` check. Any suggestions @jasonnutter?

**Comment by jasonnutter** [comment] 2020-03-02 20:56
@hkhamm Ah, that's unfortunate, good to know. We have a number of other customers asking about this, so we'll get this prioritized. Not sure of another workaround at the moment.

**Comment by jasonnutter** [comment] 2020-03-02 20:57
Closing as a duplicate of #1301.

**Closed by jasonnutter** 2020-03-02 20:57 UTC
Labels: bug, known-issue
