### ISSUE TITLE
Using extraQueryParameters in acquireTokenRedirect causes duplicate parameter error

### ISSUE THREAD

**Issue by trevonmckay** [AzureAD/microsoft-authentication-library-for-js#284] opened 2018-04-23 16:15 UTC
In our application our error handler for **acquireTokenSilent** listens for a consent required error. When it that condition is true we attempt to force the user to re-consent using acquireTokenRedirect with **prompt=consent** as an extra query parameter. Unfortunately using the parameter **prompt** in **extraQueryParameters** causes the following error

**AADSTS90004: The request is not properly formatted. The parameter 'prompt' is duplicated.**

```
if (error.indexOf('consent_required') !== -1) {
   authContext.acquireTokenRedirect(scope, authority, user, 'prompt=consent');
} else {
   authContext.acquireTokenRedirect(scope);
}
```

The expected functionality would be anything in extraQueryParameters overrides what has already been preconfigured.

**Comment by itanex** [comment] 2018-05-24 01:20
This prevents proper usage of the login_hint parameter which allows for prepopulating of the username. When using the following line, it does not allow me to have the username auto-selected.

`clientApplication.loginPopup(null, "login_hint=v-brwood@microsoft.com").then(onSignin);`

I would expect this library to provide a way to utilize the parameters in the V2 protocol as I see fit; expected STS to error out when its not well-formed.

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit

**Comment by rohitnarula7176** [comment] 2018-06-01 18:06
@trevonmckay Closing this as Duplicate of #313

**Closed by rohitnarula7176** 2018-06-01 18:06 UTC
