### ISSUE TITLE
Error 'User login is required' and app is getting redirected back to login page

### ISSUE THREAD

**Issue by SujitGodavarti** [AzureAD/microsoft-authentication-library-for-js#232] opened 2018-01-25 06:07 UTC
I am using MSAL in my angular app for authentication purpose. The error that is being thrown is "error getting accees token: user_login_error:User login is required" as shown in below image and the app gets redirected back to login page again. How can I successfully complete the login and get the token? 
I created a github repo for the code at 'https://github.com/SujitGodavarti/SamplePortalApp' with detailed instructions on how to run it mentioned in the ' README.md' file. 

![img3](https://user-images.githubusercontent.com/20764924/35373384-3fa7997e-01f2-11e8-9d6d-c02c70458e3c.png)
Please help me solve this issue.

**Comment by rohitnarula7176** [comment] 2018-01-26 01:03
@SujitGodavarti Thank you for providing me with the code repro. I am investigating your code and will get back to you within a day.

**Comment by rohitnarula7176** [comment] 2018-01-29 21:56
@SujitGodavarti I noticed a couple of issues with the code. I got busy with other stuff. I will work on your code and send you a PR in a couple of days.

**Comment by AnnaShk** [comment] 2018-01-29 22:23
Hi  @rohitnarula7176 

The issue is with routing, not msal related. So you can close it.

Thanks.

**Comment by rohitnarula7176** [comment] 2018-01-31 19:50
@SujitGodavarti As AnaShk mentioned, there is an issue with your routing and the way you have structured your code and not related to Msal. For instance, from your dashboard.component.ts, you call 
```
var requestoptions = this.apiRequest.makeRequest(RequestMethod.Get, 'Tasks/statuses');
```
In the makeRequest method, you are doing an asynchronous operation by calling getAuthenticationToken which is why the value of requestoptions in your code will always be undefined. The makeRequest api should return a promise if its doing an asynchronous operation. There are many other issues like this which I have found.

**Closed** 2018-01-31 19:54 UTC

**Comment by JBrownie77** [comment] 2018-09-06 18:27
Hi, I am running into the same issue. In my auth guard I call acquireTokenSilent to ensure that the token is available, but upon the redirect back to my app the guard is triggered before tokenRecievedCallback, so acquireTokenSilent says the user isn't logged in even though they just logged in. Upon refresh the token is available.

Is there a proper way to do this using an auth guard and waiting for the token to be available?
Thanks!

**Comment by tassadarBT** [comment] 2019-02-25 11:20
I have this same error aswell. What I don't understand is why it breaks fatally and you need to clear the local storage/ session storage / cookies to fix it back and be able to login again. Did you guys added any try/catches and reset the local storage or whatever is used to store the state of the auth.  I'm pretty sure somewhere your code is bad and you should of at least added some guards yourselves. We are the users, we are usually copy-paste idiots who use the interface, without understanding the inner workings.  A google library never done this shit to me.
