### ISSUE TITLE
Getting endpoints_resolution_error behind corporate proxy, also shows error connecting to proxy

### ISSUE THREAD

**Issue by aqibnaushad** [AzureAD/microsoft-authentication-library-for-js#6483] opened 2023-09-15 13:08 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description
@Robbie-Microsoft : Please help. 
I am trying to call Microsoft Graph API in electron desktop application following tutorial https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-nodejs-desktop 

When I hit "Sign In", I am getting error which I have mentioned in error message.

But when I do a fetch in the same app using HttpsAgentProxy, it works.
const fetch = require("node-fetch") //verion 2.7.0
const {HttpsProxyAgent} = require("https-agent-proxy");
const proxy = new HttpsProxyAgent("http://proxy.corporate.net:8080");
const data = await fetch(
  "https://login.microsoftonline.com/<id>/v2.0/.well-known/openid-configuration",
  {
	agent: proxy,
	method: "GET",
	headers: {
	  Accept: "application/json",
	  "Content-Type": "application/json",
	},
  }
)
  .then((res) => res.json())
  .then((rootData) => {
	console.error(rootData)
	return rootData;
  })
  .catch((e) => {
	console.error(`Unable to fetch data for user: ${e}`);
  });

Also I am getting below alert continuously(If I hit ok, it comes again) after API call fails
UncaughtException NodeAuthError: loopback_server_timeout: Timed out waiting for auth code listener to be registered

### Error Message

[Fri, 15 Sep 2023 12:44:13 GMT] : [] : @azure/msal-node@2.1.0 : Info - getTokenCache called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Info - getAuthCodeUrl called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - initializeRequestScopes called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - buildOauthClientConfiguration called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/<id>
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - createAuthority called
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get cloud discovery metadata  from authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Found cloud discovery metadata in authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get endpoint metadata from authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in the config... Attempting to get endpoint metadata from the hardcoded values.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in hardcoded values... Attempting to get endpoint metadata from the network metadata cache.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find cached endpoint metadata... Attempting to get endpoint metadata from the network.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Authority.getEndpointMetadataFromNetwork: attempting to retrieve OAuth endpoints from https://login.microsoftonline.com/<id>/v2.0/.well-known/openid-configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Authority.getEndpointMetadataFromNetwork: Error: Error connecting to proxy. Http status code: 400. Http status message: Bad Request
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Error - Did not find endpoint metadata from network... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.(node:3716) UnhandledPromiseRejectionWarning: ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/<id>/v2.0/.well-known/openid-configuration
    at ClientAuthError.createEndpointDiscoveryIncompleteError (I:\assistant\graph-proxy\node_modules\@azure\msal-common\dist\index.cjs:938:16)
    at AuthorityFactory.createDiscoveredInstance (I:\assistant\graph-proxy\node_modules\@azure\msal-common\dist\index.cjs:8267:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PublicClientApplication.createAuthority (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:339:16)
    at async PublicClientApplication.buildOauthClientConfiguration (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:231:37)
    at async PublicClientApplication.getAuthCodeUrl (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:51:34)
    at async PublicClientApplication.acquireTokenInteractive (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\PublicClientApplication.cjs:116:33)
    at async AuthProvider.getTokenInteractive (I:\assistant\graph-proxy\App\AuthProvider.js:89:34)
    at async AuthProvider.getToken (I:\assistant\graph-proxy\App\AuthProvider.js:64:28)
    at async AuthProvider.login (I:\assistant\graph-proxy\App\AuthProvider.js:27:30)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:3716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### Msal Logs

[Fri, 15 Sep 2023 12:44:13 GMT] : [] : @azure/msal-node@2.1.0 : Info - getTokenCache called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Info - getAuthCodeUrl called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - initializeRequestScopes called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - buildOauthClientConfiguration called
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/<id>
[Fri, 15 Sep 2023 12:44:16 GMT] : [54cb575d-4e67-4614-8fa0-7b1c9eaf6b58] : @azure/msal-node@2.1.0 : Verbose - createAuthority called
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get cloud discovery metadata  from authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Found cloud discovery metadata in authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get endpoint metadata from authority configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in the config... Attempting to get endpoint metadata from the hardcoded values.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in hardcoded values... Attempting to get endpoint metadata from the network metadata cache.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find cached endpoint metadata... Attempting to get endpoint metadata from the network.
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Authority.getEndpointMetadataFromNetwork: attempting to retrieve OAuth endpoints from https://login.microsoftonline.com/<id>/v2.0/.well-known/openid-configuration
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Authority.getEndpointMetadataFromNetwork: Error: Error connecting to proxy. Http status code: 400. Http status message: Bad Request
[Fri, 15 Sep 2023 12:44:16 GMT] : [] : @azure/msal-node@2.1.0 : Error - Did not find endpoint metadata from network... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.(node:3716) UnhandledPromiseRejectionWarning: ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/<id>/v2.0/.well-known/openid-configuration
    at ClientAuthError.createEndpointDiscoveryIncompleteError (I:\assistant\graph-proxy\node_modules\@azure\msal-common\dist\index.cjs:938:16)
    at AuthorityFactory.createDiscoveredInstance (I:\assistant\graph-proxy\node_modules\@azure\msal-common\dist\index.cjs:8267:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PublicClientApplication.createAuthority (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:339:16)
    at async PublicClientApplication.buildOauthClientConfiguration (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:231:37)
    at async PublicClientApplication.getAuthCodeUrl (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\ClientApplication.cjs:51:34)
    at async PublicClientApplication.acquireTokenInteractive (I:\assistant\graph-proxy\node_modules\@azure\msal-node\dist\client\PublicClientApplication.cjs:116:33)
    at async AuthProvider.getTokenInteractive (I:\assistant\graph-proxy\App\AuthProvider.js:89:34)
    at async AuthProvider.getToken (I:\assistant\graph-proxy\App\AuthProvider.js:64:28)
    at async AuthProvider.login (I:\assistant\graph-proxy\App\AuthProvider.js:27:30)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:3716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "<id>",
        authority: `${AAD_ENDPOINT_HOST}<id>`,
        knownAuthorities: [`${AAD_ENDPOINT_HOST}<id>`]
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: LogLevel.Verbose,
        },
        proxyUrl: "http://proxy.corporate.net:8080"
    },
}
```

### Relevant Code Snippets

```javascript
Everything is same as mentioned in tutorial https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-nodejs-desktop except for this authConfig

const { LogLevel } = require("@azure/msal-node");
const { HttpProxyAgent } = require('http-proxy-agent');

/**
 * Configuration object to be passed to MSAL instance on creation.
 * For a full list of MSAL.js configuration parameters, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/configuration.md
 */
const AAD_ENDPOINT_HOST = "https://login.microsoftonline.com/"; // include the trailing slash

const msalConfig = {
    auth: {
        clientId: "<id>",
        authority: `${AAD_ENDPOINT_HOST}<id>`,
        knownAuthorities: [`${AAD_ENDPOINT_HOST}<id>`]
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: LogLevel.Verbose,
        },
        proxyUrl: "http://proxy.corporate.net:8080"
    },
};

/**
 * Add here the endpoints and scopes when obtaining an access token for protected web APIs. For more information, see:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
 */
const GRAPH_ENDPOINT_HOST = "https://graph.microsoft.com/"; // include the trailing slash

const protectedResources = {
    graphMe: {
        endpoint: `${GRAPH_ENDPOINT_HOST}v1.0/me/calendar/events`,
        scopes: ["Calendars.Read"],
    }
};


module.exports = {
    msalConfig: msalConfig,
    protectedResources: protectedResources,
};
```

### Reproduction Steps

Tutorial https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-nodejs-desktop using behind corporate proxy

### Expected Behavior

The API call should return the data 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by Robbie-Microsoft** [comment] 2023-09-15 15:14
I'll try to reproduce this; thanks for providing verbose logs. In the mean time, you can make your own network module with your workaround code. See [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/custom-INetworkModule-and-network-tracing) for details on how to implement your own network module; start by reading through app.ts.

**Comment by aqibnaushad** [comment] 2023-09-21 07:13
Checked with the [sample ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/custom-INetworkModule-and-network-tracing) shared above, still getting the **endpoints_resolution_error**
Used HttpClientCurrent, HttpClientAxios & INetworkModule all the three mentioned in sample.

**Comment by bgavrilMS** [comment] 2023-09-26 08:42
Hi @aqibnaushad - if you just use https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientAxios.ts object (no MSAL), can you use it to make a call to  https://[login.microsoftonline.com/b458eb0a-178f-4197-8da4-514c0fe6f17b/v2.0/.well-known/openid-configuration](https://login.microsoftonline.com/b458eb0a-178f-4197-8da4-514c0fe6f17b/v2.0/.well-known/openid-configuration) ?

This extensibility point gives you full control over the HTTP stack, so it's up to you to set it in such a way as to take into account the proxy.

**Comment by bgavrilMS** [comment] 2023-10-02 16:51
Closing due to no follow up

**Comment by aqibnaushad** [comment] 2023-10-03 09:09
@bgavrilMS : Thanks for your help, earlier I had tried the sample but gave proxy as part of msal config, when I gave proxy in HttpClient it worked.

**Closed as completed** 2023-10-03 09:09 UTC
Labels: question, msal-node, no-issue-activity, bug-unconfirmed, public-client

**Comment by bgavrilMS** [comment] 2023-10-03 11:08
Thanks for confirmation @aqibnaushad
