### ISSUE TITLE
MSAL authentication is not working with "Connected to Windows" Account

### ISSUE THREAD

**Issue by piyushparamane** [AzureAD/microsoft-authentication-library-for-js#2673] opened 2020-12-01 06:25 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.4.0` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 8.2
## Description
"Connected to WIndows" Accounts are not logging in anymore 

### **Issue Description**
The authentication using msal was working for "Connected to Windows" Accounts (Work or school) before. But after we updated "account type" in Azure AD app registration from : "**Accounts in any organizational directory (Any Azure AD directory - Multitenant)**" to : "**Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)**" , the authentication is not working anymore. _If we try with any other account (which is not connected to windows), login is working fine._

**Error we are seeing in console:**

“Connected to windows” scenario : we are getting InteractionRequiredAuthError
main-es2015.87e6231bd65afafe96ac.js:1 acquireTokenFailure InteractionRequiredAuthError:

![accounts](https://user-images.githubusercontent.com/18009000/100703947-9cae2180-33ca-11eb-9d7e-c267f95e0327.jpg)

![AzureAD](https://user-images.githubusercontent.com/18009000/100704181-0af2e400-33cb-11eb-8900-986124a7fd60.jpg)

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment] 2020-12-01 17:13
Closing as duplicate of #2672

**Closed by tnorling** 2020-12-01 17:13 UTC
Labels: bug-unconfirmed
