### ISSUE TITLE
Infinite loop on msal:acquireTokenStart /msal:acquireTokenSuccess issue when switchMap to a azdo api

### ISSUE THREAD

**Issue by byunru** [AzureAD/microsoft-authentication-library-for-js#4068] opened 2021-09-16 19:03 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

"@azure/msal-angular": "^2.0.3",     "@azure/msal-browser": "^2.17.0",

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

    "@azure/msal-angular": "^2.0.3",     "@azure/msal-browser": "^2.17.0",

### Description

If I use of(1), won’t lead to infinite loop, but when I replace of(1) with this.getRuns(project, pip.id), will lead to infinite loop until browser out of memory
In getRuns, I have console.log, which also never been hit
getRuns is a function of http get list of piepelin run list (https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/list?view=azure-devops-rest-6.0)
====================================================================
  transform(project: string, pipeline: any) {
    return of(pipeline).pipe(
      switchMap((pip:any) => {    

        return of(1)   //  this.getRuns(project, pip.id)
                .pipe(
                  map((run:any) => {
                    console.log(run)
                    pip.run = run
                    return pip
                  }))
      })
    )
  }
====================================================================

### Error Message

During infinite loop, the console output until browser our of memory.

### Msal Logs

During infinite loop, the console output :
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 7 app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart app.module.ts:29:10
[Thu, 16 Sep 2021 18:29:33 GMT] : @azure/msal-angular@2.0.3 : Info - Interceptor - 1 scopes found for endpoint 3 app.module.ts:29:10

### MSAL Configuration

```javascript
{
    auth: config.getAuth(),
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
}
```

### Relevant Code Snippets

```javascript

```

### Reproduction Steps

download my code, unzip
npm i
ng serve

### Expected Behavior

shouldn't getting into infinite loop

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by byunru** [comment] 2021-09-17 17:19
@derisen ,  Do you have time to take a look on this issue?  Thanks.

**Comment by derisen** [comment] 2021-09-20 18:07
@byunru apologies for late response. I was not able to reproduce your issue using your `this.getRuns(project, pip.id)` method:

![ss](https://user-images.githubusercontent.com/13197548/134050829-45b78701-092c-470c-a073-7f287460ad0b.png)

However I might be missing what you are intending to do here. Your issue description is rather cryptic. Can you clarify:

* What are you trying to achieve here?
* What are your exact msal configuration parameters?

Please also configure msal to emit `verbose` logs (instead of `info`), which provides more detail, and share it with us.

**Comment by byunru** [comment] 2021-09-21 02:27
@derisen  I guess your devops project doesn't has any yaml pipeline created, so returns empty, can you add at least one (dummy) yaml pipeline to see what will happen? 
I can do a screen sharing demo the issue if ok from your side. 

emit verbose logs, output same pattern:
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - MSAL Interceptor activated 						app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - getting scopes for endpoint 		app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - no scopes for endpoint 			app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - MSAL Interceptor activated 						app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - getting scopes for endpoint 		app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - no scopes for endpoint 			app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - MSAL Interceptor activated 						app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - getting scopes for endpoint 		app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - Interceptor - no scopes for endpoint 			app.module.ts:25:10
[Tue, 21 Sep 2021 01:53:03 GMT] : @azure/msal-angular@2.0.3 : Verbose - MSAL Interceptor activated						app.module.ts:25:10
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

**Comment by byunru** [comment] 2021-09-21 16:21
@derisen   I got project and pipeline data, means protectedResourceMap should be correct. once using switchMap on existing pipeline, the behavior becomes unpredictable.

**Comment by derisen** [comment] 2021-09-23 15:20
@byunru I was able to reproduce your issue finally. Will try to debug further and get back to you.

**Comment by derisen** [comment] 2021-09-28 01:42
@byunru I've looked a bit more into your issue. During debugging, msal successfully fetched the token each time and attached it to the request going to the `runs` endpoint. The endpoint responds with the data so the issue is not related to authentication/authorization. The problem lies with the usage of RxJS (or rather the usage of RxJS with respect to this endpoint), which keeps making a request to the endpoint (msal simply complies with grabbing and attaching the access token). Unfortunately I'm not familiar enough with either the DevOps Rest API or the RxJS to advise you on how to go about it. Let us know if there's anything else I can help with.

**Comment by byunru** [comment] 2021-09-30 05:25
@derisen  you are right, something wrong with my usage of RxJS, you may close this case, thanks for the investigation.

**Comment by samuelkubai** [comment] 2021-09-30 11:29
Thank you @byunru for raising and aiding in the resolution of this issue. Closing this issue now.

**Closed by samuelkubai** 2021-09-30 11:29 UTC
Labels: question, msal-angular, msal-browser, answered
