### ISSUE TITLE
Support for angular 17

### ISSUE THREAD

**Issue by javieralfaya** [AzureAD/microsoft-authentication-library-for-js#6844] opened 2024-01-24 12:25 UTC
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

None

### Description

Please, I need to know: Does it support (MSAL Angular v3) angular 17 version?

Thanks in advance

**Comment by Flywheel** [comment] 2024-01-24 16:08
This request for update has been pending for a while. https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6719  Note that Jaime Still made some progress worth examining. https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6719#issuecomment-1890233947  But I find Microsoft's lengthy delay on this is concerning. I wish more could be done to assure folks starting out with fresh modern Angular apps that MSAL/ADB2C will prove to be a solid bet.

**Comment by EmLauber** [comment] 2024-01-25 18:46
Closing as a duplicate of #6719

**Closed as completed by EmLauber** 2024-01-25 18:46 UTC
Labels: question, documentation, msal-angular, msal-react, public-client
