### ISSUE TITLE
MSAL Interceptor seems to violate the library's own rule, producing a console error (but not affecting functionality)

### ISSUE THREAD

**Issue by nickeeromo** [AzureAD/microsoft-authentication-library-for-js#4862] opened 2022-06-03 18:59 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.2.0

### Description

When accessing my application for the first time in a while, there is one MSAL error log and one regular console error log. But the application continues to flow as if nothing had happened.

### Error Message

![Uploading image.png…]()
Looks like the screenshot's not getting uploaded, so here we go. Copied directly as-is from Chrome's DevTools' console logs:

[Fri, 03 Jun 2022 18:03:41 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:initializeStart
main.js:1
[Fri, 03 Jun 2022 18:03:41 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:initializeEnd
main.js:1
[Fri, 03 Jun 2022 18:03:41 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:handleRedirectStart
(index):1 You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.
polyfills.js:1
[webpack-dev-server] Live Reloading enabled.
main.js:1
[Fri, 03 Jun 2022 18:03:42 GMT] : @azure/msal-angular@2.3.0 : Info - Interceptor - 1 scopes found for endpoint
main.js:1
**[Fri, 03 Jun 2022 18:03:42 GMT] : @azure/msal-angular@2.3.0 : Error - Interceptor - acquireTokenSilent rejected with error.
Invoking interaction to resolve.**
loggerCallback @ main.js:1
p.executeCallback @ main.js:1
p.logMessage @ main.js:1
p.error @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
_error @ main.js:1
error @ main.js:1
(anonymous) @ main.js:1
invoke @ polyfills.js:1
onInvoke @ main.js:1
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:1
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
x @ polyfills.js:1
Promise.then (async)
Ie @ polyfills.js:1
X @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
Be @ polyfills.js:1
je @ polyfills.js:1
(anonymous) @ polyfills.js:1
n @ runtime.js:1
(anonymous) @ 11.js:1
main.js:1
**ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.**
    at g.y [as constructor] (main.js:1:43016)
    at new g (main.js:1:23525)
    at g.createInteractionInProgressError (main.js:1:24889)
    at d.setInteractionInProgress (main.js:1:225287)
    at F.preflightInteractiveRequest (main.js:1:358776)
    at F.preflightBrowserEnvironmentCheck (main.js:1:358554)
    at d.<anonymous> (main.js:1:348998)
    at N (main.js:1:16206)
    at Object.next (main.js:1:16311)
    at main.js:1:15247
    at je (polyfills.js:1:136730)
    at new o (polyfills.js:1:139226)
    at f (main.js:1:14982)
    at F.acquireTokenRedirect (main.js:1:348810)
    at _e.acquireTokenRedirect (main.js:1:1888)
    at ie.acquireTokenInteractively (main.js:1:10597)
    at main.js:1:9649
    at main.js:1:762891
    at c._error (main.js:1:761605)
    at c.error (main.js:1:753095)
yg @ main.js:1
handleError @ main.js:1
next @ main.js:1
next @ main.js:1
_next @ main.js:1
next @ main.js:1
(anonymous) @ main.js:1
c @ main.js:1
next @ main.js:1
emit @ main.js:1
(anonymous) @ main.js:1
invoke @ polyfills.js:1
run @ polyfills.js:1
runOutsideAngular @ main.js:1
onHandleError @ main.js:1
handleError @ polyfills.js:1
runGuarded @ polyfills.js:1
p.microtaskDrainDone @ polyfills.js:1
x @ polyfills.js:1
Promise.then (async)
Ie @ polyfills.js:1
X @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
Be @ polyfills.js:1
je @ polyfills.js:1
(anonymous) @ polyfills.js:1
n @ runtime.js:1
(anonymous) @ 11.js:1
main.js:1
[Fri, 03 Jun 2022 18:03:42 GMT] : [1c0e7351-a2db-4891-9e87-f44b3281a110] : @azure/msal-common@6.3.0 : Info - in acquireToken call
main.js:1
[Fri, 03 Jun 2022 18:03:42 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:loginSuccess

### Msal Logs

Same as the ones under the "Error Message" section

### MSAL Configuration

```javascript
{
  auth: {
    clientId: msalConfig.clientId,
    authority: `${msalConfig.authority}${b2cPolicies.signInSignUpPolicy}`,
    knownAuthorities: [
      `${msalConfig.authority}${b2cPolicies.signInSignUpPolicy}`,
    ],
    redirectUri: msalConfig.redirectUri,
    postLogoutRedirectUri: msalConfig.logOutRedirectUri,
    loginFailedRoute: msalConfig.loginFailedRoute,
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie:
      window.navigator.userAgent.indexOf("MSIE ") > -1 ||
      window.navigator.userAgent.indexOf("Trident/") > -1
  }
}
```

### Relevant Code Snippets

```javascript
export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: { scopes: [...b2cScopes] },
    loginFailedRoute: msalPublicClientAppConfig.auth.loginFailedRoute
  };
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap: new Map([
      [ environmentConfigs.paymentPortalProxy, [ msalPublicClientAppConfig.auth.clientId ] ]
    ])
  }
}
```

### Reproduction Steps

1. Access an application route that is protected by the MsalGuard
2. Get redirected to a sign-in flow and sign in
3. Get redirected back to the application as normal
4. DON'T explicitly clear local storage or sign out
5. Sign in the next day (I'm assuming just after the tokenage information all expires)
6. Observe the aforementioned error logs

### Expected Behavior

No console errors (that BrowserAuthError) as application flow seems expected by the message in the MSAL error message: rejected with error. Invoking interaction to resolve.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2022-06-06 18:18
@nickeeromo It looks like you may have two parallel http requests that are triggering the interceptor, which both fail, and both attempt to do `loginRedirect`, so this behavior makes sense if so. For now, this error can be ignored, assuming the silent requests succeed once you complete the redirect operation.

**Comment by ozkoidi** [comment] 2022-06-08 08:02
I see the same exceptions on Application Insights. In my case is not 2 but 5 calls that are done within the same second.
I think there is something wrong that should be fixed even if the end user doesn't notice this issue.

![image](https://user-images.githubusercontent.com/42638799/172562284-a5cfafa5-9056-452b-946c-3d6b9839a5c5.png)

**Comment by nickeeromo** [comment] 2022-06-10 20:57
@jasonnutter very close! Using info gleaned from your comment I did some digging into separate areas - it was on us.

We have a landing page that is protected with an MsalGuard - we also had one request in the ngOnInit portion of our AppComponent.ts file, that also happened to use an MsalInterceptor on the way out.

So the MsalInterceptor was requesting a token, but since our AppComponent's template had a router-outlet with a route protected by the MsalGuard, the guard _also_ was requesting the same info - it seems. I've refactored our behavior a bit, and no longer getting the errors in the console.

However, wondering now how this could affect us later on - what if we _want_ to make two different requests at the same time that require tokenage information? Again, it should still work, we'd just get the console error message. In any case, all of our original concerns are taken care of. Thank you!

I just want future readers to understand, so the following is just breaking it down a bit further:

AppComponent.ts excerpt, pre-updates, causing the issue:

    constructor(public store: StoreService,
                        private _router: Router,
                        private _msalService: MsalInteractionService,
                        private _portalService: PortalService,
                        private _logger: LoggingService,
                        private _appConfig: AppConfigService) {
      this._msalService.loggedInObservable$
        .pipe(
          takeUntil(this._destroying$)
        ).subscribe((isLoggedIn: boolean) => {
        this._logger.debug(this.name, 'loggedInSubject set to ', isLoggedIn);
        this.showApplication = isLoggedIn;
          if (this.showApplication) {
            this._portalService.updateUserInformation().subscribe(() => {
              this._portalService.loadAccountsAndInvoices();
              this._portalService.listBankAccounts().subscribe();
            });
          }
      });
    }

    public ngOnInit(): void {
      this.isIframe = window !== window.parent && !window.opener;

    this._router.events.pipe(
      filter((event): event is NavigationEnd => event instanceof NavigationEnd)
    ).subscribe((event: NavigationEnd) => {
      if (event.url.toLowerCase().includes('logout')) {
        this.logoutUser();
        return;
      }

      // the next line really being the problem child
      this._portalService.loadAdminEmails();
      this.handleRouteChange(event.urlAfterRedirects.toLowerCase());
    });

And in AppComponent's template, html:

        <router-outlet></router-outlet>


And the route was /dashboard, which was protected in app-routing.module.ts by the MsalGuard:


    {
      path: 'dashboard',
      // The MsalGuard here + the interceptor invoked by an http callout elsewhere produced the console error
      canActivate: [ MsalGuard, AccountsAndInvoicesGuard ],
      loadChildren: () =>
        import('src/app/main-pages/dashboard/dashboard.module').then((m) => m.DashboardModule),
    },

**Comment by nickeeromo** [comment] 2022-06-10 21:15
Small disclaimer here that IF that actually wasn't the original case, other refactoring removed all http request attempts until after someone has signed in via the Guard anyway, just in case it could also have been at the time two http requests going out at or around the same time.

**Comment by jasonnutter** [comment] 2022-06-14 15:37
> However, wondering now how this could affect us later on - what if we want to make two different requests at the same time that require tokenage information? Again, it should still work, we'd just get the console error message. In any case, all of our original concerns are taken care of. Thank you!

@nickeeromo Requesting multiple tokens at the same time is fine. This error is thrown because a second redirect is being attempted while the first one is in progress (and there can only be one redirect happening at a time). And if your scenario, that's fine.

**Comment by jasonnutter** [comment] 2022-06-14 15:39
> I see the same exceptions on Application Insights. In my case is not 2 but 5 calls that are done within the same second.
I think there is something wrong that should be fixed even if the end user doesn't notice this issue.

@ozkoidi Out of curiosity, what behavior would be desired from the interceptor in this scenario? Fail silently?

**Comment by ozkoidi** [comment] 2022-06-16 14:35
Hi @jasonnutter, if it is a known issue of the library and has no further consequences I see no reason to pollute logs with this error so indeed failing silently would be nice.

**But,** if this error is not to be expected and indicates that there is something wrong in our code then I prefer to fix the login issue on our side. I'm debugging to find the source of the problem, in our case we might be calling `MsalService.getAllAccounts()` before the login process is finished since that part of the code is not wrapped inside the `msalBroadcastService.inProgress$` subcription that checks that `InteractionStatus` is `None`.

**Comment by jasonnutter** [comment] 2022-06-16 14:58
@ozkoidi Thanks. We would tend to disagree on failing silently, as we'd rather have spurious errors that can be ignored on a case-by-case basis, as opposed to potentially hiding real issues by failing silently.

**Comment by ghost** [comment] 2022-06-22 01:01
@nickeeromo This issue has been automatically marked as stale because it is marked as requiring author feedback but has not had any activity for **5 days**. If your issue has been resolved please let us know by closing the issue. If your issue has **not** been resolved please leave a comment to keep this open. It will be closed automatically in **7 days** if it remains stale.

**Comment by ozkoidi** [comment] 2022-06-28 10:02
Hello @jasonnutter, I've found that the exceptions we get are indeed caused by calling `MsalService.getAllAccounts()` before the authentication process has finished.
Since our Angular app has **all routes protected by the MsalGuard**, how can I check if the user is authenticated without calling `getAllAccounts()` (which triggers calls that cause _"Interaction in progress"_ exceptions)?

**Comment by jasonnutter** [comment] 2022-06-28 16:36
@ozkoidi You should wait for InteractionStatus to be be `None`. More information here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/events.md#the-inprogress-observable

**Comment by AndrewJohnWalker** [comment] 2022-07-05 10:45
Is there any way to run parallel requests with msalInterceptor? I have an oninit() that calls two protected routes, if there isn't a valid token this will fail twice and cause the Interaction is currently in progress error. If one of these fails is it possible to not retrigger the acquireTokenInteractively() in msal interceptor if it is already in progress?

**Comment by jasonnutter** [comment] 2022-07-05 16:08
@AndrewJohnWalker The interceptor can attempt multiple silent requests at once, however, if there is an error that requires an interaction, only one interactive request can be made at a time. Are you using popups or redirects for the interceptor?

**Comment by AndrewJohnWalker** [comment] 2022-07-06 07:41
@jasonnutter Redirects

**Comment by jasonnutter** [comment] 2022-07-06 15:36
@AndrewJohnWalker And you are saying that both requests fail with an interaction_in_progress error? Note, the original poster of this issue indicated that the first request would successfully trigger a redirect, while the second would fail, which is what we would expect.

**Closed as completed** 2022-07-14 01:01 UTC
Labels: question, b2c, msal-angular, msal-browser, no-issue-activity, bug-unconfirmed, Needs: Author Feedback
