### ISSUE TITLE
acquireTokenSilent throws a monitor_window_timeout error when refresh token is expired or revoked

### ISSUE THREAD

**Issue by barisbikmaz** [AzureAD/microsoft-authentication-library-for-js#5110] opened 2022-08-17 11:52 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0.0

### Public or Confidential Client?

Public

### Description

I use the ssoSilent to login. 
When the refresk token is expired or revoked acquireTokenSilent throws a "monitor_window_timeout: Token acquisition in iframe failed due to timeout. " error.

Seems like the msal library does not handle the error returned from the https://login.microsoftonline.com/common/oauth2/v2.0/token endpoint correctly.

### Error Message

monitor_window_timeout: Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors.

### Msal Logs

call to https://login.microsoftonline.com/common/oauth2/v2.0/token with payload

client_id: xxxx
scope: User.Read openid profile offline_access
grant_type: refresh_token
refresh_token: xxxx

returns

{"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2022-08-11T15:44:01.5558218Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2022-08-17T10:36:56.0000000Z'.\r\nTrace ID: a01a62e7-0d7c-48c8-aa43-eec21ba51e00\r\nCorrelation ID: acd19412-4c1b-45f0-a50c-fceb0aaffe03\r\nTimestamp: 2022-08-17 11:26:24Z","error_codes":[50173],"timestamp":"2022-08-17 11:26:24Z","trace_id":"a01a62e7-0d7c-48c8-aa43-eec21ba51e00","correlation_id":"acd19412-4c1b-45f0-a50c-fceb0aaffe03","error_uri":"https://login.microsoftonline.com/error?code=50173","suberror":"bad_token"}

### MSAL Configuration

```javascript
const config: Configuration = {
            auth: {
                clientId,
                authority: 'https://login.microsoftonline.com/common',
                redirectUri: 'https://mydomain.com/oauth/index.html',
                navigateToLoginRequestUrl: false,
            },
            cache: {
                cacheLocation: 'localStorage',      
                storeAuthStateInCookie: isEdge(),
            },
        };
```

### Relevant Code Snippets

```javascript
public getAccessToken = async (account: AccountInfo, scopes: string[]) => {
    try {
      const authParams: SilentRequest = {
        account,
        scopes,
      };
      const authResponse = await this.publicClientApplication.acquireTokenSilent(authParams);
      return authResponse.accessToken;
    } catch (error) {
      // here comes the error
      console.log(error);
      const requestInteractiveToken =
        error.name === 'InteractionRequiredAuthError' &&
        error.errorCode === 'consent_required';

      if (requestInteractiveToken) {
        return await this.getAccessTokenInteractive(scopes);
      }

      throw error;
    }
  };
```

### Reproduction Steps

1. Login to an app using ssoSilent
2. Goto Azure Active Directory and revoke all session from the user
3. Wait until the AccessToken is expired or fake the localstorage expiry date manually
4. Try to get a token for a resource within the app
5. Observe the error

### Expected Behavior

msal acquireTokenSilent throws a descriptive error message which we can use to start the interaction flow with the user.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment] 2022-08-17 20:16
@barisbikmaz thanks for raising this issue. It seems to be a duplicate of #4104 and there's a PR in the works that addresses this, so I'll be closing the issue. Please follow #4104 for updates.

**Closed as completed by hectormmg** 2022-08-17 20:16 UTC
Labels: question, msal-browser, bug-unconfirmed, public-client
