### ISSUE TITLE
typescript sample: is this expected behavior?

### ISSUE THREAD

**Issue by lekpeng** [AzureAD/microsoft-authentication-library-for-js#6285] opened 2023-08-03 10:59 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-beta.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0-beta.0

### Public or Confidential Client?

Public

### Description

In the typescript sample [provided](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/a81fcef3d82523e03828d91bb0ee8d2ab2cc20d8/samples/msal-react-samples/typescript-sample) if I login and logout using redirect,

1. I note the logout does not redirect me back to the main page but I see the "You signed out of your account It's a good idea to close all browser windows." microsoft page instead. Is this expected?

2. Now if I try to navigate back in the same tab (by typing the URL not using the back button) to reattempt a login, I get the "interaction_in_progress" error. Just want to understand if this is expected behavior as well? 

I only modified the msalConfig to use my own Client ID and Authority

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: MYCLIENTID,
        authority: MYAUTHORITY,
        redirectUri: "/",
        postLogoutRedirectUri: "/",
    },
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment] 2023-08-06 22:51
@lekpeng what you describe is not expected behavior, you should be getting redirected back, and that's when the "interaction_in_progress" flag would get removed so you can log in again. However, I wasn't able to reproduce the behavior you described on the sample as it is on our repo. Can you elaborate on any changes you've made to the default configuration? I tried both logout redirect and logout popup, I did get the "You've been logged out" window but I was redirected back to the main app shortly after, as expected. Are you closing the tab too soon maybe?

**Comment by lekpeng** [comment] 2023-08-07 05:58
@hectormmg I think my issue is similar to the issue posted [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5783) as the redirect upon logout also only works in safari but not chrome. However in my case, my azuread authority must include the tenant id or the login will not work. I have posted a comment there as well, not sure if you wish to continue from that issue or here. Thanks.

**Comment by hectormmg** [comment] 2023-08-07 20:48
Closing since #5783 is more appropriate for tracking this issue

**Closed as completed by hectormmg** 2023-08-07 20:48 UTC
Labels: question, msal-browser, msal-react, public-client
