### ISSUE TITLE
acquireTokenSilent : ERROR InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in

### ISSUE THREAD

**Issue by hansakaRightS** [AzureAD/microsoft-authentication-library-for-js#7252] opened 2024-08-13 13:05 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.1.0

### Public or Confidential Client?

Public

### Description

We are calling `acquireTokenSilent` to get a new token without affecting the user experience , but this throw an error whenever we call the it. 
(we tried calling this 20 seconds after the login success)

since this error we have to force call the `acquireTokenRedirect` to get the token, which affect user experience because webpage is refresh when this happens

```
Error : 
`ERROR 
InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.`
```

### Error Message

`ERROR 
InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.`

### Network Trace (Preferrably Fiddler)

- [X] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
auth: {
        clientId: clientId,
        authority: "B2C_1A_SIGNUP_SIGNIN",
        redirectUri: '/',
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "LocalStoarage",
        storeAuthStateInCookie: false
    }
}
```

### Relevant Code Snippets

```javascript
this.msalService.acquireTokenSilent({
         scopes:[`https://${environment.activeDirectory.domain}/${environment.activeDirectory.tenantId}/access_as_user`],
         forceRefresh: false,
         account: this.msalService.instance.getActiveAccount()
});
```

### Reproduction Steps

1. successful login.
2.  call acquireTokenSilent.

### Expected Behavior

we should be able to get a new token.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Other

### Source

External (Customer)

**Comment by tnorling** [comment] 2024-08-13 21:46
Please upgrade to the latest version and if this is still an issue please provide trace level logs

**Comment by hansakaRightS** [comment] 2024-08-14 06:56
@tnorling Thanks for the reply. let me update the to the latest version and get back to you.  

How can I acquire the trace level log?

**Comment by hansakaRightS** [comment] 2024-08-14 07:20
@tnorling small question, is it normal behavior to see page refresh on the `acquireTokenSilent` method is called?

**Comment by tnorling** [comment] 2024-08-14 22:32
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md

**Comment by hansakaRightS** [comment] 2024-08-15 06:40
Thanks @tnorling 
Updating the package fixed the problem i was having, but i still experience the page refresh when we call the `acquireTokenSilent`. is that expected?

**Comment by tnorling** [comment] 2024-08-15 19:13
Great, thanks for confirming the upgrade fixed the issue, I'm going to go ahead and close this as resolved. 

acquireTokenSilent will not cause the page to refresh on its own, this is typically caused by logic implemented by the app to react to events or results of the call, such as falling back to acquireTokenRedirect in the case of a failure, or rerendering content or redirecting to another page upon a success. That's something you'll need to debug on your side.

**Closed as completed by tnorling** 2024-08-15 19:13 UTC
Labels: question, msal-angular, msal-browser, bug-unconfirmed, public-client
