### ISSUE TITLE
Retrieving Current AccessToken Expiration Extends It

### ISSUE THREAD

**Issue by BarishSarac** [AzureAD/microsoft-authentication-library-for-js#4153] opened 2021-10-13 14:39 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.2

### Description

I used to retrieve how long user's access token available from 1st approach

I got a feedback from @tnorling that, it's not guaranteed that this would give up to date expiration date for user's access token. So I was recommended to use second approach 

Using 2nd approach, I am able to say 1st approach does bring old expiration time. The problem is in the 2nd approach updating expiration time even though, I am not intending to do that. All I need to do is to know when this user's access token will expire.

My goal explanation, if matters is here. Access token needs to be active only 1 hour from the last time user used it. If user sign-in at 1pm, they take some action at 1:20pm, their access token at that time should expire at 2:20pm. The reason I ask for expiration time of the Access Token is that, if user does not take an action for 1 hour, I need to log them out. If I do not check their access token user stays logged in forever. If someone logs in and leave their PC on for hours someone else can click and load up things through API.

### MSAL Configuration

```javascript
export const b2cPolicies = {
  names: {
    signUpSignIn: "***",
    forgotPassword: "***",
  },
  authorities: {
    signUpSignIn: {
      authority:
        "***",
    },
    forgotPassword: {
      authority:
        "***",
    },
  },
  authorityDomain: "loginservicedev.b2clogin.com",
};
/**
 * Configuration object to be passed to MSAL instance on creation.
 * For a full list of MSAL.js configuration parameters, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md
 */
export const msalConfig = {
  auth: {
    clientId: "****", // This is the ONLY mandatory field that you need to supply.
    authority: b2cPolicies.authorities.signUpSignIn.authority, // Choose SUSI as your default authority.
    knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
    redirectUri: "/", // You must register this URI on Azure Portal/App Registration. Defaults to window.location.origin
    postLogoutRedirectUri: "/", // Indicates the page to navigate after logout.
    navigateToLoginRequestUrl: false, // If "true", will navigate back to the original request location before processing the auth code response.
  },
  cache: {
    cacheLocation: "localStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    tokenRenewalOffsetSeconds: 1740,
  },
};
```

### Relevant Code Snippets

```javascript
1st approach

export const b2cGetSessionTimeLeft = () => {
  return Math.round(
    (accounts[0]?.idTokenClaims.exp - Math.round(Date.now() / 1000)) / 60
  );
};
```

2nd approach
```
function fetchToken(forceRefresh = false) {
  params.forceRefresh = forceRefresh;
  return instance
    .acquireTokenSilent(params)
    .then((response) => response)
    .catch(() =>
      instance
        .acquireTokenRedirect(params)
        .then((response) => response)
        .catch(() => false)
    );
}
export const b2cTimeLeft = async () => {
  let expDateTime = await fetchToken().then((res) => res.expiresOn);
  return Math.round(
    (Math.round(expDateTime / 1000) - Math.round(Date.now() / 1000)) / 60
  );
};
```
```


### Reproduction Steps

Request token using acquireTokenSilent and it will extend accesstoken expireson.

### Expected Behavior

Do not extend expireson on each acquireTokenSilent call unless forcerefresh is true.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

_No response_

### Source

Internal (Microsoft)

**Comment by sameerag** [comment] 2021-10-13 15:40
@BarishSarac I already addressed this in the discussion linked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions/4120). This is by design from MSAL JS and not a BUG. Our users expect to get a token as long as the server has a session.

**Comment by BarishSarac** [comment] 2021-10-13 18:01
@sameerag Well, that's fine. In that case, question remains, how can we get current access token expiration time without extending it? In the old way, if I needed to get the current token's expiration time, I could by fetch and get time. If I needed to update the token and expiration time of it, I could by sending in forceRefresh = true. Now I don't have a way to access token expiration time without updating it, in which case it's pointless because by requesting it, I am extending it... Is there a way I can get current access token expiration time without updating it?

**Comment by sameerag** [comment] 2022-07-20 05:08
cc @Robbie-Microsoft, assigning this to you, aligns with the current feature you are working on. Please update this feature once we close on it.

**Comment by bgavrilMS** [comment] 2022-08-24 17:24
My 2 cents on this is that sign-out should be handled by the application, without using the concept of access token expiration. Access tokens are not even meant for the client application, they are meant for a downstream web api. You can also use Conditional Access policies - see https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime 

Here are some problems I see with this approach: 

- Exposing this level of control implies that app with make unnecessary requests to AAD, because the app wants fresh tokens at the "start" of the session. 
- It conflicts with the "proactive token refresh" initiave, where MSALs should be trying to refresh tokens well before they expire, in the background
- Won't work with WAM
- The token lifetime is not a guaranteed constant (1h), it is controlled by tenant admin.

CC @sameerag

**Closed as completed** 2022-09-27 15:59 UTC
Labels: enhancement, feature, msal-browser, tracked-internally
