### ISSUE TITLE
no ConfidentialClientApplication available in @azure/msal-browser or @azure/msal-react

### ISSUE THREAD

**Issue by ttpp123** [AzureAD/microsoft-authentication-library-for-js#4140] opened 2021-10-07 05:49 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

We have confidential client applications developed with React and like to use msal in these applications. I don't see ConfidentialClientApplication available in @azure/msal-browser or @azure/msal-react.

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2021-10-07 15:46
@ttpp123 This is by design, as single-page applications run in browser environments, which are unable to securely store client secrets, and thus can only support public client applications. If you need to support confidential clients, please look at our [MSAL Node](https://www.npmjs.com/package/@azure/msal-node) or [MSAL.net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) SDKs.

**Comment by sameerag** [comment] 2021-10-09 08:49
Closing this since confidential client apps cannot be supported for msal-browser.

**Closed as completed by sameerag** 2021-10-09 08:49 UTC
Labels: question, msal-browser, msal-react
