### ISSUE TITLE
MSAL loginSuccess not triggering iphone device

### ISSUE THREAD

**Issue by mohanrajselvam007** [AzureAD/microsoft-authentication-library-for-js#1227] opened 2020-01-21 09:58 UTC
## I'm submitting a...
- [ ] `Safari`
- [ ] `Chrome`

## Library version
`Angular 8.2.0`
`@azure/msal-angular: ^0.1.4`

## Current behavior
when i try to login i entered account details, after loginPopup closed "msal:loginSuccess" event not triggering in the iphone safari/chrome browser. 

some time triggering msal:loginSuccess event in the same browsers in iphone.
## Expected behavior
Should login to all browsers on every time.

**Comment by jasonnutter** [comment] 2020-01-21 16:50
@mohanrajselvam007 Does `loginRedirect` work when you are on a mobile device?

**Comment by mohanrajselvam007** [comment] 2020-01-22 05:33
i have tried `loginRedirect` instead `loginPopup` but "msal:loginSuccess" event not triggering in the iphone. but its working on other android devices.

**Comment by jasonnutter** [comment] 2020-01-22 16:52
@mohanrajselvam007 Is `msal:loginFailure` broadcast? If so, what is the error?

**Comment by mohanrajselvam007** [comment] 2020-01-23 15:20
> @jasonnutter I am not able to get the broadcast events msal:loginSuccess/msal:loginFailure.
I am using `Angular 8.2.0` version and `@azure/msal-angular": "^0.1.4"`. Event triggering some time in the iPhone. this issue happen only iPhone devices.

**Comment by jasonnutter** [comment] 2020-01-30 22:09
@mohanrajselvam007 Can you try the new version of MSAL Angular and let me know if this is still an issue?

Upgrade instructions here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0-protectedresources/lib/msal-angular/docs/0.x-1.x-upgrade-guide.md

**Comment by jasonnutter** [comment] 2020-02-03 21:44
Going to close this as a duplicate of #843.

**Closed by jasonnutter** 2020-02-03 21:44 UTC
Labels: angular, bug
