### ISSUE TITLE
Post logout redirect only works when browser is set to block third party cookies.

### ISSUE THREAD

**Issue by benaguitar** [AzureAD/microsoft-authentication-library-for-js#5776] opened 2023-03-08 18:50 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.4

### Public or Confidential Client?

Public

### Description

I have ran into an issue when redirecting on post logout when in non incognito mode in chrome and Firefox. 

It works perfectly fine when I set my browser to block third part cookies but when I set the browser to block third party cookies in incognito mode or set the browser to allow all cookies I do not get redirected. 

This also works fine in Safari.

### Error Message

No error message, the browser never get's redirected to login page after logout.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: "b5c2e510-4a17-4feb-b219-e55aa5b74144",
      authority: "https://login.microsoftonline.com/common",
      redirectUri: '/',
      postLogoutRedirectUri: '/login',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: false, // set to true for IE 11. Remove this line to use Angular Universal
      secureCookies: false,
    },
    system: {
      loggerOptions: {
        logLevel: LogLevel.Verbose,
        loggerCallback: (level, message, containsPii) => {
          console.log(message);
          },
        piiLoggingEnabled: false,
  
      }
    }
  }
```

### Relevant Code Snippets

```javascript
logout(popup?: boolean) {
    if (popup) {
      this.authService.logoutPopup({
        mainWindowRedirectUri: "/"
      });
    } else {
      this.authService.logoutRedirect();
    }
  }
```

### Reproduction Steps

1. Have chrome browser cookies set to block third party cookies in incognito mode only.
3. Login to app in NON incognito mode.
4. Logout of app and the window never gets redirected to the /login endpoint.

### Expected Behavior

For the logout to redirect the user to the post logout redirect URL when in non incognito mode in Chrome and Firefox.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment] 2023-03-09 20:41
Hey @benaguitar ! Are you seeing this issue in both logout with redirect as well as popup?

Just fyi when you are using logoutPopup() and you want to redirect back to the postLogoutRedirectUri which is set to /login in the main application, the mainWindowRedirectUri should also be set to /login. [(Docs)](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logoutpopup)

**Comment by benaguitar** [comment] 2023-03-10 21:50
Hi @lalimasharda! Thank you for looking at this. 

I am seeing this with both logout with redirect as well as popup. 

What is weird is I can get logout with redirect to work when I set my third party cookies to be blocked in chrome and firefox. 

Have anything I can try that would make a difference when have the cookies set to allow all?

**Comment by lalimasharda** [comment] 2023-03-11 00:06
I am a little confused about the problem. In your description you said that when you set "Allow all cookies" to true, your application does not redirect you back to login page after logging out. But in your repro steps you are asking to set "Block third-party cookies in Incognito" to true instead and the application doesn't redirect back to login page. 

In any case, I tried out our angular 6 sample app with both the settings and I am not able to reproduce it. Can you please share logs?

**Comment by benaguitar** [comment] 2023-03-11 01:38
Hello, 

The first step can be confusing, I was saying that to make sure your chrome browser has third party cookies only blocked in incognito mode or allow all cookies, sorry about that. 

In the angular 6 sample app it works as expected but I am testing this with the Angular14-rxjs7-sample-app and see the issue. 

I have attached the console logs, let me know if you want the network .har file and I can email you the file.

[login.microsoftonline.com-console-logs.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/10947267/login.microsoftonline.com-console-logs.log)

**Comment by benaguitar** [comment] 2023-03-11 18:57
@lalimasharda I did get this to work by creating a user within Active Directory verses using the admin user of the Active Directory or using an external user. 

I have read that this was an issue in the past but seems to still be an issue that's not on the MSAL Angular side.

Any thoughts?

**Comment by sameerag** [comment] 2023-03-15 04:38
@benaguitar Is this same as #5783?

**Comment by benaguitar** [comment] 2023-03-15 12:43
Hi @sameerag Yes this is the same issue we determined.

**Comment by sameerag** [comment] 2023-03-15 19:22
I will be closing this and link it to #5783 for traction in that case. Thanks @benaguitar.

**Closed as completed by sameerag** 2023-03-15 19:22 UTC
Labels: question, msal-angular, msal-browser, bug-unconfirmed, public-client
