### ISSUE TITLE
Allow Controlling Returning to Page Redirect

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#243] opened 2018-02-02 17:46 UTC
Can you please allow the consumer of MSAL.js to control if the user is redirected back to the page they came from our where the login endpoint redirected the user back to?

As it stands now, I can only control the `redirectUri` via the constructor options.  In our particular case I don't want the user to get redirected back to the page they were on.  I want them to go to the redirectUri I specified but the library is preventing this.

[Code link](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a708c7cfcc6c849fff1dcc7f0c4cb88b533a2480/src/UserAgentApplication.ts#L1357)

```js
private handleAuthenticationResponse(hash: string): void {

        ...

	if (window.parent === window && !isPopup && [I_WANT_THIS_TO_HAPPEN]) {
		window.location.href = self._cacheStorage.getItem(Constants.loginRequest);
	}
}
```

**Comment by rohitnarula7176** [comment] 2018-02-02 21:18
Duplicate of #238

**Closed by rohitnarula7176** 2018-02-02 21:18 UTC
