### ISSUE TITLE
Error - Guard - error while logging in, unable to activate - blocks the msal guard

### ISSUE THREAD

**Issue by SamShekhovtsov** [AzureAD/microsoft-authentication-library-for-js#6055] opened 2023-05-23 11:46 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Confidential

### Description

When user clicks for example change password, there is a request created for a password change. In case, if the user cancelled the change password dialog, he is sent back to the site, however the "**Error - Guard - error while logging in, unable to activate**" blocks the user from any action.

I was trying different workarounds for solving this issue:
set the active account (however the active account is set correctly)

`authService.ssoSilent`

nothing helps, the system remains broken, all features are not functioning due to the error mentioned above.

When users cancels the Change Password or cancels the Impersonate flow by clicking the Cancel button - the system shouldn't be competely broken. The user is expected to remain logged in.

### Error Message

ERROR ServerError: access_denied: AADB2C90091: The user has cancelled entering self-asserted information.
Error - Guard - error while logging in, unable to activate

### Msal Logs

Error - Guard - error while logging in, unable to activate

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication(msalConfig);
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: loginRequest
  };
}
```

### Relevant Code Snippets

```javascript
changePassword() {
        let changePasswordRequest: RedirectRequest | PopupRequest = {
            authority: b2cPolicies.authorities.customChangePassword.authority,
            scopes: [],
        };

        this.login(changePasswordRequest);
    }


    trySsoSilentLogin(originalSignInAccount: AccountInfo) {
        
        let signUpSignInFlowRequest: SsoSilentRequest = {
            authority: b2cPolicies.authorities.customSignUpSignIn.authority,
            account: originalSignInAccount as AccountInfo
        };

        // silently login again with the customSignUpSignIn policy
        this.authService.ssoSilent(signUpSignInFlowRequest);
    }

this.authService.loginRedirect(userFlowRequest);
```

### Reproduction Steps

1. implement the change password flow
2. click / activate the change password function
3. cancel the change password flow by clicking the "Cancel" button
4. try to use the system as usual

### Expected Behavior

the user should be able to use the system as usual after cancelling the current change password or impoersonate user flow.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Internet Explorer

### Source

External (Customer)

**Comment by lalimasharda** [comment] 2023-05-23 20:41
Hey @SamShekhovtsov! This is a known issue and a duplicate of #4378 (workaround mentioned). We are tracking this bug internally, but it is deprioritized at the moment.

**Closed as completed** 2023-06-09 13:00 UTC
Labels: question, b2c, msal-angular, msal-browser, no-issue-activity, bug-unconfirmed, Needs: Author Feedback, public-client
