### ISSUE TITLE
Utils.containsScope 'openid' and 'profile' authentication scopes cache miss

### ISSUE THREAD

**Issue by geitir** [AzureAD/microsoft-authentication-library-for-js#816] opened 2019-07-09 15:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
N/A

## Library version
<pre><code>
Library version: 1.0.2
</code></pre>

## Current behavior
The 'openid' and 'profile' scopes added by the Microsoft Authorization Server during authentication request are causing the Utils.containsScope to return false, causing acquireTokenSilent to re-authorize instead of use the cache. Refreshing the browser resolves the issue, but for SPA's this is not viable.

I was able to fix by adding 

<code>
return scopes.every(function (value) {    
            value = value.toString().toLowerCase();
            if (value == 'openid' || value == 'profile') { return true; }
            return cachedScopes.indexOf(value) >= 0;
        });
</code>

## Expected behavior
Disregard 'openid' and 'profile'

## Minimal reproduction of the problem with instructions
Any SPA authentication

**Comment by jasonnutter** [comment] 2019-07-09 17:39
@sameerag @pkanher617 is this expected behavior?

**Comment by sameerag** [comment] 2019-07-10 00:55
Ideally, it shouldn't. We add these default scopes as a part of [openid connect spec compliance](https://openid.net/specs/openid-connect-basic-1_0.html#Scopes). We may need to debug this.

**Comment by jasonnutter** [comment] 2019-07-10 17:15
Ah I wonder if this is the same issue that is reported in #762.

**Comment by jasonnutter** [comment] 2019-07-17 22:01
@geitir We are not able to reproduce the behavior you describe. Can you please provide a sample that exhibits the cache miss?

**Comment by geitir** [comment] 2019-07-18 13:28
Here's logging using "if (value == 'openid' || value == 'profile') { return true; }"
![with-fix](https://user-images.githubusercontent.com/26013461/61461274-64758280-a93e-11e9-9588-b6c08daa76da.png)

Here's what I'm getting by default 
![bad](https://user-images.githubusercontent.com/26013461/61461294-6b9c9080-a93e-11e9-9b12-82298d150def.png)

**Comment by anton-gorbikov** [comment] 2019-07-24 14:02
@jasonnutter currently we are experiencing the same behavior on our project even with the latest v1.1.1

![image](https://user-images.githubusercontent.com/5469718/61799767-5dfe7380-ae34-11e9-9053-7e0f529208e4.png)

We are calling the `acquireTokenSilent` with the single scope `['https://{{tenantId}}.sharepoint.com/.default']` but instead of single expected authentications we see two: the first one with our list of scopes, the second one contains two additional scopes `['openid', 'profile']` (as of screenshot).

**Comment by DarylThayil** [comment] 2019-08-13 22:29
@geitir  this should be fixed in 1.1.2 please try and if it is not fixed for your use case open a new issue. 

Thank you!

**Closed** 2019-08-13 22:29 UTC
Labels: bug, core, needs info, performance
