### ISSUE TITLE
Accessing SPA via a hyperlink breaks MSAL login process, handleRedirectCallback is never called

### ISSUE THREAD

**Issue by BoshJeckerleg** [AzureAD/microsoft-authentication-library-for-js#1349] opened 2020-03-05 14:35 UTC
## Library
- [x] `msal@1.2.1` 
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- Angular v7.2.16
- NGRX v8.2.0

## Description
The msal set up I have in my angular application uses NGRX and a MSAL service to authenticate the user and store specific values and tokens in the store. Currently we use the loginRedirect flow and this works fine if the user accesses the site directly by typing in the URL manually or from a bookmark. However, if a user accesses the site from a hyperlink then this flow breaks and the user is stuck when redirected back to the application from a successful login. 

- authenticationModule is imported into the root of my application and is available on startup. 
- NGRX effects have initialised in order to redirect the user to login
- login redirect callback waits for NGRX effects to init prior to triggering accessSilentToken to make sure store side effects are triggered.

I notice that on a successful login / when I have had errors in my configuration that on redirect to the application the state url hash fragment is removed immediately but in this instance it remains and nothing happens.

## Security
No

## Regression
No

## Configuration
```js
 this.msalConfig = {
      auth: {
        clientId: this._config.msalClientId,
        redirectUri: this._config.msalRedirectUri,
        postLogoutRedirectUri: this._config.msalPostLogoutRedirectUri,
        navigateToLoginRequestUrl: false,
        validateAuthority: false
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
      }
    };
    this.clientApplication = new Msal.UserAgentApplication(this.msalConfig);
    this.clientApplication.handleRedirectCallback(this.loginRedirectCallback);
```

## Reproduction steps (LoginRedirect method)
1. Navigate to the site from a hyperlink
2. Triggers regular login process
3. Login 
4. On redirect to site notice that the url has the state hash fragment but the callback has not been executed
5. loginRedirectCallback has not been called on redirect to the site, so you are stuck in a loop
6. Copy the url into a new incognito window, login process completes and you are logged back into the site. 

## Expected behavior
The login process should complete

## Additional Information
- Looking around in localStorage
```
msal.interaction_status: inProgress
```
## Browsers
No, this occurs in every browser.

**Comment by jasonnutter** [comment] 2020-03-06 00:25
@BoshJeckerleg Does this happen when the link that opened the site is set to open the app in a new window? If so, this is a known issue, and we are working on a fix.

In the mean time, a potential workaround is to set `window.opener = null` in your app.

**Comment by BoshJeckerleg** [comment] 2020-03-06 08:18
@jasonnutter Yes, that is what's happening currently. Thanks for the work around i'll implement that now.

**Comment by jasonnutter** [comment] 2020-03-06 17:27
@BoshJeckerleg Great, thanks for confirming.

Closing as a duplicate of #1198, #1207

**Closed by jasonnutter** 2020-03-06 17:27 UTC
Labels: bug, known-issue
