### ISSUE TITLE
Session state creating issue while redirecting to redirect URI

### ISSUE THREAD

**Issue by tushaar9027** [AzureAD/microsoft-authentication-library-for-js#5388] opened 2022-11-11 08:39 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.3

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

NA

### Public or Confidential Client?

Confidential

### Description

On Local the solution is working flawlessly as expected and once we move the solution to azure app service it breaks.

I am getting Error 404 page not found while it is redirecting,  after it goes to authorize endpoint and send the authorization code to redirect uri. I get the below error

https://.azurewebsites.net/auth/redirect?code=<Authorization_Code>&session_state=18b77656-7bb0-45e7-a678-5944ec526564

After i remove the session state manually and try it works fine .

Can someone help me understand why this is happening and how to correct this. (Like skip session state while sending)

### Error Message

Not getting redirected to the application Home page

Getting 404 page not found

https://.azurewebsites.net/auth/redirect?code=<Authorization_Code>&session_state=18b77656-7bb0-45e7-a678-5944ec526564

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "<Client-ID>",
        authority: "https://login.microsoftonline.com/<tenant-id>",
        clientSecret: "<client-secret>"
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
};
```

### Relevant Code Snippets

```javascript
// Import dependencies
const express = require("express");
// Initialize express
const app = express();
const session = require("express-session");
const msal = require('@azure/msal-node');

const sessionConfig = {
    secret: 'Thanos1993',
    resave: false,
    saveUninitialized: false,
    cookie: {
        secure: false, // set this to true on production
    }
}

app.use(session(sessionConfig));

// Authentication parameters
const config = {
    auth: {
        clientId: "<Client-ID>",
        authority: "https://login.microsoftonline.com/<tenant-id>",
        clientSecret: "<client-secret>"
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
};

const REDIRECT_URI = "http://localhost:3000/auth/redirect";

// Initialize MSAL Node object using authentication parameters
const cca = new msal.ConfidentialClientApplication(config);



app.set('view engine','ejs');

app.get('/', (req, res) => {
    res.render('home')
});

app.get('/auth', (req, res) => {

    // Construct a request object for auth code
    const authCodeUrlParameters = {
        scopes: ["user.read"],
        redirectUri: REDIRECT_URI,
    };

    // Request auth code, then redirect
    cca.getAuthCodeUrl(authCodeUrlParameters)
        .then((response) => {
            res.redirect(response);
        }).catch((error) => res.send(error));
});

app.get('/auth/redirect', (req, res) => {

    // Use the auth code in redirect request to construct
    // a token request object
    const tokenRequest = {
        code: req.query.code,
        scopes: ["user.read"],
        redirectUri: REDIRECT_URI,
    };

    // Exchange the auth code for tokens
    cca.acquireTokenByCode(tokenRequest)
        .then((response) => {
           // res.send(response);
            console.log(response);
            console.log(response.account.name);
            req.session.user = response.account.name
            req.session.isAuthenticated = true;
            res.redirect('/home');
        }).catch((error) => res.status(500).send(error));
});

app.get('/home', ensureAuthenticated ,(req,res)=>{
    res.send("You have reached the Home Page after authentication");
})

app.get('/about', ensureAuthenticated ,(req,res)=>{
    res.send("You have reached the About Page after authentication");
})

app.get('/logout',(req,res)=>{
    console.log(`Logging out the user : ${req.session.user}`);
    req.session.destroy(function (err) {
      res.redirect('/'); 
     });
  })

app.listen(3000, () => {console.log(`listening on port 3000!`)});


function ensureAuthenticated(req, res, next) {
    if (req.session.isAuthenticated) { 
        console.log(`User is Authenticated : ${req.session.isAuthenticated}`)
        return next(); 
    }
     res.redirect('/');
    }
```

### Reproduction Steps

1. Locally the Application work flawless
2. When we move the application to Azure it breaks after authrorization code is get and it needs to redirect.
3. In mobile browser it works fine , error is coming only in desktop browser.
4. I we remove the session_State and manually try the url it works gets access token and redirect to application 

### Expected Behavior

After Getting Authorization code it should go to redirect uri and get the access token and redirect to application home page

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge, Internet Explorer

### Source

External (Customer)

**Comment by jo-arroyo** [comment] 2022-11-11 22:54
@bgavrilMS @Robbie-Microsoft session state question for you.

**Comment by bgavrilMS** [comment] 2022-11-14 09:51
@derisen - `session_State` seems to be causiong 404s here, any thoughts on this?

**Comment by derisen** [comment] 2022-11-14 16:51
@tushaar9027 haven't encountered this before, let me try to reproduce it (msal is supposed to strip these query params when processing the auth code). One thing that caught my eye in the snippet you shared:

```javascript
const REDIRECT_URI = "http://localhost:3000/auth/redirect";
```

Are you updating this when you deploy to App Service? Is the updated redirect URI registered on Azure AD app registration?

**Comment by tushaar9027** [comment] 2022-11-21 18:16
> you updating this when you d

@derisen yes i am updating the Redirect URI in the App registration to use the PROD URL.

**Comment by derisen** [comment] 2022-11-21 18:18
@tushaar9027 thanks for confirming. Is the [app service authentication](https://learn.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) **not** enabled as well?

**Comment by tushaar9027** [comment] 2022-11-21 18:19
yes easy auth is not enabled

**Comment by derisen** [comment] 2022-11-21 18:23
@tushaar9027 got it -will try to reproduce this and get back to you.

**Comment by tushaar9027** [comment] 2022-11-21 18:24
> @tushaar9027 got it -will try to reproduce this and get back to you.

Thanks, its been bugging me for a while.

**Comment by derisen** [comment] 2022-11-22 20:54
@tushaar9027 I wasn't able to reproduce this. In any case, this doesn't seem to relate to MSAL. App Service is supposed to ignore query parameters when redirecting, but for some reason it's translating what's after `&` into a path. Do you have an [Application Gateway configured](https://learn.microsoft.com/en-us/azure/application-gateway/troubleshoot-app-service-redirection-app-service-url) in your environment, or [some URL rewrite rule](https://learn.microsoft.com/en-us/azure/application-gateway/rewrite-url-portal)? You might want to [open a support ticket with the App Service](https://azure.microsoft.com/en-us/support/) in that case.

On the other hand, you can mitigate this issue by [using `form_post `method instead of `query`](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code) when receiving the authorization code response. This is also the OAuth 2.0 recommendation for confidential clients. Basically you can modify your msal-node usage as follows:

```javascript
app.get('/auth', (req, res) => {

    // Construct a request object for auth code
    const authCodeUrlParameters = {
        scopes: ["user.read"],
        redirectUri: REDIRECT_URI,
        responseMode: "form_post" // configure auth code url response to use post 
    };

    // Request auth code, then redirect
    cca.getAuthCodeUrl(authCodeUrlParameters)
        .then((response) => {
            res.redirect(response);
        }).catch((error) => res.send(error));
});

// app.post instead of app.get
app.post('/auth/redirect', (req, res) => {

    // Use the auth code in redirect request to construct
    // a token request object
    const tokenRequest = {
        code: req.body.code, // auth code will be in the response body
        scopes: ["user.read"],
        redirectUri: REDIRECT_URI,
    };

    // Exchange the auth code for tokens
    cca.acquireTokenByCode(tokenRequest)
        .then((response) => {
           // res.send(response);
            console.log(response);
            console.log(response.account.name);
            req.session.user = response.account.name
            req.session.isAuthenticated = true;
            res.redirect('/home');
        }).catch((error) => res.status(500).send(error));
});
```

**Comment by tushaar9027** [comment] 2022-11-23 06:11
> ou can mitigate this issue by

@derisen i am not using any  [Application Gateway configured] in my environment, nor any [some URL rewrite rule].

Let me try to use the responseMode: "form_post" and see if that works . Thanks for analyzing the issue atleast i have some lead now.

**Comment by derisen** [comment] 2022-12-01 23:24
@tushaar9027 assuming this is mitigated with `form_post`. Closing, but let us know if not.

**Closed as completed by derisen** 2022-12-01 23:24 UTC
Labels: question, msal-node, bug-unconfirmed, msal-node-extensions, confidential-client
