### ISSUE TITLE
Can't Sign in again  after cancelling the authentication popup by the close or back button 

### ISSUE THREAD

**Issue by mustafaAly** [AzureAD/microsoft-authentication-library-for-js#4808] opened 2022-05-12 11:02 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.9.0

### Description

Hi Team, thank you for your efforts and your support I have a critical issue that I can't sign in again  to my account after canceling the authentication popup by the close button or back button
![Screenshot (76)_LI](https://user-images.githubusercontent.com/16977942/168052970-8dda9822-ceee-4b54-a2ee-64c3f3f2303a.jpg)

### Error Message

I can't log in again after canceling and trying to authenticate again, I should close the second one and try again and it will authenticate successfully, the login stopped like the attached photo I think that the  authProvider.login() function doesn't call anywhere
it gives me an error message:'Object has been destroyed' when I click the close button but this message appears when I try login again not after the close popup
it gives me an error message:'No code found in URL' when I click the click button 

![Screenshot (78)](https://user-images.githubusercontent.com/16977942/168054100-5ba29157-d885-4916-8d83-f8729081ba07.png)
 

### MSAL Configuration

```javascript
const MSAL_CONFIG = {
	auth: {
		clientId: "XXXXX-XXX-XXXXXXX",
		authority: `https://login.microsoftonline.com/common/`,
	},
	// cache: {
	// 	cachePlugin
	// },
	system: {
		loggerOptions: {
			loggerCallback(loglevel, message, containsPii) {
				console.log(message);
			},
			piiLoggingEnabled: false,
			logLevel: LogLevel.Verbose,
		}
	}
};
```

### Relevant Code Snippets

```javascript
class AuthProvider {

	clientApplication;
	cryptoProvider;
	authCodeUrlParams;
	authCodeRequest;
	pkceCodes;
	account;

	constructor() {
		/**
		 * Initialize a public client application. For more information, visit:
		 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/initialize-public-client-application.md
		 */
		this.clientApplication = new PublicClientApplication(MSAL_CONFIG);
		this.account = null;

		// Initialize CryptoProvider instance
		this.cryptoProvider = new CryptoProvider();

		this.setRequestObjects();
	}

	/**
	 * Initialize request objects used by this AuthModule.
	 */
	setRequestObjects() {
		const requestScopes = [
			'openid',
			'profile',
			'User.Read'
		];
		const redirectUri = "msal://redirect";

		this.authCodeUrlParams = {
			scopes: requestScopes,
			redirectUri: redirectUri
		};

		this.authCodeRequest = {
			scopes: requestScopes,
			redirectUri: redirectUri,
			code: null
		}

		this.pkceCodes = {
			challengeMethod: "S256", // Use SHA256 Algorithm S256 RS256 
			verifier: "", // Generate a code verifier for the Auth Code Request first
			challenge: "" // Generate a code challenge from the previously generated code verifier
		};
	}
	static createAuthWindow() {
		return new BrowserWindow({
			width: 400,
			height: 600
		});
	}
	async login() {
		const authResult = await this.getTokenInteractive(this.authCodeUrlParams);
		this.handleResponse(authResult);
		return authResult;
	}

	async logout() {
		if (this.account) {
			await this.clientApplication.getTokenCache().removeAccount(this.account);
			this.clientApplication.clearCache();
			this.account = null;
		}
	}
	async getToken(request) {
		let authResponse;
		const account = this.account || await this.getAccount();
		if (account) {
			request.account = account;
			authResponse = await this.getTokenSilent(request);
		} else {
			const authCodeRequest = { ...this.authCodeUrlParams, ...request };
			authResponse = await this.getTokenInteractive(authCodeRequest);
		}

		return authResponse.accessToken || null;
	}
	async getTokenInteractive(tokenRequest) {
		// Generate PKCE Challenge and Verifier before request
		const cryptoProvider = new CryptoProvider();
		const { challenge, verifier } = await cryptoProvider.generatePkceCodes();
		const authWindow = AuthProvider.createAuthWindow();

		// Add PKCE params to Auth Code URL request
		const authCodeUrlParams = {
			...this.authCodeUrlParams,
			scopes: tokenRequest.scopes,
			codeChallenge: challenge,
			codeChallengeMethod: "S256"
		};

		try {
			// Get Auth Code URL
			const authCodeUrl = await this.clientApplication.getAuthCodeUrl(authCodeUrlParams);

			const authCode = await this.listenForAuthCode(authCodeUrl, authWindow);

			// Use Authorization Code and PKCE Code verifier to make token request
			const authResult = await this.clientApplication.acquireTokenByCode({
				...this.authCodeRequest,
				code: authCode,
				codeVerifier: verifier
			});

			authWindow.close();
			return authResult;
		} catch (error) {
			authWindow.close();
			throw error;
		}
	}

	async listenForAuthCode(navigateUrl, authWindow) {
		// Set up custom file protocol to listen for redirect response
		const authCodeListener = new CustomProtocolListener();
		const codePromise = authCodeListener.start();
		authWindow.loadURL(navigateUrl);
		const code = await codePromise;
		authCodeListener.close();
		return code;
	}
	// Listen for authorization code response from Azure AD

	/**
	 * Handles the response from a popup or redirect. If response is null, will check if we have any accounts and attempt to sign in.
	 * @param response
	 */
	async handleResponse(response) {
		if (response !== null) {
			this.account = response.account;
		} else {
			this.account = await this.getAccount();
		}

		return this.account;
	}

	/**
	 * Calls getAllAccounts and determines the correct account to sign into, currently defaults to first account found in cache.
	 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
	 */
	async getAccount() {
		const cache = this.clientApplication.getTokenCache();
		const currentAccounts = await cache.getAllAccounts();

		if (currentAccounts === null) {
			console.log('No accounts detected');
			return null;
		}

		if (currentAccounts.length > 1) {
			// Add choose account code here
			console.log('Multiple accounts detected, need to add choose account code.');
			return currentAccounts[0];
		} else if (currentAccounts.length === 1) {
			return currentAccounts[0];
		} else {
			return null;
		}
	}
}
```

### Reproduction Steps

1. try to login 
2. prompt will open to select an account to select 
3. I click the close button or back button 
4. popup will close successfully 
5. repeat step 1 again 
6. prompt will open to select an account to select 
7. select the account and sign in 
8. the sign-in will stop and i can't login again until i restart my app

### Expected Behavior

Login Again Successfully 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by tnorling** [comment] 2022-05-13 18:48
@mustafaAly I'm not sure I understand what the issue is. Msal-node does not provide popup handling code, can you please clarify what you believe is a bug in MSAL?

**Comment by mustafaAly** [comment] 2022-05-15 14:44
i handled popup handling by CreateAuthWindow Function
	static createAuthWindow() {
		return new BrowserWindow({
			width: 400,
			height: 600
		});
	}

**Comment by tnorling** [comment] 2022-05-16 17:24
@mustafaAly Can you please clarify what you believe is a bug in MSAL?

**Comment by derisen** [comment] 2022-05-21 21:22
@tnorling I can reproduce this with our electron samples (@mustafaAly I assume your app is based on [this sample](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop) -in that case the sample is outdated and there is currently a [PR](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop/pull/8) underway to fix that). It looks like the app hangs inside the protocol listener when trying to obtain the auth code. The reason seems to be that, when the user cancels the first sign-in attempt, the code does not catch the exception thrown and unregister the existing protocol before creating a new one, so it keeps listening without ever resolving.

So first of all please checkout either the [Electron TypeScript sample here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp) or the [PR for Electron JavaScript sample](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop/pull/8), which reflects the current best practices. Then, inside the `start()` method of `CustomProtocolListener`, add the line for unregistering the protocol if auth code is not obtained:

```JavaScript
class CustomProtocolListener {
  hostName;
  constructor(hostName) {
    this.hostName = hostName; //A string that represents the host name that should be listened on (i.e. 'msal' or '127.0.0.1')
  }

  // ...
  start() {
    const codePromise = new Promise((resolve, reject) => {
      protocol.registerStringProtocol(this.host, (req, callback) => {
        const requestUrl = new URL(req.url);
        const authCode = requestUrl.searchParams.get("code");

        if (authCode) {
            resolve(authCode)
        } else {
            protocol.unregisterProtocol(this.host);
            reject(new Error("No code found in URL"));
        }

      });
    });

    return codePromise;
  }

// ...
```

Let me know if that resolves your issue. We will update both samples to handle this case properly.

**Comment by mustafaAly** [comment] 2022-05-30 12:15
Hi @derisen thank you for replying and your interest, I will check that and test it again I will make my feedback thank you

**Closed as completed** 2022-05-31 17:22 UTC
Labels: question, msal-node, bug-unconfirmed, msal-node-extensions

**Comment by mustafaAly** [comment] 2022-06-01 11:18
Hi @derisen I tried this solution and it didn't resolve the issue 
I found that when I make this scenario again and run this function 
------------------------
	async getTokenInteractive(tokenRequest) {
		// Generate PKCE Challenge and Verifier before request
		const cryptoProvider = new CryptoProvider();
		const { challenge, verifier } = await cryptoProvider.generatePkceCodes();
		const authWindow = AuthProvider.createAuthWindow();

		// Add PKCE params to Auth Code URL request
		const authCodeUrlParams = {
			...this.authCodeUrlParams,
			scopes: tokenRequest.scopes,
			codeChallenge: challenge,
			prompt: "select_account",
			codeChallengeMethod: "S256"
		};

		try {
			// Get Auth Code URL
			const authCodeUrl = await this.clientApplication.getAuthCodeUrl(authCodeUrlParams);

			const authCode = await this.listenForAuthCode(authCodeUrl, authWindow);

			// Use Authorization Code and PKCE Code verifier to make token request
			const authResult = await this.clientApplication.acquireTokenByCode({
				...this.authCodeRequest,
				code: authCode,
				codeVerifier: verifier
			});

			authWindow.close();
			return authResult;
		} catch (error) {
			authWindow.close();
			throw error;
		}
	}
------------------------ it gives me exception message 
stack:'ServerError: invalid_grant: 501481 - [2022-06-01 11:13:52Z]: AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request.\r\nTrace ID: 0c62d117-034a-487e-8df4-06197cc0b500\r\nCorrelation ID: 82aa83bd-2393-405b-b74e-100c4bd83186\r\nTimestamp: 2022-06-01 11:13:52Z - Correlation ID: 82aa83bd-2393-405b-b74e-100c4bd83186 - Trace ID: 0c62d117-034a-487e-8df4-06197cc0b500\n    at ServerError.AuthError [as constructor] (d:\\Projects\\Bitbucket\\ut-hub\\electron\\node_modu…jects\\Bitbucket\\ut-hub\\electron\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:5093:41)\n    at step (d:\\Projects\\Bitbucket\\ut-hub\\electron\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:79:23)\n    at Object.next (d:\\Projects\\Bitbucket\\ut-hub\\electron\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:60:53)\n    at fulfilled (d:\\Projects\\Bitbucket\\ut-hub\\electron\\node_modules\\@azure\\msal-common\\dist\\index.cjs.js:50:58)\n    at processTicksAndRejections (internal/pr...
any help? 
thanks in advance

**Comment by derisen** [comment] 2022-06-01 16:09
@mustafaAly this is a separate issue, but I'm not able to reproduce it with our electron sample -can you please try reproducing this with the [ElectronTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp) sample and start another issue thread if you can?

**Comment by mustafaAly** [comment] 2022-06-01 16:25
yeah sure let me check

**Comment by imrans110** [comment] 2022-10-11 19:02
hey folks, I am facing the same issue here with the sample code. 

Were you able to find a fix for this @mustafaAly ?

**Comment by derisen** [comment] 2022-10-11 20:57
@imrans110 can you please create a new issue and provide details?
