### ISSUE TITLE
SyntaxError: Invalid regular expression:

### ISSUE THREAD

**Issue by divyanichougale548** [AzureAD/microsoft-authentication-library-for-js#5561] opened 2023-01-12 10:34 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

Cannot load webpack://firestorm-webui/node_modules/@azure/msal-common/dist/cache/entities/CredentialEntity.js due to access control checks.

### Error Message

Cannot load webpack://firestorm-webui/node_modules/@azure/msal-common/dist/cache/entities/CredentialEntity.js due to access control checks.

SyntaxError: Invalid regular expression: invalid group specifier name —

### Msal Logs

NA

### MSAL Configuration

```javascript
his.msalConfig =
{
	auth :
	{
		clientId     : env.AUTH_APP_ID,
		authority    : `https://login.microsoftonline.com/${ env.AUTH_TENANT_ID }/`,
				clientSecret : env.AUTH_CLIENT_SECRET,
	},
	system :
	{
		loggerOptions :
		{
			loggerCallback    : this.log,
			piiLoggingEnabled : true,
			logLevel          : msal.LogLevel.Verbose
		}
	}
};
```

### Relevant Code Snippets

```javascript
import PropTypes from "prop-types";
import React, { useContext } from "react";
import { connect } from "react-redux";

import LangContext from "../../localization/LangContext";
import { selectCurrentWorkspace } from "../../redux/selectors/workspaces";

function WSDetail(props) {
  const { strings } = useContext(LangContext);
  const {
    description,
    businessRegion,
    properties,
    workspaceType,
    licenseType,
  } = props.currentWorkspace;

  return (
    <div style={{ flex: 1 }}>
      <div className="gradientbg WorkspacePoolBoardFirstContinare">
        <span style={{ marginLeft: 10 }}>
          {strings.workspaceDashbaord.workspaceInfo}
        </span>
      </div>
      <div
        className="shadow rounded"
        style={{
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-between",
          marginBottom: 20,
          height: 210,
          padding: 10,
        }}
      >
        <table
          style={{
            marginLeft: "10px",
          }}
        >
          <tbody>
            <tr
              style={{
                display: "flex",
              }}
            >
              <td
                style={{
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  fontWeight: "bold",
                  minWidth: "fit-content",
                }}
              >
                {strings.workspace.description}
                {":"}
              </td>
              <td style={{ marginLeft: "5px" }}>{description}</td>
            </tr>
            <tr
              style={{
                display: "flex",
                marginTop: "10px",
                marginBottom: "10px",
              }}
            >
              <td
                style={{
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  fontWeight: "bold",
                }}
              >
                {strings.workspace.region}
                {":"}
              </td>
              <td style={{ marginLeft: "5px" }}>{businessRegion}</td>
            </tr>
            <tr
              style={{
                display: "flex",
                marginTop: "10px",
                marginBottom: "10px",
              }}
            >
              <td
                style={{
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  fontWeight: "bold",
                }}
              >
                {strings.workspace.address.label}
                {":"}
              </td>

              <td style={{ marginLeft: "5px" }}>
                {properties ? properties.address : " - "}
              </td>
            </tr>
            {workspaceType ? (
              <tr
                style={{
                  display: "flex",
                  marginTop: "10px",
                  marginBottom: "10px",
                }}
              >
                <td
                  style={{
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    fontWeight: "bold",
                  }}
                >
                  {strings.workspace.workspaceType}
                  {":"}
                </td>
                <td style={{ marginLeft: "5px" }}>{workspaceType}</td>
              </tr>
            ) : null}
            {licenseType ? (
              <tr
                style={{
                  display: "flex",
                }}
              >
                <td
                  style={{
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                    fontWeight: "bold",
                  }}
                >
                  {strings.workspace.licenceType}
                  {":"}
                </td>
                <td style={{ marginLeft: "5px" }}>{licenseType}</td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </div>
  );
}

WSDetail.propTypes = {
  currentWorkspace: PropTypes.object.isRequired,
};

function mapStateToProps(state) {
  const current = selectCurrentWorkspace(state);
  return {
    currentWorkspace: current,
  };
}
export default connect(mapStateToProps, null)(WSDetail);
```

### Reproduction Steps

1.hit the application link, it will throw the error 

### Expected Behavior

Login into application

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Regression

2.32.2

### Source

Internal (Microsoft)

**Comment by adamblok** [comment] 2023-01-12 12:16
I can confirm that. After upgrading @azure/msal-browser to 2.32.2, it stopped to working on Safari (both desktop and mobile) because of the error "Invalid regular expression". I've fixed that by downgrading @azure/msal-common in package-lock.json from 9.0.2 to 9.0.1.

**Comment by lazarid** [comment] 2023-01-12 12:55
Has someone fixed it?

**Comment by ralphtheninja** [comment] 2023-01-12 13:20
@adamblok Do you have any more information on where the bug is happening?

**Comment by adamblok** [comment] 2023-01-12 13:32
@ralphtheninja Unfortunately I wasn't able to debug this and by steps by steps I've found that the problem is in 9.0.2. I think it's related to this PR https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5484/files since it contains a new REGEX pattern.

**Comment by Weschk** [comment] 2023-01-12 14:01
@adamblok Thats my guess aswell, if I understand correctly iOS does not support lookbehind so the regex fails.

**Comment by adamblok** [comment] 2023-01-12 15:08
@Weschk Yes, you're right. This pattern doesn't work, since Safari doesn't support lookbehind in regex patterns as https://caniuse.com/js-regexp-lookbehind says.

**Comment by tnorling** [comment] 2023-01-12 17:27
I believe this was addressed in #5551

**Comment by mkosir** [comment] 2023-01-12 20:42
Can confirm having same issue on iOS/Chrome.

**Comment by hectormmg** [comment] 2023-01-12 20:45
Closing as duplicate of #5548

**Closed as completed by hectormmg** 2023-01-12 20:45 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client

**Comment by mkosir** [comment] 2023-01-12 20:51
@hectormmg since both issues are closed, and [PR with fix](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5551) is merged, is there any rough plan on releasing new version (with PR fix included)?
Until then for anyone coming to this issue, [this is a workaround](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5548#issuecomment-1378328047) that works.
