### ISSUE TITLE
ES5 with Angular / Ivy breaks build with getInternalNameOfClass() called on a non-ES5 class

### ISSUE THREAD

**Issue by Crio1979** [AzureAD/microsoft-authentication-library-for-js#3277] opened 2021-03-22 10:29 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
When using Ivy in Angular (> 9) and tsconfig.json targets ES5 the build fails with the following error. I can fix the error by switching to ES2015, but this is currently not an option because it breaks other functionality in the target app. 
Interestingly when I switch to ES2015, run a build and then switch back to ES5 it works despite building with --delete-output-path.

```
Warning: Invalid constructor parameter decorator in D:/Programs/Teamcity/buildAgent/work/25e12c73cdc1a14f/node_modules/@azure/msal-angular/fesm2015/azure-msal-angular.js:
 () => [
    { type: undefined, decorators: [{ type: Inject, args: [MSAL_INSTANCE,] }] },
    { type: Location }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected MsalService to have an inner class declaration
```

## Error Message

```
Warning: Invalid constructor parameter decorator in D:/Programs/Teamcity/buildAgent/work/25e12c73cdc1a14f/node_modules/@azure/msal-angular/fesm2015/azure-msal-angular.js:
 () => [
    { type: undefined, decorators: [{ type: Inject, args: [MSAL_INSTANCE,] }] },
    { type: Location }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected MsalService to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
    at extractInjectableMetadata (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:123:69)
    at InjectableDecoratorHandler.analyze (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:341:40)
    at analyze (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:293:58)
    at _loop_1 (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:315:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:35)
    at NgccTraitCompiler.analyzeFile (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:166:27)
    at D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:50:95
    at ClusterMaster.<anonymous> (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:246:57)
    at step (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\tslib\tslib.js:139:27)
    at Object.next (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\tslib\tslib.js:120:57)
    at D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (D:\Programs\Teamcity\buildAgent\work\25e12c73cdc1a14f\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:240:32)
    at EventEmitter.emit (events.js:198:13)
```

## MSAL Configuration
Build issue rather than configuration issue

### tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": ["./node_modules/@types"],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "include": [
    "./src",
    "./node_modules/cypress"
  ],
  "exclude": [
    "./node_modules/cypress"
  ]
}
```

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
MSAL v2.0 builds for ES5 as well as ES2015, Ivy is supported.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version: 1.4.1

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment] 2021-05-03 21:25
@Crio1979 Apologies for the delayed response. I am unable to reproduce this behavior using our Angular 11 sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/971e30f44c76b6c29546e80e69b3f881624808d8/samples/msal-angular-v2-samples/angular11-sample-app/tsconfig.json#L18

Are you able to reproduce this error with that sample? And if so, can you share details? Thanks!

**Comment by sanjaysarena** [comment] 2021-07-22 14:57
issue persists with Angular 9.1.
with ngcc getting the following error:
![image](https://user-images.githubusercontent.com/42990692/126661021-d198f5ab-a6e8-40da-a4b2-d15dfe2700db.png)

target is es5

**Comment by anton-marchenko** [comment] 2021-09-08 07:36
The project for reproducing the issue is here:
[ng9.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/7126737/ng9.zip)

Node: v14.15.0

Note: if you change tsconfig.json target from "es5" to "es2015" and revert it to "es5" the issue will stop to reproduce. In this case you should remove `node_modules` folder and make `npm i`. Then the issue will start to reproduce again.

_From Russia with love._

**Comment by anton-marchenko** [comment] 2021-09-10 12:27
@jasonnutter 

> @Crio1979 Apologies for the delayed response. I am unable to reproduce this behavior using our Angular 11 sample:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/971e30f44c76b6c29546e80e69b3f881624808d8/samples/msal-angular-v2-samples/angular11-sample-app/tsconfig.json#L18
> 
> Are you able to reproduce this error with that sample? And if so, can you share details? Thanks!

I noticed that Angular 10 ignores `"target": "es5"` option. I suppose it is same for Angular 11. Instead of compiling `esm5`, Angular 10 compiles code to `esm2015`.

Angular 10 output with `"target": "es5"`:

```
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
```

Angular 9 output with `"target": "es5"`:

```
Compiling @angular/core : module as esm5
Compiling @angular/animations : module as esm5
Compiling @angular/compiler/testing : module as esm5
Compiling @angular/animations/browser : module as esm5
```

**Comment by sameerag** [comment] 2022-04-02 05:10
@jasonnutter Did we sort this?

**Comment by jasonnutter** [comment] 2022-04-04 20:13
No, we have not addressed this.

**Comment by Lonli-Lokli** [comment] 2023-03-23 20:45
IE is not supported anymore, why do you need es5 now? As well as angular 9 which is not supported too

**Comment by tnorling** [comment] 2023-07-06 20:42
Closing as Ivy will be supported in msal-angular v3 (currently in beta) but will not be backported to v2. Please track issue #4298 for announcements on general availability of v3

**Closed by tnorling** 2023-07-06 20:42 UTC
Labels: bug, msal-angular, tracked-internally
