### ISSUE TITLE
Not able to retrieve account on first page load

### ISSUE THREAD

**Issue by MarianoVeloso** [AzureAD/microsoft-authentication-library-for-js#5603] opened 2023-01-23 17:42 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.5.1

### Public or Confidential Client?

Public

### Description

Hi! I need to make a call to the API in the first load of my page, so I have seted up a Hook to make that call. For some reason that I don't understand, MSAL is not able to retrieve the user account in the first load. I mean, if if refresh the page, everything works as expected, but in the redirection of B2C Login the code breaks on acquireTokenSilent() method.

The error that i'm getting 
![image](https://user-images.githubusercontent.com/68289381/214110776-2a29a4fb-5523-4686-b579-ae14d902922c.png)

Behavior on the second load (like browser refresh or any update inside of the app)
![Screenshot 2023-01-23 144409](https://user-images.githubusercontent.com/68289381/214111311-b7c8f038-eb10-4676-9855-02b77e69f455.png)

### MSAL Configuration

```javascript
auth: {
		clientId: String(process.env.REACT_APP_MSAL_CLIENTID),
		authority: String(process.env.REACT_APP_MSAL_AUTHORITY),
		knownAuthorities:[String(process.env.REACT_APP_MSAL_KNOWN_AUTHORITIES)], // This is a URL (e.g. https://login.microsoftonline.com/{your tenant ID})
		redirectUri: '/'
	},
	cache: {
		cacheLocation: 'sessionStorage', // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
		storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
	},
	system: {
		loggerOptions: {
			loggerCallback: (level: LogLevel, message: string, containsPii: unknown) => {
				if (containsPii) {
					return;
				}
				switch (level) {
				case LogLevel.Error:
					trackException(message);
					console.error(message);
					return;
				default:
					return;
				}
			},
		},
	},
```

### Relevant Code Snippets

```javascript
My index.tsx

const root = ReactDOM.createRoot(
	document.getElementById('root') as HTMLElement
);
  
root.render(
	<React.StrictMode>
		<MsalProvider instance={msalInstance}>
			<BrowserRouter>
				<RecoilRoot>
					<AppInsightsContext.Provider value={reactPlugin}>
						<AxiosInterceptors>
							<App />	
						</AxiosInterceptors>
					</AppInsightsContext.Provider>
				</RecoilRoot>
			</BrowserRouter>
		</MsalProvider>
	</React.StrictMode>
);

const App = () => {
	AxiosInterceptors();
	const { isLoadingHandleUserState } = useHandleUserState(); //<--- my very first call
	
	if(isLoadingHandleUserState)
	{
		return (
			<>
				<Header	/>
				<MuiBackdrop/>
			</>
		);
	}else{

		const authRequest = {
			...loginRequest
		};
		return (
			<ThemeProvider theme={customThemProvider}>
				<div className="App">
					<RecoilBackdrop/>
					<AuthenticatedTemplate>
						//the rest of the site
					</AuthenticatedTemplate>
					<UnauthenticatedTemplate>
						<MsalAuthenticationTemplate 
							interactionType={InteractionType.Redirect} 
							authenticationRequest={authRequest}
							loadingComponent={MuiBackdrop}
						>
						</MsalAuthenticationTemplate>
					</UnauthenticatedTemplate>	
				</div>
			</ThemeProvider>
		);	
	}
};

const AxiosInterceptors = () => {
	const { instance } = useMsal();
	
	const account = instance.getAllAccounts()[0];

	axiosInstances.interceptors.request.use(async function (config) {
		const accessTokenRequest = {
			scopes: [''], 
			account: account,
		};
		
		await instance.acquireTokenSilent(
			accessTokenRequest
		)
			.then((res) => {
				const bearer = `Bearer ${res.idToken}`;
				config.headers = config.headers ?? {};
				config.headers.Authorization = bearer;
			})
			.catch((err) => console.error(err));
			
		return config;
	}, function (error) {
		trackException(error);
		return Promise.reject(error);
	});
		
	axiosInstances.interceptors.response.use(function (response) {
		return response;
	}, function (error: AxiosError) {
		console.error(error);
		trackException(error.message);
		if (error.status == StatusCode.Forbidden || error.status == StatusCode.Unauthorized) {
			SignOutUser(instance);	
		}
		return Promise.reject(error);
	});
};


export default function useHandleUserState () {
	const [isLoading, setIsloading] = useState(true);    
	const [userVerified, setUserVerifiedState] = useRecoilState(setUserVerified);

	const setVerifiedUser = (verified: boolean) => {
		setUserVerifiedState(verified);
	};

	const inspectUser = () => {
		setIsloading(true);
		UserService.isVerified()
			.then((res) =>{
				setVerifiedUser(Boolean(res.data));
				setIsloading(false);
			})
			.catch((err) => {
				console.log(err);
				setVerifiedUser(false);
				setIsloading(false);
			});
	};

	useEffect(() =>{
		if(!userVerified){
			inspectUser();
		}
		else{
			setIsloading(false);
		}
	}, []);
	
	return { isLoadingHandleUserState: isLoading };
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by sameerag** [comment] 2023-01-30 04:02
@MarianoVeloso `acquireTokenRedirect` reloads the page for authentication (to retrieve the auth code and exchange it with the server to fetch a token). In your case, Can you confirm that you are not checking for an account or calling `acquireTokenSilent` without loading the account info?

For code patterns, you can check our samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples).

cc @derisen if you can help regarding the usage here.

**Comment by derisen** [comment] 2023-01-30 18:17
@MarianoVeloso can you also please share verbose level [msal logs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#logger-config-options). This could be a race condition -do you have a public repo for reproduction?

**Comment by MarianoVeloso** [comment] 2023-02-01 17:22
Hi! @sameerag I did follow up the examples so that's why I seted up the way that I do on the interceptors, this not a good approach?

**Comment by MarianoVeloso** [comment] 2023-02-01 17:24
hi! @derisen I have solved my problem with this code but i'm not sure if this is correct. In my index.tsx I do this:


```
export const msalInstance = new PublicClientApplication(msalConfig);

// Default to using the first account if no account is active on page load
if (!msalInstance.getActiveAccount() && msalInstance.getAllAccounts().length > 0) {
	// Account selection logic is app dependent. Adjust as needed for different use cases.
	msalInstance.setActiveAccount(msalInstance.getAllAccounts()[0]);
}

// Optional - This will update account state if a user signs in from another tab or window
msalInstance.enableAccountStorageEvents();

msalInstance.addEventCallback((event) => {
	if (
		(event.eventType === EventType.LOGIN_SUCCESS ||
            event.eventType === EventType.ACQUIRE_TOKEN_SUCCESS ||
            event.eventType === EventType.SSO_SILENT_SUCCESS) &&
		//@ts-ignore
        event.payload.account
	) {
		//@ts-ignore
		msalInstance.setActiveAccount(event.payload.account);
	}else if(event.eventType === EventType.LOGIN_FAILURE){		
		if (event.error?.message.includes(errorCodes.forgotPassword)) {
			const authority = b2cPolicies.authorities.forgotPassword;
			msalInstance.loginRedirect(authority as RedirectRequest);
		}
	}
});

const root = ReactDOM.createRoot(
	document.getElementById('root') as HTMLElement
);

const AppRender = () => {
	const [renderApp, setRenderApp] = useState(false);

	msalInstance
		.handleRedirectPromise()
		.then(() => {
			setRenderApp(true);
		})
		.catch(() => {
			setRenderApp(true);
		});

	if(renderApp) 
		return(<App/>); 
	return <></>;
};

root.render(
	<React.StrictMode>
		<MsalProvider instance={msalInstance}>
			<BrowserRouter>
				<RecoilRoot>
					<AppInsightsContext.Provider value={reactPlugin}>
						<AppRender />
					</AppInsightsContext.Provider>
				</RecoilRoot>
			</BrowserRouter>
		</MsalProvider>
	</React.StrictMode>
);

```
So I noticed that with this promise handleRedirectPromise() I have already the token once it scapes by .then

**Comment by derisen** [comment] 2023-02-03 01:40
@MarianoVeloso still not sure what caused the original issue, but I think it's because you were calling `AxiosInterceptors()` before `MsalAuthenticationTemplate`  triggers a login (unless there was something else that triggers login).

In the last snippet you shared (which would work), you're using `handleRedirectPromise()`, which shouldn't be needed since msal-react abstracts this away. Instead, you can add an [event callback](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/events.md) to the `AppRender` component for [msal login events](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md), then fire a call to your API when that event takes place ([see](url) for more).

**Comment by sameerag** [comment] 2023-02-14 23:53
Closing, @derisen provided context and in case if you still need help, please raise a new one.

**Closed as completed by sameerag** 2023-02-14 23:53 UTC
Labels: question, b2c, msal-browser, no-issue-activity, msal-react, public-client
