### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#3383] opened 2021-04-05 13:26 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi Team,

I see the following warning while building my SPA:

ERROR  [BABEL] Note: The code generator has deoptimised the styling of /Users/karantikku/Work/IMS/edat-ims-heroku-client/node_modules/bootstrap-vue/src/icons/icons.js as it exceeds the max of 500KB.

How can I reduce the bundle size of @azure/msal-browser? 

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment] 2021-04-05 15:23
Closing as a duplicate of #3210

**Closed by jasonnutter** 2021-04-05 15:23 UTC
Labels: msal-browser, question
