### ISSUE TITLE
msal js wrongly states scope does not exist in chrome for android

### ISSUE THREAD

**Issue by jannikbuschke** [AzureAD/microsoft-authentication-library-for-js#511] opened 2018-12-17 12:34 UTC
## I'm submitting a...
 - [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Browser:
- [ ] Chrome version XX
- [x] Chrome on Android version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior

On Android Chrome the following error is printed to the console when acquiring a token silently: 
Uncaught (in promise) AADSTS70002: Error validating credentials. AADSTS65005: The application 'xxx' asked for scope 'user.read' that doesn't exist. Contact the app vendor.
Trace ID: xxx
Correlation ID: xxx
Timestamp: xxxZ|invalid_client

## Expected behavior

A valid token should be returned.
On desktop chrome, firefox and safari the code successfully runs and a token is returned.

**Comment by navyasric** [comment] 2018-12-18 00:51
@jbuschke Which API are you trying to get a token for? Also, can you provide a snippet of how you are using MSAL.js to get the token or a network request being sent?

Please check this topic to see how to pass scopes and if that helps you: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs

**Comment by jbuschke** [comment] 2018-12-18 16:49
@navyasric Im trying to get a token for my own api hosted in azure. The code thats failing looks like this

`await userAgentApplication.acquireTokenSilent(["xxxxxxxx-xxx-xxx-xxxx-xxxxxxxxxxx/user.read"]);`

where xxx... is the application id in the azure tenant. As mentioned this code works within chrome for desktop. I get a valid token back with which I can make authorized API calls

**Comment by ajbeaven** [comment] 2019-01-22 09:03
I'm getting the same error message when using the same structure for the scope (`{clientId}/user.read`). The only difference is this is occurring on chrome for desktop as well as other browsers. Some users report that it works on Edge, but it doesn't work for me.

The issue seems to occur intermittently. After initially setting this up, the login popup would appear as it should have and a correct token was generated. A while after, with no changes to the code, I started receiving this error.

@jannikbuschke did you manage to figure out the cause of this issue or get it working correctly?

**Comment by ajbeaven** [comment] 2019-01-23 21:39
I believe #488 may also be relevant to this issue.

**Comment by jannikbuschke** [comment] 2019-02-18 08:18
@ajbeaven @navyasric Im seeing the issue now also on Chrome for Desktop. Application asked for scope 'User.Read' that doesn't exist

**Comment by jannikbuschke** [comment] 2019-02-18 08:40
One thing I noticed is that the error appears when I use the loginPopup(scopes) function. When I invoke loginPopup() without scopes, or loginRedirect() the error doesnt seem to appear on Chrome for Desktop (not tested on Android)

**Comment by ajbeaven** [comment] 2019-02-18 10:25
@jannikbuschke I ended up not using the `{tenantId]/user.read` syntax for the graph scopes as it just wasn't working reliably. I don't know where this syntax is documented - if I remember correctly I found it on an example lying around somewhere. I believe I originally went this direction because the standard `user.read` scope failed to generate a token that could be used for authentication. Using `{tenantId}/user.read` worked for backend authentication but then these intermittent clientside errors occurred when generating the token.

I've only recently figured out that the cause of my backend authentication problems was because I was passing back the `access_token` in the Bearer authentication header instead of the `id_token`. Changing to use `id_token` for authentication worked for the standard `user.read` scope so I could avoid the problems described in this issue. Hopefully that's helpful!

**Comment by jannikbuschke** [comment] 2019-02-19 22:30
Are you just using `user.read` without tenantid? I think this is the same as `https://graph.microsoft.com/user.read`. The documentation could really be improved here.

**Comment by ajbeaven** [comment] 2019-02-20 01:28
@jannikbuschke yep, now I'm just using `user.read`

**Comment by navyasric** [comment] 2019-02-26 21:35
@jannikbuschke @ajbeaven Thank you for the feedback. If you are trying to access MS Graph API, you must use the scopes `user.read` as you mentioned and it is the same as `https://graph.microsoft.com/user.read`.  This has been updated in the documentation of our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q1-adal-vs-msal).
Closing this issue as it seems resolved.

**Closed by navyasric** 2019-02-26 21:35 UTC
