### ISSUE TITLE
Acquire both id_token and access_token in one call

### ISSUE THREAD

**Issue by hrishy** [AzureAD/microsoft-authentication-library-for-js#1250] opened 2020-01-28 09:30 UTC
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How do i acquire both id_token and access_token in one call to azure id ? 
Any code sample for this using silentToken refresh please ?

**Comment by jasonnutter** [comment] 2020-01-29 23:59
@hrishy Can you explain your use case? The library sets the response type based on the status of the cache and request type.

**Comment by sameerag** [comment] 2020-01-31 19:26
@hrishy We discourage fetching both tokens always by default: `response_type` is set by the library and not by the user by design. If a user is logging in for the first time, we set it to `id_token`; based on the cache state and any hint sent to us about an existing session, we set it to `id_token_token`. We advise the users not to modify this, as this may cause performance issues fetching two tokens for all use cases, even in cases you don't need to. It also may cause issues in older browsers like IE which is tracked with #1172

If you have a login_hint (which implies you have logged in at-least once) and have an active session, you can call `acquireTokenSilent()` which dynamically determines this for you.

You can always retrieve the current `idToken` from the cache (`localStorage' or `sessionStorage`) or from the `response`.

Hope this helps.

**Comment by system47** [comment] 2020-03-03 01:25
Hi @sameerag, 

I may have a different use case than @hrishy but I do have the same issue. The app I'm building utilizes Graph API calls for the frontend's layout (which requires the access_token), in addition to making calls to my backend API with the id_token. Because the Graph API calls are a part of the layout, this forces two full redirection flows when a user initially logs in to the application to retrieve both tokens, which is a poor user experience. 

Is there an alternative to this where I can obtain both tokens silently, or with a single redirection flow being invoked?

**Comment by tnorling** [comment] 2020-04-17 18:25
@system47 Apologies for the delayed response. You can provide the graph scopes you need to consent to in your login request. This will do a pre-consent and allow you to call ```acquireTokenSilent``` to acquire the access tokens silently without needing a second redirect.

Closing this as the original question has been answered but feel free to open a new issue if you have additional questions.

**Closed by tnorling** 2020-04-17 18:25 UTC
Labels: follow-up, more-information-needed, question
