### ISSUE TITLE
MSAL is not cleaning up local storage

### ISSUE THREAD

**Issue by freeman-g** [AzureAD/microsoft-authentication-library-for-js#370] opened 2018-08-02 15:31 UTC
We use MSAL to request and renew ID tokens and Access tokens. 

Here's an example of how we use it:

```
let userAgentApplication = new Msal.UserAgentApplication(msalGlobal.clientID, msalGlobal.authority, null, {
  redirectUri: msalGlobal.redirectUri,
  cacheLocation: 'localStorage',
  logger: msalGlobal.logger,
  postLogoutRedirectUri: msalGlobal.postLogoutRedirectUri
})

function callGraphApi() {
  var user = userAgentApplication.getUser()
  if (!user) {
    userAgentApplication.loginRedirect(msalGlobal.graphAccessTokenScopes)
  } else {
    userAgentApplication.acquireTokenSilent(msalGlobal.graphIdTokenScopes)
      .then((idToken) => {
        userAgentApplication.acquireTokenSilent(msalGlobal.graphAccessTokenScopes).then(accessToken => {
        }, (error) => {
          console.log(error)
        })
      }, (error) => {
        userAgentApplication.loginRedirect(msalGlobal.graphAccessTokenScopes)
        console.log(error)
      })
  }
}

callGraphApi()
```

Recently I have noticed that MSAL is leaving a bunch of data laying around in local storage. Over time this data continues to grow.

Here are a couple of screenshots:

![image](https://user-images.githubusercontent.com/495886/43593772-a2204888-9646-11e8-9e06-0b57ca22f684.png)

![image](https://user-images.githubusercontent.com/495886/43593817-be299dcc-9646-11e8-8eb7-6d30d20bd6eb.png)

**Comment by nehaagrawal** [comment] 2018-08-02 22:55
@freeman-g  we recently fixed this issue in MSAL 0.1.9 reelase. Which version of library you are using? If you are on a older version, can you please update and try again? Please let me know if the issue still exists.

**Comment by freeman-g** [comment] 2018-08-03 12:12
Thanks - We are using 0.1.7. I'll upgrade and give 0.1.9 a try.

**Comment by nehaagrawal** [comment] 2018-08-03 17:57
@freeman-g  Can you please update us here if the issue is resolved so that we can close this issue :-)

**Comment by freeman-g** [comment] 2018-08-04 10:25
Thanks for the help

**Closed** 2018-08-04 10:25 UTC
Labels: needs info
