### ISSUE TITLE
popup flow broken in full-screen macOS

### ISSUE THREAD

**Issue by yoLotus** [AzureAD/microsoft-authentication-library-for-js#4921] opened 2022-06-22 17:09 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

It seems that using the `loginPopup` function does not work properly on *full-screen*  mode on **macOS**.
The popup never get closed and the flow fails silently.
When the browser is not in *full-screen* mode, it always works as expected.

This issue has already been reported in #4839 but even with the library version `2.26.0`, it's still not working.
We also tried to follow those [instructions](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations) but without success.

This [example](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default) also fails in the same way.

### Error Message

We don't get any error neither in the parent window nor the popup.

### Msal Logs

Navigated to https://login.live.com/oauth20_authorize.srf?client_id=bbeb7747-ff22-4d91-b4d1-5847e7986bf4&scope=User.Read+email+profile+openid+offline_access&redirect_uri=https%3a%2f%2fadmin.getcontrast.dev&response_type=code&state=eyJpZCI6IjNkOGJjNWY3LTY0ODQtNGJlNi04ZDkwLTRlOTE4MTM5NmQ0ZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3d&response_mode=fragment&nonce=ea4795fd-61eb-414b-a359-d8797cf6ca74&code_challenge=HFjlKBs7AmsVWArHURPcLy7_h8kqv2hK903oVH1-4aw&code_challenge_method=S256&x-client-SKU=msal.js.browser&x-client-Ver=2.26.0&uaid=3dc3690e4b194502b9c13592b9c43424&msproxy=1&issuer=mso&tenant=common&ui_locales=fr-FR&client_info=1&epct=AQABAAAAAAD--DLA3VO7QrddgJg7WevrprbipdRja0-Eq_g8YusVTfzTyimTvpxSMoW2-CWXSL24udMbi7Mf6u_TWzCXQ1gTfvZuGOoQbDjWI1SGJI3KRmn2Q6u0CECf1cy9iuKzql5cOJI75-LL7Qbwnn1R2nWDefsP29mr-FKqFZcgzOJdUD4myTGfCbp6H1n-Z2UeKani_mArk6IIhJjDDSXMcx5oWCKDGDTyFN-mqWvyPV96LyAA&jshs=0&username=xxxxxxx%40outlook.com&login_hint=xxxxxxx%40outlook.com
Navigated to https://login.live.com/ppsecure/post.srf?client_id=bbeb7747-ff22-4d91-b4d1-5847e7986bf4&scope=User.Read+email+profile+openid+offline_access&redirect_uri=https%3a%2f%2fadmin.getcontrast.dev&response_type=code&state=eyJpZCI6IjNkOGJjNWY3LTY0ODQtNGJlNi04ZDkwLTRlOTE4MTM5NmQ0ZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3d&response_mode=fragment&nonce=ea4795fd-61eb-414b-a359-d8797cf6ca74&code_challenge=HFjlKBs7AmsVWArHURPcLy7_h8kqv2hK903oVH1-4aw&code_challenge_method=S256&x-client-SKU=msal.js.browser&x-client-Ver=2.26.0&msproxy=1&issuer=mso&tenant=common&ui_locales=fr-FR&client_info=1&epct=AQABAAAAAAD--DLA3VO7QrddgJg7WevrprbipdRja0-Eq_g8YusVTfzTyimTvpxSMoW2-CWXSL24udMbi7Mf6u_TWzCXQ1gTfvZuGOoQbDjWI1SGJI3KRmn2Q6u0CECf1cy9iuKzql5cOJI75-LL7Qbwnn1R2nWDefsP29mr-FKqFZcgzOJdUD4myTGfCbp6H1n-Z2UeKani_mArk6IIhJjDDSXMcx5oWCKDGDTyFN-mqWvyPV96LyAA&jshs=0&username=xxxxxxx%40outlook.com&login_hint=xxxxxxx%40outlook.com&contextid=A224BC714EFD7E88&bk=1655913753&uaid=3dc3690e4b194502b9c13592b9c43424&pid=15216
Navigated to https://example.com

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: 'bbeb7747-ff22-4d91-b4d1-5847e7986bf4',
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: 'https://example.com',
  },
};
```

### Relevant Code Snippets

```javascript
const loginRequest = {
  scopes: ['User.Read', 'email', 'profile', 'openid'],
};

const msalInstance = new PublicClientApplication(msalConfig);
const loginResponse = await msalInstance.loginPopup(loginRequest);
msalInstance.setActiveAccount(loginResponse.account);
const tokenResponse = await msalInstance.acquireTokenSilent(loginRequest);
```

### Reproduction Steps

1. Open the application in full-screen browser
2. Click the `Sign in` button
3. After being redirected to new tab, log in into Microsoft and accept the permission requested by the app

### Expected Behavior

After the authentication, the popup is closed and the control is yield back to the parent window.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by jerryliang64** [comment] 2022-06-24 02:31
I faced this problem too, beside I always fail to login when I'm full sceen. Here is the error:
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/8124783/175450436-739165a6-e690-4b0b-bced-3e5af0b2cc82.png">

**Comment by bmahall** [comment] 2022-06-27 15:30
@yoLotus  I am currently looking into this , thanks for your patience!

**Comment by yoLotus** [comment] 2022-07-04 15:46
A comment to just to let this issue opened

**Comment by sumedhdev** [comment] 2022-07-10 22:38
I'm also having this issue.

**Comment by sailor** [comment] 2022-07-21 13:02
I'm also having the same problem.

**Comment by tlockhart** [comment] 2022-08-17 16:51
I am experiencing a similiar issue.  When logging into my application in full-screen (macOS), msal opens a loginRedirect  in a new window, instead of a loginPopup.  After log-in, the new window redirects to my sign-in page, instead of the dashboard.  When not in full-screen, the loginPopup works just fine.

**Comment by danielvoigt** [comment] 2022-08-24 22:27
Experiencing the same issue: #5123

**Comment by jasonnutter** [comment] 2022-08-25 16:35
@jo-arroyo Looks like this is duplicate of #5123, can we close one of them?

**Comment by bmahall** [comment] 2022-08-26 20:55
@yoLotus Sorry for the wait. We are investigating this issue on our end and will get back with a resolution .  We are able to reproduce this issue on Mac in full screen - Safari and Chrome. 
It seems that the hash is lost in redirection, which is leading to the error listed above. Checking with the team for potential solution, thanks so much for your patience

**Comment by yoLotus** [comment] 2022-08-28 15:44
Thx for the update @bmahall 🙏

**Comment by wnuczek** [comment] 2022-08-29 08:17
Recently I've been struggling to get MSAL to work in two of my angular apps. 
I've also had this issue with Mac fullscreen but most importantly same thing happened on iOS (tested both Safari and Chrome). The popup wouldn't close and redirect to main app. 

Check out redirectUri considerations [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirecturi-considerations) as **setting blank html as redirectUri fixed both issues** for me.

**Comment by peterzenz** [comment] 2022-08-30 22:48
@sameerag I believe you were tracking this item.

**Comment by AK-Loblaw** [comment] 2022-09-09 17:28
@yoLotus, @sameerag, any more details on this? I've been experiencing the same issue. Hoping it doesn't get closed.

**Comment by James-Thibaudeau** [comment] 2022-09-14 19:17
I am also having the same issue, using MSAL.js v2 (@azure/msal-browser) 2.28.3

**Comment by sameerag** [comment] 2022-09-19 04:00
@James-Thibaudeau @AK-Loblaw and @yoLotus 
Did the suggestion above by @wnuczek work in your case?

I am picking this issue and will be working with @bmahall to reproduce it.

**Comment by sameerag** [comment] 2022-09-19 04:01
Same as #4458

**Comment by rutherfordjp8** [comment] 2022-09-20 20:40
Having same issue with msal-react. A fix would be much appreciated!

**Closed as completed** 2022-09-28 01:01 UTC
Labels: question, msal-browser, no-issue-activity, bug-unconfirmed, Needs: Author Feedback

**Comment by AK-Loblaw** [comment] 2022-09-28 12:25
@sameerag, sorry for the delay. No, I'm afraid it didn't help in my case. 

Was this issue closed due to a fix?

**Comment by rutherfordjp8** [comment] 2022-09-28 17:08
@sameerag  @bmahall

Can we please reopen this if there's not been a fix?

**Comment by spuyet** [comment] 2022-10-03 11:05
We've exactly the same issue here, any ETA for a fix ?

**Comment by eqdrs** [comment] 2022-10-03 11:47
I am experiencing the same issue. Is there any update on the fix?

**Comment by matEhickey** [comment] 2022-10-03 12:42
Same on my end, @bmahall  @sameerag is there any update ?

**Comment by chrisneven** [comment] 2022-12-16 15:21
We're still experiencing the same issue unfortunately. Is there maybe a workaround?

**Comment by kostikovk** [comment] 2022-12-20 11:57
The issue is still existed, why it closed?

**Comment by Cambencoil** [comment] 2023-01-04 13:14
Hey, 

i still have the issue : popup flow broken in full-screen macOS
it's been 3 months. 
Does anyone could help me?

**Comment by kostikovk** [comment] 2023-01-04 13:41
@Cambencoil Hey,

You need to create:
1. `blank.html`, this should be just empty `html` file 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/24458699/210566527-89dac833-6100-4426-a2e1-14ddbf329209.png">

2. Add `redirectUri` to this `blank.html` file

```js
const msal = new PublicClientApplication({
  auth: {
    clientId: 'id',
    authority: 'authority',
    redirectUri: '/blank.html',
    postLogoutRedirectUri: '/'
  }
})
```
[DOCS](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirecturi-considerations)

It works for me for the `VUE` project.

**Comment by jorge-d** [comment] 2023-01-06 18:33
Thanks @KosKosovuch ! it did fix the issue on our side 👏🏽

**Comment by Gwitchr** [comment] 2023-02-27 21:54
Very much experiencing this, any chance that @yoLotus solved it ?

**Comment by Dario91** [comment] 2023-03-03 20:39
Same here, any news on this issue?

**Comment by Prasun-Acharjee** [comment] 2023-07-12 12:28
Any update on this issue?

**Comment by Pro-v-7** [comment] 2023-07-12 12:45
@Prasun-Acharjee create blank.html and put redirectUri: '/blank.html'. this is given in documentation.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirecturi-considerations

**Comment by Prasun-Acharjee** [comment] 2023-07-12 12:45
> @Prasun-Acharjee create blank.html and put redirectUri: '/blank.html'. this is given in documentation. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirecturi-considerations

Thanks!

This worked for me!!!
