### ISSUE TITLE
Unable to fix useMsal and MsalProvider issue with react testing library

### ISSUE THREAD

**Issue by ranshine** [AzureAD/microsoft-authentication-library-for-js#6709] opened 2023-11-21 04:48 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.7

### Public or Confidential Client?

Public

### Description

 /Users/ram/SAMPLE_MF/testjest/node_modules/@azure/msal-react/dist/index.js:4
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { MsalProvider } from "@azure/msal-react";
        | ^
      3 | import { IPublicClientApplication } from "@azure/msal-browser";
      4 | import Sample from './Sample'
      5 | interface AppProps {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/App.tsx:2:1)
      at Object.require (src/__tests__/App.test.tsx:3:1)

### Msal Logs

 /Users/ram/SAMPLE_MF/testjest/node_modules/@azure/msal-react/dist/index.js:4
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { MsalProvider } from "@azure/msal-react";
        | ^
      3 | import { IPublicClientApplication } from "@azure/msal-browser";
      4 | import Sample from './Sample'
      5 | interface AppProps {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/App.tsx:2:1)
      at Object.require (src/__tests__/App.test.tsx:3:1)

    TypeError: Cannot read properties of undefined (reading 'inProgress')

       7 |
       8 | const Home = () => {
    >  9 |   const { inProgress, instance } = useMsal()
         |                     ^
      10 |   const isAuthenticated = useIsAuthenticated()
      11 |   const { signOut, signIn } = useAuth()
      12 |   const { getUserListData, getTodoList } = useDashboard()

      at inProgress (src/screens/Home.tsx:9:21)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20074:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21587:16)

### MSAL Configuration

```javascript
import { Configuration, PopupRequest } from "@azure/msal-browser";

// Config object to be passed to Msal on creation
export const msalConfig: Configuration = {
	auth: {
		clientId: "b5c2e510-4a17-4feb-b219-e55aa5b74144",
		authority: "https://login.microsoftonline.com/common",
		redirectUri: "/",
		postLogoutRedirectUri: "/"
	},
	system: {
		allowNativeBroker: false // Disables WAM Broker
	}
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest: PopupRequest = {
	scopes: ["User.Read"]
};

// Add here the endpoints for MS Graph API services you would like to use.
export const graphConfig = {
	graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};
```

### Relevant Code Snippets

```javascript
/Users/ram/SAMPLE_MF/testjest/node_modules/@azure/msal-react/dist/index.js:4
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { MsalProvider } from "@azure/msal-react";
        | ^
      3 | import { IPublicClientApplication } from "@azure/msal-browser";
      4 | import Sample from './Sample'
      5 | interface AppProps {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/App.tsx:2:1)
      at Object.require (src/__tests__/App.test.tsx:3:1)
```

    TypeError: Cannot read properties of undefined (reading 'inProgress')

       7 |
       8 | const Home = () => {
    >  9 |   const { inProgress, instance } = useMsal()
         |                     ^
      10 |   const isAuthenticated = useIsAuthenticated()
      11 |   const { signOut, signIn } = useAuth()
      12 |   const { getUserListData, getTodoList } = useDashboard()

      at inProgress (src/screens/Home.tsx:9:21)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20074:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21587:16)

### Reproduction Steps

 /Users/ram/SAMPLE_MF/testjest/node_modules/@azure/msal-react/dist/index.js:4
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { MsalProvider } from "@azure/msal-react";
        | ^
      3 | import { IPublicClientApplication } from "@azure/msal-browser";
      4 | import Sample from './Sample'
      5 | interface AppProps {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/App.tsx:2:1)
      at Object.require (src/__tests__/App.test.tsx:3:1)

### Expected Behavior

msal should support react testing library and able to test msal code

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

3.1.0

### Source

Internal (Microsoft)

**Comment by patrickfatrick** [comment] 2023-11-21 18:15
This isn't an msal-reactproblem as such, it's a problem with jest's handling of ESM. See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6487 The best solution IMO wold be for this package to export both commonjs and esm until jest has better support for ESM.

**Comment by tnorling** [comment] 2023-12-12 19:29
Closing as duplicate of #6487. Please track that issue for this request

**Closed as completed by tnorling** 2023-12-12 19:29 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client
