### ISSUE TITLE
Login after logout, sometimes automatically reauthenticates?

### ISSUE THREAD

**Issue by widget31too** [AzureAD/microsoft-authentication-library-for-js#1759] opened 2020-06-05 22:44 UTC
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.
I'm seeing odd behavior with MSAL UserAgentApplication logout and login, and am trying to figure out how to resolve it.

My Angular 8 application has two methods for logout (explicit from button press, or idle timeout), which go through the same path in the code to UserAgentApplication.logout. No problem here.

After logout, I redirect back to a page that displays that the user is logged out, and on clicking a link we call UserAgentApplication.loginRedirect.

If the original session was logged in for 10 minutes or less before logging out, login redirects to the Azure AD B2C login page, requesting the user's password. This is what I expect.

If the original session was logged in for 15 minutes or more before logging out, login automatically reauthenticates **without** redirecting and requesting password.

After logout in both situations, I check session storage, and all the MSAL data values have been cleared. During the sessions, there were no calls to get the access token, other than the initial fetch. I checked network traffic, and as far as I can tell there were no additional requests to Azure AD B2C for any authentication or token refresh.

Has anyone seen this before, and/or have any ideas? Are there some configuration parameters on the Azure AD B2C tenant, application, or user flow that would cause this? Our app displays protected health information, so this could cause a HIPAA violation.

Please let me know if there is any additional information I can provide for this.

**Comment by bc3** [comment] 2020-06-08 07:16
we have sort a like issue, we logout, all session storage disappears, but when you hit login again msal automatically logs in without requesting username, password again ...

is there some info that is left behind on browser/os level ?

**Comment by jasonnutter** [comment] 2020-06-09 17:10
@widget31too What operating systems do you observe this on? And are they domain joined devices? Windows includes Seamless SSO, which can result in the behavior you describe.

https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso

**Comment by jasonnutter** [comment] 2020-06-17 00:55
@widget31too A couple things:

> The sign-out clears the user's single sign-on state with Azure AD B2C, but it might not sign the user out of their social identity provider session. If the user selects the same identity provider during a subsequent sign-in, they might reauthenticate without entering their credentials. If a user wants to sign out of the application, it doesn't necessarily mean they want to sign out of their Facebook account. However, if local accounts are used, the user's session ends properly.

You are using a social IDP, correct? As opposed to local accounts.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-overview#sign-out

> Web app session lifetime (minutes) - The lifetime of Azure AD B2C's session cookie stored on the user's browser upon successful authentication.
Default = 1440 minutes.
Minimum (inclusive) = 15 minutes.
Maximum (inclusive) = 1440 minutes.

This is where the 15 minute duration comes from.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior#session-behavior-properties

**Comment by technical-boy** [comment] 2020-08-10 17:57
Closing this issue since this is expected behavior. Please let us know if you have any further questions or concerns.

**Closed by technical-boy** 2020-08-10 17:57 UTC
Labels: b2c, b2c-service, no-issue-activity, question
