### ISSUE TITLE
InteractionType.Redirect issue : : interaction_in_progress 

### ISSUE THREAD

**Issue by ismail1971** [AzureAD/microsoft-authentication-library-for-js#2868] opened 2021-01-13 04:22 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.9.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ X] `@azure/msal-angular@2.0.0-alpha.3`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by ismail1971** [comment] 2021-01-13 04:34
When I am using InteractionType.Popup I have no issue but InteractionType.Redirect gives me BrowserAuthError: interaction_in_progress

Here is my code and config:
app.module.ts:
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(    config.resources.resourceUri, [config.resources..resourceScope]
  );
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect
    ,    authRequest: { prompt: 'select_account' },
  };
}

app.component.ts:


  ngOnInit() {
    this.isIframe = window !== window.parent && !window.opener;
    this.checkAccount();
  

    this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_SUCCESS ||
            msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS
        ),
        takeUntil(this._destroying$)
      )
      .subscribe((result) => {
        this.checkAccount();      
        if (result.eventType == EventType.LOGIN_SUCCESS) {      
          this.router.navigate(['home']);
        }
      });
  }

checkAccount() {
    this.loggedIn = this.authService.instance.getAllAccounts()?.length > 0;
    if (this.loggedIn) {
      this.userName = this.authService.instance
        .getAllAccounts()[0]
        .name?.split('-')[0];
    }
    
  }


  login() {
    if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
      if (this.msalGuardConfig.authRequest) {
        this.authService
          .loginPopup({ ...this.msalGuardConfig.authRequest } as PopupRequest)
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
            this.checkAccount();
          });
      } else {
        this.authService
          .loginPopup()
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
            this.checkAccount();
          });
      }
    } else {
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginRedirect({
          ...this.msalGuardConfig.authRequest        
        } as RedirectRequest);
      } else {
        this.authService.loginRedirect();
      }
    }
  }
  logout() {
    if (this.loggedIn && this.isValidTenant && this.isValidFaculty) {
      this.subsink.sink = this.dataService
        .clearRedisCache()
        .subscribe((data) => {
          localStorage.clear();
          this.authService.logout();
        });
    } else {
      this.authService.logout();
    }
  }

app-routing.module.ts:
const routes: Routes = [
  {
    path: 'home',
    loadChildren: () => import('./home/home.module').then((m) => m.HomeModule),
    canActivate: [MsalGuard, TenantGuard],
  },
  {
    path: 'resources',
    loadChildren: () => import('./resources/resources.module').then((m) => m.ResourcesModule),
    canActivate: [MsalGuard, TenantGuard],
  },
  {
    path: 'error',
    component: ErrorPageComponent,
  },
  {
    path: '',
    loadChildren: () => import('./welcome/welcome.module').then((m) => m.WelcomeModule),
  },
  { path: '**', component: PageNotfoundComponent },
];
const isIframe = window !== window.parent && !window.opener;
@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      enableTracing: false,
      useHash: false,
      initialNavigation: !isIframe ? 'enabled' : 'disabled',
    }),
  ],
  exports: [RouterModule],
})


Error message:
error = Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. at BrowserAuthError.AuthError [as constructor] (https://localhost:5021/vendor.js:145530:20) at new BrowserAuthError (https://localhost:5021/vendor.js:153233:24) at Function.BrowserAuthError.createInteractionInProgressError (https://localhost:5021/vendor.js:153313:12) at PublicClientApplication.ClientApplication.preflightInteractiveRequest (https://localhost:5021/vendor.js:157572:30) at PublicClientApplication.<anonymous> (https://localhost:5021/vendor.js:156762:33) at step (https://localhost:5021/vendor.js:144894:19) at Object.next (https://localhost:5021/vendor.js:144824:14) at https://localhost:5021/vendor.js:144796:67 at new ZoneAwarePromise (https://localhost:5021/polyfills.js:1139:23) at __awaiter (https://localhost:5021/vendor.js:144775:10) at resolvePromise (https://localhost:5021/polyfills.js:1044:23) at resolvePromise (https://localhost:5021/polyfills.js:987:11) at https://localhost:5021/polyfills.js:935:11 at step (https://localhost:5021/vendor.js:144793:21) at https://localhost:5021/vendor.js:144796:5 at new ZoneAwarePromise (https://localhost:5021/polyfills.js:1139:23) at __awaiter (https://localhost:5021/vendor.js:144775:10) at PublicClientApplication.loginRedirect (https://localhost:5021/vendor.js:157840:12) at MsalService.loginRedirect (https://localhost:5021/vendor.js:22467:78) at WelcomeComponent.push.J7Q4.WelcomeComponent.login (https://localhost:5021/welcome-welcome-module.js:99:34)

**Comment by jo-arroyo** [comment] 2021-01-13 19:55
@ismail1971 Can you provide the code for the `WelcomeComponent`, as that is where the error is originating?

**Comment by ismail1971** [comment] 2021-01-13 21:52
@jo-arroyo 
Here is the welcome.component.ts

import { Component, OnInit, OnDestroy, Inject } from '@angular/core';

import {
  MsalService,
  MSAL_GUARD_CONFIG,
  MsalGuardConfiguration,
} from '@azure/msal-angular';
import { Router } from '@angular/router';
import { SubSink } from 'subsink';
import {   InteractionType, PopupRequest, RedirectRequest } from '@azure/msal-browser';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css'],
})
export class WelcomeComponent implements OnInit, OnDestroy {
  loggedIn = false;
  subsink = new SubSink();
  isAlreadyLoggedIn = false;
  constructor(
    private authService: MsalService,   
    private router: Router,   
    @Inject(MSAL_GUARD_CONFIG) private msalGuardConfig: MsalGuardConfiguration
  ) {}

  ngOnInit(): void {    
       this.loggedIn = this.authService.instance.getAllAccounts().length > 0;
       if (this.loggedIn) this.router.navigate(['home']);
  }

  login() {
    if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginPopup({ ...this.msalGuardConfig.authRequest } as PopupRequest);
      } 
      else 
      { 
        this.authService.loginPopup(); 
      }
    } else {
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginRedirect({...this.msalGuardConfig.authRequest } as RedirectRequest);
      }
      else { 
        this.authService.loginRedirect();
      }
    }
  }
  ngOnDestroy() {
    this.subsink.unsubscribe();
    
  }
}

**Comment by jo-arroyo** [comment] 2021-01-14 19:49
@ismail1971 How is the login in the Welcome Component being triggered? Is the user clicking login?

**Comment by eluchsinger** [comment] 2021-01-15 11:01
I've got the same issue with MSAL Angular (v2).

**Comment by balcanusebi** [comment] 2021-01-15 11:23
Same issue here also ("@azure/msal-browser": "^2.9.0", "@azure/msal-angular": "^2.0.0-alpha.3",). Goes to Azure AD login, returns to login page with the message interaction_in_progress. The login process is triggered by the user clicking on a button.

**Comment by eluchsinger** [comment] 2021-01-15 15:20
I've tried the redirection with a call to the `authService.loginRedirect()` method and via browsing to a protected route. Both with the same result.

**Comment by ismail1971** [comment] 2021-01-15 16:10
> @ismail1971 How is the login in the Welcome Component being triggered? Is the user clicking login?
@jo-arroyo It's a login button click:
Here is the html:

<header class="hero-bg"
        id="home">
  <div class="aws-container hero-bg-shadow">
    
    <div class="aws-col l6">
      <div class="hero-content aws-center">
        <div class="hero-text aws-mobile aws-text-white">
          <h3 class="hero-welcome">Welcome to the</h3>
          <h3 class="hero-title"><strong>Faculty</strong> Portal</h3>
         
        </div>
        <div class="hero-actions">
          <button *ngIf="!loggedIn"
                  (click)="login()"
                  class="aws-button aws-yellow aws-large aws-round-xxlarge aws-card-8 aws-mobile"
                  style="padding:16px 120px;"><b>Sign in</b></button></div>
      </div>
    </div>
    
    <div class="aws-col l6">
      
    </div>
  </div>
</header>

**Comment by ismail1971** [comment] 2021-01-22 20:47
@jo-arroyo Any update on this issue?

**Comment by jo-arroyo** [comment] 2021-01-25 17:37
@ismail1971 The `interaction_in_progress` error occurs when a redirect call is already in progress, and has not been handled by `handleRedirectObservable` when another redirect call is made. 

We are currently working on updates to the library to make redirects easier to use. In the meantime, can you send me your `home.component` code and what steps you would take to reproduce this error?

**Comment by edwinn1990** [comment] 2021-01-28 00:06
Hi there 

Any fix for this issue 

Thanks

**Comment by eluchsinger** [comment] 2021-01-30 15:56
@jo-arroyo there is a similar problem with the Password Reset. [Apparently](https://github.com/MicrosoftDocs/azure-docs/issues/20128), one needs to handle the error code (AADB2C90118) returned to the app. I'm guessing, you would want to solve it in a similar way?

**Comment by jo-arroyo** [comment] 2021-02-02 17:39
@ismail1971 @edwinn1990 @balcanusebi @eluchsinger The latest versions of msal-browser and msal-angular were released last night, and contains new guidance on redirects to avoid the interaction_in_progress error. Please update using `npm install @azure/msal-browser@2.11.0 @azure/msal-angular@alpha` and give the new version a try.

@eluchsinger If you have additional problems with Password Reset after the update, please open up a new issue with the new versions so we can track it.

**Comment by vitaliidasaev** [comment] 2021-02-03 21:26
Here is the link to new documentation
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md

**Comment by eluchsinger** [comment] 2021-02-05 09:59
Hi @jo-arroyo the redirection now apparently logs you in, but if I go to a protected route, let's say `/admin`, I get redirected to the login screen. After logging in, I get briefly redirected to `/admin` (I only see it in the logs)  **and then back to** `/`.

If I enter `/admin` again, I don't get redirected to the login, because I'm already logged in.

Also, after the weird redirection back to `/`, the URL contains a `#state` with something that probably is the token.

I am not sure, if you prefer to track it in this issue - for me it's not resolved yet - or if you want to open a new one and track it there.

**Comment by jo-arroyo** [comment] 2021-02-05 16:57
@eluchsinger Could you open up a [new issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose)? A new issue with the new versions, your configurations and usage would help us identify where the problem is occurring, thanks.

**Comment by pkanher617** [comment] 2021-02-18 21:27
Is this issue still happening on the latest version of msal-angular?

**Comment by eluchsinger** [comment] 2021-02-21 12:33
@pkanher617 yes there are several new issues around this issue.

**Closed** 2021-03-16 00:31 UTC
Labels: no-issue-activity, question
