### ISSUE TITLE
Login using MSAL in Safari not able to process session from localStorage.

### ISSUE THREAD

**Issue by isaacwgarcia** [AzureAD/microsoft-authentication-library-for-js#5572] opened 2023-01-13 16:20 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

Unable to login from Safari Browser, works on Chrome and Brave

Doing some research found that regex ?<= not supported Safari iOS, we can use ?: 

Note: / or 1st reference letter that comes before in a non-captured group.

### Source Code 

https://github.com/isaacwgarcia/azure-aad-nlpeditor

### Error Message

Error: 

Invalid regular expression: invalid group specifier name  - CredentialEntity.ts  : 118

if (key.toLowerCase().search(`(?<=${separator}${domainRe})${separator}${credVal}${separator}`) !== -1) {
                return CredentialType[credKey];
            }

### Msal Logs

[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - Event callback registered with id: 2bbb9010-f425-4cea-9e21-f8204eda864b (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-react@1.5.2 : Verbose - MsalProvider - Registered event callback with id: 2bbb9010-f425-4cea-9e21-f8204eda864b (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeStart (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 2bbb9010-f425-4cea-9e21-f8204eda864b: msal:initializeStart (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeEnd (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 2bbb9010-f425-4cea-9e21-f8204eda864b: msal:initializeEnd (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:handleRedirectStart (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 2bbb9010-f425-4cea-9e21-f8204eda864b: msal:handleRedirectStart (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-react@1.5.2 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - initializeServerTelemetryManager called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - getRedirectResponseHash called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Hash contains known properties, returning response hash (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - validateAndExtractStateFromHash called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Returning state from hash (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - State extracted from hash (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Current page is loginRequestUrl, handling hash (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - handleHash called, retrieved cached request (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - getClientConfiguration called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - getDiscoveredAuthority called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Creating discovered authority with configured authority (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Attempting to get cloud discovery metadata in the config (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache. (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network. (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request. (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork() (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - Auth code client created (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : msal.js.browser@2.32.2 : Verbose - RedirectHandler.handleCodeResponse called (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:12 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : @azure/msal-common@9.0.2 : Info - in acquireToken call in auth-code client (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : [79743877-c09e-40ec-b657-7eea6da22cd3] : @azure/msal-common@9.0.2 : Verbose - Error in fetching token in ACC (main.b340b4c8.js, line 2)
[Info] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:loginFailure (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 2bbb9010-f425-4cea-9e21-f8204eda864b: msal:loginFailure (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-react@1.5.2 : Verbose - MsalProvider - Removing event callback 2bbb9010-f425-4cea-9e21-f8204eda864b (main.b340b4c8.js, line 2)
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-browser@2.32.2 : Verbose - Event callback 2bbb9010-f425-4cea-9e21-f8204eda864b removed. (main.b340b4c8.js, line 2)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	os (main.b340b4c8.js:2:459795)
	(anonymous function) (main.b340b4c8.js:2:466547)
	gi (main.b340b4c8.js:2:425813)
	cs (main.b340b4c8.js:2:461111)
	wl (main.b340b4c8.js:2:478482)
	wl
	(anonymous function) (main.b340b4c8.js:2:534725)
	_l (main.b340b4c8.js:2:475145)
	sl (main.b340b4c8.js:2:471276)
	sl
	(anonymous function) (main.b340b4c8.js:2:422554)
	(anonymous function) (main.b340b4c8.js:2:534725)
	Zo (main.b340b4c8.js:2:422500)
	$o (main.b340b4c8.js:2:422435)
	nl (main.b340b4c8.js:2:467859)
	ba (main.b340b4c8.js:2:439650)
	ba
	(anonymous function) (main.b340b4c8.js:2:2828753)
	(anonymous function) (main.b340b4c8.js:2:2941243)
	forEach
	(anonymous function) (main.b340b4c8.js:2:2941163)
	(anonymous function) (main.b340b4c8.js:2:3096108)
	promiseReactionJob
[Debug] [Fri, 13 Jan 2023 16:08:13 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called (main.b340b4c8.js, line 2)

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: process.env.REACT_APP_CLIENT_ID,
    authority: process.env.REACT_APP_AUTHORITY,
    redirectUri: process.env.REACT_APP_REDIRECT_URL, //SetRedirect URIs SPA Azure AD Registration
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      logLevel: LogLevel.Verbose,
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
<Provider store={store}>
      <Header aria-label="Elyra Open Source">
        <HeaderName href="#" prefix="Elyra">
          Visual Editor for NLP rules
        </HeaderName>
        {isAuthenticated ? (
          <HeaderGlobalBar>
            <HeaderMenuItem style={{ display: 'inline' }}>
              <User16 />
            </HeaderMenuItem>
            <HeaderMenuItem style={{ display: 'inline', cursor: 'pointer' }}>
              <SignOut />
            </HeaderMenuItem>
          </HeaderGlobalBar>
        ) : (
          <HeaderGlobalBar>
            <HeaderMenuItem style={{ display: 'inline', cursor: 'pointer' }}>
              <SignIn />
            </HeaderMenuItem>
          </HeaderGlobalBar>
        )}
      </Header>

      {isAuthenticated ? <VisualEditor /> : <>NOT SIGNED IN</>}
    </Provider>
```

### Reproduction Steps

1. Click Sign In Button 
2. Authenticate
3. Error is logged in console

### Expected Behavior

1. Click Sign In Button 
2. Authenticate
3. Login success event should occur

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by Weschk** [comment] 2023-01-13 19:45
@isaacwgarcia looks like the same issue as in [5561](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5561)

The workaround is to override the msal-common package to use version 9.0.1 as described [here ](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5548#issuecomment-1378328047) until a fix has been release

**Comment by tickoosunny** [comment] 2023-01-17 12:07
@Weschk  have already done the change of downgrading to 9.0.1 , but it still persists.
tried with node version 18.0.0 and 18.12.1
my overrides &  dependencies sections look like below:

```
"dependencies": {
    "@azure/msal-browser": "^2.32.1",
    "@azure/msal-react": "^1.5.1",
},
"overrides": {
    "@azure/msal-browser": {
      "@azure/msal-common": "9.0.1"
    }
  }
```
If we do above changes then we get error  [5579](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5579)

**Comment by sandrooco** [comment] 2023-01-17 13:33
Try to revert to the last working versions (you probably don't need the latest version in most cases). Make sure you don't use carets (see https://stackoverflow.com/a/22345808/5243272). Then when a fix is released, you can update to latest.

```
"dependencies": {
    "@azure/msal-browser": "2.32.1",
    "@azure/msal-react": "^1.5.1"
},
```
(no overrides!)

**Comment by hectormmg** [comment] 2023-01-17 19:21
@isaacwgarcia this is a duplicate of #5561. Please downgrade until the fix is released!

**Closed as completed by hectormmg** 2023-01-17 19:21 UTC
Labels: question, msal-browser, msal-react, bug-unconfirmed, public-client
