### ISSUE TITLE
No cached authority found when clicking Back button from browser in Forgot Password screen

### ISSUE THREAD

**Issue by BiancaDianaAlexiuc** [AzureAD/microsoft-authentication-library-for-js#3036] opened 2021-02-17 15:41 UTC
## Library

- [ ] `@azure/msal-angular": "^2.0.0-alpha.5`
- [ ] `@azure/msal-browser": "^2.11.1`

## Framework

- [ ] Angular: 10.2.4

## Error Message
BrowserAuthError: no_cached_authority_error: No cached authority found.

## MSAL Configuration

```js
export const b2cPolicies: B2CPolicies = {
  names: {
    signUpSignIn: environment.B2C.SIGN_IN_POLICY_NAME,
    forgotPassword: environment.B2C.RESET_PASSWORD_POLICY_NAME,
  },
  authorities: {
    signUpSignIn: {
      authority: environment.B2C.SIGN_IN_AUTHORITY,
    },
    forgotPassword: {
      authority: environment.B2C.RESET_PASSWORD_AUTHORITY,
    },
  },
  authorityDomain: environment.B2C.AUTHORITY_DOMAIN,
};

export const apiScope: string = environment.B2C.SCOPE;

export const apiConfig: B2CApiConfig[] = Object.values(environment.API_URLS).map((uri: string) => ({
  scopes: [apiScope],
  uri: `${uri}/**`,
}));

```

## Reproduction steps

1.  Go to http://localhost:4200/  (will run signup-sign in policy and display login page)
2. Click on Forgot Password link (will run password-reset policy)
3. Click the back button from the browser (This should display the login page but returns an error)
```js
 subscribeToSuccessResetPassword(): void {
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_SUCCESS || msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS
        ),
        takeUntil(this.destroy)
      )
      .subscribe((result: EventMessage) => {
        console.log('subscribeToSuccessResetPassword');
        const payload: IdTokenClaims = result.payload as AuthenticationResult;
        const isSuccessResetPassword: boolean =
          payload.idTokenClaims?.tfp === authConfig.b2cPolicies.names.forgotPassword;

        localStorage.setItem(CommonConstants.AUTH_TOKEN, payload.idToken);

        if (isSuccessResetPassword) {
          return this.authService.logout();
        }

        this.checkAccount();

        return result;
      });
  }

  subscribeToLoginFailure(): void {
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_FAILURE || msg.eventType === EventType.ACQUIRE_TOKEN_FAILURE
        ),
        takeUntil(this.destroy)
      )
      .subscribe((result: EventMessage) => {
        console.log('subscribeToLoginFailure');

        if (result.error instanceof AuthError) {
          this.loggerService.logMessage(result.error.message, CommonConstants.logType.ERROR);

          const isForgotPasswordFlow: boolean = result.error.message.includes('AADB2C90118');

          if (isForgotPasswordFlow) {
            const resetPasswordFlowRequest: RedirectRequest | PopupRequest = {
              scopes: ['openid'],
              authority: authConfig.b2cPolicies.authorities.forgotPassword.authority,
            };

            this.login(resetPasswordFlowRequest);

            return;
          }

          const isForgotPasswordFlowCancelled: boolean = result.error.message.includes('AADB2C90091');

          if (isForgotPasswordFlowCancelled) {
            this.login();
          }
        }
      });
  }

// We use msalGuard and msalInterceptor and login is made by one of them. Here is the code: 
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap: Map<string, Array<string>> = new Map<string, Array<string>>();

  apiConfig.forEach((config: B2CApiConfig) => {
    protectedResourceMap.set(config.uri, config.scopes);
  });

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [apiScope],
    },
  };
}
```

I also tried this example https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample and it seems that the same bug with **BrowserAuthError: no_cached_authority_error: No cached authority found.** can be reproduced ..It's an unsystematic bug. It doesn't occur every time. 
Steps to reproduce: 
1. Go to forgot password 
2. Go back by pressing the back button from the browser 
3. Click on forgot password again  (The error reproduces) 

## Expected behavior
Should return to login page
## Identity Provider

- [ ] Azure B2C Custom Policy

## Browsers/Environment

- [ ] Chrome

## Regression

- [ ] Did this behavior work before?
No

## Security

- [ ] Is this issue security related?
- [ ] No

## Source

- [ ] Customer request

**Comment by pkanher617** [comment] 2021-02-17 20:16
@BiancaDianaAlexiuc Thanks for opening this issue! We were able to reproduce this behavior. This is definitely a bug. What appears to be happening is the forgot password flow seems to skip the client app when hitting the back button, which ends up putting the application in a bad state where it can't read the appropriate items from the cache. Let me investigate with the B2C team and get back to you on how we can mitigate this.

**Comment by sergiupop** [comment] 2021-02-23 07:57
Hello :) Any updates on this issue?

**Comment by pkanher617** [comment] 2021-02-26 23:42
Still working on trying to find a fix for this issue. Thanks for your patience.

**Comment by tnorling** [comment] 2021-03-22 20:33
Looks like this is due to a "feature" in Chrome. [See here](https://groups.google.com/a/chromium.org/g/blink-dev/c/T8d4_BRb2xQ/m/WSdOiOFcBAAJ). Essentially what's happening is that because you are redirected from signin policy to your app and then to the forgot password policy without any user interaction, Chrome is then skipping the app in the history when you hit the back button, sending you directly back to the signin policy. We're not quite sure how we can work around this in the library as switching policies outside the context of msal is unsupported and is expected to break the auth flow.

As of right now there are 2 mitigations: 

1. Enable the brand new "self service password reset" feature on your signin policy so you don't need to catch the error and redirect to a separate policy. This is documented [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended)
2. Force the user to click somewhere on the page before redirecting to the forgotPassword policy

**Closed** 2021-04-13 00:14 UTC
Labels: b2c, msal-angular, no-issue-activity, question
