### ISSUE TITLE
possible Incorrect cached token returned

### ISSUE THREAD

**Issue by kberawala** [AzureAD/microsoft-authentication-library-for-js#3362] opened 2021-03-31 05:26 UTC
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [-] `@azure/msal-browser@2.x.x`, "@azure/msal-browser": "^2.13.0",
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [] Other - Vue.js

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
e.g. There are 2 scopes=> scope1 and scope2, after first login access tokens are issued and valid for one hour.
after the token for "scope2" expires, by calling acquireTokenSilent() returns the access token of scope1 instead it should generate new token and issue the token for scope2.

```
async getSilentTokenForscope2 () {
    let accessToken = "";
    let currentAccount = await this.getUser();
    let tokenRequest = {
      scopes: [`${scope2}`],
      account: currentAccount,
      forceRefresh: false
    };  
    try {
      const tokenResponse = await this.app.acquireTokenSilent(tokenRequest);      
      accessToken = tokenResponse.accessToken;
    } catch (error) {
      tokenRequest = {
        scopes: [`${scope2}`],
        account: currentAccount,
        forceRefresh: true,
        loginHint: currentAccount.username
      };  

      try {
        const tokenResponse = await this.app.acquireTokenPopup(tokenRequest);
        accessToken = tokenResponse.accessToken;
      } catch (errorPopup) {
        return undefined;
      }
    }
    return accessToken;
  }
```

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
new access token should be generated, however returns the incorrect token.

## Identity Provider

- [ ] Azure AD
- [] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [] Is this issue security related? YES

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment] 2021-03-31 16:42
Closing as duplicate of #3363. This is a bug introduced by the service late last week, we're working with them to revert or patch the changes ASAP. In the meantime you can set `forceRefresh` to true to go to the network each time for a new token. Please track resolution in the other issue. Thanks!

**Closed by tnorling** 2021-03-31 16:42 UTC
Labels: bug-unconfirmed, more-information-needed, question
