### ISSUE TITLE
Unwanted side effect by case sensitive check of tokentype Bearer

### ISSUE THREAD

**Issue by beutlingsteven** [AzureAD/microsoft-authentication-library-for-js#4317] opened 2021-12-09 15:35 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

Hi,

I'm a software developer for a big company in Belgium and I'm currently upgrading an Angular application from ADAL To MSAL v2.

I configured everything correctly and everything appeared to be working but I found out for each API call, the msal httpInterceptor requested a new accessToken from ADFS. After much debugging in the msal code I found out what caused this side effect.

In the msal-common.cache.entities.AccessTokenEntity file, function createAccessTokenEntity there is following condition to define the credential type:
 if (atEntity.tokenType !== AuthenticationScheme.BEARER) {
            atEntity.credentialType = CredentialType.ACCESS_TOKEN_WITH_AUTH_SCHEME;
...

AuthenticationScheme.BEARER is an (string) Enum which has value 'Bearer'.

From ADFS we get tokenType="bearer" (without the capital letter) and because of this, a major side effect is triggered.

Because this case sensitive check, the credentialType will be ACCESS_TOKEN_WITH_AUTH_SCHEME and the cached token will not be found. Because of this, msal cannot find the cached token because he is looking for a token with credentialType="ACCESS_TOKEN" and will ask a new token for each call.

I ask you to consider to make this check case insensitive because according to the internet, many people experience the same problem. 

### MSAL Configuration

```javascript
MsalModule.forRoot( new PublicClientApplication({
      auth: {
        clientId: msalConfig.clientId, // This is your client ID
        authority: msalConfig.authority, // This is your tenant ID
        redirectUri: msalConfig.redirectUri,// This is your redirect URI
        knownAuthorities: msalConfig.knownAuthorities,
        postLogoutRedirectUri: msalConfig.redirectUrin,
      },     
      cache: {
        cacheLocation: msalConfig.cacheLocation,
        storeAuthStateInCookie: isIE// Set to true for Internet Explorer 11
      }
    }), {
      interactionType: InteractionType.Redirect, // MSAL Guard Configuration
      authRequest: {
        scopes: msalConfig.scopes
      }      
  }, {
    interactionType: InteractionType.Redirect, // MSAL Interceptor Configuration
    protectedResourceMap: new Map(msalConfig.protectedResourceMap),
    authRequest: {
      authenticationScheme: AuthenticationScheme.BEARER,

    }

  })
```

### Relevant Code Snippets

```javascript
atEntity.tokenType = StringUtils.isEmpty(tokenType) ? AuthenticationScheme.BEARER : tokenType;
        // Create Access Token With Auth Scheme instead of regular access token
        if (atEntity.tokenType !== AuthenticationScheme.BEARER) {
            atEntity.credentialType = CredentialType.ACCESS_TOKEN_WITH_AUTH_SCHEME;
            switch (atEntity.tokenType) {
                case AuthenticationScheme.POP:
                    // Make sure keyId is present and add it to credential
                    var tokenClaims = AuthToken.extractTokenClaims(accessToken, cryptoUtils);
                    if (!((_a = tokenClaims === null || tokenClaims === void 0 ? void 0 : tokenClaims.cnf) === null || _a === void 0 ? void 0 : _a.kid)) {
                        throw ClientAuthError.createTokenClaimsRequiredError();
                    }
                    atEntity.keyId = tokenClaims.cnf.kid;
                    break;
                case AuthenticationScheme.SSH:
                    atEntity.keyId = keyId;
            }
        }
        return atEntity;
```

### Reproduction Steps

1. Ask token
2. Get token from ADFS (with token_type: 'bearer' instead of 'Bearer')
3. Credential type is registered as ACCESS_TOKEN_WITH_AUTH_SCHEME because of case sensitive check

### Expected Behavior

MSAL should accept tokenType in any case (with or without capitals)

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment] 2021-12-09 16:54
Closing as duplicate of #4252

**Closed as completed by jasonnutter** 2021-12-09 16:54 UTC
Labels: question, msal-angular, msal-browser, adfs, bug-unconfirmed
