### ISSUE TITLE
How to access DevOps API with MSAL ?

### ISSUE THREAD

**Issue by byunru** [AzureAD/microsoft-authentication-library-for-js#4009] opened 2021-08-28 06:44 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

"@azure/msal-angular": "^2.0.2"

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

"@azure/msal-angular": "^2.0.2"

### Description

How to config MSAL to access Devops API

My angular library reference:
    "@azure/msal-angular": "^2.0.2",
    "@azure/msal-browser": "^2.16.1",

The app can call Azure rest API & Graph API with no problem, but can't call DevOps API

### Relevant Code Snippets

```javascript
1) App registration: in [API permissions], added Azure Devops user_impersonation as Delegated type

2) in https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md
protectedResourceMap.set("https://app.vsaex.visualstudio.com", "https://app.vsaex.visualstudio.com/user_impersonation")
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment] 2021-08-28 13:46
@byunru Have you reached out to the DevOps team for the list of relevant scopes to be enabled?

**Comment by byunru** [comment] 2021-08-28 17:40
@sameerag 
Since "https://management.azure.com/user_impersonation" is the global scope for All azure resource API, so I assume that "https://app.vsaex.visualstudio.com/user_impersonation" is the global scope for DevOps API

I tried with this format
    endpoint: "https://dev.azure.com/msaltestingjs/_apis/projects?api-version=4.0",
    scopes: ["499b84ac-1321-427f-aa17-267ca6975798/.default"] 
from https://github.com/microsoft/azure-devops-auth-samples/blob/master/JavascriptWebAppSample/config.js
give me different error: "CORS header “Access-Control-Allow-Origin” missing)"
I think "config.js" file is outdated.

Tried different combination of above, no luck.

**Comment by byunru** [comment] 2021-08-31 17:14
According to https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops
"MSAL is the best authentication mechanism to use with our REST APIs."

I hope can get advise or tips from you soon @jasonnutter

**Comment by jasonnutter** [comment] 2021-09-01 23:36
@byunru Apologies for the delayed response. @derisen Can you help with the devops sample linked above?

**Comment by derisen** [comment] 2021-09-02 16:59
@byunru you need to make sure to [connect your AAD tenant to your Azure DevOps account](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=azure-devops&tabs=preview-page&viewFallbackFrom=vsts), and then modify the `config.js` like:

```javascript
const apiConfig = {
    // e.g. https://dev.azure.com/{organization}/_apis[/{area}]/{resource}?api-version={version}
    endpoint: "https://dev.azure.com/<YOUR_TENANT_NAME>/_apis/projects?api-version=4.0",
    scopes: ["499b84ac-1321-427f-aa17-267ca6975798/.default"] // this is the app Id of devOps service
};
```

Can you give this a try and let me know? Steps should have been much clearer, apologies. Making a PR to fix that.

**Comment by byunru** [comment] 2021-09-02 23:12
I got error as below when use the above config (my aad account is the admin of adoz portal)
=========================== error msg =======================================
[Thu, 02 Sep 2021 22:58:37 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:acquireTokenSuccess 2 app.module.ts:27:10
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dev.azure.com/byunru/_apis/projects?api-version=6.0. (Reason: CORS header “Access-Control-Allow-Origin” missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dev.azure.com/byunru/_apis/projects?api-version=6.0. (Reason: CORS request did not succeed).

**Comment by derisen** [comment] 2021-09-03 15:01
CORS issues are beyond the scope of MSAL. Basically the API you are calling needs to allow CORS for your client app. 

Regardless, DevOps API [supports CORS](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/cross-origin-resource-sharing?view=azure-devops). Are you sure you're making a simple GET request? Can you share a code snippet or network trace?

**Comment by byunru** [comment] 2021-09-04 06:03
@derisen  can you provide email? I can zip the code to you.

My app is pure angular + MSAL, no server-side code., it based on https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular12-sample-app
I added very little code.  

In app I call Graph api & Azure resource api with no issue. only have issue when I call DevOps api, so no idea where the CORS issue come from.

**Comment by derisen** [comment] 2021-09-05 03:31
@byunru you can find my email on my GitHub profile, though I would recommend creating a GitHub repo instead

**Comment by byunru** [comment] 2021-09-07 16:37
@derisen   I've sent the code, hope I provided enough information so that easy for you to reproduce the issue on your side.

**Comment by derisen** [comment] 2021-09-07 18:37
@byunru this went to the spam folder apparently, sorry. Checking and will get back to you.

**Comment by derisen** [comment] 2021-09-08 00:32
@byunru I couldn't reproduce your issue. The request was successful for these coordinates:

`this.resourceMap.set("https://dev.azure.com/MY_TENANT/_apis/projects?api-version=4.0", ["499b84ac-1321-427f-aa17-267ca6975798/.default"]);`

![ss](https://user-images.githubusercontent.com/13197548/132426850-c658b5c0-2445-4a2b-afba-78e9c686c3ce.png)

I only tested this on localhost. Are you having this issue when your app is deployed? Are you getting different results on localhost vs hosted?

**Comment by byunru** [comment] 2021-09-08 04:47
@derisen   thanks trying out for me,
It is very very old, I tested localhost and deploy to storage account (static site), having the same error while retrieving azure resource with no issue, I tested with chrome, edge, Firefox. 
Do you mind arrange a remote screen-sharing troubleshooting this ? I can create a service ticket from my company portal if you need.

**Comment by derisen** [comment] 2021-09-08 17:44
Interesting.. ok let's setup some for this. I've added you on Teams.

**Comment by derisen** [comment] 2021-09-08 19:23
This was resolved offline. For reference, the issue was to [connect the DevOps organization to Azure AD tenant](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/connect-organization-to-azure-ad?view=azure-devops). Closing.

**Closed by derisen** 2021-09-08 19:23 UTC
Labels: question, msal-angular, msal-browser, answered, Needs: Author Feedback
