### ISSUE TITLE
URI malformed error when current page HASH contains %25 in it

### ISSUE THREAD

**Issue by av-virlan** [AzureAD/microsoft-authentication-library-for-js#3879] opened 2021-07-19 09:41 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.10.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

If you configure MSAL on a page that uses hash for storing state and the hash contains %25 in it, when you call

client.acquireTokenSilent(..) it crashes

This seems to be similar to - https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2125

The issue is that StringUtils.queryStringToObject double decodes the window.location.hash so 
http://contoso.com/page.html#value=some%25value
has the hash decoded to 
some%value
And then it tries to decode it again and crashes because decodeURIComponent thinks it has to decode %value to something and can't

Cannot work around this because the state has to be single encoded for the main application to work so I can't double encoded just to MSAL doesn't crash

### Error Message

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at o (msal.js?v=5.3.0.0-c17174:725)
    at Function.e.queryStringToObject (msal.js?v=5.3.0.0-c17174:728)
    at Function.e.getDeserializedHash (msal.js?v=5.3.0.0-c17174:1846)
    at Function.e.hashContainsKnownProperties (msal.js?v=5.3.0.0-c17174:1851)
    at Function.t.blockReloadInHiddenIframes (msal.js?v=5.3.0.0-c17174:3977)
    at a.t.preflightBrowserEnvironmentCheck (msal.js?v=5.3.0.0-c17174:4625)

### MSAL Configuration

```javascript
{
   "auth":{
      "clientId":"x3exxe0x-a2c3-xxxx-xxxx-8xxx17xc7xxx",
      "authority":"https://login.microsoftonline.com/...",
      "knownAuthorities":[
         "https://login.microsoftonline.com/..."
      ],
      "protocolMode":"AAD",
      "redirectUri":"http://contoso.com/Login.aspx"
   },
   "cache":{
      "cacheLocation":"localStorage",
      "storeAuthStateInCookie":false
   },
   "scopes":[
      "api://...../my_scope"
   ]
}
```

### Relevant Code Snippets

```javascript
client.acquireTokenSilent({ scopes: ["openid", "profile"], account: "..." }).then(function (resp) { }).catch(function (error) { /* it crashes here */ debugger; })
```

### Reproduction Steps

Have an HTMl page and set a HASH state via JS that contains an encoded value with percentage in it - like:
index.html#key=some%25value

Create your MSAL client and call acquireTokenSilently

The promise for acquireTokenSilently crashes with URI malformed error

### Expected Behavior

StringUtils only decodes once or checks before re-decoding so that you don't crash the acquireTokenSilent promise. Or don't decode the HASH at all if not needed - because there is no MSAL state in that window.location.hash so why try to decode it? 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by hectormmg** [comment] 2021-07-19 19:35
Hi @av-virlan! Thanks for raising this issue. We're currently looking into issue #3491 that looks similar to yours, so we'll update this issue when we confirm whether or not it has the same root cause.

I understand not wanting to keep the state double decoded for the main application's use, but is there a reason why you can't encode the state value you pass to `acquireTokenSilent` and then decode the state value that is returned before using it in the main application?

Thanks!

**Comment by av-virlan** [comment] 2021-07-20 07:39
I can give that a shot - so something like this:

**Before:**
client.acquireTokenSilent({ ... }).then(function (resp) { }).catch(function (error){});

**After:**
client.acquireTokenSilent({ ..., _**state: encodeURIComponent(window.location.hash.substring(1))**_ }).then(function (resp) { }).catch(function (error){});

**Comment by av-virlan** [comment] 2021-07-20 07:50
I'm back - I just tested the above and it doesn't change anything. If you look at the stacktrace the issue starts from **preflightBrowserEnvironmentCheck** method which calls **blockReloadInHiddenIframes** which is hardcoded to use window.location.hash instead of the state I pass in the request.

So the issue is not with acquiring itsel but with the pre-validation which is hardcoded to use window.location.hash (at least in MSAL 2.10.0)

**Comment by hectormmg** [comment] 2021-07-20 17:46
@av-virlan I'm able to reproduce the issue, I'll do some more investigating to determine the best fix/workaround and will update this issue when I have more information, thanks!

**Comment by jasonnutter** [comment] 2021-08-02 21:03
@hectormmg @bmahall This got fixed by #3903, correct?

**Comment by hectormmg** [comment] 2021-08-02 21:24
Yes, this was fixed in #3903.

**Closed by hectormmg** 2021-08-02 21:24 UTC
Labels: bug, msal-browser

**Comment by av-virlan** [comment] 2021-08-05 14:41
@hectormmg @jasonnutter any idea on when an updated msal-browser build will be released with a fix for this?

**Comment by jasonnutter** [comment] 2021-08-05 16:03
@av-virlan Latest version of msal-browser should contain this fix.

**Comment by av-virlan** [comment] 2021-08-05 17:05
@jasonnutter thanks I see it's published on NPM. I was looking for it in Github Releases and was only seeing 2.16.0, didn't think to check NPM directly 👍
