### ISSUE TITLE
For 'User assignment required' prevent redirect and LOGIN_FAILURE event

### ISSUE THREAD

**Issue by rosspi** [AzureAD/microsoft-authentication-library-for-js#3949] opened 2021-08-10 00:45 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Description

Hello, I'm hoping somebody knows what my problem is here with MSAL or AAD.
I have an angular app that is referencing an application in AAD for which I have turned on 'User assignment required', and I have also selected a particular AD Group as an assigned user/group.
When I then run the angluar app and sign in as an acceptable user, everything flows and works fine.
However if I sign in as an unassigned/unaccepted user, I would expect that the Microsoft sign in screen would error and report that the user I'm attempting to sign in as is not assigned to the application. But what actually happens is that it redirects back to my `redirectUri` and then a `LOGIN_FAILURE` event is handleable from the MsalBroadcastService back within angular after the redirect. But I want it to stay on the Microsoft side and _not_ redirect back to my application.

The weird thing is, is that I noticed that if I set the redirect url in the js to a url that is different to what is registered as the redirect url in the AAD application, then the behaviour changes to what I would expect anyway -  I then get this error screen:
![image](https://user-images.githubusercontent.com/5019079/128789016-b35a7511-d2e4-4dd9-a17e-0c304550fd19.png)
I do not know why it behaves like that with a misconfigured redirecturl, but with it misconfigured I cannot login with a valid user of course (it will then error about the url being wrong).
Is there a way to correctly configure it so that it will not redirect back to my application when a user who is not assigned to the application in AAD attempts to login? I do not want to have to manually handle that in JS via the LOGIN_FAILURE event. I want it to show the above error screen (or something like it).

Thanks.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by pkanher617** [comment] 2021-08-11 01:10
@rosspi Could you provide a code snippet of how you are invoking authentication? You can add placeholders for any GUIDs and URIs.

Could you also provide any additional error information about the LOGIN_FAILURE event? Is there any additional messaging that is provided stating the cause of the failure?

**Comment by rosspi** [comment] 2021-08-11 01:41
The LOGIN_FAILURE js event is a valid kind of failure in the sense that it reports that the user I am trying to login with is not assigned to the app in AAD, and therefore should not have access.
But what I want to happen is for the login process on the Microsoft side to _not_ redirect back to my site when a user who is not assigned to that application attempts to login.
What is happening currently is that it is redirecting back to (which I don't want to happen):

`http://localhost:4200/redirect#error=interaction_required&error_description=AADSTS50105%3a+The+signed+in+user+%27%7bEmailHidden%7d%27+is+not+assigned+to+a+role+for+the+application+%000000-00000000%27(Name+Here).%0d%0aTrace+ID%3000002%0d%0aCorrelation+ID%3a+251c00000000000008ae%0d%0aTimestamp%3a+2020000Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50105&state=eyJp.......X0%3d`

Notice how the error_description qs is the same as the message in the screenshot from my original issue posting?
Incidentally, the eventual raised JS event also contains the same error:
![image](https://user-images.githubusercontent.com/5019079/128956599-e9688d22-44a9-4f51-9892-0614dcce1b31.png)

Some of my config code:
```
export const msalConfig: Configuration = {
     auth: {
         clientId: environment.aadClientId, 
         authority: `https://login.microsoftonline.com/${environment.aadTenantId}`, 
         redirectUri: environment.aadRedirectUri,  
         postLogoutRedirectUri: '/',  
         navigateToLoginRequestUrl: true, 
     },
     cache: {
         cacheLocation: BrowserCacheLocation.LocalStorage,  
         storeAuthStateInCookie: isIE,  
     },
     system: {
         loggerOptions: {
             loggerCallback(logLevel: LogLevel, message: string) {
                 console.log(message);
             },
             logLevel: LogLevel.Verbose,
             piiLoggingEnabled: false
         }
     }
 } 

 export const silentRequest = {
     scopes: [environment.aadScope] 
 };
```
And my app,module.st file's providers:
```
{
  provide: MSAL_INSTANCE,
  useFactory: () => new PublicClientApplication(msalConfig)
},
{
  provide: MSAL_GUARD_CONFIG,
  useFactory: () => {
    return { 
      interactionType: InteractionType.Redirect,
      authRequest: silentRequest
    } as MsalGuardConfiguration;
  }
},
MsalService,
MsalGuard,
MsalBroadcastService
```

**Comment by pkanher617** [comment] 2021-08-12 16:32
Sorry, I'm a bit unclear on the flow of how this is happening. Could you provide some more detailed repro steps? When you are signing in users, what API calls are you making? It sounds like you are making a redirect request? Generally if there is an error during a redirect on the login.microsoftonline.com page, it will display the error without navigating back to the application. `interaction_required` errors are generally thrown during silent requests where `prompt=none`, where the redirect back to the application is required since no prompt is being shown, and can be resolved by calling `acquireTokenRedirect` or `acquireTokenPopup`.

**Comment by kleky** [comment] 2021-08-23 11:16
Hi, I'm having this same issue. I'm getting the error screen `Sorry, but we’re having trouble with signing you in.`, but I don't want this; I want to be re-directed back to the app and handle this in the app, allowing the user to sign out of the invalid account.

Here's my setup:

```
#export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.authClientId,
      authority: 'https://login.microsoftonline.com/' + environment.authAuthorityId,
      redirectUri: '/',
      navigateToLoginRequestUrl: false,
      postLogoutRedirectUri: '/logged-out'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      allowRedirectInIframe: true,
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Error,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);
  protectedResourceMap.set(environment.api, [environment.apiPermissionScope]);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: []
    },
    loginFailedRoute: '/login-failed'
  };
}
```

I'm using Authorization Code Flow with PKCE and have a SPA redirect URI in there for `http://localhost:4200`

The route is protected with the `MsalGuard`, and navigating to this route in locahost having been signed in as an unauthorised user via Azure Portal causes the miscrosft signin error page.

Would really appreciate some help on this.

Many thanks

Ian

**Comment by rosspi** [comment] 2021-08-24 04:31
@kleky You're actually having the opposite problem to me.
The behaviour I _was_ experiencing is the one that you want.
However, I have noticed recently (past week), that the login flow behaviour has changed to align with what I was expecting - I assume something changed on the Microsoft end.

**Comment by kleky** [comment] 2021-08-24 15:11
Hi @rosspi , yes that's correct, I want the behaviour you didn't want.

**Comment by christeredvartsen** [comment] 2021-09-02 09:58
We are experiencing a similar issue, but we are not using the JS-library.

Our issue is that whenever the `AADSTS50105: The signed in user 'Christer.Edvartsen@nav.no' is not assigned to a role for the application '6e45010d-2637-4a40-b91d-d4cbb451fb57'(naisdevice-apiserver).` error occurs for our users, the client is no longer sent to the `redirect_uri` for the application (specified as a query param). Instead the users only see the error page saying that the signed in user is not assigned to a role for the application.

We started seeing this behaviour about a month ago. Before this started happening the same error resulted in the client being redirected to the `redirect_uri` so that our application could handle the error accordingly. We have not changed the redirect URI, and the configuration for the app registration in Azure AD is also unchanged.

As an interesting note, if we provide `prompt=none` in the initial request, the client is sent to the `redirect_uri` when encountering this error.

**Comment by kleky** [comment] 2021-09-08 07:47
I've since worked around this with a less than ideal solution, but I'd at
least like to know what's going on.

**Comment by pkanher617** [comment] 2021-09-20 16:12
Sorry for the delay on this issue, but it sounds like the original issue was resolved, so I will be closing this.

> Hi, I'm having this same issue. I'm getting the error screen Sorry, but we’re having trouble with signing you in., but I don't want this; I want to be re-directed back to the app and handle this in the app, allowing the user to sign out of the invalid account

@kleky the issue you describe above is a bit confusing, since you want the user to sign out, but the user hasn't been able to sign in anyway. So are you seeing this after the account has already acquired tokens? Or before any tokens have been returned for the account that wasn't signed in correctly.

**Comment by kleky** [comment] 2021-09-20 16:43
> Sorry for the delay on this issue, but it sounds like the original issue was resolved, so I will be closing this.
> 
> > Hi, I'm having this same issue. I'm getting the error screen Sorry, but we’re having trouble with signing you in., but I don't want this; I want to be re-directed back to the app and handle this in the app, allowing the user to sign out of the invalid account
> 
> @kleky the issue you describe above is a bit confusing, since you want the user to sign out, but the user hasn't been able to sign in anyway. So are you seeing this after the account has already acquired tokens? Or before any tokens have been returned for the account that wasn't signed in correctly.

Hi. The latter. User is signed in under a different account in the same tenant, from somewhere like Azure DevOps, but this use account is unauthorized for the app by not being assigned to the appropriate role. User wants to use a different account from that tenant but they're unable to sign into it due to this error.

**Comment by BriHav** [comment] 2021-09-24 10:34
@kleky sounds like your issue can be solved by providing the prompt: 'select_account' parameter, which will prompt the user to select which account to use whenever they login.

@christeredvartsen I have a similar issue, I have an application where I would like to handle the error AADSTS50105, however from around the middle of August, this error is no longer being redirected back to the application. If I set the prompt parameter to none, the user will run into an infinite loop when they are not logged in, the login screen is not shown.

**Comment by christeredvartsen** [comment] 2021-09-24 10:42
> If I set the prompt parameter to none, the user will run into an infinite loop when they are not logged in, the login screen is not shown.

Yes, and because of this using this flag is a no-go for our use case.

**Comment by christeredvartsen** [comment] 2021-09-29 14:26
I'd like to get a proper explanation at least. Not sure if this comment will remove the stale status of the issue though...

**Closed** 2021-11-03 01:01 UTC
Labels: question, msal-angular, msal-browser, no-issue-activity, answered, Needs: Author Feedback
