### ISSUE TITLE
Multiple Open ID Redirects happening while Using MSAL version 1.3.2 with Azure AD B2C Session from target=_blank

### ISSUE THREAD

**Issue by muraliyv2020** [AzureAD/microsoft-authentication-library-for-js#1783] opened 2020-06-15 17:11 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.2` or `@azure/msal@1.x.x`
- [x] `@azure/msal-angular@1.0.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular version : 7.2.0
Azure AD B2C 
MSAL - 1.3.2

## Description
When the User is logging from the Azure B2C SSO the following observations were identified. 
1.  If the user has Azure AD B2C session available  (Example : testapp1) and clicking on the Href link with target ="_blank" pointing to another app (test app2) ,  which is again protected by Azure AD B2C,  multiple redirects were observed.  Test app2 application is loading after a multiple redirects . At times the test app2 does not load also. This issue is not browser specific.

2. But when we login directly to test app2 where Azure AD B2C SSO is not available, we are not facing multiple directs and application loads.  This issue is not browser specific.

Test app2 code is attached. Test app1 can be sample html page or another Azure Azure AD B2C app .

## Error Message
No error message in the console.

## Security
- [ ] Is this issue security related?
Not sure

## Regression
- [ ] Did this behavior work before? 
It did not work earlier
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```
```
   case 'qa.isp.xxxxxx.com':
    authConfig = Object.freeze({
     auth: {
        clientId: qaClientID,
        authority:'https://tmnab2cqa.b2clogin.com/tfp/tmnab2cqa.onmicrosoft.com/B2C_1A_IPlusISP_SignInPolicy',
        validateAuthority: false,
        redirectUri: 'https://qa.isp.toyota.com',
        postLogoutRedirectUri: 'https://qa.isp.toyota.com',
        navigateToLoginRequestUrl: true,
        // popUp: false
        // extraQueryParameters: signInPolicy
      },
      cache: {
        storeAuthStateInCookie: isIE, // Set this to "true" to save cache in cookies to address trusted zones limitations in IE (see: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser)
      },
      system: {
        logger: new Logger(loggerCallback, {
            correlationId: '1234',
            level: LogLevel.Verbose,
            piiLoggingEnabled: true
        })
    }
    });
    logout = "https://cpssologin-dc2.stg.toyota.com/tesslogin/logout.jsp?end_url=https://qa.isp.toyota.com";
    scopes = ["https://tmnab2cqa.onmicrosoft.com/qaispservices/read"]
```
## Expected behavior
Without multiple redirects the user should be able to logon successfully

## Browsers/Environment
- [x] Chrome - Yes
- [ ] Firefox - Yes
- [x] Edge - Yes
- [ ] Safari
- [x] IE
- [ ] Other (Please add browser name here)
[sample-poc.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/4781811/sample-poc.zip)

**Comment by jmckennon** [comment] 2020-06-15 20:33
I haven't been able to reproduce a loop even with the sample poc provided--so I have a few questions to make sure I'm understanding everything correctly.

Are your first and second test apps using the same clientId/authority/policies?

Are you using different test users when logging in to both of these apps?

Can any network traces be provided?

Please specify the _exact_ repro steps. What I've done is:
1. Start two b2c test apps locally. For me this is our own sample app and the poc provided here.
2. Navigate to test app1 and login.
3. Click a link with target=_blank on test app1 which redirects to the second sample app (the poc in this case)

And this is where you're seeing a loop, on page load to the second app?

I get redirected to the login page, and after logging in, I just see a page with some text at the top. Functionality is the same even if I'm already logged in. This is both with using the client's creds/clientId and our own test creds/clientId.

**Comment by jmckennon** [comment] 2020-06-15 20:35
You could also try setting `navigateToLoginRequestUrl` to false to try and deter any redirect shenanigans, though again, everything was working for me even with it set to true.

**Comment by muraliyv2020** [comment] 2020-06-15 20:52
•• PROTECTED 関係者外秘

Team

Please refer the ticket # 120020124000308. We have uploaded all the fiddler logs for the cyclic loop issue. Please do find the inline comments listed out below for the questions.

Thanks & Regards
Murali Yadavalli
On Assignment @ Toyota
Incentive Systems | IS Business Enablement – D&IS, Incentives
Toyota Motor North America (TMNA) | 469-292-2418 (Office) | 302-465-2940 (Cell)

**Comment by jmckennon** [comment] 2020-06-15 21:39
Okay, using the sample poc and https://qa.isp.toyota.com, I was able to see this, though it's still not happening with other apps.

Could you make sure that both apps are on the latest versions of `msal-angular` and `msal`? In the IcM it mentions version `1.3.0` for `msal`, and there were some redirect/loop fixes included in 1.3.1. We recommend upgrading that to 1.3.2.

Additionally, after changing all the instances of `navigateToLoginRequestUrl` to false, I was no longer getting multiple redirects/loops.

Please try these couple of possible fixes and let us know if things change.

**Comment by muraliyv2020** [comment] 2020-06-15 22:00
•• PROTECTED 関係者外秘

Jake

Please let me know where do we need to set up the navigateToLoginRequestUrl flag to false. We are using MSAL Angular version and Not MSAL.JS version. Do we have 1.3.2 in angular ?

Thanks & Regards
Murali Yadavalli
On Assignment @ Toyota
Incentive Systems | IS Business Enablement – D&IS, Incentives
Toyota Motor North America (TMNA) | 469-292-2418 (Office) | 302-465-2940 (Cell)

**Comment by jmckennon** [comment] 2020-06-15 22:26
`navigateToLoginRequestUrl` is a flag that you pass to an msal configuration. It enables/disables default redirect to a start page after login. More on that in [these docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications). 

Generally an app has one msal config that you pass in, though in your poc it looks like you're trying to juggle a few of of these configs, so you may need to change them all for now. An example:
```typescript
export type AuthOptions = {
    clientId: string;
    authority?: string;
    validateAuthority?: boolean;
    redirectUri?: string | (() => string);
    postLogoutRedirectUri?: string | (() => string);
    navigateToLoginRequestUrl?: boolean;
};
```

As for msal versions, `msal-angular` is a wrapper library for `msal`, so you actually use both. You can see how that works in our [msal-angular docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/README.md). Make sure that in BOTH apps (and likely any others you're using) that these are both up-to-date.

**Comment by muraliyv2020** [comment] 2020-06-15 22:42
•• PROTECTED 関係者外秘

I guess this flag is available in 1.3.0 version. We don’t have issues with cyclic loop redirections in earlier MSAL Versions . Not sure with this version why ?

DO we have MSAL angular version in 1.3.2 ?


Thanks & Regards
Murali Yadavalli
On Assignment @ Toyota
Incentive Systems | IS Business Enablement – D&IS, Incentives
Toyota Motor North America (TMNA) | 469-292-2418 (Office) | 302-465-2940 (Cell)

**Comment by jmckennon** [comment] 2020-06-15 23:22
The flag is available in both versions, yes, but in `msal@1.3.2`, there have been some bugfixes related to redirects and loops since `msal@1.3.0`, so I wanted to make sure you were receiving those bugfixes. The `navigateToLoginRequestUrl` flag is unrelated to the version bump. These were two different possible fixes to the issue you're seeing.

The latest version for msal-angular is `msal-angular@1.0.0`, and yes it is still supported in `msal@1.3.2`. The idea is to make sure both of these versions are updated in both of your apps, as it may fix the issue you're seeing.

**Comment by muraliyv2020** [comment] 2020-06-15 23:41
•• PROTECTED 関係者外秘

We are using MSAL Angular 1.0.0 , also you want us to include MSAL@1.3.2<mailto:MSAL@1.3.2> rt. Please confirm.

Thanks & Regards
Murali Yadavalli
On Assignment @ Toyota
Incentive Systems | IS Business Enablement – D&IS, Incentives
Toyota Motor North America (TMNA) | 469-292-2418 (Office) | 302-465-2940 (Cell)

**Comment by jmckennon** [comment] 2020-06-15 23:42
Yep, that is correct.

**Comment by jmckennon** [comment] 2020-06-25 19:11
Closing this as it was confirmed to be resolved externally. If you have further questions/issues, please open another ticket. Thanks!

**Closed by jmckennon** 2020-06-25 19:11 UTC
Labels: bug
