### ISSUE TITLE
The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2691] opened 2020-12-03 20:25 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.6.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React
## Description
Seeing some logs in our application showing the error
The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null
errorCode: token_request_cache_error

If it gives a clue, a user that faced this error was also facing error: AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request. Could the two be related?
## Error Message
The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:
Not sure..
## MSAL Configuration

```js
    const browser = Bowser.getParser(window.navigator.userAgent);
    const isIEOrOldEdge =
      browser.satisfies({ edge: "<79" }) || browser.getBrowserName().toLowerCase() === "internet explorer";
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: 60,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        this.account = response ? response.account : this.getAccount();
        if (!this.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login);
          return this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority,
            extraQueryParameters: this.safeRolloutQueryParams,
            redirectStartPage: returnUrl
          });
        } else {
          this.setTenantId(this.account.tenantId);
        }
        return undefined;
      })
      .catch(error => {
        if (error instanceof AuthError) {
          this.trackError(error);
        }
        this.loginToTenantRedirect(MsalAuthContext.defaultTenantId);
      });
    return { publicClientApp, handleRedirectPromise };
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
No TypeError
## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment] 2020-12-04 01:36
@thoo1 This may or may not be related to the other issue you posted related to state. What's happening here is that msal places your request in localstorage before redirecting to AAD. When AAD redirects back to your app msal will attempt to retrieve the cacehed request and compare certain properties to the response. In the error you shared above it appears msal was unable to get any cached request. Given that you were also seeing state issues, this may be related since the request is cached with state as part of the key. If you are able to reproduce this or are able to debug a live instance of this occurring it would be useful to take a look at local/session storage when this happens.

The code verifier error is interesting as I would expect msal to throw before attempting to make the network request with bad params. That's something I'll take a closer look at on our side.

**Comment by thoo1** [comment] 2020-12-04 18:25
@tnorling I see, thanks for the insight, that could be it.. I'll try to find a repro but for right now, I'm only seeing this in our logs.
For the code verifier error, what would be the bad params? I also see the code verifier errors on their own (so none of the other mentioned errors happened)

**Comment by tnorling** [comment] 2020-12-04 22:20
@thoo1 In this case it's specifically complaining about the `codeVerifier` being either wrong or missing. Which is likely also due to the fact that you seem to be having issues getting the cached request. I believe all of these issues share the same root cause.

**Comment by gabriel-kohen-by** [comment] 2020-12-21 00:23
I seem to be getting these consistently trying to re-login  after issuing logout while running in Chrome Incognito(MacOS Catalina Chrome 87):
`index.js:1 Error code={
  "errorCode": "invalid_request",
  "errorMessage": "undefined - [undefined]: AADB2C90182: The supplied code_verifier does not match associated code_challenge\r\nCorrelation ID: d1a8de73-e47e-4522-8f18-1b5b9ab941b9\r\nTimestamp: 2020-12-21 00:13:04Z\r\n - Correlation ID: undefined - Trace ID: undefined",
  "subError": "",
  "name": "ServerError"
} []` 

Then I'll try to log in after about 3 seconds and will get another error that auth is in progress. After trying again after about 4-5 seconds login works fine.
msal-browser version is 2.8.0

Ideas?

FYI: @alex-mason-by

**Comment by tnorling** [comment] 2020-12-21 17:28
@gabriel-kohen-by hmm that's odd, are you able to provide a minimal reproduction? Thus far, I have not seen this behavior personally so I couldn't speculate as to what's causing it.

**Comment by gabriel-kohen-by** [comment] 2020-12-21 18:30
@tnorling , thanks for the quick response. Not sure about minimal but I can share some of our code. I'd appreciate any insight on this as it stands in the way of us adopting PKCE.
Just to set the context, we have a main component for all of the apps that both makes sure we login before presenting the reset of the apps and has a simple messaging capability to allow different parts of the app to accept requests to get access token:
Main React Component:
```
import React, {useState} from 'react';

import {LinearProgress} from '@material-ui/core';
import {AuthService} from './auth/authService';
import {
    MsalProvider,
    UnauthenticatedTemplate,
    useMsal,
    AuthenticatedTemplate, useMsalAuthentication
} from "@azure/msal-react";
import {InteractionType} from "@azure/msal-browser";
import FallbackScreen from './components/fallbackScreen/fallbackScreen';
import App from './app';
import {IMsalContext} from "@azure/msal-react/dist/MsalContext";
import {MsalAuthenticationResult} from "@azure/msal-react/dist/hooks/useMsalAuthentication";


function AzureADWrapper() {
    const iframe = document.getElementById('mfe') as HTMLIFrameElement;
    const UnauthenticatedErrorComponent = () => {
        const {instance, accounts, inProgress} = useMsal();
        const {login, result, error} = useMsalAuthentication(InteractionType.Popup);
        iframe.className = 'mfe';
        console.debug(
            '%c MSAL authentication returned unauthenticated state',
            'background: yellow; color: black; display: block;'
        );
        console.log(`result=${JSON.stringify(result, null, 2)} inProgress=${inProgress}`)
        if (error) {
            console.error(`Error code=${JSON.stringify(error, null, 2)}`);
            // ERROR] Error: Can't construct an IdTokenResponse from a AuthResponse that has a token type of "access_token".
            switch (error.errorCode) {
                case 'endpoints_resolution_error':
                case 'popup_window_error':
                case 'token_renewal_error':
                    console.debug(
                        '%c MSAL authentication returned unauthenticated state and endpoints_resolution_error, trying to login again...',
                        'background: yellow; color: black; display: block;'
                    );
                    return <FallbackScreen loginFunction={login} errorCode={error.errorCode}/>;
                case 'interaction_required':
                case 'login_required':
                case 'consent_required':
                    console.debug(
                        `%c MSAL authentication returned unauthenticated state and ${error.errorCode}, trying to login again...`,
                        'background: yellow; color: black; display: block;'
                    );
                    if (!result?.account && inProgress !== "login") {
                        login();
                    } else if (inProgress === "login") {
                        return <LinearProgress/>;
                    } else {
                        return <FallbackScreen loginFunction={login} errorCode={error.errorCode}/>;
                    }

                case 'invalid_request':

                    setInterval(() => {
                        console.log(`result=${JSON.stringify(result, null, 2)} inProgress=${inProgress}`)
                        console.error(`Error code=${JSON.stringify(error, null, 2)}`);
                        console.log(`Account ${JSON.stringify(AuthService.getInstance().getDefaultAccount(), null, 2)}`)
                        console.log(`Accounts Raw ${JSON.stringify(accounts, null, 2)}`)
                 //       console.log(`MSAL Instance Raw ${JSON.stringify(instance, null, 2)}`)

                    }, 3000);
                    setTimeout(async () => {
                        const response: MsalAuthenticationResult=await login();
                        if (response.error?.errorCode === 'interaction_in_progress') {
                            setTimeout(login, 3000);
                        }
                        return <LinearProgress/>
                    }, 3000);

                    return <LinearProgress/>
                case 'user_cancelled':
                    return <FallbackScreen loginFunction={login} errorCode={error.errorCode}/>;
                default:
                    return <FallbackScreen loginFunction={login} errorCode={error.errorCode}/>;
            }
        } else {
            return <LinearProgress/>;
        }
        return <LinearProgress/>;
    }

    const InProgressComponent = ({inProgress}: IMsalContext) => {
        return <h5>{inProgress} In Progress</h5>;
    }

    const MainApp = () => {
        return (
            <App loginFunction={AuthService.getInstance().getAuthProvider().loginPopup}
                 accountInfo={AuthService.getInstance().getDefaultAccount()}>
            </App>
        )
    }

    return (
        <MsalProvider instance={AuthService.getInstance().getAuthProvider()}>
            <AuthenticatedTemplate>
                <MainApp></MainApp>
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
                <UnauthenticatedErrorComponent></UnauthenticatedErrorComponent>
            </UnauthenticatedTemplate>
        </MsalProvider>
    );
}

export default AzureADWrapper;

```

Our utility wrapper to delegate requests for access token to MSAL.js 2.0 (`authService.tsx`)
```

import { configureMsal, AuthProviderState } from './AuthProvider';
import { Logger, LogLevel } from 'msal';
import throttle from 'lodash/throttle';
import {
  Configuration,
  PublicClientApplication,
  InteractionRequiredAuthError,
  AuthenticationResult,
  AccountInfo,
  BrowserAuthError
} from '@azure/msal-browser';
import { msalProviderConfig } from './authConfig';
import { PopupRequest } from '@azure/msal-browser/dist/src/request/PopupRequest';
import { SilentRequest } from '@azure/msal-browser/dist/src/request/SilentRequest';

class DeferredRequest {
  scopes: string[];
  promise: Promise<AuthenticationResult>;
  resolve: (value: AuthenticationResult) => void;
  reject: (reason?: any) => void;

  constructor() {
    this.promise = new Promise<AuthenticationResult>((resolve, reject) => {
      this.resolve = resolve;
      this.reject = reject;
    });
  }
}

export class AuthService {
  private static _instance: AuthService;
  private account: AccountInfo | null;
  private requestQueue: Array<DeferredRequest> = [];
  private authProvider = new PublicClientApplication(msalProviderConfig.msalConfig);
  private readonly localStorageDomainHintName = 'default-domain-hint';

  static getInstance = () => {
    if (!AuthService._instance) {
      AuthService._instance = new AuthService();
    }
    return AuthService._instance;
  };
  
  isMSAL = (): boolean => {
    return window['env'].AUTH_METHOD ? window['env'].AUTH_METHOD.trim().toLowerCase() === 'msal' : false;
  };

  populateDomainHint = (): string => {
    const urlParams = new URLSearchParams(window.location.search);
    const domainHint = urlParams.get('domain-hint') || localStorage.getItem(this.localStorageDomainHintName) || '';
    localStorage.setItem(this.localStorageDomainHintName, domainHint);
    return domainHint;
  };

  getAuthToken = () => {
    if (this.isMSAL()) {
      const request = new DeferredRequest();
      this.requestQueue.push(request);
      this.processTokenRequest();
      return request.promise;
    } else {
      const mockedResponse = this.getEmptyAuthResponse();
      mockedResponse.accessToken = window['env'].AUTH_STATIC_TOKEN;
      return Promise.resolve(mockedResponse);
    }
  };

  logout = async (): Promise<void> => {
    if (this.isMSAL()) (await this.getAuthProvider().logout());
    localStorage.clear();
    sessionStorage.clear();
  };

  getDefaultAccount = () => {
    this.account = this.account || this.getResolvedAccount();
    return this.account;
  };

  getAuthUser = (): string => {
    if (this.isMSAL()) {
      return this.getDefaultAccount()?.name || '';
    } else {
      return window['env'].AUTH_STATIC_USER || '';
    }
  };

  getAuthPreferredUsername = (): string => {
    if (this.isMSAL()) {
      return this.getDefaultAccount()?.idTokenClaims?.['idp_preferred_username'] || '';
    } else {
      return window['env'].AUTH_STATIC_USER || '';
    }
  };
  login = async () => {
    const loginHint = this.getAuthPreferredUsername();
    const silentLoginRequest: PopupRequest = {
      scopes: msalProviderConfig.loginRequestConfig.scopes
    };
    if (loginHint !== '') {
      silentLoginRequest.loginHint = this.getAuthPreferredUsername();
    }
    const loginResponse = await AuthService._instance.authProvider.loginPopup(silentLoginRequest).catch(error => {
      console.error('Could not log in');
      return Promise.reject(error);
    });
    AuthService._instance.account = loginResponse.account;
  };

  private processTokenRequest = async () => {
    if ((this.requestQueue || []).length > 0) {
      const request = this.requestQueue.shift();
      if (request) {
        const scopes = request?.scopes || this.getDefaultScopes();
        try {
          try {
            const response = await this.requestToken(scopes);
            request.resolve(response);
          } catch (error) {
            console.warn(error);
            if (error instanceof InteractionRequiredAuthError) {
              try {
                const response = await this.requestTokenPopup(scopes);
                request.resolve(response);
              } catch (error1) {
                console.error(error1);
                request.reject(error1);
              }
            } else {
              const emptyResponse = this.getEmptyAuthResponse();
              request.reject(emptyResponse);
            }
          }
        } catch (error) {
          request.reject(error);
        }
      }
      await this.processTokenRequest();
    }
  };

  private getResolvedAccount() {
    // need to call getAccount here?
    const currentAccounts = this.getAuthProvider().getAllAccounts();

    if (currentAccounts.length > 1) {
      // Add choose account code here
      console.log('Multiple accounts detected, need to add choose account code.');
      return currentAccounts[0];
    } else if (currentAccounts.length === 1) {
      return currentAccounts[0];
    }
    return null;
  }

  private requestTokenPopup = async (scopes: string[]) => {
    const authProvider = this.getAuthProvider();
    let account = this.account;

    if (account) {
      return authProvider.acquireTokenPopup({
        scopes,
        extraQueryParameters: { domain_hint: this.populateDomainHint() },
        account: account
      });
    }
    return Promise.reject('Could not found user account');
  };

  private requestToken = async (scopes: string[]) => {
    const authProvider = this.getAuthProvider();
    if (!this.getDefaultAccount()) {
      await this.login();
    }
    const account = this.getDefaultAccount();

    if (account != null) {
      const silentTokenRequestParameters: SilentRequest = {
        scopes: this.getDefaultScopes(),
        account
      };
      const domainHint = this.populateDomainHint();
      if (domainHint !== '') {
        silentTokenRequestParameters.extraQueryParameters = {
          domainHint
        };
      }

      const response = await authProvider.acquireTokenSilent(silentTokenRequestParameters).catch(async error => {
        if (error instanceof InteractionRequiredAuthError) {
          // fallback to interaction when silent call fails
          const successResponse = await authProvider.acquireTokenPopup(silentTokenRequestParameters);
          return successResponse;
        } else {
          return Promise.reject(`Unspecified error: ${error.name}`);
        }
      });
      return response;
    }

    return Promise.reject('Could not get authorization token. Account not found because could not login.');
  };

  getDefaultScopes = (): Array<string> => {
    return [window['env'].DEFAULT_SCOPE];
  };

  getAuthProvider = () => {
    if (!this.authProvider) {
      this.authProvider = new PublicClientApplication(msalProviderConfig.msalConfig);
    }

    return this.authProvider;
  };

  getEmptyAuthResponse = (): AuthenticationResult => {
    return {
      accessToken: '',
      account: null,
      authority: '',
      expiresOn: new Date(),
      fromCache: false,
      idToken: '',
      idTokenClaims: {},
      scopes: [],
      tenantId: '',
      tokenType: '',
      uniqueId: ''
    };
  };
}
```

**Comment by drweb86** [comment] 2021-01-06 12:39
Hello

We have the same issue

Reproduction steps
1. Authorise using MSAL in some domain
2. Open web-site/Test1 and web-site/Test2 pages at the same time from one page (using middle mouse click). Each page should instruct MSAL to redirect to itself (it is important)
3. Result:
Page 1: The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null
Page 2: The reply address 'web-site/Test1' does not match the reply address 'web-site/Test2' provided when requesting Authorization code. 

Somehow MSAL invoked on second page knows about MSAL on first page response and mixes it!

**Comment by tnorling** [comment] 2021-01-06 17:21
@drweb86 Can you clarify your versions? Msal versions 1.4.4 and 1.4.0 do not use the Authorization Code Flow and are not the same as `msal-browser`.

I believe, the problem in your case is that we do not support multiple concurrent interactive requests for the same application. When you start the redirect flow msal places the request in localstorage so that when it returns from the AAD sign-in page the response can be compared to what was requested. Since your 2 tabs share localstorage and clientId they will each have access to the same cache entries which is causing the mixup. If you were to refresh page 2 before initiating the second redirect call the redirect call would fail with an `interaction_in_progress` error due to the first page already having started its login flow. 

Some things that should work with 2 tabs:
- Using `sessionStorage` each tab will have it's own storage
- 2 apps with different clientIds will not share cache

If you have further questions about this please open a new issue so we can focus on your specific scenario. Thanks!

**Comment by tnorling** [comment] 2021-01-25 19:10
@thoo1 @gabriel-kohen-by Is this still happening with the latest versions?

**Comment by thoo1** [comment] 2021-01-29 16:54
@tnorling We're still using 2.6.1, but have now fully migrated to msal-browser. We'll upgrade to 2.10.1 and see if we continue to see the error
Was there any code changes made in the later versions that could have solved this issue of 
AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request. ?

**Comment by tnorling** [comment] 2021-01-29 17:32
@thoo1 Since I have not been able to reproduce this I can't say for sure but we recently made some improvements to how the temporary cache works during a request which may solve this issue. We plan to release 2.10.1 next week, I'd give that a shot and if it's still happening reach out to me on Teams and we can try to debug.

**Comment by hectormmg** [comment] 2021-02-05 22:23
@thoo1, @gabriel-kohen-by  have you been able to test with the latest version of msal-browser (2.11) to see if your issue has been fixed?

**Comment by thoo1** [comment] 2021-02-08 18:16
@hectormmg thanks for following up, we have upgraded our msal-browser version from 2.6.1 to 2.11.0. As of right now, we do not see any instances of "token_request_cache_error" for users running v2.11.0. So far it looks good! I'll let you know if I do see the error again in v2.11.0
Cheers!

**Comment by pkanher617** [comment] 2021-02-18 20:37
Closing for now as the original issue seems to be resolved. Please comment if you have further issues with this specific error.

**Closed** 2021-02-18 20:36 UTC
Labels: bug-unconfirmed, msal-browser, question
