### ISSUE TITLE
Chrome browser freezes after popup login window closed

### ISSUE THREAD

**Issue by khuangzzz** [AzureAD/microsoft-authentication-library-for-js#5755] opened 2023-03-04 00:39 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Browser freezes after popup login window closed. If I put a breakpoint at the first line of `cleanPopup` function inside PopupClient.ts, and then resume script execution, the issue is gone. This issue only observes on Chrome. Safari and Edge are good. OS is macOS Ventura 13.2.1 (22D68).

Breakpoint is at:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/10824418/222860375-87496ed9-f619-4114-9005-1f5fdd937745.png">

### Error Message

No error message.

### Msal Logs

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/10824418/222859626-e82633b7-10b4-465e-ab45-2f3c395a6e70.png">

### MSAL Configuration

```javascript
{
      auth: {
        authority: `${instance}${tenant}`,
        clientId,
        navigateToLoginRequestUrl: true,
        postLogoutRedirectUri,
        redirectUri,
        clientCapabilities: ['CP1'],
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
      },
      system: {
        loggerOptions,
        allowRedirectInIframe: true,
      },
    }
```

### Relevant Code Snippets

```javascript
An example repo is provided in the Reproduction Steps.
```

### Reproduction Steps

1. Clone https://github.com/khuangzzz/msal_bug.git
1. npm i
1. Replace tenant id and app id in the `popupClient.ts`
1. npm start
1. Click the login button to sign-in in Chrome

### Expected Behavior

After popup window closed, the browser should still functional.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment] 2023-03-07 01:53
Hey @khuangzzz !

Are you seeing an error in the console when the browser freezes (without the break point hack)?

**Comment by khuangzzz** [comment] 2023-03-07 17:09
Hello @lalimasharda, no, I don't see any console errors. Log stops at `@azure/msal-common@10.0.0: Info - in acquireToken call in auth-code client`

**Comment by lalimasharda** [comment] 2023-03-07 22:33
Thanks for letting me know @khuangzzz . I am having a bit of trouble reproducing your issue but I am working with a teammate on this. I will get back to you tomorrow.

**Comment by JasonGore** [comment] 2023-03-14 18:28
@sameerag We have been seeing this with our app and `msal-browser` intermittently since October in both Chrome and Edge, specifically on Macs. Redirect flows are not affected. I have been able to repro this locally. I have a repro case that you can try if you can ping me internally.

**Comment by sameerag** [comment] 2023-03-14 19:16
Ack. Will do.

**Comment by sameerag** [comment] 2023-03-15 03:38
@khuangzzz We think this could be a browser issue. We are following up with an in-house browser expert and will update the findings here. Please note that this may take a couple weeks.

**Comment by JasonGore** [comment] 2023-03-15 23:17
I had some findings to share.

This issue seems to affect both MSA and AAD accounts doing full signin or partial signin (where password is not required.) 

As of 3/15/23 this issue seems to be only reproing in Chrome (111.0.5563.64) on ARM Macs. I'm not sure about Intel versions. It does not happen with Edge or either Chromium version surrounding the corresponding Chrome version (Mac_Arm_1097626_chrome-mac and Mac_Arm_1097658_chrome-mac.)

This issue also does not repro with the following builds so assume it will be "fixed" soon but still should follow up with Chrome team since issue has appeared in the past.
* Chrome Canary Version 113.0.5653.0 (Official Build) canary (arm64)
* Chrome Dev Version 113.0.5638.0 (Official Build) dev (arm64)
* Chrome Beta Version 112.0.5615.28 (Official Build) beta (arm64)

 I have a CPU Profiler trace that I'm trying to share with the Chrome team for followup.

**Comment by khuangzzz** [comment] 2023-03-16 17:31
Hey @JasonGore, thanks for the follow up. I am using the intel version Mac (2.3 GHz 8-Core Intel Core i9) with Chrome (111.0.5563.64)

**Comment by JasonGore** [comment] 2023-03-16 17:53
I've also reported a bug against Chrome and Mac ARM: https://bugs.chromium.org/p/chromium/issues/detail?id=1425153

@khuangzzz I only did an ARM CPU Profiler trace but if you want to do a CPU Profiler trace (via Xcode Instruments) and link it to that issue that may be helpful.

**Comment by sameerag** [comment] 2023-04-01 05:38
@JasonGore Do we need this issue open?

**Comment by JasonGore** [comment] 2023-04-03 15:27
For now this seems to be a Mac+Chrome specific issue, so I think it's ok closing this.

**Comment by sameerag** [comment] 2023-04-03 19:38
Thanks @JasonGore. Closing.

**Closed as completed by sameerag** 2023-04-03 19:38 UTC
Labels: question, external, msal-browser, bug-unconfirmed, public-client
