### ISSUE TITLE
interaction_in_progress: Interaction is currently in progress.

### ISSUE THREAD

**Issue by ignatzami** [AzureAD/microsoft-authentication-library-for-js#2929] opened 2021-01-22 21:09 UTC
I'm attempting to use the loginRedirect. When calling the function I receive the following error:

interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

Code Path:
```
export const App = () => 
{
  const [auth] = useState(new AuthStore());

  useEffect(() => {initializeIcons();}, [])

  try
  {
    auth.msalClient.loginRedirect();
  }
  catch(err)
  {
    console.log(err)
  }
  ....
  }
  ```

  AuthStore is a simple class wrapper around the msalClient and configuration objects, as well as the register call for the redirect callback.  

  AuthStore.tsx

```
import * as msal from "@azure/msal-browser";

export class AuthStore
{
    accountId?: string;
    idToken?: string;
    msalClient: msal.PublicClientApplication = new msal.PublicClientApplication(
        {
            auth: 
            {
                clientId: '...',
                authority: 'https://login.microsoftonline.com/...'
            }
        }
    );

    constructor() 
    {
        // Register Callbacks for Redirect flow
        this.msalClient.handleRedirectPromise()
            .then(this.handleResponse)
            .catch((error) => 
            {
                // TODO: Logging!
                console.log("Handle Redir: " + error);
            }
        );
    }

    handleResponse(resp: msal.AuthenticationResult | null) 
    {
        if (resp !== null && resp.account !== null)
        {
            this.accountId = resp.account.homeAccountId;
            this.idToken = resp.idToken;
        }
        else
        {
            const currentAccounts = this.msalClient.getAllAccounts();

            if (!currentAccounts || currentAccounts.length < 1) 
            {
                this.msalClient.loginRedirect({scopes: ["User.Read"]});
            }
        }
    }
}
```

**Comment by ignatzami** [comment] 2021-01-22 21:30
The response from MSAL is null, this causes the error case in AuthStore to re-call the login redirect, despite having already been redirected.

**Comment by jasonnutter** [comment] 2021-01-22 21:44
@tnorling Can you help here?

**Comment by tnorling** [comment] 2021-01-22 21:48
@ignatzami I would recommend putting your login call into a `useEffect` hook. You don't want `loginRedirect` to be invoked on every render. Additionally, I would not recommend calling `loginRedirect` inside `handleResponse` as this can cause loops.

In case you are not yet aware we also have a react wrapper which solves a lot of these problems for you and should be mostly plug and play. Check it out [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react)

**Comment by AGDevX** [comment] 2021-01-24 19:39
@tnorling , the issue that @ignatzami  describes seems to be exactly what another dev describes in issue #2149. I'm experiencing the issue in this thread by using the repro steps in the one I referenced. It seems to have been fixed in version 2.0.2, but it appeared again in 2.10.0. I walked through upgrading my msal-browser version-by-version from 2.0.1 to 2.10.0. Here is what I found:

2.0.1: this issue exists
2.0.1 - 2.9.0: this is not an issue
2.10.0: this issue reappears

Here is a very simple React component that demonstrates this issue. I realize there is a React wrapper being built, but it's in alpha and I hope to have a production-ready app prior to the library being officially released.

`
import React from 'react';
import { PublicClientApplication } from '@azure/msal-browser'; //-- https://www.npmjs.com/package/@azure/msal-browser

const Login = () => {
	const msalPublicClientApp = new PublicClientApplication(APP_SETTINGS.msalConfig);

	const handleLogin = () => {
		msalPublicClientApp.loginRedirect();
	};

	return (
		<>
			<h1>Login</h1>
			<button onClick={handleLogin}>Log In</button>
		</>
	);
};

export default Login;
`

**Comment by tnorling** [comment] 2021-01-25 18:11
@AGDevX Thanks for the information. I've identified the source of the regression and will make sure a fix is included in the next release.

**Comment by eluchsinger** [comment] 2021-02-01 10:36
@tnorling this is an issue that also happens in Angular.

**Comment by tnorling** [comment] 2021-02-02 02:28
All, `msal-browser@2.11.0` has just been released, which contains the fix for this bug. Closing, please open a new issue if you have further questions. Thanks!

**Closed by tnorling** 2021-02-02 02:28 UTC
Labels: msal-react, question

**Comment by fjuriolli** [comment] 2021-02-02 18:52
@tnorling I'm still able to reproduce this using `loginRedirect` with `msal-browser@2.11.0`.

**Comment by tnorling** [comment] 2021-02-02 19:32
@fjuriolli Can you please open a new issue and include your config and steps to reproduce? Thanks!
