### ISSUE TITLE
Cannot find module '@azure/msal-angular' or its corresponding type declarations. Angular 16

### ISSUE THREAD

**Issue by theviveik1** [AzureAD/microsoft-authentication-library-for-js#6323] opened 2023-08-10 06:32 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0

### Public or Confidential Client?

Public

### Description

**Cannot find module '@azure/msal-angular' or its corresponding type declarations.**

The module '@azure/msal-angular' or its corresponding type declarations could not be located. Despite having installed @azure/msal-angular@3.0.0, I'm encountering difficulties in utilizing the library. Refer to the image below for more context. It's important to note that I'm utilizing the library with Angular 16, having previously used version 3.0.0-beta.1, which functioned as anticipated.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/134932805/5345453a-8330-4372-a2c2-9010d36b2d06)

### MSAL Configuration

```javascript
import {
  MsalBroadcastService,
  MsalGuard,
  MsalInterceptor,
  MsalModule,
  MsalRedirectComponent,
  MsalService,
  MSAL_GUARD_CONFIG,
  MSAL_INSTANCE,
  MSAL_INTERCEPTOR_CONFIG
} from '@azure/msal-angular';
```

### Relevant Code Snippets

```javascript
import { MsalGuard } from '@azure/msal-angular';
```

### Reproduction Steps

1. download any angular 16 project
2. configured whatever is required for msal
3. then run npm install @azure/msal-browser@3.0.0 @azure/msal-angular@3.0.0
4. npm start 

### Expected Behavior

Application should run.. but receiving below error 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/134932805/e472816d-bca0-4407-9178-dfd0e51d36a7)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Internet Explorer

### Regression

@azure/msal-browser@3.0.0-beta.1 @azure/msal-angular@3.0.0-beta.1

### Source

External (Customer)

**Comment by solita-markuspulkkinen** [comment] 2023-08-10 07:50
content of node_modules/@azure/msal-angular seems to have just src and no dist || other build results

**Comment by hansakaRightS** [comment] 2023-08-10 08:09
we are having the same issue.check here #6310

**Comment by theviveik1** [comment] 2023-08-10 09:00
Please link this bug with #6310, so that i can follow the same whatever the status change would notified me.

**Comment by jo-arroyo** [comment] 2023-08-10 16:15
@theviveik1 As others have stated above, there has been an error in our release process for msal-angular, and we are currently working on a fix. Please follow #6310, where the issue was first raised, and where updates will be posted. 

Closing as duplicate of #6310.

**Closed as completed by jo-arroyo** 2023-08-10 16:15 UTC
Labels: question, msal-angular, msal-browser, bug-unconfirmed, public-client
