### ISSUE TITLE
Msal.UserAgentApplication object is undefined in authCallback when using loginRedirect

### ISSUE THREAD

**Issue by gayathri-rajamanickam4** [AzureAD/microsoft-authentication-library-for-js#278] opened 2018-04-12 11:53 UTC
Hi,

I'm trying to integrate MSAL with angular 5.x application. I'm using angular-cli template. 

I have a requirement to show the login screen NOT as pop and need to retrieve access token as soon as the id token is retrieved.

For loginRedirect, all existing examples have implemented this as 2 step process. That is, first get idToken in a click event. and then acquireAccessToken in another click event. As my requirement is to get access token as soon as the page is redirected to my application (not with one another button click event), I have tried with authentication call back method to call 'acquireTokenSilent'. But in the call back, the object of Msal.UserAgentApplication is undefined.

In the below code, **withinin authCallback, this.app is undefined**. The same code is working fine if I use loginPopup method and have this code block within promise returned from loginPopup.

Entire code setup is available at https://github.com/gayathri-rajamanickam4/angular-msal

Here is the code snippet.

@Injectable()
export class AuthHelper {
  public access_token = null;

  public app: Msal.UserAgentApplication = null;
  public user;
  public isAuthenticated = false;

  constructor() {
    const logger = new Msal.Logger(this.loggerCallback, { level: Msal.LogLevel.Verbose, correlationId: '12345' });
    this.app = new Msal.UserAgentApplication(CONFIG.CLIENT_ID,  CONFIG.AUTHORITY, this.authCallback
    , { logger: logger, cacheLocation: 'localStorage',
    redirectUri: CONFIG.REDIRECT_URI,
    navigateToLoginRequestUrl: false});
      }

authCallback = (errorDesc, token, error, tokenType) => {
       if (token) {
        console.log('loginRedirect- Success');
        **this.app.acquireTokenSilent**(CONFIG.SCOPES).then(
          accessToken => {
            this.access_token = accessToken;
            console.log('ACCESS TOKEN: \n ' + this.access_token);
            this.user = this.app.getUser(); // AZURE AD
            this.isAuthenticated = true;
          },
          acquireTokenSilentError => {
            console.log('acquireTokenSilent- Error:\n' + acquireTokenSilentError);
            this.app.acquireTokenRedirect(CONFIG.SCOPES).then(accessToken => {
              console.log('acquireTokenRedirect- Success:\n' + accessToken);
            },
            acquireTokenRedirectError => {
              console.log('acquireTokenRedirect- Error:\n' + acquireTokenRedirectError);
            });
          }
        );
      } else {
        console.log('Error during login:\n' + error);
        console.log('Error Description of login error:', errorDesc);
      }
  }
}

Please let me know how this can be achieved

**Comment by 4deeptech** [comment] 2018-05-02 15:08
The problem I see with this is that when you access 'this' in the callback, it is not longer the AuthHelper that is referenced by 'this'.  It appears to be the UserAgentApplication but the issue here is the compiler won't let you use 'this' assuming it is the UserAgentApplication object referenced. What is needed is the callback needs to preserve the scope of 'this' so that inside the callback 'this' refers to the original object the callback function is tied to.

**Comment by 4deeptech** [comment] 2018-05-02 20:44
I believe the issue is here:

`this._tokenReceivedCallback.call(this, errorDesc, token, error, tokenType);`

It overrides the context of 'this' so if you try to pass a tokenCallback.bind(this), the code above just tosses that away.

**Comment by jkga** [comment] 2018-05-10 09:43
I'm having the same issue when updated to latest version.

ERROR : **Error occurred in token received callback function: TypeError: Cannot read property 'acquireTokenSilent' of undefined**

**Downgrading** to msal **0.1.3** solves the issue

**Comment by redtaped** [comment] 2018-05-18 02:40
In order to preserve the scope of "this" to be the UserAgentApplication instance that initiated the callback, remove the arrow function syntax and replace with a function() {} syntax. 

The arrow function auto binds "this" to the declared scope instead of the scope of the original caller. 

After making that change, no longer refer to this.app, but just "this" which will represent the UserAgentApplication object.

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

**Comment by jkga** [comment] 2018-05-21 13:28
But even without using "_this_" it will still throw an error. 
Consider the following code below

``` 
var applicationConfig = {
   clientID: 'dd7a26d3-c6ef-4cba-8ed4-b796889378583849-7g96',
    . . .
};

var logger = new Msal.Logger(loggerCallback, { level: Msal.LogLevel.Verbose });

function loggerCallback(logLevel, message, piiEnabled) {
        console.log(message);
}
    
var userAgentApplication = new Msal.UserAgentApplication(
applicationConfig.clientID, 
null, 
authCallback, 
{ cacheLocation: 'localStorage', logger: logger });

 // callback function
function authCallback(errorDesc, token, error, tokenType) {
      if (token) {
            // This throws an error
            userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes)
     }

}

```

**Comment by redtaped** [comment] 2018-05-22 02:40
@jkga, because you are referencing the local instance, and not the instance of the callback. You need 'this' to have access to the original context that originated the callback

**Comment by jkga** [comment] 2018-05-22 04:12
@redtaped, you are right! Thank you for clarification.

FYI, the local instance of `userAgentApplication` works as expected in MSALJS **<= 0.13**. This might not be appropriate but maybe we could add it on the [example](https://github.com/AzureAD/microsoft-authentication-library-for-js#example) code 2.) to avoid confusion of  using `userAgentApplication` in 3.) ?

> Excerpt from https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html

```function authCallback(errorDesc, token, error, tokenType) {
            //This function is called after loginRedirect and acquireTokenRedirect. Use tokenType to determine context. 
            //For loginRedirect, tokenType = "id_token". For acquireTokenRedirect, tokenType:"access_token".
            if (token) {
                this.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
                    // Change button to Sign Out
                    updateUI();
                }, function (error) {
                    console.log(error);
                    this.acquireTokenPopup(applicationConfig.graphScopes).then(function (accessToken) {
                        updateUI();
                    }, function (error) {
                        console.log(error);
                    });
                });
            }
            else if (errorDesc || error) {
                console.log(error + ':' + errorDesc);
            }
        }
```

**Comment by rdeveen** [comment] 2018-05-28 09:44
Maybe you can try something like this:
```
authCallback = (errorDesc, token, error, tokenType) => {
  let msal = window.msal as Msal.UserAgentApplication;
  msal.acquireTokenSilent( 
  etc. etc. etc.
}
```

**Comment by 4deeptech** [comment] 2018-06-13 14:34
@redtaped So if my application declares a variable for the UserAgentApplication like below:
`var userAgentApplication = new Msal.UserAgentApplication(
applicationConfig.clientID, 
null, 
authCallback, 
{ cacheLocation: 'localStorage', logger: logger });

 // callback function
function authCallback(errorDesc, token, error, tokenType) {
      if (token) {
            //'this' is the instance of UserAgentApplication above
            this.acquireTokenSilent(applicationConfig.graphScopes)
     }
}`

There is a line I referenced above that hijacks the 'this' reference that you may want to control through arrow functions or binding with .bind(). This means that it doesn't matter what you try to do to make 'this' be the context of the outside scope where you declared `var userAgentApplication`, it will always be the UserAgentApplication.

I forked this library and changed it so I the following:

`var userAgentApplication = new Msal.UserAgentApplication(
applicationConfig.clientID, 
null, 
authCallback.bind(this), //<---change here
{ cacheLocation: 'localStorage', logger: logger });

 // callback function
function authCallback(errorDesc, token, error, tokenType) {
      if (token) {
            //'this' is the now the outer scope where I declared var userAgentApplication
            //and I can just use my declared variable to call acquireTokenSilent
            // and to whatever other functions/methods I have defined in that outer scope
            //perhaps show progress spinner or do some other UI work
            userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes)
     }
}`

so that in my callback 'this' refers to the outer scope.  Why would they hijack my ability to control 'this' using:

`this._tokenReceivedCallback.call(this, errorDesc, token, error, tokenType);`

I changed it back to a normal:

`this._tokenReceivedCallback(errorDesc, token, error, tokenType);`

**Comment by navyasric** [comment] 2018-11-01 20:54
Closing this issue as this has been addressed in the above referenced issue.

**Closed by navyasric** 2018-11-01 20:54 UTC
