### ISSUE TITLE
Slow running local with multiple openid-configuration calls 

### ISSUE THREAD

**Issue by kingbe01** [AzureAD/microsoft-authentication-library-for-js#992] opened 2019-09-18 12:56 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ X] Chrome version XX
- [ X] Firefox version XX
- [ X] IE version XX
- [ ] Edge version XX
- [ X] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior
I have searched high and low for an answer for this and cannot find a solution. 
When running locally it makes a call to .well-known/openid-configuration for every api call made on the page and takes about 5 seconds each. Basically looks like it is trying to renew token before every call instead of using cached token. I apologize if this is not the right platform for this but cannot find a solution and it is making development very difficult. All of the compiled versions in Angular 7 work as expected.

## Minimal reproduction of the problem with instructions
Running msal-angular per the documentation locally.

**Comment by jasonnutter** [comment] 2019-09-18 16:18
@kingbe01 Can you please provide some steps (e.g. a sample project) that demonstrates this? And can you share the `openid-configuration` url your app is calling (e.g. `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`)?

Calling that endpoint every time a new token is fetched from the network is by design and should be cached by browser, so I'm guessing the issue is how you are fetching your cached token, which is resulting in a network call to get a new one each time.

Thanks!

**Comment by jasonnutter** [comment] 2019-09-18 16:19
Also, please denote the version of `msal-angular` you are using, thanks!

**Comment by kingbe01** [comment] 2019-09-18 16:28
@jasonnutter Thanks for the quick response. 
Version 0.1.2

https://mncportaldev.b2clogin.com/tfp/mncportaldev.onmicrosoft.com/b2c_1_mncportaldev_signupsignin/v2.0/.well-known/openid-configuration

The odd thing is this behavior does not exist on a full build. It checks the cached version 1st before going back out to openId. Is it possible that something with HMR running locally could cause the issue? This is my first MSAL project so I apologize for any ignorance in the matter.

**Comment by himadrinath** [comment] 2019-09-18 17:23
@jasonnutter  i am also seeing this same behavior in my react application today i just updated to version@1.1.3

i cached to into my localStorage. 

https://linklookrauthdev.b2clogin.com/tfp/26530a5c-4c03-4545-bcdc-fa423894e9ff/b2c_1_sign_in_up/v2.0/.well-known/openid-configuration

it's happening to dev and pod both env

**Comment by himadrinath** [comment] 2019-09-19 08:03
fixed it. its happened because of scope. now its working fine

**Comment by kingbe01** [comment] 2019-09-19 13:44
@himadrinath that did it. Looks like local env scope settings were off! Thanks.

**Comment by jasonnutter** [comment] 2019-09-19 15:41
Good to hear you were able to get it working. One note, it is a known issue that the `openid-configuration` endpoints for B2C authorities do not have the proper cache headers set, and we have alerted the B2C server team about that.

Closing, let us know if you have any further questions. Thanks!

**Closed by jasonnutter** 2019-09-19 15:41 UTC
Labels: angular, question

**Comment by Rocky-Moon** [comment] 2019-12-03 20:24
I had the same problem, I was specifying my scopes with openid:

const scopes = ['openid', `api://${process.env.REACT_APP_CLIENT_APPLICATIONID}/access_as_user`];

I thought I required openid in there for some reason, however removing it still works and I now longer get the https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration requests on every api call.
