### ISSUE TITLE
[ERROR] ClientAuthError: Token renewal operation failed due to timeout.

### ISSUE THREAD

**Issue by edd82** [AzureAD/microsoft-authentication-library-for-js#2361] opened 2020-10-01 08:20 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
 `msal@1.3.3`
 "react-aad-msal": "2.3.5",

## Framework

React JS

## Description

After opening up a number of tabs to our application we receive the 'Token renewal operation failed due to timeout' error and the user are confronted with the "Microsoft Pick an account"  page with the error "We couldn't sign you in. Please try again."  If the user tried the original account then the issue continues however if you chose "Chose another Account" and then chose the same account again then the user will be routed back to our site, for a few moments the page loads but then the users receive a blank page.  On checking the console at the point we see an error.

## Error Message

Within Firefox:

ClientAuthError: Token renewal operation failed due to timeout.
    t AuthError.ts:26
    t ClientAuthError.ts:108
    createTokenRenewalTimeoutError ClientAuthError.ts:141
    c WindowUtils.ts:65
    setInterval handler*Ce</e.monitorIframeForHash/< WindowUtils.ts:60
    monitorIframeForHash WindowUtils.ts:50
    loadIframeTimeout UserAgentApplication.ts:943
    u tslib.es6.js:100
    u tslib.es6.js:81
    a tslib.es6.js:71
    promise callback*c tslib.es6.js:73
    a tslib.es6.js:74
    a tslib.es6.js:70
    loadIframeTimeout 2.20c2431e.chunk.js:2
    renewToken UserAgentApplication.ts:1540
    acquireTokenSilent UserAgentApplication.ts:849
    u tslib.es6.js:100
    u tslib.es6.js:81
    a tslib.es6.js:71
    promise callback*c tslib.es6.js:73
    a tslib.es6.js:74
    a tslib.es6.js:70
    acquireTokenSilent UserAgentApplication.ts:713
    acquireTokenSilent UserAgentApplication.ts:713
    e MsalAuthProvider.ts:130
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    d 2.20c2431e.chunk.js:2
    a 2.20c2431e.chunk.js:2
    h 2.20c2431e.chunk.js:2
    h 2.20c2431e.chunk.js:2
    t MsalAuthProvider.ts:51
    e ApiUtils.js:11
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    k ApiUtils.js:6
    D ApiUtils.js:135
    e Covid19DashboardAreas.js:38
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97

Within Chrome

authorize:82 Unsafe JavaScript attempt to initiate navigation for frame with origin 'The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

authorize:82 Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to

react_devtools_backend.js:2273 [ERROR] ClientAuthError: Token renewal operation failed due to timeout.
overrideMethod @ react_devtools_backend.js:2273
value @ Logger.ts:19
(anonymous) @ MsalAuthProvider.ts:301
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
d @ 2.20c2431e.chunk.js:2
a @ 2.20c2431e.chunk.js:2
(anonymous) @ 2.20c2431e.chunk.js:2
(anonymous) @ 2.20c2431e.chunk.js:2
(anonymous) @ MsalAuthProvider.ts:51
(anonymous) @ MsalAuthProvider.ts:143
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
d @ 2.20c2431e.chunk.js:2
u @ 2.20c2431e.chunk.js:2
Promise.then (async)
d @ 2.20c2431e.chunk.js:2
a @ 2.20c2431e.chunk.js:2
(anonymous) @ 2.20c2431e.chunk.js:2
(anonymous) @ 2.20c2431e.chunk.js:2
(anonymous) @ MsalAuthProvider.ts:51
(anonymous) @ ApiUtils.js:11
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ ApiUtils.js:6
I @ ApiUtils.js:96
(anonymous) @ Summary.js:41
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
value @ Summary.js:34
iu @ react-dom.production.min.js:212
dc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bo @ react-dom.production.min.js:122
pc @ react-dom.production.min.js:248
Zu @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Vo @ react-dom.production.min.js:122
Gu @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ CacheBuster.js:58
Promise.then (async)
value @ CacheBuster.js:46
iu @ react-dom.production.min.js:212
dc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bo @ react-dom.production.min.js:122
pc @ react-dom.production.min.js:248
Zu @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bo @ react-dom.production.min.js:122
$o @ react-dom.production.min.js:123
Vo @ react-dom.production.min.js:122
gc @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bo @ react-dom.production.min.js:122
vc @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
U @ scheduler.production.min.js:17
O.port1.onmessage @ scheduler.production.min.js:14
Show 26 more frames
ApiUtils.js:30 ClientAuthError: Token renewal operation failed due to timeout.
## Security

Yes

## Regression
- [ ] Did this behavior work before?   We're not sure as the error was reported after pushing out to production.   We had received "Cookie header size too large" previously during testing but found it difficult to replicate this issue.   After upgrading to MSAL 1.3.3 this error has not been seen so far however now we are receiving the 'Token renewal operation failed due to timeout' fairly consistently.

Version: MSAL 1.3.3

## MSAL Configuration

 // authProvider.js
    import { MsalAuthProvider, LoginType } from 'react-aad-msal';

    // Internet Explorer 6-11
    const isIE = /*@cc_on!@*/false || !!document.documentMode;

    // Edge 20+
    const isEdge = !isIE && !!window.StyleMedia;

    const varStoreAuthStateInCookie = isEdge?true:false;
    
    // Msal Configurations
    const config = {
    auth: {
        authority: 'https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        redirectUri: window.location.origin + '/xxxxxxx/xxxxxxxx-xxxxx/auth'
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: varStoreAuthStateInCookie
    }
    };
    
    // Authentication Parameters
    const authenticationParameters = {
    scopes: [
        // 'user.read',
        'api://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/access_as_user'
    ],
    }
    
    // Options.  LoginType should be set to Redirect to force the use of the non-popup login screen.
    const options = {
    loginType: LoginType.Redirect,
   
    tokenRefreshUri: window.location.origin + '/xxxxxxxxxx/xxxxxxxxx/auth'
    }
    
    export const authProvider = new MsalAuthProvider(config, authenticationParameters, options)

```js
// Provide configuration values here.

Within the App Registration we do have /auth after each of the available URL's

Implicit Grant flow:  Access Tokens and ID Tokens are enabled.

## Reproduction steps

Users open our application within multiple tabs.  It's not always the same amount of open tabs however we've managed to replicate it at times after opening 4/5 tabs with the same URL.

## Expected behavior

Application should load as expected.   So far we've manage to replicate issue in Chrome and Firefox.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge

**Comment by jmckennon** [comment] 2020-10-01 16:12
Can you upgrade to `msal@1.4.1` and see if the issue is fixed?

**Comment by edd82** [comment] 2020-10-02 10:56
Unfortunately not we have updated library both locally and on our test servers but we are still getting the same error.    Opening up Chrome tabs 10/11 times and error persists.

Also we’ve just noticed that when routing through a web reverse proxy the error happens every time away.  Perhaps this is different issue but I thought I should raise it.

**Comment by edd82** [comment] 2020-10-02 11:39
We've realised that the Web Proxy problem was a different issue and have now resolved it.   We'd tried creating an auth.html blank file and set that as the tokenRefreshUri, this caused issues with the web  proxy so have reverted to /auth and can now access the site.   

Opening multiple tabs still causes the "Token renewal operation failed due to timeout" error

**Comment by jmckennon** [comment] 2020-10-02 16:13
@edd82 Can you send a fiddler trace to the email on my profile so we can take a closer look?

**Comment by jmckennon** [comment] 2020-10-19 20:13
Resolved offline in email. User was experiencing throttling from the server which `msal@1.x` does not respect as the feature is in `msal@2.x`. Closing now. If there are further questions please open a new issue. Thanks!

**Closed by jmckennon** 2020-10-19 20:13 UTC
Labels: bug, msal@1.x, no-issue-activity
