### ISSUE TITLE
IdToken missing from AccountInfo object on page reload

### ISSUE THREAD

**Issue by sunil-ems** [AzureAD/microsoft-authentication-library-for-js#6112] opened 2023-06-08 01:46 UTC
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.7

### Public or Confidential Client?

Public

### Description

Unable to retrieve id token from account object (needed for logout) after reloading the page.

Logout Scenario:
- Navigate to setting page (which is guarded by MsalGuard)
- Then reload the page
- invoke msal auth service getActiveAccount() method (id token is missing in account object here)
- currently using logoutRedirect() with idtokenhint as 'Require ID token in logout requests in Azure B2C user flow' is configured to true.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/80860403/9634fa02-a036-4b3b-a342-6fb87fe2ab1c)

Log after reloading the page.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/80860403/8c526243-e23e-41c2-ab2f-43af6e72495d)

It seems like it's failing because of the authority metadata stored in memory storage which gets cleared on page reload and the authority meta data is not discovered until acquireToken get called?

### MSAL Configuration

```javascript
{
     auth: {
      "clientId": "client-id",
      "authority": "https://domain.b2clogin.com/domain.onmicrosoft.com/signin_policy_name",
      "redirectUri": "http://localhost:4200/auth",
      "postLogoutRedirectUri": "http://localhost:4200/",
      "knownAuthorities": [
        "domain.b2clogin.com"
      ]
    },
    "cache": {
      "cacheLocation": "localStorage",
      "storeAuthStateInCookie": false
    },
    "guard": {
      "interactionType": "redirect",
      "authRequest": {
        "scopes": []
      },
      "loginFailedRoute": "/auth-failed"
    },
    "interceptor": {
      "interactionType": "redirect",
      "protectedResourceMap": {
        "https://apidomain.azurewebsites.net/api/": [
          "https://domain.onmicrosoft.com/ApiName/RouteName"
        ]
      }
    }
}
```

### Relevant Code Snippets

```javascript
logout(): {
  const account = this.msalService.instance.getActiveAccount();
    this.msalService.logoutRedirect({
      account: account,
      idTokenHint: account.idToken
    });
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by sameerag** [comment] 2023-06-11 03:01
@sunil-ems Can you confirm that the `idToken` is returned in the response before `reload`?  `AuthorityCache` is in-memory and does not sustain page reloads but the account object cached should have had `idToken` cached already in the first place.

**Comment by sunil-ems** [comment] 2023-06-12 23:59
Hi @sameerag, Yes the idToken is in response before reload. After reload, if I switch to another page which interacts with protected api then next time the idToken will retrieved successfully. 

After refresh the the matchEnvironment function in CacheManager returning false where it validates authority metadata which is stored in memory and probably lost it's state after refresh? 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/80860403/e0d99fe5-6818-4ec7-befc-1433dfae36ed)
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/80860403/aa78a126-9a31-47be-b207-3377053fe867)

**Comment by sameerag** [comment] 2023-06-13 06:14
Yes, but there should be a config environment variable that matches the lookup. This looks like a potential bug. Can you share a simple code for sample repro on our end?

**Comment by sunil-ems** [comment] 2023-06-14 23:39
Hi @sameerag, please refer this sample example of profile page to reproduce the issue. If you navigate to profile page after login you'll get the idToken but not after reloading the profile page.

```
@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  idToken?: string;

  constructor(
    private authService: MsalService
  ) { }

  ngOnInit() {
	const account = this.authService.instance.getActiveAccount();
	if(account) {
		this.idToken = account.idToken;
	}
  }
}
```

Update the profile html file to this: 
`<div>ID Token: {{ idToken || 'Not Found'}}</div>`

**Comment by MattWatt** [comment] 2023-06-26 19:28
I'm also experiencing this with msal-browser 2.37.1.  I'm trying to comply with a B2C logout configuration that requires the `idTokenHint` in a situation where the browser page is reloaded and\or cache is dropped. 

When I call `getAllAccounts` or `getAccountByHomeId`, the `AccountInfo` object returned does not contain an `idToken` value.

I can see the cached token in Local storage, but the library does not fetch it.

I have a temporary workaround, but it appears there is a long history of similar issues (see #5053) , and my expectation is the `AccountInfo` object should contain this value, fetched from cache internally by the library.

```
    protected getIdTokenFromCache(homeAccountId: string): string | null {
        if(!this.msalInstance) {
            this.logger.error("MSAL is not Initalized");
            return null;
        }

        const cache = this.msalInstance.getTokenCache();
        // @ts-ignore
        // This isn't exposed by MSAL.js type definitions
        const idTokenEntity = cache.storage.getIdToken(homeAccountId);
        return idTokenEntity?.secret;
    }
```

Are my expectations wrong, that when I select an account with a method like `getAllAccounts()`, that it would contain the cached idToken as a property on the account?  Or is this a bug?

**Comment by sameerag** [comment] 2023-06-28 05:01
@sunil-ems  and @MattWatt let me get back once I get a chance to reproduce this. Marking it as a bug.

**Comment by tnorling** [comment] 2023-07-06 18:26
This is expected behavior (for now) as the authority metadata is required in order to do the token lookup and we can't do the metadata retrieval in our account APIs because it's an async operation, it only works if the data is already there (which it's not on a fresh page load). The idToken was added to the `AccountInfo` object as a convenience feature but is done by best effort, it's not guaranteed. If you need the idToken `acquireTokenSilent` is the best way to retrieve it.

We will be making some improvements to this in our v3 release where we will pre-fetch the metadata during initialization but that work has not been prioritized yet.

**Comment by sameerag** [comment] 2023-07-11 17:07
Thanks @tnorling for the update. @MattWatt and @sunil-ems closing this as we cannot fix this in v2. We will try improving this experience in the next iteration.

Please also note that perf for the call `acquireTokenSilent` should be equivalent to fetching from `cache` as long as the token is cached.

**Closed as completed by sameerag** 2023-07-11 17:07 UTC
Labels: bug, b2c, msal-angular, msal-browser, public-client
