### ISSUE TITLE
Not able to acquire token if user is logged in to multiple Google accounts

### ISSUE THREAD

**Issue by ChristianOlsson** [AzureAD/microsoft-authentication-library-for-js#609] opened 2019-03-22 12:40 UTC
Using msal 0.2.4 and Chrome I am seeing issues when users are signed in to multiple Google accounts. This both happens in my app and for the sample app active-directory-b2c-javascript-msal-singlepageapp.

Repro using the sample app:
1. Sign in to gmail with two different accounts (I used Add account in the Google Account tab)
2. Clone the sample app and run it (https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp.git)
3. Sign in using Account 1

Expected:
The user is signed in as Account 1

Actual:
The method acquireTokenSilent throws an exception and the only way to recover is to ask the user to sign in again. The user is no able to select Account 2, resulting in an id token for Account 1 and an Access token for Account. If acquireTokenSilent is called again, the user will again be asked to sign in.

Also described here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/177

**Comment by randompixel** [comment] 2019-07-01 10:34
Yes, seeing the same issue here. If signed in to multiple Google accounts the `acquireTokenSilent` function fails. It loads the silent iframe but then fails because it doesn't know which token to get (it seems)
![image](https://user-images.githubusercontent.com/2316601/60429731-9e7f1e80-9bf3-11e9-9508-a7d240529285.png)
The failure then triggers a popup window which you can select an account and then it gets the access_token (although my initial HTTP request will have already failed by that point :/

**Comment by randompixel** [comment] 2019-07-01 13:53
It feels like whatever is calling the above URL is skipping out the `login_hint` field, even though I've specified it in MSAL based on the user obtained in the accessToken. If it passed that through then maybe it could know which one to pick and avoid the prompt?

**Comment by sameerag** [comment] 2019-07-01 19:38
@ChristianOlsson  @randompixel Can you please try this usecase with msal 1.0.x and let us know if the issues are still persistent?

**Comment by randompixel** [comment] 2019-07-01 19:40
Hi @sameerag - I'm using MSAL 1.0.2

**Comment by sameerag** [comment] 2019-07-01 19:49
@randompixel So Is this issue specific to the case when multiple google accounts are logged in? You are sending the login_hint in msal js but unable to distinguish between the google accounts? 

I can notify the B2C Server team to check how they would like to distinguish this and why they are not considering the login_hint set by the user, but I want to confirm my understanding above is correct.

**Comment by randompixel** [comment] 2019-07-01 19:55
@sameerag - yes. I have a personal and work gmail account logged in. When I try and log in with AAD B2C, I select the work account. It gives me an idToken but when I try and get an accessToken it fails and tries to obtain another login (acquireTokenPopup). Once it has done this I do appear to get a token - however it's not how it should be working! I'm sending both login and domain hints in the request and I can see them in the logger, but when it redirects to Google to get the token they're no longer there. If I call the Google URL manually and add in the login_hint to the query string then it redirects to my app successfully without showing the account selector (which has the no iframe policy on it).

**Comment by sameerag** [comment] 2019-07-01 20:55
Thank you @randompixel for the information. I am tagging this as B2C Service issue and will follow up on why the hints are ignored.

**Comment by DarylThayil** [comment] 2019-07-25 22:34
Unfortunately B2C does not support this at this time #756 
Their team is investigating this, but please leave feedback on their [user voice page](https://feedback.azure.com/forums/169401-azure-active-directory/category/160596-b2c)

**Comment by randompixel** [comment] 2019-08-06 11:07
Hey @DarylThayil - I'm not sure this is the same as #756. We don't want any prompts to appear. I think this is more related to #741 where multiple logged in Microsoft accounts fail to get tokens silently too.

**Comment by DarylThayil** [comment] 2019-08-07 18:00
reopening to investigate further!

**Comment by JasSuri** [comment] 2019-08-13 08:21
Please try this with AAD B2C Custom policies.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-custom-setup-goog-idp

Follow the following to allow domain_hint parameter to work for your chosen IdP by adding the <domain> element. Make sure to send the domain_hint parameter in the request with msal.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/direct-signin

Then in the IdP technical profile, add this:
```xml
<InputClaims>
   <InputClaim ClaimTypeReferenceId="signInName" PartnerClaimType="login_hint" DefaultValue="{OIDC:LoginHint}"/>
</InputClaims>
```

That will send the login_hint parameter from the request to B2C to the downstream federated IdP.

I am slightly confused at this issue however, since on acquireTokenSilent(), B2C should be relying on the B2C session cookie, and only if that cookie has expired to send you to the downstream IdP to re-auth. Only then would you get the issue with the iFrame. Are you already sending the domain_hint parameter? Maybe that is the cause in itself.

**Comment by randompixel** [comment] 2019-08-13 08:21
Definitely not sending domain_hint. Will have a go at the above, thanks :)

**Comment by sameerag** [comment] 2019-08-13 18:27
@ktsakas FYI.

**Comment by randompixel** [comment] 2019-08-21 15:55
@JasSuri I think this has helped. Getting a weird issue where the Node server is throwing a 400 because the cookies are too long now, but if I can reproduce consistently I'll file another bug. Thanks.

**Comment by zawor** [comment] 2019-09-05 14:02
@JasSuri's way with custom policy solved issue... but it is mightily strange that we hit b2c every time when `acquireTokenSilent` is invoked :P

**Comment by sameerag** [comment] 2019-10-02 22:26
@ktsakas 's team is addressing this issue in their backlog this quarter. Closing this as MSAL JS does not have any open action item.

**Closed by sameerag** 2019-10-02 22:26 UTC
Labels: B2C, B2CService, Feature Request

**Comment by JasSuri** [comment] 2019-10-03 08:33
@zawor  I confirmed and B2C does go to the downstream IdP on every silent token call to make sure that the user still has a session at that IdP, there we use the IdPs session cookie to get SSO.

**Comment by zawor** [comment] 2019-10-03 08:36
sounds fair

**Comment by rakragh** [comment] 2019-12-23 21:49
@ktsakas Any news about this?
