### ISSUE TITLE
Error throws when creating msal instance at a third party cookie disabled broswer

### ISSUE THREAD

**Issue by XingyangHuang** [AzureAD/microsoft-authentication-library-for-js#2166] opened 2020-08-19 20:33 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
"@azure/msal-browser": "2.0.0-beta.4",
"msal": "1.3.0",

## Framework
TypeScript/ JavaScript

## Description
This error Happens when:
1. I have a page A running JavaScript call to create a msal instance
2. I have another page B running in a different domain, and trying to put page A inside a iframe
3. Third party cookie has been disabled by browser
I get error throws from the msal package like the Window.sessionStorage is not accessible:
(error from @azure/msal-browser": "2.0.0-beta.4)
![image](https://user-images.githubusercontent.com/69926459/90686154-cbd7c300-e21f-11ea-8686-9d3999bdfe2d.png)

(error from msal 1.3.0)
![image](https://user-images.githubusercontent.com/69926459/90686479-3ab51c00-e220-11ea-801b-c0998ddfeb30.png)

## Error Message
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at BrowserStorage

## Browsers/Environment
- [x] Chrome icongnito when third party cookie disabled
maybe all browser when third party cooked are disabled, it looks like an general problem.

**Comment by technical-boy** [comment] 2020-08-25 16:45
Hi @XingyangHuang . We're unable to reproduce this with Chrome in an Incognito window with third-party cookies disabled. Do you have any additional privacy settings enabled that would prevent access to sessionStorage?

MSAL requires either localStorage or sessionStorage, but we are looking into allowing application to [provide custom storage options](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2060) which would be available in future versions of msal-browser.

**Comment by XingyangHuang** [comment] 2020-08-25 17:47
Hi,
I don't have special additional privacy setting for the sessionStorage.
Did you tried that with Iframe a page which in a different domain? 
For me the error can be reproduce like:
1. first page in domain a, have msal running,
2, second page in domain b, private window, third-party cookie disabled, have page a running in its iframe.

I would suggest that if you can have the try-catch around whenever the window is trying to access sessionStorage/ localStorage, in this case the msal won't throw in that case...

**Comment by technical-boy** [comment] 2020-08-31 18:21
@XingyangHuang could you provide the version of Chrome that you are using? Thanks!

**Comment by XingyangHuang** [comment] 2020-09-03 17:43
@technical-boy  we are using version 84.0.4147.125 (Official Build) (64-bit).
Thanks.

**Comment by XingyangHuang** [comment] 2020-09-03 17:44
@dsm0880 the current solution for us is to get a try-catch around when trying to creating the msal incident so we won't throw... but for totally fix it should requires the msal code change..

**Comment by dsm0880** [comment] 2020-09-03 18:03
@XingyangHuang What do you do instead when the error is caught? The error is coming within MSAL, do you branch their code and deal with the try catch directly inside MSAL? If not and you are catching the error and handling in your code, what are you doing to handle?

**Comment by XingyangHuang** [comment] 2020-09-03 20:28
@dsm0880 not, we just using the try/catch over our code when trying to create msal indecent, and return undefined if it is not able to be created

**Comment by jasonnutter** [comment] 2020-09-03 20:32
Thanks for the information, we're on fixing this, should be available in next version of MSAL.js v2.

**Comment by kwilkins** [comment] 2020-09-04 20:36
Thanks for the update @jasonnutter! Can you confirm if the fix you mentioned will cover both SessionStorage and LocalStorage options if they are blocked with a `Access is denied for this document` error?

**Comment by jasonnutter** [comment] 2020-09-04 20:46
> Thanks for the update @jasonnutter! Can you confirm if the fix you mentioned will cover both SessionStorage and LocalStorage options if they are blocked with a `Access is denied for this document` error?

Yes.

**Comment by kwilkins** [comment] 2020-10-20 16:05
Is there a new ETA on the fix getting merged in for release?

**Closed** 2020-10-28 23:03 UTC
Labels: bug, msal-browser, work-in-progress
