### ISSUE TITLE
Library is not working in ios device safari browser, after authentication, broadcast service is not triggering login success

### ISSUE THREAD

**Issue by bks1242** [AzureAD/microsoft-authentication-library-for-js#2449] opened 2020-10-19 06:54 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment] 2020-10-19 16:41
It is a known issue that MSAL Angular v1 will not work when third-party cookies are disabled, such as in Safari with ITP enabled. We are working on MSAL Angular v2, which will address problems caused by third-party cookie blocking in most scenarios.

Closing as duplicate of #2042

**Closed by jasonnutter** 2020-10-19 16:41 UTC
Labels: bug

**Comment by bks1242** [comment] 2020-10-20 04:24
Hi ,

I am using angular 9, how & from where to get MSAL.Js 2.0 ?
can you pls guide me?


Thanks!
Babloo Kumar
