### ISSUE TITLE
Identity Provider Google: Refused to display 'https://accounts.google.com' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by kumarunster** [AzureAD/microsoft-authentication-library-for-js#965] opened 2019-09-02 16:03 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 76.0.3809
- [ ] Firefox version
- [ ] IE version 
- [ ] Edge version 
- [ ] Safari version 

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

Using third party identity provider, like Google is not possible within MSAL for js. Google responses with header set to ´x-frame-options: SAMEORIGIN`. MSAL cannot load the iframe and access to the identity data.

This issue was already reported [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/177) but the corresponded issue and [stackoverflow question](https://stackoverflow.com/questions/47163384/msal-js-iframe-issue-with-twitter-and-while-choosing-from-multiple-google-accoun) remains unanswered.

## Expected behavior

MSAL should support third party identity providers from Azure (Google, Twitter, LinkedIn, etc)

Any suggestions, or official statement regarding usage of third party B2C identity providers in azure with this library, which seems to be an official way to integrate with Azure Active Directory?

## Minimal reproduction of the problem with instructions

Configure B2C tenant and use https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp example (btw outdated link to msal library)

**Comment by sameerag** [comment] 2019-09-03 04:23
@ktsakas FYI.

**Comment by kumarunster** [comment] 2019-09-03 08:52
I was able to make it working locally by modifying one line in UserAgentApplication:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2de03e0818346993bdcdbcf0bb5cee7aeb56d8e0/lib/msal-
core/src/UserAgentApplication.ts#L497

```typescript
//const responseType = isLoginCall ? ResponseTypes.id_token : this.getTokenType(account, scopes, false);
const responseType = ResponseTypes.id_token_token; 
```

`ResponseTypes.id_token_token` does the trick, thanks to @sushi4u for the hint [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/177#issuecomment-370247624)

is it possible to specify the default response type via configuration?

any comment from maintainers?

**Comment by sk2andy** [comment] 2019-09-07 11:50
@kumarunster that's not working for me when writing the following because loginRedirect is not returning a promise (at least my console says so):
```
this.msalInstance.loginRedirect().then((loginResponse) => {
                this.AcquireToken(); // my function that tries to acquire a token
                resolve(loginResponse);
            }).catch((error) => {  
                console.error(error);  
                reject(error);
            });  
```
Could you provide me your code how do you call the `loginRedirect` or even share your msal.js? That would be great!

**Comment by kumarunster** [comment] 2019-09-09 11:25
Hi Andre,

I can't see your message anymore. did you found the code place to tweak?

Best regards,

Nikolai


Am Sa., 7. Sept. 2019 um 13:50 Uhr schrieb André Naumann <
notifications@github.com>:

**Comment by sk2andy** [comment] 2019-09-09 14:43
Hi Nikolai,

yes. Meny thanks for your help. I forked the repo and fixed it.

Cheers

Am Mo., 9. Sept. 2019 um 13:25 Uhr schrieb Nikolai Raitsev <
notifications@github.com>:

**Comment by sameerag** [comment] 2019-09-19 18:25
@kumarunster Can you share us the sample to repro this? We are curious why editing the response_type is solving this issue.

**Comment by kumarunster** [comment] 2019-10-01 21:06
@sameerag sorry, I cannot provide an easy to go reproducer, because it requries setup on google and azure. But for me is clear, why response_type set to id_token_token solves the issue: it is because the tokens are retrieved in one call.

**Comment by WretchedDade** [comment] 2020-01-06 04:27
I am still getting this issue and it is unclear how to resolve it/work around it. Any suggestions?

**Comment by kumarunster** [comment] 2020-01-06 12:20
@WretchedDade did you checked the [workaround](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/965#issuecomment-527368096) i posted a while ago?

**Comment by sk2andy** [comment] 2020-01-06 21:33
@WretchedDade according to the workaround of @kumarunster I did the following:
![image](https://user-images.githubusercontent.com/5347673/71850381-73124a80-30d4-11ea-8303-a98836f17fea.png)

Hope that helps

**Comment by WretchedDade** [comment] 2020-01-06 22:36
@kumarunster @sk2andy is there no way to resolve this without modifying the source code?

**Comment by sameerag** [comment] 2020-01-07 00:48
@kumarunster Can you please test this with `msal@1.2.0` without the tweak and let us know if the bug still exists?

**Comment by kumarunster** [comment] 2020-01-07 09:50
@sameerag thanks for your comment, could you please point us to some release notes or commit that fixes that issue? I believe that @WretchedDade is already on msal@1.2.0, isn't?

**Comment by WretchedDade** [comment] 2020-01-07 13:23
@kumarunster is correct, I am already using msal@1.2.0 without the tweak.

**Comment by Nasicus** [comment] 2020-01-21 20:57
The same happens to me with my google login at our app. It doesn't even help to clear the local storage (of "my site"), in an anonymous / private window it works.

**Comment by WretchedDade** [comment] 2020-01-28 17:11
@sameerag Any update?

**Comment by sameerag** [comment] 2020-01-30 18:01
Couple of things here:

- Google accounts are accessible with B2C with our current sample [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) - the existing issue is only with multiple google accounts, and it is a bug with the B2C Service. When there are two active google accounts logged in, `msal js` sends `prompt=select_account` to the service for the user to be able to select the appropriate account but the B2C service is swallowing that. It is in their pipeline to address this issue. cc @ktsakas.

- `response_type` is set by the library and not by the user by design. If a user is logging in for the first time, we set it to id_token; based on the cache state and any hint sent to us about an existing session, we set it to id_token_token. We advise the users not to modify this as this may cause performance issues fetching two tokens in all use cases when you do not need it. It also may cause issues in older browsers like IE which is tracked with #1172 

- The reason why this workaround seemed to work in some use cases is that it is tying up the `id_token` and `token` for a given call but for the reasons mentioned above and the lack of support code around,  I am unsure if this works in all scenarios.

I will have our b2c dev take a look at this `sameorigin` bug again and will update when we have more info.

**Comment by WretchedDade** [comment] 2020-01-30 22:17
@sameerag thanks for the follow up. I am signed in to multiple google accounts. I'll log out of all but one and see if that resolves my issue!

**Comment by sameerag** [comment] 2020-02-04 19:19
Any update @WretchedDade? 
@ktsakas  Can we debug this sometime?

**Comment by WretchedDade** [comment] 2020-02-04 20:02
I can confirm my issue is related to multiple google accounts being signed in.

**Comment by sameerag** [comment] 2020-02-04 21:20
Great! Thanks, As mentioned, this is work-in-progress with B2C service tracked with #842. Can I close this issue?

**Comment by sameerag** [comment] 2020-02-06 08:25
Closing this. Please track the original issue with #842.

**Closed by sameerag** 2020-02-06 08:25 UTC
Labels: b2c, bug, more-information-needed
