### ISSUE TITLE
'MsalModule' does not appear to be an NgModule class

### ISSUE THREAD

**Issue by johnvinosh** [AzureAD/microsoft-authentication-library-for-js#5336] opened 2022-10-26 06:43 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.5

### Public or Confidential Client?

Public

### Description

![image](https://user-images.githubusercontent.com/26540475/197953238-69e923a0-3f3f-4c47-ae1d-f0c18ba8bf8f.png)

I am getting this compile time error when I import MsalModule

### Error Message

'MsalModule' does not appear to be an NgModule class.(-996002)
msal.module.d.ts(7, 19): This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### MSAL Configuration

```javascript
auth: {
    clientId: '',
    authority: '',
    navigateToLoginRequestUrl: true,
    redirectUri: '',
  },
```

### Relevant Code Snippets

```javascript
@NgModule({
  imports: [
    MsalModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

### Reproduction Steps

Just import MsalModule

### Expected Behavior

No compile Time error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by bmahall** [comment] 2022-10-26 21:22
@johnvinosh Thanks for opening this issue, it is currently being tracked in #4298 . You can find the [Roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md) here. 

Can you include the Angular version you are using as well?

**Comment by bmahall** [comment] 2022-11-02 03:28
@johnvinosh Closing this as duplicate of #4298.

**Closed as completed by bmahall** 2022-11-02 03:28 UTC
Labels: question, msal-angular, msal-browser, no-issue-activity, bug-unconfirmed, public-client

**Comment by spock123** [comment] 2022-12-29 18:18
I can add that I have this issue with Angular v15.0.4, using EsBuild. 
It works fine with the standard builder.

Thanks

**Comment by SGeorge007** [comment] 2023-01-12 02:57
I can confirm too , the issue is there with angular v14

**Comment by kenstanley37** [comment] 2023-05-11 19:05
Same issue with Angular v16

**Comment by SebastianBaiju** [comment] 2023-05-15 05:51
yes it is in the angular v16

**Comment by dansau84** [comment] 2023-05-19 23:59
where is the solution ???? why too long for this or temporary workaround ?

**Comment by Taats** [comment] 2023-05-24 07:16
look here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4298
