### ISSUE TITLE
ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.

### ISSUE THREAD

**Issue by hardik-codiste** [AzureAD/microsoft-authentication-library-for-js#6215] opened 2023-07-06 12:22 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

1.18.0

### Public or Confidential Client?

Public

### Description

sending all required data still facing error pls 

followed this 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/auth-code-pkce/src/index.ts

example

### Error Message

ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.
    at ClientAuthError.AuthError [as constructor] (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:499:24)
    at new ClientAuthError (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:819:28)
    at ClientAuthError.createTokenRequestCannotBeMadeError (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:945:16)
    at AuthorizationCodeClient.<anonymous> (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:5718:51)
    at step (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
    at Object.next (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
    at /Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:53:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:49:12)
    at AuthorizationCodeClient.acquireToken (/Users/hardikkheni/Workspace/codiste/outbox/outbox-gpt-backend/node_modules/@azure/msal-common/dist/index.cjs.js:5711:16) {
  errorCode: 'request_cannot_be_made',
  errorMessage: 'Token request cannot be made without authorization code or refresh token.',
  subError: ''
}

### Msal Logs

![Screenshot 2023-07-06 at 5 50 29 PM](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/138784702/c957e66c-335f-4dee-bdce-cc8d409e9845)

### MSAL Configuration

```javascript
{
auth: {
    clientId: process.env.MSAL_CLIENT_ID,
    authority: `https://login.microsoftonline.com/common`,
    clientSecret: process.env.MSAL_CLIENT_SECRET,
  },
  scopes,
  system: {
    loggerOptions: {
      loggerCallback(loglevel, message, containsPii) {
        if (!containsPii) console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose,
    },
  },
}
```

### Relevant Code Snippets

```javascript
![Screenshot 2023-07-06 at 5 50 29 PM](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/138784702/c957e66c-335f-4dee-bdce-cc8d409e9845)
```

### Reproduction Steps

![Screenshot 2023-07-06 at 5 50 29 PM](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/138784702/c957e66c-335f-4dee-bdce-cc8d409e9845)

### Expected Behavior

shouldn't get the error  

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment] 2023-07-06 18:01
@hardik-codiste I am not able to reproduce this with the sample you mentioned. Are you using the sample as-is or did you make changes to it?

**Comment by hardik-codiste** [comment] 2023-07-07 08:29
![Screenshot 2023-07-07 at 1 57 33 PM](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/138784702/24e0fbbe-b28e-4c2d-bf06-81cddc41adcd)

now i am using same example just replaced.

clientId: "f502cef2-ac21-4670-b99c-6ef6e4e5058f",
authority: `https://login.microsoftonline.com/consumers`,
clientSecret: 'xxxxxxx'

**Comment by sameerag** [comment] 2023-07-07 13:29
@hardik-codiste `client-secrets` are confidential data and cannot be shared in public places. I have edited your comment accordingly.

@tnorling Guess we can try reproduction on our end with a newly minted one.

**Comment by hardik-codiste** [comment] 2023-07-07 14:06
it's happening because i was using PublicClientApplication in nodejs(express) is that was the issue? because using ConfidentialClientApplication fixed it.

**Comment by hardik-codiste** [comment] 2023-07-07 14:10
Question:

 i want to implement service where i can schedule an email on behalf of user, how can i implement it?, how can i manage access token expiration and refresh.
 
 also which authentication flow should i use?.
 
 auth-code
 on-belaf-of-user
 etc...
 
 there are lot of recourse and i am confuse now,

**Comment by tnorling** [comment] 2023-07-07 16:29
> @hardik-codiste `client-secrets` are confidential data and cannot be shared in public places. I have edited your comment accordingly.

@hardik-codiste Please be sure to revoke the secret as it will still be visible in the comment history.

> i want to implement service where i can schedule an email on behalf of user, how can i implement it?, how can i manage access token expiration and refresh.

MSAL will manage token lifetimes and refresh for you. All your application needs to do is invoke the acquireToken___ APIs when you need a token.

> also which authentication flow should i use?.

For this use case you should use the [on-behalf-of flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)

**Comment by hardik-codiste** [comment] 2023-07-08 11:14
@tnorling 
secret was already expired when i added to the comment. 

thanks for your replay.

**Comment by tnorling** [comment] 2023-07-10 16:40
Going ahead and closing this but let us know if you have further questions

**Closed as completed by tnorling** 2023-07-10 16:40 UTC
Labels: question, msal-node, bug-unconfirmed, public-client
