### ISSUE TITLE
BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.

### ISSUE THREAD

**Issue by Lakshman-Sundeep-Teki** [AzureAD/microsoft-authentication-library-for-js#6692] opened 2023-11-13 11:13 UTC
### Core Library

MSAL Angular v3 (@azure/msal or msal)

### Core Library Version

3.0.8

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I want to perform authentication when ever app was loaded in browser. To achieve that i was trying to user loginRedirect function in **`onInit()`**, But i am facing the below error.
**`ERROR Error: Uncaught (in promise): BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.`**

I tried many ways but i am not getting, is my way of implementation was wrong or any bug with this MSAL
Is there any way to perform authentication in the application without user input or click

### MSAL Configuration

```javascript
auth: {
      clientId: environment.msalConfig.auth.clientId,
      authority: environment.msalConfig.auth.authority,
      redirectUri: window.location.origin,
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
```

### Relevant Code Snippets

```javascript
app.component.ts

import { AfterViewInit, Component, Inject, OnDestroy, OnInit } from '@angular/core';
import { MSAL_GUARD_CONFIG, MsalBroadcastService, MsalGuardConfiguration, MsalService } from '@azure/msal-angular';
import { InteractionStatus } from '@azure/msal-browser';
import { Subject, filter, takeUntil } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, AfterViewInit, OnDestroy{
  title = 'sso-poc';
  loginDisplay = false;
  private readonly _destroying$ = new Subject<void>();
  constructor(private msalBroadcastService: MsalBroadcastService ,private authService: MsalService) {}
  ngOnDestroy(): void {
    this._destroying$.next(undefined);
    this._destroying$.complete();
  }
  ngAfterViewInit(): void {
   
  }
  //AD auth
  ngOnInit(): void {
    this.authService.loginRedirect();  
    this.setLoginDisplay();
      this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.setLoginDisplay();
        this.checkAndSetActiveAccount();
      })
  }

  checkAndSetActiveAccount(){
    /**
     * If no active account set but there are accounts signed in, sets first account to active account
     * To use active account set here, subscribe to inProgress$ first in your component
     * Note: Basic usage demonstrated. Your app may require more complicated account selection logic
     */
    let activeAccount = this.authService.instance.getActiveAccount();

    if (!activeAccount && this.authService.instance.getAllAccounts().length > 0) {
      let accounts = this.authService.instance.getAllAccounts();
      this.authService.instance.setActiveAccount(accounts[0]);
    }
  }


  loginRedirect() {
    this.authService.loginRedirect()
  }

  setLoginDisplay() {
    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;
  }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment] 2023-11-13 19:33
Duplicate of #6693. Closing.

**Closed as completed by lalimasharda** 2023-11-13 19:33 UTC
Labels: question, msal-angular, public-client
