### ISSUE TITLE
Can not logout

### ISSUE THREAD

**Issue by mapennig** [AzureAD/microsoft-authentication-library-for-js#1265] opened 2020-02-05 09:03 UTC
## Library
- [x ] `msal@1.2.1` 

## Framework
Vanilla JS

## Description
When you use the logout method it calls the Azure B2C logout endpoint, but it doesn't set the client id as query parameter. You get redirected to your application but it doesn't log you out.

## Security
Is this issue security related?
Yes

## Regression
Did this behavior work before?
No
## Configuration
MSAL Example Configuration

## Reproduction steps
1.  Download the MSAL example
2.  Try to logout

## Expected behavior
Logout from the service

## Browsers
No

**Comment by jasonnutter** [comment] 2020-02-05 21:30
This appears to be a duplicate of #1235, closing.

**Closed by jasonnutter** 2020-02-05 21:30 UTC
Labels: bug
