### ISSUE TITLE
getAccount in @azure/msal-browser": "^2.0.0"

### ISSUE THREAD

**Issue by dglozano** [AzureAD/microsoft-authentication-library-for-js#2196] opened 2020-08-26 11:25 UTC
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

In the version 2.x.x of the msal-browser library,  `getAccount()` was removed. In issue #1843 it was mentioned that we can ensure that at any moment there is only one logged in user in our application by doing this: 

> If you want to ensure your application is always a single account application, you can do that yourself by ensuring you
> don't present a sign-in screen after the initial login.
> 

If I understand correctly, this is not always possible to ensure by just not presenting the sign-in screen after the initial login in my application. For example, if I use my admin Azure AD user to login to portal.azure.com and then I go to my own application and try to log in with my personal user from AD, MSAL.js will keep track of both accounts, even though one of the logins didn't happen in my own application, it happened in azure portal. Is that right?

Is there any piece of documentation on how to achieve the same single account behavior that we had in MSAL v1 using loginPopup?

I agree with @jrmcdona that it would be nice if MSAL provided an API to keep track of an user session, as it did before. For us, is a stopper for going to v2.x.x

**Comment by technical-boy** [comment] 2020-08-26 16:45
Hi @dglozano!
 
>For example, if I use my admin Azure AD user to login to portal.azure.com and then I go to my own application and try to log in with my personal user from AD, MSAL.js will keep track of both accounts, even though one of the logins didn't happen in my own application, it happened in azure portal. Is that right?

No, an instance of MSAL JS will only keep track of accounts for the application that it is used in. The `getAllAccounts` API will return all of the currently active accounts for your application, and if you are confident that there's only one account you can use the first account from the returned array.

You can find more details about the account APIs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#account-apis). 

Would this approach work for your scenario?

**Comment by dglozano** [comment] 2020-08-27 06:36
Thanks for the quick response @technical-boy 👍 

I think I have tested it, but I believe in this specific scenario it's not working as expected. Isn't it related to the SSO functionalities?

From  ([MSAL SSO Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso))
> Single Sign-On (SSO) enables users to enter their credentials once to sign in and establish a session which can be reused across multiple applications without requiring to authenticate again. This provides a seamless experience to the user and reduces the repeated prompts for credentials.
> 
> Azure AD provides SSO capabilities to applications by setting a session cookie when the user authenticates the first time. The MSAL.js library allows applications to leverage this in a few ways.

Further down in the docs ([MSAL SSO - Applications on different domain](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#applications-on-different-domain))

> When applications are hosted on different domains, the tokens cached on domain A cannot be accessed by MSAL.js in domain B.

> This means that when users signed in on domain A navigate to an application on domain B, they will be redirected or prompted with the Azure AD page. Since Azure AD still has the user session cookie, it will sign in the user and they will not have to re-enter the credentials. If the user has multiple user accounts in session with Azure AD, the user will be prompted to pick the relevant account to sign in with.


So if I have two different applications, both using the same tenant in Azure AD for authentication, and a user logs into one of them, when he/she tries to log in to the second application MSAL will show in the pop up that he is already signed in, so doesn't need to enter the password again. Same thing if you login to Azure portal since it is, again, the same tenant. 

I can double check again if you want, I remember I tested it some time ago, but I might have been using an older version of the library or something.

In any case,  IMHO I believe that it would be a great feature if in some time in the future MSAL provided the functionality to track the last user that logged in out of the box, as it did in the previous versions 😄

**Comment by jrmcdona** [comment] 2020-08-27 10:43
@dglozano tracking last user that signed in works very easy with localStorage or cookie..  I wouldn't let it stop you from moving to auth code flow.

**Comment by dglozano** [comment] 2020-08-31 07:05
@jrmcdona yes, but for now it's not prioritized, so it's easier to just stay in version 1.x.x until we find time to make the change 😅

**Comment by jrmcdona** [comment] 2020-08-31 12:18
@dglozano I already moved to 2.1 tho.   And it was easy to do so,  like I said in my last post.    So I would not recommend staying in 1.x.x if somebody needs to move away from implicit flow.

**Comment by technical-boy** [comment] 2020-08-31 18:04
Hi @dglozano .

>So if I have two different applications, both using the same tenant in Azure AD for authentication, and a user logs into one of them, when he/she tries to log in to the second application MSAL will show in the pop up that he is already signed in, so doesn't need to enter the password again. Same thing if you login to Azure portal since it is, again, the same tenant. In all those cases, won't getAllAccounts return more than just one user?

MSAL generates the account info based on the ID Token and client_info returned from the server for a given client application. This happens when the login request is completed, so `getAllAccounts` will only return a single account on the first request. When you complete a login request for a second account on **the same client application**, you'll have multiple account object in the cache for that client application.

For example, if User One logs into App A, `getAllAccounts` for App A will only return one account (User One's). If User Two logs into App B, `getAllAccounts` for App A will still only return one account (User One's). Then if User Two logs into App A, `getAllAccounts` for App A will return multiple accounts (User One and Two's). 

Let us know if this clears it up! Thanks.

**Comment by deasems** [comment] 2020-09-01 06:34
> Then if User Two logs into App A, getAllAccounts for App A will return multiple accounts (User One and Two's).

@technical-boy Is there a guaranteed order to the `getAllAccounts` array? In this scenario, what would the order would user one and two be in in this array?

I'd like to agree that having support for a 'single user mode' would be very convenient (and I think would be the common case given apps need to implement extra UI for multi-user scenarios).

**Comment by dglozano** [comment] 2020-09-02 10:10
@technical-boy Thanks for the detailed explanation😄

Now if the behaviour is as you describe, then I think I am not understanding how does the SSO support plays out in that scenario. When User Two logs into App A, will he/she need to enter his/her credentials again?

**Comment by pkanher617** [comment] 2020-09-09 18:15
@deasems I'm not sure I understand what you are trying to do here. Our docs on the account management need to be greatly improved, so this is probably the source of confusion here...

> Is there a guaranteed order to the getAllAccounts array? In this scenario, what order would user one and two be in in this array?

The array is unordered - you will have zero or more objects with unique homeAccountIds. 

> I'd like to agree that having support for a 'single user mode' would be very convenient (and I think would be the common case given apps need to implement extra UI for multi-user scenarios).

Our decision to not include a single-user mode was made because ideally developers should be managing the accounts that are signing into their application. We return the account that successfully completed the request in the [response object](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#response) returned by any of the `login` or `acquireToken` APIs. If you just need to keep track of single user, you can use the account returned from this object only. This account object will have associated `homeAccountId` or `username` properties that you can keep track of in your application, and then use the `getAccountByUsername` or `getAccountByHomeId` APIs to retrieve the rest of the information about the account.

> If I understand correctly, this is not always possible to ensure by just not presenting the sign-in screen after the initial login in my application.

This is absolutely possible. If you call `getAllAccounts` and the length of the array is > 0, then you are in a logged in state and you, as the app developer, can prevent the user from signing into your application with a different account. Preventing the user from signing in with a different account just means that the user cannot directly invoke loginRedirect, loginPopup, acquireTokenRedirect, or acquireTokenPopup. 

To reiterate what @technical-boy mentioned above: if you have App A and App B, you most likely have two different PublicClientApplication objects in your code (we will call them `pca1` and `pca2`). If the same user signs into App A (interactive login API on `pca1`) and App B (interactive login API on `pca2`) then calling `getAllAccounts` on either `pca1` or `pca2` will return only a *single account*. If a new user signs into App A (interactive login API on `pca1`), then `pca1.getAllAccounts()` will return an array with *two accounts*. `pca2.getAllAccounts()` will still return an array with a *single account*.

Hope this clears things up. If you have further questions you can also email me (email is on my profile).

**Comment by deasems** [comment] 2020-09-10 18:51
Thanks for the info @pkanher617. 

The expected behavior in my app is that the user that signed in most recently is the account that will be used in my app (this isn't really an explicit requirement, rather just maintaining the behavior from pre-v2). I'm interested in the specifics of MSAL's account APIs because it seems in this multi-user world it's technically possible to not select the most recent signed in account. 

The scenario I see this inadvertently happening in is when resuming an existing session (which we'd like to do as much as possible for perf). In this scenario I'd call `getAllAccounts` and if length > 0, choose the first entry. Now if the order of the returned array isn't guaranteed then it seems possible to get any old account. 

Now of course we can track accounts used in our app and add logic to ensure we choose the right account, that just increases the effort needed to adopt v2 and I can imagine it's easy to get that wrong, hence I see value in a `getAccount` api.

**Comment by jrmcdona** [comment] 2020-09-10 19:16
@deasems it is actually quite simple to track the latest user.  I, like you, at first was trying to fight it.  Then once I did it, I realized how easy it was.  I have done it for two sites and it works fine.    Very little extra effort was needed there.

**Comment by jrmcdona** [comment] 2020-09-10 19:22
mentioned that two weeks ago and certainly could have been done by then ;)

**Comment by jmckennon** [comment] 2020-09-28 21:11
Closing this as we're assuming the original question has been answered. Please open a new issue if you have further questions. Thanks!

**Closed by jmckennon** 2020-09-28 21:11 UTC
Labels: feature, msal-browser
