### ISSUE TITLE
ConfidentialClientApplication.acquireTokenOnBehalfOf() undefined scenarios

### ISSUE THREAD

**Issue by harryhtet8** [AzureAD/microsoft-authentication-library-for-js#4606] opened 2022-03-16 18:58 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

From @azure/msal-node, I am initializing `ConfidentialClientApplication` and later calling `let response = await this.cca.acquireTokenOnBehalfOf(oboRequest)`. From time to time, when I try to access `accessToken `from `response`, it is empty or undefined. Is this a known issue? Otherwise, what scenarios can return empty or undefined `accessToken` from `acquireTokenOnBehalfOf()`? Any help would be appreciated

### MSAL Configuration

```javascript
this.cca = new ConfidentialClientApplication({
                auth: {
                    clientId: *******,
                    authority: 'https://login.microsoftonline.com/' + *******,
                    clientSecret: *******                   
                }
            });
    }
```

### Relevant Code Snippets

```javascript
const oboRequest = {
            oboAssertion: *****,
            scopes: *****,
            correlationId: *****,
            skipCache: true                      
        } as OnBehalfOfRequest;

let response = await this.cca.acquireTokenOnBehalfOf(oboRequest);
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment] 2022-03-17 11:09
Hi @iron-man14, thank you for reaching out about this. Could you share the general structure of the response, in the cases where the access token has been empty when returned?

**Comment by harryhtet8** [comment] 2022-03-17 17:51
I am not able to repro this issue and we do not store the response object of the accessToken, so we do not know what is returned for the response. However, after tracing the code, it is possible that the accessToken is empty when it is returned from response, but I cannot validate that since we do not store the response object, so I am wondering if there are scenarios where accessToken might be returned as empty?

**Comment by samuelkubai** [comment] 2022-03-21 13:46
For successful authentication flows, there's no scenario where the access token would be empty.

Have you seen a reoccurrence of this issue, since you raised this Github issue?

**Comment by harryhtet8** [comment] 2022-03-31 16:36
I have not seen the issue again for a while but in our telemetry, we did not detect that issue for the whole month of February, but started seeing the issue again in March. For now, we have added additional telemetry to help us make further analysis on this issue.

**Comment by sameerag** [comment] 2022-04-01 17:27
Thanks. Closing this, please raise a new issue if you have reproduced it and with telemetry preferably to us.

**Closed as completed by sameerag** 2022-04-01 17:27 UTC
Labels: question, msal-node
