### ISSUE TITLE
Getting a generic network error from `acquireOnBehalfOf`

### ISSUE THREAD

**Issue by itstaby** [AzureAD/microsoft-authentication-library-for-js#5260] opened 2022-10-03 05:47 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.12.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I have an MS Teams app which is using Graph API to fetch data.
I first use the incremental consent flow detailed [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-user-consent) to get an AAD token with the permissions I require to make a Graph API call.

I'm then using the `acquireOnBehalfOf` method to exchange the AAD token for a Graph API token.
I tested this flow in our dev and staging environments and I was able to perform a successful token exchange and Graph API calls. 

However,  on our production environment, I'm receiving a very generic "Network Error" with status code 400 when trying to exchange tokens. It has no information on what the problem actually is and makes it difficult for us to debug and fix.
Please see the error message posted below.

### Error Message

```
subError: ''
errorMessage: 'Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/9eab1974-31cc-4aa8-8ba7-c8943c73f995/oauth2/v2.0/token',
errorCode: 'network_error',
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
at runMicrotasks (<anonymous>)
at rejected (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)
at Object.throw (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
at step (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
at NetworkManager.<anonymous> (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/src/network/NetworkManager.ts:44:39)
at Function.ClientAuthError.createNetworkError (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:259:16)
at new ClientAuthError (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:205:15)
at ClientAuthError.AuthError [as constructor] (/home/core/node_modules/@azure/msal-node/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)
error: ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/9eab1974-31cc-4aa8-8ba7-c8943c73f995/oauth2/v2.0/token
errorString: '{"errorCode":"network_error","errorMessage":"Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/9eab1974-31cc-4aa8-8ba7-c8943c73f995/oauth2/v2.0/token","subError":"","name":"ClientAuthError"}',

```

### MSAL Configuration

```javascript
{
      auth: {
        clientId: appId,
        clientSecret: appPassword,
      },
}
```
```


### Relevant Code Snippets

```javascript
const msalClient = new msal.ConfidentialClientApplication({
      auth: {
        clientId: appId,
        clientSecret: appPassword,
      },
    });

    try {
      const result = await msalClient.acquireTokenOnBehalfOf({
        authority: `https://login.microsoftonline.com/${tenantId}`,
        oboAssertion: aadToken as string,
        scopes: this.userConsentedScopes,
      });

      return result.accessToken;
    } catch (error) {
      console.error({ errorString: JSON.stringify(error), error });
    }
```
```


### Reproduction Steps

Not Applicable. 
Doing a very basic token exchange, please see code snippet.

### Expected Behavior

Successful token exchange and subsequent Graph API calls.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

External (Customer)

**Comment by hectormmg** [comment] 2022-10-03 16:44
@itstaby thanks for raising the issue, however it seems to be a duplicate of #4878. I'm closing this one but please track #4878 for the fix.

**Closed as completed by hectormmg** 2022-10-03 16:44 UTC
Labels: question, msal-node, bug-unconfirmed, Needs: Author Feedback, confidential-client
