### ISSUE TITLE
msal-node acquireTokenSilent does not use cacheplugin

### ISSUE THREAD

**Issue by lasrol** [AzureAD/microsoft-authentication-library-for-js#5536] opened 2023-01-08 15:24 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

When running 'acquireTokenByCode' i see the cacheplugin is used and the data is stored as expected.

If i try to use 'acquireTokenSilent' after the cache has been set i would expect it to read the values from the cache and return the access token or renew with the refreshtoken.

I have added logging in my ICacheClient and IPartitionManager and it does not get called during 'acquireTokenSilent'

It seems to work when running 'acquireTokenByCode' and 'acquireTokenSilent' with the same ConfidentialClientApplication, i assume it uses some kind of in-memory storage and disregarding the CachePlugin defined.

### Error Message

```
SilentRenew Failed:  InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.                                                                      16:06:20
    at InteractionRequiredAuthError.AuthError [as constructor] (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:516:24)
    at new InteractionRequiredAuthError (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:4378:28)
    at Function.InteractionRequiredAuthError.createNoTokensFoundError (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:4401:16)
    at RefreshTokenClient.<anonymous> (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:6107:56)
    at step (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
    at Object.next (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
    at C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:53:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:49:12)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (C:\Dev\internal-admin\src\node_modules\@azure\msal-common\dist\index.cjs.js:6099:16) {
  errorCode: 'no_tokens_found',
  errorMessage: 'No refresh token found in the cache. Please sign-in.',
  subError: ''
}

```

### Msal Logs

[Sun, 08 Jan 2023 15:06:20 GMT] : @azure/msal-node@1.14.5 : Verbose - initializeRequestScopes called                                                                                          16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-node@1.14.5 : Verbose - buildOauthClientConfiguration called                                           16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-node@1.14.5 : Verbose - building oauth client configuration with the authority: https://b2c-url
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-node@1.14.5 : Verbose - createAuthority called                                                         16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : @azure/msal-node@1.14.5 : Verbose - Attempting to get cloud discovery metadata in the config                                                                16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : @azure/msal-node@1.14.5 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.                          16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : @azure/msal-node@1.14.5 : Verbose - Found cloud discovery metadata in the config.                                                                           16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-node@1.14.5 : Verbose - Silent flow client created                                                     16:06:20
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-common@9.0.1 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properti
es.
[Sun, 08 Jan 2023 15:06:20 GMT] : [3b8bf4cb-f4b0-487d-8acf-cd2ba4b08c1f] : @azure/msal-common@9.0.1 : Verbose - RefreshTokenClientAcquireTokenWithCachedRefreshToken called  

### MSAL Configuration

```javascript
{
        auth: {
            clientId: config.auth.clientId,
            authority: config.auth.authority,
            clientSecret: config.auth.clientSecret,
            knownAuthorities: [
                config.auth.authority
            ]
        } as NodeAuthOptions,
        cache: {
            cachePlugin: new DistributedCachePlugin(new MsalSessionCacheClient(session), new SessionPartitionManager(session)),
        },
        system: {
            loggerOptions: {
                loggerCallback(loglevel: any, message: string, containsPii: boolean) {
                    console.log(message);
                },
                piiLoggingEnabled: false,
                logLevel: LogLevel.Verbose,
            } as any
        } as NodeSystemOptions
    } as Configuration;
```

### Relevant Code Snippets

```javascript
//Request 1:
const response = await this._client.acquireTokenByCode({
            code: code,
            scopes: scopes,
            redirectUri: config.baseUrl + "/signin-oidc",
        } as AuthorizationCodeRequest)

//Request 2:
const response = await this._client.acquireTokenSilent({
            scopes: scopes,
            account: account
        });
```

### Reproduction Steps

1. AquireTokenByCode
2. Store the response with a custom CachePlugin (using DistributedCachePlugin, but with own implementation of CacheClient and PartitionManager)
3. Run aquireTokenSilent (cache does not get called)

### Expected Behavior

Expect the library to lookup the cache and return the cached response using the defined CachePlugin

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by derisen** [comment] 2023-01-09 18:41
@lasrol are you calling `getAccountBy*` to retrieve the account object before calling `acquireTokenSilent`? If not, can you try doing that? Also, can you enable Trace level logs in the config? Possibly a duplicate of #5502

**Closed as completed** 2023-01-22 13:00 UTC
Labels: question, b2c, msal-node, no-issue-activity, bug-unconfirmed, Needs: Author Feedback, confidential-client

**Comment by jiannx** [comment] 2024-10-29 13:18
> @lasrol are you calling `getAccountBy*` to retrieve the account object before calling `acquireTokenSilent`? If not, can you try doing that? Also, can you enable Trace level logs in the config? Possibly a duplicate of #5502

I have the same problem with @azure/msal-node @2.15.0，I call cca.getTokenCache().getAllAccounts before calling acquireTokenSilent and it works
