### ISSUE TITLE
'Keep me signed in' not available when redirect url is chrome-extension://xxxx

### ISSUE THREAD

**Issue by marty-wang** [AzureAD/microsoft-authentication-library-for-js#1621] opened 2020-05-09 23:36 UTC
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We are creating an edge extension using msal.js to authenticate users against AAD. For edge extension the redirect url is in such format chrome-extension://xxxx. I noticed that in such case the 'Keep me signed in' option is not longer available. However, if I just replaced the redirect_url segment in the url with https://xxxx, the 'Keep me signed in' option showed up. 

I am wondering if there is something that I should do to enable KMSI, or it is a bug/limitation on the msal/AAD side.

Thanks.

**Comment by hpsin** [comment] 2020-05-12 21:18
This is expected behavior at this time for AAD.  Non-HTTP(S) redirect URIs at this time indicate to the login server that the request is going to a native application or otherwise embedded app, and therefore there's no reason to keep the session around.  

In your scenario this is not desirable, of course, since you are inside a browser and would like the session to stick around.  This limitation has cropped up as well in native apps using the system webview/system browser on Windows/Android/iOS as well, so we're looking at was to improve our detection of these browser scenarios.  I don't have any estimates on if or when that will be possible however.

**Comment by marty-wang** [comment] 2020-05-12 23:24
Thanks for the reply.

**Comment by marty-wang** [comment] 2020-05-13 01:27
@hpsin just out of curiosity, since chrome-extension:// protocol is clearly the browser scenario, specially now given that edge browser uses the same protocol, lots of microsoft 1st party extension will suffer this problem, is it possible to expedite it just for chrome-extension:// protocol?

**Comment by tnorling** [comment] 2020-05-27 21:19
Closing as no further action needed by msal

**Closed by tnorling** 2020-05-27 21:19 UTC
Labels: no-issue-activity, question
