### ISSUE TITLE
Multiple tokens in cache but same claims

### ISSUE THREAD

**Issue by pixeldrew** [AzureAD/microsoft-authentication-library-for-js#6425] opened 2023-09-04 14:40 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

While using a CachePlugin that implements a distributed cache using Mongo (following the example [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/auth-code-distributed-cache/src/middleware.ts)), that segments the cache based on homeaccount id. There is an OIDC token claim made as part of login.

After adding in claim request where we fetch 2 access tokens (graph and scoped access token) in the same event cycle, we're seeing an error 

This seems only affect the claims being passed back from the graph token. 

### Error Message

"multiple_matching_tokens": the cache contains multiple tokens satisfying the requirements. 

### Msal Logs

JSON cache (looks like the scope target is out of order):
```json
"9b109d69-e09e-46b5-83de-844311fb828b.XXXX-login.windows.net-accesstoken-XXXX-XXXX-user.read profile openid email--": {
      "home_account_id": "9b109d69-e09e-46b5-83de-844311fb828b.XXXX",
      "environment": "login.windows.net",
      "credential_type": "AccessToken",
      "client_id": "XXXX",
      "secret": "XXXX",
      "realm": "XXXX",
      "target": "User.Read profile openid email",
      "cached_at": "1693700315",
      "expires_on": "1693705213",
      "extended_expires_on": "1693710112",
      "token_type": "Bearer"
    },
    "9b109d69-e09e-46b5-83de-844311fb828b.XXXX-login.windows.net-accesstoken-XXXX-XXXX-profile openid email user.read--": {
      "home_account_id": "9b109d69-e09e-46b5-83de-844311fb828b.XXXX",
      "environment": "login.windows.net",
      "credential_type": "AccessToken",
      "client_id": "XXXX",
      "secret": "XXXX",
      "realm": "XXXX",
      "target": "profile openid email User.Read",
      "cached_at": "1693662534",
      "expires_on": "1693666342",
      "extended_expires_on": "1693670151",
      "token_type": "Bearer"
    }
```

### MSAL Configuration

```javascript
const msalConfig = {
      auth: {
        clientId: authConfig.clientId,
        authority: `${authConfig.instance}/${authConfig.tenantId}`,
        clientSecret: authConfig.clientSecret,
      },
      system: {
        tokenRenewalOffsetSeconds: authConfig.tokenRenewalOffsetSeconds,
        loggerOptions: {
          loggerCallback(loglevel, message) {
            console.log(message);
          },
          logLevel: isNaN(parseInt(process.env.MSAL_LOG_LEVEL, 10)) ? LogLevel.Error : parseInt(process.env.MSAL_LOG_LEVEL, 10),
          piiLoggingEnabled: false,
        },
      },
    } as Configuration;
```

### Relevant Code Snippets

```javascript
async getTokenSilent(
    silentRequest: SilentFlowRequest,
    sessionId: string
  ): Promise<AuthenticationResult | null> {
    const msalInstance = this.getMsalInstance(sessionId);
    let tokenResponse = null;

    await msalInstance.getTokenCache().getAllAccounts(); // required for triggering beforeCacheACcess
    tokenResponse = await msalInstance.acquireTokenSilent(silentRequest);

    return tokenResponse;
  }

const [tokenResponse, graphToken] = await Promise.all([
        options.authProvider.getTokenSilent(
          {
            account: req.session.account,
            scopes,
          },
          req.session.id
        ),
        options.authProvider.getTokenSilent(
          {
            account: req.session.account,
            scopes: ['User.Read'],
          },
          req.session.id
        ),
      ]);
```

### Reproduction Steps

Login that seems to fail the most is a guest of the tenant. We're not changing the order of the scopes when requesting so the return shouldn't be out of order.

### Expected Behavior

There shouldn't be 2 claims in the cache.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by konstantin-msft** [comment] 2023-09-11 18:59
Hi @pixeldrew.
Thanks for bringing this to our attention. I have created a bug to track this. Will keep you posted on the progress.

**Comment by cheenamalhotra** [comment] 2023-10-19 02:39
We're also experiencing this error, quite often and noticing a new property 'client_info' showing up sometimes and not always - leading to inconsistent tokens in cache.

```json
    "3e7d7b79-6622-4a75-b22f-d5db22b6978c.72f988bf-86f1-41af-91ab-2d7cd011db47-login.windows.net-accesstoken-a69788c6-1d43-44ed-9ca3-b83e194da255-72f988bf-86f1-41af-91ab-2d7cd011db47-https://database.windows.net/user.read https://database.windows.net/.default": {
      "home_account_id": "3e7d7b79-6622-4a75-b22f-d5db22b6978c.72f988bf-86f1-41af-91ab-2d7cd011db47",
      "environment": "login.windows.net",
      "client_id": "a69788c6-1d43-44ed-9ca3-b83e194da255",
      "secret": "#####",
      "credential_type": "AccessToken",
      "realm": "72f988bf-86f1-41af-91ab-2d7cd011db47",
      "target": "https://database.windows.net/User.Read https://database.windows.net/.default",
      "cached_at": "1697682254",
      "expires_on": "1697687591",
      "extended_expires_on": "1697692929",
      "ext_expires_on": "1697692929"
    },
    "3e7d7b79-6622-4a75-b22f-d5db22b6978c.72f988bf-86f1-41af-91ab-2d7cd011db47-login.windows.net-accesstoken-a69788c6-1d43-44ed-9ca3-b83e194da255-72f988bf-86f1-41af-91ab-2d7cd011db47-https://database.windows.net//user.read https://database.windows.net//.default": {
      "home_account_id": "3e7d7b79-6622-4a75-b22f-d5db22b6978c.72f988bf-86f1-41af-91ab-2d7cd011db47",
      "environment": "login.windows.net",
      "client_info": "######",
      "client_id": "a69788c6-1d43-44ed-9ca3-b83e194da255",
      "secret": "#####",
      "credential_type": "AccessToken",
      "realm": "72f988bf-86f1-41af-91ab-2d7cd011db47",
      "target": "https://database.windows.net//User.Read https://database.windows.net//.default",
      "cached_at": "1697682448",
      "expires_on": "1697687383",
      "extended_expires_on": "1697687383",
      "ext_expires_on": "1697687383"
    },
```
---------

_Edit: v1.16.0 seems to be working fine, we saw issue with v1.18.3. Currently we're sticking to v1.16.0 and will wait for this issue to be fixed soon._

**Comment by bgavrilMS** [comment] 2023-10-19 10:31
@konstantin-msft - are you actually working on this or should I assign someone @Robbie-Microsoft or @trwalke to this?

**Comment by Robbie-Microsoft** [comment] 2023-10-20 21:52
@cheenamalhotra Have you observed this in v2.x?

**Comment by cheenamalhotra** [comment] 2023-10-20 22:45
Tested on a clean cache state, I don't repro this issue with 2.2.0. 
I might have tested with pre-loaded cache with upgraded version before, when I saw it occurring.

Will upgrade to 2.2.0 and continue testing experience.

**Comment by Robbie-Microsoft** [comment] 2023-10-20 23:02
I'm not sure that the scopes being out of order are causing the error, but will look into this more. Additionally, still waiting to hear back from Konstantin. I think he fixed this issue already in [this PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/6311) for 2.x and that it might just need to be backported to 1.x.

**Comment by bgavrilMS** [comment] 2023-10-22 01:10
MSAL libs typically cache tokens using scopes returned by AAD. This is because AAD might issue a tokens with more scopes than requested. E
G. If app requests user.read, aad might issue token for user.read and user.write

By convention, AAD returns the scope list in alphabetical order!

If MSAL js took a dependency o n this convention and aad broke this promise, we should icm AAD to bring back this functionality. At the same time, msal should not rely on this type of weak promise and we shiild fix latest msal. Thoughts @Peter ***@***.***>?



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pmaytak** [comment] 2023-10-23 21:51
Seems like the fix that Robbie linked would fix this issue also. In MSAL.NET we handle this scenario different. We delete [duplicates on save](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/520ef2b9a87bf6cd4b7e6ad46260662f1a2d1189/src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs#L204C25-L204C65), not get, and we [compare on scope set](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/520ef2b9a87bf6cd4b7e6ad46260662f1a2d1189/src/client/Microsoft.Identity.Client/TokenCache.cs#L136). As immediate we can merge this in 1.x.

**Comment by konstantin-msft** [comment] 2023-10-24 19:51
@bgavrilMS @Robbie-Microsoft This is currently a low-priority task, so I am not actively working on it. MSAL.js does not enforce scopes' order at the moment as per AAD spec. Looks like the scopes' order is not always deterministic, so we need to sort them on MSAL.js side. I will make a fix once i get a chance.
Though this [PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/6311) helps to fix the issue, it does not address the root cause. In fact, I did that change to address cache schema incompatibility we discovered after making claims part of the cache schema.

**Comment by Robbie-Microsoft** [comment] 2023-10-24 20:02
Via unit testing, I can confirm that @konstantin-msft's bugfix that was merged into 2.x fixes this issue. So the [PR to backport the bugfix](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/6590) will fix the issue in this PR.

Additionally, I already had the same thought as @konstantin-msft has about sorting the scopes. Via unit testing, I can confirm that the following will also fix the issue in this PR:

Change [this function](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-common/src/cache/entities/CredentialEntity.ts#L174) to:
```
/**
 * Generate target key component as per schema: <target>
 */
private static generateTargetForCacheKey(scopes?: string): string {
    if (!scopes) {
        return Constants.EMPTY_STRING;
    }

    // sort the scopes alphabetically
    return scopes.split(" ").sort().join(" ").toLowerCase();
}
```

Assuming that code I just pasted above exists, [this functionality](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-common/test/client/ClientTestUtils.ts#L68) would prevent the token from ever being stored in the cache more than once. However, that code is just for testing purposes, that functionality would need to be copied to [msal-node's setIdTokenCredential](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-node/src/cache/NodeStorage.ts#L239).

**Comment by pmaytak** [comment] 2023-10-25 05:31
> By convention, AAD returns the scope list in alphabetical order! 

@bgavrilMS Btw, the full scope list is not alphabetical. A subset of app scopes seems sorted, but not the full list. Either way, yes, we shouldn't rely on this assumption.

**Comment by Robbie-Microsoft** [comment] 2023-10-27 22:14
msal-node v1.18.4 has been released and contains the bugfix from the linked PR. @pixeldrew can you let us know if you're still seeing this problem in v1.18.4?

**Comment by pixeldrew** [comment] 2023-10-28 02:07
Sorry, I’m unable to test it as I no longer work on that project.

**Comment by Robbie-Microsoft** [comment] 2023-10-31 17:28
@cheenamalhotra can you let us know if you're still seeing this problem in v1.18.4?

**Comment by cheenamalhotra** [comment] 2023-11-02 00:13
I tested and don't see the error with v1.18.4

**Comment by Robbie-Microsoft** [comment] 2023-11-02 00:27
Will close this issue when the affected customer we're working with tells us the same.

**Closed as completed** 2023-12-01 13:44 UTC
Labels: bug, msal-node, confidential-client
