### ISSUE TITLE
[Msal for Angular] Dynamic configuration

### ISSUE THREAD

**Issue by vogloblinsky** [AzureAD/microsoft-authentication-library-for-js#481] opened 2018-11-13 15:14 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

Is it possible to set the configuration at runtime ?

We are loading for our project the information for the module from a json file loaded during initialization of angular, like in this example (https://juristr.com/blog/2018/01/ng-app-runtime-config/#runtime-configuration)

**Comment by Weschk** [comment] 2018-12-12 15:20
@vogloblinsky I'm hosting my application in Azure and have been struggling with the issue to load the AppSettings and until there is a better way to inject the config I made a workaround using XMLHttpRequest:

```
//Temporary workaround until config configurable 
export function getConfig() {
  var request = new XMLHttpRequest();
  request.open('GET', "/api/settings", false);  // request application settings synchronous
  request.send(null);
  const response = JSON.parse(request.responseText);
  return response as MsalConfig;
}
imports: [
  MsalModule.forRoot(getConfig())
]
```

It's not a pretty solution but at least it works and I can now dynamically load the settings from my web server. 

It would be nice if this feature was implemented so that you could load the settings via APP_INITIALIZER instead.

**Comment by taivu** [comment] 2018-12-14 18:47
@Weschk are you able to make a `--prod` build using that method? I get errors that say `@decorators` cannot run functions to get values

**Comment by Weschk** [comment] 2018-12-17 10:52
@taivu found another solution that works with --prod builds

```
import { MsalModule } from "@azure/msal-angular";
import { MsalService, MsalConfig } from "@azure/msal-angular";
import { MSAL_CONFIG } from "@azure/msal-angular/dist/msal.service";
import { MsalInterceptor } from "@azure/msal-angular/dist/msal.interceptor";

export function getConfig() {
  var request = new XMLHttpRequest();
  request.open('GET', "/api/settings", false);  // request application settings synchronous
  request.send(null);
  const response = JSON.parse(request.responseText);
  return response as MsalConfig;
}
  
@NgModule({
 imports: [
MsalModule
],
 providers: [
    MsalService,
    {
      provide: MSAL_CONFIG,
      useValue: getConfig()
    },
    { 
      provide: HTTP_INTERCEPTORS, 
      useClass: MsalInterceptor, 
      multi: true 
    },
] , 
bootstrap: [AppComponent]
})
```
give it a try if you haven't found a solution =)

**Comment by taivu** [comment] 2018-12-17 16:43
@Weschk prod builds come out working beautifully, thank you!!

**Comment by acarrau** [comment] 2018-12-21 14:10
I appreciate the solution @Weschk! I really expected MSAL to allow runtime configuration. ADAL already had it when initializing the AuthenticationContext

**Comment by acarrau** [comment] 2018-12-28 14:15
The downside of doing a "sync" call like @Weschk mentions, will produce a warning in the console saying XMLHttpRequest synchronous calls are deprecated.

I ended up wrapping the angular bootstrapping in main.ts to be done after the onsuccess of an  XMLHttpRequest to retrieve the configuration file.

**Comment by taivu** [comment] 2018-12-28 15:19
@acarrau can you show some example code? i guess you would bootstrap angular as a callback after XMLHttpRequest success?

**Comment by acarrau** [comment] 2018-12-28 15:40
Yes, exaclty that. I did just by creating a new XMLHttpRequest without the "false" flag in the xhr.open method and in the onsuccess callback starting the 

```
platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.log(err));
```

You can also pass an extra provider to platformBrowserDynamic with a custom injection token to set the configuration value there

**Comment by vogloblinsky** [comment] 2019-01-15 13:33
@acarrau Where do you store your configuratino after the XHR, and how do you pass it to the module ?
Thanks

**Comment by acarrau** [comment] 2019-01-15 14:09
@vogloblinsky In the end I didn't go with this approach and decided to go back to ADAL because of other issues with IE11. I had done it like this:

```
platformBrowserDynamic([{ provide: MY_CONFIGURATION, useValue: config }])
    .bootstrapModule(AppModule)
    .catch(err => console.log(err));
```

MY_CONFIGURATION would be a custom injection token. If I would have to do it I think I would use the plain msal library and create my custom Angular components like HttpInterceptor, AuthorizationService, Guards, etc. This way I could avoid having to do this.

**Comment by taivu** [comment] 2019-01-16 14:17
@vogloblinsky heres whats in my main.ts file:

```
function bootstrapApp() {
  var req = new XMLHttpRequest();

  req.addEventListener('error', (res: any) => {
    console.log('Error: ', res);
  })
  req.addEventListener('load', (res: any) => {
    const appConfig = JSON.parse(res.currentTarget.response);

    platformBrowserDynamic([
      {
        provide: MSAL_CONFIG,
        useValue: appConfig.msalConfig as MsalConfig
      },
      {
        provide: APP_CONFIG_SERVICE_CONFIG,
        useValue: appConfig
      },
    ]).bootstrapModule(AppModule)
      .catch(err => console.error(err));
  });

  req.open('GET', '/assets/config/app-config.json');
  req.send(null);
}

bootstrapApp();
```

im storing my config in an app config module, which i provide to by a custom injection token.

@acarrau what kind of ie11 issues were you having? Its working for me fine in ie. just curious if theres an edge case that i dont know about in ie.

**Comment by acarrau** [comment] 2019-01-16 14:57
I was having this issue:  [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/414](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/414 )

**Comment by infogulch** [comment] 2019-03-12 04:59
I was able to improve @Weschk's solution to work more generally, e.g. for the `window.location` case.  A `useFactory` provider is the key.

Here it is in the most compilable form I could make it with the key parts commented:

```
import { MsalModule, MsalConfig } from '@azure/msal-angular';
import { MsalService } from '@azure/msal-angular';
import { MSAL_CONFIG } from '@azure/msal-angular/dist/msal.service';
import { MsalInterceptor } from '@azure/msal-angular/dist/msal.interceptor';
import { NgModule } from '@angular/core';
import { HTTP_INTERCEPTORS } from '@angular/common/http';

@NgModule({
  imports: [
    MsalModule, // No .forRoot
  ],
  providers: [
    MsalService,  // This is a provider explicitly now
    {
      provide: MSAL_CONFIG,  // MsalService needs config, this provides it.
      useFactory: () => ({   // Note this is an anonymous func that returns the config object
        redirectUri: window.location.origin + '/',
        clientID: 'dc45f87e-4e3d-48aa-9568-aefa6957f29b',
        // other fields here
        example: (console.log('this logs when the page loads, even when compiled with --prod')),
      }),
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
  ],
  bootstrap: [AppComponent],
})
export class AppModule { }
```

**Comment by frjtrifork** [comment] 2019-03-20 09:01
@infogulch 
> I was able to improve @Weschk's solution to work more generally, e.g. for the `window.location` case. A `useFactory` provider is the key.

Hmm, I tried using your example and when I do that I get a null MsalService injected in the services that depend on it. Any idea why?

**Comment by infogulch** [comment] 2019-03-21 01:50
No idea, perhaps it's related to [WindowWrapper](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-angular/src/msal.module.ts) that I didn't manually provide here?  Try providing it, just like the source does.

**Comment by frjtrifork** [comment] 2019-05-20 09:08
> No idea, perhaps it's related to [WindowWrapper](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-angular/src/msal.module.ts) that I didn't manually provide here? Try providing it, just like the source does.

Sorry for my late reply. I got it working now without providing the windowwrapper. I am not sure why it did not work for me the first time around. Thanks for the instructions

**Comment by sameerag** [comment] 2019-06-27 19:53
Link to #786 for traction. Not closing for now until we can evaluate if moving to 1.0.x for Angular will incorporate this change.

**Comment by sameerag** [comment] 2019-06-27 23:36
I believe since msal core 1.0.x supports configuration in a JSON format, this is not too tough to achieve.

**Comment by DarylThayil** [comment] 2019-07-25 22:44
Tracked in #786 closing

**Closed by DarylThayil** 2019-07-25 22:44 UTC
Labels: Feature Request, angular, angularjs, enhancement

**Comment by chrislangston** [comment] 2019-09-02 21:26
> I was able to improve @Weschk's solution to work more generally, e.g. for the `window.location` case. A `useFactory` provider is the key.
> 
> Here it is in the most compilable form I could make it with the key parts commented:
> 
> ```ts
> import { MsalModule, MsalConfig } from '@azure/msal-angular';
> import { MsalService } from '@azure/msal-angular';
> import { MSAL_CONFIG } from '@azure/msal-angular/dist/msal.service';
> import { MsalInterceptor } from '@azure/msal-angular/dist/msal.interceptor';
> import { NgModule } from '@angular/core';
> import { HTTP_INTERCEPTORS } from '@angular/common/http';
> 
> @NgModule({
>   imports: [
>     MsalModule, // No .forRoot
>   ],
>   providers: [
>     MsalService,  // This is a provider explicitly now
>     {
>       provide: MSAL_CONFIG,  // MsalService needs config, this provides it.
>       useFactory: () => ({   // Note this is an arrow fn that returns the config object
>         redirectUri: window.location.origin + '/',
>         clientID: 'dc45f87e-4e3d-48aa-9568-aefa6957f29b',
>         // other fields here
>         example: (console.log('logs on page load, even when compiled with --prod')),
>       }),
>     },
>     {
>       provide: HTTP_INTERCEPTORS,
>       useClass: MsalInterceptor,
>       multi: true,
>     },
>   ],
>   bootstrap: [AppComponent],
> })
> export class AppModule { }
> ```

Hi @infogulch.  If I needed to make an Http Get call to my website serving up my configuration settings or to fetch a .json file, how can I accomplish that using the example you provided?

For example, I see you are returning a configuration object.  I can't seem to figure out the correct behavior inside of this Arrow function to make my get (ie. https://www.mywesite.com/assets/settings.json). I would then parse that file and return it as my setting for the MsalConfig object.

Appreciate any sample you might have.

Thanks,

Chris

**Comment by frjtrifork** [comment] 2019-09-03 07:14
> Hi @infogulch. If I needed to make an Http Get call to my website serving up my configuration settings or to fetch a .json file, how can I accomplish that using the example you provided?
> 
> For example, I see you are returning a configuration object. I can't seem to figure out the correct behavior inside of this Arrow function to make my get (ie. https://www.mywesite.com/assets/settings.json). I would then parse that file and return it as my setting for the MsalConfig object.
> 
> Appreciate any sample you might have.

I am using the same approach as @infogulch - I have not tried fetching a json config, but if it was me I would try to fetch the JSON config in an Angular APP_INITIALIZER that returns a promise which when resolves will persist the parsed json config  somewhere where you can access it from the MSAL_CONFIG useFactory arrow function.

https://angular.io/guide/dependency-injection-providers#predefined-tokens-and-multiple-providers

Not sure if it will work, but that is what I would try out first.

**Comment by chrislangston** [comment] 2019-09-03 10:53
I can’t seem to figure out how to make my Http call using this example.  The case syntax of the Arrow function in this example only shows returning an Object Literal.  Would you happen to have an example of how I could invoke an Http call that fall my .net CORE website that returns the information?

Yes I have I tried the APP-INITIALIZER  technique as you referenced but I couldn’t get that to work.

Appreciate you taking the time to respond.

Thanks,

Chris
7708561528

________________________________

**Comment by kyubisation** [comment] 2019-09-03 12:32
I apologize for intruding.
If you need runtime configuration, maybe [angular-server-side-configuration](https://www.npmjs.com/package/angular-server-side-configuration) might be an option. It allows you to use environment variables to configure your Angular app on server/container startup.
Disclaimer: I am the author of angular-server-side-configuration

**Comment by chrislangston** [comment] 2019-09-03 12:44
> I apologize for intruding.
> If you need runtime configuration, maybe [angular-server-side-configuration](https://www.npmjs.com/package/angular-server-side-configuration) might be an option. It allows you to use environment variables to configure your Angular app on server/container startup.
> Disclaimer: I am the author of angular-server-side-configuration

Hi @kyubisation    Thanks for that suggestion and for putting all that time/effort into your library..  Yes I would love to do Server Side Rendering for our Angular applications.  We are using .NET Core WebApp that serves up the Angular application.

If you can make a complete end-to-end example of how to accomplish this I would love to attempt to integrate that approach into our solution.

**Comment by chrislangston** [comment] 2019-09-03 12:45
> > Hi @infogulch. If I needed to make an Http Get call to my website serving up my configuration settings or to fetch a .json file, how can I accomplish that using the example you provided?
> > For example, I see you are returning a configuration object. I can't seem to figure out the correct behavior inside of this Arrow function to make my get (ie. https://www.mywesite.com/assets/settings.json). I would then parse that file and return it as my setting for the MsalConfig object.
> > Appreciate any sample you might have.
> 
> I am using the same approach as @infogulch - I have not tried fetching a json config, but if it was me I would try to fetch the JSON config in an Angular APP_INITIALIZER that returns a promise which when resolves will persist the parsed json config somewhere where you can access it from the MSAL_CONFIG useFactory arrow function.
> 
> https://angular.io/guide/dependency-injection-providers#predefined-tokens-and-multiple-providers
> 
> Not sure if it will work, but that is what I would try out first.
> 
> UPDATE: I made a small test, and it seems to work (remember to put the APP_INITIALIZER before the MsalService and MSAL_CONFIG provider)
> 
> ```
> let testConfig: any = {
>   bar: 'before initializer'
> };
> 
> export function msalConfigFactory(): MsalConfig {
>   console.log('Returning the msalConfig - testConfig: ', testConfig);
>   return {
>       // msal config object
>   };
> }
> 
> 
> const providers: any[] = [
>   {
>     provide: APP_INITIALIZER,
>     useFactory: () => {
>       return () => {
>         console.log('Starting APP_INITIALIZER'); // Do the fetch of the config here
>         return new Promise((resolve, reject) => {
>           setTimeout(() => {
>             console.log('Resolving APP_INITIALIZER');
>             testConfig.bar = 'after initializer';
>             resolve();
>           }, 5000);
>         });
>       };
>     },
>     multi: true
>   },
>   MsalService,
>   {
>     provide: MSAL_CONFIG, // MsalService needs config, this provides it.
>     useFactory: msalConfigFactory,
>   },
> ```
> 
> On my system the log printed by msalConfigFactory is 'after initializer'.
> Note that you will have to do some extra work in order to avoid the fetch to happen both before and after the Azure redirect since the APP_INITIALIZER will run in both cases. I guess a simple way to handle it could be to put the parsed config in sessionStorage when the fetch resolves, and add a check if you already have the config before fetching it again. If the fetch is fast the 2nd time around due to response caching in the browser, you could also just let it refetch/parse and not use the sessionStorage.
> 
> If that approach does not work for you, you could try fetching the config first, and then effectively delay the Angular bootstrap of your App - like suggested in this comment - [angular/angular#23279 (comment)](https://github.com/angular/angular/issues/23279#issuecomment-394129129)

Thanks @frjtrifork for the example!

**Comment by frjtrifork** [comment] 2019-09-03 13:06
> I can’t seem to figure out how to make my Http call using this example. The case syntax of the Arrow function in this example only shows returning an Object Literal. Would you happen to have an example of how I could invoke an Http call that fall my .net CORE website that returns the information? Yes I have I tried the APP-INITIALIZER technique as you referenced but I couldn’t get that to work. Appreciate you taking the time to respond.

This is working for me.

```
let testConfig: any = {
  bar: 'before initializer'
};

export function msalConfigFactory(): MsalConfig {
  console.log('Returning the msalConfig - testConfig: ', testConfig);
  // TODO: return the config
  return {
      ...
  };
}

const providers: any[] = [
  {
    provide: APP_INITIALIZER,
    useFactory: () => {
      return () => {
        console.log('Starting APP_INITIALIZER');
        // TODO: Do the fetch of the config here
        return fetch('https://jsonplaceholder.typicode.com/todos/1')
          .then(response => {
            const myJsonConfig = response.json();
            // NOTE: I store the fetched config in a variable in a scope where my msalConfigFactory function can access the result - it could also be sessionStorage/somewhere else - this is just an example
            testConfig.bar = myJsonConfig;
            return myJsonConfig;
          })
          .then(json => console.log('Fetched some random json and persisted it in testConfig.bar', json));
      };
    },
    multi: true
  },
  MsalService,
  {
    provide: MSAL_CONFIG, // MsalService needs config, this provides it.
    useFactory: msalConfigFactory,
  },
// ... more providers here

```

When I execute that, I can see that the JSON fetched is printed by the msalConfigFactory, so you should be able to convert what you fetch (if needed), and return it as the configuration.  Is that not working for you?

**Comment by chrislangston** [comment] 2019-09-03 13:55
Hi @frjtrifork 

Thank you for the code example. One thing I've learned from Angular is to ensure I'm always running against production build.  Many times I get different behavior from JIT compiles vs AOT compiles.

My code is running with AOL compiler (ng build --watch --prod --source-map)

Following your example I am not able to see my console.log message being written in the msalConfigFactory(): MsalConfig.

Also, when I attempt to being the actual login process to Azure Active Directory, none of my values are populated for clientID, authority, etc.  These values are null.

Below is my code and console log when I'm running with a production build.

Can you explain what you mean by this comment?  What scope are you talking about saving it into?  Maybe you can demonstrate this?

            // NOTE: I store the fetched config in a variable in a scope where my 
            // msalConfigFactory function can access the result - it could also be
            // sessionStorage/somewhere else - this is just an example

`
let testConfig: any = {
  clientID: '',
  authority: '',
  navigateToLoginRequestUrl: true,
  redirectUri: '',
  level: LogLevel.Verbose
};

export function msalConfigFactory(): MsalConfig {
  console.log('Returning the msalConfig - testConfig', testConfig)  
  return {
    clientID: testConfig.clientID,
    authority: testConfig.authority,
    navigateToLoginRequestUrl: testConfig.navigateToLoginRequestUrl,
    redirectUri: testConfig.redirectUri,
    level: testConfig.level,
    consentScopes: testConfig.consentScopes,
    protectedResourceMap: testConfig.protectedResourceMap,
    unprotectedResources: testConfig.unprotectedResources
  };
}


  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: () => {
        return () => {
          console.log('Starting APP_INITIALIZER')
          //todo:  Do the fetch of the config here.name
          return fetch('/api/clientsettings')
            .then(response => response.json())
            .then(json => {
              console.log('fetched some JSON and persisted to testConfig', json);

              let webApiRootUrl = `${json.webApiEndpointUrl}api/`;

              let consentScopes = [];
              consentScopes[0] = `${json.webApiEndpointUrl}Standards.Admin`;
              consentScopes[1] = `${json.webApiEndpointUrl}Standards.User`;
            
              let protectedResourceMap: [string, string[]][] =
                [
                  [`${webApiRootUrl}sdo/`, [`${consentScopes[0]}`, `${consentScopes[1]}`]],
                  [`${webApiRootUrl}standards/`, [`${consentScopes[0]}`, `${consentScopes[1]}`]],
                  [`${webApiRootUrl}favorites/`, [`${consentScopes[0]}`, `${consentScopes[1]}`]]
                ];
            
              let config = new MsalConfig();
              config.clientID = `${json.clientId}`;
              config.authority = 'https://login.microsoftonline.com/{DOMAIN-NAME}.onmicrosoft.com';
              config.navigateToLoginRequestUrl = true;
              config.redirectUri = `${window.location.origin}/`;
              config.consentScopes = consentScopes;
              config.protectedResourceMap = protectedResourceMap;
              config.unprotectedResources = [`${window.location.origin}/api/clientsettings`];
              config.level = LogLevel.Verbose;            

              testConfig = config;
            })
        }
      }
    },
    MsalService,
    {
      provide: MSAL_CONFIG,
      useValue: msalConfigFactory
    },
    {
      provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true
    }
`

![Auth-Init-](https://user-images.githubusercontent.com/16180977/64178600-c24b2480-ce2f-11e9-999b-8a618d70ba6f.jpg)

**Comment by frjtrifork** [comment] 2019-09-04 07:41
@chrislangston 
regarding the scope I just meant that the testconfig is declared at the top level in the app.module.ts file.

Ah wait, I have this code at the bottom of my App.module.ts to prevent my angular application from reloading when the login succeeds and the token-redirect happens in the hidden frame. 

The code below prevents your App.component from being bootstrapped again after the redirect that contains the login token happens in the msal frame. In that scenario you only want to bootstrap the MsalComponent (and persist the token).

```
...providers, and other settings here
  entryComponents: [...different components, MsalComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
  public ngDoBootstrap(ref: ApplicationRef) {
    if (window !== window.parent && !window.opener) {
      ref.bootstrap(MsalComponent);
    } else {
      ref.bootstrap(AppComponent);
    }
  }
}
```
For an explanation see
 https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-avoid-page-reloads 
and 
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q6-how-to-avoid-page-reloads-when-acquiring-and-renewing-tokens-silently

I have tested both with and without --prod --source-map and it still works for me - based on your console log I guess the only difference between our setups is that you don't have the above reload workaround?

**Comment by chrislangston** [comment] 2019-09-05 15:17
Hi @frjtrifork   You have been so helpful!  I really appreciate you walking through this.

Would it be possible for you to push a small sample Angular solution to a git repo somewhere that I can pull to see all the various interactions?    I'd love to see how you implemented the "prevent reload workaround" inside of your App.module.ts file.  I think this is what is causing my issue below with IE11 (which we must support)

Also we're having problems now using IE11 where the browser will perpetually attempt to make this GET Request until the remote location 


GET https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/authorize?response_type=token&scope=openid%20profile&client_id={APPLICATION_CLIENT_ID}&redirect_uri=https%3A%2F%2F{MY_DOMAIN_NAME}.azurewebsites.net%2F&state=c79d0543-40c0-4413-830a-aee47f76a41a&nonce=662f586e-de28-4f97-9d46-ed73d07e7a7b&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.2&client-request-id={SOME_REQUEST_GUID}&prompt=none&login_hint={USERS_EMAIL_ADDRESS}%40global.{MY_TENANT_DOMAIN}.com&domain_req={TENANT_ID}&login_req={SOME_GUID}&domain_hint=organizations HTTP/1.1


![IE-11-continual-refresh-attempts](https://user-images.githubusercontent.com/16180977/64354942-581cb600-cfce-11e9-9168-0776924ca764.jpg)

**Comment by christo-k** [comment] 2020-02-10 22:38
Apologies for commenting on a closed post but I'm interested in the solution described above while waiting for a new feature to be added to the source.

The problem I'm encountering is that I receive the following runtime error whenever I try to import MsalModule without using .forRoot():

`Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
    at NgModuleProviderAnalyzer.push.../../node_modules/@angular/compiler/fesm5/compiler.js.NgModuleProviderAnalyzer.parse`

I wonder if part of the problem is that I'm using the 1.0.0-beta.2 release of the Msal angular wrapper.

Thanks in advance!

**Comment by jasonnutter** [comment] 2020-02-11 23:48
@christo-k Do you think that #814 addresses that?

**Comment by christo-k** [comment] 2020-02-12 14:02
Upon further review I found that I had the causality wrong - error not
related to the workaround described above. (In fact, I had removed my
comment when I discovered this, but not soon enough!)

Thanks for the message - looking forward to the GA release.
