### ISSUE TITLE
Only one version of refresh token is being used for any scope.

### ISSUE THREAD

**Issue by ratnapraveen** [AzureAD/microsoft-authentication-library-for-js#3726] opened 2021-06-08 13:17 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are using Azure B2C custom policy with a RESTful technical profile to get additional claims. Our SPA uses multiple scopes and access tokens to access the WebAPIs. While generating these tokens silently the MSAL library redeems the refresh token generated in the last token request. However, it is not considering/validating the scope while redeeming the refresh token. Only one version of refresh token is maintained in the cache and same being used for generating the token silently for any scope. This is causing a problem in our application flow as the generated token (claims) doesn’t belong to the requested token. 

Ex: 

1.	Generate access token for _scope1_
     1.	_access_token_scope1_
     1.	_refresh_token_
     1.	Claims in access token
             1.  _scope1_claim1_
             2. _scope2_claim2_

1.	Generate access token for _scope2_ (MSAL uses _refresh_token_ generated in 1ii above)
     1.	_acccess_token_scope2_
     1.	_refresh_token_ (replacing the previous one)
     1.	Claims in access token
             1.	_scope1_claim1_
             2.	_scope2_claim2_

 The step 2 should get claims for scope2 (_scope2_claim1, scope2_claim2_)

I have got following comment from Microsoft support team when raised this with them

_in B2C you cannot exchange a refresh token for another with scope different from the one you got it for. B2C refresh tokens, unlike AAD refresh tokens are single-resource refresh tokens. Unfortunately, OBO flow is not supported in B2C so your only recourse seems to be to trigger another authorization code request and exchange that for a different scope access and refresh token pair_

### Error Message

Generating a token with wrong claims in it.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: <APPLICATION_CLIENT_ID>,
    authority: <AUTHORITY_URL_WITH_POLICY>,
    redirectUri: window.location.origin,
    protocolMode: ProtocolMode.AAD
  },
  cache: {
    cacheLocation: cacheLocation,
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
None
```

### Reproduction Steps

1.	Generate access token for _scope1_
     1.	_access_token_scope1_
     1.	_refresh_token_
     1.	Claims in access token
             1.  _scope1_claim1_
             2. _scope2_claim2_

1.	Generate access token for _scope2_ (MSAL used _refresh_token_ generated in 1a above)
     1.	_acccess_token_scope2_
     1.	_refresh_token_ (replacing the previous one)
     1.	Claims in access token
             1.	_scope1_claim1_
             2.	_scope2_claim2_

 The step 2 should get claims for scope2 (_scope2_claim1, scope2_claim2_)

### Expected Behavior

MSAL should create refresh tokens per scope and redeem it when there is a request for access token for the respective scope. 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment] 2021-06-08 18:29
@ratnapraveen 

>I have got following comment from Microsoft support team when raised this with them
in B2C you cannot exchange a refresh token for another with scope different from the one you got it for. B2C refresh tokens, unlike AAD refresh tokens are single-resource refresh tokens.

This used to be true but has recently changed. B2C refresh tokens can now be redeemed for any previously consented scope similar to AAD. You can verify this yourself by comparing the scopes for the two access tokens.

That said, this does appear to be a bug on the B2C service as they should not be mixing claims. I believe there is a known issue where claims are not refreshed on refresh token redemption. Unfortunately for now your best option is, as suggested by the support engineer you spoke to, to not use the refresh token when switching scopes. You can do this by either calling `ssoSilent` or calling an interactive API: `acquireTokenRedirect` or `acquireTokenPopup`

cc @nickgmicrosoft This should probably be filed as a bug if not already

**Comment by ratnapraveen** [comment] 2021-06-09 08:42
Thank you, @tnorling.

You are right, the B2C service is generating the token with right scope and audience. However, the custom claims added through a REST API claims provider are not related to the scope requested with redeeming a refresh token. I will try to use the other alternatives, but they are obviously not as elegant as silent acquireTokenSilent.

Is there a way I can track the B2C service issue if they have one already?

**Comment by tnorling** [comment] 2021-06-09 16:06
I'm not aware of a public tracker but you can open a support ticket with B2C [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) and they can provide status updates for you. You can reference this issue if they need more context.

**Comment by ratnapraveen** [comment] 2021-06-09 16:08
Thank you @tnorling . I will give it a go.

**Comment by tnorling** [comment] 2021-06-10 22:22
I did follow up with the B2C service team and they said they do have a solution for this and customer support should be able to help you get it enabled. For custom policies it will require some changes to your refresh token user journey and for basic policies they'll need to enable the feature for your tenant.

Closing as there's no further action from MSAL.js needed at this time but please feel free to open a new issue if you have any further questions. Thanks!

**Closed by tnorling** 2021-06-10 22:22 UTC
Labels: Needs: Attention :wave:, answered, b2c, b2c-service, external, msal-browser, question

**Comment by ratnapraveen** [comment] 2021-06-10 22:30
Brilliant!! I will follow-up with the support team. 

Thank you @tnorling.

**Comment by nickgmicrosoft** [comment] 2021-06-11 06:02
To help expand:
1) Today, when a refresh token is redeemed for an access token (regardless if for a different resource or not), aside from expiry/other datetime claims, claims are read directly from the refresh token and included in the access token. That is, information from the directory or from REST calls are not re-fetched. This has been the behavior in both built-in and custom policies.
2) The cause that surfaced this Github issue is the above, existing behavior. It's not unique to redeeming a refresh token for a different resource different from the original. Today, there is no publicly available workaround.
3) As Thomas mentioned, you can contact customer support and they'll help connect you to feature team which can consider adding some preview functionality to your tenant that could address your scenario. We're working on evaluating when and how to make this functionality publicly available. For now, consider it experimental and under preview.

**Comment by ratnapraveen** [comment] 2021-06-11 12:13
Thank you @nickgmicrosoft for the clear explanation.

@tnorling - Looks like I need to fallback to _acquireTokenRedirect_ in case the token is not already available in the cache. Is there any preferred way through which I can restrict MSAL from using  _acquireTokenByRefreshToken_? So, I can call  silent acquire first and then fallback to _acquireTokenRedirect_ if it cannot find the token in the cache.
