### ISSUE TITLE
Hash value cannot be processed because it is empty

### ISSUE THREAD

**Issue by ivantrave** [AzureAD/microsoft-authentication-library-for-js#4573] opened 2022-03-04 17:20 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

The user cannot log in after entering email & password. The login popup gets closed and nothing happens.

After getting the error, that does not happen all times, it's possible to login after clicking the login button again (sometimes, it is needed to click it several times). This intermittence makes it difficult to debug.

I basically followed this tutorial: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react

The Azure AD app in portal.azure.com (Microsoft_AAD_RegisteredApps) was configured with Single Page Application redirect URIs having the URI set matching the one configured in the msal configuration (`auth.redirectUri` property)

![Screenshot 2022-03-04 at 17 17 12](https://user-images.githubusercontent.com/2745404/156810842-30b01503-264a-41c6-a7ec-caa0ecba3cdc.png)

### Error Message

`
error BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://myUrl.com/
`

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: '930b1k1b-...',
    authority: 'https://login.microsoftonline.com/l2cba3e8-...',
    redirectUri: 'https://myUrl.com/'
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
ClientApp instantiation:
---------------------------------------------------------------------
import { PublicClientApplication } from '@azure/msal-browser';
import { MsalProvider } from '@azure/msal-react';
import { msalConfig } from './config';

const msaInstance = new PublicClientApplication(msalConfig);

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={msaInstance}>
      <App />
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
---------------------------------------------------------------------
Signing in:

const { instance } = useMsal();
const navigate = useNavigate();

let signin = () => {
    return instance
      .loginPopup({
       scopes: ['User.Read'],
      })
      .then((response) => {
          setUserData(response);
          navigate('welcomPagePath');
      })
      .catch((e) => {
        console.log('error', e);
      });
};
```

### Reproduction Steps

1. Enter Microsoft email
2. Enter password

### Expected Behavior

The user can log in

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by mpminayo** [comment] 2022-03-07 16:30
Hi, which version of chrome are you using, and did you add any code to the sample? Could you also share a network trace and verbose logs to the email on my github profile?

**Comment by mpminayo** [comment] 2022-03-08 07:53
Could you upgrade to the latest version of MSAL?

**Comment by ivantrave** [comment] 2022-03-09 11:38
> Hi, which version of chrome are you using

I am currently using Version 98.0.4758.109 (Official Build) (arm64)

>  ... and did you add any code to the sample? 

I did not add any particular code to the sample beside the one shared in this ticket

> Could you also share a network trace and verbose logs to the email on my github profile?

I will check if I can gather any log and send them. The popup closes and makes it difficult to get data from it

> Could you upgrade to the latest version of MSAL?

I will try with the new version released. The ticket was created using 1.3.0

Thanks for your feedback and quick support

**Comment by ivantrave** [comment] 2022-03-09 12:21
Not sure if it is related, but it also throws this error sometimes:

<img width="477" height="400" alt="Screenshot 2022-03-09 at 12 07 08" src="https://user-images.githubusercontent.com/2745404/157439066-fab9e82f-49ef-49f9-9b9a-5e1f3ceb259f.png">

This error message is shown after entering the Microsoft account. It does not get to ask you for the password.

No particular error is shown in the console.

I can get to see the following requests:

<img width="451" alt="Screenshot 2022-03-09 at 12 18 33" src="https://user-images.githubusercontent.com/2745404/157440664-c485f9bc-01a1-42e3-86a2-60f899f50e49.png">

But since I get redirected to the error popup, I do not get to inspect them further.

Switching to an incognito tab solves the problem, so I believe it is not related to any error on Microsoft account.

I tried doing a hard refresh and removing cookies and still get the same error.

I am getting this error as I write using the following versions:
* "@azure/msal-browser": "^2.22.1",
* "@azure/msal-react": "^1.3.1",

But I am pretty sure I got this before with older ones

Thanks in advance for any suggestion/feedback.

**Comment by OscarDL** [comment] 2022-03-09 15:37
I am facing this exact issue with Chrome on Android. Using Edge, Chrome or Firefox on Windows 11 works perfectly fine. Below is a video of the issue. While trying to record the first time for this comment, it worked for the first time on my phone, so I gave it another try and the error happened again, which is even more strange.

Either way, it never happens once on all 3 browsers I tried on Windows, but it happens (almost, apparently) everytime on Android. Haven't tested on iOS as I unfortunately can't. It seems really important that this issue gets solved ASAP.

Packages: msal-browser@2.22.0 & msal-react@1.3.1

https://user-images.githubusercontent.com/27915933/157475012-61fc147d-fc51-4e30-a4f8-dda96f146d57.mp4

**Comment by mpminayo** [comment] 2022-03-09 16:24
> I am facing this exact issue with Chrome on Android. Using Edge, Chrome or Firefox on Windows 11 works perfectly fine. Below is a video of the issue. While trying to record the first time for this comment, it worked for the first time on my phone, so I gave it another try and the error happened again, which is even more strange.
> 
> Either way, it never happens once on all 3 browsers I tried on Windows, but it happens (almost, apparently) everytime on Android. Haven't tested on iOS as I unfortunately can't. It seems really important that this issue gets solved ASAP.
> 
> Packages: msal-browser@2.22.0 & msal-react@1.3.1
> 
>  2022-03-09.16-31-17.mp4

Could you share the logs? Try an upgrade to the latest MSAL version and see if it persists.

**Comment by OscarDL** [comment] 2022-03-09 18:39
> Could you share the logs? Try an upgrade to the latest MSAL version and see if it persists.

I've just updated msal-browser to 2.22.1 and the issue persists unfolrtunately. The react-specific package was already on the latest version. Here's the stack trace log below, I'm not sure exactly what logs you're asking me so if something else, let me know so I can help you get those as well :)
Thanks!

PS: You might wonder if it could be tied to me using a self-signed certificate for HTTPS, I also tried without HTTPS (I have both http and https setup in my redirect URIs on the Azure portal) and the error also persists.

[localhost-1646850881167.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8217273/localhost-1646850881167.log)

**Comment by tejaswibm-roposo** [comment] 2022-03-14 08:01
Am facing this same issue on react webapp. Though I have used loginPopup() , still it opens a new tab and then closes by itself. Login is unsuccessful and get this below error message in console.

```
BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://<application-fqdn>/
at BrowserAuthError.AuthError [as constructor] (vendors.59b4d47dd671469824f8.bundle.js:2:227816)
at new BrowserAuthError (vendors.59b4d47dd671469824f8.bundle.js:2:12149)
at Function.BrowserAuthError.createEmptyHashError (vendors.59b4d47dd671469824f8.bundle.js:2:12832)
at vendors.59b4d47dd671469824f8.bundle.js:2:168252
```

Versions -
```
"@azure/msal-browser": "^2.22.1",
"@azure/msal-react": "^1.3.1"
```

not sure what the issue is !! I cannot fetch the network logs since am in a corporate network !

**Comment by tejaswibm-roposo** [comment] 2022-03-14 09:56
Additional question. There is a consideration given in this link -

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4573

I did not understand how this will impact the `popup()` flow.. As of now, my `redirectUri` is configured to the landing page of my react application which has below code -

```
const rootEl = document.getElementById('root');
const msalInstance = new PublicClientApplication(MSAL_CONFIG_TEST);

const render = Component =>
  // eslint-disable-next-line react/no-render-return-value
  ReactDOM.render(
    <MsalProvider instance={msalInstance}>
      <ErrorBoundary>
        <Provider store={store}>
          <div>
            <Component />
          </div>
        </Provider>
      </ErrorBoundary>
    </MsalProvider>,
    rootEl
  );

render(AppComponent);
```

Below is the az-config.

```
import { Configuration } from '@azure/msal-browser';

const TENANT_ID = '<MY_TENANT_ID>';

export const MSAL_CONFIG_PROD: Configuration = {
  auth: {
    clientId: '<MY_CLIENT_ID>',
    authority: `https://login.microsoftonline.com/${TENANT_ID}`,
    redirectUri: 'https://<subdomain>.<domain>.com/',
    postLogoutRedirectUri: 'https://<subdomain>.<domain>.com.com/',
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
    secureCookies: false,
  },
};

export const MSAL_CONFIG_TEST: Configuration = {
  auth: {
    clientId: '<MY_CLIENT_ID>',
    authority: `https://login.microsoftonline.com/${TENANT_ID}`,
    redirectUri: 'http://localhost:9000/',
    postLogoutRedirectUri: 'http://localhost:9000',
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
    secureCookies: false,
  },
};

/**
 * Scopes you add here will be prompted for user consent during sign-in.
 * By default, MSAL.js will add OIDC scopes (openid, profile, email) to any login request.
 * For more information about OIDC scopes, visit:
 * https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
 */
export const loginRequest = {
  scopes: ['User.Read', 'profile', 'openid', 'Directory.Read.All'],
};

/**
 * Add here the scopes to request when obtaining an access token for MS Graph API. For more information, see:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
 */
export const graphConfig = {
  graphMeEndpoint: 'https://graph.microsoft.com/v1.0/me',
};

export default MSAL_CONFIG_PROD;
```

So, all components have `MsalProvider` instance, including landing page post redirect from `popup()` flow. Will this cause an issue ?

If so, what can be done in this case. My application sometimes opens `popup()` and then closes it post login and main window refreshes automatically. 
But intermittently, it opens in new tab instead of `popup()` and throws error 


> Am facing this same issue on react webapp. Though I have used loginPopup() , still it opens a new tab and then closes by itself. Login is unsuccessful and get this below error message in console.
> 
> ```
> BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://<application-fqdn>/
> at BrowserAuthError.AuthError [as constructor] (vendors.59b4d47dd671469824f8.bundle.js:2:227816)
> at new BrowserAuthError (vendors.59b4d47dd671469824f8.bundle.js:2:12149)
> at Function.BrowserAuthError.createEmptyHashError (vendors.59b4d47dd671469824f8.bundle.js:2:12832)
> at vendors.59b4d47dd671469824f8.bundle.js:2:168252
> ```
> 
> Versions -
> 
> ```
> "@azure/msal-browser": "^2.22.1",
> "@azure/msal-react": "^1.3.1"
> ```
> 
> not sure what the issue is !! I cannot fetch the network logs since am in a corporate network !

**Comment by atkinchris** [comment] 2022-03-15 11:45
For me, when the login popup is opened in a popup window, then it succeeds. However, if the login popup is opened in a tab - then it fails with the same error as above (`hash_empty_error`). I find Chrome, running in fullscreen mode on a Mac (rather than just expanded to the display) will open the popup as a tab, rather than a new window - triggering the error.

**Comment by tejaswibm-roposo** [comment] 2022-03-15 12:06
> For me, when the login popup is opened in a popup window, then it succeeds. However, if the login popup is opened in a tab - then it fails with the same error as above (`hash_empty_error`). I find Chrome, running in fullscreen mode on a Mac (rather than just expanded to the display) will open the popup as a tab, rather than a new window - triggering the error.

In my case, for few users irrespective of doing anything, it always opens in new tab.

**Comment by shashankBobbala** [comment] 2022-03-15 17:23
I too facing this issue, my react app is used both in electron and browser. In electron it is working fine but in browser most of the time it returns this error, one difference I observed in both is there is no refresh  for electron so it’s always you close and open and when open it always making  authorization but in browser it’s different. I see in storage, cache hits is incrementing when I see this error. How to overcome this issue. did lot of browsing but no proper solution

**Comment by tejaswibm-roposo** [comment] 2022-03-16 05:13
> I too facing this issue, my react app is used both in electron and browser. In electron it is working fine but in browser most of the time it returns this error, one difference I observed in both is there is no refresh for electron so it’s always you close and open and when open it always making authorization but in browser it’s different. I see in storage, cache hits is incrementing when I see this error. How to overcome this issue. did lot of browsing but no proper solution

only @mpminayo or somebody from msft can comment on this issue now.. Its been faced by many as far as github issues is concerned. Maybe they need to address the issue, or provide FAQ / Sample app to demo how library needs to be used.

**Comment by atkinchris** [comment] 2022-03-17 17:47
We've resolved this in our application. For us, we had our redirect URL as the home page of our application. This caused an issue where our router (in Next.js) took over the routing in the popup, stripping the hash and redirecting it to the login page - before the window that launched the popup had time to extract it. Redirecting to a blank page allowed consistent logins.

These comments and documentation helped:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4550#issuecomment-1058519256
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4456#issuecomment-1046328877
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations

**Comment by tejaswibm-roposo** [comment] 2022-03-18 05:53
> We've resolved this in our application. For us, we had our redirect URL as the home page of our application. This caused an issue where our router (in Next.js) took over the routing in the popup, stripping the hash and redirecting it to the login page - before the window that launched the popup had time to extract it. Redirecting to a blank page allowed consistent logins.
> 
> These comments and documentation helped: [#4550 (comment)](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4550#issuecomment-1058519256) [#4456 (comment)](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4456#issuecomment-1046328877) https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations

@atkinchris - Could you let me know what this `blank.html` should consist of ?? How will this redirect back to my application landing page ?? A sample would be of great help to me as am a newbie to React.

**Comment by atkinchris** [comment] 2022-03-18 09:09
We use the popup login methods. The popup first directs the user to Microsoft, they sign in (or are already signed in) and are then redirected to our `redirectUri` that we've set in both the `PublicClientApplication` config and Azure portal. The URL they're redirected to has a hash appended (`http://your.redirect.url#some-hash-from-microsoft`). The parent window (the one where you created the popup from) reads the hash from the popup's URL, and then closes the popup.

We had our redirect URL set to our application's homepage (i.e. `/`). This meant that, when the popup loaded the page after being redirected back from Microsoft, our application was loaded - including the code that checks if the user is logged in. If the parent window didn't read the hash in time before the application in the popup checked the user's login status, then the hash would be cleared - and our parent application would error, as it couldn't read the hash from the popup. So we had a race between the parent window reading the URL and our application loading - not good!

The solution, as given in docs and issue comments, was to redirect the popup to a blank page.

>Could you let me know what this blank.html should consist of

Not very much, ideally. 😄 It's literally just a page to redirect the popup to; it just needs to be on the same domain as your application, so the parent window can read from it. Here's a (slightly redacted) version of ours:

```html
<html>

<head>
  <title>Blank Page | [Our Application Name]</title>
</head>

<body>
  <!-- This is an intentionally blank page -->
</body>

</html>

```

This page should never be seen by your users. It will flash up quickly just before the popup closes, so having it as minimal as possible will help with performance. It doesn't need to be styled - if anything, having content will confuse users who'll see a momentary flash of content in the popup before its closed for them.

>How will this redirect back to my application landing page

If you're using the popup login, then it never redirects back to your application landing page. You have MSAL in your main application window that a user sees (we'll call this the "parent"). The parent creates the popup, the popup goes to Microsoft, Microsoft redirects back to your blank page, and the parent reads from the popup URL before closing the popup. Your parent window never redirects to Microsoft - but when you're logged in the `AuthenticatedTemplate` will show rather than `UnauthenticatedTemplate`.

**Comment by tejaswibm-roposo** [comment] 2022-03-18 10:04
> We use the popup login methods. The popup first directs the user to Microsoft, they sign in (or are already signed in) and are then redirected to our `redirectUri` that we've set in both the `PublicClientApplication` config and Azure portal. The URL they're redirected to has a hash appended (`http://your.redirect.url#some-hash-from-microsoft`). The parent window (the one where you created the popup from) reads the hash from the popup's URL, and then closes the popup.
> 
> We had our redirect URL set to our application's homepage (i.e. `/`). This meant that, when the popup loaded the page after being redirected back from Microsoft, our application was loaded - including the code that checks if the user is logged in. If the parent window didn't read the hash in time before the application in the popup checked the user's login status, then the hash would be cleared - and our parent application would error, as it couldn't read the hash from the popup. So we had a race between the parent window reading the URL and our application loading - not good!

This part I did understand. Thanks for giving a detailed info.

> The solution, as given in docs and issue comments, was to redirect the popup to a blank page.

React being a SPA, is it even possible to have a url to open up a static html page ? My application entire routes + App components are bound by
```
const rootEl = document.getElementById('root');
const msalInstance = new PublicClientApplication(MSAL_CONFIG_TEST);

const render = Component =>
  // eslint-disable-next-line react/no-render-return-value
  ReactDOM.render(
    <MsalProvider instance={msalInstance}>
      <ErrorBoundary>
        <Provider store={store}>
          <div>
            <Component />
          </div>
        </Provider>
      </ErrorBoundary>
    </MsalProvider>,
    rootEl
  );

render(AppComponent);
```
According to msft docs, this blank route should be outside of the `<MsalProvider />` . Is my understanding correct ? If so, how do we now open a blank.html outside of the SPA 🤔 
> 
> > Could you let me know what this blank.html should consist of
> 
> Not very much, ideally. 😄 It's literally just a page to redirect the popup to; it just needs to be on the same domain as your application, so the parent window can read from it. Here's a (slightly redacted) version of ours:
> 
> ```
> <html>
> 
> <head>
>   <title>Blank Page | [Our Application Name]</title>
> </head>
> 
> <body>
>   
> </body>
> 
> </html>
> ```
> 
> This page should never be seen by your users. It will flash up quickly just before the popup closes, so having it as minimal as possible will help with performance. It doesn't need to be styled - if anything, having content will confuse users who'll see a momentary flash of content in the popup before its closed for them.
> 
> > How will this redirect back to my application landing page
> 
> If you're using the popup login, then it never redirects back to your application landing page. You have MSAL in your main application window that a user sees (we'll call this the "parent"). The parent creates the popup, the popup goes to Microsoft, Microsoft redirects back to your blank page, and the parent reads from the popup URL before closing the popup. Your parent window never redirects to Microsoft - but when you're logged in the `AuthenticatedTemplate` will show rather than `UnauthenticatedTemplate`.

Again appreciate you providing this explanation regarding how MSAL is enabling authentication !! 👍

**Comment by atkinchris** [comment] 2022-03-18 10:10
There'll be a few ways to solve this, depending on your setup and how you want to implement it.

If you're serving your application from a static location, and routing all unmatched resources to `index.html`, add an empty (or nearly empty, as above) `blank.html` alongside your `index.html`.

If you're serving from `nginx` or similar, again add a `blank.html` alongside your `index.html` - and make sure it can be routed to.

If you absolutely cannot ship a `blank.html` file alongside your `index.html`, you'll need to add a "blank" route to your router, likely within your `UnauthenticatedTemplate` or otherwise outside of `AuthenticatedTemplate`.

```
| - /
| --- /some-route-in-your-app
| ------ AuthenticatedTemplate
| ------ UnauthenticatedTemplate
| --- /blank
```

If you're using Create React App, you can place a `blank.html` in your `public` folder. https://create-react-app.dev/docs/using-the-public-folder

**Comment by tejaswibm-roposo** [comment] 2022-03-18 10:31
Am using JHipster to generate my React application. Given the structure of JHipster React App, I have tried to add below snippets -

```
<UnauthenticatedTemplate>
  <Route exact path="/blank">
    <Redirect push to="/blank.html" />
  </Route>
</UnauthenticatedTemplate>
```
This is added inside of `<MsalProvider />` only, since `<Route /> ` cannot be added outside of `Router` and `Router` in-turn is under `<MsalProvider />` only.

I have also tried adding a BlankPage component like below -

```
import React from 'react';
import { Redirect } from 'react-router-dom';

const BlankPage = () => {
  return <Redirect push to={'/blank.html'} />;
};

export default BlankPage;
```

and `blank.html` is same as you have provided and added alongside `index.html`. Webpack is used to generate production ready resources.

Still the issue persists and throws hash error ! 😞

**Comment by atkinchris** [comment] 2022-03-18 10:37
If you navigate to `http://your-application.url/blank.html` does your `blank.html` appear? Does your `blank.html` appear in the build folder that `webpack` writes to, alongside your `index.html`?

**Comment by tejaswibm-roposo** [comment] 2022-03-18 11:52
> If you navigate to `http://your-application.url/blank.html` does your `blank.html` appear? Does your `blank.html` appear in the build folder that `webpack` writes to, alongside your `index.html`?

Yes. When I use `http://your-application.url/blank.html` , it renders on the browser.

**Comment by atkinchris** [comment] 2022-03-18 12:15
Great - then you can set that as your redirect URL in your `PublicClientApplication` config and Azure portal. 🙂

**Comment by tejaswibm-roposo** [comment] 2022-03-18 14:33
> Great - then you can set that as your redirect URL in your `PublicClientApplication` config and Azure portal. 🙂

Seems like its working now.. Still under testing though.. Thanks for your help and valuable feedback !!

**Comment by pkanher617** [comment] 2022-03-21 23:35
@atkinchris's answer above should resolve this issue - thank you for your input. We will update our docs to be more clear that you must either allow MSAL to complete processing before the router, or follow the docs listed and redirect to a blank page. 

Thank you for your help @atkinchris!

**Comment by tejaswibm-roposo** [comment] 2022-03-22 05:21
Yes.. The documentation is provided by msft which states we need to provide a `blank.html` redirect URI. But the samples do not incorporate this. Probably a full scale sample with this recommendation would help or at least a comment on the config values in the sample.

We are getting consistent logins now via `blank.html` redirect uri !

**Comment by ivantrave** [comment] 2022-03-22 11:20
A full scale sample would help a lot

Thanks for your feedback

**Comment by tejaswibm-roposo** [comment] 2022-03-27 14:01
Am getting into a new issue now. The `LOGIN_SUCCESS` callback event is getting triggered many times post login success.
Am not able to figure our why this behaviour. 

Code snippets -
```
const handleLogin = async () => {
    await msalInstance
      .loginPopup(loginRequest)
      .catch(function (error) {
        console.log(error);
      });
  };
```

```
msalInstance.addEventCallback((event: EventMessage) => {
    if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
      const payload = event.payload as AuthenticationResult;
      const account = payload.account;
      instance.setActiveAccount(account);

      console.log("Inside LOGIN_SUCCESS event handler");
      handleResponse(payload); // custom-business logic post login
    }
  });
```

`console.log("Inside LOGIN_SUCCESS event handler");` print 4 times in my case.

code snippets are from the samples provided by Azure only. Nothing new here.

I was able to work around this issue by calling `handleResponse(payload)` from within `then()` block of `loginPopup()`. But this is not the solution though for multiple event callbacks.

**Comment by jasonnutter** [comment] 2022-04-12 16:22
I have seen these a few times in my own testing, and I have theory on why it is happening, will follow up with a fix.

**Comment by bryce-by** [comment] 2022-04-13 01:24
We are getting this "hash_empty_error" error as well. Been trying to resolve it for days now. 

Our React apps are deployed using a very common method (Azure Static Web Apps with GitHub Actions). How would we get this required blank.html page included in this case? Github Actions is building our app so we can't just add a blank.html page into the public folder.

Additionally, how would this play with the [staticwebapp.config.json (Azure SPA Static Web App Docs)](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes) that is required for SPA's?

**Comment by jasonnutter** [comment] 2022-04-13 17:50
@bryce-by A common cause of this is the page used as the redirect uri redirects and/or removes the hash before MSAL has a chance to parse it. When your redirect URI is loaded in a popup with a hash response (i.e. `myapplication.com/redirect#code=`), does your application redirect and/or clear the hash? If so, make it so that it doesn't do that, and for popup/silent requests, you can set your redirect URI to a blank HTML (that does literally nothing). This will help performance and help mitigate this issue.

Note, for redirects (i.e. loginRedirect/acquireTokenRedirect), you cannot use a blank html page for the redirect uri.

**Comment by jasonnutter** [comment] 2022-04-13 17:51
>  Github Actions is building our app so we can't just add a blank.html page into the public folder.

Why not?

**Comment by tejaswibm-roposo** [comment] 2022-04-15 08:31
> I have seen these a few times in my own testing, and I have theory on why it is happening, will follow up with a fix.

Does this relate to multiple `LOGIN_SUCCESS` events getting fired, post login or is this related to Hash error in general ??

**Comment by huzaifah050** [comment] 2022-04-25 10:59
For those who have a fixed for this, please can you create a sample on Codesanbox @tejaswibm-roposo?

**Comment by janekos** [comment] 2022-05-02 11:36
this worked for me. shame on you microsoft for making users have to write hacks like these

```
const runApp = () => {
    ReactDOM.render(
        <App />,
        document.querySelector('body')
    );
};

if (location && location.href.indexOf('<reference to your redirect url>') > -1) {
    setTimeout(runApp, 5000);
}
else {
    runApp();
}
```

**Comment by naveenrk92** [comment] 2022-05-11 11:17
**"Has value cannot be processed because it is empty"**
I see this error due to a recent update in the msal-common package which is being referenced by msal-browser. 
Recent version msal-common is [6.3.0]. msal-browser version should sync with this.
Below is a combination which works :

npm uninstall @azure/msal-common
npm uninstall @azure/msal-browser
npm uninstall @azure/msal-react
npm i @azure/msal-common@6.0.0 
npm i @azure/msal-browser@2.21.0 
npm i @azure/msal-react@1.2.0

**Comment by mebsn** [comment] 2022-05-25 12:09
does any1 knows solution that helps with the same problem but for vue2 project?

i need a little better explanation of that blank.html solution

**Comment by tnorling** [comment] 2022-05-25 15:58
Please see the explanation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a94db43e8b50fd831b82bb4c5a27422c07a63b12/lib/msal-browser/docs/errors.md#hash_empty_error) which will be added to our docs as a part of the linked PR

**Closed as completed** 2022-05-25 17:19 UTC
Labels: bug, msal-browser, msal-react
