### ISSUE TITLE
Infinite redirects after updating to MSAL 1.2.2

### ISSUE THREAD

**Issue by anton-gorbikov** [AzureAD/microsoft-authentication-library-for-js#1505] opened 2020-04-15 21:40 UTC
## Library
- [x] `msal@1.2.2`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular

## Description
After updating to version 1.2.2 from version 1.2.1 acquiring token via redirects flow is broken (this flow is the only possible for Safari/iOS).

## Security
No

## Regression
Yes

I've investigated further and found that this bug can be related to this changes:
https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/d492c3569b69525ca6e820472ddd7b68554e23a6

I see that after each redirect this code deletes `msal.acquireTokenAccount|...` key from the store which causes further problems.

## Configuration
Please provide your MSAL configuration options.

```js
{
	auth: {
		clientId: '{{my-app-id}}',
		authority: 'https://login.microsoftonline.com/{{tenant-id}}.onmicrosoft.com',
		redirectUri: `{{application-login-page}}`,
		navigateToLoginRequestUrl: false
	},
	cache: {
		cacheLocation: 'localStorage',
		storeAuthStateInCookie: true
	},
		system: {
			loadFrameTimeout: 15000
		}
	}
}
```

## Reproduction steps
1. Call `acquireTokenRedirect`
2. Receive token (I can see it in the hash)
3. Try to call `acquireTokenSiliently` to get value from cache
4. Token is not in cache. Acquire token silent fails in browsers which disallow third-party cookies
5. Fallback to `acquireTokenRedirect`, getting infinite loop.

## Expected behavior
A token should be returned after redirects.

## Browsers
Safari or any other browsers with `block third-party cookies` flag enabled.

**Comment by tnorling** [comment] 2020-04-15 23:22
@anton-gorbikov Can you first try upgrading to ```msal@1.3.0-beta.1```? We made some changes to the way msal handles redirects and this update fixed redirect loops other users were experiencing. 

If this doesn't fix your issue, can you clarify in step 2 are you saying that the hash is not being stripped from the URL?

**Comment by sergey-tihon** [comment] 2020-04-16 07:27
We've tried `msal@1.3.0-beta.1` and the issues is still there.

It looks like an issue in new `resetTempCacheItems` function.
- First `acquireTokenRedirect` works correctly, authenticate current user and set `msal|AquireTokenAccount` in local storage
- Then we request auth token for MS Graph and call `acquireTokenSiliently`, it fails because cookies are blocked, so we have to fall-back to `acquireTokenRedirect` to request send token.
- But here it calls `resetTempCacheItems` and remove user token `msal|AquireTokenAccount`, then we have to request it again and jump into infinity loop.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1197905/79426748-440d4e00-7fcc-11ea-8c87-beff0ccb07e8.png">

**Comment by tnorling** [comment] 2020-04-16 23:15
@sergey-tihon Thanks for the additional info. The ```resetTempCacheItems``` is necessary and expected. I am more interested in why ```acquireTokenSilent``` is not picking up the cached token from the first ```acquireTokenRedirect``` call. Can you confirm that ```msal|AcquireTokenAccount``` is being set in local storage after the first redirect call and before the silent call? #1509 seems to be having a similar issue and I think these issues may be related

**Comment by sergey-tihon** [comment] 2020-04-17 15:42
I've reproduces the same behavior in new Edge with disables 3rd party cookies
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1197905/79586730-30500d80-80da-11ea-930d-f79367bd09a2.png">
Here is MSAL console logs between redirects
<img width="1604" alt="Presales_Portal" src="https://user-images.githubusercontent.com/1197905/79586278-8f615280-80d9-11ea-8813-61e09f3db3be.png">

and here is video that shows what happens in local storage (I've removed everything from local storage before the recording)
https://youtu.be/wv5iGU7tZbA

**Comment by tnorling** [comment] 2020-04-17 16:29
@sergey-tihon It is a known issue that ```acquireTokenSilent``` will fail with 3rd party cookies disabled. Unfortunately this is not something we are able to fix at this time. It looks like what is happening here is that the ```acquireTokenRedirect``` call is not caching the token and because of this, in combination with the 3rd party cookies disabled, ```acquireTokenSilent``` is failing, causing your loop. 

```acquireTokenRedirect``` failing to cache the token is something we should look into but in the meantime a potential workaround for you would be not to call ```acquireTokenSilent``` and instead implement your ```handleRedirectCallback``` method to pull the token from the response of calling ```acquireTokenRedirect```. Let me know if you need help with this.

**Comment by sergey-tihon** [comment] 2020-04-17 16:38
Is it known issues of msal 1.2.2+ ? 


Out implementation works as expected with `msal@1.2.1` (in Safari and in Edge with disables 3rd party cookies) but goes into infinite loop when we upgrade to `msal@1.2.2` or `msal@1.3.0-beta.1`.

**Comment by tnorling** [comment] 2020-04-17 16:54
It has always been an issue. You can read an explanation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari) 

I suspect the reason it was working in a previous version was because your ```acquireTokenSilent``` call was merely returning the token acquired from the previous ```acquireTokenRedirect``` call. From the information you have given me it sounds like something changed in 1.2.2 that is preventing ```acquireTokenRedirect``` from caching the token. You can get around this with the workaround I mentioned above. I will also discuss with the team and see if we can figure out what changed and if we can get a patch out. Thanks for bringing this to our attention.

**Comment by HanhNguyenAtChubb** [comment] 2020-04-20 17:27
Here are some behaviors I noticed when Azure redirects back to your site:
1> Local website: msal.id token is set to cookie since storeAuthStateInCookie: true
           this.cookieService.get('msal.idtoken') = id token value
2> Https: msal.idtoken is not set to cookie , please fix msal library so that cookie get set 
  :tthis.cookieService.get('msal.idtoken') = null
3> work around to getId token:
idtoken = window.sessionStorage.getItem(msal.clientid.idtoken); //clientId is your azure clientId

**Comment by tnorling** [comment] 2020-04-21 02:12
@anton-gorbikov @sergey-tihon A fix for this was just merged into dev. It will be included in the next release. Thanks again for bringing this to our attention

**Closed** 2020-04-21 02:12 UTC
Labels: bug
