### ISSUE TITLE
Salesforce integration impossible

### ISSUE THREAD

**Issue by Bartheleway** [AzureAD/microsoft-authentication-library-for-js#4379] opened 2022-01-10 10:36 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

There is a small failure in the process of retrieving cached data.

On our case, we try to integrate on Salesforce environment. Unfortunately for us, Salesforce first load it's own framework which add a kind of proxy to all window API.

This proxy works well with msal apart from one point, this line :
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2f0c4095993f54056acc1b30b52628a9a308cd9e/lib/msal-browser/src/cache/BrowserStorage.ts#L42

It seems that the proxy make the keys of the storage to not be enumerable.

### Error Message

It basically failed to return token using `acquireTokenSilent` with an error of `InteractionRequiredAuthError` which according to documentation should lead to a call to `acquireTokenRedirect` (or Popup).

In this case we have a redirect loop as everytime I try to get the token I got redirected.

### MSAL Configuration

```javascript
{
    auth: {
        clientId: 'someClientId',
        authority: 'https://login.microsoftonline.com/someTenantId',
    },
}
```

### Relevant Code Snippets

```javascript
A bit hard to explain.
```

### Reproduction Steps

(Might only means something for people with Salesforce knowledge)
1. Create a js file and put the source code of https://alcdn.msauth.net/browser/2.21.0/js/msal-browser.min.js
2. Upload the js file as static resource
3. Create a LWC (Lightning Web Component) and import the static resource with `loadScript`
4. Implement `loginRedirect` and `acquireTokenSilent` flow
5. Insert your LWC on a page
6. You will get continuous redirection

### Expected Behavior

Get the token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Source

External (Customer)

**Comment by tnorling** [comment] 2022-01-10 18:48
@Bartheleway 

> It seems that the proxy make the keys of the storage to not be enumerable.

Is this intended behavior by the framework you're using? Unfortunately with something like this, where the proxy behaves differently from the browser APIs it may be difficult for us to support. Even if we fix this line for you now there's no guarantee it won't break somewhere else or break again in the future as it sounds like this is a non-standard implementation. I would suggest reaching out to Salesforce and clarifying if this is a bug on their end.

**Comment by jasonnutter** [comment] 2022-01-11 18:02
> On our case, we try to integrate on Salesforce environment. Unfortunately for us, Salesforce first load it's own framework which add a kind of proxy to all window API.

Is there documentation for this framework (and specifically about this proxy)?

**Comment by Bartheleway** [comment] 2022-01-11 18:31
Hi, unfortunately there is no precise documentation about this. To make a short answer, in Salesforce we run our web components in a secure context where some best pratices are enforced. They call it [LockerService](https://developer.salesforce.com/docs/component-library/tools/locker-service-viewer). They basically have proxied all the known public API, this is working great and it complicates our life regularly.

I don't think having the storage keys to be enumerable is the intended behavior as I can't find any documentation on this.
Using `Object.keys` or `hasOwnProperty` seems more like a weak implementation based on the [official public API of storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage).

Knowing the Salesforce context for a while now, there is 99% chance they will say that it works "as designed" and then will direct me to their "idea exchange" where I will have to wait for community to vote for the bug fix which is a process known to last for around 10-15 years for every idea. So I really hope this fix will make it through here.

**Comment by jasonnutter** [comment] 2022-01-11 18:42
Thanks, found this: https://developer.salesforce.com/docs/component-library/documentation/en/lwc/security_locker_global_access

**Comment by jasonnutter** [comment] 2022-01-11 18:45
I agree with @tnorling though, we'll need to discuss whether to fully support this environment.

**Comment by tnorling** [comment] 2022-01-11 19:21
@Bartheleway I found [this](https://github.com/salesforce/lwsec-docs-mirror/blob/main/packages/%40locker/distortion/docs/distortions.md#distorted-behavior-56) which explicitly calls out `Object.keys(localstorage)` as being supported by Salesforce. It seems Salesforce either has a docs issue or an implementation bug and I suggest bringing it up with them. I'll also point out that MSAL.js [supports the last 2 versions](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-browsers-are-supported-by-msaljs) of major browsers and a select few other environments. Anything not listed there is not currently supported. We'll have a discussion internally about whether or not we should add Salesforce to this list but for now you should discuss with Salesforce how you can make your app work in their environment.

**Comment by Bartheleway** [comment] 2022-01-11 21:12
Indeed I agree they seems to have it documented on Lightning Web component framework. In my case we are running on the aura framework which is a, let's say, previous version.

I will try to open a ticket on their side to see what is the official position. In the meantime I did a custom version of msal with my PR modification and it's working like a charm. Apart from Salesforce having documented the behaviour, the MDN documentation doesn't say that storage interface should be iterable so I wonder if this is really intended on a vanilla js side.

**Comment by jasonnutter** [comment] 2022-01-11 22:30
> the MDN documentation doesn't say that storage interface should be iterable so I wonder if this is really intended on a vanilla js side.

Quite certain this is intended behavior, as the Storage interface is a [Map](https://infra.spec.whatwg.org/#maps) underneath.

**Comment by Bartheleway** [comment] 2022-01-11 22:50
From my point of view underneath implementation shouldn't be source of truth as it might change in the future if not in the spec.

Apart from that I wonder how can we make the proxy to be iterable. I will have more luck if I come with a solution rather than only the issue. Could you provide any help with this ?

**Comment by jasonnutter** [comment] 2022-01-13 22:01
> From my point of view underneath implementation shouldn't be source of truth as it might change in the future if not in the spec.

That is a link to the spec above (and I don't expect it to change).

> Apart from that I wonder how can we make the proxy to be iterable. I will have more luck if I come with a solution rather than only the issue. Could you provide any help with this ?

For this specific issue, we would ask that you get confirmation from Salesforce about the intended behavior for `Objects.keys(localStorage/sessionStorage)`, as their documentation explicitly states it should be supported. We would prefer not to make changes to the library to account for bugs in frameworks like this.

Generally speaking, we are hesitant to properly support this environment (i.e. prioritize bug fixes like this), given the relatively low usage, difficulty in testing, and potentially large number of changes that we would need to make to the library to make it work 100% (I expect there are other parts of the library that aren't working properly like this or are simply not supported, e.g. IndexedDB usage).

**Comment by Bartheleway** [comment] 2022-01-31 16:33
I opened the ticket on Salesforce side today, I will keep you posted with their replies.

Meanwhile, I did some more research and found this :
> It's recommended to use the Web Storage API (setItem, getItem, removeItem, key, length) to prevent the pitfalls associated with using plain objects as key-value stores.
[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API)

The [HTML living standard](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface) spec defines the storage interface like this:
```
interface Storage {
  readonly attribute unsigned long length;
  DOMString? key(unsigned long index);
  getter DOMString? getItem(DOMString key);
  setter undefined setItem(DOMString key, DOMString value);
  deleter undefined removeItem(DOMString key);
  undefined clear();
};
```

**Comment by Bartheleway** [comment] 2022-02-25 13:19
I got an answer from Salesforce, and as expected they say everything is working as expected on their side. They currently don't have a public document explaining it but they will have one (no ETA provided).

Knowing this in addition with my previous comment, could you consider again accepting my PR ?

**Comment by jasonnutter** [comment] 2022-02-26 00:13
> I got an answer from Salesforce, and as expected they say everything is working as expected on their side.

Thanks for the update. So to be clear, they are saying their documentation (which explicitly shows `Object.keys(localStorage)`) is incorrect?

**Comment by jasonnutter** [comment] 2022-02-26 00:15
> Knowing this in addition with my previous comment, could you consider again accepting my PR ?

We will discuss internally and follow up. One concern is that as a team we don't have an easy way to test this environment, and just because we fix this issue doesn't mean there aren't other parts of the library that are broken (either currently or in the future).

**Comment by Bartheleway** [comment] 2022-02-26 08:35
> Thanks for the update. So to be clear, they are saying their documentation (which explicitly shows `Object.keys(localStorage)`) is incorrect?

As I tried to explain before, there are several technologies in Salesforce world. In particular there are 2 front end framework "Aura" and "LWC" (or Lightning Out). The documentation was for LWC and I am in Aura context. It seems they don't have the equivalent of provided documentation for Aura. They said they will add it but they don't know when.

> One concern is that as a team we don't have an easy way to test this environment

We could describe this environment as an environment with strict respect to the storage spec (instead of Salesforce specific framework). And because I successfully wrote some test for this, we could take that as an example and update all tests around storage. Would this be enough to ensure library stability ? And having issues is pretty normal, that's why we have release fix 🤣 even if we try our best to limit them.

**Comment by jasonnutter** [comment] 2022-02-28 17:11
> As I tried to explain before, there are several technologies in Salesforce world. In particular there are 2 front end framework "Aura" and "LWC" (or Lightning Out). The documentation was for LWC and I am in Aura context. It seems they don't have the equivalent of provided documentation for Aura. They said they will add it but they don't know when.

I see, I missed that, apologies for the confusion. That said, we certainly cannot guarantee support for an undocumented environment. 

> We could describe this environment as an environment with strict respect to the storage spec (instead of Salesforce specific framework). And because I successfully wrote some test for this, we could take that as an example and update all tests around storage. Would this be enough to ensure library stability ? And having issues is pretty normal, that's why we have release fix 🤣 even if we try our best to limit them.

Potentially. Our library relies heavily on persistent browser storage (localStorage, sessionStorage, IndexedDB, cookies) and an environment where those are restricted will likely be difficult for us to properly support.

**Comment by Bartheleway** [comment] 2022-02-28 17:54
> Our library relies heavily on persistent browser storage (localStorage, sessionStorage, IndexedDB, cookies) and an environment where those are restricted will likely be difficult for us to properly support.

That's why implementation should be based on specifications more than observations / implementations (`Object.keys(this.sessionStorage)` returning the keys but not documented).

Let say tomorrow we have a new browser that only implement the session storage as described by the HTML living standard and thus does not make it iterable. Would you like this library to work on it or not ?

I'm happy to help updating the tests if you can set your expectations.

**Comment by jasonnutter** [comment] 2022-04-04 21:44
I've checked with the folks who own the HTML standards and `Object.keys(local/sessionStorage)` returning the array of keys is the correct behavior, so we would consider Salesforce's behavior incorrect. Please ask Salesforce to fix this in their framework (feel free to have them contact me if needed). And unfortunately, we would prefer not to accept fixes for unsupported browsers that are not following the standard that our supported browsers follow, especially when we can't guarantee we won't break those environments in the future.

In the meantime, we will look at prioritizing allowing applications to provide custom storage interfaces (#1588) for environments that do not have local/session storage and/or are more constrained that normal browsers. As workaround, you can use in-memory storage, and/or leverage a fork that contains your needed fixes. Apologies for the inconvenience. 

Closing, as no further action at this time.

**Closed as completed by jasonnutter** 2022-04-04 21:44 UTC
Labels: bug, compatibility, external, msal-browser

**Comment by Bartheleway** [comment] 2022-04-04 23:01
@jasonnutter really sad to read this ... Could you provide a link to the HTML standards specification which state this ?
I already know the answer from Salesforce support, "work as designed". It's nearly impossible for the crowd to reach product owner at Salesforce to make a point.
I will use my fork and try to stay up to date until the custom storage interface comes out. Hopefully it will solve my issue for good.

Thanks for looking into this and taking the time to reply.

**Comment by jasonnutter** [comment] 2022-04-06 17:19
https://github.com/whatwg/html/issues/7741
