### ISSUE TITLE
'The "listener" argument must be of type function. Received an instance of Object' during acquireToken

### ISSUE THREAD

**Issue by camer314** [AzureAD/microsoft-authentication-library-for-js#5139] opened 2022-08-28 06:58 UTC
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.12.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I have a nodeJS application and am attempting to implement OBO flow however I immediately run into an issue that seems to be a bug, although given it is fundamental perhaps it has something to do with my setup.

The following code:

const pca = new msal.ConfidentialClientApplication({
  auth: {
      clientId: xxx,
      authority: "https://login.microsoftonline.com/xxx",
      clientSecret: xxx,
      knownAuthorities: ["https://login.microsoftonline.com/xxx"]
  }
});

  const request = {
    scopes: ["xxx"],
    oboAssertion: token
  }

  const response = await pca.acquireTokenOnBehalfOf(request);
  return response.accessToken;

Generates the error:

_**_Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints_**_

However, the root cause of this error is the following exception, thrown from this line:

this.networkInterface.sendGetRequestAsync(this.defaultOpenIdConfigurationEndpoint, options)]

**'The "listener" argument must be of type function. Received an instance of Object'**

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:259:3)
    at ClientRequest.once (node:events:661:3)
    at new ClientRequest (node:_http_client:215:10)
    at Object.request (node:https:353:10)

### Error Message

'The "listener" argument must be of type function. Received an instance of Object'

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
at checkListener (node:events:259:3)
at ClientRequest.once (node:events:661:3)
at new ClientRequest (node:_http_client:215:10)
at Object.request (node:https:353:10)

### Msal Logs

[Sun, 28 Aug 2022 06:48:50 GMT] : @azure/msal-node@1.11.0 : Info - acquireTokenOnBehalfOf called
notebook-server/server/auth.js:17
[Sun, 28 Aug 2022 06:48:50 GMT] : @azure/msal-node@1.11.0 : Verbose - initializeRequestScopes called
notebook-server/server/auth.js:17
[Sun, 28 Aug 2022 06:48:50 GMT] : [3489d97e-e98a-4184-85e0-3a077c0c8b84] : @azure/msal-node@1.11.0 : Verbose - buildOauthClientConfiguration called
notebook-server/server/auth.js:17
[Sun, 28 Aug 2022 06:48:50 GMT] : [3489d97e-e98a-4184-85e0-3a077c0c8b84] : @azure/msal-node@1.11.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/76e3921f-489b-4b7e-9547-9ea297add9b5
notebook-server/server/auth.js:17
[Sun, 28 Aug 2022 06:48:50 GMT] : [3489d97e-e98a-4184-85e0-3a077c0c8b84] : @azure/msal-node@1.11.0 : Verbose - createAuthority called

### MSAL Configuration

```javascript
auth: {
      clientId: clientId,
      authority: "https://login.microsoftonline.com/tenantId",
      clientSecret: clientSecret,
      knownAuthorities: ["https://login.microsoftonline.com/tenantId"]
  },
```

### Relevant Code Snippets

```javascript
See above in description
```

### Reproduction Steps

As per description, just attempting to get a bearer token using acquireTokenOnBehalfOf. It does not seem to get past the point of resolving endpoints

### Expected Behavior

The error that is thrown generically tells me to check the URL is returning the correct endpoints. That URL is fine. The issue is that the code is throwing when attempting to get that URL and then the real error is being masked by the generic one.

Expected behaviour is that the code is able to retrieve endpoints from that valid URL

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by camer314** [comment] 2022-08-28 11:15
Update to this. msal-node@1.9.1 introduced this breaking change (against node 16.16.0)

msal-node@1.9.0 works as expected and all version since are affected.

**Comment by tnorling** [comment] 2022-08-31 19:07
@camer314 I was not able to reproduce this behavior. Can you try our [OBO sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/on-behalf-of) and see if you have the same problem?

Also of note: you should not use `knownAuthorities` for login.microsoftonline.com. The library will handle discovery for "known to Microsoft" authorities.

**Comment by camer314** [comment] 2022-09-01 02:53
You are correct. If I create a new node application and include latest MSAL then it works as expected. It must have something to do with my setup in my other project, possibly because I am mixing msal and adal or something else. But for the purposes of this issue I think it is fine.

**Comment by tnorling** [comment] 2022-09-01 16:32
Great thanks for confirming! Closing as resolved, let us know if you need any further assistance.

**Closed as completed by tnorling** 2022-09-01 16:32 UTC
Labels: question, msal-node, bug-unconfirmed, Needs: Attention :wave:, confidential-client
