### ISSUE TITLE
Cached scopes returning client Id in 0.1.3

### ISSUE THREAD

**Issue by Magrangs** [AzureAD/microsoft-authentication-library-for-js#187] opened 2017-11-13 12:33 UTC
In UserAgentApplication.js line 544 the cached scopes are returning the client id and not the scopes. This means it can never find a match

var cachedScopes = cacheItem.key.scopes.split(" ");

I am using version 0.1.3

It seems to be caused by this line in UserAgentApplication.js

scope = this.clientId; (line 1147)

It means that this check if (Utils_1.Utils.containsScope(cachedScopes, scopes) fails because they will never be equal as:
var scopes = authenticationRequest.scopes;
will not be equal to the client ld

**Comment by rohitnarula7176** [comment] 2017-11-13 19:35
@Magrangs Can you please share logs and and your code snippet. What I need is the code that shows the scopes you are passing for login() followed by the scopes you are passing for clientId.

**Comment by Magrangs** [comment] 2017-11-14 09:08
Please see the code as follows:

```
@Injectable()
export class AuthService {
    private _tenantConfig = {
        tenant: environment.tenant,
        clientID: environment.clientId,
        signUpSignInPolicy: environment.policy,
        b2cScopes: environment.scopes //['https://{{tenant ID redacted}}/spa/read', 'openid'],
    };

    private _authority = environment.authority + this._tenantConfig.tenant + '/' + this._tenantConfig.signUpSignInPolicy;
    private _clientApplication: Msal.UserAgentApplication;

    constructor() {
        const options = {
            redirectUri: window.location.protocol + '//' + window.location.host
        };

        this._clientApplication = new Msal.UserAgentApplication(
            this._tenantConfig.clientID,
            this._authority,
            this.authCallback.bind(this),
            options
        );
    }

    public login(): void {
        this._clientApplication.loginRedirect(this._tenantConfig.b2cScopes);
    }

    public getAuthenticationToken(): Promise<string> {
        return this._clientApplication.acquireTokenSilent(environment.scopes)
            .then(token => {
                return token;
            }).catch(error => {
                return this._clientApplication.acquireTokenPopup(environment.scopes)
                    .then(token => {
                        return Promise.resolve(token);
                    }).catch(innererror => {
                        console.error('Could not retrieve token from popup.', innererror);
                        return Promise.resolve('');
                    });
            });
    }
    .....
```

As you can see the scopes passed into login are the same as those passed into acquireToken...

The issues seems to occur in saveAccessToken in UserAgentApplication where it sets the scope to be the client id and then constructs a new AccessTokenKey.

If you require any more information please let me know.

**Comment by Magrangs** [comment] 2017-11-14 12:49
I think we have resolved this issue by doing this:

`this._clientApplication.acquireTokenSilent([environment.clientId])`

I.e. passing in the client as the only scope in the acquireTokenSilent (seems a bit strange however) and then removing the api/read scope from my scopes array in the environment class:

```
     export const environment = {
        production: false,
        apiUrl: 'http://localhost:49919/api/',
        tenant: '{{tenant id redacted}}',
        clientId: '{{client id redacted}}',
        policy: 'B2C_1A_signup_signinWithAAD',
        scopes: ['openid'],
        authority: 'https://login.microsoftonline.com/te/'
    };
```

**Comment by rohitnarula7176** [comment] 2017-11-17 01:20
@Magrangs By design you only 2 kinds of scopes can be passed to the acquireTokenSilent. Either just the clientID in which case it tries to get an access_token for self or a list of scopes not containing clientID to get access_token for each of them. We also have a B2C sample in the repo which you can use for guidance. Closing this issue for now as it is resolved for you.

**Closed by rohitnarula7176** 2017-11-17 01:20 UTC
