### ISSUE TITLE
UserAgentApplication.getAccount return type is incorrect

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#1529] opened 2020-04-21 11:46 UTC
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/508239004e8752e4446f75c02fa46557334b14e5/lib/msal-core/src/UserAgentApplication.ts#L1718

The correct return type is `Account | null`

**Comment by tnorling** [comment] 2020-04-21 16:14
@snebjorn We do not have ```strictNullChecks``` enabled in msal-core so this is not needed. Are you seeing a specific issue caused by this?

**Comment by tnorling** [comment] 2020-04-21 16:25
@snebjorn We do not have ```strictNullChecks``` enabled in msal-core so this is not needed. Are you seeing a specific issue caused by this?

**Comment by snebjorn** [comment] 2020-04-21 18:04
`const isAuthenticated = !!this.msalService.getAccount();` reports type `true` which is incorrect and will cause "expression is always true" errors later.

I'd suggest to turn it on cause it's my experience that 9/10 js errors are `null` or `undefined` related

**Comment by snebjorn** [comment] 2020-04-21 18:19
Hmm guess there's some issues with a using a library that have `--strictNullChecks false` in an app that have `--strictNullChecks true` as one assumes null and the other doesn't

**Comment by tnorling** [comment] 2020-04-21 18:22
@snebjorn This is in our backlog to do but unfortunately don't have an estimate right now when msal-core may be updated as there are many changes that will need to be made to enable this. Newer libraries, like the upcoming msal-node, will have this enabled from the start. I'm going to close this but you can track #1097 for updates on this.

**Closed by tnorling** 2020-04-21 18:22 UTC
Labels: more-information-needed, question

**Comment by snebjorn** [comment] 2020-04-21 18:35
That's good to know. Happy coding :)
