### ISSUE TITLE
URI Redirection created by service is wrong has # character separator

### ISSUE THREAD

**Issue by masalinas** [AzureAD/microsoft-authentication-library-for-js#1542] opened 2020-04-24 11:31 UTC
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0-beta.5`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 9

## Description
I registered my app in my Azure AD BC with this redirect uri: http://localhost:4200/sample

I configure the MsalModule service authService like this:

```js
auth: {
              clientId: '<CLIENT_ID>',            
              validateAuthority: true,
              redirectUri: "http://localhost:4200/sample",
              postLogoutRedirectUri: "http://localhost:4200/sample",
              navigateToLoginRequestUrl: true,
            },
            cache: {
              cacheLocation: "localStorage",
              storeAuthStateInCookie: true, // set to true for IE 11
            },
            system: {
              logger: new Logger(
                (logLevel, message, piiEnabled) => {
                  console.log(message);
                },
                { level: 3 }
              )
            }
```

When click on login the handler handleRedirectCallback of the service authService is fired, and get the token correctly, but **the redirect uri created is wrong** like this:

```js
http://localhost:4200/sample#id_token=<ID_TOKEN>
```

Noticed that the uri has a # to separate atributes and not ? so it must be

```js
http://localhost:4200/sample?id_token=<ID_TOKEN>
```

So Angular not redirect correctly!

Is possible to configure this uri redirect separator?, is it a bug?

Regards

**Comment by tnorling** [comment] 2020-04-24 16:07
@masalinas Tokens are returned in the form of a hash on the url. This is intended behavior. Can you explain a little more about why this is an issue for you? If you are trying to use a hash routing strategy and this is preventing that, please try ```msal@1.3.0-beta.1``` and ```msal-angular@1.0.0-beta.5```

**Comment by masalinas** [comment] 2020-04-24 16:47
The problem is simple, the redirection URL created by @azure/msal-angular package and loaded in my google chrome after the Azure AD B2C service authorize my account is wrong because is like this. It include the # character to separa the URI from id_token parameter:

     http://localhost:4200#id_token=<TOKEN>

And it must be like this. Including de ? character:

     http://localhost:4200?id_token=<TOKEN>

Regards

**Comment by tnorling** [comment] 2020-04-24 17:37
This is expected behavior and the way that both msal and the service operate. This is not something we can change. If you can explain to me why returning the token in the hash is a problem for you I can provide better guidance.

**Comment by masalinas** [comment] 2020-04-24 17:40
I don’t need to receive the token in URL, request redirection, is possible
avoid that??

**Comment by tnorling** [comment] 2020-04-24 17:45
The token must be returned in the url. When you are redirected to ```http://localhost:4200/sample``` it will include the token in the hash of the url. Here you must initialize msal so that it can process this hash and cache your token for later use. When this is done it will remove the token from the url. Are you saying that the token is not being removed from the url?

**Comment by tnorling** [comment] 2020-04-30 21:17
Let us know if you're still having issues. Closing for now.

**Closed by tnorling** 2020-04-30 21:17 UTC
Labels: angular, more-information-needed, question
