### ISSUE TITLE
TypeScript - @azure/msal-node - accessToken type on AuthenticationResults

### ISSUE THREAD

**Issue by NickLiffen** [AzureAD/microsoft-authentication-library-for-js#3346] opened 2021-03-30 13:01 UTC
## Library
- [x] `@azure/msal-node@1.x.x`

## Description

I am using the latest version of the `@azure/msal-node` module. I have a small typescript lambda that is creating an `accessToken` using the `OAuth 2.0 Client Credentials Grant` flow. 

High level, I import the module:

```
import * as msal from '@azure/msal-node';
```

Setup my config: 

```
  const config = {
    auth: {
      clientId: client_id,
      authority,
      clientSecret: client_secret,
    },
    system: {
      loggerOptions: {
        loggerCallback(loglevel: any, message: any, containsPii: any) {
          core.info(`${loglevel}:${message}:${containsPii} `);
        },
        piiLoggingEnabled: false,
        logLevel: msal.LogLevel.Verbose,
      },
    },
  };
```

Create the App & set scopes:

```
  const cca = new msal.ConfidentialClientApplication(config);

  const clientCredentialRequest = {
    scopes: ['api://xxxx/.default'],
  };
```

I then attempt to deconstruct the accessToken from the request by doing:

```
  try {
    const { accessToken } = await cca.acquireTokenByClientCredential(clientCredentialRequest);
    return accessToken;
  } catch (error) {
   log(error)
  }
}
```

However, I am getting the error:

```
Property 'accessToken' does not exist on type 'AuthenticationResult | null'.
```

On this line:

```
 const { accessToken } = await cca.acquireTokenByClientCredential(clientCredentialRequest);
```

I have tried finding the `@azure/msal-node` types library but I can't find one. 

I have got this working in Vanilla JS, but must admit I am new to TypeScript a little, so this is likely not a bug but on me, where about am I going wrong here, if you don't mind me asking? 

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by sameerag** [comment] 2021-03-30 18:16
@NickLiffen types are included in `msal-node`. My guess is that since `AuthenticationResult` can potentially return null, the deconstruction may not be working as expected here.

Can you please try and test if this works:
```javascript
const result = await cca.acquireTokenByClientCredential(clientCredentialRequest);
if(result) {
    const { accessToken } = result;
} 
...
```

**Comment by sameerag** [comment] 2021-03-30 18:20
We will also try to reproduce this on our end. We also think there could never be a scenario to have `AuthenticationResult` null, and we will get back on this if this needs changes from our end.

**Comment by sameerag** [comment] 2021-04-06 20:45
@NickLiffen Any update? We haven't yet reproduced this, would like to know if this is still happening on your end.

**Comment by NickLiffen** [comment] 2021-04-07 07:50
Hey @sameerag sorry for not responding 🤦 That's on me!

So this doesn't work:

```
const result = await cca.acquireTokenByClientCredential(clientCredentialRequest);
if(result) {
    const { accessToken } = result;
} 
```

However, I got it to work by doing this:

```
const { accessToken } = await cca.acquireTokenByClientCredential(clientCredentialRequest) as AuthenticationResult;
```

However, I don't think this is a perfect solution. I think you are right that `AuthenticationResult` could respond with `null`. . But I don't know a use case where I would have `null`. Shouldn't it just check for type `AuthenticationResult`. If that makes sense? 

So in short, it works, but I think it could be made better 👀 Thoughts? 

Sorry once more for the long response 👍

**Comment by sameerag** [comment] 2021-04-09 19:39
We added `strict null checks` in our code and hence had to support `| null` in cases where it applied. I do think that some of the changes can be refined and possibly remove this for certain return types, but this would need changes in a lot of code. We will take it up eventually and I will mark this as an enhancement in our backlog.

Hopefully we will get to it sooner than later :-)

**Comment by sameerag** [comment] 2021-04-28 17:05
@NickLiffen Closing this issue. We will follow up on strict null checks enhancement, I just do not have a clear timeline at this point. Marked it internally.

**Closed by sameerag** 2021-04-28 17:05 UTC
Labels: enhancement, msal-node
