### ISSUE TITLE
MSAL logout remove account selection page

### ISSUE THREAD

**Issue by skyshine999** [AzureAD/microsoft-authentication-library-for-js#3833] opened 2021-07-06 11:55 UTC
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.14.11

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.14.11

### Description

i am using msal.js library for azure authentication. Due to refresh token timeout issues in msal we thought of implementing session timeout. If user is inactive for 15 mins we do logout but when i do msal.logout() it is showing again account selection. It disturbs seamless logout flow.Is there any possibility to skip account selection while doing logout.

### MSAL Configuration

```javascript
auth: {
    clientId: “XXXXXXXXXXXXXXXXXXXXXX,
    authority:
      "https://login.microsoftonline.com/XXXXXXXXXXXXXXX/“,
    validateAuthority: true,
    postLogoutRedirectUri: redirectUri,
    redirectUri: redirectUri,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
});
```

### Relevant Code Snippets

```javascript
msal.logout()
```

### Reproduction Steps

login with msal.js
logout will show account options

### Expected Behavior

remove account selection page while doing logout

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Regression

not working in any version

### Source

Internal (Microsoft)

**Comment by sameerag** [comment] 2021-07-06 17:06
I think this is by design. `logout` is not supported without select accounts by the service today. @hpsin can clarify if this is coming.

> i am using msal.js library for azure authentication. Due to refresh token timeout issues in msal we thought of implementing session timeout.

Any details on this scenario? May be we can help with an alternative?

**Comment by hpsin** [comment] 2021-07-06 17:53
We have a logout hint coming over the next few months - it will allow the app to silently logout a user.  This fixes a DoS potential, where apps could signout a user entirely without ever knowing who they are or signing them in.

**Comment by skyshine999** [comment] 2021-07-12 07:43
currently i am using msal.js for azure authentication, rarely i get timeout issue. Now i wanted to give a try @azure/msal-react. Is this library completely resolve refresh token timeout issue

**Comment by jasonnutter** [comment] 2021-07-14 16:19
> currently i am using msal.js for azure authentication, rarely i get timeout issue. Now i wanted to give a try @azure/msal-react. Is this library completely resolve refresh token timeout issue

Yes, we expect fewer timeouts when renewing tokens in MSAL.js v2/MSAL React.

**Comment by sameerag** [comment] 2021-07-23 16:36
Closing this. Both the topics discussed in this issue are addressed.

**Closed by sameerag** 2021-07-23 16:36 UTC
Labels: Needs: Author Feedback, answered, bug-unconfirmed, msal-react, msal@1.x, no-issue-activity, question
