### ISSUE TITLE
Sample for SSO between different applications using @azure/msal-angular

### ISSUE THREAD

**Issue by rajithakolan** [AzureAD/microsoft-authentication-library-for-js#2198] opened 2020-08-26 17:20 UTC
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-angular@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

**Comment by technical-boy** [comment] 2020-08-27 17:22
Closing as duplicate of #2177.

**Closed by technical-boy** 2020-08-27 17:22 UTC
Labels: documentation, question
