### ISSUE TITLE
Invalid State MSAL Error

### ISSUE THREAD

**Issue by TPullen21** [AzureAD/microsoft-authentication-library-for-js#519] opened 2018-12-20 10:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version 17.17134
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior
In few EDGE browsers when logging in we get NULL in the URL.

When looking in the MSAL session storage, we get an Invalid State Error key.

## Notes

- This works in IE on the same machine
- Looking at previous issues, it was fixed in 0.2.2 (we are using a later version)
- Even using the suggested work arounds such as adding the login page to trusted sites in IE, it still doesn't work

</code></pre>

**Comment by navyasric** [comment] 2019-01-04 20:13
@TPullen21 Are you are using the latest version (0.2.3) of MSAL.js and are setting the flag `storeAuthStateInCookie` as described [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser#update-fix-available-in-msaljs-023)?

**Comment by dwatty** [comment] 2019-01-06 14:43
I'm seeing this invalid state behavior on 0.2.3 in the latest version of Chrome as well.  

Sometimes it's accompanied by a /null in the address and sometimes it's not.  But in both cases, the console shows an invalid state error.

**Comment by navyasric** [comment] 2019-01-15 00:31
@dwatty We are not able to repro this issue. Can you please share any repro steps or your code snippet?
Also, please try the latest version 0.2.4 to see if it resolved it.

**Comment by navyasric** [comment] 2019-02-13 00:27
Closing this issue due to no new information being provided and unable to reproduce on our end.

**Closed by navyasric** 2019-02-13 00:27 UTC

**Comment by alexantom** [comment] 2020-02-06 18:52
when we store token in cookie, in safari we started seeing  `431 Request Header Fields Too Large safari`

**Comment by jasonnutter** [comment] 2020-02-06 19:33
@alexantom We're aware of issues with cookie length. Cookies are really only needed for IE / old Edge, and should not be needed for Safari.

**Comment by alexantom** [comment] 2020-02-06 20:33
is there  a specific reason `invalid_state_error` happens, this happens in chrome windows, but not able to reproduce the issue every time.

**Comment by jasonnutter** [comment] 2020-02-10 16:38
@alexantom It could happen for a few different reasons. If you are able to determine why they are happening for your scenario, feel free to open a new issue, thanks!

**Comment by AbhaysinghBhosale** [comment] 2020-02-17 13:12
getting the same issue. found `invalid_state_error `in localStorage. unable to find exact reason of this issue.
