### ISSUE TITLE
msal js does not retrieve access tokens from cache when calling acquireTokenSilent

### ISSUE THREAD

**Issue by LastTribunal** [AzureAD/microsoft-authentication-library-for-js#2299] opened 2020-09-16 17:46 UTC
[ ]@azure/msal@1.4
I can see the access token in sessionStorage
 _{"authority":"https://login.microsoftonline.com.... :{"accessToken":"eyJ......_
but no matter what scope is used, a**cquireTokenSilent()** never gets the token from cache.
As a result, developers have to implement their own token refresh mechanisms

Moreover, if a acquireTokenSilent is called consecutively within short intervals, which always fetches the token from Azure multiple times, the entire session is broken, and the user has to log off and log back in...

**Comment by jzelos** [comment] 2020-09-17 13:58
We just upgraded from 1.3.4 and have exactly the same scenario.

**Comment by jzelos** [comment] 2020-09-17 14:10
Just checking and I this has been recorded under https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2238 as well. Its certainly the same for us.

**Comment by jmckennon** [comment] 2020-09-17 21:13
@jzelos That is correct, #2206 plans to address this issue. Users can downgrade to `msal@1.3.2` to mitigate the bug until the fix is in. Closing this as it's effectively a duplicate of #2238, if you see further issues please open a new ticket so we can track accordingly. Thanks!

**Closed by jmckennon** 2020-09-17 21:13 UTC
Labels: bug
