### ISSUE TITLE
msal.interceptor.ts acquireTokenSilent should gracefully fallback to redirect or popup

### ISSUE THREAD

**Issue by lordtct** [AzureAD/microsoft-authentication-library-for-js#1647] opened 2020-05-13 02:34 UTC
## Library
- [X] `@azure/msal-angular@1.x.x`

## Description
Issue: Once the user session has expired and `MsalInterceptor` is being used, API calls to protected resources will yield "`Message: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None`'." This is due to `acquireTokenSilent` being unable to obtain a token "silently" and that there are no fallbacks in the code.

## Suggestion
Ideally, fallback to `acquireTokenRedirect` for Angular applications:
```
err => {
                    if (err instanceof HttpErrorResponse && err.status === 401) {
                        this.auth.clearCacheForScope(token);
                        this.broadcastService.broadcast("msal:notAuthorized", err.message);
                    } else if ((err.errorCode === 'consent_required' || err.errorCode === 'interaction_required' || err.errorCode === 'login_required')) {
                        /* Interactive login is required */
                        this.auth.acquireTokenRedirect({scopes});
                    }
}
                
```

Suggestions are welcome.

**Comment by jasonnutter** [comment] 2020-05-13 16:39
@lordtct I agree that the interceptor should provide built-in error handling, as you describe. For now, a workaround is to invoke one of the interactive methods (e.g. acquireTokenPopup) and perform the http request again.

**Comment by jasonnutter** [comment] 2020-08-25 22:28
Closing as duplicate of #497

**Closed by jasonnutter** 2020-08-25 22:28 UTC
Labels: feature
