### ISSUE TITLE
loginPopup doesn't properly close itself

### ISSUE THREAD

**Issue by dfederm** [AzureAD/microsoft-authentication-library-for-js#174] opened 2017-11-04 05:38 UTC
Using version 0.1.3

**Code:**
```
let microsoftApp = new UserAgentApplication("my-app-id", null, null);
microsoftApp.loginPopup(["openid", "email"])
    .then(idtoken => /* do something with the id token */)
    .catch(error => /* do something with the error */);
```

**Expected behavior:**
A login popup pops up and after the user logs in the pop up closes itself and the `loginPopup` promise resolves (or rejects).

**Actual behavior:**
A login popup pops up and after the user logs in the pop up redirects back to my site in the pop up.

![image](https://user-images.githubusercontent.com/6445614/32402697-30facb86-c0e7-11e7-8cdd-23f5335c9926.png)

**Comment by dfederm** [comment] 2017-11-04 05:56
I think I found a workaround. If I create a `UserAgentApplication` on that redirected page, it closes the popup and works as I expect it to.

It seems like a weird requirement to require the redirect. This is an SPA and I only need the id token (to auth with my application). Both the Google and Facebook JS libraries can handle this scenario without requiring a redirect in the pop up.

**Comment by rohitnarula7176** [comment] 2017-11-06 18:57
@dfederm This is by design. All the tokens we receive are in the form of a redirect response on the redirectURI page and you need an instance of userAgentApplication on that page for MSAL to process that response and close the popup. Closing this issue as this is by design.

**Closed by rohitnarula7176** 2017-11-06 18:57 UTC

**Comment by dfederm** [comment] 2017-11-07 00:44
@rohitnarula7176 that's extremely inconventient. An SPA has to stand up a new endpoint simply to include the msal lib again so it can close itself?

The Google and Facebook JS libraries can do it, why can't msal?

**Comment by volosovich** [comment] 2018-07-25 08:40
I agree with @dfederm it's extremely inconventient.
**What problem do you fix with this design?**
All oAuth providers sent token to promise resolve and close popup. It's default behavior for all SPA's

**Comment by eugeniymatkovskiy** [comment] 2018-07-27 10:02
I encountered the problem to implement this library to my application because of inappropriate behaviour.
It's time consuming due to its inflexibility. I couldn't initialize the library after AJAX request - wtf???
This behaviour is inconsistence with usual flow (like in Google and Facebook), so I have to add some hacks to my application

**Comment by chetanku** [comment] 2018-08-01 14:08
@dfederm how did you fix this problem? new to this, why do we have to create UserAgentApplication again in the redirecte URI? how do we do it?

**Comment by dfederm** [comment] 2018-08-01 14:29
@chetanku my workaround was just to load the entire SPA in the redirect, and the SPA always creates a `UserAgentApplication` at app startup. It's pretty terrible and I only have to do this workaround for MSA log in support; Facebook and Google's libraries work perfectly.

**Comment by chetanku** [comment] 2018-08-01 14:33
@dfederm Thank you so much, this is very weird. Hope Microsoft fixes this soon.

**Comment by volosovich** [comment] 2018-08-07 14:10
wow, it's undocumented behavior.
I need to have  id_token in URL and after create UserAgentApplication I can get access token, save it and close modal.
I think, this information need to be added to MSAL wiki pages.

**Comment by neural22** [comment] 2018-08-30 12:50
This behaviour is absolutely incomprehensible, by definition the authentication process is completed when the token is returned by the service, so why should we need to instantiate an other UserAgentApplication just to avoid cancel operation error closing the popup? It does not make sense at all...

**Comment by jcabrito** [comment] 2018-10-25 09:09
// This is weird but Microsoft login redirects back to the site and expects it to create the object before it closes the popup.
    // See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174
    if (location.hash.includes("id_token")) {
      new UserAgentApplication("4ecf3d26-e844-4855-9158-b8f6c0121b50", null, null);
    }

Where exactly do i need to put this code in reactjs?

**Comment by Ethan-Arrowood** [comment] 2018-11-13 23:29
@jcabrito i added it to my `componentWillMount` on the root react component

**Comment by blindfish3** [comment] 2019-02-01 11:00
Wish I'd found this a few days ago: now the incomprehensible and undocumented behaviour is explained.
+1 to at least document this.

**Comment by russellr86** [comment] 2019-02-07 16:19
instantiating `UserAgentApplication` twice results in the cookie length issue:

#534

**Comment by kroska** [comment] 2019-03-08 15:19
> @chetanku my workaround was just to load the entire SPA in the redirect, and the SPA creates a `UserAgentApplication` at app startup if the hash include "id_token". It's pretty terrible and I only have to do this workaround for MSA log in support; Facebook and Google's libraries work perfectly.
> 
> ```
>     // This is weird but Microsoft login redirects back to the site and expects it to create the object before it closes the popup.
>     // See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174
>     if (location.hash.includes("id_token")) {
>       new UserAgentApplication("4ecf3d26-e844-4855-9158-b8f6c0121b50", null, null);
>     }
> ```

tks!!

**Comment by Danieliverant** [comment] 2019-05-05 14:24
Using Angular 7 - the Angular wrapper not compatible so I have to use the vanilla JS library.
And I'm facing the same issue.

I've created a service guard that do all the authentication process and on success redirect the app (using Angular Router) to the main page.

How can I use @chetanku workaround to close the popup? 
where should I insert the code snippet?

**Comment by Apollinaire** [comment] 2019-05-13 15:50
Not working for me either, on React + msal 1.0.0. I tried the fix suggested above, it did not work. Adding a listener on the popup isn't that hard, and all the other libs do it so it's an expected behaviour and there are plenty of open source examples for the implementation.

**Comment by sameerag** [comment] 2019-05-14 04:08
@Apollinaire Can you please send us the sample code that you have used with your react application? For a native JS application, I have tested and the popup closes by itself. Repro steps can help us understand your issue.

@Danieliverant Is your issue with Angular 7? For angular, we have not yet upgraded our current wrapper with the latest msal 1.0.0, our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) will be soon updated with potential dates. Having said that, if you believe the core msal is causing the issue, please share the sample code and steps to repro,

**Comment by Apollinaire** [comment] 2019-05-14 12:29
I found the issue: so the workaround is actually to create the AuthProvider as a global, and not in React. If you do this it won't work:
```js
class Msal extends React.Component {
  componentWillMount() {
    const authProvider = new UserAgentApplication(msalConfig);
    this.setState({ authProvider })
  }
  render() {
    // ...
  }
}
```
But this setup works:
```js
const authProvider = new UserAgentApplication(msalConfig);
class Msal extends React.Component {
  componentWillMount() {
    this.setState({ authProvider })
  }
  render() {
    // ...
  }
}
```

This still feels like a hack and should not be 'per design'. The good design would be to track the popup's `location` and resolve the promise when the token appears in the hash.
But anyway, the lib does not support `response_type=code` so it's not suitable for me.

**Comment by DarylThayil** [comment] 2019-05-14 17:47
@Apollinaire  thanks for sharing, I think that the setup code you provided that works is not necessarily a hack, but understand the frustration around no set pattern for react. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap
React is on our roadmap, and we hope to have a wrapper that abstracts all of this away.

We are also working on ideas for cleaner ways to resolve popups, but need to do some work to decouple the flows first. Right now the code handling redirect, popup and silent all share some code paths and for us to change one, we first need to separate those code paths.

I know its not a great answer today, but we definitely understand your pain and are working to make things easier moving forward. 
Any thoughts or contributions are appreciated.

**Comment by Apollinaire** [comment] 2019-05-15 07:52
@DarylThayil Thanks for your answer. It's good to know that the maintainers intends to improve for SPAs too.
Do you ever plan on supporting the `authorization_code` too? I think the endpoint V2 supports it: https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-request

**Comment by DarylThayil** [comment] 2019-05-15 22:30
@Apollinaire  we absolutely do. Currently, our plan is that our node.js lib will support it, although that does not help SPA.  We have used the implict flow on the web because of previous recommendations by the Oauth spec , but from what I understand those winds have shifted and auth_code is now safe to use on the web.  This requires some investigation on our end and I don't have a solid answer yet, but do check our roadmap from time to time and we will put it there.

**Comment by oehm-smith** [comment] 2019-05-24 01:17
For the record, in Angular7 app using MSAL I have:

import {Component, OnInit} from '@angular/core';
import {UserAgentApplication} from 'msal';

```
@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
    ngOnInit() {
        console.log(`login component`);
        // necessary - https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174
        new UserAgentApplication(
            {
                auth: {
                    clientId: '0db627a0-1836-45cf-85a6-721354ca5241',
                }
            });
    }
}
```

This component is hit as part of the redirectUri.

**Comment by NateJBeck** [comment] 2019-09-09 16:44
For those using Angular 6+ looking to implement the workaround from @dfederm, my suggestion would be to subscribe to `NavigationStart` Router events in a root level component like `AppComponent`. 

This should eliminate the need to create a separate route just to handle the popup close.

    const MSAL_CONFIG = {
      auth: {
        clientId: 'xxx-xxx-xxx...'
      }
    }

    export class AppComponent {
      constructor(
        private router: Router,
      ) {
        this.router.events.subscribe(event => {
          if (event instanceof NavigationStart) {
            if (location.hash.includes("id_token")) {
              // this will close MS login popup
              new UserAgentApplication(MSAL_CONFIG);
            }
          }
       }
    }

Note: I had timeout issues with the `fetch()` implementation seen in this library's documentation - after I started using Angular's native `HttpClient` (which I prefer anyway) I did not see any more timeouts.

**Comment by theloserbm** [comment] 2019-10-16 12:14
If you need to use access token at some point you'll need to add that as well.

`if (location.hash.includes("id_token") || location.hash.includes("access_token"))`

**Comment by Germain-Italic** [comment] 2019-11-07 01:52
I am closing the popup like this: 

```
if (location.hash.includes("id_token")) {
    open(location, '_self').close()
    window.close()
}
```

Not sure if it's legal, but it works.

**Comment by gauriz** [comment] 2020-07-30 19:04
There's the same issue I'm facing with 'Login with Github' option too!
