### ISSUE TITLE
Allow MSAL Browser temporary cache storage location to be configurable

### ISSUE THREAD

**Issue by nicolaszawada** [AzureAD/microsoft-authentication-library-for-js#4231] opened 2021-11-02 10:20 UTC
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.5

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.19.0

### Description

MSAL uses SessionStorage to temporarily store its authentication state, even though LocalStorage is configured as cache location. After being logged in, LocalStorage is used correctly.

Because of this behavior, we are having issues in Safari on iOS. Our B2C has an external identity provider. When returning from said provider, it is opening a new tab, and because MSAL was using SessionStorage, authentication state is lost.

This results in the user landing on an empty component where nothing is happening...

### MSAL Configuration

```javascript
return new PublicClientApplication({
    auth: {
      clientId: 'ec53373e-be8b-49ef-83cc-7d9449433088',
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: '/redirect',
      postLogoutRedirectUri: '/',
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
```

### Relevant Code Snippets

```javascript
Please read the reproduction steps.
```

### Reproduction Steps

1. Start from angular11-b2c-sample
2. Protect default '/' route with `MsalGuard`
3. Add a 'redirect' route with `MsalRedirectComponent` & set as redirectUri in config
4. `npm start` and set a breakpoint in the `MsalRedirectComponent` constructor
5. Log in and the breakpoint gets hit, the state is saved in SessionStorage, even though we configured LocalStorage
![chrome_2021-11-02_11-12-42](https://user-images.githubusercontent.com/9047816/139828103-ce2714da-01ef-4685-b9b5-b1bf40a756cd.png)
6. Continue from breakpoint, SessionStorage is cleared and MSAL now uses LocalStorage
![chrome_2021-11-02_11-13-10](https://user-images.githubusercontent.com/9047816/139828313-824d5135-4833-4d49-85e3-0beacf43b0d4.png)

![chrome_2021-11-02_11-13-02](https://user-images.githubusercontent.com/9047816/139828324-92871849-4b6a-48c7-a92c-918f74e5a64d.png)

### Expected Behavior

MSAL should always use the LocalStorage when configured, and not temporarily use SessionStorage to store its state.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by nicolaszawada** [comment] 2021-11-02 12:47
Hi, I was going through the source code looking for the cause and I stumbled upon it.
```
private setupTemporaryCacheStorage(cacheLocation: BrowserCacheLocation | string): IWindowStorage<string> {
    switch (cacheLocation) {
        case BrowserCacheLocation.LocalStorage:
        case BrowserCacheLocation.SessionStorage:
            try {
                // Temporary cache items will always be stored in session storage to mitigate problems caused by multiple tabs
                return new BrowserStorage(BrowserCacheLocation.SessionStorage);
            } catch (e) {
                this.logger.verbose(e);
                return this.internalStorage;
            }
        case BrowserCacheLocation.MemoryStorage:
        default:
            return this.internalStorage;
    }
}
```

This code sets up the `BrowserCacheManager` storage. No matter what you configure, Session storage will always be used. What's the particular reason for this? 

By using local storage here, our issue would be fixed.

**Comment by jasonnutter** [comment] 2021-11-02 15:37
@nicolaszawada The behavior you observe is by design, both to properly support multiple tabs (i.e. a user having the same application open in multiple tabs), and to mitigate issues where temporary cache values are not cleared when closing the browser.

>  When returning from said provider, it is opening a new tab, and because MSAL was using SessionStorage, authentication state is lost.

Can you please provide more detail about this behavior? The library expects that a response would be returned in the same tab, as opposed to in a new tab. Are you saying that instead of redirecting the existing tab, the external IDP is opening a new tab?

**Comment by nicolaszawada** [comment] 2021-11-02 15:54
@jasonnutter 
> Are you saying that instead of redirecting the existing tab, the external IDP is opening a new tab?

Exactly. Our external IDP is a government tool. It opens an app to authenticate, and when confirming in the app, the user gets redirected to the browser, but in a **new** tab. So we don't have any control over this behavior.

This is the scenario:
1. Go to Angular app
2. Get redirected to B2C
3. Choose federal IDP
4. Get redirected to federal IDP
5. Choose authenticator app
6. Authenticator app gets opened
7. Confirm in authenticator app
8. Browser opens again but in a new TAB

To solve our use case, it should be possible to configure this. Or do you have any other suggestion how to tackle this?

**Comment by jasonnutter** [comment] 2021-11-02 16:49
@nicolaszawada Interesting, thank you for those details. I'll add to our backlog and discuss with the team about how to address this. In the mean time, this behavior was changed in 2.10.0, so versions of MSAL.js before that should not have this issue.

**Comment by lukemcgregor** [comment] 2023-02-15 20:13
Is there any progress on this. It is stopping single sign out working correctly as when the signout links are opened in an iframe it wont clear session storage in other tabs (or the current one as its an iframe). This feature will only work using cookies or localStorage, session storage has no vector to clear the state across all of your open tabs (for obvious reasons)

**Comment by tnorling** [comment] 2023-04-17 22:51
Thanks for the PR, it has been merged and will be available in the next release. Closing this issue as resolved.

**Closed as completed by tnorling** 2023-04-17 22:51 UTC
Labels: enhancement, b2c, feature, msal-angular, msal-browser, tracked-internally
